import { expect,test } from '@playwright/test';

test('catalog follows the official 175-lesson Merzlyak plan through lesson 43',async({page})=>{
  await page.goto('/');
  await expect(page.getByText('175 уроков в официальном плане')).toBeVisible();
  await expect(page.locator('.course-chapter-group')).toHaveCount(7);
  const lessons=page.locator('.course-lesson-grid > button');
  await expect(lessons).toHaveCount(175);
  await expect(page.locator('.course-lesson-grid > button.is-interactive')).toHaveCount(41);
  await expect(page.locator('.course-lesson-grid > button:not([disabled])')).toHaveCount(43);
  await expect(page.locator('.course-lesson-grid > button.is-control-ready')).toHaveCount(2);
  await expect(lessons.nth(24)).toContainText('Вычитание натуральных чисел');
  await expect(lessons.nth(28)).toContainText('Вычитание натуральных чисел');
  await expect(lessons.nth(29)).toContainText('Числовые и буквенные выражения. Формулы');
  await expect(lessons.nth(30)).toContainText('Числовые и буквенные выражения. Формулы');
  await expect(lessons.nth(31)).toContainText('Числовые и буквенные выражения. Формулы');
  await expect(lessons.nth(32)).toContainText('Контрольная работа № 2');
  await expect(lessons.nth(32)).toBeEnabled();
  await expect(lessons.nth(32)).toHaveClass(/is-control-ready/);
  await expect(lessons.nth(33)).toContainText('Уравнение');
  await expect(lessons.nth(33)).toBeEnabled();
  await expect(lessons.nth(33)).toHaveClass(/is-interactive/);
  await expect(lessons.nth(34)).toContainText('Уравнение');
  await expect(lessons.nth(34)).toBeEnabled();
  await expect(lessons.nth(34)).toHaveClass(/is-interactive/);
  await expect(lessons.nth(35)).toContainText('Уравнение');
  await expect(lessons.nth(35)).toBeEnabled();
  await expect(lessons.nth(35)).toHaveClass(/is-interactive/);
  for(let index=36;index<=42;index+=1){await expect(lessons.nth(index)).toBeEnabled();await expect(lessons.nth(index)).toHaveClass(/is-interactive/)}
  await expect(lessons.nth(38)).toContainText('Виды углов. Измерение углов');
  await expect(lessons.nth(39)).toContainText('Виды углов. Измерение углов');
  await expect(lessons.nth(40)).toContainText('Виды углов. Измерение углов');
  await expect(lessons.nth(41)).toContainText('Виды углов. Измерение углов');
  await expect(lessons.nth(42)).toContainText('Виды углов. Измерение углов');
  await expect(lessons.nth(43)).toContainText('Многоугольники. Равные фигуры');
  await expect(lessons.nth(43)).toBeDisabled();
  await expect(lessons.nth(90)).toContainText('Понятие обыкновенной дроби');
  await expect(lessons.nth(108)).toContainText('Представление о десятичных дробях');
  await expect(lessons.nth(174)).toContainText('Итоговая контрольная работа');
  await expect(page.getByText('Полностью готовы 43 урока.')).toBeVisible();
});