import {expect,test,type Page} from '@playwright/test';

test.use({viewport:{width:1024,height:1366},userAgent:'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});
async function openLesson48(page:Page){await page.goto('/');const chapterTwo=page.locator('.course-chapter-group').nth(1);if(!(await chapterTwo.evaluate(element=>(element as HTMLDetailsElement).open)))await chapterTwo.locator('summary').click();const lesson48=page.getByRole('button',{name:/Открыть урок 48:/});const lesson49=page.locator('.course-lesson-grid > button').nth(48);const lesson50=page.locator('.course-lesson-grid > button').nth(49);const lesson51=page.locator('.course-lesson-grid > button').nth(50);await expect(lesson48).toBeEnabled();await expect(lesson49).toBeEnabled();await expect(lesson50).toBeEnabled();await expect(lesson51).toBeDisabled();await lesson48.click();await page.locator('.lesson-opening-start').click()}
async function jump(page:Page,index:number,id:string){await page.evaluate(({index})=>window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber:48,stageIndex:index}})),{index});await expect(page.locator(`[data-stage-id="${id}"]`)).toBeVisible()}

test('lesson 48 keeps exact constructions, retry gates, persistence and practice stable on iPad',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('mathnikita-mentor-auto-guide','false'));await openLesson48(page);await expect(page.locator('[data-stage-id="l48-mission"] .lesson-controls')).toContainText('Этап 1 из 36');

  await jump(page,5,'l48-protractor-scale-gate');const protractor=page.locator('[data-stage-id="l48-protractor-scale-gate"] .triangle-construction-diagram');await expect(protractor).toHaveAttribute('data-construction-method','sas');await expect(protractor).toHaveAttribute('data-step','1');await expect(protractor).toHaveAttribute('data-protractor-scale','from-right-50');await expect(protractor.locator('[data-construction-ray]')).toHaveCount(2);

  await jump(page,7,'l48-sas-connect-step');const sas=page.locator('[data-stage-id="l48-sas-connect-step"] .triangle-construction-diagram');await expect(sas).toHaveAttribute('data-side-values','3 см|2 см');await expect(sas).toHaveAttribute('data-angle-values','50');await expect(sas.locator('[data-construction-segment]')).toHaveCount(3);const sasGeometry=await sas.evaluate(node=>{const line=(name:string)=>node.querySelector<SVGLineElement>(`[data-construction-segment="${name}"]`)!;const length=(element:SVGLineElement)=>Math.hypot(Number(element.getAttribute('x2'))-Number(element.getAttribute('x1')),Number(element.getAttribute('y2'))-Number(element.getAttribute('y1')));const ab=line('AB');const ac=line('AC');const abVector=[Number(ab.getAttribute('x2'))-Number(ab.getAttribute('x1')),Number(ab.getAttribute('y2'))-Number(ab.getAttribute('y1'))];const acVector=[Number(ac.getAttribute('x2'))-Number(ac.getAttribute('x1')),Number(ac.getAttribute('y2'))-Number(ac.getAttribute('y1'))];const cosine=(abVector[0]*acVector[0]+abVector[1]*acVector[1])/(Math.hypot(...abVector)*Math.hypot(...acVector));return{ratio:length(ab)/length(ac),angle:Math.acos(cosine)*180/Math.PI}});expect(sasGeometry.ratio).toBeCloseTo(1.5,2);expect(sasGeometry.angle).toBeCloseTo(50,1);

  await jump(page,18,'l48-example2-complete');const asa=page.locator('[data-stage-id="l48-example2-complete"] .triangle-construction-diagram');await expect(asa).toHaveAttribute('data-construction-method','asa');await expect(asa).toHaveAttribute('data-step','4');await expect(asa).toHaveAttribute('data-angle-values','40|110|30');await expect(asa.locator('[data-construction-ray]')).toHaveCount(2);await expect(asa.locator('[data-intersection-marker="true"]')).toHaveCount(1);

  await jump(page,13,'l48-source350-3');const equalSas=page.locator('[data-stage-id="l48-source350-3"] .triangle-construction-diagram');await expect(equalSas).toHaveAttribute('data-classification','остроугольный равнобедренный');await expect(equalSas.locator('[data-equal-side-mark]')).toHaveCount(2);
  await jump(page,26,'l48-source350-7');const rightIsosceles=page.locator('[data-stage-id="l48-source350-7"] .triangle-construction-diagram');await expect(rightIsosceles).toHaveAttribute('data-angle-values','45|45|90');await expect(rightIsosceles.locator('[data-right-angle-marker="true"]')).toHaveCount(1);await expect(rightIsosceles.locator('[data-equal-side-mark]')).toHaveCount(2);
  await jump(page,27,'l48-source350-8');await expect(page.locator('[data-stage-id="l48-source350-8"] [data-equal-side-mark]')).toHaveCount(3);
  await jump(page,30,'l48-source352');await expect(page.locator('[data-stage-id="l48-source352"] [data-point-on-side="true"]')).toHaveCount(1);

  await jump(page,2,'l48-sas-order-gate');const retry=page.locator('[data-stage-id="l48-sas-order-gate"]');for(let attempt=0;attempt<2;attempt+=1){await retry.getByRole('button',{name:'Три длины → сложить',exact:true}).click();await retry.locator('.check-button').click();await expect(retry.locator('.instant-feedback.bad')).toBeVisible()}await expect(retry.locator('.lesson-controls .primary')).toBeEnabled();await expect(retry.locator('.instant-feedback.bad')).toContainText('Можно перейти дальше');

  await jump(page,23,'l48-source350-4');const textbook=page.locator('[data-stage-id="l48-source350-4"]');await textbook.locator('.inline-answer input').fill('80°');await textbook.locator('.check-button').click();await expect(textbook.locator('.instant-feedback.good')).toBeVisible();await textbook.locator('.inline-answer input').fill('81');await expect(textbook.locator('.instant-feedback')).toHaveCount(0);await expect(textbook.locator('.lesson-controls .primary')).toBeDisabled();await expect.poll(async()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-48-progress-v1')??'null')?.results?.['l48-p16'])).toBe(false);await textbook.locator('.inline-answer input').fill('80');await textbook.locator('.check-button').click();await expect(textbook.locator('.instant-feedback.good')).toBeVisible();await textbook.locator('.lesson-controls .primary').click();
  await page.getByRole('button',{name:/Все уроки/}).click();await page.getByRole('button',{name:/Открыть урок 48:/}).click();await page.locator('.lesson-opening-start').click();await expect(page.locator('[data-stage-id="l48-source350-5"]')).toBeVisible();const collapsed=page.locator('.cat-mentor-collapsed');await expect(collapsed).toBeVisible();await collapsed.click();await expect(page.locator('.cat-mentor-actions button')).toHaveCount(4);

  await jump(page,33,'l48-source357');await expect(page.locator('[data-stage-id="l48-source357"]')).toContainText('74 768 + 25 232');await expect(page.locator('[data-stage-id="l48-source357"]')).toContainText('101 230 − 45 675');
  await jump(page,35,'l48-summary');await expect(page.locator('.lesson-reflection')).toBeVisible();await expect(page.locator('.extended-practice[data-practice-task="l48-extra-01"]')).toBeVisible();await expect(page.locator('.practice-pythagoras-actions button')).toHaveCount(4);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2)
});
