import {expect,test,type Page} from '@playwright/test';

test.use({viewport:{width:1024,height:1366},userAgent:'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});

async function openLesson45(page:Page){await page.goto('/');const chapterTwo=page.locator('.course-chapter-group').nth(1);if(!(await chapterTwo.evaluate(element=>(element as HTMLDetailsElement).open)))await chapterTwo.locator('summary').click();const lesson45=page.getByRole('button',{name:/Открыть урок 45:/});const lesson46=page.locator('.course-lesson-grid > button').nth(45);await expect(lesson45).toBeVisible();await expect(lesson45).toBeEnabled();await expect(lesson46).toBeDisabled();await lesson45.click();await expect(page.locator('.lesson-opening')).toContainText('Многоугольники: строим');await page.locator('.lesson-opening-start').click()}
async function jump(page:Page,index:number,id:string){await page.evaluate(({index})=>window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber:45,stageIndex:index}})),{index});await expect(page.locator(`[data-stage-id="${id}"]`)).toBeVisible()}
async function actualSelfCrosses(page:Page){return page.locator('[data-stage-id="l45-builder"] .polygon-builder').evaluate(root=>{const lines=[...root.querySelectorAll<SVGLineElement>('[data-construction-edge]')].map(line=>({x1:Number(line.getAttribute('x1')),y1:Number(line.getAttribute('y1')),x2:Number(line.getAttribute('x2')),y2:Number(line.getAttribute('y2'))}));const ccw=(a:number[],b:number[],c:number[])=>(c[1]-a[1])*(b[0]-a[0])>(b[1]-a[1])*(c[0]-a[0]);const cross=(a:{x1:number;y1:number;x2:number;y2:number},b:{x1:number;y1:number;x2:number;y2:number})=>ccw([a.x1,a.y1],[b.x1,b.y1],[b.x2,b.y2])!==ccw([a.x2,a.y2],[b.x1,b.y1],[b.x2,b.y2])&&ccw([a.x1,a.y1],[a.x2,a.y2],[b.x1,b.y1])!==ccw([a.x1,a.y1],[a.x2,a.y2],[b.x2,b.y2]);for(let i=0;i<lines.length;i+=1){for(let j=i+1;j<lines.length;j+=1){if(j===i+1||(i===0&&j===lines.length-1))continue;if(cross(lines[i],lines[j]))return true}}return false})}

test('lesson 45 keeps real polygon construction, persistence, diagonals, Pythagoras and practice stable on iPad',async({page})=>{await page.addInitScript(()=>localStorage.setItem('mathnikita-mentor-auto-guide','false'));await openLesson45(page);await expect(page.locator('[data-stage-id="l45-mission"]')).toBeVisible();await expect(page.locator('.lesson-runtime:not([hidden]) .lesson-controls')).toContainText('Этап 1 из 36');
  await jump(page,3,'l45-builder');const builder=page.locator('[data-stage-id="l45-builder"]');for(const vertex of ['C','B','D','E'])await builder.getByRole('button',{name:`Вершина ${vertex}`,exact:true}).click();await expect(builder.locator('.polygon-builder')).toHaveAttribute('data-builder-crossing','true');expect(await actualSelfCrosses(page),'A-C-B-D-E must geometrically self-intersect').toBeTruthy();await expect(builder.locator('.lesson-controls .primary')).toBeDisabled();await builder.getByRole('button',{name:'Сбросить',exact:true}).click();for(const vertex of ['B','C','D','E'])await builder.getByRole('button',{name:`Вершина ${vertex}`,exact:true}).click();await expect(builder.locator('.polygon-builder')).toHaveAttribute('data-builder-valid','true');expect(await actualSelfCrosses(page),'A-B-C-D-E must be a simple polygon').toBeFalsy();await expect(builder.locator('[data-construction-edge]')).toHaveCount(5);await expect(builder.locator('.lesson-controls .primary')).toBeEnabled();await builder.locator('.lesson-controls .primary').click();await expect(page.locator('[data-stage-id="l45-practice1"]')).toBeVisible();
  const p1=page.locator('[data-stage-id="l45-practice1"]');await p1.getByRole('button',{name:'Контур замкнут и несоседние стороны не пересекаются',exact:true}).click();await p1.locator('.check-button').click();await expect(p1.locator('.instant-feedback.good')).toBeVisible();await p1.locator('.lesson-controls .primary').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-45-progress-v1')??'null'));expect(saved?.stageIndex).toBe(5);expect(saved?.results?.['l45-p1']).toBe(true);expect(saved?.results?.['l45-builder']).toBe(true);expect(saved?.builderOrder).toEqual(['A','B','C','D','E']);
  await page.getByRole('button',{name:/Все уроки/}).click();await page.getByRole('button',{name:/Открыть урок 45:/}).click();await page.locator('.lesson-opening-start').click();await expect(page.locator('[data-stage-id="l45-side-diagonal-model"]')).toBeVisible();await jump(page,7,'l45-from-one-model');await expect(page.locator('[data-stage-id="l45-from-one-model"] [data-origin-diagonal]')).toHaveCount(2);const collapsed=page.locator('.cat-mentor-collapsed');await expect(collapsed).toBeVisible();await collapsed.click();await expect(page.locator('.cat-mentor-panel')).toBeVisible();await expect(page.locator('.cat-mentor-actions button')).toHaveCount(4);
  await jump(page,35,'l45-summary');await expect(page.locator('.lesson-reflection')).toHaveCount(1);await expect(page.locator('.extended-practice')).toHaveCount(1);await expect(page.locator('.extended-practice[data-practice-task="l45-extra-01"]')).toBeVisible();const practice=page.locator('.extended-practice');await practice.locator('.extended-practice-options').getByRole('button',{name:'AC',exact:true}).click();await practice.locator('.extended-practice-check').click();await expect(practice.locator('.extended-practice-feedback.is-correct')).toBeVisible();await expect(practice.locator('.practice-pythagoras-actions button')).toHaveCount(4);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2)});
