import {expect,test,type Page} from '@playwright/test';

test.use({viewport:{width:1024,height:1366},userAgent:'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});

async function openLesson44(page:Page){await page.goto('/');const chapterTwo=page.locator('.course-chapter-group').nth(1);if(!(await chapterTwo.evaluate(element=>(element as HTMLDetailsElement).open)))await chapterTwo.locator('summary').click();const lesson44=page.getByRole('button',{name:/Открыть урок 44:/});const lesson45=page.getByRole('button',{name:/Открыть урок 45:/});await expect(lesson44).toBeVisible();await expect(lesson44).toBeEnabled();await expect(lesson45).toBeEnabled();await lesson44.click();await expect(page.locator('.lesson-opening')).toContainText('Многоугольники: граница');await page.locator('.lesson-opening-start').click()}
async function jump(page:Page,index:number,id:string){await page.evaluate(({index})=>window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber:44,stageIndex:index}})),{index});await expect(page.locator(`[data-stage-id="${id}"]`)).toBeVisible()}

test('lesson 44 keeps polygon geometry, persistence, Pythagoras and practice stable on iPad',async({page})=>{await page.addInitScript(()=>localStorage.setItem('mathnikita-mentor-auto-guide','false'));await openLesson44(page);await expect(page.locator('[data-stage-id="l44-mission"]')).toBeVisible();await expect(page.locator('.lesson-runtime:not([hidden]) .lesson-controls')).toContainText('Этап 1 из 36');
  const geometry=await page.locator('[data-stage-id="l44-mission"] .polygon-diagram').evaluate(root=>{const lines=[...root.querySelectorAll<SVGLineElement>('[data-crossing-edge]')].map(line=>({x1:Number(line.getAttribute('x1')),y1:Number(line.getAttribute('y1')),x2:Number(line.getAttribute('x2')),y2:Number(line.getAttribute('y2'))}));const points=(root.querySelector('[data-shape="valid"] polygon')?.getAttribute('points')??'').trim().split(/\s+/).map(pair=>pair.split(',').map(Number));const ccw=(a:number[],b:number[],c:number[])=>(c[1]-a[1])*(b[0]-a[0])>(b[1]-a[1])*(c[0]-a[0]);const cross=(a:{x1:number;y1:number;x2:number;y2:number},b:{x1:number;y1:number;x2:number;y2:number})=>ccw([a.x1,a.y1],[b.x1,b.y1],[b.x2,b.y2])!==ccw([a.x2,a.y2],[b.x1,b.y1],[b.x2,b.y2])&&ccw([a.x1,a.y1],[a.x2,a.y2],[b.x1,b.y1])!==ccw([a.x1,a.y1],[a.x2,a.y2],[b.x2,b.y2]);let validSelfCrosses=false;for(let i=0;i<points.length;i+=1){for(let j=i+1;j<points.length;j+=1){if(j===i+1||(i===0&&j===points.length-1))continue;const a={x1:points[i][0],y1:points[i][1],x2:points[(i+1)%points.length][0],y2:points[(i+1)%points.length][1]};const b={x1:points[j][0],y1:points[j][1],x2:points[(j+1)%points.length][0],y2:points[(j+1)%points.length][1]};if(cross(a,b))validSelfCrosses=true}}return{invalidCrosses:lines.length===2&&cross(lines[0],lines[1]),validSelfCrosses}});expect(geometry.invalidCrosses).toBeTruthy();expect(geometry.validSelfCrosses).toBeFalsy();
  await jump(page,3,'l44-practice1');const p1=page.locator('[data-stage-id="l44-practice1"]');await p1.getByRole('button',{name:'Замкнутая ломаная без самопересечений',exact:true}).click();await p1.locator('.check-button').click();await expect(p1.locator('.instant-feedback.good')).toBeVisible();await p1.locator('.lesson-controls .primary').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-44-progress-v1')??'null'));expect(saved?.stageIndex).toBe(4);expect(saved?.results?.['l44-p1']).toBe(true);
  await page.getByRole('button',{name:/Все уроки/}).click();await page.getByRole('button',{name:/Открыть урок 44:/}).click();await page.locator('.lesson-opening-start').click();await expect(page.locator('[data-stage-id="l44-counterexample"]')).toBeVisible();await jump(page,8,'l44-elements');await expect(page.locator('[data-stage-id="l44-elements"] [data-vertex-index]')).toHaveCount(4);const collapsed=page.locator('.cat-mentor-collapsed');await expect(collapsed).toBeVisible();await collapsed.click();await expect(page.locator('.cat-mentor-panel')).toBeVisible();await expect(page.locator('.cat-mentor-actions button')).toHaveCount(4);
  await jump(page,35,'l44-summary');await expect(page.locator('.lesson-reflection')).toHaveCount(1);await expect(page.locator('.extended-practice')).toHaveCount(1);await expect(page.locator('.extended-practice[data-practice-task="l44-extra-01"]')).toBeVisible();const practice=page.locator('.extended-practice');await practice.locator('.extended-practice-options').getByRole('button',{name:'Замкнутая ломаная без самопересечений',exact:true}).click();await practice.locator('.extended-practice-check').click();await expect(practice.locator('.extended-practice-feedback.is-correct')).toBeVisible();await expect(practice.locator('.practice-pythagoras-actions button')).toHaveCount(4);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2)});
