import {expect,test,type Page} from '@playwright/test';
async function open142(page:Page){await page.goto('/');const button=page.locator('button[aria-label^="Открыть урок 142:"]');await expect(button).toBeEnabled();await button.evaluate((node:HTMLButtonElement)=>node.click());await expect(page.getByText('Урок 142 из 175')).toBeVisible();await page.locator('.lesson-opening-start').evaluate((node:HTMLButtonElement)=>node.click());await expect(page.locator('.control-eight-page')).toBeVisible()}
async function reopen142(page:Page){await page.reload();const button=page.locator('button[aria-label^="Открыть урок 142:"]');await expect(button).toBeEnabled();await button.evaluate((node:HTMLButtonElement)=>node.click());await page.locator('.lesson-opening-start').evaluate((node:HTMLButtonElement)=>node.click());await expect(page.locator('.control-eight-page')).toBeVisible()}
async function jump(page:Page,index:number){await page.evaluate(stageIndex=>window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber:142,stageIndex}})),index)}
const stageValues:Record<number,string[]>={1:['0,108','29410','0,0286','0,25','0,6','130'],2:['6,92'],3:['0,72'],4:['69,92'],5:['1,59']};
async function fillAll(page:Page,wrongFirst=false){for(let stageIndex=1;stageIndex<=5;stageIndex++){await jump(page,stageIndex);const stage=page.locator('.interactive-stage[data-stage-id]').first();const values=[...stageValues[stageIndex]];if(wrongFirst&&stageIndex===1)values[0]='0,108000001';const inputs=stage.locator('input');await expect(inputs).toHaveCount(values.length);for(const[index,value]of values.entries())await inputs.nth(index).fill(value)}}
async function submit(page:Page){await page.getByRole('button',{name:'Сдать работу'}).click();await expect(page.locator('.interactive-stage[data-stage-id="l142-summary"]')).toBeVisible();return page.locator('.control-result-card')}
test('lesson 142 hides answers, accepts exact control variant and freezes a perfect primary result',async({page})=>{await open142(page);await expect(page.locator('.cat-mentor')).toBeHidden();await expect(page.locator('.progressive-hint-coach')).toBeHidden();await expect(page.locator('.lesson-reflection')).toBeHidden();await jump(page,1);const first=page.locator('.interactive-stage[data-stage-id="l142-task1"]');await expect(first.locator('.control-explanation')).toHaveCount(0);await expect(first).not.toContainText('Ответ:');await fillAll(page);await jump(page,6);await expect(page.getByText('Заполнено 10 из 10')).toBeVisible();let result=await submit(page);await expect(result).toContainText('Первичный результат: 10/10');await expect(result).toContainText('оценка 5');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-142-control-v1')??'null'));expect(saved?.submitted).toBe(true);expect(saved?.submittedResponses?.['l142-1a']).toBe('0,108');const completion=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita:lesson-complete:142')??'null'));expect(completion?.completedAt).toBeTruthy();await reopen142(page);result=page.locator('.control-result-card');await expect(result).toContainText('Первичный результат: 10/10')});
test('lesson 142 rejects a near decimal and correction cannot change the frozen primary score',async({page})=>{await open142(page);await fillAll(page,true);await jump(page,6);let result=await submit(page);await expect(result).toContainText('Первичный результат: 9/10');await expect(result).toContainText('Ошибок: 1. Первичный балл уже сохранён.');await page.getByRole('button',{name:'Исправить ошибки'}).click();const correction=page.locator('.interactive-stage[data-stage-id="l142-task1"]');await expect(correction.locator('input')).toHaveCount(1);await correction.locator('input').fill('000,1080');await page.getByRole('button',{name:'Завершить коррекцию'}).click();result=page.locator('.control-result-card');await expect(result).toContainText('Первичный результат: 9/10');await expect(result).toContainText('Коррекция завершена. Первичный результат не изменён.');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-142-control-v1')??'null'));expect(saved?.submittedResponses?.['l142-1a']).toBe('0,108000001');expect(saved?.responses?.['l142-1a']).toBe('000,1080');await reopen142(page);await expect(page.locator('.control-result-card')).toContainText('Первичный результат: 9/10')});
