import {expect,test,type Page} from '@playwright/test';

test.use({viewport:{width:1024,height:1366},userAgent:'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});
async function openLesson47(page:Page){await page.goto('/');const chapterTwo=page.locator('.course-chapter-group').nth(1);if(!(await chapterTwo.evaluate(element=>(element as HTMLDetailsElement).open)))await chapterTwo.locator('summary').click();const lesson47=page.getByRole('button',{name:/Открыть урок 47:/});const lesson48=page.locator('.course-lesson-grid > button').nth(47);const lesson49=page.locator('.course-lesson-grid > button').nth(48);const lesson50=page.locator('.course-lesson-grid > button').nth(49);const lesson51=page.locator('.course-lesson-grid > button').nth(50);await expect(lesson47).toBeEnabled();await expect(lesson48).toBeEnabled();await expect(lesson49).toBeEnabled();await expect(lesson50).toBeEnabled();await expect(lesson51).toBeDisabled();await lesson47.click();await page.locator('.lesson-opening-start').click()}
async function jump(page:Page,index:number,id:string){await page.evaluate(({index})=>window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber:47,stageIndex:index}})),{index});await expect(page.locator(`[data-stage-id="${id}"]`)).toBeVisible()}
async function expectScaledIsosceles(page:Page,index:number,id:string,values:number[],angle:'acute'|'obtuse'){await jump(page,index,id);const diagram=page.locator(`[data-stage-id="${id}"] .triangle-practice-diagram`);await expect(diagram).toHaveAttribute('data-side-values',values.map(value=>`${value} см`).join('|'));await expect(diagram).toHaveAttribute('data-angle-type',angle);await expect(diagram.locator('[data-equal-side-mark]')).toHaveCount(2);const lengths=await diagram.locator('polygon.triangle-practice-shape').evaluate((node:SVGPolygonElement)=>{const points=(node.getAttribute('points')??'').trim().split(/\s+/).map(pair=>pair.split(',').map(Number));const distance=(a:number[],b:number[])=>Math.hypot(a[0]-b[0],a[1]-b[1]);return[distance(points[0],points[1]),distance(points[1],points[2]),distance(points[2],points[0])]});const scales=lengths.map((length,side)=>length/values[side]);expect(Math.max(...scales)-Math.min(...scales)).toBeLessThan(.08)}

test('lesson 47 keeps exact geometry, soft retry gates, persistence and practice stable on iPad',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('mathnikita-mentor-auto-guide','false'));await openLesson47(page);await expect(page.locator('[data-stage-id="l47-mission"] .lesson-controls')).toContainText('Этап 1 из 36');
  await jump(page,3,'l47-angle-dictation');const obtuse=page.locator('[data-stage-id="l47-angle-dictation"] .triangle-practice-diagram');await expect(obtuse).toHaveAttribute('data-angle-type','obtuse');const dots=await obtuse.locator('polygon.triangle-practice-shape').evaluate((node:SVGPolygonElement)=>{const pts=(node.getAttribute('points')??'').trim().split(/\s+/).map(pair=>pair.split(',').map(Number));const dot=(o:number[],a:number[],b:number[])=>(a[0]-o[0])*(b[0]-o[0])+(a[1]-o[1])*(b[1]-o[1]);return[dot(pts[0],pts[1],pts[2]),dot(pts[1],pts[0],pts[2]),dot(pts[2],pts[0],pts[1])]});expect(dots.filter(value=>value<0)).toHaveLength(1);
  await jump(page,5,'l47-unit-gate');const conversions=page.locator('[data-stage-id="l47-unit-gate"] .triangle-practice-measures > div');await expect(conversions).toHaveCount(3);await expect(conversions.nth(0)).toContainText('3,2 см');await expect(conversions.nth(2)).toContainText('32 см');
  await jump(page,7,'l47-passport-gate');const right=page.locator('[data-stage-id="l47-passport-gate"] .triangle-practice-diagram');await expect(right).toHaveAttribute('data-angle-type','right');await expect(right).toHaveAttribute('data-side-type','isosceles');await expect(right.locator('[data-right-angle-marker="true"]')).toHaveCount(1);await expect(right.locator('[data-equal-side-mark]')).toHaveCount(2);
  await expectScaledIsosceles(page,15,'l47-textbook346a',[8,8,13],'obtuse');await expectScaledIsosceles(page,17,'l47-textbook346b',[12,12,15],'acute');await expectScaledIsosceles(page,33,'l47-control-type',[9,9,12],'acute');await expectScaledIsosceles(page,34,'l47-final-gate',[15,15,14],'acute');
  await jump(page,18,'l47-equilateral-model');const equilateral=page.locator('[data-stage-id="l47-equilateral-model"] .triangle-practice-diagram');await expect(equilateral).toHaveAttribute('data-side-type','equilateral');await expect(equilateral.locator('[data-equal-side-mark]')).toHaveCount(3);
  await jump(page,2,'l47-recall-gate');const retry=page.locator('[data-stage-id="l47-recall-gate"]');for(let attempt=0;attempt<2;attempt+=1){await retry.getByRole('button',{name:'Величины углов',exact:true}).click();await retry.locator('.check-button').click();await expect(retry.locator('.instant-feedback.bad')).toBeVisible()}await expect(retry.locator('.lesson-controls .primary')).toBeEnabled();await expect(retry.locator('.instant-feedback.bad')).toContainText('Можно перейти дальше');
  await jump(page,11,'l47-textbook344-step1');const textbook=page.locator('[data-stage-id="l47-textbook344-step1"]');await textbook.locator('.inline-answer input').fill('42 см');await textbook.locator('.check-button').click();await expect(textbook.locator('.instant-feedback.good')).toBeVisible();await textbook.locator('.inline-answer input').fill('43');await expect(textbook.locator('.instant-feedback')).toHaveCount(0);await expect(textbook.locator('.lesson-controls .primary')).toBeDisabled();await expect.poll(async()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-47-progress-v1')??'null')?.results?.['l47-p6'])).toBe(false);await textbook.locator('.inline-answer input').fill('42 см');await textbook.locator('.check-button').click();await expect(textbook.locator('.instant-feedback.good')).toBeVisible();await textbook.locator('.lesson-controls .primary').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathnikita-lesson-47-progress-v1')??'null'));expect(saved?.stageIndex).toBe(12);expect(saved?.results?.['l47-p6']).toBe(true);
  await page.getByRole('button',{name:/Все уроки/}).click();await page.getByRole('button',{name:/Открыть урок 47:/}).click();await page.locator('.lesson-opening-start').click();await expect(page.locator('[data-stage-id="l47-textbook344-step2"]')).toBeVisible();const collapsed=page.locator('.cat-mentor-collapsed');await expect(collapsed).toBeVisible();await collapsed.click();await expect(page.locator('.cat-mentor-actions button')).toHaveCount(4);
  await jump(page,35,'l47-summary');await expect(page.locator('.lesson-reflection')).toBeVisible();await expect(page.locator('.extended-practice[data-practice-task="l47-extra-01"]')).toBeVisible();await expect(page.locator('.practice-pythagoras-actions button')).toHaveCount(4);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(2);
});
