import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='map'|'column'|'pairs'|'properties'|'letters'|'story'|'measure'|'error'|'algorithm'|'challenge';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-24-progress-v1';

export const lessonTwentyFourStages:Stage[]=[
  {id:'l24-mission',kind:'story',eyebrow:'Глава 2 · § 7 · итог',title:'Сегодня выбираем способ, а не повторяем правило',body:'Ты уже умеешь складывать многозначные числа и знаешь два свойства сложения. Итог § 7 проверяет более важное: умеешь ли ты распознать ситуацию, выбрать надёжный путь, объяснить преобразование и перенести его в задачу.',note:'По технологической карте урок 24 — обобщение и систематизация знаний. Ядро: применение свойств сложения, упражнения линии № 179, 181, 182, 184, 186 и повторение № 194.',sourceTag:'Мерзляк · § 7 · технологическая карта урока 24',visual:'map'},
  {id:'l24-warmup',kind:'guided',eyebrow:'Актуализация',title:'Сначала увидь структуру',body:'Не каждую сумму выгодно считать слева направо. Посмотри, можно ли получить круглое число одним переставлением.',activity:{id:'l24-a1',type:'input',prompt:'Вычисли удобным способом: 784 + (179 + 116).',answer:'1079',placeholder:'Ответ',explanation:'Переставим 179 и 116: (784 + 116) + 179 = 900 + 179 = 1 079.'},visual:'pairs'},
  {id:'l24-map',kind:'model',eyebrow:'Карта решения',title:'Три режима сложения',body:'Режим 1: обычное точное сложение по разрядам. Режим 2: удобная сумма — ищем дополнения до круглых чисел. Режим 3: задача — сначала строим математическую модель, затем выбираем вычислительный путь.',note:'Свойства — инструмент, а не обязательный ритуал в каждом примере.',visual:'map'},
  {id:'l24-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Когда свойства не главное',body:'Здесь нет специальной круглой пары. Главная задача — аккуратно удержать разряды.',activity:{id:'l24-p1',type:'input',prompt:'Выполни сложение: 2 905 047 + 38 996.',answer:'2944043',placeholder:'Сумма',explanation:'При поразрядном сложении получаем 2 944 043.'},visual:'column'},
  {id:'l24-property',kind:'guided',eyebrow:'Понимание свойства',title:'Назови, что именно изменилось',body:'Не определяй свойство по наличию скобок. Сравни порядок слагаемых и их группировку.',activity:{id:'l24-a2',type:'choice',prompt:'Какое свойство использовано: (120 + 380) + 625 = 120 + (380 + 625)?',options:['Сочетательное','Переместительное','Оба свойства','Свойство нуля'],answer:'Сочетательное',explanation:'Порядок 120, 380, 625 сохранился. Изменилась только группировка — это сочетательное свойство.'},visual:'properties'},
  {id:'l24-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Две пары — один короткий ход',body:'Сначала просмотри всю сумму и только потом начинай вычислять.',activity:{id:'l24-p2',type:'input',prompt:'Вычисли удобным способом: 339 + 584 + 416 + 661.',answer:'2000',placeholder:'Ответ',explanation:'339 + 661 = 1 000, 584 + 416 = 1 000. Значит вся сумма равна 2 000.'},visual:'pairs'},
  {id:'l24-explain',kind:'model',eyebrow:'Обоснование',title:'Почему удобный порядок законен',body:'Чтобы соединить далёкие слагаемые, мы можем изменить их порядок переместительным свойством, а затем поставить скобки вокруг удобных групп сочетательным свойством. Сумма при этом не меняется.',note:'Сильный ответ содержит не только число, но и объяснение, какое преобразование было выполнено.',visual:'properties'},
  {id:'l24-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Собери алгоритм рационального вычисления',body:'Порядок действий здесь важнее конкретных чисел.',activity:{id:'l24-p3',type:'order',prompt:'Расположи шаги удобного сложения в разумном порядке.',items:['Просмотреть все слагаемые','Найти удобные пары или группы','При необходимости переставить слагаемые','Сгруппировать выбранные слагаемые','Вычислить и проверить сумму'],answer:['Просмотреть все слагаемые','Найти удобные пары или группы','При необходимости переставить слагаемые','Сгруппировать выбранные слагаемые','Вычислить и проверить сумму'],explanation:'Сначала анализируем всю сумму, затем выбираем пары, обосновываем перестановку и группировку и только после этого считаем.'},visual:'algorithm'},
  {id:'l24-letters',kind:'model',eyebrow:'Буквенные выражения',title:'Неизвестное не мешает работать с известными числами',body:'В выражении 146 + (m + 854) значение m неизвестно, но 146 и 854 можно соединить: свойства сложения работают и в буквенном выражении.',visual:'letters'},
  {id:'l24-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Упрости выражение',body:'Не подставляй значение m — его нет. Упрости числовую часть.',activity:{id:'l24-p4',type:'choice',prompt:'Во что превращается 146 + (m + 854)?',options:['1 000 + m','146m + 854','m + 708','1 000m'],answer:'1 000 + m',explanation:'146 + (m + 854) = 146 + (854 + m) = (146 + 854) + m = 1 000 + m.'},visual:'letters'},
  {id:'l24-story',kind:'model',eyebrow:'Текстовая задача',title:'Сначала связь между величинами, потом сумма',body:'Если второе значение задано словами «на … больше», его нельзя сразу складывать с остальными. Сначала восстанови неизвестное значение, затем собери итог.',note:'Это соответствует линии текстовых задач § 7: вычислительное свойство должно помогать модели задачи, а не заменять её.',sourceTag:'Мерзляк · § 7 · линия упражнений 182–186',visual:'story'},
  {id:'l24-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Задача в два вычислительных слоя',body:'В первый день библиотека обработала 3 250 книг, во второй — на 750 больше, чем в первый, в третий — 1 750.',activity:{id:'l24-p5',type:'input',prompt:'Сколько книг обработали за три дня?',answer:'9000',placeholder:'Всего книг',explanation:'Во второй день: 3 250 + 750 = 4 000. Всего: 3 250 + 4 000 + 1 750 = 9 000.'},visual:'story'},
  {id:'l24-measure',kind:'model',eyebrow:'Составные величины',title:'Свойства помогают, но единицы должны совпадать',body:'Часы складываем с часами, минуты — с минутами. Если минут получилось 60 или больше, переводим лишние минуты в часы. Удобный порядок не отменяет работу с единицами.',visual:'measure'},
  {id:'l24-error',kind:'guided',eyebrow:'Разбор ошибки',title:'Не путай перестановку с новой группировкой',body:'Ученик написал (398 + 202) + 175 = 398 + (202 + 175) и объяснил: «Я поменял слагаемые местами».',activity:{id:'l24-a3',type:'choice',prompt:'Что нужно исправить в объяснении?',options:['Здесь применено сочетательное свойство','Здесь применено переместительное свойство','Здесь применены оба свойства','Само равенство неверно'],answer:'Здесь применено сочетательное свойство',explanation:'Порядок чисел не изменился. Поменялась только группировка, значит применено сочетательное свойство.'},visual:'error'},
  {id:'l24-algorithm',kind:'model',eyebrow:'Самостоятельная стратегия',title:'Пять вопросов перед ответом',body:'Что требуется найти? Какие данные нужно восстановить? Есть ли удобная пара? Какое свойство разрешает преобразование? Чем проверить результат? Такой маршрут уменьшает и вычислительные, и смысловые ошибки.',visual:'algorithm'},
  {id:'l24-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Четыре слагаемых — две круглые группы',body:'Это последний тренировочный пример перед независимым контролем.',activity:{id:'l24-p6',type:'input',prompt:'Вычисли: 1 654 + 18 135 + 7 346 + 11 865.',answer:'39000',placeholder:'Ответ',explanation:'1 654 + 7 346 = 9 000, 18 135 + 11 865 = 30 000. Общая сумма 39 000.'},visual:'pairs'},
  {id:'l24-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Точное сложение',body:'Без подсказки выбери надёжный способ.',activity:{id:'l24-q1',type:'input',prompt:'Вычисли: 425 806 + 74 194.',answer:'500000',placeholder:'Ответ',explanation:'425 806 + 74 194 = 500 000.'},visual:'column'},
  {id:'l24-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Формула свойства',body:'Работай самостоятельно.',activity:{id:'l24-q2',type:'choice',prompt:'Какая формула выражает переместительное свойство сложения?',options:['a + b = b + a','(a + b) + c = a + (b + c)','a + 0 = 0','a + a = a'],answer:'a + b = b + a',explanation:'Переместительное свойство меняет местами два слагаемых.'},visual:'properties'},
  {id:'l24-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Удобная сумма',body:'Сам выбери пары.',activity:{id:'l24-q3',type:'input',prompt:'Вычисли: 427 + 88 + 273 + 112.',answer:'900',placeholder:'Ответ',explanation:'427 + 273 = 700, 88 + 112 = 200; всего 900.'},visual:'pairs'},
  {id:'l24-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Перенос в текстовую задачу',body:'В первый день мастерская изготовила 4 350 деталей, во второй — на 650 больше, в третий — 1 650.',activity:{id:'l24-q4',type:'input',prompt:'Сколько деталей изготовили за три дня?',answer:'11000',placeholder:'Ответ',explanation:'Во второй день изготовили 5 000 деталей. Всего 4 350 + 5 000 + 1 650 = 11 000.'},visual:'story'},
  {id:'l24-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Составные величины',body:'Работай самостоятельно.',activity:{id:'l24-q5',type:'input',prompt:'Вычисли: 4 ч 52 мин + 2 ч 38 мин. Запиши «7 ч 30 мин».',answer:'7ч30мин',placeholder:'Ответ',explanation:'52 + 38 = 90 мин = 1 ч 30 мин; 4 + 2 + 1 = 7 ч 30 мин.'},visual:'measure'},
  {id:'l24-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Три суммы — одно скрытое удвоение',body:'Для натуральных A, B, C известно: A + B = 780, B + C = 650, A + C = 930. Не подбирай числа по одному: сложи три равенства и посмотри, сколько раз встретилось каждое число.',activity:{id:'l24-c1',type:'input',prompt:'Найди A + B + C.',answer:'1180',placeholder:'Общая сумма',explanation:'780 + 650 + 930 = 2 360. Слева каждое число A, B, C учтено дважды, значит 2(A+B+C)=2 360 и A+B+C=1 180.'},visual:'challenge'},
  {id:'l24-summary',kind:'summary',eyebrow:'Итог § 7',title:'Теперь сложение — это система решений',body:'Ты различал точное и рациональное сложение, называл свойства, упрощал буквенные выражения, работал с величинами и переносил сложение в текстовые и нестандартные задачи.',note:'Рефлексия по технологической карте: «Теперь я умею …», «На уроке для меня было важно …», «На уроке мне было сложно …». После основной части обязательны 20 итоговых заданий.',sourceTag:'Мерзляк · § 7 · урок 24: обобщение и систематизация'},
];

function load():Saved{
  const fallback:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
  try{const raw=localStorage.getItem(KEY);if(!raw)return fallback;const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonTwentyFourStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return fallback}
}
function normalize(value:string){return value.trim().toLowerCase().replace(/\s+/g,'').replace(/[−–]/g,'-')}
function sameOrder(a:string[],b:string[]){return a.length===b.length&&a.every((value,index)=>value===b[index])}

function SummaryVisual({kind}:{kind?:Visual}){
  if(kind==='column')return <div className="properties-visual"><div className="property-hero"><b>Разряд под разрядом</b><b>Перенос учитываем сразу</b><span>Иногда лучший способ — обычное точное сложение</span></div></div>;
  if(kind==='pairs')return <div className="properties-visual"><div className="pair-board"><span>339 + 661</span><span>584 + 416</span><b>1 000</b><b>1 000</b></div></div>;
  if(kind==='properties'||kind==='error')return <div className="properties-visual"><div className="property-cards"><div><b>Переместительное</b><span>меняем порядок</span><code>a + b = b + a</code></div><div><b>Сочетательное</b><span>меняем группировку</span><code>(a + b) + c = a + (b + c)</code></div></div></div>;
  if(kind==='letters')return <div className="properties-visual"><div className="letter-chain"><span>146 + (m + 854)</span><i>→</i><span>(146 + 854) + m</span><i>→</i><strong>1 000 + m</strong></div></div>;
  if(kind==='measure')return <div className="properties-visual"><div className="time-board"><div><b>4 ч 52 мин</b><span>+</span><b>2 ч 38 мин</b></div><p>90 мин = 1 ч 30 мин</p></div></div>;
  if(kind==='algorithm'||kind==='map')return <div className="properties-visual"><div className="properties-algorithm">{['Понять задачу','Выбрать режим','Обосновать свойство','Вычислить','Проверить'].map((text,index)=><div key={text}><b>{index+1}</b><span>{text}</span></div>)}</div></div>;
  if(kind==='challenge')return <div className="properties-visual"><div className="challenge-pairs"><b>A + B = 780</b><b>B + C = 650</b><b>A + C = 930</b><strong>вместе каждое число встретится дважды</strong></div></div>;
  if(kind==='story')return <div className="properties-visual"><div className="property-hero"><b>Сначала восстанови данные</b><b>Потом собери итог</b><span>Свойства помогают вычислению, но не заменяют модель задачи</span></div></div>;
  return <div className="properties-visual"><div className="property-hero"><b>Точно сложить</b><b>Удобно преобразовать</b><span>Итог § 7: сам выбираю стратегию</span></div></div>;
}

export function AdditionPropertiesSummaryPlayer(){
  const saved=useMemo(load,[]);
  const[stageIndex,setStageIndex]=useState(saved.stageIndex);
  const[responses,setResponses]=useState(saved.responses);
  const[orders,setOrders]=useState(saved.orders);
  const[checked,setChecked]=useState(saved.checked);
  const[results,setResults]=useState(saved.results);
  const stage=lessonTwentyFourStages[stageIndex];
  const activity=stage.activity;
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results} satisfies Saved))},[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const jump=(event:Event)=>{const detail=(event as CustomEvent<{lessonNumber:number;stageIndex:number}>).detail;if(detail?.lessonNumber!==24)return;setStageIndex(Math.min(Math.max(detail.stageIndex,0),lessonTwentyFourStages.length-1));window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('mathnikita-go-to-stage',jump);return()=>window.removeEventListener('mathnikita-go-to-stage',jump)},[]);
  const practiceCorrect=lessonTwentyFourStages.filter(item=>item.kind==='practice'&&item.activity).filter(item=>results[item.activity!.id]).length;
  const quizCorrect=lessonTwentyFourStages.filter(item=>item.kind==='quiz'&&item.activity).filter(item=>results[item.activity!.id]).length;
  const currentOrder=activity?orders[activity.id]??[]:[];
  const currentResponse=activity?responses[activity.id]??'':'';
  const isCorrect=activity?Boolean(results[activity.id]&&checked[activity.id]):true;
  const wasChecked=activity?Boolean(checked[activity.id]):false;
  function invalidateCurrent(){if(!activity)return;setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  function choose(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));invalidateCurrent()}
  function addOrder(value:string){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:[...(previous[activity.id]??[]),value]}));invalidateCurrent()}
  function removeOrder(index:number){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:(previous[activity.id]??[]).filter((_,itemIndex)=>itemIndex!==index)}));invalidateCurrent()}
  function checkAnswer(){if(!activity)return;const correct=activity.type==='order'?sameOrder(currentOrder,activity.answer as string[]):normalize(currentResponse)===normalize(activity.answer as string);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function resetActivity(){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:''}));setOrders(previous=>({...previous,[activity.id]:[]}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  function move(delta:number){setStageIndex(index=>Math.min(Math.max(index+delta,0),lessonTwentyFourStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  return <main className="lesson-player-page"><div className="lesson-workspace">
    <header className="lesson-header"><div><span>Урок 24 · § 7 · итог</span><h1>Сложение натуральных чисел — итог § 7</h1><p>Обобщение: точность, свойства, выбор стратегии и перенос в задачи.</p></div><div className="lesson-duration">≈ 48 минут</div></header>
    <div className="lesson-progress"><i style={{width:`${((stageIndex+1)/lessonTwentyFourStages.length)*100}%`}}/></div>
    <div className="stage-counter"><span>Этап {stageIndex+1} из {lessonTwentyFourStages.length}</span><div><small>{practiceCorrect}/6 практика · {quizCorrect}/5 контроль</small></div></div>
    <section className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}>
      <div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p><b>{stage.note}</b></p>:null}{stage.sourceTag?<small className="properties-source">{stage.sourceTag}</small>:null}</div>
      <SummaryVisual kind={stage.visual}/>
      {activity?<div className="activity-area"><h3>{activity.prompt}</h3>
        {activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={currentResponse===option?'selected':''} onClick={()=>choose(option)}>{option}</button>)}</div>:null}
        {activity.type==='input'?<div className="inline-answer"><input value={currentResponse} onChange={event=>choose(event.target.value)} onKeyDown={event=>event.key==='Enter'&&currentResponse.trim()&&checkAnswer()} placeholder={activity.placeholder??'Ответ'}/></div>:null}
        {activity.type==='order'?<><div className="order-bank">{activity.items?.map(item=><button key={item} type="button" disabled={currentOrder.includes(item)} onClick={()=>addOrder(item)}>{item}</button>)}</div><div className="order-result">{currentOrder.length?currentOrder.map((item,index)=><button key={`${item}-${index}`} type="button" onClick={()=>removeOrder(index)}>{index+1}. {item}</button>):<span>Нажимай шаги по порядку</span>}</div></>:null}
        <div className="activity-actions"><button type="button" className="secondary" onClick={resetActivity}>Сбросить</button><button type="button" className="check-button" disabled={activity.type==='order'?!currentOrder.length:!currentResponse.trim()} onClick={checkAnswer}>Проверить</button></div>
        {wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{activity.explanation}</span></div>:null}
      </div>:null}
      {stage.kind==='quiz'?<div className="quiz-meter"><span>Итоговый контроль § 7</span><b>{quizCorrect}/5</b></div>:null}
      {stage.kind==='summary'?<div className="summary-card"><div><span>Контроль</span><b>{quizCorrect}/5</b><small>самостоятельных заданий</small></div><div><span>Практика</span><b>{practiceCorrect}/6</b><small>основных упражнений</small></div><div><span>Статус</span><b>{quizCorrect===5&&practiceCorrect===6?'Основная часть готова':'Нужно закончить'}</b><small>дальше — 20 обязательных заданий</small></div></div>:null}
    </section>
    <nav className="lesson-controls" aria-label="Переход между этапами"><button type="button" disabled={stageIndex===0} onClick={()=>move(-1)}>← Назад</button><span>{stageIndex+1} / {lessonTwentyFourStages.length}</span><button type="button" className="primary" disabled={stageIndex===lessonTwentyFourStages.length-1||(Boolean(activity)&&!isCorrect)} onClick={()=>move(1)}>{stageIndex===lessonTwentyFourStages.length-1?'Основная часть завершена':'Дальше →'}</button></nav>
  </div></main>;
}