import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='equal'|'same-ray'|'four-rays'|'shared-side'|'vertex-on-side';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-38-progress-v1';
const normalize=(value:string)=>value.trim().toUpperCase().replace(/\s+/g,'').replace(/[∠<>]/g,'').replace(/Ё/g,'Е');

export const lessonThirtyEightStages:Stage[]=[
  {id:'l38-mission',kind:'story',eyebrow:'Урок 38 · § 11 · закрепление',title:'Теперь читаем сложный чертёж целиком',body:'В прошлом уроке мы научились называть отдельный угол. Сегодня задача сложнее: на одном рисунке могут быть несколько лучей, несколько названий одной фигуры и несколько углов, связанных между собой. Нужно не угадывать по картинке, а рассуждать по вершинам и сторонам.',note:'Градусы и виды углов пока не используем — это следующий § 12.',diagram:'four-rays'},
  {id:'l38-recap',kind:'model',eyebrow:'Разминка',title:'Три проверки перед любой задачей',body:'1) Найди вершину. 2) Определи два луча-стороны. 3) Проверь, что в трёхбуквенном названии вершина стоит в середине. Эти три действия работают и на самом сложном рисунке.'},
  {id:'l38-practice1',kind:'practice',eyebrow:'Практика · 1/12',title:'Быстрая проверка обозначения',body:'Сначала восстанови стороны по названию.',activity:{id:'l38-p1',type:'choice',prompt:'Какие лучи являются сторонами ∠BOC?',options:['OB и OC','BO и BC','CB и CO','BC и OC'],answer:'OB и OC',hint:'Вершина O — средняя буква, оба луча начинаются в O.',explanation:'Стороны ∠BOC — лучи OB и OC.'}},
  {id:'l38-equal-model',kind:'model',eyebrow:'Новое правило § 11',title:'Равные углы совпадают при наложении',body:'Два угла называют равными, если один из них можно наложить на другой так, чтобы их вершины и обе стороны совпали. Длины нарисованных кусочков лучей значения не имеют: сторона угла — луч, а не отрезок.',diagram:'equal'},
  {id:'l38-practice2',kind:'practice',eyebrow:'Практика · 2/12',title:'Что означает «равные углы»?',body:'Опирайся на определение, а не на внешний вид страницы.',activity:{id:'l38-p2',type:'choice',prompt:'Когда два угла называют равными?',options:['Когда они совпадают при наложении','Когда у них одна вершина','Когда стороны нарисованы одинаковой длины','Когда они подписаны одинаковыми буквами'],answer:'Когда они совпадают при наложении',hint:'Равенство геометрических фигур проверяется совпадением при наложении.',explanation:'Если углы совпадают при наложении, они равны.'}},
  {id:'l38-overlay',kind:'model',eyebrow:'Важно',title:'Поворот рисунка не меняет сам угол',body:'Один и тот же по форме угол можно нарисовать в другой части листа и повернуть. Если после переноса и поворота стороны совпадут, углы равны. Положение на странице не является свойством угла.',diagram:'equal'},
  {id:'l38-practice3',kind:'practice',eyebrow:'Практика · 3/12',title:'Что не влияет на равенство?',body:'Отдели фигуру от оформления.',activity:{id:'l38-p3',type:'choice',prompt:'Что само по себе НЕ доказывает, что два угла разные?',options:['Один рисунок повёрнут относительно другого','При наложении стороны не совпадают','У фигур разная форма','После совмещения одна сторона уходит в другое направление'],answer:'Один рисунок повёрнут относительно другого',hint:'Фигуру можно переносить и поворачивать при наложении.',explanation:'Разное положение на листе не мешает углам быть равными.'}},
  {id:'l38-same-ray-model',kind:'model',eyebrow:'Тонкость обозначений',title:'Несколько точек могут лежать на одной стороне',body:'Пусть точки B и A лежат на одном луче из O, а C — на другом. Тогда лучи OA и OB совпадают. Поэтому ∠AOC и ∠BOC могут быть разными названиями одной и той же фигуры.',note:'Новая буква на уже существующем луче не создаёт новый луч.',diagram:'same-ray'},
  {id:'l38-practice4',kind:'practice',eyebrow:'Практика · 4/12',title:'Один луч — две отмеченные точки',body:'Смотри на направление от вершины.',diagram:'same-ray',activity:{id:'l38-p4',type:'choice',prompt:'Точки A и B лежат на одном луче из O. Что верно?',options:['Лучи OA и OB совпадают','OA и OB — противоположные лучи','OA и OB образуют угол','OA длиннее OB'],answer:'Лучи OA и OB совпадают',hint:'Оба луча имеют начало O и идут в одном направлении.',explanation:'Если A и B лежат на одном луче из O, записи OA и OB обозначают один и тот же луч.'}},
  {id:'l38-practice5',kind:'guided',eyebrow:'Практика · 5/12',title:'Два имени одной фигуры',body:'Используй совпадающую сторону.',diagram:'same-ray',activity:{id:'l38-p5',type:'choice',prompt:'A и B лежат на одном луче из O, C — на другом. Какие углы совпадают?',options:['∠AOC и ∠BOC','∠AOB и ∠BOC','∠OAC и ∠OCB','∠ABC и ∠AOC'],answer:'∠AOC и ∠BOC',hint:'Лучи OA и OB совпадают, а вторая сторона OC общая.',explanation:'У ∠AOC и ∠BOC одна вершина O и те же две стороны.'}},
  {id:'l38-four-rays-model',kind:'model',eyebrow:'Сложный чертёж',title:'Четыре луча — шесть пар сторон',body:'Из O выходят OA, OB, OC и OD. Каждый угол определяется выбором двух разных лучей. Получаем пары AB, AC, AD, BC, BD, CD — всего шесть углов.',diagram:'four-rays'},
  {id:'l38-practice6',kind:'practice',eyebrow:'Практика · 6/12',title:'Не пропусти пару',body:'Считай именно пары лучей.',diagram:'four-rays',activity:{id:'l38-p6',type:'input',prompt:'Сколько разных углов задают четыре разных луча из одной вершины?',answer:'6',placeholder:'Число',hint:'Первый луч образует пары с тремя, второй — ещё с двумя, третий — с одним.',explanation:'3 + 2 + 1 = 6 разных пар лучей.'}},
  {id:'l38-practice7',kind:'practice',eyebrow:'Практика · 7/12',title:'Найди дальнюю пару',body:'На рисунке нужны лучи OB и OD.',diagram:'four-rays',activity:{id:'l38-p7',type:'choice',prompt:'Как называется угол между лучами OB и OD?',options:['∠BOD','∠BOC','∠AOD','∠BDO'],answer:'∠BOD',hint:'O должна быть средней буквой.',explanation:'Лучи OB и OD образуют ∠BOD (или ∠DOB).'}},
  {id:'l38-all-angles',kind:'model',eyebrow:'Системный способ',title:'Перечисляй углы как пары, а не «по картинке»',body:'Для четырёх лучей удобно выписать все пары: OA–OB, OA–OC, OA–OD, OB–OC, OB–OD, OC–OD. После этого превращаем каждую пару в название угла. Так ни один угол не потеряется и не повторится.',diagram:'four-rays'},
  {id:'l38-practice8',kind:'guided',eyebrow:'Практика · 8/12',title:'Полный список',body:'Проверь все шесть пар.',activity:{id:'l38-p8',type:'choice',prompt:'Какой список содержит все углы для лучей OA, OB, OC, OD?',options:['∠AOB, ∠AOC, ∠AOD, ∠BOC, ∠BOD, ∠COD','∠AOB, ∠BOC, ∠COD, ∠AOD','∠AOC, ∠AOD, ∠BOC, ∠BOD','∠AOB, ∠AOC, ∠BOC, ∠COD'],answer:'∠AOB, ∠AOC, ∠AOD, ∠BOC, ∠BOD, ∠COD',hint:'Нужны все пары A-B, A-C, A-D, B-C, B-D, C-D.',explanation:'В полном списке шесть углов — по одному для каждой пары лучей.'}},
  {id:'l38-shared-model',kind:'model',eyebrow:'Связи между углами',title:'Общая вершина и общая сторона — разные вещи',body:'Углы ∠AOB и ∠BOC имеют общую вершину O и общую сторону OB. А ∠AOB и ∠COD имеют общую вершину O, но ни одной общей стороны.',diagram:'shared-side'},
  {id:'l38-practice9',kind:'practice',eyebrow:'Практика · 9/12',title:'Найди общую сторону',body:'Разложи каждый угол на два луча.',diagram:'shared-side',activity:{id:'l38-p9',type:'choice',prompt:'Какая общая сторона у ∠AOB и ∠BOC?',options:['OB','OA','OC','AB'],answer:'OB',hint:'Стороны первого: OA и OB; второго: OB и OC.',explanation:'Луч OB входит в оба угла.'}},
  {id:'l38-practice10',kind:'practice',eyebrow:'Практика · 10/12',title:'Только общая вершина',body:'Общая вершина ещё не означает общую сторону.',activity:{id:'l38-p10',type:'choice',prompt:'У ∠AOB и ∠COD общая вершина O. Что ещё обязательно общее?',options:['Ничего из перечисленного','Сторона OA','Сторона OB','Они обязательно равны'],answer:'Ничего из перечисленного',hint:'У первого стороны OA, OB; у второго OC, OD.',explanation:'Эти углы могут иметь только общую вершину O.'}},
  {id:'l38-vertex-on-side',kind:'model',eyebrow:'Взаимное расположение',title:'Вершина одного угла может лежать на стороне другого',body:'На большом угле с вершиной O точка P отмечена на стороне OA. Из P построены ещё два луча. Тогда вершина P второго угла лежит на стороне OA первого. Такие условия нужно читать буквально — по принадлежности точки лучу.',diagram:'vertex-on-side'},
  {id:'l38-practice11',kind:'guided',eyebrow:'Практика · 11/12',title:'Прочитай условие геометрически',body:'Не делай лишних выводов.',activity:{id:'l38-p11',type:'choice',prompt:'Если вершина P одного угла лежит на стороне OA другого, что известно точно?',options:['P принадлежит лучу OA','Углы равны','У углов одна вершина','Углы имеют общую сторону'],answer:'P принадлежит лучу OA',hint:'«Лежит на стороне» означает принадлежит соответствующему лучу.',explanation:'Из условия следует только то, что P лежит на луче OA.'}},
  {id:'l38-construction',kind:'model',eyebrow:'Построение по условию',title:'Сначала выполняй связи, потом добавляй детали',body:'Если нужно построить два угла с общей вершиной и общей стороной, сначала отметь вершину O и общий луч OB. Затем добавь по одному различному лучу OA и OC. Получатся ∠AOB и ∠BOC.',diagram:'shared-side'},
  {id:'l38-practice12',kind:'practice',eyebrow:'Практика · 12/12',title:'Выбери правильную конструкцию',body:'Условие должно выполняться целиком.',activity:{id:'l38-p12',type:'choice',prompt:'Какая пара углов имеет общую вершину O и общую сторону OB?',options:['∠AOB и ∠BOC','∠AOB и ∠COD','∠ABC и ∠BOC','∠OAB и ∠COD'],answer:'∠AOB и ∠BOC',hint:'В обоих названиях вершина O и должна присутствовать сторона OB.',explanation:'У ∠AOB и ∠BOC вершина O, а луч OB — общая сторона.'}},
  {id:'l38-errors',kind:'model',eyebrow:'Типичные ошибки',title:'Не считай буквы вместо лучей',body:'На сложном рисунке легко посчитать один угол дважды: ∠AOB и ∠BOA — это одна фигура. Ещё одна ловушка: если A и B лежат на одном луче из O, то OA и OB — не две разные стороны. Всегда сначала определяй геометрические лучи, а уже затем их названия.'},
  {id:'l38-error-check',kind:'guided',eyebrow:'Диагностика',title:'Найди неверное рассуждение',body:'Проверь, где смешали название и фигуру.',activity:{id:'l38-p13',type:'choice',prompt:'Какое утверждение ошибочно?',options:['∠AOB и ∠BOA — два разных угла','Четыре разных луча из O образуют шесть пар','Если A и B на одном луче из O, OA и OB совпадают','Равные углы совпадают при наложении'],answer:'∠AOB и ∠BOA — два разных угла',hint:'Перестановка крайних букв не меняет стороны угла.',explanation:'∠AOB и ∠BOA — два названия одной фигуры.'}},
  {id:'l38-control-intro',kind:'model',eyebrow:'Итог § 11',title:'Шесть вопросов без опоры на подсказки',body:'Проверим равенство углов, совпадающие лучи, полный перебор углов и связи между несколькими фигурами.'},
  {id:'l38-quiz1',kind:'quiz',eyebrow:'Контроль · 1/6',title:'Равные углы',body:'Вспомни определение.',activity:{id:'l38-q1',type:'choice',prompt:'Два угла равны, если…',options:['они совпадают при наложении','у них одна вершина','их стороны подписаны одинаково','они нарисованы рядом'],answer:'они совпадают при наложении',hint:'Равенство определяется совпадением фигур.',explanation:'Равные углы совпадают при наложении.'}},
  {id:'l38-quiz2',kind:'quiz',eyebrow:'Контроль · 2/6',title:'Совпадающие лучи',body:'Одна сторона может иметь несколько отмеченных точек.',activity:{id:'l38-q2',type:'choice',prompt:'A и B лежат на одном луче из O. Какая запись верна?',options:['OA и OB — один луч','OA и OB — противоположные лучи','OA и OB обязательно образуют угол','OA короче OB'],answer:'OA и OB — один луч',hint:'Начало и направление совпадают.',explanation:'Лучи OA и OB совпадают.'}},
  {id:'l38-quiz3',kind:'quiz',eyebrow:'Контроль · 3/6',title:'Четыре луча',body:'Считай пары.',activity:{id:'l38-q3',type:'input',prompt:'Сколько углов задают четыре разных луча из общей вершины?',answer:'6',placeholder:'Число',hint:'3 + 2 + 1.',explanation:'Четыре луча дают шесть разных пар.'}},
  {id:'l38-quiz4',kind:'quiz',eyebrow:'Контроль · 4/6',title:'Общая сторона',body:'Сравни пары лучей.',activity:{id:'l38-q4',type:'choice',prompt:'Какая общая сторона у ∠KOM и ∠MON?',options:['OM','OK','ON','KN'],answer:'OM',hint:'Запиши стороны каждого угла отдельно.',explanation:'Луч OM входит в оба угла.'}},
  {id:'l38-quiz5',kind:'quiz',eyebrow:'Контроль · 5/6',title:'Одна фигура — разные названия',body:'Точки на одной стороне могут меняться.',activity:{id:'l38-q5',type:'choice',prompt:'A и B лежат на одном луче из O, C — на другом. Какая пара обозначает один угол?',options:['∠AOC и ∠BOC','∠AOB и ∠BOC','∠OAC и ∠ABC','∠ACO и ∠BCO'],answer:'∠AOC и ∠BOC',hint:'OA и OB совпадают.',explanation:'Оба названия задают вершину O и одни и те же два луча.'}},
  {id:'l38-quiz6',kind:'quiz',eyebrow:'Контроль · 6/6',title:'Полный перебор',body:'Не повторяй один угол в обратной записи.',activity:{id:'l38-q6',type:'choice',prompt:'Какая запись НЕ добавляет новый угол к ∠AOB?',options:['∠BOA','∠AOC','∠BOC','∠AOD'],answer:'∠BOA',hint:'Поменялись только крайние буквы.',explanation:'∠AOB и ∠BOA — одна фигура.'}},
  {id:'l38-challenge1',kind:'challenge',eyebrow:'Challenge · 1/2',title:'Пять лучей без формулы',body:'Продолжи системный перебор пар.',activity:{id:'l38-c1',type:'input',prompt:'Из одной вершины выходят пять разных лучей. Сколько разных углов задают все пары лучей?',answer:'10',placeholder:'Число',hint:'Первый луч даёт 4 пары, второй ещё 3, затем 2 и 1.',explanation:'4 + 3 + 2 + 1 = 10 углов.'}},
  {id:'l38-challenge2',kind:'challenge',eyebrow:'Challenge · 2/2',title:'Четыре имени одной фигуры',body:'На каждой стороне отмечено по две точки.',activity:{id:'l38-c2',type:'choice',prompt:'A и B лежат на одном луче из O, C и D — на другом. Какие записи могут обозначать один и тот же угол?',options:['∠AOC, ∠AOD, ∠BOC, ∠BOD','∠AOB, ∠COD, ∠AOC, ∠BOD','∠OAC, ∠OAD, ∠OBC, ∠OBD','∠ABC, ∠BAD, ∠COD, ∠DOB'],answer:'∠AOC, ∠AOD, ∠BOC, ∠BOD',hint:'Вершина всегда O; на каждой из двух совпадающих сторон можно выбрать любую отмеченную точку.',explanation:'Все четыре названия задают одну вершину O и те же два направления сторон.'}},
  {id:'l38-final-map',kind:'model',eyebrow:'Карта § 11',title:'Теперь у тебя есть полный набор инструментов',body:'Угол задают два луча с общим началом. Вершина стоит в середине названия. Обратная запись не создаёт новый угол. Несколько точек на одном луче могут давать разные названия одной фигуры. Равные углы совпадают при наложении. На многолучевом рисунке углы надёжнее перечислять через пары лучей.'},
  {id:'l38-summary',kind:'summary',eyebrow:'Финиш § 11',title:'§ 11 закрыт: обозначения углов освоены',body:'Ты умеешь читать и строить обозначения, видеть равные углы, различать общую вершину и общую сторону, перечислять все углы на сложном чертеже и не считать одну фигуру дважды.',note:'Осталась обязательная практика из 20 заданий. После неё можно переходить к § 12 — видам и измерению углов.'},
];

function MasteryDiagram({kind}:{kind:Diagram}){
  if(kind==='equal')return <div className="angle-diagram" aria-label="Два равных угла, которые совпадут при наложении"><svg viewBox="0 0 620 300" role="img"><line className="angle-ray" x1="155" y1="230" x2="65" y2="90"/><line className="angle-ray" x1="155" y1="230" x2="275" y2="110"/><circle className="angle-point" cx="155" cy="230" r="6"/><path className="angle-arc" d="M132 194 Q157 165 190 194"/><text className="angle-label" x="140" y="266">O</text><line className="angle-ray" x1="445" y1="220" x2="335" y2="110"/><line className="angle-ray" x1="445" y1="220" x2="535" y2="80"/><circle className="angle-point" cx="445" cy="220" r="6"/><path className="angle-arc" d="M414 190 Q444 160 472 181"/><text className="angle-label" x="433" y="258">P</text></svg><span className="angle-caption">Положение на листе может отличаться; равенство проверяем наложением</span></div>;
  if(kind==='same-ray')return <div className="angle-diagram" aria-label="Точки B и A лежат на одном луче из O, C лежит на другом"><svg viewBox="0 0 620 300" role="img"><line className="angle-ray" x1="170" y1="235" x2="525" y2="100"/><line className="angle-ray" x1="170" y1="235" x2="105" y2="55"/><circle className="angle-point" cx="170" cy="235" r="6"/><circle className="angle-point" cx="300" cy="186" r="5"/><circle className="angle-point" cx="430" cy="136" r="5"/><text className="angle-label" x="151" y="270">O</text><text className="angle-label" x="292" y="216">B</text><text className="angle-label" x="427" y="166">A</text><text className="angle-label" x="82" y="50">C</text><path className="angle-arc" d="M166 190 Q220 170 246 206"/></svg><span className="angle-caption">OA и OB — один луч; ∠AOC и ∠BOC задают одну фигуру</span></div>;
  if(kind==='four-rays')return <div className="angle-diagram" aria-label="Четыре луча OA, OB, OC и OD с общей вершиной O"><svg viewBox="0 0 620 320" role="img"><line className="angle-ray" x1="305" y1="260" x2="70" y2="155"/><line className="angle-ray" x1="305" y1="260" x2="180" y2="55"/><line className="angle-ray" x1="305" y1="260" x2="395" y2="45"/><line className="angle-ray" x1="305" y1="260" x2="555" y2="140"/><circle className="angle-point" cx="305" cy="260" r="6"/><text className="angle-label" x="287" y="298">O</text><text className="angle-label" x="47" y="155">A</text><text className="angle-label" x="163" y="46">B</text><text className="angle-label" x="397" y="36">C</text><text className="angle-label" x="565" y="137">D</text></svg><span className="angle-caption">4 луча → 6 разных пар сторон</span></div>;
  if(kind==='vertex-on-side')return <div className="angle-diagram" aria-label="Точка P лежит на стороне OA угла AOB"><svg viewBox="0 0 620 320" role="img"><line className="angle-ray" x1="120" y1="255" x2="535" y2="90"/><line className="angle-ray" x1="120" y1="255" x2="500" y2="260"/><circle className="angle-point" cx="120" cy="255" r="6"/><circle className="angle-point" cx="315" cy="177" r="6"/><line className="angle-ray" x1="315" y1="177" x2="300" y2="55"/><line className="angle-ray" x1="315" y1="177" x2="450" y2="55"/><text className="angle-label" x="102" y="292">O</text><text className="angle-label" x="545" y="88">A</text><text className="angle-label" x="510" y="278">B</text><text className="angle-label" x="300" y="205">P</text></svg><span className="angle-caption">P принадлежит стороне OA большого угла</span></div>;
  return <div className="angle-diagram" aria-label="Углы AOB и BOC имеют общую сторону OB"><svg viewBox="0 0 620 300" role="img"><line className="angle-ray" x1="300" y1="240" x2="80" y2="110"/><line className="angle-ray" x1="300" y1="240" x2="305" y2="45"/><line className="angle-ray" x1="300" y1="240" x2="540" y2="120"/><circle className="angle-point" cx="300" cy="240" r="6"/><text className="angle-label" x="282" y="278">O</text><text className="angle-label" x="58" y="107">A</text><text className="angle-label" x="294" y="35">B</text><text className="angle-label" x="550" y="117">C</text><path className="angle-arc" d="M258 213 Q290 176 302 185"/><path className="angle-arc" d="M307 185 Q354 181 381 199"/></svg><span className="angle-caption">∠AOB и ∠BOC: общая вершина O, общая сторона OB</span></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirtyEightStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function AngleNotationMasteryPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonThirtyEightStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==38||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonThirtyEightStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonThirtyEightStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player" aria-label="Урок 38. Угол. Обозначение углов: мастерская"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<MasteryDiagram kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} autoCapitalize="characters"/></div>}<button type="button" className="check-button" disabled={!response.trim()} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 11 · урок 2 из 2 завершён</strong><span>Равные углы · многолучевые чертежи · совпадающие стороны · общие вершины и стороны</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonThirtyEightStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonThirtyEightStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonThirtyEightStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}
