import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';
import './angleMeasurement.css';
import './protractorPractice.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='boundaries'|'protractor'|'parts'|'overlap'|'full-turn'|'twelve-rays'|'strategy'|'proof'|'check';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-43-progress-v1';
const normalize=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/\s+/g,'').replace(/[°º]/g,'').replace(/Ё/g,'Е');

export const lessonFortyThreeStages:Stage[]=[
  {id:'l43-mission',kind:'story',eyebrow:'Урок 43 · § 12 · итог',title:'Сегодня выбираешь метод сам',body:'Это пятый и завершающий урок § 12. Теперь рисунок не подсказывает готовое действие: сначала определи тип угла и геометрическое целое, затем выбери способ, вычисли и обязательно проверь результат.',note:'Карта мастерства: классифицировать → измерить или построить → увидеть части → выбрать 90°, 180° или 360° → вычислить → проверить.',diagram:'strategy'},
  {id:'l43-map',kind:'model',eyebrow:'Система § 12',title:'Четыре опоры вместо десятка отдельных правил',body:'Первое — диапазоны углов. Второе — транспортир и его шкалы. Третье — целое и его части. Четвёртое — доказательство: ответ должен согласоваться со всем рисунком, а общее утверждение — выдерживать проверку.',diagram:'boundaries'},
  {id:'l43-boundaries',kind:'model',eyebrow:'Границы',title:'90°, 180° и 360° нельзя путать',body:'Острый угол меньше 90°. Прямой равен 90°. Тупой больше 90°, но меньше 180°. Развёрнутый равен 180°. Полный оборот вокруг точки равен 360° и служит целым в задачах с лучами во все стороны.',diagram:'boundaries'},
  {id:'l43-practice1',kind:'practice',eyebrow:'Разминка · граница слева',title:'89°',body:'Один градус до прямого.',activity:{id:'l43-p1',type:'choice',prompt:'Как называется угол 89°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Острый',hint:'Сравни 89° с 90°.',explanation:'89° < 90°, значит угол острый.'},diagram:'boundaries'},
  {id:'l43-practice2',kind:'practice',eyebrow:'Разминка · точная граница',title:'90°',body:'На границе нужен точный термин.',activity:{id:'l43-p2',type:'choice',prompt:'Как называется угол 90°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Прямой',hint:'Прямой угол по определению равен 90°.',explanation:'90° — прямой угол.'},diagram:'boundaries'},
  {id:'l43-practice3',kind:'practice',eyebrow:'Разминка · граница справа',title:'91°',body:'Всего один градус после прямого.',activity:{id:'l43-p3',type:'choice',prompt:'Как называется угол 91°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Тупой',hint:'91° уже больше 90°, но ещё меньше 180°.',explanation:'90° < 91° < 180°, поэтому угол тупой.'},diagram:'boundaries'},
  {id:'l43-protractor-model',kind:'model',eyebrow:'Транспортир',title:'Шкала начинается с выбранного нуля',body:'Сначала совмести вершину с центром и одну сторону угла с нулевой линией. Затем найди именно тот 0°, от которого начинается эта сторона. Вторая шкала может показывать дополнительное число, но оно не является ответом.',note:'До чтения цифры оцени: угол выглядит острым или тупым? Такая прикидка сразу обнаруживает ошибку шкалы.',diagram:'protractor'},
  {id:'l43-practice4',kind:'practice',eyebrow:'Две шкалы',title:'43° или 137°?',body:'Начальная сторона совпадает с нулём той шкалы, на которой второй луч проходит через отметку 137°. Рисунок явно тупой.',activity:{id:'l43-p4',type:'input',prompt:'Какова градусная мера угла?',answer:'137',placeholder:'Градусы',hint:'Выбирай шкалу, где начальная сторона стоит на 0°. Прикидка: угол тупой.',explanation:'Правильное чтение — 137°. Число 43° относится к другой шкале и противоречит виду угла.'},diagram:'protractor'},
  {id:'l43-practice5',kind:'practice',eyebrow:'Прикидка до измерения',title:'121°',body:'Точное число уже известно, но проверка должна быть мгновенной.',activity:{id:'l43-p5',type:'choice',prompt:'Какой вид должен иметь измеренный угол 121°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Тупой',hint:'121° находится между 90° и 180°.',explanation:'121° — тупой угол. Если рисунок выглядит острым, установка или шкала прочитаны неверно.'},diagram:'protractor'},
  {id:'l43-construction-model',kind:'model',eyebrow:'Построение',title:'После построения сделай обратное измерение',body:'Построить угол — значит не только поставить точку на нужной риске. После проведения второго луча снова прочитай угол как при измерении: это ловит неверную шкалу, смещённый центр и ошибочную сторону отсчёта.',diagram:'check'},
  {id:'l43-practice6',kind:'practice',eyebrow:'Построение · контроль смысла',title:'135°',body:'Перед тем как брать транспортир, предскажи вид результата.',activity:{id:'l43-p6',type:'choice',prompt:'Как должен выглядеть правильно построенный угол 135°?',options:['Острым','Прямым','Тупым','Развёрнутым'],answer:'Тупым',hint:'135° больше 90° и меньше 180°.',explanation:'135° — тупой. Это простая проверка построения ещё до обратного измерения.'},diagram:'protractor'},
  {id:'l43-parts-model',kind:'model',eyebrow:'Составные углы',title:'Неизвестная часть = целое − известные части',body:'Если соседние углы без перекрытия заполняют одно целое, их градусные меры складываются. Для прямого угла сумма частей 90°, для развёрнутого — 180°. Сначала докажи, какое целое изображено.',diagram:'parts'},
  {id:'l43-practice7',kind:'practice',eyebrow:'Части прямого угла',title:'27° и неизвестная часть',body:'Два соседних угла вместе образуют прямой угол.',activity:{id:'l43-p7',type:'input',prompt:'Найди неизвестную часть.',answer:'63',placeholder:'Градусы',hint:'90 − 27.',explanation:'90° − 27° = 63°. Проверка: 27° + 63° = 90°.'},diagram:'parts'},
  {id:'l43-practice8',kind:'practice',eyebrow:'Три части развёрнутого угла',title:'48°, 67° и x',body:'Три соседние части заполняют все 180°.',activity:{id:'l43-p8',type:'input',prompt:'Найди x.',answer:'65',placeholder:'Градусы',hint:'180 − 48 − 67.',explanation:'x = 180° − 48° − 67° = 65°. Проверка: 48° + 67° + 65° = 180°.'},diagram:'parts'},
  {id:'l43-overlap-model',kind:'model',eyebrow:'Перекрывающиеся углы',title:'Здесь обычное вычитание частей уже не работает',body:'Если два составных угла имеют общую часть и их объединение равно известному целому T, сумма двух данных углов считает перекрытие дважды. Поэтому общая часть равна α + β − T.',note:'T выбирается по рисунку: 90° для прямого угла или 180° для развёрнутого.',diagram:'overlap'},
  {id:'l43-practice9',kind:'practice',eyebrow:'Перекрытие внутри 90°',title:'72° и 61°',body:'Два составных угла вместе заполняют прямой угол.',activity:{id:'l43-p9',type:'input',prompt:'Найди общую часть.',answer:'43',placeholder:'Градусы',hint:'72 + 61 − 90.',explanation:'72° + 61° − 90° = 43°. Результат меньше каждого из двух составных углов.'},diagram:'overlap'},
  {id:'l43-practice10',kind:'practice',eyebrow:'Перекрытие внутри 180°',title:'154° и 139°',body:'Два составных угла вместе заполняют развёрнутый угол.',activity:{id:'l43-p10',type:'input',prompt:'Найди общую часть.',answer:'113',placeholder:'Градусы',hint:'154 + 139 − 180.',explanation:'154° + 139° − 180° = 113°. Проверка диапазона: 113° меньше 139° и 154°.'},diagram:'overlap'},
  {id:'l43-full-turn-model',kind:'model',eyebrow:'Новое целое для обобщения',title:'Вокруг одной точки — 360°',body:'Когда лучи расходятся во все стороны из одной точки, все соседние углы одного полного обхода без пропусков и перекрытий дают 360°. Это тот же принцип «целое и части», только целое теперь полный оборот.',diagram:'full-turn'},
  {id:'l43-practice11',kind:'practice',eyebrow:'Полный оборот',title:'Пять соседних углов',body:'Четыре из пяти соседних углов равны 52°, 71°, 89° и 64°.',activity:{id:'l43-p11',type:'input',prompt:'Чему равен пятый угол?',answer:'84',placeholder:'Градусы',hint:'360 − (52 + 71 + 89 + 64).',explanation:'52° + 71° + 89° + 64° = 276°, поэтому пятый угол 360° − 276° = 84°.'},diagram:'full-turn'},
  {id:'l43-practice12',kind:'practice',eyebrow:'Выбор целого',title:'Лучами заполнен полный обход',body:'Задача не говорит «прямой» или «развёрнутый»: лучи идут вокруг одной точки до возвращения к началу.',activity:{id:'l43-p12',type:'choice',prompt:'Какую сумму должны дать все соседние углы?',options:['90°','180°','270°','360°'],answer:'360°',hint:'Один полный оборот возвращает направление к исходному.',explanation:'Полный обход вокруг точки равен 360°.'},diagram:'full-turn'},
  {id:'l43-generalize312',kind:'model',eyebrow:'Учебник № 312 · обобщение',title:'Сначала распознай структуру, потом считай',body:'В смешанных задачах этого урока важен не номер упражнения, а выбор модели: соседние части складываются, перекрывающиеся составные углы требуют вычесть объединение, а полный обход требует суммы 360°. Подписи и поворот чертежа принцип не меняют.',diagram:'strategy'},
  {id:'l43-practice13',kind:'practice',eyebrow:'Выбор стратегии',title:'Три соседних части лежат на одной прямой',body:'Известны две части, а крайние стороны образуют развёрнутый угол.',activity:{id:'l43-p13',type:'choice',prompt:'Какое целое нужно использовать?',options:['90°','180°','270°','360°'],answer:'180°',hint:'Крайние лучи направлены в противоположные стороны.',explanation:'Развёрнутый угол равен 180°, поэтому сумма трёх соседних частей должна быть 180°.'},diagram:'strategy'},
  {id:'l43-generalize314',kind:'model',eyebrow:'Учебник № 314 · систематизация',title:'Ответ без проверки — половина решения',body:'После вычисления проверь минимум два признака: арифметический — части восстанавливают целое; геометрический — полученная мера соответствует виду угла и расположению лучей. Для транспортира добавь проверку выбранной шкалы.',diagram:'check'},
  {id:'l43-practice14',kind:'practice',eyebrow:'Диагностика ошибки',title:'На рисунке тупой угол, ученик записал 38°',body:'На шкале транспортира вторая отметка рядом показывает 142°. Начальная сторона стоит на нуле шкалы 142°.',activity:{id:'l43-p14',type:'choice',prompt:'Что произошло?',options:['Угол действительно 38°','Выбрана противоположная шкала; правильный ответ 142°','Нужно сложить 38° и 142° и получить 180°','Транспортир нельзя использовать для тупых углов'],answer:'Выбрана противоположная шкала; правильный ответ 142°',hint:'Прикидка говорит, что угол тупой, то есть больше 90°.',explanation:'38° противоречит виду угла. Отсчёт начинается по другой шкале, поэтому мера равна 142°.'},diagram:'protractor'},
  {id:'l43-proof315',kind:'model',eyebrow:'Учебник № 315 · задача со звёздочкой',title:'Шесть прямых дают 12 соседних углов',body:'Если шесть различных прямых проходят через одну точку, каждая даёт два противоположных луча. Получаем 12 лучей и 12 соседних углов вокруг точки. Их общая сумма обязательно равна 360°.',note:'Нужно доказать: невозможно, чтобы каждый из этих 12 углов был не меньше 31°.',diagram:'twelve-rays'},
  {id:'l43-average',kind:'guided',eyebrow:'Идея доказательства',title:'Средняя доля полного оборота — 30°',body:'Если 360° разделить поровну между 12 соседними углами, получится 30°. Значит требование «каждый хотя бы 31°» уже выглядит невозможным: оно требует от каждого угла больше средней доли одновременно.',diagram:'proof'},
  {id:'l43-challenge1',kind:'challenge',eyebrow:'№ 315 · доказательство',title:'Проверь предположение 31°',body:'Предположим противное: каждый из 12 соседних углов не меньше 31°.',activity:{id:'l43-c1',type:'input',prompt:'Какой была бы тогда минимальная сумма 12 углов?',answer:'372',placeholder:'Градусы',hint:'31 · 12.',explanation:'31° · 12 = 372°. Но полный оборот равен только 360°, значит предположение невозможно.'},diagram:'proof'},
  {id:'l43-challenge2',kind:'challenge',eyebrow:'№ 315 · сильный вывод',title:'Что гарантирует сумма 360°?',body:'Двенадцать неотрицательных соседних углов имеют сумму 360°.',activity:{id:'l43-c2',type:'input',prompt:'Не больше скольких градусов гарантированно имеет хотя бы один из них?',answer:'30',placeholder:'Градусы',hint:'Раздели 360° на 12. Если бы все были больше результата, сумма превысила бы 360°.',explanation:'Хотя бы один угол не больше 30°. Следовательно, он тем более меньше 31°, что и требовалось.'},diagram:'twelve-rays'},
  {id:'l43-quiz1',kind:'quiz',eyebrow:'Мини-контроль · 1/5',title:'Граница 180°',body:'Никаких подсказок по виду.',activity:{id:'l43-q1',type:'choice',prompt:'Как называется угол 179°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Тупой',hint:'Сравни с 90° и 180°.',explanation:'90° < 179° < 180°, поэтому угол тупой.'},diagram:'boundaries'},
  {id:'l43-quiz2',kind:'quiz',eyebrow:'Мини-контроль · 2/5',title:'Шкала транспортира',body:'Начальная сторона стоит на 0°, вторая проходит через 42° выбранной шкалы; угол визуально острый.',activity:{id:'l43-q2',type:'input',prompt:'Запиши меру угла.',answer:'42',placeholder:'Градусы',hint:'Отсчёт начинается с нуля выбранной шкалы.',explanation:'Угол равен 42°. Прикидка подтверждает: 42° — острый.'},diagram:'protractor'},
  {id:'l43-quiz3',kind:'quiz',eyebrow:'Мини-контроль · 3/5',title:'Развёрнутый угол по частям',body:'Три соседних угла равны 39°, 85° и x.',activity:{id:'l43-q3',type:'input',prompt:'Найди x.',answer:'56',placeholder:'Градусы',hint:'180 − 39 − 85.',explanation:'x = 56°. Проверка: 39° + 85° + 56° = 180°.'},diagram:'parts'},
  {id:'l43-quiz4',kind:'quiz',eyebrow:'Мини-контроль · 4/5',title:'Полный оборот',body:'Четыре соседних угла вокруг точки: 74°, 96°, 88° и x.',activity:{id:'l43-q4',type:'input',prompt:'Найди x.',answer:'102',placeholder:'Градусы',hint:'360 − 74 − 96 − 88.',explanation:'x = 102°. Проверка: 74° + 96° + 88° + 102° = 360°.'},diagram:'full-turn'},
  {id:'l43-quiz5',kind:'quiz',eyebrow:'Мини-контроль · 5/5',title:'Логика № 315',body:'Нужно выбрать не просто правильное число, а достаточное доказательство.',activity:{id:'l43-q5',type:'choice',prompt:'Почему все 12 углов не могут быть не меньше 31°?',options:['Потому что 31° — острый угол','Потому что 31 · 12 = 372 > 360','Потому что 12 лучей образуют только 180°','Потому что один из углов обязательно прямой'],answer:'Потому что 31 · 12 = 372 > 360',hint:'Сравни минимально возможную сумму с полным оборотом.',explanation:'Если каждый угол ≥31°, сумма ≥372°, но вокруг точки она равна 360°. Получили противоречие.'},diagram:'proof'},
  {id:'l43-correction',kind:'guided',eyebrow:'Контроль и коррекция',title:'К какой категории относится твоя ошибка?',body:'Если ответ не сходился, найди причину: неверно классифицировал угол; взял не ту шкалу; выбрал не то целое; перепутал соседние и перекрывающиеся углы; не выполнил обратную проверку. Исправленная причина ценнее случайно угаданного ответа.',diagram:'check'},
  {id:'l43-synthesis',kind:'model',eyebrow:'Финальный алгоритм § 12',title:'Пять вопросов перед ответом',body:'1) Что изображено? 2) Какого вида угол должен получиться? 3) Какое целое связывает части: 90°, 180° или 360°? 4) Есть ли перекрытие? 5) Как я проверю результат независимо от первого вычисления? Если на все пять вопросов есть ответ, задача уже почти решена.',diagram:'strategy'},
  {id:'l43-summary',kind:'summary',eyebrow:'§ 12 завершён',title:'Ты собрал тему углов в одну систему',body:'Теперь ты умеешь классифицировать и измерять углы, строить их транспортиром, работать с частями 90°, 180° и 360°, находить перекрытие, проверять утверждения и доказывать невозможность через сумму полного оборота. Следующая тема — § 13 «Многоугольники. Равные фигуры».',note:'Главный результат урока — не ещё одна формула, а умение самому выбрать правильную геометрическую модель и проверить себя.',diagram:'strategy'},
];

function DiagramView({kind}:{kind:Diagram}){
  if(kind==='boundaries')return <div className="angle-diagram" aria-label="Границы видов углов"><svg viewBox="0 0 620 270" role="img"><line className="angle-ray" x1="65" y1="140" x2="555" y2="140"/><text className="measure-small" x="55" y="180">0°</text><text className="measure-label" x="285" y="105">90°</text><text className="measure-label" x="495" y="105">180°</text><text className="measure-small" x="125" y="205">острый</text><text className="measure-small" x="360" y="205">тупой</text></svg><span className="angle-caption">90° и 180° — точные границы</span></div>;
  if(kind==='protractor')return <div className="angle-diagram" aria-label="Две шкалы транспортира"><svg viewBox="0 0 620 310" role="img"><path className="measure-protractor" d="M85 245 A225 225 0 0 1 535 245" fill="none"/><line className="angle-ray" x1="310" y1="245" x2="85" y2="245"/><line className="measure-mark" x1="310" y1="245" x2="455" y2="75"/><text className="measure-label" x="420" y="105">137°</text><text className="measure-small" x="445" y="140">43°</text><text className="measure-small" x="75" y="270">0°</text><text className="measure-small" x="515" y="270">180°</text></svg><span className="angle-caption">Начинай отсчёт с нуля начальной стороны</span></div>;
  if(kind==='parts')return <div className="angle-diagram" aria-label="Соседние части угла"><svg viewBox="0 0 620 290" role="img"><g transform="translate(310 235)"><line className="angle-ray" x1="0" y1="0" x2="-235" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="235" y2="0"/><line className="measure-mark" x1="0" y1="0" x2="-110" y2="-180"/><line className="measure-mark" x1="0" y1="0" x2="80" y2="-195"/><text className="measure-small" x="-185" y="-55">часть 1</text><text className="measure-small" x="-45" y="-130">часть 2</text><text className="measure-small" x="90" y="-55">часть 3</text></g></svg><span className="angle-caption">Соседние части без перекрытия складываются</span></div>;
  if(kind==='overlap')return <div className="angle-diagram" aria-label="Перекрывающиеся составные углы"><svg viewBox="0 0 620 285" role="img"><text className="measure-label" x="80" y="80">α = левая + x</text><text className="measure-label" x="80" y="135">β = x + правая</text><text className="measure-label" x="80" y="205">x = α + β − T</text></svg><span className="angle-caption">T = 90° или 180° по рисунку</span></div>;
  if(kind==='full-turn')return <div className="angle-diagram" aria-label="Полный оборот вокруг точки"><svg viewBox="0 0 620 320" role="img"><circle className="measure-protractor" cx="310" cy="160" r="115"/><line className="angle-ray" x1="310" y1="160" x2="310" y2="45"/><line className="angle-ray" x1="310" y1="160" x2="420" y2="195"/><line className="angle-ray" x1="310" y1="160" x2="230" y2="245"/><line className="angle-ray" x1="310" y1="160" x2="205" y2="105"/><text className="measure-label" x="275" y="170">360°</text></svg><span className="angle-caption">Все соседние углы полного обхода дают 360°</span></div>;
  if(kind==='twelve-rays'){const rays=Array.from({length:12},(_,index)=>{const angle=index*30*Math.PI/180;const x=310+125*Math.cos(angle);const y=160+125*Math.sin(angle);return <line key={index} className="angle-ray twelve-ray" data-ray-index={index} x1="310" y1="160" x2={x} y2={y}/>});return <div className="angle-diagram twelve-rays-diagram" aria-label="Двенадцать лучей при пересечении шести прямых"><svg viewBox="0 0 620 330" role="img">{rays}<circle cx="310" cy="160" r="5"/><text className="measure-label" x="235" y="315">12 углов · сумма 360°</text></svg><span className="angle-caption">Если каждый ≥31°, сумма была бы ≥372° — невозможно</span></div>}
  if(kind==='proof')return <div className="angle-diagram" aria-label="Доказательство задачи 315"><svg viewBox="0 0 620 280" role="img"><text className="measure-label" x="90" y="75">12 · 31° = 372°</text><text className="measure-label" x="90" y="140">372° &gt; 360°</text><text className="measure-label" x="90" y="210">противоречие ✓</text></svg><span className="angle-caption">Полный оборот не может превысить 360°</span></div>;
  if(kind==='check')return <div className="angle-diagram" aria-label="Обратная проверка решения"><svg viewBox="0 0 620 270" role="img"><text className="measure-label" x="80" y="75">1. восстанови целое</text><text className="measure-label" x="80" y="135">2. проверь диапазон</text><text className="measure-label" x="80" y="195">3. проверь модель</text></svg><span className="angle-caption">Проверка должна быть независимой от первого шага</span></div>;
  return <div className="angle-diagram" aria-label="Выбор стратегии решения"><svg viewBox="0 0 620 290" role="img"><text className="measure-label" x="70" y="70">прямой → 90°</text><text className="measure-label" x="70" y="130">развёрнутый → 180°</text><text className="measure-label" x="70" y="190">полный оборот → 360°</text><text className="measure-small" x="70" y="245">перекрытие? тогда учти двойной счёт общей части</text></svg></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyThreeStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function AngleMasteryReviewPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonFortyThreeStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==43||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonFortyThreeStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonFortyThreeStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player measurement-player" aria-label="Урок 43. Обобщение и систематизация знаний об углах"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<DiagramView kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>setResponse(option)} disabled={isCorrect}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric" disabled={isCorrect}/></div>}<button type="button" className="check-button" disabled={!response.trim()||isCorrect} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 12 полностью завершён</strong><span>виды углов · транспортир · 90° · 180° · 360° · составные и перекрывающиеся углы · доказательство № 315</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonFortyThreeStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonFortyThreeStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonFortyThreeStages.length-1?'Готово':'Дальше →'}</button></div></article></section>;
}
