import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='basic'|'reverse'|'multi'|'construction';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-37-progress-v1';
const normalize=(value:string)=>value.trim().toUpperCase().replace(/\s+/g,'').replace(/[∠<>]/g,'').replace(/Ё/g,'Е');

export const lessonThirtySevenStages:Stage[]=[
  {id:'l37-mission',kind:'story',eyebrow:'Урок 37 · § 11 · новая тема',title:'Геометрия начинается с точного языка',body:'Угол — это не просто «уголок» на рисунке. Это фигура, образованная двумя лучами с общим началом. Сегодня научимся видеть её части и записывать название так, чтобы другой человек однозначно понял, о каком угле идёт речь.',note:'Сегодня не измеряем углы в градусах — это будет в § 12. Сначала учимся правильно видеть и называть фигуру.',diagram:'basic'},
  {id:'l37-parts',kind:'model',eyebrow:'Модель',title:'Два луча и одно общее начало',body:'На рисунке лучи BA и BC имеют общее начало B. Вместе они образуют угол. Точка B — вершина угла, а лучи BA и BC — его стороны.',diagram:'basic'},
  {id:'l37-practice1',kind:'practice',eyebrow:'Практика · 1/10',title:'Найди вершину',body:'Смотри на общее начало двух лучей.',diagram:'basic',activity:{id:'l37-p1',type:'choice',prompt:'Какая точка является вершиной изображённого угла?',options:['A','B','C','A и C'],answer:'B',hint:'Вершина — общее начало двух сторон угла.',explanation:'Оба луча начинаются в точке B, значит B — вершина.'}},
  {id:'l37-practice2',kind:'practice',eyebrow:'Практика · 2/10',title:'Назови стороны',body:'Стороны угла — именно лучи, а не отдельные точки и не отрезки.',diagram:'basic',activity:{id:'l37-p2',type:'choice',prompt:'Какие лучи являются сторонами угла?',options:['BA и BC','AB и AC','AC и CB','Точки A и C'],answer:'BA и BC',hint:'Оба луча должны начинаться в вершине B.',explanation:'Стороны угла — лучи BA и BC с общим началом B.'}},
  {id:'l37-name-rule',kind:'model',eyebrow:'Обозначение',title:'Вершина всегда стоит в середине',body:'Угол можно назвать тремя буквами: ∠ABC. Первая буква лежит на одной стороне, третья — на другой, а средняя буква B обязательно обозначает вершину.',note:'Главное правило: в трёхбуквенном названии угла вершина всегда в середине.',diagram:'basic'},
  {id:'l37-practice3',kind:'practice',eyebrow:'Практика · 3/10',title:'Выбери правильное название',body:'Проверь среднюю букву.',diagram:'basic',activity:{id:'l37-p3',type:'choice',prompt:'Как можно правильно назвать изображённый угол?',options:['∠ABC','∠BAC','∠ACB','∠AB'],answer:'∠ABC',hint:'Вершина B должна стоять второй.',explanation:'В ∠ABC буква B находится в середине и обозначает вершину.'}},
  {id:'l37-practice4',kind:'guided',eyebrow:'Практика · 4/10',title:'Средняя буква — контрольная точка',body:'Запиши только букву вершины.',activity:{id:'l37-p4',type:'input',prompt:'В названии ∠KLM какая точка является вершиной? Введи одну букву.',answer:'L',placeholder:'Буква',hint:'Вершина стоит в середине трёхбуквенного названия.',explanation:'В ∠KLM средняя буква L — вершина угла.'}},
  {id:'l37-reverse',kind:'model',eyebrow:'Два имени',title:'Один угол можно прочитать в двух направлениях',body:'Если стороны угла — BA и BC, то один и тот же угол можно записать как ∠ABC или ∠CBA. Мы просто начинаем название с другой стороны, но вершина B остаётся в середине.',diagram:'reverse'},
  {id:'l37-practice5',kind:'practice',eyebrow:'Практика · 5/10',title:'Узнай тот же угол',body:'Поменяй местами только крайние буквы.',activity:{id:'l37-p5',type:'choice',prompt:'Какая запись обозначает тот же угол, что и ∠MNP?',options:['∠PNM','∠NMP','∠MPN','∠PMN'],answer:'∠PNM',hint:'Вершина N должна остаться в середине.',explanation:'∠MNP и ∠PNM имеют одну вершину N и те же две стороны.'}},
  {id:'l37-one-letter',kind:'model',eyebrow:'Короткая запись',title:'Иногда угол можно назвать одной буквой',body:'Если из точки B на рисунке выходят только две нужные стороны и нет опасности спутать угол с другим, можно написать просто ∠B. Но если из B выходит три или больше лучей, одной буквы часто недостаточно.',diagram:'basic'},
  {id:'l37-practice6',kind:'practice',eyebrow:'Практика · 6/10',title:'Когда одной буквы достаточно?',body:'Ищи неоднозначность.',activity:{id:'l37-p6',type:'choice',prompt:'На рисунке из точки Q выходят только два луча QA и QC. Можно ли этот единственный угол кратко назвать ∠Q?',options:['Да','Нет'],answer:'Да',hint:'Других углов с вершиной Q на таком рисунке нет.',explanation:'Если угол с вершиной Q единственный, краткая запись ∠Q однозначна.'}},
  {id:'l37-multi-model',kind:'model',eyebrow:'Несколько лучей',title:'Три луча создают несколько углов',body:'Из вершины O выходят лучи OA, OB и OC. Теперь есть углы ∠AOB, ∠BOC и ∠AOC. Запись ∠O уже не объясняет, какой именно из них имеется в виду.',diagram:'multi'},
  {id:'l37-practice7',kind:'practice',eyebrow:'Практика · 7/10',title:'Назови нужный угол',body:'Смотри, какие две стороны ограничивают нужную область.',diagram:'multi',activity:{id:'l37-p7',type:'choice',prompt:'Как называется угол между лучами OA и OB?',options:['∠AOB','∠AOC','∠BOC','∠OAB'],answer:'∠AOB',hint:'Обе крайние буквы лежат на нужных лучах, O — вершина.',explanation:'Луч OA и луч OB образуют ∠AOB (или ∠BOA).'}},
  {id:'l37-practice8',kind:'practice',eyebrow:'Практика · 8/10',title:'Различи соседние углы',body:'У общей вершины могут быть разные пары сторон.',diagram:'multi',activity:{id:'l37-p8',type:'choice',prompt:'Какой угол образован лучами OB и OC?',options:['∠BOC','∠AOB','∠AOC','∠BCO'],answer:'∠BOC',hint:'O должно стоять в середине.',explanation:'Лучи OB и OC образуют угол ∠BOC.'}},
  {id:'l37-construction',kind:'model',eyebrow:'Построение',title:'Как построить угол по названию',body:'Чтобы построить ∠KLM, сначала отмечаем вершину L. Затем проводим из L два луча: один через K, другой через M. Порядок букв заранее говорит, где находится вершина.',diagram:'construction'},
  {id:'l37-practice9',kind:'guided',eyebrow:'Практика · 9/10',title:'Порядок построения',body:'Первый шаг задаёт всю фигуру.',activity:{id:'l37-p9',type:'choice',prompt:'С чего разумнее начать построение ∠RST?',options:['Отметить точку S — вершину','Отметить только точку R','Провести отрезок RT','Сразу измерить градусы'],answer:'Отметить точку S — вершину',hint:'Средняя буква определяет общее начало сторон.',explanation:'В ∠RST вершина S, поэтому сначала отмечаем S, затем строим лучи SR и ST.'}},
  {id:'l37-errors',kind:'model',eyebrow:'Типичные ошибки',title:'Самая опасная ошибка — вершина не в середине',body:'Если вершина угла B, запись ∠BAC неверно называет эту фигуру: в ней вершиной считается A. Ещё одна ошибка — путать луч BA с отрезком BA: сторона угла продолжается от вершины бесконечно в одном направлении.'},
  {id:'l37-practice10',kind:'guided',eyebrow:'Практика · 10/10',title:'Найди ошибочную запись',body:'Проверь положение вершины.',activity:{id:'l37-p10',type:'choice',prompt:'Вершина угла — D, на его сторонах лежат C и E. Какая запись НЕ может обозначать этот угол?',options:['∠CDE','∠EDC','∠CED','∠D'],answer:'∠CED',hint:'В трёхбуквенной записи D должна быть второй.',explanation:'В ∠CED средней буквой является E, значит эта запись задаёт вершину E, а не D.'}},
  {id:'l37-control-intro',kind:'model',eyebrow:'Мини-контроль',title:'Теперь без подсказки рисунка',body:'Шесть заданий проверят определения, чтение обозначений и неоднозначные случаи.'},
  {id:'l37-quiz1',kind:'quiz',eyebrow:'Контроль · 1/6',title:'Определение угла',body:'Выбери точную формулировку.',activity:{id:'l37-q1',type:'choice',prompt:'Что образует угол?',options:['Два луча с общим началом','Две любые прямые','Два отрезка одинаковой длины','Три точки на одной прямой'],answer:'Два луча с общим началом',hint:'У сторон угла одна общая начальная точка.',explanation:'Угол — фигура из двух лучей с общим началом.'}},
  {id:'l37-quiz2',kind:'quiz',eyebrow:'Контроль · 2/6',title:'Чтение записи',body:'Средняя буква решает всё.',activity:{id:'l37-q2',type:'input',prompt:'Какая точка является вершиной ∠XYZ? Введи букву.',answer:'Y',placeholder:'Буква',hint:'Вершина находится в середине.',explanation:'Вершина ∠XYZ — Y.'}},
  {id:'l37-quiz3',kind:'quiz',eyebrow:'Контроль · 3/6',title:'Обратное имя',body:'Сохрани вершину.',activity:{id:'l37-q3',type:'choice',prompt:'Как ещё можно записать тот же угол, что и ∠ABC?',options:['∠CBA','∠ACB','∠BAC','∠BCA'],answer:'∠CBA',hint:'Поменяй местами A и C, оставив B в центре.',explanation:'∠ABC и ∠CBA задают те же стороны BA и BC.'}},
  {id:'l37-quiz4',kind:'quiz',eyebrow:'Контроль · 4/6',title:'Несколько углов',body:'Одна буква может стать неоднозначной.',activity:{id:'l37-q4',type:'choice',prompt:'Из точки O выходят три луча OA, OB и OC. Почему запись ∠O недостаточна?',options:['Неясно, какая пара лучей задаёт угол','Угол нельзя обозначать буквой O','Вершина должна быть только A','Нужно обязательно знать градусную меру'],answer:'Неясно, какая пара лучей задаёт угол',hint:'С вершиной O здесь существует несколько углов.',explanation:'Нужно указать две стороны, например ∠AOB или ∠BOC.'}},
  {id:'l37-quiz5',kind:'quiz',eyebrow:'Контроль · 5/6',title:'Стороны по названию',body:'Читай от вершины к крайним буквам.',activity:{id:'l37-q5',type:'choice',prompt:'Какие лучи являются сторонами ∠KLM?',options:['LK и LM','KL и KM','MK и ML','KM и LM'],answer:'LK и LM',hint:'Вершина L, оба луча начинаются в L.',explanation:'Стороны ∠KLM — лучи LK и LM.'}},
  {id:'l37-quiz6',kind:'quiz',eyebrow:'Контроль · 6/6',title:'Правильная запись',body:'Проверь вершину и стороны.',activity:{id:'l37-q6',type:'choice',prompt:'Вершина P, на сторонах лежат A и T. Какие две трёхбуквенные записи правильны?',options:['∠APT и ∠TPA','∠PAT и ∠ATP','∠PTA и ∠TAP','∠ATP и ∠TPA'],answer:'∠APT и ∠TPA',hint:'P должна стоять в середине обеих записей.',explanation:'Крайние буквы можно менять местами, но P остаётся в центре.'}},
  {id:'l37-challenge1',kind:'challenge',eyebrow:'Challenge · 1/2',title:'Сколько углов назовём?',body:'У одной вершины четыре луча.',activity:{id:'l37-c1',type:'choice',prompt:'Из точки O выходят лучи OA, OB, OC и OD. Сколько разных углов можно назвать, выбирая любые две стороны?',options:['4','5','6','8'],answer:'6',hint:'Выбираем пары лучей: AB, AC, AD, BC, BD, CD.',explanation:'Каждая пара из четырёх лучей задаёт угол: всего 6 пар.'}},
  {id:'l37-challenge2',kind:'challenge',eyebrow:'Challenge · 2/2',title:'Геометрический детектив',body:'Определи фигуру только по записи.',activity:{id:'l37-c2',type:'choice',prompt:'Углы ∠AOB и ∠BOC имеют общую сторону. Какая это сторона?',options:['OB','OA','OC','AC'],answer:'OB',hint:'Стороны первого: OA и OB; второго: OB и OC.',explanation:'Оба угла содержат луч OB, значит это их общая сторона.'}},
  {id:'l37-recap',kind:'model',eyebrow:'Карта знаний',title:'Пять правил, которые нужно унести из урока',body:'1) угол образуют два луча с общим началом; 2) общее начало — вершина; 3) лучи — стороны; 4) в трёхбуквенном имени вершина всегда в середине; 5) при нескольких углах с одной вершиной используем три буквы.'},
  {id:'l37-summary',kind:'summary',eyebrow:'Финиш',title:'Ты научился говорить на языке углов',body:'Теперь по записи ∠ABC можно восстановить вершину B и стороны BA и BC, а по рисунку — выбрать однозначное название угла. Следующий урок закрепит § 11 на более сложных чертежах.',note:'После основной части пройди обязательную практику из 20 заданий.'},
];

function AngleDiagram({kind}:{kind:Diagram}){
  if(kind==='multi')return <div className="angle-diagram" aria-label="Три луча OA, OB и OC с общей вершиной O"><svg viewBox="0 0 600 300" role="img"><line className="angle-ray" x1="290" y1="240" x2="90" y2="90"/><line className="angle-ray" x1="290" y1="240" x2="300" y2="45"/><line className="angle-ray" x1="290" y1="240" x2="520" y2="110"/><circle className="angle-point" cx="290" cy="240" r="6"/><text className="angle-label" x="272" y="275">O</text><text className="angle-label" x="65" y="82">A</text><text className="angle-label" x="292" y="35">B</text><text className="angle-label" x="530" y="105">C</text><path className="angle-arc" d="M250 210 Q287 170 298 185"/><path className="angle-arc" d="M304 185 Q355 177 375 192"/></svg><span className="angle-caption">Из O выходят три луча: OA, OB, OC</span></div>;
  if(kind==='construction')return <div className="angle-diagram" aria-label="Угол KLM с вершиной L"><svg viewBox="0 0 600 300" role="img"><line className="angle-ray" x1="285" y1="235" x2="105" y2="80"/><line className="angle-ray" x1="285" y1="235" x2="515" y2="105"/><circle className="angle-point" cx="285" cy="235" r="6"/><text className="angle-label" x="90" y="72">K</text><text className="angle-label" x="270" y="272">L</text><text className="angle-label" x="525" y="102">M</text><path className="angle-arc" d="M244 200 Q286 157 339 204"/></svg><span className="angle-caption">∠KLM: L — вершина, LK и LM — стороны</span></div>;
  return <div className="angle-diagram" aria-label="Угол ABC с вершиной B"><svg viewBox="0 0 600 300" role="img"><line className="angle-ray" x1="290" y1="235" x2="95" y2="85"/><line className="angle-ray" x1="290" y1="235" x2="515" y2="100"/><circle className="angle-point" cx="290" cy="235" r="6"/><text className="angle-label" x="75" y="78">A</text><text className="angle-label" x="272" y="272">B</text><text className="angle-label" x="525" y="98">C</text><path className="angle-arc" d="M250 205 Q290 160 343 202"/></svg><span className="angle-caption">{kind==='reverse'?'Один угол: ∠ABC = ∠CBA':'∠ABC: B — вершина, BA и BC — стороны'}</span></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirtySevenStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function AngleNotationPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonThirtySevenStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==37||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonThirtySevenStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonThirtySevenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player" aria-label="Урок 37. Угол. Обозначение углов"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<AngleDiagram kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} autoCapitalize="characters"/></div>}<button type="button" className="check-button" disabled={!response.trim()} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 11 · урок 1 из 2 завершён</strong><span>Вершина · стороны угла · трёхбуквенная запись · однозначные обозначения</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonThirtySevenStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonThirtySevenStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonThirtySevenStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}
