import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'rate'|'field'|'tiles'|'paint'|'factors'|'equal'|'home'|'verify'|'final';
export type LessonSeventySixStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-76-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventySixStages:LessonSeventySixStage[]=[
{id:'l76-mission',kind:'story',eyebrow:'Урок 76 · § 21 · практическое закрепление',title:'Площадь в реальных расчётах',body:'Сегодня формула S=ab работает не сама по себе: после площади нужно вычислять расход семян, количество плиток или массу краски, а затем сравнивать требуемое количество с имеющимся.',note:'Технологическая карта урока 76: устно № 3, с. 141; № 580, 581, 583, 590, 592; домашнее задание § 21, № 582, 591.',visual:'mission'},
{id:'l76-oral-model',kind:'guided',eyebrow:'Актуализация · устно № 3, с. 141',title:'Насосы: сначала производительность',body:'Точное условие: пять одинаковых насосов за 6 минут перекачивают 450 л воды. Нужно узнать, сколько литров один такой насос перекачает за 8 минут.',visual:'rate',sourceExercise:'Устно № 3, с. 141'},
{id:'l76-oral-unit-rate',kind:'practice',eyebrow:'Устно № 3 · шаг 1',title:'Сколько даёт один насос за минуту?',body:'Пять насосов за 6 минут — это 30 насосо-минут работы.',activity:{id:'l76-p1',type:'input',prompt:'450 : (5·6) = ? л за одну насосо-минуту',answer:'15',placeholder:'л',hint:'5·6=30, затем 450:30.',explanation:'Один насос за минуту перекачивает 15 л.'},visual:'rate',sourceExercise:'Устно № 3, с. 141'},
{id:'l76-oral-answer',kind:'practice',eyebrow:'Устно № 3 · шаг 2',title:'Теперь восемь минут',body:'Один насос перекачивает 15 л за минуту.',activity:{id:'l76-p2',type:'input',prompt:'15·8 = ? л',answer:'120',placeholder:'л',hint:'Умножь минутную производительность на 8.',explanation:'За 8 минут один насос перекачает 120 л.'},visual:'rate',sourceExercise:'Устно № 3, с. 141'},
{id:'l76-580-model',kind:'guided',eyebrow:'№ 580',title:'Поле и норма высева',body:'Точное условие: поле 500 м × 400 м; на 1 га нужно 260 кг гороха. Проверяем, хватит ли 5 т.',visual:'field',sourceExercise:'№ 580'},
{id:'l76-580-area',kind:'practice',eyebrow:'№ 580 · шаг 1',title:'Площадь поля в м²',body:'Стороны уже выражены в одинаковых единицах.',activity:{id:'l76-p3',type:'input',prompt:'500·400 = ? м²',answer:'200000',placeholder:'м²',hint:'5·4=20 и добавь четыре нуля.',explanation:'Площадь поля 200 000 м².'},visual:'field',sourceExercise:'№ 580'},
{id:'l76-580-ha',kind:'practice',eyebrow:'№ 580 · шаг 2',title:'Переведи площадь в гектары',body:'1 га=10 000 м².',activity:{id:'l76-p4',type:'input',prompt:'200 000 м² = ? га',answer:'20',placeholder:'га',hint:'Раздели на 10 000.',explanation:'Поле имеет площадь 20 га.'},visual:'field',sourceExercise:'№ 580'},
{id:'l76-580-seed',kind:'practice',eyebrow:'№ 580 · шаг 3',title:'Сколько гороха требуется?',body:'На каждый гектар требуется 260 кг.',activity:{id:'l76-p5',type:'input',prompt:'20·260 = ? кг',answer:'5200',placeholder:'кг',hint:'26·2=52, затем учти сотни.',explanation:'Для поля нужно 5200 кг гороха.'},visual:'rate',sourceExercise:'№ 580'},
{id:'l76-580-enough',kind:'quiz',eyebrow:'№ 580 · вывод',title:'Хватит ли пяти тонн?',body:'5 т=5000 кг, а требуется 5200 кг.',activity:{id:'l76-p6',type:'choice',prompt:'Хватит ли 5 т гороха?',options:['нет','да','ровно хватит'],answer:'нет',hint:'Сравни 5000 и 5200.',explanation:'Нет: 5000 кг меньше 5200 кг.'},visual:'verify',sourceExercise:'№ 580'},
{id:'l76-580-shortage',kind:'practice',eyebrow:'№ 580 · контроль',title:'Насколько не хватит?',body:'Разность показывает запас или недостачу.',activity:{id:'l76-p7',type:'input',prompt:'5200−5000 = ? кг',answer:'200',placeholder:'кг',hint:'Вычти имеющуюся массу из требуемой.',explanation:'Не хватает 200 кг.'},visual:'verify',sourceExercise:'№ 580'},
{id:'l76-581-model',kind:'guided',eyebrow:'№ 581',title:'Кафель: площадь стены и одной плитки',body:'Точное условие: стена 4 м 50 см × 3 м, плитка — квадрат 15 см × 15 см, в одном ящике 30 плиток, всего 20 ящиков.',visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-length',kind:'practice',eyebrow:'№ 581 · шаг 1',title:'Согласуй единицы',body:'Удобно всё считать в сантиметрах.',activity:{id:'l76-p8',type:'input',prompt:'4 м 50 см = ? см',answer:'450',placeholder:'см',hint:'4 м=400 см.',explanation:'4 м 50 см=450 см.'},visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-wall',kind:'practice',eyebrow:'№ 581 · шаг 2',title:'Площадь стены',body:'Высота 3 м=300 см.',activity:{id:'l76-p9',type:'input',prompt:'450·300 = ? см²',answer:'135000',placeholder:'см²',hint:'45·3=135 и добавь три нуля.',explanation:'Площадь стены 135 000 см².'},visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-tile',kind:'practice',eyebrow:'№ 581 · шаг 3',title:'Площадь одной плитки',body:'Плитка квадратная со стороной 15 см.',activity:{id:'l76-p10',type:'input',prompt:'15² = ? см²',answer:'225',placeholder:'см²',hint:'15·15.',explanation:'Одна плитка покрывает 225 см².'},visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-needed',kind:'practice',eyebrow:'№ 581 · шаг 4',title:'Сколько плиток нужно?',body:'Количество плиток — площадь стены, делённая на площадь плитки.',activity:{id:'l76-p11',type:'input',prompt:'135000 : 225 = ? плиток',answer:'600',placeholder:'шт.',hint:'225·6=1350, значит 225·600=135000.',explanation:'Нужно 600 плиток.'},visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-available',kind:'practice',eyebrow:'№ 581 · шаг 5',title:'Сколько плиток куплено?',body:'20 ящиков по 30 плиток.',activity:{id:'l76-p12',type:'input',prompt:'20·30 = ? плиток',answer:'600',placeholder:'шт.',hint:'2·3=6 и два нуля.',explanation:'В 20 ящиках 600 плиток.'},visual:'tiles',sourceExercise:'№ 581'},
{id:'l76-581-conclusion',kind:'quiz',eyebrow:'№ 581 · вывод',title:'Сравни требуемое и имеющееся',body:'Нужно 600 плиток и имеется 600.',activity:{id:'l76-p13',type:'choice',prompt:'Хватит ли 20 ящиков?',options:['ровно хватит','не хватит','останется целый ящик'],answer:'ровно хватит',hint:'Обе величины равны 600.',explanation:'Да, плиток ровно столько, сколько требуется.'},visual:'verify',sourceExercise:'№ 581'},
{id:'l76-583-model',kind:'guided',eyebrow:'№ 583',title:'Краска: расход на квадратный метр',body:'Точное условие: 180 г эмали на 1 м², стена 6 м × 3 м, в наличии 3 кг.',visual:'paint',sourceExercise:'№ 583'},
{id:'l76-583-area',kind:'practice',eyebrow:'№ 583 · шаг 1',title:'Площадь стены',body:'Стороны выражены в метрах.',activity:{id:'l76-p14',type:'input',prompt:'6·3 = ? м²',answer:'18',placeholder:'м²',hint:'Умножь длину на высоту.',explanation:'Площадь стены 18 м².'},visual:'paint',sourceExercise:'№ 583'},
{id:'l76-583-paint',kind:'practice',eyebrow:'№ 583 · шаг 2',title:'Масса краски',body:'Каждый квадратный метр требует 180 г.',activity:{id:'l76-p15',type:'input',prompt:'18·180 = ? г',answer:'3240',placeholder:'г',hint:'18·18=324, затем умножь на 10.',explanation:'Потребуется 3240 г, то есть 3 кг 240 г.'},visual:'paint',sourceExercise:'№ 583'},
{id:'l76-583-enough',kind:'quiz',eyebrow:'№ 583 · вывод',title:'Сравнение с 3 кг',body:'3 кг=3000 г, требуется 3240 г.',activity:{id:'l76-p16',type:'choice',prompt:'Хватит ли 3 кг эмали?',options:['нет','да','ровно хватит'],answer:'нет',hint:'3000<3240.',explanation:'Нет, имеющейся эмали недостаточно.'},visual:'verify',sourceExercise:'№ 583'},
{id:'l76-583-shortage',kind:'practice',eyebrow:'№ 583 · контроль',title:'Вычисли недостачу',body:'Требуемое минус имеющееся.',activity:{id:'l76-p17',type:'input',prompt:'3240−3000 = ? г',answer:'240',placeholder:'г',hint:'Вычти 3000.',explanation:'Не хватает 240 г эмали.'},visual:'verify',sourceExercise:'№ 583'},
{id:'l76-590-source',kind:'model',eyebrow:'№ 590 · source checkpoint',title:'Перебор прямоугольников площади 12',body:'Полное условие № 590 не реконструируем. Методическое пособие точно указывает способ: перебрать пары натуральных чисел с произведением 12 и для каждой пары определить число квадратов со стороной 2 см, которые помещаются в таком прямоугольнике.',note:'Подтверждённая таблица методички: 1×12→0, 2×6→3, 3×4→2, 4×3→2, 6×2→3, 12×1→0.',visual:'factors',sourceExercise:'№ 590 · методический комментарий'},
{id:'l76-590-pair',kind:'practice',eyebrow:'№ 590 · методический комментарий',title:'Пара 2 × 6',body:'В прямоугольнике 2×6 квадрат 2×2 помещается один раз по первой стороне и три раза по второй.',activity:{id:'l76-p18',type:'input',prompt:'Сколько квадратов 2×2 помещается в прямоугольнике 2×6?',answer:'3',placeholder:'шт.',hint:'1·3.',explanation:'Помещаются 3 квадрата.'},visual:'factors',sourceExercise:'№ 590 · подтверждённая таблица'},
{id:'l76-590-max',kind:'practice',eyebrow:'№ 590 · перебор',title:'Максимум по таблице',body:'Сравни значения 0, 3, 2, 2, 3, 0.',activity:{id:'l76-p19',type:'input',prompt:'Какое наибольшее число квадратов получается?',answer:'3',placeholder:'шт.',hint:'Найди максимум в таблице.',explanation:'Максимум равен 3.'},visual:'factors',sourceExercise:'№ 590 · подтверждённая таблица'},
{id:'l76-590-best',kind:'quiz',eyebrow:'№ 590 · перебор',title:'Какие пары дают максимум?',body:'Максимум встречается дважды из-за перестановки сторон.',activity:{id:'l76-p20',type:'choice',prompt:'Какие размеры прямоугольника дают 3 квадрата 2×2?',options:['2×6 и 6×2','3×4 и 4×3','1×12 и 12×1'],answer:'2×6 и 6×2',hint:'Сверься с подтверждённой таблицей.',explanation:'И 2×6, и 6×2 дают по 3 квадрата.'},visual:'factors',sourceExercise:'№ 590 · подтверждённая таблица'},
{id:'l76-592-source',kind:'guided',eyebrow:'№ 592 · source checkpoint',title:'Прямая через центр прямоугольника',body:'Полную формулировку и рисунок № 592 не реконструируем. Методическое пособие фиксирует нужный вывод: прямая, проходящая через точку пересечения диагоналей прямоугольника, делит его на две равные части; отдельного доказательства от ученика не требуется.',visual:'equal',sourceExercise:'№ 592 · методический комментарий'},
{id:'l76-592-conclusion',kind:'quiz',eyebrow:'№ 592 · методический вывод',title:'Что можно сказать о площадях частей?',body:'Равные части прямоугольника имеют равные площади.',activity:{id:'l76-p21',type:'choice',prompt:'Как относятся площади двух частей?',options:['равны','первая всегда больше','вторая всегда больше','зависит от наклона прямой'],answer:'равны',hint:'Методический комментарий прямо говорит о двух равных частях.',explanation:'Площади двух частей равны.'},visual:'equal',sourceExercise:'№ 592 · методический комментарий'},
{id:'l76-transfer-584',kind:'model',eyebrow:'§ 21 · точный перенос № 584',title:'Равновеликие фигуры',body:'Квадрат со стороной 12 см имеет площадь 144 см². Равновеликий прямоугольник длиной 18 см имеет ширину 8 см и периметр 52 см.',visual:'equal',sourceExercise:'№ 584'},
{id:'l76-transfer-585',kind:'model',eyebrow:'§ 21 · точный перенос № 585',title:'Из прямоугольника в квадрат',body:'Прямоугольник 3×12 имеет площадь 36 см². Равновеликий квадрат имеет сторону 6 см и периметр 24 см.',visual:'equal',sourceExercise:'№ 585'},
{id:'l76-transfer-586',kind:'model',eyebrow:'§ 21 · точный перенос № 586',title:'Как меняется площадь?',body:'Если ширина равна 26 см, а длина увеличена на 4 см, добавляется полоса 26×4. Поэтому площадь увеличивается на 104 см².',visual:'field',sourceExercise:'№ 586'},
{id:'l76-transfer-587',kind:'model',eyebrow:'§ 21 · точный перенос № 587',title:'Масштабирование сторон',body:'Если обе стороны прямоугольника увеличить в 4 раза, периметр увеличится в 4 раза, а площадь — в 16 раз.',visual:'field',sourceExercise:'№ 587'},
{id:'l76-home-582',kind:'model',eyebrow:'Домашнее · № 582',title:'Теплица: точное условие восстановлено',body:'Теплица 16 м 50 см × 12 м, урожайность 30 кг с 1 м². Площадь равна 198 м², значит урожай — 5940 кг. Полное решение повторишь в обязательной практике.',visual:'home',sourceExercise:'№ 582'},
{id:'l76-home-591',kind:'model',eyebrow:'Домашнее · № 591 · source checkpoint',title:'№ 591 решаем по учебнику',body:'Технологическая карта назначает № 591, но его полная формулировка или рисунок не восстановлены надёжно. Приложение не подменяет их похожей задачей.',note:'Открой № 591 в своём учебнике и реши исходное задание.',visual:'home',sourceExercise:'№ 591 · source checkpoint'},
{id:'l76-reflection',kind:'model',eyebrow:'Рефлексия технологической карты',title:'Где стало легче?',body:'Продолжи: «Мне понравился сегодняшний урок, но …». Затем выбери: материал был трудным — и что помогло бы; или лёгким — и что теперь можешь делать самостоятельно.',visual:'verify'},
{id:'l76-summary',kind:'summary',eyebrow:'Итог урока 76',title:'Площадь стала инструментом для практических задач',body:'Ты считаешь площадь, переводишь единицы, применяешь нормы расхода, сравниваешь требуемое и имеющееся, работаешь с перебором прямоугольников и понимаешь равенство площадей частей.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 77 — обобщение § 21.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'S',rate:'×',field:'га',tiles:'▦',paint:'g/m²',factors:'12',equal:'=',home:'⌂',verify:'✓',final:'76'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='rate'?'норма × площадь':kind==='field'?'S=a·b → гектары':kind==='tiles'?'площадь стены ÷ площадь плитки':kind==='paint'?'180 г на 1 м²':kind==='factors'?'1·12 = 2·6 = 3·4':kind==='equal'?'центр → две равные части':'§ 21 · площадь'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventySixStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function AreaAppliedPracticePlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventySixStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventySixStages.length)*100),[saved.stageIndex]);
useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==76||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventySixStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
function next(){if(saved.stageIndex>=lessonSeventySixStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
return <section className="lesson-player division-meaning-player area-applied-practice-player" data-lesson-number="76" data-source-reference="Мерзляк § 21 · технологическая карта урока 76 · устно № 3; № 580, 581, 583, 590, 592" data-source-exercise-range="580,581,583,590,592"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" onClick={check} disabled={!response}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Пока не сходится.'}</b><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} ${activity.explanation}`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><div><span>Этап {saved.stageIndex+1} из {lessonSeventySixStages.length}</span><progress value={progress} max={100}/></div><button type="button" onClick={next} disabled={saved.stageIndex===lessonSeventySixStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
