import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'unit'|'convert'|'rectangle'|'square'|'equal'|'verify'|'challenge'|'final';
export type LessonSeventyFourStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-74-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyFourStages:LessonSeventyFourStage[]=[
{id:'l74-mission',kind:'story',eyebrow:'Урок 74 · § 21 · новый материал',title:'Площадь — это не периметр и не форма',body:'Сегодня вводим новую величину: площадь показывает, какую часть плоскости занимает фигура. Измерять её будем единичными квадратами, а затем получим формулы площади прямоугольника и квадрата.',note:'Технологическая карта урока 74: устно № 1, с. 141; теория § 21; первичное закрепление № 564, 565, 566, 567, 569, 571, 572; повторение № 595; домашний перенос § 21, вопросы 1–7, № 568, 570, 573, 596(1).',visual:'mission'},
{id:'l74-oral-1a',kind:'quiz',eyebrow:'Актуализация · устно № 1, с. 141',title:'Длина перед площадью',body:'Перед квадратными единицами вспомним обычные единицы длины.',activity:{id:'l74-p1',type:'input',prompt:'Сколько сантиметров в 1 дм?',answer:'10',placeholder:'см',hint:'1 дм = 10 см.',explanation:'В одном дециметре 10 сантиметров.'},visual:'convert',sourceExercise:'Устно № 1, с. 141'},
{id:'l74-oral-1b',kind:'quiz',eyebrow:'Актуализация · устно № 1, с. 141',title:'Составная длина',body:'1 м — это 100 см, а 3 дм — ещё 30 см.',activity:{id:'l74-p2',type:'input',prompt:'Сколько сантиметров в 1 м 3 дм?',answer:'130',placeholder:'см',hint:'100+30.',explanation:'1 м 3 дм = 130 см.'},visual:'convert',sourceExercise:'Устно № 1, с. 141'},
{id:'l74-area-properties',kind:'model',eyebrow:'§ 21 · свойства площади',title:'Равные фигуры имеют равные площади',body:'Если две фигуры совпадают при наложении, они равны и их площади равны. Если фигуру разбили на несколько неперекрывающихся частей, её площадь равна сумме площадей этих частей.',note:'Обратное утверждение неверно: одинаковая площадь ещё не означает одинаковую форму.',visual:'equal'},
{id:'l74-unit-square',kind:'model',eyebrow:'§ 21 · измерение площади',title:'Единичный квадрат — мерка площади',body:'За единицу площади берут квадрат со стороной, равной единице длины. Измерить площадь фигуры — значит определить, сколько выбранных единичных квадратов в ней помещается.',visual:'unit'},
{id:'l74-unit-check',kind:'quiz',eyebrow:'Проверка понятия',title:'Что именно считаем?',body:'Линейка считает единицы длины вдоль отрезка, а площадь требует двумерной мерки.',activity:{id:'l74-p3',type:'choice',prompt:'Что подсчитывают при измерении площади?',options:['единичные квадраты','стороны фигуры','вершины фигуры','сантиметры периметра'],answer:'единичные квадраты',hint:'Единица площади сама является квадратом.',explanation:'Площадь измеряют количеством единичных квадратов.'},visual:'unit'},
{id:'l74-area-units',kind:'model',eyebrow:'§ 21 · квадратные единицы',title:'Квадратный сантиметр — не просто сантиметр с индексом',body:'1 см² — площадь квадрата со стороной 1 см. Аналогично определяются 1 дм², 1 м² и 1 км². Коэффициент перехода по длине нужно применить по двум направлениям.',visual:'convert'},
{id:'l74-564-dm',kind:'practice',eyebrow:'№ 564(1)',title:'От дм² к см²',body:'Сторона квадрата 1 дм равна 10 см, значит по каждой стороне помещается 10 сантиметровых отрезков.',activity:{id:'l74-p4',type:'input',prompt:'Сколько квадратных сантиметров в 1 дм²?',answer:'100',placeholder:'см²',hint:'10·10.',explanation:'1 дм² = 100 см².'},visual:'convert',sourceExercise:'№ 564(1)'},
{id:'l74-564-m',kind:'practice',eyebrow:'№ 564(1)',title:'От м² к см²',body:'1 м = 100 см. Квадрат со стороной 100 см содержит 100 рядов по 100 квадратных сантиметров.',activity:{id:'l74-p5',type:'input',prompt:'Сколько квадратных сантиметров в 1 м²?',answer:'10000',placeholder:'см²',hint:'100·100.',explanation:'1 м² = 10 000 см².'},visual:'convert',sourceExercise:'№ 564(1)'},
{id:'l74-564-km',kind:'practice',eyebrow:'№ 564(2)',title:'Квадратный километр',body:'1 км = 1000 м. Для площади коэффициент 1000 действует в двух измерениях.',activity:{id:'l74-p6',type:'input',prompt:'Сколько квадратных метров в 1 км²?',answer:'1000000',placeholder:'м²',hint:'1000·1000.',explanation:'1 км² = 1 000 000 м².'},visual:'convert',sourceExercise:'№ 564(2)'},
{id:'l74-rectangle-formula',kind:'guided',eyebrow:'§ 21 · формула прямоугольника',title:'Почему S = ab',body:'Если стороны прямоугольника равны a и b единиц длины, в каждом ряду помещается a единичных квадратов, а рядов b. Всего a·b квадратов, поэтому S=ab.',note:'Длины a и b перед умножением должны быть выражены в одних и тех же единицах.',visual:'rectangle'},
{id:'l74-same-units',kind:'quiz',eyebrow:'§ 21 · обязательное условие',title:'Сначала согласуй единицы',body:'Формула работает с числовыми значениями сторон в одной системе единиц.',activity:{id:'l74-p7',type:'choice',prompt:'В каких единицах должны быть выражены стороны перед вычислением S=ab?',options:['в одних и тех же','обязательно в сантиметрах','обязательно в метрах','в любых разных'],answer:'в одних и тех же',hint:'Нельзя напрямую перемножать, например, 2 м и 30 см.',explanation:'Сначала обе стороны приводят к одной единице длины.'},visual:'rectangle'},
{id:'l74-565',kind:'practice',eyebrow:'№ 565',title:'Прямоугольник 14 см × 8 см',body:'Обе стороны уже выражены в сантиметрах.',activity:{id:'l74-p8',type:'input',prompt:'Найди площадь прямоугольника, см².',answer:'112',placeholder:'см²',hint:'14·8.',explanation:'S=14·8=112 см².'},visual:'verify',sourceExercise:'№ 565'},
{id:'l74-square-formula',kind:'model',eyebrow:'§ 21 · формула квадрата',title:'Квадрат — прямоугольник с равными сторонами',body:'У квадрата обе соседние стороны равны a. Поэтому S=a·a=a².',visual:'square'},
{id:'l74-566',kind:'practice',eyebrow:'№ 566',title:'Квадрат со стороной 7 дм',body:'Площадь квадрата равна квадрату его стороны.',activity:{id:'l74-p9',type:'input',prompt:'Найди площадь квадрата, дм².',answer:'49',placeholder:'дм²',hint:'7²=7·7.',explanation:'S=7²=49 дм².'},visual:'square',sourceExercise:'№ 566'},
{id:'l74-equal-area',kind:'model',eyebrow:'§ 21 · равновеликие фигуры',title:'Одинаковая площадь не требует одинаковой формы',body:'Фигуры, имеющие равные площади, называют равновеликими. Равные фигуры обязательно равновелики, но равновеликие фигуры могут не совпадать при наложении.',visual:'equal'},
{id:'l74-equal-area-check',kind:'quiz',eyebrow:'Самопроверка',title:'Проверь обратное утверждение',body:'Например, прямоугольники 2×6 и 3×4 имеют одинаковую площадь 12, но разные стороны.',activity:{id:'l74-p10',type:'choice',prompt:'Если площади двух фигур равны, обязаны ли сами фигуры быть равными?',options:['нет','да'],answer:'нет',hint:'Вспомни прямоугольники 2×6 и 3×4.',explanation:'Нет. Они могут быть только равновеликими.'},visual:'equal'},
{id:'l74-567-model',kind:'guided',eyebrow:'№ 567',title:'Сначала восстанови вторую сторону',body:'Одна сторона прямоугольника 16 см, соседняя на 6 см длиннее. До формулы площади нужно найти эту соседнюю сторону.',visual:'rectangle',sourceExercise:'№ 567'},
{id:'l74-567-side',kind:'practice',eyebrow:'№ 567',title:'Вторая сторона',body:'«На 6 см длиннее» означает прибавить 6.',activity:{id:'l74-p11',type:'input',prompt:'Чему равна соседняя сторона, см?',answer:'22',placeholder:'см',hint:'16+6.',explanation:'16+6=22 см.'},visual:'verify',sourceExercise:'№ 567'},
{id:'l74-567-area',kind:'practice',eyebrow:'№ 567',title:'Теперь площадь',body:'Размеры прямоугольника 16 см и 22 см.',activity:{id:'l74-p12',type:'input',prompt:'Найди площадь, см².',answer:'352',placeholder:'см²',hint:'16·22.',explanation:'S=16·22=352 см².'},visual:'verify',sourceExercise:'№ 567'},
{id:'l74-569-model',kind:'guided',eyebrow:'№ 569',title:'Площадь по периметру и одной стороне',body:'Периметр равен 162 дм, одна сторона — 47 дм. Полупериметр a+b равен 162:2.',visual:'rectangle',sourceExercise:'№ 569'},
{id:'l74-569-half',kind:'practice',eyebrow:'№ 569',title:'Полупериметр',body:'Для прямоугольника P=2(a+b).',activity:{id:'l74-p13',type:'input',prompt:'Чему равен a+b, дм?',answer:'81',placeholder:'дм',hint:'162:2.',explanation:'a+b=81 дм.'},visual:'verify',sourceExercise:'№ 569'},
{id:'l74-569-side',kind:'practice',eyebrow:'№ 569',title:'Неизвестная сторона',body:'Сумма соседних сторон 81 дм, одна из них 47 дм.',activity:{id:'l74-p14',type:'input',prompt:'Найди вторую сторону, дм.',answer:'34',placeholder:'дм',hint:'81−47.',explanation:'Вторая сторона 34 дм.'},visual:'verify',sourceExercise:'№ 569'},
{id:'l74-569-area',kind:'practice',eyebrow:'№ 569',title:'Финальный шаг',body:'Теперь известны обе стороны: 47 дм и 34 дм.',activity:{id:'l74-p15',type:'input',prompt:'Найди площадь, дм².',answer:'1598',placeholder:'дм²',hint:'47·34.',explanation:'S=47·34=1598 дм².'},visual:'verify',sourceExercise:'№ 569'},
{id:'l74-571-model',kind:'guided',eyebrow:'№ 571',title:'Квадрат: из периметра к площади',body:'Периметр квадрата 96 см. Сначала по P=4a найдём сторону, затем применим S=a².',visual:'square',sourceExercise:'№ 571'},
{id:'l74-571-side',kind:'practice',eyebrow:'№ 571',title:'Сторона квадрата',body:'Все четыре стороны квадрата равны.',activity:{id:'l74-p16',type:'input',prompt:'Найди сторону квадрата, см.',answer:'24',placeholder:'см',hint:'96:4.',explanation:'a=24 см.'},visual:'verify',sourceExercise:'№ 571'},
{id:'l74-571-area',kind:'practice',eyebrow:'№ 571',title:'Площадь квадрата',body:'Используй найденную сторону 24 см.',activity:{id:'l74-p17',type:'input',prompt:'Найди площадь, см².',answer:'576',placeholder:'см²',hint:'24².',explanation:'S=24²=576 см².'},visual:'square',sourceExercise:'№ 571'},
{id:'l74-572-model',kind:'guided',eyebrow:'№ 572',title:'Сначала единицы: 4 м 8 дм',body:'Периметр прямоугольника равен 4 м 8 дм, одна сторона в 5 раз больше соседней. Удобно перевести весь периметр в дециметры.',visual:'convert',sourceExercise:'№ 572'},
{id:'l74-572-perimeter',kind:'practice',eyebrow:'№ 572',title:'Переведи периметр',body:'4 м = 40 дм.',activity:{id:'l74-p18',type:'input',prompt:'Сколько дециметров в 4 м 8 дм?',answer:'48',placeholder:'дм',hint:'40+8.',explanation:'4 м 8 дм = 48 дм.'},visual:'convert',sourceExercise:'№ 572'},
{id:'l74-572-side',kind:'practice',eyebrow:'№ 572',title:'Отношение сторон 1:5',body:'Полупериметр равен 24 дм. Если меньшая сторона x, большая 5x, то 6x=24.',activity:{id:'l74-p19',type:'input',prompt:'Найди меньшую сторону, дм.',answer:'4',placeholder:'дм',hint:'24:6.',explanation:'Меньшая сторона 4 дм, большая 20 дм.'},visual:'challenge',sourceExercise:'№ 572'},
{id:'l74-572-area',kind:'practice',eyebrow:'№ 572',title:'Площадь после восстановления сторон',body:'Стороны равны 4 дм и 20 дм.',activity:{id:'l74-p20',type:'input',prompt:'Найди площадь, дм².',answer:'80',placeholder:'дм²',hint:'4·20.',explanation:'S=80 дм².'},visual:'verify',sourceExercise:'№ 572'},
{id:'l74-595-source',kind:'model',eyebrow:'Повторение · № 595',title:'Источник отмечен, формулировку не реконструируем',body:'Технологическая карта урока 74 требует повторение № 595. Точная формулировка этого номера в доступном извлечении учебника не восстановлена надёжно, поэтому приложение не подменяет её придуманным заданием.',note:'Выполни № 595 непосредственно по учебнику. Это намеренный source-checkpoint.',visual:'map',sourceExercise:'№ 595 · source checkpoint'},
{id:'l74-questions',kind:'quiz',eyebrow:'§ 21 · вопросы 1–7',title:'Что значит измерить площадь?',body:'Вернёмся к главному смыслу нового понятия.',activity:{id:'l74-p21',type:'choice',prompt:'Как точнее всего описать измерение площади фигуры?',options:['определить, сколько единичных квадратов в ней помещается','сложить длины всех сторон','посчитать вершины','измерить самую длинную сторону'],answer:'определить, сколько единичных квадратов в ней помещается',hint:'Площадь сравнивают с выбранной единицей площади.',explanation:'Измерить площадь — определить число единичных квадратов выбранного размера.'},visual:'unit',sourceExercise:'Вопросы 1–7 § 21'},
{id:'l74-home',kind:'model',eyebrow:'Домашний перенос',title:'Те же идеи — в новых задачах',body:'По технологической карте: § 21, вопросы 1–7, № 568, 570, 573 и № 596(1). В № 568, 570 и 573 снова нужно восстановить недостающие стороны и только затем вычислить площадь.',note:'Точные условия № 568, 570 и 573 сохранены в обязательной практике этого урока.',visual:'map',sourceExercise:'№ 568, 570, 573'},
{id:'l74-596-source',kind:'model',eyebrow:'Домашнее повторение · № 596(1)',title:'Ещё один source-checkpoint без выдуманного текста',body:'Методичка назначает № 596(1), но его точная формулировка именно из используемого издания Мерзляка не извлечена надёжно. Открываем этот пункт по учебнику, а не заменяем похожей задачей из другого пособия.',visual:'map',sourceExercise:'№ 596(1) · source checkpoint'},
{id:'l74-summary',kind:'summary',eyebrow:'Итог урока 74',title:'Площадь стала измеримой величиной',body:'Ты знаешь свойства площади и смысл единичного квадрата, переводишь основные квадратные единицы, различаешь равные и равновеликие фигуры, применяешь S=ab и S=a² и сначала приводишь стороны к одинаковым единицам.',note:'Обязательная практика: 20 задач / 50 ответов. Следующий урок § 21 остаётся заблокирован до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'S',map:'§21',unit:'1□',convert:'↔',rectangle:'a·b',square:'a²',equal:'=',verify:'✓',challenge:'★',final:'74'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='unit'?'считаем единичные квадраты':kind==='convert'?'квадратные единицы':kind==='rectangle'?'S = a·b':kind==='square'?'S = a²':kind==='equal'?'равные и равновеликие':kind==='verify'?'проверь размерность':kind==='challenge'?'сначала восстанови стороны':'площадь · § 21'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyFourStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function AreaFoundationsPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyFourStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyFourStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==74||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyFourStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyFourStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player area-foundations-player" data-lesson-number="74" data-source-reference="Мерзляк § 21 · технологическая карта урока 74 · № 564, 565, 566, 567, 569, 571, 572; повторение № 595" data-source-exercise-range="564,565,566,567,569,571,572,595"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyFourStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSeventyFourStages.length-1||!canContinue}>{saved.stageIndex===lessonSeventyFourStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
