import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'convert'|'rectangle'|'square'|'equal'|'verify'|'challenge'|'final';
export type LessonSeventyFiveStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-75-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyFiveStages:LessonSeventyFiveStage[]=[
{id:'l75-mission',kind:'story',eyebrow:'Урок 75 · § 21 · закрепление',title:'Площадь: переводим, восстанавливаем, доказываем',body:'Во втором уроке § 21 закрепляем единицы площади и формулы. Главная цель — не просто получить число, а понимать, какую единицу выбрать и какое действие восстанавливает неизвестную сторону.',note:'Технологическая карта урока 75: устно № 2, с. 141; закрепление № 574, 576, 578, 589; повторение № 596(2); домашнее задание § 21, № 575, 577, 579.',visual:'mission'},
{id:'l75-oral-source',kind:'model',eyebrow:'Актуализация · устно № 2, с. 141',title:'Источник отмечен без реконструкции',body:'Технологическая карта требует устное № 2 на с. 141. Полная формулировка этого устного блока в доступном извлечении не восстановлена надёжно, поэтому приложение не выдаёт придуманное за текст учебника.',note:'Открой устно № 2 на с. 141 в учебнике; далее урок закрепляет именно нужные для § 21 связи единиц площади.',visual:'map',sourceExercise:'Устно № 2, с. 141 · source checkpoint'},
{id:'l75-area-ladder',kind:'model',eyebrow:'§ 21 · единицы площади',title:'Две опорные ступени',body:'1 а = 100 м², а 1 га = 100 а = 10 000 м². Кроме того, 1 км² = 100 га. Эти связи позволяют переводить площади без угадывания количества нулей.',visual:'convert'},
{id:'l75-574-12ha',kind:'practice',eyebrow:'№ 574(1)',title:'Гектары в ары',body:'12 гектаров нужно выразить в арах.',activity:{id:'l75-p1',type:'input',prompt:'12 га = ? а',answer:'1200',placeholder:'а',hint:'1 га = 100 а.',explanation:'12·100=1200 а.'},visual:'convert',sourceExercise:'№ 574(1)'},
{id:'l75-574-6ha28a',kind:'practice',eyebrow:'№ 574(1)',title:'Составная площадь',body:'Сначала переведи гектары в ары, затем добавь уже данные ары.',activity:{id:'l75-p2',type:'input',prompt:'6 га 28 а = ? а',answer:'628',placeholder:'а',hint:'6 га = 600 а.',explanation:'600+28=628 а.'},visual:'convert',sourceExercise:'№ 574(1)'},
{id:'l75-574-32400',kind:'practice',eyebrow:'№ 574(1)',title:'Квадратные метры в ары',body:'В одном аре 100 м².',activity:{id:'l75-p3',type:'input',prompt:'32 400 м² = ? а',answer:'324',placeholder:'а',hint:'Раздели 32 400 на 100.',explanation:'32 400:100=324 а.'},visual:'convert',sourceExercise:'№ 574(1)'},
{id:'l75-574-123800',kind:'practice',eyebrow:'№ 574(1)',title:'Ещё один перевод в ары',body:'Деление на 100 переводит квадратные метры в ары.',activity:{id:'l75-p4',type:'input',prompt:'123 800 м² = ? а',answer:'1238',placeholder:'а',hint:'123 800:100.',explanation:'123 800:100=1238 а.'},visual:'convert',sourceExercise:'№ 574(1)'},
{id:'l75-574-2km',kind:'practice',eyebrow:'№ 574(1)',title:'Км², гектары и ары вместе',body:'Переводи каждую часть в ары: 1 км² = 10 000 а, 1 га = 100 а.',activity:{id:'l75-p5',type:'input',prompt:'2 км² 14 га 5 а = ? а',answer:'21405',placeholder:'а',hint:'20 000+1 400+5.',explanation:'2 км²=20 000 а, 14 га=1400 а; всего 21 405 а.'},visual:'challenge',sourceExercise:'№ 574(1)'},
{id:'l75-574-4km',kind:'practice',eyebrow:'№ 574(1)',title:'Большая составная площадь',body:'Тот же алгоритм работает и для больших значений.',activity:{id:'l75-p6',type:'input',prompt:'4 км² 72 га 16 а = ? а',answer:'47216',placeholder:'а',hint:'40 000+7 200+16.',explanation:'Получаем 47 216 а.'},visual:'challenge',sourceExercise:'№ 574(1)'},
{id:'l75-574-5a',kind:'practice',eyebrow:'№ 574(2)',title:'Ары в квадратные метры',body:'Теперь движемся в обратную сторону.',activity:{id:'l75-p7',type:'input',prompt:'5 а = ? м²',answer:'500',placeholder:'м²',hint:'1 а = 100 м².',explanation:'5·100=500 м².'},visual:'convert',sourceExercise:'№ 574(2)'},
{id:'l75-574-17a',kind:'practice',eyebrow:'№ 574(2)',title:'17 а в м²',body:'Каждый ар содержит 100 квадратных метров.',activity:{id:'l75-p8',type:'input',prompt:'17 а = ? м²',answer:'1700',placeholder:'м²',hint:'17·100.',explanation:'17 а=1700 м².'},visual:'convert',sourceExercise:'№ 574(2)'},
{id:'l75-574-8ha',kind:'practice',eyebrow:'№ 574(2)',title:'Гектары сразу в м²',body:'1 га = 10 000 м².',activity:{id:'l75-p9',type:'input',prompt:'8 га = ? м²',answer:'80000',placeholder:'м²',hint:'8·10 000.',explanation:'8 га=80 000 м².'},visual:'convert',sourceExercise:'№ 574(2)'},
{id:'l75-574-5ha72a',kind:'practice',eyebrow:'№ 574(2)',title:'Гектары плюс ары',body:'5 га дают 50 000 м², а 72 а — ещё 7200 м².',activity:{id:'l75-p10',type:'input',prompt:'5 га 72 а = ? м²',answer:'57200',placeholder:'м²',hint:'50 000+7200.',explanation:'5 га 72 а=57 200 м².'},visual:'convert',sourceExercise:'№ 574(2)'},
{id:'l75-574-530a',kind:'practice',eyebrow:'№ 574(3)',title:'Ары в гектары и ары',body:'Выдели полные сотни аров.',activity:{id:'l75-p11',type:'input',prompt:'530 а = ? га ? а. Запиши, например: 5 га 30 а',answer:['5 га 30 а','5га30а'],hint:'500 а=5 га, остаётся 30 а.',explanation:'530 а=5 га 30 а.'},visual:'convert',sourceExercise:'№ 574(3)'},
{id:'l75-574-1204a',kind:'practice',eyebrow:'№ 574(3)',title:'1204 а',body:'1200 а — это 12 га.',activity:{id:'l75-p12',type:'input',prompt:'1204 а = ? га ? а',answer:['12 га 4 а','12га4а'],hint:'12·100=1200.',explanation:'1204 а=12 га 4 а.'},visual:'convert',sourceExercise:'№ 574(3)'},
{id:'l75-574-16300',kind:'practice',eyebrow:'№ 574(3)',title:'м² в гектары и ары',body:'Сначала переведи 16 300 м² в ары, затем выдели гектары.',activity:{id:'l75-p13',type:'input',prompt:'16 300 м² = ? га ? а',answer:['1 га 63 а','1га63а'],hint:'16 300 м²=163 а.',explanation:'163 а=1 га 63 а.'},visual:'convert',sourceExercise:'№ 574(3)'},
{id:'l75-574-85200',kind:'practice',eyebrow:'№ 574(3)',title:'85 200 м²',body:'Переведи в ары и выдели сотни аров.',activity:{id:'l75-p14',type:'input',prompt:'85 200 м² = ? га ? а',answer:['8 га 52 а','8га52а'],hint:'85 200 м²=852 а.',explanation:'852 а=8 га 52 а.'},visual:'convert',sourceExercise:'№ 574(3)'},
{id:'l75-conversion-checkpoint',kind:'model',eyebrow:'№ 574 · итог',title:'Алгоритм без лишних нулей',body:'Для площади полезно держать цепочку: 1 км²=100 га, 1 га=100 а, 1 а=100 м². Если переводишь к меньшей единице — умножай; к большей — дели.',visual:'convert'},
{id:'l75-576-model',kind:'guided',eyebrow:'№ 576',title:'Площадь известна, сторона известна',body:'Поле имеет площадь 56 а и длину 80 м. Чтобы найти ширину по S=ab, сначала площадь и длину нужно согласовать по единицам.',visual:'rectangle',sourceExercise:'№ 576'},
{id:'l75-576-area',kind:'practice',eyebrow:'№ 576',title:'56 а в квадратные метры',body:'Один ар — 100 м².',activity:{id:'l75-p15',type:'input',prompt:'56 а = ? м²',answer:'5600',placeholder:'м²',hint:'56·100.',explanation:'56 а=5600 м².'},visual:'convert',sourceExercise:'№ 576'},
{id:'l75-576-width',kind:'practice',eyebrow:'№ 576',title:'Восстанови ширину',body:'S=ab, поэтому неизвестная сторона равна площади, делённой на известную сторону.',activity:{id:'l75-p16',type:'input',prompt:'5600 м² : 80 м = ? м',answer:'70',placeholder:'м',hint:'5600:80.',explanation:'Ширина поля равна 70 м.'},visual:'rectangle',sourceExercise:'№ 576'},
{id:'l75-576-perimeter',kind:'practice',eyebrow:'№ 576',title:'Теперь периметр поля',body:'Стороны поля 80 м и 70 м.',activity:{id:'l75-p17',type:'input',prompt:'P=2·(80+70). Чему равен периметр, м?',answer:'300',placeholder:'м',hint:'80+70=150.',explanation:'P=2·150=300 м.'},visual:'verify',sourceExercise:'№ 576'},
{id:'l75-578-source',kind:'model',eyebrow:'№ 578',title:'Source-checkpoint № 578',body:'Технологическая карта включает № 578, но полная формулировка номера не восстановлена из доступного извлечения учебника с достаточной надёжностью. Поэтому приложение не подменяет её похожей задачей.',note:'Выполни № 578 по своему учебнику. Навык этого участка урока — применение площади прямоугольника и согласование единиц.',visual:'map',sourceExercise:'№ 578 · source checkpoint'},
{id:'l75-589-source',kind:'guided',eyebrow:'№ 589',title:'Равные части дают равные площади',body:'Методическое пособие даёт ключ к № 589: после проведения диагонали BD видно, что квадрат и прямоугольник состоят из четырёх соответственно равных треугольников.',note:'Полную формулировку и рисунок № 589 не реконструируем; используем только явно данный методический комментарий.',visual:'equal',sourceExercise:'№ 589 · source checkpoint'},
{id:'l75-589-proof',kind:'quiz',eyebrow:'№ 589 · идея доказательства',title:'Что следует из разбиения?',body:'Если две фигуры разложены на одинаковое число попарно равных неперекрывающихся частей, площади соответствующих частей равны.',activity:{id:'l75-p18',type:'choice',prompt:'Что можно заключить о площадях двух фигур, составленных из четырёх попарно равных треугольников?',options:['площади равны','периметры обязательно равны','фигуры обязательно совпадают при наложении','ничего нельзя заключить'],answer:'площади равны',hint:'Площадь целой фигуры равна сумме площадей её частей.',explanation:'Суммы площадей четырёх попарно равных треугольников одинаковы.'},visual:'equal',sourceExercise:'№ 589 · методический комментарий'},
{id:'l75-596-source',kind:'model',eyebrow:'Повторение · № 596(2)',title:'Повторение без выдуманного условия',body:'Технологическая карта назначает № 596(2). Точное условие этого подпункта из используемого издания не восстановлено надёжно, поэтому здесь остаётся явный source-checkpoint.',note:'Реши № 596(2) непосредственно по учебнику.',visual:'map',sourceExercise:'№ 596(2) · source checkpoint'},
{id:'l75-dictation-1',kind:'practice',eyebrow:'Методическое пособие · диктант 18',title:'Разные единицы сторон',body:'Точная задача диктанта: площадь прямоугольника со сторонами 20 дм и 4 м. Сначала переведи 4 м в 40 дм.',activity:{id:'l75-p19',type:'input',prompt:'Найди площадь прямоугольника, дм².',answer:'800',placeholder:'дм²',hint:'20·40.',explanation:'S=20·40=800 дм².'},visual:'rectangle',sourceExercise:'Диктант 18 · № 1'},
{id:'l75-dictation-2',kind:'practice',eyebrow:'Методическое пособие · диктант 18',title:'Квадрат по периметру',body:'Периметр квадрата равен 36 см. Сначала найди сторону: 36:4=9 см.',activity:{id:'l75-p20',type:'input',prompt:'Чему равна площадь квадрата, см²?',answer:'81',placeholder:'см²',hint:'9².',explanation:'S=9²=81 см².'},visual:'square',sourceExercise:'Диктант 18 · № 2'},
{id:'l75-dictation-3',kind:'practice',eyebrow:'Методическое пособие · диктант 18',title:'Периметр по площади квадрата',body:'Площадь квадрата равна 49 м², значит сторона — 7 м.',activity:{id:'l75-p21',type:'input',prompt:'Найди периметр квадрата, м.',answer:'28',placeholder:'м',hint:'4·7.',explanation:'P=4·7=28 м.'},visual:'square',sourceExercise:'Диктант 18 · № 3'},
{id:'l75-dictation-4',kind:'model',eyebrow:'Методическое пособие · диктант 18',title:'1 гектар как квадрат',body:'Если площадь квадрата равна 1 га=10 000 м², его сторона равна 100 м, потому что 100·100=10 000.',visual:'square',sourceExercise:'Диктант 18 · № 4'},
{id:'l75-dictation-5',kind:'model',eyebrow:'Методическое пособие · диктант 18',title:'4 ара',body:'4 а=400 м². Этот перевод — прямое применение связи 1 а=100 м².',visual:'convert',sourceExercise:'Диктант 18 · № 5'},
{id:'l75-dictation-6',kind:'model',eyebrow:'Методическое пособие · диктант 18',title:'Составные квадратные единицы',body:'2 дм² 4 см² = 200 см²+4 см²=204 см², поскольку 1 дм²=100 см².',visual:'convert',sourceExercise:'Диктант 18 · № 6'},
{id:'l75-dictation-7',kind:'model',eyebrow:'Методическое пособие · диктант 18',title:'Участок в арах',body:'Участок 40 м × 25 м имеет площадь 1000 м², то есть 10 а.',visual:'rectangle',sourceExercise:'Диктант 18 · № 7'},
{id:'l75-home',kind:'model',eyebrow:'Домашний перенос',title:'§ 21 · № 575, 577, 579',body:'По технологической карте домашнее задание — § 21, № 575, 577, 579. Формулировка № 575 восстановлена точно и включена в обязательную практику. № 577 и рисунок № 579 оставляем за учебником, не реконструируя недостающие детали.',note:'№ 579 требует рисунок; задача должна решаться по исходной фигуре из учебника, а не по приблизительно восстановленной схеме.',visual:'map',sourceExercise:'§ 21 · № 575, 577, 579'},
{id:'l75-reflection',kind:'model',eyebrow:'Рефлексия',title:'Что теперь стало автоматическим?',body:'Продолжи две фразы из технологической карты: «Знания, полученные на уроке, мне необходимы …» и «Я получил(а) полезную информацию о том, что …».',visual:'verify'},
{id:'l75-summary',kind:'summary',eyebrow:'Итог урока 75',title:'Единицы площади и обратные задачи закреплены',body:'Ты переводишь м², ары, гектары и км², восстанавливаешь сторону из S=ab, находишь периметр после восстановления размеров и объясняешь равенство площадей через разбиение на равные части.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 76 остаётся заблокирован до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'S',map:'§21',convert:'↔',rectangle:'a·b',square:'a²',equal:'=',verify:'✓',challenge:'★',final:'75'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='convert'?'1 км² ↔ 100 га ↔ 10 000 а':kind==='rectangle'?'S=ab · P=2(a+b)':kind==='square'?'S=a² · P=4a':kind==='equal'?'равные части → равные площади':kind==='challenge'?'собери единицы в одну':'площадь · § 21'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyFiveStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function AreaReinforcementPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyFiveStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyFiveStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==75||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyFiveStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyFiveStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player area-reinforcement-player" data-lesson-number="75" data-source-reference="Мерзляк § 21 · технологическая карта урока 75 · № 574, 576, 578, 589; повторение № 596(2)" data-source-exercise-range="574,576,578,589,596(2)"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyFiveStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSeventyFiveStages.length-1||!canContinue}>{saved.stageIndex===lessonSeventyFiveStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
