import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './associativeMultiplication.css';

type Activity={
  id:string;
  type:'choice'|'input';
  prompt:string;
  options?:string[];
  answer:string|string[];
  explanation:string;
  hint:string;
  placeholder?:string;
};
type VisualKind='mission'|'volume'|'formula'|'laws'|'pairs'|'lab'|'coefficient'|'error'|'final'|'bridge';
type Stage={
  id:string;
  title:string;
  eyebrow:string;
  kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';
  body:string;
  note?:string;
  activity?:Activity;
  visual?:VisualKind;
  sourceExercise?:string;
};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-58-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/[\s.,;:!?()[\]{}'"«»]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonFiftyEightStages:Stage[]=[
  {id:'l58-mission',kind:'story',eyebrow:'Урок 58 · § 17 · новая тема',title:'Скобки превращают длинное произведение в короткий путь',body:'В трёх и более множителях можно сначала вычислить одну группу, затем другую. Сегодня докажем, когда такая перегруппировка законна, и научимся замечать пары, которые сразу дают 10, 100 или 1000.',note:'Маршрут по учебнику Мерзляка: § 17, № 420–423 · модель → формула → удобные пары → буквенные коэффициенты.',visual:'mission'},
  {id:'l58-volume-model',kind:'model',eyebrow:'Модель свойства',title:'Один набор кубиков считают двумя маршрутами',body:'Пусть есть 4 коробки, в каждой 25 рядов по 7 кубиков. Можно сначала найти кубики в коробке: (25·7), а можно сначала объединить 4 одинаковых набора рядов: (4·25). Общее число кубиков не изменится.',note:'Меняется порядок промежуточных действий, но не сами множители и не результат.',visual:'volume'},
  {id:'l58-parentheses-model',kind:'model',eyebrow:'Два вычислительных маршрута',title:'Левые и правые скобки ведут к одному числу',body:'В выражении (4·25)·7 сначала получаем 100, а в 4·(25·7) — сначала 175. Промежуточные числа разные, итог один.',note:'Скобки показывают, какое умножение выполняется первым.',visual:'formula'},
  {id:'l58-left-route',kind:'practice',eyebrow:'Маршрут 1',title:'Сначала удобная левая пара',body:'Вычислим (4·25)·7: первый шаг даёт круглое число 100.',activity:{id:'l58-p1',type:'input',prompt:'Чему равно (4·25)·7?',answer:['700'],placeholder:'Произведение',hint:'Сначала 4·25=100, затем умножь на 7.','explanation':'(4·25)·7=100·7=700.'},visual:'formula'},
  {id:'l58-right-route',kind:'practice',eyebrow:'Маршрут 2',title:'Теперь правые скобки',body:'В выражении 4·(25·7) первым результатом будет 175.',activity:{id:'l58-p2',type:'input',prompt:'Чему равно 4·(25·7)?',answer:['700'],placeholder:'Произведение',hint:'25·7=175; теперь найди 4·175.','explanation':'4·(25·7)=4·175=700.'},visual:'formula'},
  {id:'l58-property-choice',kind:'quiz',eyebrow:'Вывод из модели',title:'Формулируем сочетательное свойство',body:'Чтобы умножить произведение двух чисел на третье число, можно первое число умножить на произведение второго и третьего.',activity:{id:'l58-p3',type:'choice',prompt:'Какая формула описывает это правило?',options:['(a·b)·c=a·(b·c)','a·b=b·a','a·(b+c)=a·b+a·c','a·1=a'],answer:'(a·b)·c=a·(b·c)',hint:'Ищи формулу, где меняются только скобки.','explanation':'В (a·b)·c=a·(b·c) порядок a, b, c сохранён, изменилась только группировка.'},visual:'formula'},
  {id:'l58-formula',kind:'model',eyebrow:'Язык математики',title:'Три множителя, один неизменный результат',body:'Буквы a, b и c могут обозначать любые натуральные числа. Формула (a·b)·c=a·(b·c) говорит не о конкретном примере, а обо всех таких произведениях.',note:'Сочетательное свойство позволяет опускать скобки в цепочке умножений: a·b·c.',visual:'formula'},
  {id:'l58-laws-compare',kind:'model',eyebrow:'Не перепутай свойства',title:'Переместительное меняет порядок, сочетательное — группы',body:'В a·b=b·a множители меняются местами. В (a·b)·c=a·(b·c) порядок a, b, c остаётся прежним. В удобных вычислениях эти свойства часто работают вместе, но это два разных шага.',note:'Перестановка отвечает на вопрос «в каком порядке?», группировка — «что умножить сначала?».',visual:'laws'},
  {id:'l58-legal-transform',kind:'quiz',eyebrow:'Проверка закона',title:'Находим чистую перегруппировку',body:'Выбери запись, в которой не изменены ни порядок множителей, ни знаки действий.',activity:{id:'l58-p4',type:'choice',prompt:'Где применено только сочетательное свойство?',options:['(6·25)·4=6·(25·4)','6·25·4=25·6·4','6·(25+4)=6·25+6·4','6·25·4=6·29'],answer:'(6·25)·4=6·(25·4)',hint:'Сравни последовательность 6, 25, 4 слева и справа.','explanation':'В первой записи сохранены множители 6, 25, 4 и их порядок; изменились только скобки.'},visual:'laws'},
  {id:'l58-pair-strategy',kind:'model',eyebrow:'Стратегия № 420',title:'Ищи пару, которая создаёт разрядную единицу',body:'Пары 2·5, 4·25 и 8·125 дают 10, 100 и 1000. После этого оставшийся множитель умножается на разрядную единицу почти мгновенно.',note:'Перед вычислением огляди всю цепочку множителей, а не начинай автоматически слева.',visual:'pairs',sourceExercise:'№ 420'},
  {id:'l58-420-a',kind:'practice',eyebrow:'№ 420(1)',title:'Пара до десяти',body:'В произведении 2·328·5 множители 2 и 5 разделены числом 328. Переместительное свойство ставит их рядом, сочетательное — объединяет.',activity:{id:'l58-p5',type:'input',prompt:'Вычисли 2·328·5 удобным способом.',answer:['3280','3 280'],placeholder:'Произведение',hint:'(2·5)·328=10·328.','explanation':'2·328·5=(2·5)·328=10·328=3280.'},visual:'pairs',sourceExercise:'№ 420(1)'},
  {id:'l58-420-b',kind:'practice',eyebrow:'№ 420(2)',title:'Пара до тысячи',body:'125 и 8 образуют тысячу, поэтому вычислять 125·43 столбиком не требуется.',activity:{id:'l58-p6',type:'input',prompt:'Вычисли 125·43·8.',answer:['43000','43 000'],placeholder:'Произведение',hint:'Сначала объедини 125 и 8.','explanation':'125·43·8=(125·8)·43=1000·43=43000.'},visual:'pairs',sourceExercise:'№ 420(2)'},
  {id:'l58-420-c',kind:'practice',eyebrow:'№ 420(3)',title:'Пара до ста',body:'25·4=100. Именно эту пару выгодно вычислить первой.',activity:{id:'l58-p7',type:'input',prompt:'Вычисли 25·243·4.',answer:['24300','24 300'],placeholder:'Произведение',hint:'Переставь 243 и 4, затем сгруппируй 25·4.','explanation':'25·243·4=(25·4)·243=100·243=24300.'},visual:'pairs',sourceExercise:'№ 420(3)'},
  {id:'l58-grouping-lab',kind:'guided',eyebrow:'Интерактивная лаборатория',title:'Переключай скобки и меняй множители',body:'Ползунки задают a, b и c. Переключатель меняет первый вычислительный шаг, а лаборатория показывает оба промежуточных результата и подтверждает равенство итогов.',note:'Попробуй изменить третий множитель: обе стороны изменятся одновременно и останутся равными.',visual:'lab'},
  {id:'l58-lab-conclusion',kind:'quiz',eyebrow:'Лаборатория · вывод',title:'Что действительно сохраняется',body:'Промежуточные результаты могут не совпадать: a·b обычно не равно b·c. Свойство утверждает равенство полных произведений.',activity:{id:'l58-p8',type:'choice',prompt:'Какой вывод верен для любых натуральных a, b, c?',options:['Полные значения (a·b)·c и a·(b·c) равны','Промежуточные значения a·b и b·c всегда равны','Скобки превращают умножение в сложение','После перегруппировки один множитель исчезает'],answer:'Полные значения (a·b)·c и a·(b·c) равны',hint:'Свойство сравнивает завершённые вычисления слева и справа.','explanation':'Итоги равны для любых a, b, c, хотя первые промежуточные произведения могут различаться.'},visual:'lab'},
  {id:'l58-420-second-half',kind:'model',eyebrow:'№ 420(4–6)',title:'Одинаковая идея выглядит по-разному',body:'Пары 4·5, 50·2 и 250·4 дают 20, 100 и 1000. Не обязательно получать только степень десяти: число 20 тоже заметно упрощает дальнейший шаг.',note:'Удобная пара — та, после которой оставшееся действие стало проще.',visual:'pairs',sourceExercise:'№ 420(4–6)'},
  {id:'l58-420-d',kind:'practice',eyebrow:'№ 420(4)',title:'Сначала получаем двадцать',body:'В 4·36·5 удобно поставить рядом 4 и 5.',activity:{id:'l58-p9',type:'input',prompt:'Вычисли 4·36·5.',answer:['720'],placeholder:'Произведение',hint:'(4·5)·36=20·36.','explanation':'4·36·5=(4·5)·36=20·36=720.'},visual:'pairs',sourceExercise:'№ 420(4)'},
  {id:'l58-420-e',kind:'practice',eyebrow:'№ 420(5)',title:'Два множителя создают сто',body:'50 и 2 выгодно объединить до умножения на 236.',activity:{id:'l58-p10',type:'input',prompt:'Вычисли 50·236·2.',answer:['23600','23 600'],placeholder:'Произведение',hint:'(50·2)·236=100·236.','explanation':'50·236·2=(50·2)·236=100·236=23600.'},visual:'pairs',sourceExercise:'№ 420(5)'},
  {id:'l58-420-f',kind:'practice',eyebrow:'№ 420(6)',title:'Четыре дополняет 250 до тысячи',body:'После группировки вычисление превращается в 1000·3.',activity:{id:'l58-p11',type:'input',prompt:'Вычисли 250·3·4.',answer:['3000','3 000'],placeholder:'Произведение',hint:'Сначала 250·4.','explanation':'250·3·4=(250·4)·3=1000·3=3000.'},visual:'pairs',sourceExercise:'№ 420(6)'},
  {id:'l58-421-model',kind:'model',eyebrow:'№ 421',title:'Свойства работают командой',body:'Чтобы собрать удобную пару, иногда надо сначала переставить множители, а затем поставить скобки. Например, 4·17·25=17·(4·25).',note:'Шаг 1 — перестановка; шаг 2 — группировка; шаг 3 — простое умножение.',visual:'laws',sourceExercise:'№ 421'},
  {id:'l58-421-a',kind:'practice',eyebrow:'№ 421(1)',title:'Сотня спрятана по краям',body:'В произведении 4·17·25 удобные множители стоят первым и последним.',activity:{id:'l58-p12',type:'input',prompt:'Вычисли 4·17·25.',answer:['1700','1 700'],placeholder:'Произведение',hint:'17·(4·25)=17·100.','explanation':'4·17·25=(4·25)·17=100·17=1700.'},visual:'pairs',sourceExercise:'№ 421(1)'},
  {id:'l58-421-b',kind:'practice',eyebrow:'№ 421(2)',title:'Десяток из первого и последнего',body:'Пара 5 и 2 превращает вычисление в 10·673.',activity:{id:'l58-p13',type:'input',prompt:'Вычисли 5·673·2.',answer:['6730','6 730'],placeholder:'Произведение',hint:'(5·2)·673=10·673.','explanation':'5·673·2=(5·2)·673=10·673=6730.'},visual:'pairs',sourceExercise:'№ 421(2)'},
  {id:'l58-421-c',kind:'challenge',eyebrow:'№ 421(3)',title:'Большое число не требует длинного умножения',body:'В 8·475·125 сначала вычисляется 8·125=1000.',activity:{id:'l58-p14',type:'input',prompt:'Вычисли 8·475·125.',answer:['475000','475 000'],placeholder:'Произведение',hint:'(8·125)·475=1000·475.','explanation':'8·475·125=(8·125)·475=1000·475=475000.'},visual:'pairs',sourceExercise:'№ 421(3)'},
  {id:'l58-combination-strategy',kind:'model',eyebrow:'Стратегия выбора',title:'Не каждая круглая пара обязана быть степенью десяти',body:'В 73·5·4 пара 5·4 даёт 20, а затем 73·20 легко найти как 73·2·10. Удобство определяется следующим шагом.',note:'Сравни возможные первые шаги и выбери тот, который уменьшает нагрузку на вычисление.',visual:'pairs',sourceExercise:'№ 421(4–6)'},
  {id:'l58-421-d',kind:'practice',eyebrow:'№ 421(4)',title:'Двадцать вместо двух отдельных множителей',body:'Переставим 73 и объединим 5·4.',activity:{id:'l58-p15',type:'input',prompt:'Вычисли 73·5·4.',answer:['1460','1 460'],placeholder:'Произведение',hint:'73·(5·4)=73·20.','explanation':'73·5·4=73·20=1460.'},visual:'pairs',sourceExercise:'№ 421(4)'},
  {id:'l58-421-e',kind:'practice',eyebrow:'№ 421(5)',title:'Сотня умножает число без столбика',body:'Множители 2 и 50 дают 100.',activity:{id:'l58-p16',type:'input',prompt:'Вычисли 2·916·50.',answer:['91600','91 600'],placeholder:'Произведение',hint:'(2·50)·916=100·916.','explanation':'2·916·50=(2·50)·916=100·916=91600.'},visual:'pairs',sourceExercise:'№ 421(5)'},
  {id:'l58-421-f',kind:'practice',eyebrow:'№ 421(6)',title:'Пять и двести создают тысячу',body:'В произведении 5·9·200 удобная пара стоит по краям.',activity:{id:'l58-p17',type:'input',prompt:'Вычисли 5·9·200.',answer:['9000','9 000'],placeholder:'Произведение',hint:'(5·200)·9=1000·9.','explanation':'5·9·200=(5·200)·9=1000·9=9000.'},visual:'pairs',sourceExercise:'№ 421(6)'},
  {id:'l58-coefficient-model',kind:'model',eyebrow:'№ 422–423',title:'Числа собираются в коэффициент, буквы сохраняются',body:'В выражении 13·2a число a означает буквенный множитель. Числовые множители 13 и 2 можно объединить: (13·2)·a=26a.',note:'При упрощении ни одна буква не исчезает и не появляется: меняется только числовой коэффициент.',visual:'coefficient',sourceExercise:'№ 422–423'},
  {id:'l58-coefficient-a',kind:'practice',eyebrow:'№ 422(1)',title:'Один буквенный множитель',body:'В 13·2a числовая часть равна 13·2.',activity:{id:'l58-p18',type:'input',prompt:'Упрости 13·2a.',answer:['26a','26а'],placeholder:'Выражение',hint:'Сначала вычисли 13·2, затем припиши a.','explanation':'13·2a=(13·2)·a=26a.'},visual:'coefficient',sourceExercise:'№ 422(1)'},
  {id:'l58-coefficient-y',kind:'practice',eyebrow:'№ 422(4)',title:'Буква между числами не мешает группировке',body:'В 28·y·5 переставим y после числовой пары.',activity:{id:'l58-p19',type:'input',prompt:'Упрости 28·y·5.',answer:['140y','140у'],placeholder:'Выражение',hint:'28·5=140; множитель y сохрани.','explanation':'28·y·5=(28·5)·y=140y.'},visual:'coefficient',sourceExercise:'№ 422(4)'},
  {id:'l58-coefficient-abc',kind:'challenge',eyebrow:'№ 422(8)',title:'Несколько чисел и несколько букв',body:'В 4a·8·b·3c числовые множители равны 4, 8 и 3, а буквенные — a, b и c.',activity:{id:'l58-p20',type:'input',prompt:'Упрости 4a·8·b·3c.',answer:['96abc','96acb','96bac','96bca','96cab','96cba','96абс'],placeholder:'Выражение',hint:'4·8·3=96; затем перепиши a, b, c.','explanation':'4a·8·b·3c=(4·8·3)·a·b·c=96abc.'},visual:'coefficient',sourceExercise:'№ 422(8)'},
  {id:'l58-error-model',kind:'model',eyebrow:'Контроль преобразования',title:'Свойство не разрешает менять действие или терять множитель',body:'Ошибочная запись 2·328·5=2·(328+5) подменяет умножение сложением. В законной перегруппировке все знаки умножения и все три множителя остаются на месте.',note:'Чек-лист: те же множители, столько же множителей, те же знаки действий, одинаковый итог.',visual:'error'},
  {id:'l58-error-choice',kind:'quiz',eyebrow:'Поиск ошибки',title:'Объясняем нарушение закона',body:'Недостаточно сказать «так нельзя»: нужно назвать конкретно, что изменилось.',activity:{id:'l58-p21',type:'choice',prompt:'Почему равенство 2·328·5=2·(328+5) неверно?',options:['Умножение 328·5 заменили сложением 328+5','Число 2 нельзя ставить первым','В произведении запрещены скобки','328 должно быть меньше 5'],answer:'Умножение 328·5 заменили сложением 328+5',hint:'Сравни знаки действий до и после преобразования.','explanation':'Сочетательное свойство меняет только группировку: верно 2·(328·5), но не 2·(328+5).'},visual:'error'},
  {id:'l58-checklist',kind:'model',eyebrow:'Самопроверка',title:'Алгоритм удобного произведения из четырёх шагов',body:'Осмотри все множители; найди удобную пару; при необходимости переставь её члены; поставь скобки и проверь, что ни один множитель не потерян. Только после этого вычисляй.',note:'Хорошая запись показывает не только ответ, но и причину, почему выбранный путь удобен.',visual:'final'},
  {id:'l58-bridge',kind:'guided',eyebrow:'Мост внутри § 17',title:'Группировка готовит распределение',body:'Сегодня мы меняли скобки в цепочке умножений. В следующей части § 17 скобки будут содержать сумму или разность: a·(b+c). Там множитель понадобится распределить на каждое слагаемое.',note:'Не смешивай свойства: (a·b)·c=a·(b·c) — сочетательное; a·(b+c)=a·b+a·c — распределительное.',visual:'bridge'},
  {id:'l58-summary',kind:'summary',eyebrow:'Урок 58 · итог',title:'Сочетательное свойство стало вычислительным инструментом',body:'Ты доказал равенство двух группировок, отличил скобки от перестановки, освоил пары до 10, 100 и 1000, решил № 420–421 и собрал числовые коэффициенты в № 422–423.',note:'Теперь пройди обязательную мастерскую: 20 задач и 50 оцениваемых ответов.',visual:'final'}
];

function GroupingLab(){
  const[a,setA]=useState(4);const[b,setB]=useState(25);const[c,setC]=useState(7);const[active,setActive]=useState<'left'|'right'>('left');const leftPair=a*b;const rightPair=b*c;const left=leftPair*c;const right=a*rightPair;
  return <div className="associative-lab" data-grouping-lab="interactive" data-active-group={active} data-left-value={left} data-right-value={right} data-equal={String(left===right)}>
    <div className="associative-lab-controls"><label>Множитель a: <b>{a}</b><input aria-label="Множитель a" type="range" min="1" max="12" step="1" value={a} onChange={event=>setA(Number(event.target.value))}/></label><label>Множитель b: <b>{b}</b><input aria-label="Множитель b" type="range" min="2" max="50" step="1" value={b} onChange={event=>setB(Number(event.target.value))}/></label><label>Множитель c: <b>{c}</b><input aria-label="Множитель c" type="range" min="1" max="12" step="1" value={c} onChange={event=>setC(Number(event.target.value))}/></label></div>
    <button type="button" className="associative-lab-toggle" onClick={()=>setActive(value=>value==='left'?'right':'left')}>{active==='left'?'Сначала a·b':'Сначала b·c'} · переключить скобки</button>
    <div className="associative-lab-routes"><span className={active==='left'?'active':''}><small>левые скобки</small><b>({a}·{b})·{c}</b><em>{leftPair}·{c}={left}</em></span><strong>=</strong><span className={active==='right'?'active':''}><small>правые скобки</small><b>{a}·({b}·{c})</b><em>{a}·{rightPair}={right}</em></span></div>
  </div>;
}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='lab')return <GroupingLab/>;
  if(kind==='mission')return <div className="associative-visual" data-visual="mission"><div className="associative-route"><span>модель</span><i>→</i><span>скобки</span><i>→</i><span>удобная пара</span><i>→</i><strong>короткое решение</strong></div></div>;
  if(kind==='volume')return <div className="associative-visual" data-visual="volume"><div className="associative-volume"><span><b>4</b><small>коробки</small></span><i>×</i><span><b>25</b><small>рядов</small></span><i>×</i><span><b>7</b><small>кубиков</small></span><strong>700 кубиков</strong></div></div>;
  if(kind==='formula')return <div className="associative-visual" data-visual="formula"><div className="associative-formula"><span><small>сначала слева</small><b>(a·b)·c</b></span><strong>=</strong><span><small>сначала справа</small><b>a·(b·c)</b></span></div></div>;
  if(kind==='laws')return <div className="associative-visual" data-visual="laws"><div className="associative-laws"><span><small>переместительное</small><b>a·b=b·a</b><em>меняем порядок</em></span><span><small>сочетательное</small><b>(a·b)·c=a·(b·c)</b><em>меняем группы</em></span></div></div>;
  if(kind==='pairs')return <div className="associative-visual" data-visual="pairs"><div className="associative-pairs"><span><b>2·5</b><strong>10</strong></span><span><b>4·25</b><strong>100</strong></span><span><b>8·125</b><strong>1000</strong></span></div></div>;
  if(kind==='coefficient')return <div className="associative-visual" data-visual="coefficient"><div className="associative-coefficient"><span>4a·8·b·3c</span><i>→</i><b>(4·8·3)·abc</b><i>→</i><strong>96abc</strong></div></div>;
  if(kind==='error')return <div className="associative-visual" data-visual="error"><div className="associative-error"><del>2·328·5=2·(328+5)</del><span>знак действия изменён ✕</span><strong>2·328·5=(2·5)·328 ✓</strong></div></div>;
  if(kind==='bridge')return <div className="associative-visual" data-visual="bridge"><div className="associative-bridge"><span><small>сегодня</small><b>(a·b)·c=a·(b·c)</b></span><i>→</i><span><small>дальше</small><b>a·(b+c)=a·b+a·c</b></span></div></div>;
  return <div className="associative-visual" data-visual="final"><div className="associative-final"><b>формула ✓</b><b>группировка ✓</b><b>пары 10/100/1000 ✓</b><b>№ 420–423 ✓</b><b>коэффициенты ✓</b><b>проверка ✓</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyEightStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function AssociativeMultiplicationPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyEightStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyEightStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==58||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyEightStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyEightStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player associative-multiplication-player" data-lesson-number="58" data-source-reference="Мерзляк § 17 · № 420–423" data-source-exercise-range="420-423"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFiftyEightStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyEightStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyEightStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
