import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './chapterTwoReview.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type Diagram=
  |{type:'panel';kind:'route'|'addition'|'path'|'equation'|'angles'|'polygon'|'rectangle'|'checklist'|'final'}
  |{type:'composite-angle';variant:'summary'|'test-6'}
  |{type:'triangles';variant:'summary'|'test-7'};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram;sourceItem?:number};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-52-progress-v1';
const normalized=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[−–—]/g,'-').replace(/[×·]/g,'X').replace(/\s+/g,'').replace(/(?:СМ|КМ|МИН|Ч|ГРАДУСА?|°|[.])$/,'');
const answerMatches=(response:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalized(response)===normalized(item))};

export const lessonFiftyTwoStages:Stage[]=[
  {id:'l52-mission',kind:'story',eyebrow:'Урок 52 · итог главы 2',title:'Не перечень правил, а карта решений',body:'Мы соберём главу 2 в единую систему и полностью выполним «Задание № 2 “Проверьте себя”» из 12 вопросов. У каждого задания будет короткий маршрут: распознать тему, выбрать правило, решить и проверить.',note:'Источник: учебник Мерзляка, страницы 102–105. Следующий урок — контрольная работа № 3.',diagram:{type:'panel',kind:'route'}},
  {id:'l52-route',kind:'model',eyebrow:'Карта главы 2',title:'Восемь опор ведут к одному результату',body:'Сложение и вычитание, формулы, уравнения, углы, многоугольники, треугольники, прямоугольники и самопроверка связаны общим умением переводить условие на язык математики.',diagram:{type:'panel',kind:'route'}},
  {id:'l52-addition-model',kind:'model',eyebrow:'Итоги главы 2 · свойства сложения',title:'Переставляй и группируй только слагаемые',body:'Переместительное свойство меняет порядок: a+b=b+a. Сочетательное меняет группировку: (a+b)+c=a+(b+c). Значение суммы остаётся тем же.',diagram:{type:'panel',kind:'addition'}},
  {id:'l52-addition-check',kind:'practice',eyebrow:'Свойства сложения · применение',title:'Собери удобную сотню',body:'В выражении (48+125)+52 число 125 можно переставить, а 48 и 52 — сгруппировать.',activity:{id:'l52-p1',type:'choice',prompt:'Какие свойства позволяют записать 125+(48+52)?',options:['Переместительное и сочетательное свойства сложения','Только переместительное свойство','Только сочетательное свойство','Свойство вычитания'],answer:'Переместительное и сочетательное свойства сложения',hint:'Изменились и порядок слагаемых, и скобки.',explanation:'125 переставили вперёд, а 48 и 52 объединили в удобную сумму 100.'},diagram:{type:'panel',kind:'addition'}},
  {id:'l52-path-model',kind:'model',eyebrow:'Итоги главы 2 · формула пути',title:'Три величины: путь, скорость и время',body:'Формула s=vt связывает путь s, скорость v и время t. Перед вычислением проверь совместимость единиц: км/ч и часы дают километры.',diagram:{type:'panel',kind:'path'}},
  {id:'l52-path-check',kind:'practice',eyebrow:'Формула пути · применение',title:'Подставь значения вместе с единицами',body:'Автобус движется 4 часа со скоростью 72 км/ч.',activity:{id:'l52-p2',type:'input',prompt:'Какой путь проедет автобус, км?',answer:'288',placeholder:'км',hint:'Вычисли 72·4.',explanation:'s=vt=72·4=288 км.'},diagram:{type:'panel',kind:'path'}},
  {id:'l52-formula-check',kind:'practice',eyebrow:'Буквенные выражения и формулы',title:'Повторяющееся слагаемое записывай коэффициентом',body:'Для 30 учеников каждый билет стоит a рублей, а экскурсовод получает 450 рублей один раз за всю группу.',activity:{id:'l52-p3',type:'choice',prompt:'Какая формула задаёт общую стоимость b?',options:['b = 30a + 450','b = a + 450','b = 30(a + 450)','b = 450a + 30'],answer:'b = 30a + 450',hint:'Раздели стоимость билетов и разовую доплату.',explanation:'30 билетов стоят 30a рублей, затем прибавляем 450 рублей за экскурсовода.'},diagram:{type:'panel',kind:'path'}},
  {id:'l52-equation-model',kind:'model',eyebrow:'Итоги главы 2 · корень уравнения',title:'Корень превращает уравнение в верное равенство',body:'Решить уравнение — найти все корни или убедиться, что их нет. После обратных действий обязательно подставь найденное число в исходную запись.',diagram:{type:'panel',kind:'equation'}},
  {id:'l52-equation-check',kind:'practice',eyebrow:'Уравнения · проверка',title:'Возвращай действия в обратном порядке',body:'В уравнении y−48=76 к обеим частям надо прибавить 48.',activity:{id:'l52-p4',type:'input',prompt:'Найди корень y.',answer:'124',placeholder:'корень',hint:'76+48.',explanation:'y=124; проверка: 124−48=76.'},diagram:{type:'panel',kind:'equation'}},
  {id:'l52-angle-map',kind:'model',eyebrow:'Итоги главы 2 · углы',title:'Границы классификации нельзя заменять догадкой',body:'Острый угол меньше 90°, прямой равен 90°, тупой больше 90°, но меньше 180°, развёрнутый равен 180°.',diagram:{type:'panel',kind:'angles'}},
  {id:'l52-angle-check',kind:'practice',eyebrow:'Виды углов · применение',title:'Сравни меру с двумя границами',body:'Угол равен 126°: он уже больше прямого, но ещё меньше развёрнутого.',activity:{id:'l52-p5',type:'choice',prompt:'Как называется угол 126°?',options:['Тупой','Острый','Прямой','Развёрнутый'],answer:'Тупой',hint:'126 находится между 90 и 180.',explanation:'90°<126°<180°, поэтому угол тупой.'},diagram:{type:'panel',kind:'angles'}},
  {id:'l52-composite-model',kind:'model',eyebrow:'Свойство величины угла',title:'Целый угол равен сумме частей',body:'Если луч проходит между сторонами угла ABC, то ∠ABC=∠ABD+∠DBC. Для развёрнутого угла сумма частей равна 180°.',diagram:{type:'composite-angle',variant:'summary'}},
  {id:'l52-composite-check',kind:'practice',eyebrow:'Части развёрнутого угла',title:'Из целого вычти известную часть',body:'Один из двух соседних углов равен 112°.',activity:{id:'l52-p6',type:'input',prompt:'Найди второй угол, °.',answer:'68',placeholder:'градусы',hint:'180−112.',explanation:'Второй угол равен 180°−112°=68°.'},diagram:{type:'composite-angle',variant:'summary'}},
  {id:'l52-polygon-model',kind:'model',eyebrow:'Итоги главы 2 · многоугольники',title:'Периметр идёт по всей замкнутой границе',body:'Многоугольник задают вершины, стороны и углы. Равные многоугольники совпадают при наложении, а периметр равен сумме длин всех сторон.',diagram:{type:'panel',kind:'polygon'}},
  {id:'l52-polygon-check',kind:'practice',eyebrow:'Периметр многоугольника',title:'Не пропусти ни одну сторону',body:'Пятиугольник имеет стороны 7, 9, 8, 6 и 10 см.',activity:{id:'l52-p7',type:'input',prompt:'Найди его периметр, см.',answer:'40',placeholder:'см',hint:'Сложи все пять длин.',explanation:'P=7+9+8+6+10=40 см.'},diagram:{type:'panel',kind:'polygon'}},
  {id:'l52-triangle-model',kind:'model',eyebrow:'Итоги главы 2 · треугольники',title:'У треугольника два независимых паспорта',body:'По углам треугольник бывает остроугольным, прямоугольным или тупоугольным; по сторонам — разносторонним, равнобедренным или равносторонним.',diagram:{type:'triangles',variant:'summary'}},
  {id:'l52-triangle-check',kind:'practice',eyebrow:'Равнобедренный треугольник',title:'Равные стороны учитывай дважды',body:'Боковые стороны равны 7 см, основание — 10 см.',activity:{id:'l52-p8',type:'input',prompt:'Найди периметр треугольника, см.',answer:'24',placeholder:'см',hint:'7+7+10.',explanation:'P=7+7+10=24 см.'},diagram:{type:'triangles',variant:'summary'}},
  {id:'l52-rectangle-model',kind:'model',eyebrow:'Итоги главы 2 · прямоугольник',title:'Четыре прямых угла и две пары равных сторон',body:'У прямоугольника противолежащие стороны равны. При длине a и ширине b периметр вычисляют по формуле P=2a+2b=2(a+b).',diagram:{type:'panel',kind:'rectangle'}},
  {id:'l52-rectangle-check',kind:'practice',eyebrow:'Периметр прямоугольника',title:'Сначала найди полупериметр',body:'Длина прямоугольника 11 см, ширина 7 см.',activity:{id:'l52-p9',type:'input',prompt:'Найди периметр, см.',answer:'36',placeholder:'см',hint:'2·(11+7).',explanation:'P=2·18=36 см.'},diagram:{type:'panel',kind:'rectangle'}},
  {id:'l52-test-intro',kind:'guided',eyebrow:'Учебник · «Проверьте себя» № 2',title:'Двенадцать вопросов — двенадцать коротких доказательств',body:'Дальше идут задания 1–12 в исходном порядке. После каждого ответа мы фиксируем правило, которое делает выбор однозначным.',note:'Не угадывай по виду вариантов: вычисляй или доказывай.',diagram:{type:'panel',kind:'checklist'}},
  {id:'l52-test-01',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 1',title:'Разность многозначных чисел',body:'Чему равна разность 738 621−239 507?',sourceItem:1,activity:{id:'l52-p10',type:'choice',prompt:'Выбери ответ.',options:['499 114','498 104','489 014','488 124'],answer:'499 114',hint:'Выполни вычитание по разрядам и проверь сложением.',explanation:'738 621−239 507=499 114.'},diagram:{type:'panel',kind:'addition'}},
  {id:'l52-test-02',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 2',title:'Сложение времени',body:'Чему равна сумма 2 ч 36 мин+6 ч 48 мин?',sourceItem:2,activity:{id:'l52-p11',type:'choice',prompt:'Выбери ответ.',options:['9 ч 34 мин','8 ч 14 мин','9 ч 24 мин','8 ч 24 мин'],answer:'9 ч 24 мин',hint:'36+48=84 минуты — это 1 час 24 минуты.',explanation:'2 ч+6 ч+1 ч=9 ч, остаётся 24 мин.'},diagram:{type:'panel',kind:'addition'}},
  {id:'l52-test-03',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 3',title:'Перевод отношения на язык равенства',body:'Число m на 18 меньше числа n.',sourceItem:3,activity:{id:'l52-p12',type:'choice',prompt:'Какое равенство выражает условие?',options:['m − n = 19','n − m = 18','m + n = 18','m = n + 18'],answer:'n − m = 18',hint:'Из большего числа вычти меньшее.',explanation:'Если m меньше n на 18, то разность n−m равна 18.'},diagram:{type:'panel',kind:'equation'}},
  {id:'l52-test-04',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 4',title:'Корень составного уравнения',body:'Найди корень уравнения (x−63)+105=175.',sourceItem:4,activity:{id:'l52-p13',type:'choice',prompt:'Выбери корень.',options:['133','7','343','217'],answer:'133',hint:'x−63=175−105.',explanation:'x−63=70, поэтому x=133; проверка: 70+105=175.'},diagram:{type:'panel',kind:'equation'}},
  {id:'l52-test-05',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 5',title:'Верное утверждение об углах',body:'Проверь каждую фразу по точным границам 90° и 180°.',sourceItem:5,activity:{id:'l52-p14',type:'choice',prompt:'Какое утверждение верно?',options:['Угол, который больше острого угла, — тупой','Угол, который меньше тупого угла, — прямой','Острый угол меньше тупого угла','Угол, который больше прямого угла, — развёрнутый'],answer:'Острый угол меньше тупого угла',hint:'Острые углы меньше 90°, тупые — больше 90°.',explanation:'Любой острый угол меньше любого тупого; остальные фразы не учитывают промежуточные виды.'},diagram:{type:'panel',kind:'angles'}},
  {id:'l52-test-06',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 6',title:'Два луча внутри развёрнутого угла',body:'∠MKB=115°, ∠AKP=94°. Найди ∠AKB.',sourceItem:6,activity:{id:'l52-p15',type:'choice',prompt:'Выбери градусную меру ∠AKB.',options:['21°','27°','29°','32°'],answer:'29°',hint:'Сначала найди ∠BKP=180°−115°.',explanation:'∠BKP=65°, поэтому ∠AKB=94°−65°=29°.'},diagram:{type:'composite-angle',variant:'test-6'}},
  {id:'l52-test-07',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 7',title:'Найди равнобедренный треугольник',body:'Сравни три набора сторон и вычисли периметр подходящей фигуры.',sourceItem:7,activity:{id:'l52-p16',type:'choice',prompt:'Каков периметр равнобедренного треугольника?',options:['24 см','16 см','30 см','20 см'],answer:'16 см',hint:'Ищи треугольник со сторонами 4, 6 и 6 см.',explanation:'Треугольник DFE равнобедренный; P=4+6+6=16 см.'},diagram:{type:'triangles',variant:'test-7'}},
  {id:'l52-test-08',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 8',title:'Соседняя сторона больше на 7 см',body:'Одна сторона прямоугольника 8 см, соседняя — на 7 см больше.',sourceItem:8,activity:{id:'l52-p17',type:'choice',prompt:'Чему равен периметр?',options:['15 см','30 см','23 см','46 см'],answer:'46 см',hint:'Сначала найди вторую сторону: 8+7.',explanation:'Вторая сторона 15 см; P=2·(8+15)=46 см.'},diagram:{type:'panel',kind:'rectangle'}},
  {id:'l52-test-09',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 9',title:'Сколько времени осталось на английский',body:'Всего 2 ч 15 мин; русский и математика — по 40 мин, история — 25 мин.',sourceItem:9,activity:{id:'l52-p18',type:'choice',prompt:'Сколько минут ушло на английский язык?',options:['40 мин','35 мин','25 мин','30 мин'],answer:'30 мин',hint:'Переведи 2 ч 15 мин в 135 минут.',explanation:'135−40−40−25=30 минут.'},diagram:{type:'panel',kind:'path'}},
  {id:'l52-test-10',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 10',title:'Равные периметры квадрата и прямоугольника',body:'Сторона квадрата 12 см; одна сторона прямоугольника 10 см.',sourceItem:10,activity:{id:'l52-p19',type:'choice',prompt:'Найди неизвестную сторону прямоугольника.',options:['8 см','26 см','2 см','14 см'],answer:'14 см',hint:'Периметр квадрата 48 см, полупериметр прямоугольника 24 см.',explanation:'10+x=24, поэтому x=14 см.'},diagram:{type:'panel',kind:'rectangle'}},
  {id:'l52-test-11',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 11',title:'Когда a+a равно a−a',body:'Левая часть равна 2a, правая — нулю.',sourceItem:11,activity:{id:'l52-p20',type:'choice',prompt:'При каком значении a верно равенство?',options:['При любом значении a','Такого значения a не существует','При a = 0','При a = 1'],answer:'При a = 0',hint:'Подставь 0, затем проверь остальные варианты.',explanation:'При a=0 обе части равны нулю; при положительном a сумма не равна разности.'},diagram:{type:'panel',kind:'equation'}},
  {id:'l52-test-12',kind:'quiz',eyebrow:'Проверьте себя № 2 · вопрос 12',title:'Формула стоимости экскурсии',body:'30 билетов по a рублей и разовая доплата 450 рублей.',sourceItem:12,activity:{id:'l52-p21',type:'choice',prompt:'Выбери формулу общей стоимости b.',options:['b = a + 450','b = 30a + 450','b = 30(a + 450)','b = 450a + 30'],answer:'b = 30a + 450',hint:'Умножь цену одного билета на число учеников.',explanation:'Стоимость билетов 30a, общая стоимость b=30a+450.'},diagram:{type:'panel',kind:'path'}},
  {id:'l52-error-check',kind:'challenge',eyebrow:'Разбор типичной ошибки',title:'Правильное число может появиться из неправильной модели',body:'Ученик для прямоугольника 8×15 см записал 8+15=23 см и назвал это периметром.',activity:{id:'l52-p22',type:'choice',prompt:'В чём ошибка ученика?',options:['Он посчитал только полупериметр','Он должен был вычесть стороны','Он перепутал сантиметры с часами','Ошибки нет'],answer:'Он посчитал только полупериметр',hint:'В границе прямоугольника каждая длина встречается дважды.',explanation:'8+15=23 см — полупериметр; полный периметр равен 46 см.'},diagram:{type:'panel',kind:'rectangle'}},
  {id:'l52-control-plan',kind:'model',eyebrow:'Алгоритм перед контрольной № 3',title:'Пять точек самопроверки',body:'Перечитай условие, назови тему, запиши правило, проверь вычисления и единицы, затем ответь именно на заданный вопрос. Этот порядок работает для арифметики и геометрии.',diagram:{type:'panel',kind:'checklist'}},
  {id:'l52-readiness',kind:'challenge',eyebrow:'Финальная готовность',title:'Выбери сильную стратегию',body:'Если ответ не совпал ни с одним вариантом, не подгоняй вычисление под тест.',activity:{id:'l52-p23',type:'choice',prompt:'Что делать сначала?',options:['Вернуться к условию, правилу и единицам','Выбрать ближайшее число','Сразу заменить знак действия','Пропустить проверку'],answer:'Вернуться к условию, правилу и единицам',hint:'Ошибка часто возникает ещё до вычислений.',explanation:'Повторная проверка модели и единиц надёжнее угадывания по вариантам.'},diagram:{type:'panel',kind:'checklist'}},
  {id:'l52-summary',kind:'summary',eyebrow:'Итог урока 52 · глава 2',title:'Карта главы собрана, тест пройден',body:'Ты связал свойства сложения, формулы, уравнения и геометрию, решил все 12 исходных вопросов «Проверьте себя» и закрепил алгоритм самопроверки перед контрольной № 3.',note:'Дальше — обязательная практика из 20 смешанных задач с Пифагором и озвучкой Sulafat.',diagram:{type:'panel',kind:'final'}}
];

function PanelDiagram({kind}:{kind:Extract<Diagram,{type:'panel'}>['kind']}){
  if(kind==='route')return <div className="chapter-two-review-panel" data-summary-topic-count="8"><div className="c2r-route">{['Сложение','Формулы','Уравнения','Углы','Многоугольники','Треугольники','Прямоугольники','Проверка'].map((item,index)=><span key={item}><b>{index+1}</b><strong>{item}</strong></span>)}</div></div>;
  if(kind==='addition')return <div className="chapter-two-review-panel" data-summary-topic="addition"><div className="c2r-formulas"><span><small>переместительное</small><b>a+b=b+a</b></span><span><small>сочетательное</small><b>(a+b)+c=a+(b+c)</b></span><span><small>удобная сумма</small><b>48+52=100</b></span></div></div>;
  if(kind==='path')return <div className="chapter-two-review-panel" data-summary-topic="formula"><div className="c2r-path"><b>s</b><span>путь</span><strong>=</strong><b>v</b><span>скорость</span><strong>·</strong><b>t</b><span>время</span></div></div>;
  if(kind==='equation')return <div className="chapter-two-review-panel" data-summary-topic="equation"><div className="c2r-equation"><span><b>1</b>выдели неизвестную часть</span><i>→</i><span><b>2</b>выполни обратное действие</span><i>→</i><span><b>3</b>проверь подстановкой</span></div></div>;
  if(kind==='angles')return <div className="chapter-two-review-panel" data-summary-topic="angles"><div className="c2r-angle-types"><span><i style={{transform:'rotate(-28deg)'}}/><b>&lt;90°</b><small>острый</small></span><span><i style={{transform:'rotate(-90deg)'}}/><b>90°</b><small>прямой</small></span><span><i style={{transform:'rotate(-132deg)'}}/><b>90°…180°</b><small>тупой</small></span><span><i style={{transform:'rotate(-180deg)'}}/><b>180°</b><small>развёрнутый</small></span></div></div>;
  if(kind==='polygon')return <div className="chapter-two-review-panel" data-summary-topic="polygon"><svg className="c2r-polygon" viewBox="0 0 620 250" role="img" aria-label="Пятиугольник: вершины, стороны, углы и периметр"><polygon points="105,205 60,92 190,35 320,92 275,205"/><circle cx="105" cy="205" r="6"/><circle cx="60" cy="92" r="6"/><circle cx="190" cy="35" r="6"/><circle cx="320" cy="92" r="6"/><circle cx="275" cy="205" r="6"/><text x="390" y="78">5 вершин</text><text x="390" y="125">5 сторон</text><text x="390" y="172">P = сумма сторон</text></svg></div>;
  if(kind==='rectangle')return <div className="chapter-two-review-panel" data-summary-topic="rectangle"><svg className="c2r-rectangle" viewBox="0 0 650 260" role="img" aria-label="Прямоугольник со сторонами a и b и формулой периметра"><rect x="65" y="45" width="300" height="165"/><path d="M65 65h20V45M345 45v20h20M365 190h-20v20M85 210v-20H65"/><text x="215" y="34">a</text><text x="45" y="132">b</text><text x="425" y="105">P=2a+2b</text><text x="425" y="155">P=2(a+b)</text></svg></div>;
  if(kind==='checklist')return <div className="chapter-two-review-panel"><div className="c2r-checklist">{['Условие','Тема','Правило','Вычисление','Единицы и ответ'].map((item,index)=><span key={item}><b>{index+1}</b>{item}</span>)}</div></div>;
  return <div className="chapter-two-review-panel"><div className="c2r-final"><b>12/12<br/><small>вопросов источника</small></b><b>23<br/><small>интерактивные проверки</small></b><b>20<br/><small>задач практики</small></b><b>№ 3<br/><small>готовность к контрольной</small></b></div></div>;
}

function CompositeAngleDiagram({variant}:{variant:Extract<Diagram,{type:'composite-angle'}>['variant']}){
  if(variant==='test-6')return <div className="chapter-two-review-diagram"><svg viewBox="0 0 720 330" role="img" aria-label="Вопрос 6: развёрнутый угол MKP, лучи KA и KB, угол MKB 115 градусов, угол AKP 94 градуса" data-source-test-figure="2-6" data-angle-mkb="115" data-angle-akp="94" data-result-angle-akb="29"><line x1="70" y1="255" x2="650" y2="255"/><line data-ray-angle="94" x1="360" y1="255" x2="345.35" y2="45.51"/><line data-ray-angle="65" x1="360" y1="255" x2="448.75" y2="64.67"/><path className="c2r-arc" d="M305 255A55 55 0 0 1 383.24 205.15"/><path className="c2r-arc is-result" d="M355.47 190.16A65 65 0 0 1 387.47 196.09"/><text x="52" y="278">M</text><text x="350" y="283">K</text><text x="660" y="278">P</text><text x="324" y="42">A</text><text x="458" y="64">B</text><text x="205" y="220">115°</text><text x="384" y="130">94°</text><text className="c2r-result-text" x="397" y="218">29°</text></svg></div>;
  return <div className="chapter-two-review-diagram"><svg viewBox="0 0 720 300" role="img" aria-label="Развёрнутый угол разделён лучом на углы 112 и 68 градусов" data-whole-angle="180" data-known-angle="112" data-missing-angle="68"><line x1="70" y1="235" x2="650" y2="235"/><line data-ray-angle="68" x1="360" y1="235" x2="434.92" y2="49.56"/><path className="c2r-arc" d="M300 235A60 60 0 0 1 382.48 179.37"/><path className="c2r-arc is-result" d="M382.48 179.37A60 60 0 0 1 420 235"/><text x="240" y="190">112°</text><text className="c2r-result-text" x="425" y="205">68°</text><text x="325" y="280">112°+68°=180°</text></svg></div>;
}

function TrianglesDiagram({variant}:{variant:Extract<Diagram,{type:'triangles'}>['variant']}){
  if(variant==='test-7')return <div className="chapter-two-review-diagram"><svg viewBox="0 0 820 320" role="img" aria-label="Вопрос 7: три треугольника со сторонами 5, 8, 11; 4, 6, 6; 5, 12, 13 сантиметров" data-source-test-figure="2-7" data-triangle-sides="5|8|11;4|6|6;5|12|13" data-isosceles-perimeter="16"><g data-side-scale="20" transform="translate(10 15)"><polygon points="15,210 89.55,143.35 235,210"/><text x="43" y="166">5</text><text x="164" y="170">8</text><text x="112" y="237">11</text><text x="72" y="278">разносторонний</text></g><g className="is-answer" data-side-scale="30" transform="translate(285 15)"><polygon points="15,210 55,96.86 195,210"/><text x="18" y="145">4</text><text x="126" y="146">6</text><text x="96" y="237">6</text><text x="72" y="278">P=16 см</text></g><g data-side-scale="20" transform="translate(545 15)"><polygon points="15,210 15,110 255,210"/><text x="0" y="164">5</text><text x="126" y="237">12</text><text x="132" y="148">13</text><text x="76" y="278">разносторонний</text></g></svg></div>;
  return <div className="chapter-two-review-diagram"><svg viewBox="0 0 720 300" role="img" aria-label="Равнобедренный треугольник со сторонами 7, 7 и 10 сантиметров" data-triangle-sides="7|7|10" data-side-scale="38" data-side-type="isosceles"><polygon points="170,245 360,58.93 550,245"/><path className="c2r-tick" d="M255 150l18 15M447 165l18-15"/><text x="245" y="130">7 см</text><text x="460" y="130">7 см</text><text x="342" y="278">10 см</text><text x="52" y="75">по сторонам:</text><text x="52" y="108">равнобедренный</text></svg></div>;
}

function DiagramView({diagram}:{diagram:Diagram}){
  if(diagram.type==='composite-angle')return <CompositeAngleDiagram variant={diagram.variant}/>;
  if(diagram.type==='triangles')return <TrianglesDiagram variant={diagram.variant}/>;
  return <PanelDiagram kind={diagram.kind}/>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyTwoStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function ChapterTwoReviewPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyTwoStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyTwoStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==52||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyTwoStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyTwoStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player chapter-two-review-player" data-lesson-number="52" data-source-reference="Мерзляк · задание № 2 «Проверьте себя» · итоги главы 2 · с. 102–105" data-test-item-count="12"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id} data-source-test-item={stage.sourceItem??undefined}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<DiagramView diagram={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} Можно перейти дальше и вернуться к заданию позже.`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span className="stage-counter">Этап {saved.stageIndex+1} из {lessonFiftyTwoStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyTwoStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyTwoStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
