import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';
import './naturalComparison.css';
import './chapterOneReview.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='map'|'natural'|'digits'|'segment'|'line'|'scale'|'compare'|'strategy'|'challenge';
export type ChapterOneReviewStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};

const KEY='mathnikita-lesson-19-progress-v1';

export const lessonNineteenStages:ChapterOneReviewStage[]=[
  {id:'l19-mission',kind:'story',eyebrow:'Повторение главы 1',title:'Сегодня — генеральная репетиция',body:'Нового правила не будет. Нужно быстро узнавать тип задачи, выбирать нужное свойство и проверять ответ так, как это потребуется на контрольной работе № 1.',note:'Не торопись вычислять. Первый вопрос к каждой задаче: «Какую тему здесь проверяют?»',sourceTag:'Методическое пособие: урок 19 — повторение и систематизация',visual:'map'},
  {id:'l19-map',kind:'model',eyebrow:'Карта главы',title:'Шесть тем — одна система',body:'Глава начинается с натурального ряда, затем учит записывать числа, работать с отрезками и линиями, строить координатный луч и сравнивать числа. На контрольной эти навыки могут встречаться вперемешку.',note:'Если задача кажется новой, сначала определи, к какому из шести параграфов она относится.',sourceTag:'Учебник Мерзляка · «Итоги главы 1»',visual:'map'},
  {id:'l19-natural',kind:'practice',eyebrow:'Повторение · § 1',title:'Натуральный ряд',body:'За каждым натуральным числом есть следующее, большее на 1. Число 1 не имеет предыдущего натурального числа.',activity:{id:'l19-p1',type:'input',prompt:'Какое натуральное число непосредственно предшествует числу 8 100?',answer:'8099',placeholder:'Число',explanation:'Предыдущее число на единицу меньше: 8 100 − 1 = 8 099.'},visual:'natural'},
  {id:'l19-digits',kind:'practice',eyebrow:'Повторение · § 2',title:'Классы и разряды',body:'Многозначное число читают по классам справа налево, а значение цифры определяется её разрядом.',activity:{id:'l19-p2',type:'choice',prompt:'Какая цифра стоит в разряде десятков тысяч числа 572 843?',options:['5','7','2','8'],answer:'7',explanation:'В числе 572 843 цифры слева направо занимают разряды: сотни тысяч, десятки тысяч, тысячи, сотни, десятки, единицы.'},visual:'digits'},
  {id:'l19-segment',kind:'practice',eyebrow:'Повторение · § 3',title:'Отрезок и его части',body:'Если точки расположены A–C–B–D, то длина AD складывается из AC, CB и BD.',activity:{id:'l19-p3',type:'input',prompt:'Точки A–C–B–D лежат на одной прямой. AC = 18 см, CB = 7 см, BD = 16 см. Найди AD.',answer:'41',placeholder:'Только число',explanation:'AD = AC + CB + BD = 18 + 7 + 16 = 41 см.'},visual:'segment'},
  {id:'l19-line',kind:'practice',eyebrow:'Повторение · § 4',title:'Прямая и луч',body:'Через две различные точки проходит ровно одна прямая. Луч имеет начало и продолжается бесконечно только в одном направлении.',activity:{id:'l19-p4',type:'choice',prompt:'Сколько прямых можно провести через две различные точки?',options:['0','1','2','Бесконечно много'],answer:'1',explanation:'Это основное свойство прямой: через две различные точки проходит ровно одна прямая.'},visual:'line'},
  {id:'l19-scale',kind:'practice',eyebrow:'Повторение · § 5',title:'Шкала и координатный луч',body:'Координата зависит от единичного отрезка. Сначала выясни шаг, затем считай равные промежутки от нуля.',activity:{id:'l19-p5',type:'input',prompt:'На координатном луче один шаг равен 8. Какова координата точки после 6 шагов от нуля?',answer:'48',placeholder:'Координата',explanation:'6 одинаковых шагов по 8 дают координату 48.'},visual:'scale'},
  {id:'l19-compare',kind:'practice',eyebrow:'Повторение · § 6',title:'Сравнение чисел и величин',body:'Натуральные числа сравнивают по количеству цифр и разрядам. Величины сначала переводят в одинаковые единицы.',activity:{id:'l19-p6',type:'choice',prompt:'Какая запись верна?',options:['5 ц 18 кг > 507 кг','5 ц 18 кг < 507 кг','5 ц 18 кг = 507 кг'],answer:'5 ц 18 кг > 507 кг',explanation:'5 ц 18 кг = 518 кг, а 518 > 507.'},visual:'compare'},
  {id:'l19-strategy',kind:'model',eyebrow:'Перед проверкой',title:'Стратегия контрольной работы',body:'Сначала решай то, где сразу видишь правило. В заданиях с рисунком подпиши данные. В координатах проверь шаг. В сравнении величин переведи единицы. После ответа перечитай условие.',note:'Если сомневаешься между двумя ответами, не угадывай: найди свойство, которое исключает один из них.',sourceTag:'Учебник · «Проверьте себя» в тестовой форме',visual:'strategy'},
  {id:'l19-q1',kind:'quiz',eyebrow:'Генеральная репетиция · 1/12',title:'Предыдущее натуральное число',body:'Без подсказки.',activity:{id:'l19-q1a',type:'choice',prompt:'Какое число непосредственно предшествует 7 100?',options:['7 099','7 009','7 101','6 999'],answer:'7 099',explanation:'Предыдущее натуральное число меньше на 1.'},visual:'natural'},
  {id:'l19-q2',kind:'quiz',eyebrow:'Генеральная репетиция · 2/12',title:'Числа между границами',body:'Без подсказки.',activity:{id:'l19-q2a',type:'input',prompt:'Сколько натуральных чисел находится между 44 и 91?',answer:'46',placeholder:'Количество',explanation:'91 − 44 − 1 = 46. Сами границы не считаем.'},visual:'natural'},
  {id:'l19-q3',kind:'quiz',eyebrow:'Генеральная репетиция · 3/12',title:'Разряд цифры',body:'Без подсказки.',activity:{id:'l19-q3a',type:'choice',prompt:'Какая цифра стоит в разряде десятков тысяч числа 684 321?',options:['6','8','4','3'],answer:'8',explanation:'В числе 684 321 цифра 8 обозначает 8 десятков тысяч.'},visual:'digits'},
  {id:'l19-q4',kind:'quiz',eyebrow:'Генеральная репетиция · 4/12',title:'Запись числа цифрами',body:'Без подсказки.',activity:{id:'l19-q4a',type:'input',prompt:'Запиши цифрами: три миллиона сорок тысяч пятьсот.',answer:'3040500',placeholder:'Число',explanation:'Класс миллионов: 3; класс тысяч: 040; класс единиц: 500. Получаем 3 040 500.'},visual:'digits'},
  {id:'l19-q5',kind:'quiz',eyebrow:'Генеральная репетиция · 5/12',title:'Длина составного отрезка',body:'Без подсказки.',activity:{id:'l19-q5a',type:'input',prompt:'Точки A–C–B–D расположены по порядку. AC = 16 см, CB = 8 см, BD = 22 см. Найди AD.',answer:'46',placeholder:'Только число',explanation:'AD = 16 + 8 + 22 = 46 см.'},visual:'segment'},
  {id:'l19-q6',kind:'quiz',eyebrow:'Генеральная репетиция · 6/12',title:'Принадлежность лучу',body:'Точки на прямой расположены слева направо: E, B, D, K, M. Рассматриваем луч BD.',activity:{id:'l19-q6a',type:'choice',prompt:'Какая точка не принадлежит лучу BD?',options:['B','D','K','E'],answer:'E',explanation:'Луч BD начинается в B и идёт через D вправо. Точка E лежит по другую сторону от начала B.'},visual:'line'},
  {id:'l19-q7',kind:'quiz',eyebrow:'Генеральная репетиция · 7/12',title:'Координата точки',body:'Единичный отрезок равен одному шагу.',activity:{id:'l19-q7a',type:'input',prompt:'Точка M находится на седьмой отметке справа от 0. Какова её координата?',answer:'7',placeholder:'Координата',explanation:'При единичном шаге координата равна числу шагов от нуля.'},visual:'scale'},
  {id:'l19-q8',kind:'quiz',eyebrow:'Генеральная репетиция · 8/12',title:'Координата по шкале',body:'На шкале подписаны 0, 25, 50, 75, 100.',activity:{id:'l19-q8a',type:'choice',prompt:'Какова координата точки K на отметке между 50 и 100, если это третья подписанная отметка после 0?',options:['50','60','75','80'],answer:'75',explanation:'Подписанные отметки идут с шагом 25: 0, 25, 50, 75, 100.'},visual:'scale'},
  {id:'l19-q9',kind:'quiz',eyebrow:'Генеральная репетиция · 9/12',title:'Цифра вместо звёздочки',body:'Без перебора всех чисел найди решающий разряд.',activity:{id:'l19-q9a',type:'choice',prompt:'Какую цифру можно поставить вместо * в неравенстве 2 583 < 2 5*7, чтобы оно было верным?',options:['6','7','8','9'],answer:'9',explanation:'Тысячи и сотни совпадают. В десятках нужно получить цифру больше 8; из вариантов подходит только 9.'},visual:'compare'},
  {id:'l19-q10',kind:'quiz',eyebrow:'Генеральная репетиция · 10/12',title:'Числа левее точки',body:'На координатном луче натуральные числа растут вправо.',activity:{id:'l19-q10a',type:'input',prompt:'Сколько натуральных чисел расположено левее числа 18?',answer:'17',placeholder:'Количество',explanation:'Левее 18 лежат натуральные числа от 1 до 17 — всего 17 чисел.'},visual:'scale'},
  {id:'l19-q11',kind:'quiz',eyebrow:'Генеральная репетиция · 11/12',title:'Сколько раз встречается цифра',body:'Считай цифры в записи номеров, а не количество самих номеров.',activity:{id:'l19-q11a',type:'input',prompt:'Дома пронумерованы числами от 1 до 35. Сколько раз в нумерации встречается цифра 3?',answer:'10',placeholder:'Количество',explanation:'Цифра 3 встречается в 3, 13, 23, затем в десятках чисел 30–35 и ещё раз в числе 33. Всего 10.'},visual:'digits'},
  {id:'l19-q12',kind:'quiz',eyebrow:'Генеральная репетиция · 12/12',title:'Сравнение величин',body:'Сначала вырази обе длины в метрах.',activity:{id:'l19-q12a',type:'choice',prompt:'Какой знак верен: 4 км 70 м □ 4 700 м?',options:['>','<','='],answer:'<',explanation:'4 км 70 м = 4 070 м, а 4 070 < 4 700.'},visual:'compare'},
  {id:'l19-challenge',kind:'challenge',eyebrow:'Задача повышенного уровня',title:'Составь максимум с ограничением',body:'Используй цифры 0, 2, 6, 8 ровно по одному разу. Нужно получить наибольшее четырёхзначное натуральное число, меньшее 7 000.',activity:{id:'l19-c1',type:'input',prompt:'Какое число получится?',answer:'6820',placeholder:'Число',explanation:'Первая цифра не может быть 8, иначе число превысит 7 000. Берём 6, затем оставшиеся цифры ставим по убыванию: 6 820.'},visual:'challenge'},
  {id:'l19-reflection',kind:'model',eyebrow:'Самопроверка',title:'Назови слабое место до контрольной',body:'Посмотри не только на счёт, но и на тип ошибок. Если ошибался в координатах — проверяй шаг. Если в геометрии — порядок точек. Если в записи числа — разбивай его на классы.',note:'Контрольная нужна не для угадывания ответа, а для точного применения знакомого правила.',visual:'strategy'},
  {id:'l19-summary',kind:'summary',eyebrow:'Итог урока 19',title:'Глава 1 повторена',body:'Ты прошёл все ключевые навыки главы и генеральную репетицию в формате «Проверьте себя». Следующий урок — контрольная работа № 1.',sourceTag:'Учебник Мерзляка · «Проверьте себя» и «Итоги главы 1»',visual:'map'},
];

const emptySaved:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function normalize(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е').replace(/[;]+/g,',').replace(/[–—]/g,'-')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...emptySaved,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonNineteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:emptySaved}catch{return emptySaved}}

function ReviewVisual({kind}:{kind:Visual}){
  if(kind==='map')return <div className="chapter-review-visual"><div className="chapter-review-map"><div><b>§1</b><span>Натуральный ряд</span></div><div><b>§2</b><span>Запись чисел</span></div><div><b>§3</b><span>Отрезки</span></div><div><b>§4</b><span>Прямая и луч</span></div><div><b>§5</b><span>Координаты</span></div><div><b>§6</b><span>Сравнение</span></div></div></div>;
  if(kind==='natural')return <div className="chapter-review-visual"><div className="chapter-review-row"><b>…</b><span>8 098</span><span>8 099</span><strong>8 100</strong><span>8 101</span><b>…</b></div></div>;
  if(kind==='digits')return <div className="chapter-review-visual"><div className="chapter-review-digits"><span>5</span><mark>7</mark><span>2</span><span>8</span><span>4</span><span>3</span></div></div>;
  if(kind==='segment')return <div className="chapter-review-visual"><div className="chapter-review-segment"><div>A</div><div>C</div><div>B</div><div>D</div></div></div>;
  if(kind==='line')return <div className="chapter-review-visual"><div className="chapter-review-line"><i className="point p1"><span>E</span></i><i className="point p2"><span>B</span></i><i className="point p3"><span>D</span></i><i className="point p4"><span>K</span></i><i className="point p5"><span>M</span></i></div></div>;
  if(kind==='scale')return <div className="chapter-review-visual"><div className="chapter-review-scale">{['0','25','50','75','100'].map(value=><span key={value}>{value}</span>)}</div></div>;
  if(kind==='compare')return <div className="chapter-review-visual"><div className="chapter-review-row"><b>4 км 70 м</b><strong>&lt;</strong><b>4 700 м</b></div></div>;
  if(kind==='strategy')return <div className="chapter-review-visual"><div className="chapter-review-strategy"><div><b>1. Узнай тему</b><span>Что проверяет задача?</span></div><div><b>2. Выбери правило</b><span>Какое свойство решает её?</span></div><div><b>3. Реши</b><span>Без лишних действий.</span></div><div><b>4. Проверь</b><span>Ответ соответствует условию?</span></div></div></div>;
  return <div className="chapter-review-visual"><div className="chapter-review-challenge">{['0','2','6','8'].map(value=><span key={value}>{value}</span>)}</div></div>;
}

export function ChapterOneReviewPlayer(){
  const saved=useMemo(load,[]);
  const[stageIndex,setStageIndex]=useState(saved.stageIndex);
  const[responses,setResponses]=useState(saved.responses);
  const[orders,setOrders]=useState(saved.orders);
  const[checked,setChecked]=useState(saved.checked);
  const[results,setResults]=useState(saved.results);
  const[completedAt,setCompletedAt]=useState(saved.completedAt);
  const stage=lessonNineteenStages[stageIndex];
  const activity=stage.activity;
  const response=activity?responses[activity.id]??'':'';
  const ordered=activity?orders[activity.id]??[]:[];
  const isChecked=activity?Boolean(checked[activity.id]):false;
  const isCorrect=activity?Boolean(results[activity.id]):true;
  const practiceIds=['l19-p1','l19-p2','l19-p3','l19-p4','l19-p5','l19-p6'];
  const quizIds=Array.from({length:12},(_,index)=>`l19-q${index+1}a`);
  const practiceScore=practiceIds.filter(id=>results[id]).length;
  const quizScore=quizIds.filter(id=>results[id]).length;
  const progress=Math.round(((stageIndex+1)/lessonNineteenStages.length)*100);

  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
  useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{lessonNumber:number;stageIndex:number}>).detail;if(detail?.lessonNumber===19&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);

  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonNineteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):normalize(response)===normalize(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
  function render(current:Activity){
    if(current.type==='choice')return <section className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button type="button" className="check-button" disabled={!response} onClick={submit}>Проверить</button></section>;
    if(current.type==='input')return <section className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={response} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button type="button" className="check-button" disabled={!response.trim()} onClick={submit}>Проверить</button></div></section>;
    const items=current.items??[];
    return <section className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button type="button" key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button type="button" key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button type="button" className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></section>;
  }

  return <main className="lesson-player-page chapter-review-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 19 из 175 · повторение</span><h1>Повторение главы 1</h1><p>Натуральный ряд, запись чисел, геометрия, координатный луч и сравнение — перед контрольной № 1.</p></div><div className="lesson-duration">48 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonNineteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<ReviewVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:'Определи тему задания и вернись к соответствующему правилу главы.'}</span></div>:null}{stage.kind==='quiz'?<div className="quiz-meter"><span>Генеральная репетиция</span><b>{quizScore} из 12</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Повторение</span><b>{practiceScore}/6</b><small>ключевые темы</small></div><div><span>Репетиция</span><b>{quizScore}/12</b><small>формат «Проверьте себя»</small></div><div><span>Готовность</span><b>{practiceScore===6&&quizScore>=10?'Готов':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button type="button" onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button type="button" className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonNineteenStages.length-1||Boolean(activity&&!isCorrect)}>Продолжить →</button></footer></section></main>;
}
