import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './distributiveMultiplication.css';

type Activity={
  id:string;
  type:'choice'|'input';
  prompt:string;
  options?:string[];
  answer:string|string[];
  explanation:string;
  hint:string;
  placeholder?:string;
};
type VisualKind='mission'|'area'|'formula'|'directions'|'factor'|'lab'|'expand'|'like'|'error'|'bridge'|'final';
type Stage={
  id:string;
  title:string;
  eyebrow:string;
  kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';
  body:string;
  note?:string;
  activity?:Activity;
  visual?:VisualKind;
  sourceExercise?:string;
};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-59-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonFiftyNineStages:Stage[]=[
  {id:'l59-mission',kind:'story',eyebrow:'Урок 59 · § 17 · новая идея',title:'Один прямоугольник раскрывает скобки',body:'Умножение можно распределить на каждую часть суммы или разности. Сегодня увидим это на площади, научимся двигаться в обе стороны и превращать громоздкие вычисления в короткие.',note:'Маршрут по учебнику Мерзляка: § 17, № 424–429 · модель площади → формулы → общий множитель → раскрытие скобок → одинаковые буквенные части.',visual:'mission'},
  {id:'l59-area-model',kind:'model',eyebrow:'Модель свойства',title:'Высота одна, ширина состоит из двух частей',body:'Прямоугольник высотой 6 и шириной 20+3 можно считать целиком: 6·23. Можно разделить его на прямоугольники 6·20 и 6·3. Площадь фигуры от линии разреза не меняется.',note:'Общий множитель 6 — одинаковая высота обеих частей.',visual:'area'},
  {id:'l59-whole-route',kind:'practice',eyebrow:'Маршрут 1 · целое',title:'Сначала сложи внутри скобок',body:'Ширина равна 20+3=23, поэтому площадь целого прямоугольника равна 6·23.',activity:{id:'l59-p1',type:'input',prompt:'Чему равно 6·(20+3)?',answer:['138'],placeholder:'Площадь',hint:'Сначала найди 20+3, затем умножь на 6.',explanation:'6·(20+3)=6·23=138.'},visual:'area'},
  {id:'l59-parts-route',kind:'practice',eyebrow:'Маршрут 2 · части',title:'Умножь высоту на каждую ширину',body:'Первая часть имеет площадь 6·20=120, вторая — 6·3=18. Их сумма возвращает площадь целой фигуры.',activity:{id:'l59-p2',type:'input',prompt:'Чему равно 6·20+6·3?',answer:['138'],placeholder:'Сумма площадей',hint:'Сложи 120 и 18.',explanation:'6·20+6·3=120+18=138.'},visual:'area'},
  {id:'l59-property-choice',kind:'quiz',eyebrow:'Вывод из модели',title:'Записываем распределительное свойство',body:'Каждая часть суммы внутри скобок должна получить общий множитель a.',activity:{id:'l59-p3',type:'choice',prompt:'Какая формула соответствует модели?',options:['a·(b+c)=a·b+a·c','a·(b+c)=a·b+c','(a·b)·c=a·(b·c)','a+b=b+a'],answer:'a·(b+c)=a·b+a·c',hint:'Множитель a относится и к b, и к c.',explanation:'a·(b+c)=a·b+a·c: общий множитель распределён на оба слагаемых.'},visual:'formula'},
  {id:'l59-addition-formula',kind:'model',eyebrow:'Формула для суммы',title:'Умножить сумму — значит умножить каждое слагаемое',body:'Равенство a·(b+c)=a·b+a·c можно читать слева направо — раскрывать скобки — и справа налево — выносить общий множитель.',note:'Распределительное свойство работает и когда скобки стоят перед множителем: (b+c)·a=b·a+c·a.',visual:'formula'},
  {id:'l59-subtraction-model',kind:'model',eyebrow:'Формула для разности',title:'Из большого прямоугольника вычитаем полосу',body:'Площадь 7·30 уменьшим на полосу 7·4. Останется 7·(30−4). Оба маршрута дают один результат, поэтому a·(b−c)=a·b−a·c.',note:'В натуральных числах для такой модели берём b≥c.',visual:'area'},
  {id:'l59-subtraction-route',kind:'practice',eyebrow:'Разность · проверка',title:'Два маршрута снова совпадают',body:'Можно сначала вычислить ширину 30−4, а можно вычесть площадь полосы из площади большого прямоугольника.',activity:{id:'l59-p4',type:'input',prompt:'Вычисли 7·(30−4).',answer:['182'],placeholder:'Площадь остатка',hint:'30−4=26; теперь 7·26.',explanation:'7·(30−4)=7·26=182; также 210−28=182.'},visual:'area'},
  {id:'l59-subtraction-formula-choice',kind:'quiz',eyebrow:'Формула для разности',title:'Следим за знаком между произведениями',body:'Общий множитель умножается и на уменьшаемое, и на вычитаемое; знак минус сохраняется.',activity:{id:'l59-p5',type:'choice',prompt:'Как правильно раскрыть a·(b−c)?',options:['a·b−a·c','a·b−c','a·b+a·c','a·(b·c)'],answer:'a·b−a·c',hint:'Умножь a на обе части разности.',explanation:'a·(b−c)=a·b−a·c.'},visual:'formula'},
  {id:'l59-direction-compare',kind:'model',eyebrow:'Два направления',title:'Раскрыть скобки или собрать общий множитель',body:'Слева направо: 8·(40+7)=8·40+8·7. Справа налево: 8·40+8·7=8·(40+7). Выбирай направление, которое делает числа удобнее.',note:'Общий множитель обязан присутствовать в каждом слагаемом или вычитаемом.',visual:'directions'},
  {id:'l59-factor-choice',kind:'quiz',eyebrow:'Общий множитель',title:'Находим повторяющийся множитель',body:'В выражении 47·632+632·53 число 632 встречается в обоих произведениях.',activity:{id:'l59-p6',type:'choice',prompt:'Что можно вынести за скобки?',options:['632','47','53','100'],answer:'632',hint:'Ищи число, которое является множителем в каждом слагаемом.',explanation:'47·632+632·53=632·(47+53).'},visual:'factor',sourceExercise:'№ 425(1)'},
  {id:'l59-424-a',kind:'practice',eyebrow:'№ 424(1)',title:'Сумма коэффициентов даёт сто',body:'Вместо двух длинных произведений вынесем 318: 318·78+318·22=318·(78+22).',activity:{id:'l59-p7',type:'input',prompt:'Вычисли 318·78+318·22 удобным способом.',answer:['31800','31 800'],placeholder:'Значение',hint:'78+22=100.',explanation:'318·(78+22)=318·100=31800.'},visual:'factor',sourceExercise:'№ 424(1)'},
  {id:'l59-424-b',kind:'practice',eyebrow:'№ 424(2)',title:'Разность соседних коэффициентов',body:'У произведений общий множитель 92: 856·92−853·92=92·(856−853).',activity:{id:'l59-p8',type:'input',prompt:'Вычисли 856·92−853·92.',answer:['276'],placeholder:'Значение',hint:'856−853=3.',explanation:'92·(856−853)=92·3=276.'},visual:'factor',sourceExercise:'№ 424(2)'},
  {id:'l59-distributive-lab',kind:'model',eyebrow:'Интерактивная лаборатория',title:'Меняй части и наблюдай неизменное равенство',body:'Ползунки меняют общий множитель и части скобок. Переключатель меняет сумму на разность. Сравни маршрут «сначала скобки» с маршрутом «распределить множитель».',note:'Равенство сохраняется для всех значений лаборатории.',visual:'lab'},
  {id:'l59-lab-conclusion',kind:'quiz',eyebrow:'Вывод из лаборатории',title:'Что именно обязано совпадать',body:'Промежуточные действия отличаются, но обе записи описывают одну площадь.',activity:{id:'l59-p9',type:'choice',prompt:'Какой вывод верен?',options:['Полные значения a·(b±c) и a·b±a·c равны','Равны только выражения со знаком плюс','Можно умножить только первое число в скобках','После раскрытия знак всегда становится плюсом'],answer:'Полные значения a·(b±c) и a·b±a·c равны',hint:'Сравни итоговые значения двух маршрутов.',explanation:'Распределительное свойство сохраняет значение и для суммы, и для разности.'},visual:'lab'},
  {id:'l59-424-c',kind:'practice',eyebrow:'№ 424(3)',title:'Два коэффициента образуют пятьсот',body:'Общий множитель 943 превращает сумму произведений в 943·(268+232).',activity:{id:'l59-p10',type:'input',prompt:'Вычисли 943·268+943·232.',answer:['471500','471 500'],placeholder:'Значение',hint:'268+232=500.',explanation:'943·500=471500.'},visual:'factor',sourceExercise:'№ 424(3)'},
  {id:'l59-424-d',kind:'challenge',eyebrow:'№ 424(4)',title:'Внутри скобок получается ноль',body:'Вынесем 65 из всех трёх произведений: 65·(246−229−17).',activity:{id:'l59-p11',type:'input',prompt:'Вычисли 65·246−65·229−65·17.',answer:['0'],placeholder:'Значение',hint:'246−229=17, затем 17−17.',explanation:'65·(246−229−17)=65·0=0.'},visual:'factor',sourceExercise:'№ 424(4)'},
  {id:'l59-425-a',kind:'practice',eyebrow:'№ 425(1)',title:'Общий множитель стоит с разных сторон',body:'47·632 и 632·53 имеют общий множитель 632 благодаря переместительному свойству.',activity:{id:'l59-p12',type:'input',prompt:'Вычисли 47·632+632·53.',answer:['63200','63 200'],placeholder:'Значение',hint:'632·(47+53).',explanation:'632·100=63200.'},visual:'factor',sourceExercise:'№ 425(1)'},
  {id:'l59-425-b',kind:'practice',eyebrow:'№ 425(2)',title:'Разность коэффициентов равна единице',body:'49 встречается в обоих произведениях: 598·49−597·49=49·(598−597).',activity:{id:'l59-p13',type:'input',prompt:'Вычисли 598·49−597·49.',answer:['49'],placeholder:'Значение',hint:'598−597=1.',explanation:'49·1=49.'},visual:'factor',sourceExercise:'№ 425(2)'},
  {id:'l59-425-c',kind:'practice',eyebrow:'№ 425(3)',title:'Разность коэффициентов равна десяти',body:'Общий множитель 754 сразу превращает вычисление в 754·10.',activity:{id:'l59-p14',type:'input',prompt:'Вычисли 754·324−754·314.',answer:['7540','7 540'],placeholder:'Значение',hint:'324−314=10.',explanation:'754·(324−314)=754·10=7540.'},visual:'factor',sourceExercise:'№ 425(3)'},
  {id:'l59-425-d',kind:'challenge',eyebrow:'№ 425(4)',title:'Три слагаемых и один общий множитель',body:'Переставим множители и вынесем 37: 37·(46−18+72).',activity:{id:'l59-p15',type:'input',prompt:'Вычисли 37·46−18·37+37·72.',answer:['3700','3 700'],placeholder:'Значение',hint:'46−18+72=100.',explanation:'37·100=3700.'},visual:'factor',sourceExercise:'№ 425(4)'},
  {id:'l59-expand-rule',kind:'model',eyebrow:'Раскрытие скобок',title:'Каждая часть получает множитель',body:'В 2·(a+5) множитель 2 относится к a и к 5: получаем 2a+10. В 8·(7−x) получаем 56−8x.',note:'Полезная самопроверка: после раскрытия должно появиться столько произведений, сколько частей было в скобках.',visual:'expand'},
  {id:'l59-426-a',kind:'practice',eyebrow:'№ 426(1)',title:'Число и буквенное слагаемое',body:'Умножь 2 сначала на a, затем на 5.',activity:{id:'l59-p16',type:'input',prompt:'Раскрой скобки: 2·(a+5).',answer:['2a+10','2а+10'],placeholder:'Выражение',hint:'2·a+2·5.',explanation:'2·(a+5)=2a+10.'},visual:'expand',sourceExercise:'№ 426(1)'},
  {id:'l59-426-b',kind:'practice',eyebrow:'№ 426(2)',title:'Сохраняем знак минус',body:'В 8·(7−x) первое произведение числовое, второе содержит x.',activity:{id:'l59-p17',type:'input',prompt:'Раскрой скобки: 8·(7−x).',answer:['56-8x','56−8x','56-8х','56−8х'],placeholder:'Выражение',hint:'8·7−8·x.',explanation:'8·(7−x)=56−8x.'},visual:'expand',sourceExercise:'№ 426(2)'},
  {id:'l59-426-c',kind:'practice',eyebrow:'№ 426(3)',title:'Два буквенных слагаемых',body:'Число 12 умножается отдельно на x и на y.',activity:{id:'l59-p18',type:'input',prompt:'Раскрой скобки: 12·(x+y).',answer:['12x+12y','12х+12у'],placeholder:'Выражение',hint:'12·x+12·y.',explanation:'12·(x+y)=12x+12y.'},visual:'expand',sourceExercise:'№ 426(3)'},
  {id:'l59-427-a',kind:'practice',eyebrow:'№ 427(1)',title:'Закрепляем раскрытие суммы',body:'Четыре умножается на обе части a+2.',activity:{id:'l59-p19',type:'input',prompt:'Раскрой скобки: 4·(a+2).',answer:['4a+8','4а+8'],placeholder:'Выражение',hint:'4·a+4·2.',explanation:'4·(a+2)=4a+8.'},visual:'expand',sourceExercise:'№ 427(1)'},
  {id:'l59-427-c',kind:'practice',eyebrow:'№ 427(3)',title:'Множитель стоит после скобок',body:'Используй переместительное свойство: (p−q)·9=9·(p−q).',activity:{id:'l59-p20',type:'input',prompt:'Раскрой скобки: (p−q)·9.',answer:['9p-9q','9p−9q','9р-9q','9р−9q'],placeholder:'Выражение',hint:'9·p−9·q.',explanation:'(p−q)·9=9p−9q.'},visual:'expand',sourceExercise:'№ 427(3)'},
  {id:'l59-like-terms',kind:'model',eyebrow:'Одинаковая буквенная часть',title:'6a+8a — это шесть a и ещё восемь a',body:'Вынесем общий множитель a: 6a+8a=a·(6+8)=14a. Складываются числовые коэффициенты; буква не удваивается и не исчезает.',note:'Складывать можно только слагаемые с одинаковой буквенной частью.',visual:'like'},
  {id:'l59-428-a',kind:'practice',eyebrow:'№ 428(1)',title:'Собираем одинаковые слагаемые',body:'Обе части содержат один и тот же множитель a.',activity:{id:'l59-p21',type:'input',prompt:'Упрости: 6a+8a.',answer:['14a','14а'],placeholder:'Выражение',hint:'a·(6+8).',explanation:'6a+8a=14a.'},visual:'like',sourceExercise:'№ 428(1)'},
  {id:'l59-428-set',kind:'guided',eyebrow:'№ 428 · система',title:'Коэффициенты складываются и вычитаются',body:'28c−15c=13c; 13y−2y=11y; m+29m=30m; 98p−p=97p. Невидимый коэффициент перед одной буквой равен 1.',note:'Если остаётся число без буквы, его нельзя объединить с буквенной частью: 67z−18z+37=49z+37.',visual:'like',sourceExercise:'№ 428'},
  {id:'l59-429-chain',kind:'guided',eyebrow:'№ 429 · несколько частей',title:'Собираем все коэффициенты одной буквы',body:'36y−19y+23y=y·(36−19+23)=40y. В 49a+21a+30 получается 70a+30: число 30 не содержит a.',note:'Сначала отметь одинаковые буквенные части, затем выполни действия только с их коэффициентами.',visual:'like',sourceExercise:'№ 429'},
  {id:'l59-coefficient-one',kind:'model',eyebrow:'Скрытая единица',title:'a означает 1a, а −a означает −1a',body:'Записи m+29m и 98p−p становятся понятнее как 1m+29m и 98p−1p. Это защищает от ошибок 29m и 98p.',note:'Коэффициент 1 обычно не пишут, но учитывают в вычислении.',visual:'like'},
  {id:'l59-error-one-term',kind:'model',eyebrow:'Диагностика ошибки',title:'Множитель потерял второе слагаемое',body:'Запись 5·(a+3)=5a+3 неверна: число 3 тоже находится внутри скобок и должно быть умножено на 5.',note:'Верно: 5·(a+3)=5a+15.',visual:'error'},
  {id:'l59-error-sign',kind:'model',eyebrow:'Диагностика знака',title:'Минус не превращается в плюс',body:'Запись 7·(b−4)=7b+28 меняет смысл разности. Распределение сохраняет действие между частями.',note:'Верно: 7·(b−4)=7b−28.',visual:'error'},
  {id:'l59-bridge',kind:'guided',eyebrow:'Мост к уроку 60',title:'Свойство изучено — дальше стратегия и задачи',body:'Теперь ты умеешь раскрывать скобки и выносить общий множитель. Следующий урок § 17 соединит оба направления в многошаговых выражениях, текстовых задачах, уравнениях и доказательствах.',note:'Перед каждым вычислением спрашивай: скобки удобнее раскрыть или общий множитель удобнее вынести?',visual:'bridge'},
  {id:'l59-summary',kind:'summary',eyebrow:'Урок 59 · итог',title:'Распределительное свойство работает в обе стороны',body:'Ты доказал формулы на площади, вычислил № 424–425 вынесением общего множителя, раскрыл скобки в № 426–427 и упростил одинаковые буквенные части в № 428–429.',note:'Теперь пройди обязательную мастерскую: 20 задач и 50 оцениваемых ответов.',visual:'final'}
];

function DistributiveLab(){
  const[a,setA]=useState(6);const[b,setB]=useState(20);const[c,setC]=useState(3);const[operation,setOperation]=useState<'sum'|'difference'>('sum');
  const inside=operation==='sum'?b+c:b-c;const whole=a*inside;const first=a*b;const second=a*c;const parts=operation==='sum'?first+second:first-second;const sign=operation==='sum'?'+':'−';
  return <div className="distributive-lab" data-distributive-lab="interactive" data-operation={operation} data-whole-value={whole} data-parts-value={parts} data-equal={String(whole===parts)}>
    <div className="distributive-lab-controls"><label>Общий множитель a: <b>{a}</b><input aria-label="Общий множитель a" type="range" min="1" max="12" step="1" value={a} onChange={event=>setA(Number(event.target.value))}/></label><label>Основная часть b: <b>{b}</b><input aria-label="Основная часть b" type="range" min="13" max="50" step="1" value={b} onChange={event=>setB(Number(event.target.value))}/></label><label>Часть c: <b>{c}</b><input aria-label="Добавляемая или вычитаемая часть c" type="range" min="1" max="12" step="1" value={c} onChange={event=>setC(Number(event.target.value))}/></label></div>
    <button type="button" className="distributive-lab-toggle" onClick={()=>setOperation(value=>value==='sum'?'difference':'sum')}>{operation==='sum'?'Сложение: b+c':'Вычитание: b−c'} · переключить действие</button>
    <div className="distributive-lab-routes"><span><small>сначала скобки</small><b>{a}·({b}{sign}{c})</b><em>{a}·{inside}={whole}</em></span><strong>=</strong><span><small>распределить a</small><b>{a}·{b}{sign}{a}·{c}</b><em>{first}{sign}{second}={parts}</em></span></div>
  </div>;
}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='lab')return <DistributiveLab/>;
  if(kind==='mission')return <div className="distributive-visual" data-visual="mission"><div className="distributive-route"><span>площадь</span><i>→</i><span>формула</span><i>→</i><span>два направления</span><i>→</i><strong>короткое решение</strong></div></div>;
  if(kind==='area')return <div className="distributive-visual" data-visual="area"><div className="distributive-area"><span className="area-height">6</span><span className="area-main"><b>6·20</b><small>120</small></span><span className="area-extra"><b>6·3</b><small>18</small></span><strong>6·(20+3)=138</strong></div></div>;
  if(kind==='formula')return <div className="distributive-visual" data-visual="formula"><div className="distributive-formula"><span><small>сумма</small><b>a·(b+c)</b><em>a·b+a·c</em></span><span><small>разность</small><b>a·(b−c)</b><em>a·b−a·c</em></span></div></div>;
  if(kind==='directions')return <div className="distributive-visual" data-visual="directions"><div className="distributive-directions"><span><small>раскрыть</small><b>8·(40+7)</b><i>→</i><strong>8·40+8·7</strong></span><span><small>вынести</small><b>8·40+8·7</b><i>→</i><strong>8·(40+7)</strong></span></div></div>;
  if(kind==='factor')return <div className="distributive-visual" data-visual="factor"><div className="distributive-factor"><span>318·78+318·22</span><i>→</i><b>318·(78+22)</b><i>→</i><strong>31 800</strong></div></div>;
  if(kind==='expand')return <div className="distributive-visual" data-visual="expand"><div className="distributive-expand"><span><b>2·(a+5)</b><i>→</i><strong>2a+10</strong></span><span><b>8·(7−x)</b><i>→</i><strong>56−8x</strong></span></div></div>;
  if(kind==='like')return <div className="distributive-visual" data-visual="like"><div className="distributive-like"><span><b>6a+8a</b><small>a·(6+8)</small><strong>14a</strong></span><span><b>36y−19y+23y</b><small>y·(36−19+23)</small><strong>40y</strong></span></div></div>;
  if(kind==='error')return <div className="distributive-visual" data-visual="error"><div className="distributive-error"><del>5·(a+3)=5a+3</del><strong>5·(a+3)=5a+15</strong><del>7·(b−4)=7b+28</del><strong>7·(b−4)=7b−28</strong></div></div>;
  if(kind==='bridge')return <div className="distributive-visual" data-visual="bridge"><div className="distributive-bridge"><span><small>сегодня</small><b>раскрыть ↔ вынести</b></span><i>→</i><span><small>дальше</small><b>задачи и доказательства</b></span></div></div>;
  return <div className="distributive-visual" data-visual="final"><div className="distributive-final"><b>модель площади ✓</b><b>сумма и разность ✓</b><b>общий множитель ✓</b><b>№ 424–425 ✓</b><b>№ 426–429 ✓</b><b>проверка ошибок ✓</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyNineStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function DistributiveMultiplicationPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyNineStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyNineStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==59||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyNineStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyNineStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player distributive-multiplication-player" data-lesson-number="59" data-source-reference="Мерзляк § 17 · № 424–429" data-source-exercise-range="424-429"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFiftyNineStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyNineStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyNineStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
