import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'division'|'equation'|'work'|'expression'|'verify'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-67-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtySevenStages:Stage[]=[
{id:'l67-mission',kind:'story',eyebrow:'Урок 67 · § 18 · итоговое обобщение',title:'Финиш § 18: деление должно работать как система',body:'Это последний урок параграфа. Здесь недостаточно уметь получить частное: нужно предсказывать, как оно изменится, распознавать модель, доказывать ответ обратным действием и конструировать собственные выражения.',note:'Технологическая карта урока 67: устно № 510; закрепление № 487, 497, 507, 509, 517; домашний перенос № 488, 498, 508, 511.',visual:'mission'},
{id:'l67-map',kind:'model',eyebrow:'Карта мастерства',title:'Пять навыков одного параграфа',body:'1) деление и проверка умножением; 2) изменение частного; 3) неизвестные компоненты; 4) текстовая модель; 5) выражение как конструкция. Сегодня все пять соединяются.',visual:'map'},
{id:'l67-warmup',kind:'quiz',eyebrow:'Разминка',title:'Обратное действие — самый быстрый контроль',body:'Если 1512:27=56, проверка должна восстановить делимое.',activity:{id:'l67-p1',type:'choice',prompt:'Какая запись доказывает частное?',options:['56·27=1512','1512·27=56','56+27=1512','1512:56=27+1'],answer:'56·27=1512',hint:'Частное умножают на делитель.',explanation:'56·27=1512 — исходное делимое восстановлено.'},visual:'verify'},
{id:'l67-510-model',kind:'model',eyebrow:'№ 510',title:'Частное можно предсказывать без вычисления',body:'Если меняется делимое или делитель, результат меняется закономерно. Это важнее механического пересчёта: сначала предскажи направление и коэффициент изменения, затем проверяй числа.',note:'№ 510 рассматривает шесть преобразований делимого и делителя.',visual:'division',sourceExercise:'№ 510'},
{id:'l67-510-1',kind:'quiz',eyebrow:'№ 510(1)',title:'Делимое увеличили в 7 раз',body:'Делитель не меняется.',activity:{id:'l67-p2',type:'choice',prompt:'Как изменится частное?',options:['увеличится в 7 раз','уменьшится в 7 раз','не изменится','увеличится в 49 раз'],answer:'увеличится в 7 раз',hint:'Больше делимое при том же делителе — больше частное.',explanation:'Частное увеличится в 7 раз.'},visual:'division',sourceExercise:'№ 510(1)'},
{id:'l67-510-2',kind:'quiz',eyebrow:'№ 510(2)',title:'Делитель увеличили в 4 раза',body:'Делимое не меняется.',activity:{id:'l67-p3',type:'choice',prompt:'Как изменится частное?',options:['уменьшится в 4 раза','увеличится в 4 раза','не изменится','уменьшится в 16 раз'],answer:'уменьшится в 4 раза',hint:'Тот же объём делим на более крупные группы.',explanation:'Частное уменьшится в 4 раза.'},visual:'division',sourceExercise:'№ 510(2)'},
{id:'l67-510-3',kind:'quiz',eyebrow:'№ 510(3)',title:'Делимое ×8, делитель ×2',body:'Оба компонента изменились.',activity:{id:'l67-p4',type:'choice',prompt:'Что произойдёт с частным?',options:['увеличится в 4 раза','увеличится в 16 раз','уменьшится в 4 раза','не изменится'],answer:'увеличится в 4 раза',hint:'Сравни коэффициенты: 8:2.',explanation:'Новое частное в 8:2=4 раза больше.'},visual:'division',sourceExercise:'№ 510(3)'},
{id:'l67-510-4',kind:'quiz',eyebrow:'№ 510(4)',title:'Делимое ÷9, делитель ÷3',body:'Оба числа стали меньше, но не одинаково.',activity:{id:'l67-p5',type:'choice',prompt:'Как изменится частное?',options:['уменьшится в 3 раза','увеличится в 3 раза','уменьшится в 27 раз','не изменится'],answer:'уменьшится в 3 раза',hint:'(a/9):(b/3)=(a:b)·3/9.',explanation:'Коэффициент изменения 3/9=1/3.'},visual:'division',sourceExercise:'№ 510(4)'},
{id:'l67-510-5',kind:'quiz',eyebrow:'№ 510(5)',title:'Делимое ×6, делитель ÷2',body:'Оба изменения увеличивают частное.',activity:{id:'l67-p6',type:'choice',prompt:'Во сколько раз изменится частное?',options:['увеличится в 12 раз','увеличится в 3 раза','увеличится в 8 раз','уменьшится в 12 раз'],answer:'увеличится в 12 раз',hint:'Умножение делимого даёт ×6, уменьшение делителя в 2 раза даёт ещё ×2.',explanation:'6·2=12: частное увеличится в 12 раз.'},visual:'division',sourceExercise:'№ 510(5)'},
{id:'l67-510-6',kind:'quiz',eyebrow:'№ 510(6)',title:'Делимое ÷6, делитель ×2',body:'Оба изменения уменьшают частное.',activity:{id:'l67-p7',type:'choice',prompt:'Во сколько раз изменится частное?',options:['уменьшится в 12 раз','уменьшится в 3 раза','увеличится в 12 раз','не изменится'],answer:'уменьшится в 12 раз',hint:'÷6 и ещё ÷2 по эффекту на частное.',explanation:'Частное станет в 12 раз меньше.'},visual:'division',sourceExercise:'№ 510(6)'},
{id:'l67-510-synthesis',kind:'quiz',eyebrow:'№ 510 · вывод',title:'Когда частное не меняется?',body:'Это фундаментальная идея, которая пригодится и дальше.',activity:{id:'l67-p8',type:'choice',prompt:'Как изменить делимое и делитель, чтобы частное сохранилось?',options:['умножить оба на одно и то же ненулевое число','умножить только делимое','умножить только делитель','сложить с обоими одно число'],answer:'умножить оба на одно и то же ненулевое число',hint:'Сравни (ak):(bk).',explanation:'Общий множитель сокращается: (ak):(bk)=a:b.'},visual:'verify'},
{id:'l67-487-map',kind:'guided',eyebrow:'№ 487',title:'Исходная задача учебника: сначала модель, потом контроль',body:'Реши № 487 по полному условию учебника. В тренажёре не подменяем его пересказом: после самостоятельного решения сверяем две искомые величины с ответным разделом.',note:'Контрольные ответы учебника: 35 ящиков яблок и 15 ящиков груш.',visual:'work',sourceExercise:'№ 487'},
{id:'l67-487-a',kind:'practice',eyebrow:'№ 487 · контроль 1',title:'Первая искомая величина',body:'Сверь свою модель с ответным разделом.',activity:{id:'l67-p9',type:'input',prompt:'Сколько ящиков яблок должно получиться?',answer:['35','35 ящиков','35 ящиков яблок'],placeholder:'ящиков',hint:'Если число другое — проверь, что именно означало найденное частное.',explanation:'Контрольный ответ — 35 ящиков яблок.'},visual:'verify',sourceExercise:'№ 487'},
{id:'l67-487-b',kind:'practice',eyebrow:'№ 487 · контроль 2',title:'Вторая искомая величина',body:'Теперь вторая часть ответа.',activity:{id:'l67-p10',type:'input',prompt:'Сколько ящиков груш должно получиться?',answer:['15','15 ящиков','15 ящиков груш'],placeholder:'ящиков',hint:'Сверь единицы и вопрос задачи.',explanation:'Контрольный ответ — 15 ящиков груш.'},visual:'verify',sourceExercise:'№ 487'},
{id:'l67-487-check',kind:'practice',eyebrow:'№ 487 · независимая сверка',title:'Контроль общей структуры',body:'Две части ответа можно дополнительно связать арифметически.',activity:{id:'l67-p11',type:'input',prompt:'Сколько ящиков вместе: 35+15?',answer:'50',placeholder:'ящиков',hint:'Сложи две найденные группы.',explanation:'35+15=50 ящиков.'},visual:'verify'},
{id:'l67-497-map',kind:'guided',eyebrow:'№ 497',title:'Уравнение из учебника: роль неизвестного раньше действия',body:'Выполни № 497 в учебнике. Для каждого x сначала назови его роль — множитель, делимое или делитель — и только затем выбирай обратное действие. Так решение становится объяснимым, а не угадываемым.',visual:'equation',sourceExercise:'№ 497'},
{id:'l67-497-train',kind:'practice',eyebrow:'Тренировка к № 497',title:'Неизвестное делимое',body:'x:24=35.',activity:{id:'l67-p12',type:'input',prompt:'Найди x.',answer:['840','x=840'],placeholder:'x',hint:'Неизвестное делимое = делитель · частное.',explanation:'x=24·35=840.'},visual:'equation'},
{id:'l67-497-check',kind:'practice',eyebrow:'Тренировка к № 497',title:'Подстановка завершает решение',body:'Проверь найденный корень.',activity:{id:'l67-p13',type:'input',prompt:'Чему равно 840:35?',answer:'24',placeholder:'частное',hint:'Проверка должна вернуть известный компонент.',explanation:'840:35=24 — вычислительная связь подтверждена.'},visual:'verify'},
{id:'l67-507-map',kind:'model',eyebrow:'№ 507',title:'Три длины — три смысловые контрольные точки',body:'Реши исходную задачу № 507 в учебнике, сохраняя единицы на каждом шаге. Ответный раздел даёт три результата; тренажёр использует их только для сверки уже построенной модели.',note:'Контрольные ответы: 7 см, 35 см, 32 см.',visual:'work',sourceExercise:'№ 507'},
{id:'l67-507-a',kind:'practice',eyebrow:'№ 507 · контроль 1',title:'Первая длина',body:'Сверь первый результат.',activity:{id:'l67-p14',type:'input',prompt:'Первая контрольная длина?',answer:['7','7 см'],placeholder:'см',hint:'Не теряй единицу измерения.',explanation:'Первая контрольная длина — 7 см.'},visual:'verify',sourceExercise:'№ 507'},
{id:'l67-507-b',kind:'practice',eyebrow:'№ 507 · контроль 2',title:'Вторая длина',body:'Сверь второй результат.',activity:{id:'l67-p15',type:'input',prompt:'Вторая контрольная длина?',answer:['35','35 см'],placeholder:'см',hint:'Проверь смысл промежуточного частного.',explanation:'Вторая контрольная длина — 35 см.'},visual:'verify',sourceExercise:'№ 507'},
{id:'l67-507-c',kind:'practice',eyebrow:'№ 507 · контроль 3',title:'Третья длина',body:'Сверь третий результат.',activity:{id:'l67-p16',type:'input',prompt:'Третья контрольная длина?',answer:['32','32 см'],placeholder:'см',hint:'Сверь вопрос исходной задачи.',explanation:'Третья контрольная длина — 32 см.'},visual:'verify',sourceExercise:'№ 507'},
{id:'l67-507-check',kind:'practice',eyebrow:'№ 507 · арифметическая сверка',title:'Числа не должны жить отдельно',body:'Выполни независимое действие над контрольными значениями.',activity:{id:'l67-p17',type:'input',prompt:'Чему равно 7+35+32?',answer:'74',placeholder:'см',hint:'Сложи три числа.',explanation:'7+35+32=74.'},visual:'verify'},
{id:'l67-509-map',kind:'guided',eyebrow:'№ 509',title:'Последняя исходная модель перед творческой задачей',body:'Реши № 509 непосредственно по учебнику. Подпиши смысл каждого действия и отдельно отметь место, где деление отвечает на вопрос «сколько групп?» или «сколько в одной группе?». Формулировку задания тренажёр не реконструирует.',visual:'work',sourceExercise:'№ 509'},
{id:'l67-509-train',kind:'quiz',eyebrow:'Тренировка к № 509',title:'Что означает частное в модели?',body:'672 детали разложили поровну в 24 коробки.',activity:{id:'l67-p18',type:'input',prompt:'Сколько деталей в одной коробке?',answer:['28','28 деталей'],placeholder:'деталей',hint:'672:24.',explanation:'672:24=28 деталей в одной коробке.'},visual:'work'},
{id:'l67-517-model',kind:'model',eyebrow:'№ 517 · задача-конструктор',title:'Четыре двойки превращаются в лабораторию выражений',body:'Используй ровно четыре цифры 2 и только четыре арифметических действия. Скобки разрешают управлять порядком. Цель — не перебор вслепую, а проектирование: сначала придумай структуру результата, потом проверь вычислением.',note:'В учебнике нужно получить 1, 2, 3, 4, 5, 6, 8 и 10.',visual:'expression',sourceExercise:'№ 517'},
{id:'l67-517-one',kind:'challenge',eyebrow:'№ 517 · цель 1',title:'Сделай единицу',body:'Нужно использовать все четыре двойки.',activity:{id:'l67-p19',type:'input',prompt:'Введи один допустимый вариант для 1.',answer:['2/2*2/2','(2/2)*(2/2)','(2/2)·(2/2)','2/2·2/2'],placeholder:'выражение',hint:'Две пары 2:2 дают две единицы.',explanation:'Например, (2/2)·(2/2)=1.'},visual:'challenge',sourceExercise:'№ 517'},
{id:'l67-517-five',kind:'challenge',eyebrow:'№ 517 · цель 5',title:'Собери пятёрку',body:'Попробуй увидеть 4+1.',activity:{id:'l67-p20',type:'input',prompt:'Введи один допустимый вариант для 5.',answer:['2+2+2/2','2+2+(2/2)'],placeholder:'выражение',hint:'2+2 даёт 4, а 2:2 даёт 1.',explanation:'2+2+2/2=5.'},visual:'challenge',sourceExercise:'№ 517'},
{id:'l67-517-ten',kind:'challenge',eyebrow:'№ 517 · цель 10',title:'Собери десятку',body:'Попробуй увидеть 2+8.',activity:{id:'l67-p21',type:'input',prompt:'Введи один допустимый вариант для 10.',answer:['2+2*(2+2)','2+2·(2+2)'],placeholder:'выражение',hint:'В скобках получи 4, затем удвой и прибавь 2.',explanation:'2+2·(2+2)=10.'},visual:'challenge',sourceExercise:'№ 517'},
{id:'l67-517-gallery',kind:'model',eyebrow:'№ 517 · систематизация',title:'Один набор цифр — много архитектур',body:'Примеры: 3=2+2−2/2; 4=2−2+(2+2); 6=2·(2+2/2); 8=2+2+2+2. Проверяй два условия: ровно четыре двойки и только разрешённые действия.',visual:'expression',sourceExercise:'№ 517'},
{id:'l67-517-challenge',kind:'challenge',eyebrow:'№ 517 · сильный уровень',title:'Найди другой путь',body:'Для одной из целей 1, 2, 3, 4, 5, 6, 8, 10 придумай выражение, отличное от показанных. Сравни два решения: какое проще проверить и почему?',visual:'challenge',sourceExercise:'№ 517'},
{id:'l67-error',kind:'model',eyebrow:'Лаборатория ошибок',title:'Четыре ошибки финального урока',body:'Лишний ноль в частном; неверное направление изменения частного; перепутанная роль x; правильное число без ответа на вопрос задачи. Пятый риск в № 517 — случайно использовать не четыре двойки. Все ошибки ловятся отдельной проверкой условия.',visual:'error'},
{id:'l67-transfer',kind:'model',eyebrow:'Перенос',title:'Мастерство — это выбор стратегии',body:'Если видишь вычисление — оцени масштаб и проверь умножением. Если уравнение — назови неизвестный компонент. Если текст — подпиши смысл каждого результата. Если конструктор — сначала спроектируй структуру.',visual:'map'},
{id:'l67-reflection',kind:'model',eyebrow:'Рефлексия методички',title:'Где возникла ошибка и почему?',body:'Назови одно задание, где пришлось исправлять решение. Причина была в арифметике, выборе действия, понимании условия или проверке? Затем сформулируй конкретный приём, который предотвратит такую ошибку в следующий раз.',visual:'verify'},
{id:'l67-bridge',kind:'model',eyebrow:'Граница параграфа',title:'§ 18 завершён',body:'После этого урока тема обычного деления натуральных чисел систематизирована. Следующий урок 68 начинает новый § 19 — деление с остатком. Его правила здесь специально не опережаем.',visual:'map'},
{id:'l67-summary',kind:'summary',eyebrow:'Итог урока 67',title:'§ 18 закрыт не количеством примеров, а системой навыков',body:'Ты прошёл изменение частного № 510, контрольные модели № 487 и № 507, исходные задания № 497 и № 509 и творческий конструктор № 517. Теперь обязательная практика проверит перенос этих навыков на 20 задач и 50 ответов.',note:'После успешной практики следующий содержательный шаг курса — § 19 «Деление с остатком».',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'÷',map:'→',division:'a:b',equation:'x',work:'Σ',expression:'2²',verify:'✓',error:'!',challenge:'★',final:'67'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='division'?'изменение частного':kind==='equation'?'роль → правило':kind==='expression'?'структура выражения':kind==='verify'?'доказательство ответа':kind==='work'?'смысл величины':'деление · модель · стратегия'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSixtySevenStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function DivisionSynthesisPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSixtySevenStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtySevenStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==67||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSixtySevenStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSixtySevenStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player division-synthesis-player" data-lesson-number="67" data-source-reference="Мерзляк § 18 · технологическая карта урока 67 · № 510, 487, 497, 507, 509, 517" data-source-exercise-range="487,497,507,509,510,517"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtySevenStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtySevenStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtySevenStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
