import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'meanings'|'lab'|'inverse'|'components'|'table'|'exactness'|'specials'|'check'|'written'|'zeros'|'estimate'|'error'|'language'|'olympiad'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-61-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyOneStages:Stage[]=[
  {id:'l61-mission',kind:'story',eyebrow:'Урок 61 · § 18 · новая тема',title:'Деление отвечает на два разных вопроса',body:'Начинаем § 18. Одно и то же равенство может описывать распределение поровну или поиск количества одинаковых групп. В обоих случаях ответ доказывает умножение.',note:'Маршрут по учебнику Мерзляка: § 18, № 447–453 · смысл действия → обратность умножению → компоненты → особые случаи → точные вычисления.',visual:'mission'},
  {id:'l61-two-meanings',kind:'model',eyebrow:'Смысл действия',title:'Поровну и по содержанию',body:'24:6=4 можно прочитать так: 24 предмета разделили поровну между 6 участниками — каждому по 4. Или так: из 24 предметов составили группы по 6 — получилось 4 группы.',note:'Делимое и делитель те же, но роль частного в реальной ситуации различается.',visual:'meanings'},
  {id:'l61-division-lab',kind:'model',eyebrow:'Интерактивная лаборатория',title:'Переключай деления и сравни две модели',body:'Выбери равенство. Лаборатория одновременно покажет распределение поровну, группировку по заданному размеру и обратную проверку умножением.',note:'Числа в моделях меняют роль, но значение частного остаётся одним и тем же.',visual:'lab'},
  {id:'l61-share-basic',kind:'practice',eyebrow:'Поровну',title:'Ищем размер каждой доли',body:'24 фишки распределили поровну между 6 детьми.',activity:{id:'l61-p1',type:'input',prompt:'Сколько фишек получил каждый ребёнок?',answer:['4','по 4'],placeholder:'Количество',hint:'Найди число, которое при умножении на 6 даёт 24.',explanation:'24:6=4, потому что 4·6=24.'},visual:'meanings'},
  {id:'l61-groups-basic',kind:'practice',eyebrow:'По содержанию',title:'Ищем количество групп',body:'24 фишки раскладывают в пакеты по 6 фишек.',activity:{id:'l61-p2',type:'choice',prompt:'Сколько полных пакетов получится?',options:['4 пакета','6 пакетов','18 пакетов','30 пакетов'],answer:'4 пакета',hint:'Считай, сколько раз группа из 6 помещается в 24.',explanation:'24:6=4: в 24 содержатся четыре шестёрки.'},visual:'meanings'},
  {id:'l61-inverse-model',kind:'model',eyebrow:'Главная связь',title:'Частное — неизвестный множитель',body:'Равенство a:b=c означает, что c·b=a. Поэтому каждый результат деления можно доказать обратным умножением.',note:'Если 35:5=7, то проверка 7·5=35 восстанавливает делимое.',visual:'inverse'},
  {id:'l61-447-a',kind:'practice',eyebrow:'№ 447(1)',title:'Восстанавливаем второй множитель',body:'Известно: 243·425=103275.',activity:{id:'l61-p3',type:'input',prompt:'Вычисли 103275:243.',answer:['425'],placeholder:'Частное',hint:'Какой множитель стоял рядом с 243?',explanation:'103275:243=425, потому что 425·243=103275.'},visual:'inverse',sourceExercise:'№ 447(1)'},
  {id:'l61-447-b',kind:'practice',eyebrow:'№ 447(2)',title:'Меняем известный множитель',body:'Используй то же произведение 243·425=103275.',activity:{id:'l61-p4',type:'input',prompt:'Вычисли 103275:425.',answer:['243'],placeholder:'Частное',hint:'Теперь неизвестен первый множитель.',explanation:'103275:425=243, потому что 243·425=103275.'},visual:'inverse',sourceExercise:'№ 447(2)'},
  {id:'l61-components',kind:'model',eyebrow:'Язык математики',title:'Делимое, делитель, частное',body:'В записи a:b=c число a называют делимым, b — делителем, c — частным. Делимое показывает целое количество, делитель задаёт условие разделения, частное является результатом.',note:'Порядок важен: 24:6=4, но 6:24 не равно 4.',visual:'components'},
  {id:'l61-448-product',kind:'practice',eyebrow:'№ 448(1)',title:'Частное возвращает делимое',body:'Известно, что 4608:48=96.',activity:{id:'l61-p5',type:'input',prompt:'Чему равно 96·48?',answer:['4608','4 608'],placeholder:'Произведение',hint:'Умножение должно восстановить делимое.',explanation:'96·48=4608 — это проверка исходного деления.'},visual:'check',sourceExercise:'№ 448(1)'},
  {id:'l61-448-quotient',kind:'practice',eyebrow:'№ 448(2)',title:'Второе обратное деление',body:'То же равенство связывает три числа: 4608, 48 и 96.',activity:{id:'l61-p6',type:'input',prompt:'Вычисли 4608:96.',answer:['48'],placeholder:'Частное',hint:'Ищи второй множитель произведения 96·48.',explanation:'4608:96=48, потому что 48·96=4608.'},visual:'inverse',sourceExercise:'№ 448(2)'},
  {id:'l61-449-table',kind:'model',eyebrow:'№ 449 · таблица',title:'Одно семейство — четыре связанных факта',body:'Если 8·9=72, то 9·8=72, 72:8=9 и 72:9=8. Таблица компонентов помогает не угадывать, а восстанавливать неизвестное по роли.',note:'Умножение связывает множители с произведением, деление — делимое, делитель и частное.',visual:'table',sourceExercise:'№ 449'},
  {id:'l61-missing-factor',kind:'practice',eyebrow:'Обратная связь',title:'Деление находит неизвестный множитель',body:'В равенстве 8·x=72 неизвестен один множитель.',activity:{id:'l61-p7',type:'input',prompt:'Найди x.',answer:['9','x=9','х=9'],placeholder:'x =',hint:'Раздели произведение на известный множитель.',explanation:'x=72:8=9; проверка 8·9=72.'},visual:'table'},
  {id:'l61-name-dividend',kind:'quiz',eyebrow:'Компоненты',title:'Находим делимое по позиции',body:'Прочитай равенство слева направо: 84:7=12.',activity:{id:'l61-p8',type:'choice',prompt:'Какое число является делимым?',options:['84','7','12','84 и 7'],answer:'84',hint:'Делимое стоит перед знаком деления.',explanation:'84 — делимое, 7 — делитель, 12 — частное.'},visual:'components'},
  {id:'l61-table-relation',kind:'practice',eyebrow:'Семейство фактов',title:'Из произведения получаем частное',body:'Известно равенство 7·9=63.',activity:{id:'l61-p9',type:'input',prompt:'Вычисли 63:9.',answer:['7'],placeholder:'Частное',hint:'Какой множитель вместе с 9 даёт 63?',explanation:'63:9=7, потому что 7·9=63.'},visual:'table'},
  {id:'l61-exactness',kind:'model',eyebrow:'Натуральные числа',title:'Деление не всегда выполнимо без остатка',body:'В натуральных числах 36:6 выполнимо точно, потому что существует натуральное число 6 и 6·6=36. Для 35:6 такого натурального множителя нет.',note:'Деление с остатком будет отдельной темой § 19; сейчас различаем точное и неточное деление.',visual:'exactness'},
  {id:'l61-exactness-check',kind:'quiz',eyebrow:'Точный смысл',title:'Ищем доказательство существования частного',body:'Нужно решить 35:6 в натуральных числах без остатка.',activity:{id:'l61-p10',type:'choice',prompt:'Существует ли натуральное частное?',options:['Нет: ни одно натуральное n не даёт 6·n=35','Да, частное равно 5','Да, частное равно 6','Да, частное равно 29'],answer:'Нет: ни одно натуральное n не даёт 6·n=35',hint:'Проверь соседние произведения 6·5 и 6·6.',explanation:'6·5=30, а 6·6=36, поэтому точного натурального частного нет.'},visual:'exactness'},
  {id:'l61-specials',kind:'model',eyebrow:'Особые случаи',title:'Ноль, единица и само число',body:'Для натурального a>0 верны равенства a:1=a, a:a=1 и 0:a=0. Но выражение a:0 не имеет смысла: не существует числа, которое при умножении на 0 даст ненулевое a.',note:'0:0 тоже не определено: любое число при умножении на 0 даёт 0, поэтому единственного частного нет.',visual:'specials'},
  {id:'l61-zero-dividend',kind:'practice',eyebrow:'Нулевое делимое',title:'Ноль делим на ненулевое число',body:'Проверка строится умножением.',activity:{id:'l61-p11',type:'input',prompt:'Вычисли 0:37.',answer:['0'],placeholder:'Частное',hint:'Какое число при умножении на 37 даёт 0?',explanation:'0:37=0, потому что 0·37=0.'},visual:'specials'},
  {id:'l61-divide-one',kind:'practice',eyebrow:'Делитель 1',title:'Одна группа содержит всё',body:'Если всё делимое образует одну равную группу, размер этой группы не меняется.',activity:{id:'l61-p12',type:'input',prompt:'Вычисли 84:1.',answer:['84'],placeholder:'Частное',hint:'Проверь 84·1.',explanation:'84:1=84, потому что 84·1=84.'},visual:'specials'},
  {id:'l61-divide-self',kind:'practice',eyebrow:'Делитель равен делимому',title:'По одному целому в группе',body:'Ненулевое число делим само на себя.',activity:{id:'l61-p13',type:'input',prompt:'Вычисли 84:84.',answer:['1'],placeholder:'Частное',hint:'Какой множитель вместе с 84 даёт 84?',explanation:'84:84=1, потому что 1·84=84.'},visual:'specials'},
  {id:'l61-zero-divisor',kind:'quiz',eyebrow:'Стоп-сигнал',title:'Ноль не может быть делителем',body:'Проверка частного q потребовала бы равенства q·0=a.',activity:{id:'l61-p14',type:'choice',prompt:'Что верно для выражения 19:0?',options:['Делить на ноль нельзя','Частное равно 0','Частное равно 19','Частное равно 1'],answer:'Делить на ноль нельзя',hint:'Любое произведение с нулём равно нулю, а не 19.',explanation:'Не существует числа q, для которого q·0=19.'},visual:'error'},
  {id:'l61-check-model',kind:'model',eyebrow:'Алгоритм проверки',title:'Умножь частное на делитель',body:'После деления a:b=c вычисли c·b. Если произведение равно a, частное прошло проверку. Прикидка дополнительно защищает от ответа неверного порядка.',note:'1248:24≈1200:24≈50, поэтому частное 52 выглядит правдоподобно; 520 — нет.',visual:'check'},
  {id:'l61-check-52',kind:'practice',eyebrow:'Проверка вычисления',title:'Подбираем частное и доказываем его',body:'Найди число, которое при умножении на 24 даёт 1248.',activity:{id:'l61-p15',type:'input',prompt:'Вычисли 1248:24.',answer:['52'],placeholder:'Частное',hint:'24·50=1200, осталось 48=24·2.',explanation:'1248:24=52; проверка 52·24=1248.'},visual:'check'},
  {id:'l61-lab-conclusion',kind:'quiz',eyebrow:'Вывод лаборатории',title:'Две модели связаны одним равенством',body:'Вернись к распределению поровну и группировке по размеру.',activity:{id:'l61-p16',type:'choice',prompt:'Какой вывод верен для одного деления a:b=c?',options:['Оба смысла дают одно частное и одну проверку c·b=a','В каждой модели обязательно другое частное','Проверка нужна только для распределения поровну','Делитель и делимое можно всегда менять местами'],answer:'Оба смысла дают одно частное и одну проверку c·b=a',hint:'Сравни числовое равенство под обеими моделями.',explanation:'Сюжет меняет роль результата, но математическая связь c·b=a остаётся общей.'},visual:'lab'},
  {id:'l61-450-1',kind:'practice',eyebrow:'№ 450(1)',title:'Точное деление подтверждаем произведением',body:'Подбери частное по близкому произведению: 36·40=1440.',activity:{id:'l61-p17',type:'input',prompt:'Вычисли 1548:36.',answer:['43'],placeholder:'Частное',hint:'После 36·40 остаётся 108=36·3.',explanation:'1548:36=43; 43·36=1548.'},visual:'written',sourceExercise:'№ 450(1)'},
  {id:'l61-451-3',kind:'practice',eyebrow:'№ 451(3)',title:'Ноль внутри частного нельзя терять',body:'6565 делится на 13. Прикидка 6500:13≈500.',activity:{id:'l61-p18',type:'input',prompt:'Вычисли 6565:13.',answer:['505'],placeholder:'Частное',hint:'13·500=6500 и 13·5=65.',explanation:'6565:13=505; проверка 505·13=6565.'},visual:'written',sourceExercise:'№ 451(3)'},
  {id:'l61-round-zero-model',kind:'model',eyebrow:'№ 452–453 · круглые числа',title:'Сокращаем одинаковое число конечных нулей',body:'В делении 25600:800 можно разделить делимое и делитель на 100: 256:8=32. Это не механическое зачёркивание — оба числа делятся на один и тот же ненулевой множитель.',note:'После сокращения всегда проверяй исходное равенство: 32·800=25600.',visual:'zeros',sourceExercise:'№ 452–453'},
  {id:'l61-452-5',kind:'practice',eyebrow:'№ 452(5)',title:'Две общие сотни',body:'Раздели оба числа на 100.',activity:{id:'l61-p19',type:'input',prompt:'Вычисли 25600:800.',answer:['32'],placeholder:'Частное',hint:'25600:800=256:8.',explanation:'256:8=32; проверка 32·800=25600.'},visual:'zeros',sourceExercise:'№ 452(5)'},
  {id:'l61-453-6',kind:'practice',eyebrow:'№ 453(6)',title:'Четыре общих нуля',body:'124360000 и 40000 делятся на 10000.',activity:{id:'l61-p20',type:'input',prompt:'Вычисли 124360000:40000.',answer:['3109','3 109'],placeholder:'Частное',hint:'Сначала получи 12436:4.',explanation:'124360000:40000=12436:4=3109; 3109·40000=124360000.'},visual:'zeros',sourceExercise:'№ 453(6)'},
  {id:'l61-estimate',kind:'model',eyebrow:'Разумная проверка',title:'Частное должно подходить по масштабу',body:'До точного вычисления оцени результат. Например, 1548:36 близко к 1600:40=40, поэтому ответ 43 реалистичен, а 430 — нет.',note:'Три защиты: смысл задачи, обратное умножение и оценка порядка величины.',visual:'estimate'},
  {id:'l61-error-hunt',kind:'quiz',eyebrow:'Ловушка',title:'Найди невозможное равенство',body:'Одно утверждение нарушает определение деления.',activity:{id:'l61-p21',type:'choice',prompt:'Какую запись нельзя считать верным делением?',options:['0:0=0','0:9=0','9:1=9','9:9=1'],answer:'0:0=0',hint:'При делении частное должно определяться однозначно.',explanation:'0:0 не определено: равенство q·0=0 выполняется для любого q, поэтому единственного частного нет.'},visual:'error'},
  {id:'l61-language',kind:'model',eyebrow:'Математическая речь',title:'Объяснение сильнее голого ответа',body:'Полный ответ на деление содержит три части: называю смысл, записываю частное, доказываю умножением. Например: 72:8=9, потому что девять групп по 8 дают 72.',note:'Такое объяснение сразу обнаруживает перестановку делимого и делителя.',visual:'language'},
  {id:'l61-olympiad',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Когда 100 конфет делятся поровну',body:'Количество детей должно быть натуральным делителем 100. Разложение 100=2²·5² помогает получить все варианты: 1, 2, 4, 5, 10, 20, 25, 50 и 100.',note:'Если нужен настоящий класс, можно отдельно обсудить реалистичные варианты, но математический список должен быть полным.',visual:'olympiad'},
  {id:'l61-self-check',kind:'model',eyebrow:'Чек-лист',title:'Пять вопросов перед ответом',body:'Что является целым? Что задаёт делитель? Ищу размер доли или число групп? Существует ли точное натуральное частное? Какое умножение проверит результат?',note:'Если на все пять вопросов есть ответ, решение устойчиво даже без подсказки.',visual:'language'},
  {id:'l61-summary',kind:'summary',eyebrow:'Урок 61 · итог',title:'Деление стало осмысленным действием',body:'Ты связал два смысла деления с умножением, разобрал компоненты по № 447–449, проверил первые точные вычисления № 450–451 и освоил деление круглых чисел № 452–453.',note:'Теперь пройди обязательную мастерскую: 20 задач и ровно 50 оцениваемых ответов.',visual:'final'}
];

type LabScenario={id:string;label:string;dividend:number;divisor:number;quotient:number};
const labScenarios:LabScenario[]=[
  {id:'twenty-four-six',label:'24 предмета ÷ 6',dividend:24,divisor:6,quotient:4},
  {id:'thirty-five-five',label:'35 предметов ÷ 5',dividend:35,divisor:5,quotient:7},
  {id:'seventy-two-eight',label:'72 предмета ÷ 8',dividend:72,divisor:8,quotient:9}
];

function DivisionLab(){
  const[selected,setSelected]=useState(0);const scenario=labScenarios[selected];
  return <section className="division-lab" data-division-lab="interactive" data-plan-id={scenario.id} data-dividend={scenario.dividend} data-divisor={scenario.divisor} data-quotient={scenario.quotient} data-share-groups={scenario.divisor} data-share-size={scenario.quotient} data-group-size={scenario.divisor} data-group-count={scenario.quotient} data-check-product={scenario.divisor*scenario.quotient} data-equal-models="true">
    <div className="division-lab-tabs">{labScenarios.map((item,index)=><button type="button" key={item.id} className={index===selected?'active':''} onClick={()=>setSelected(index)}>{item.label}</button>)}</div>
    <div className="division-lab-equation"><b>{scenario.dividend}</b><i>:</i><b>{scenario.divisor}</b><i>=</i><strong>{scenario.quotient}</strong></div>
    <div className="division-lab-models">
      <article><small>поровну</small><b>{scenario.divisor} групп</b><div>{Array.from({length:scenario.divisor},(_,index)=><span key={index}>{scenario.quotient}</span>)}</div><p>в каждой по {scenario.quotient}</p></article>
      <article><small>по содержанию</small><b>по {scenario.divisor} в группе</b><div>{Array.from({length:scenario.quotient},(_,index)=><span key={index}>{scenario.divisor}</span>)}</div><p>получилось {scenario.quotient} групп</p></article>
    </div>
    <p className="division-lab-check">Проверка: {scenario.quotient}·{scenario.divisor}={scenario.dividend}</p>
  </section>
}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='lab')return <DivisionLab/>;
  if(kind==='mission')return <div className="division-visual"><div className="division-mission"><span><small>целое</small><b>24</b></span><i>:</i><span><small>условие</small><b>6</b></span><i>=</i><strong>4</strong><em>проверка 4·6=24</em></div></div>;
  if(kind==='meanings')return <div className="division-visual"><div className="division-meanings"><span><small>поровну между 6</small><b>4 каждому</b></span><span><small>группы по 6</small><b>4 группы</b></span></div></div>;
  if(kind==='inverse')return <div className="division-visual"><div className="division-inverse"><span>a:b=c</span><i>⇄</i><strong>c·b=a</strong></div></div>;
  if(kind==='components')return <div className="division-visual"><div className="division-components"><span><small>делимое</small><b>84</b></span><i>:</i><span><small>делитель</small><b>7</b></span><i>=</i><span><small>частное</small><b>12</b></span></div></div>;
  if(kind==='table')return <div className="division-visual"><div className="division-fact-family"><b>8·9=72</b><b>9·8=72</b><strong>72:8=9</strong><strong>72:9=8</strong></div></div>;
  if(kind==='exactness')return <div className="division-visual"><div className="division-exactness"><span><b>36:6=6</b><small>6·6=36 ✓</small></span><span><b>35:6</b><small>30 &lt; 35 &lt; 36</small><em>не точно</em></span></div></div>;
  if(kind==='specials')return <div className="division-visual"><div className="division-specials"><b>a:1=a</b><b>a:a=1</b><b>0:a=0</b><strong>a:0 — нельзя</strong></div></div>;
  if(kind==='check')return <div className="division-visual"><div className="division-check"><span>1248:24</span><i>→</i><b>52</b><i>→</i><strong>52·24=1248 ✓</strong></div></div>;
  if(kind==='written')return <div className="division-visual"><div className="division-written"><span><small>прикидка</small><b>6500:13≈500</b></span><i>+</i><span><small>точная добавка</small><b>65:13=5</b></span><strong>505</strong></div></div>;
  if(kind==='zeros')return <div className="division-visual"><div className="division-zeros"><span>25 600:800</span><i>÷100</i><span>256:8</span><i>=</i><strong>32</strong></div></div>;
  if(kind==='estimate')return <div className="division-visual"><div className="division-estimate"><span><small>прикидка</small><b>1600:40≈40</b></span><strong>43 подходит</strong><del>430 не подходит</del></div></div>;
  if(kind==='error')return <div className="division-visual"><div className="division-errors"><b>0:9=0 ✓</b><b>9:1=9 ✓</b><b>9:9=1 ✓</b><del>0:0=0</del><strong>частное не определено</strong></div></div>;
  if(kind==='language')return <div className="division-visual"><div className="division-language"><b>72:8=9</b><span>девять групп по восемь</span><strong>9·8=72 ✓</strong></div></div>;
  if(kind==='olympiad')return <div className="division-visual"><div className="division-divisors"><small>делители 100</small><b>1 · 2 · 4 · 5 · 10 · 20 · 25 · 50 · 100</b><strong>9 вариантов</strong></div></div>;
  return <div className="division-visual"><div className="division-final"><b>два смысла ✓</b><b>компоненты ✓</b><b>обратная проверка ✓</b><b>ноль и единица ✓</b><b>№ 447–453 ✓</b><b>50 ответов →</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyOneStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function DivisionMeaningPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyOneStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyOneStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==61||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyOneStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonSixtyOneStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player division-meaning-player" data-lesson-number="61" data-source-reference="Мерзляк § 18 · № 447–453" data-source-exercise-range="447-453"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyOneStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyOneStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyOneStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
