import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-35-progress-v1';
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g,'').replace(/−/g,'-').replace(/×|·/g,'*').replace(',', '.');

export const lessonThirtyFiveStages:Stage[]=[
  {id:'l35-mission',kind:'story',eyebrow:'Урок 35 · § 10 · практика',title:'Уравнение — это не угадайка, а последовательность решений',body:'Сегодня уравнения станут на один шаг длиннее. Например, в x + 18 = 74 − 16 сначала удобно вычислить известную правую часть, а уже затем найти неизвестное слагаемое.',note:'План урока: вычисли известную часть → назови роль x → найди x → проверь подстановкой.'},
  {id:'l35-recap',kind:'model',eyebrow:'Разминка',title:'Три роли неизвестного нужно узнавать сразу',body:'x + a = b: x — неизвестное слагаемое. x − a = b: x — неизвестное уменьшаемое. a − x = b: x — неизвестное вычитаемое. Именно роль неизвестного подсказывает обратное действие.'},
  {id:'l35-known-side',kind:'model',eyebrow:'Новый уровень',title:'Если одна часть — числовое выражение, сначала упрости её',body:'В x + 18 = 74 − 16 правая часть полностью известна: 74 − 16 = 58. Получаем простое уравнение x + 18 = 58, поэтому x = 40.'},
  {id:'l35-practice1',kind:'practice',eyebrow:'Практика · 1/7',title:'Неизвестное слагаемое после упрощения',body:'Не перескакивай через первый шаг.',activity:{id:'l35-p1',type:'input',prompt:'Реши уравнение x + 18 = 74 − 16.',answer:'40',placeholder:'x =',hint:'Сначала вычисли 74 − 16, затем найди неизвестное слагаемое.',explanation:'74 − 16 = 58; x + 18 = 58; x = 58 − 18 = 40. Проверка: 40 + 18 = 58.'}},
  {id:'l35-minuend-model',kind:'model',eyebrow:'Случай 2',title:'Числовое выражение может стоять справа и при вычитании',body:'В x − 27 = 45 + 18 сначала получаем 45 + 18 = 63. Теперь x — неизвестное уменьшаемое: x = 63 + 27.'},
  {id:'l35-practice2',kind:'practice',eyebrow:'Практика · 2/7',title:'Неизвестное уменьшаемое',body:'Сначала упрости известную часть.',activity:{id:'l35-p2',type:'input',prompt:'Реши уравнение x − 27 = 45 + 18.',answer:'90',placeholder:'x =',hint:'45 + 18 = 63. Неизвестное уменьшаемое находят сложением.',explanation:'45 + 18 = 63; x = 63 + 27 = 90. Проверка: 90 − 27 = 63.'}},
  {id:'l35-subtrahend-model',kind:'model',eyebrow:'Случай 3',title:'Неизвестное вычитаемое требует другого правила',body:'В 120 − x = 36 + 24 сначала вычисляем 36 + 24 = 60. Затем x — неизвестное вычитаемое: x = 120 − 60.'},
  {id:'l35-practice3',kind:'practice',eyebrow:'Практика · 3/7',title:'Неизвестное вычитаемое',body:'Не путай с неизвестным уменьшаемым.',activity:{id:'l35-p3',type:'input',prompt:'Реши уравнение 120 − x = 36 + 24.',answer:'60',placeholder:'x =',hint:'Сначала найди 36 + 24, затем из уменьшаемого вычти разность.',explanation:'36 + 24 = 60; x = 120 − 60 = 60. Проверка: 120 − 60 = 60.'}},
  {id:'l35-plan',kind:'model',eyebrow:'Алгоритм',title:'Четыре вопроса перед каждым решением',body:'1) Что здесь уже можно вычислить? 2) Какую роль играет x? 3) Какое правило компонентов подходит? 4) Получается ли исходное равенство после подстановки?',note:'Если ученик пропускает первый или второй вопрос, чаще всего и появляется неверное действие.'},
  {id:'l35-practice4',kind:'practice',eyebrow:'Практика · 4/7',title:'Выбери правильную последовательность',body:'Здесь важен не только ответ, но и порядок шагов.',activity:{id:'l35-p4',type:'choice',prompt:'Как правильно начать решение x + 48 = 135 − 27?',options:['Сначала 135 − 27, затем из результата вычесть 48','Сначала 135 + 27, затем прибавить 48','Сразу 48 − 135','Сначала 135 − 48, затем вычесть 27'],answer:'Сначала 135 − 27, затем из результата вычесть 48',hint:'Правая часть полностью известна.',explanation:'Сначала 135 − 27 = 108, затем x = 108 − 48 = 60.'}},
  {id:'l35-check-model',kind:'model',eyebrow:'Самопроверка',title:'Проверяем не сокращённое, а исходное уравнение',body:'Если из x + 18 = 74 − 16 получили x = 40, проверка должна выглядеть так: 40 + 18 = 74 − 16. Обе части равны 58. Это подтверждает и вычисление, и выбранное правило.'},
  {id:'l35-practice5',kind:'practice',eyebrow:'Практика · 5/7',title:'Проверь готовый корень',body:'Подстановка быстрее повторного решения.',activity:{id:'l35-p5',type:'choice',prompt:'Является ли x = 72 корнем уравнения x − 25 = 60 − 13?',options:['Да','Нет'],answer:'Да',hint:'Слева 72 − 25, справа 60 − 13.',explanation:'72 − 25 = 47 и 60 − 13 = 47. Равенство верно, значит 72 — корень.'}},
  {id:'l35-word-model',kind:'model',eyebrow:'Текст → уравнение',title:'Сначала выясни, что было неизвестным',body:'«После того как из неизвестного количества потратили 18, осталось 47» означает: было x, из него вычли 18 и получили 47. Уравнение: x − 18 = 47.'},
  {id:'l35-practice6',kind:'practice',eyebrow:'Практика · 6/7',title:'Выбери модель задачи',body:'Не ориентируйся только на отдельные слова.',activity:{id:'l35-p6',type:'choice',prompt:'У Маши было несколько наклеек. 18 она подарила, после чего осталось 47. Какое уравнение описывает задачу?',options:['x − 18 = 47','18 − x = 47','x + 18 = 47','47 − 18 = x'],answer:'x − 18 = 47',hint:'Неизвестно первоначальное количество.',explanation:'Было x, уменьшили на 18, осталось 47: x − 18 = 47.'}},
  {id:'l35-word-solve',kind:'model',eyebrow:'Модель задачи',title:'Уравнение сохраняет смысл условия',body:'Для x − 18 = 47 неизвестно уменьшаемое, поэтому x = 47 + 18. Ответ 65 можно проверить: 65 − 18 = 47.'},
  {id:'l35-practice7',kind:'practice',eyebrow:'Практика · 7/7',title:'Реши задачу через уравнение',body:'Составь уравнение мысленно и найди неизвестное.',activity:{id:'l35-p7',type:'input',prompt:'В коробке было несколько деталей. После того как 26 деталей взяли, осталось 39. Сколько деталей было сначала?',answer:'65',placeholder:'Ответ',hint:'Составь x − 26 = 39.',explanation:'x = 39 + 26 = 65. Проверка: 65 − 26 = 39.'}},
  {id:'l35-error-model',kind:'model',eyebrow:'Разбор ошибок',title:'Правильное вычисление может стоять после неправильного правила',body:'Если в 90 − x = 34 ученик пишет x = 90 + 34, он сложил числа без учёта роли x. Здесь x — вычитаемое, поэтому x = 90 − 34.'},
  {id:'l35-error-check',kind:'guided',eyebrow:'Диагностика ошибки',title:'Найди неверный шаг',body:'Объяснение ошибки важнее простого исправления.',activity:{id:'l35-a1',type:'choice',prompt:'Ученик решает x − 28 = 75 − 15 так: 75 − 15 = 60; x = 60 − 28 = 32. Где ошибка?',options:['Нужно после 60 прибавить 28','Нужно вычислить 75 + 15','Нужно из 28 вычесть 60','Ошибки нет'],answer:'Нужно после 60 прибавить 28',hint:'x — неизвестное уменьшаемое.',explanation:'После упрощения имеем x − 28 = 60. Неизвестное уменьшаемое: x = 60 + 28 = 88.'}},
  {id:'l35-same-root',kind:'model',eyebrow:'Сравнение уравнений',title:'Разные записи могут приводить к одному корню',body:'Уравнения x + 12 = 40 и x − 5 = 23 имеют один корень: 28. Иногда быстрее решить одно уравнение и подставить результат во второе, чем повторять весь алгоритм.'},
  {id:'l35-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Упрости и реши',body:'Работай по четырём вопросам алгоритма.',activity:{id:'l35-q1',type:'input',prompt:'x + 35 = 120 − 25. Найди x.',answer:'60',placeholder:'x =',hint:'120 − 25 = 95.',explanation:'x + 35 = 95; x = 60. Проверка: 60 + 35 = 95.'}},
  {id:'l35-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Неизвестное уменьшаемое',body:'Сначала вычисли известную часть.',activity:{id:'l35-q2',type:'input',prompt:'x − 46 = 38 + 27. Найди x.',answer:'111',placeholder:'x =',hint:'38 + 27 = 65; затем найди уменьшаемое.',explanation:'x − 46 = 65; x = 65 + 46 = 111.'}},
  {id:'l35-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Неизвестное вычитаемое',body:'Определи роль x до вычисления.',activity:{id:'l35-q3',type:'input',prompt:'150 − x = 90 − 15. Найди x.',answer:'75',placeholder:'x =',hint:'90 − 15 = 75.',explanation:'150 − x = 75; x = 150 − 75 = 75.'}},
  {id:'l35-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Задача → уравнение',body:'Сохрани смысл изменения величины.',activity:{id:'l35-q4',type:'choice',prompt:'На полке было x книг. Поставили ещё 24 книги, и стало 70. Какое уравнение подходит?',options:['x + 24 = 70','x − 24 = 70','24 − x = 70','70 + 24 = x'],answer:'x + 24 = 70',hint:'Количество увеличилось на 24.',explanation:'Было x, прибавили 24, получили 70: x + 24 = 70.'}},
  {id:'l35-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Проверка корня',body:'Проверь обе части исходной записи.',activity:{id:'l35-q5',type:'choice',prompt:'Является ли 54 корнем уравнения 100 − x = 70 − 24?',options:['Да','Нет'],answer:'Да',hint:'Вычисли обе части при x = 54.',explanation:'100 − 54 = 46 и 70 − 24 = 46. Значит 54 — корень.'}},
  {id:'l35-reasoning',kind:'model',eyebrow:'Сильное понимание',title:'Оценка ответа работает и в уравнениях',body:'Если x + 35 = 95, x должен быть меньше 95. Если x − 35 = 95, x должен быть больше 95. Если 150 − x = 75, x меньше 150. Такая оценка быстро ловит неверное действие.'},
  {id:'l35-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Один корень для двух разных записей',body:'Найди значение x, которое одновременно делает верными оба равенства.',activity:{id:'l35-c1',type:'choice',prompt:'Какое число является общим корнем уравнений x + 27 = 100 − 13 и 120 − x = 60?',options:['54','60','66','73'],answer:'60',hint:'Сначала упрости правую часть первого уравнения.',explanation:'100 − 13 = 87; x = 87 − 27 = 60. Во втором: 120 − 60 = 60.'}},
  {id:'l35-selfcheck',kind:'guided',eyebrow:'Самопроверка',title:'Можешь ли ты объяснить решение без слова «перенёс»?',body:'Попробуй вслух объяснить: что вычисляешь первым, каким компонентом является x, какое правило используешь и как проверяешь корень. Если это получается — алгоритм действительно понятен.'},
  {id:'l35-summary',kind:'summary',eyebrow:'Итог урока 35',title:'Сложное уравнение превращаем в простое по шагам',body:'Ты научился сначала упрощать известную часть, затем определять роль неизвестного, выбирать правило компонентов и проверять корень в исходном уравнении. Это основа для следующего, итогового урока § 10.',note:'Следующий урок 36 завершит тему уравнений задачами на рассуждение и систематизацию.'},
];

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirtyFiveStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function EquationPracticePlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonThirtyFiveStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==35||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonThirtyFiveStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonThirtyFiveStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player equation-practice-player" aria-label="Урок 35. Уравнение. Практика"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric"/></div>}<button type="button" className="check-button" disabled={!response.trim()} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><b>§ 10 · практика пройдена</b><span>Упрощение известной части · роль x · задачи · проверка корня</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonThirtyFiveStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonThirtyFiveStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonThirtyFiveStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}
