import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-32-progress-v1';
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g,'').replace(/×|·/g,'*').replace(',', '.');

export const lessonThirtyTwoStages:Stage[]=[
  {id:'l32-mission',kind:'story',eyebrow:'Урок 32 · § 9 · итог',title:'Формула — это правило, которое работает снова и снова',body:'P = 4a, P = 2(a + b), s = vt — не просто записи с буквами. Каждая формула показывает, как одна величина зависит от других. Если меняются исходные данные, формула остаётся той же.',note:'Сегодня работаем в обе стороны: не только подставляем числа, но и восстанавливаем неизвестную величину по готовому результату.'},
  {id:'l32-meaning',kind:'model',eyebrow:'Главная идея',title:'В формуле каждая буква имеет смысл',body:'В P = 4a буква a обозначает сторону квадрата, а P — его периметр. В s = vt буквы означают путь, скорость и время. Перед вычислением важно назвать смысл каждой величины.'},
  {id:'l32-recognize',kind:'guided',eyebrow:'Различаем записи',title:'Найди формулу',body:'Формула — это равенство, которое выражает зависимость между величинами.',activity:{id:'l32-a1',type:'choice',prompt:'Какая запись является формулой? ',options:['3a + 5','48 + 17','P = 4a','72 − x'],answer:'P = 4a',hint:'Ищи равенство, связывающее величины.',explanation:'P = 4a связывает периметр квадрата с длиной его стороны.'}},
  {id:'l32-square-model',kind:'model',eyebrow:'Модель 1',title:'Периметр квадрата: P = 4a',body:'У квадрата четыре равные стороны. Поэтому периметр равен четырём длинам стороны: P = a + a + a + a = 4a.'},
  {id:'l32-practice1',kind:'practice',eyebrow:'Практика · 1/7',title:'Подстановка в формулу квадрата',body:'Подставь значение стороны и вычисли.',activity:{id:'l32-p1',type:'input',prompt:'Найди P по формуле P = 4a, если a = 7 см.',answer:'28',placeholder:'Ответ',hint:'Умножь 4 на 7.',explanation:'P = 4 · 7 = 28 см.'}},
  {id:'l32-rectangle-model',kind:'model',eyebrow:'Модель 2',title:'Периметр прямоугольника: P = 2(a + b)',body:'У прямоугольника две стороны длины a и две стороны длины b. Поэтому P = a + b + a + b = 2(a + b).'},
  {id:'l32-practice2',kind:'practice',eyebrow:'Практика · 2/7',title:'Периметр прямоугольника',body:'Сначала сложи стороны в скобках.',activity:{id:'l32-p2',type:'input',prompt:'Найди P, если a = 8 см, b = 5 см.',answer:'26',placeholder:'Ответ',hint:'P = 2 · (8 + 5).',explanation:'8 + 5 = 13, затем 2 · 13 = 26 см.'}},
  {id:'l32-path-model',kind:'model',eyebrow:'Модель 3',title:'Путь: s = vt',body:'Если скорость постоянна, путь равен произведению скорости на время. Например, при v = 60 км/ч и t = 3 ч путь равен 180 км.'},
  {id:'l32-practice3',kind:'practice',eyebrow:'Практика · 3/7',title:'Путь по скорости и времени',body:'Следи не только за числом, но и за единицами.',activity:{id:'l32-p3',type:'input',prompt:'Найди путь s при v = 70 км/ч и t = 4 ч.',answer:'280',placeholder:'Ответ',hint:'s = 70 · 4.',explanation:'s = 280 км.'}},
  {id:'l32-units',kind:'model',eyebrow:'Единицы измерения',title:'Число без единицы может потерять смысл',body:'Если скорость дана в км/ч, а время в часах, путь получится в километрах. Если единицы не согласованы, сначала нужно привести их к совместимому виду.'},
  {id:'l32-practice4',kind:'practice',eyebrow:'Практика · 4/7',title:'Проверка единиц',body:'Определи правильную единицу результата.',activity:{id:'l32-p4',type:'choice',prompt:'v = 45 км/ч, t = 2 ч. В каких единицах измеряется найденный путь?',options:['км','км/ч','ч','см'],answer:'км',hint:'Скорость умножается на время.',explanation:'(км/ч) · ч = км.'}},
  {id:'l32-inverse-square',kind:'model',eyebrow:'Обратная задача',title:'По периметру можно найти сторону',body:'Если P = 4a и известен P, рассуждаем обратно: какая сторона, умноженная на 4, дала этот периметр? Это проверка понимания формулы, а не механическая подстановка.'},
  {id:'l32-practice5',kind:'practice',eyebrow:'Практика · 5/7',title:'Найди неизвестную сторону',body:'Используй обратное действие.',activity:{id:'l32-p5',type:'input',prompt:'Периметр квадрата 36 см. Найди сторону a.',answer:'9',placeholder:'Ответ',hint:'36 : 4.',explanation:'a = 36 : 4 = 9 см.'}},
  {id:'l32-inverse-path',kind:'model',eyebrow:'Обратная задача',title:'Из s = vt можно восстановить скорость или время',body:'Если известны путь и время, скорость равна s : t. Если известны путь и скорость, время равно s : v.'},
  {id:'l32-practice6',kind:'practice',eyebrow:'Практика · 6/7',title:'Найди скорость',body:'Путь раздели на время.',activity:{id:'l32-p6',type:'input',prompt:'Автомобиль прошёл 240 км за 4 ч. Найди скорость.',answer:'60',placeholder:'Ответ',hint:'v = s : t.',explanation:'240 : 4 = 60 км/ч.'}},
  {id:'l32-compose',kind:'model',eyebrow:'Составляем формулу',title:'Текстовую зависимость можно записать одной строкой',body:'Если билет стоит 12 рублей, а ученик покупает n билетов и ещё платит 30 рублей за экскурсию, общую стоимость c можно записать формулой c = 12n + 30.'},
  {id:'l32-practice7',kind:'practice',eyebrow:'Практика · 7/7',title:'Переведи условие в формулу',body:'Сначала найди часть, которая зависит от количества.',activity:{id:'l32-p7',type:'choice',prompt:'Одна тетрадь стоит 7 рублей, доставка — 20 рублей. Какая формула задаёт стоимость c для n тетрадей?',options:['c = 7n + 20','c = 7 + n + 20','c = 20n + 7','c = 7n − 20'],answer:'c = 7n + 20',hint:'Стоимость тетрадей равна 7n, доставка добавляется один раз.',explanation:'c = 7n + 20.'}},
  {id:'l32-table',kind:'guided',eyebrow:'Таблица значений',title:'Одна формула создаёт много результатов',body:'Для c = 7n + 20 при n = 1, 2, 3 получаем 27, 34, 41. Значение растёт на 7 каждый раз, потому что каждая новая тетрадь добавляет 7 рублей.',activity:{id:'l32-a2',type:'input',prompt:'По формуле c = 7n + 20 найди c при n = 5.',answer:'55',placeholder:'Ответ',hint:'7 · 5 + 20.',explanation:'35 + 20 = 55.'}},
  {id:'l32-reasonableness',kind:'model',eyebrow:'Проверка смысла',title:'Формула должна давать разумный результат',body:'Если квадрат со стороной 10 см вдруг получил периметр 2 см, ошибка очевидна ещё до пересчёта. Прикидка и здравый смысл — часть работы с формулами.'},
  {id:'l32-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Периметр квадрата',body:'Без подсказки из предыдущего шага.',activity:{id:'l32-q1',type:'input',prompt:'P = 4a, a = 12. Найди P.',answer:'48',placeholder:'Ответ',hint:'4 · 12.',explanation:'P = 48.'}},
  {id:'l32-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Периметр прямоугольника',body:'Сначала скобки.',activity:{id:'l32-q2',type:'input',prompt:'P = 2(a + b), a = 9, b = 6. Найди P.',answer:'30',placeholder:'Ответ',hint:'2 · (9 + 6).',explanation:'P = 30.'}},
  {id:'l32-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Путь',body:'Используй s = vt.',activity:{id:'l32-q3',type:'input',prompt:'v = 55 км/ч, t = 3 ч. Найди s.',answer:'165',placeholder:'Ответ',hint:'55 · 3.',explanation:'s = 165 км.'}},
  {id:'l32-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Обратное вычисление',body:'Теперь результат формулы известен.',activity:{id:'l32-q4',type:'input',prompt:'s = 300 км, t = 5 ч. Найди v.',answer:'60',placeholder:'Ответ',hint:'300 : 5.',explanation:'v = 60 км/ч.'}},
  {id:'l32-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Составь формулу',body:'Выбери точную математическую модель.',activity:{id:'l32-q5',type:'choice',prompt:'Было 500 рублей. Каждый день тратят по d рублей в течение n дней. Какая формула задаёт остаток r?',options:['r = 500 − dn','r = 500 + dn','r = 500n − d','r = d − 500n'],answer:'r = 500 − dn',hint:'За n дней потратят dn рублей.',explanation:'Из начальных 500 вычитают общую сумму расходов dn.'}},
  {id:'l32-thinking',kind:'model',eyebrow:'Сильное понимание',title:'Формула показывает, как меняется результат',body:'В c = 7n + 20 увеличение n на 1 увеличивает c на 7. В r = 500 − dn увеличение n на 1 уменьшает остаток на d. Так формула позволяет рассуждать даже без конкретных чисел.'},
  {id:'l32-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Найди подходящие размеры',body:'Используй формулу периметра и перебор натуральных сторон.',activity:{id:'l32-c1',type:'choice',prompt:'Периметр прямоугольника 20 см. Какая пара натуральных сторон подходит?',options:['4 см и 6 см','4 см и 5 см','3 см и 8 см','2 см и 9 см'],answer:'4 см и 6 см',hint:'Проверь 2(a + b) = 20.',explanation:'2 · (4 + 6) = 20. Для остальных пар периметр другой.'}},
  {id:'l32-selfcheck',kind:'model',eyebrow:'Самопроверка',title:'Четыре вопроса к любой формуле',body:'1) Что означает каждая буква? 2) Какие данные известны? 3) В каких единицах они даны? 4) Разумен ли результат? Этот чек-лист защищает от большинства ошибок.'},
  {id:'l32-summary',kind:'summary',eyebrow:'Итог § 9',title:'Теперь формула — не набор букв, а математическая модель',body:'Ты умеешь читать формулу, подставлять значения, восстанавливать неизвестную величину, следить за единицами и составлять простые зависимости по тексту. Следующий урок — контрольная работа № 2.',note:'После основной части пройди 20 обязательных заданий. Они завершают § 9 перед контролем.'},
];

function loadSaved():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Saved|null;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return parsed}catch{/* ignore */}return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}

export function FormulaPracticePlayer(){
  const initial=useMemo(loadSaved,[]);
  const[stageIndex,setStageIndex]=useState(Math.min(initial.stageIndex,lessonThirtyTwoStages.length-1));
  const[responses,setResponses]=useState<Record<string,string>>(initial.responses);
  const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);
  const[results,setResults]=useState<Record<string,boolean>>(initial.results);
  const stage=lessonThirtyTwoStages[stageIndex];const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const jump=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==32||!Number.isInteger(detail.stageIndex))return;stopVoice();setStageIndex(Math.max(0,Math.min(Number(detail.stageIndex),lessonThirtyTwoStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('mathnikita-go-to-stage',jump);return()=>window.removeEventListener('mathnikita-go-to-stage',jump)},[]);
  function stopVoice(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));window.speechSynthesis?.cancel()}
  function moveTo(index:number){stopVoice();setStageIndex(Math.max(0,Math.min(index,lessonThirtyTwoStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})}
  function choose(value:string){if(!activity)return;setResponses(current=>({...current,[activity.id]:value}));setChecked(current=>({...current,[activity.id]:false}));setResults(current=>({...current,[activity.id]:false}))}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(current=>({...current,[activity.id]:true}));setResults(current=>({...current,[activity.id]:correct}))}
  const canAdvance=!activity||isCorrect;const percent=Math.round(((stageIndex+1)/lessonThirtyTwoStages.length)*100);
  return <main className="lesson-player"><div className="lesson-progress" aria-label={`Пройдено ${percent}% урока`}><i style={{width:`${percent}%`}}/></div><section className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}>
    <div className="stage-counter"><span>Этап {stageIndex+1} из {lessonThirtyTwoStages.length}</span><div><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0} aria-label="Предыдущий этап">←</button><button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={stageIndex===lessonThirtyTwoStages.length-1||!canAdvance} aria-label="Следующий этап">→</button></div></div>
    <div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside>{stage.note}</aside>:null}</div>
    {activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<><div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>choose(option)} disabled={isCorrect}>{option}</button>)}</div><button type="button" className="check-button" onClick={checkAnswer} disabled={!response.trim()||isCorrect}>Проверить</button></>:<div className="inline-answer"><input value={response} onChange={event=>choose(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Введи ответ'} disabled={isCorrect}/><button type="button" className="check-button" onClick={checkAnswer} disabled={!response.trim()||isCorrect}>Проверить</button></div>}{isChecked&&!isCorrect?<div className="instant-feedback bad" data-explanation={activity.explanation}><b>Пока не так.</b><span>{activity.hint}</span></div>:null}{isCorrect?<div className="instant-feedback good"><b>Верно!</b><span>{activity.explanation}</span></div>:null}</div>:null}
    {stage.kind==='summary'?<div className="summary-card"><b>Основная часть урока 32 завершена</b><span>Теперь закрепи формулы в 20 обязательных заданиях и заверши § 9 перед контрольной работой № 2.</span></div>:null}
    {stage.kind!=='summary'?<div className="lesson-controls"><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={!canAdvance}>{activity&&!isCorrect?'Сначала реши задание':'Дальше →'}</button></div>:null}
  </section></main>;
}
