import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './segmentLength.css';
import './polyline.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type GeometrySummaryStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-9-progress-v2';

export const lessonNineStages:GeometrySummaryStage[]=[
  {id:'l9-story',kind:'story',eyebrow:'Обобщение § 3',title:'Точка, отрезок и ломаная — одна система',body:'Сегодня новой формулы нет. Задача урока — быстро узнавать геометрическую ситуацию, выбирать нужное правило и уверенно работать с длинами.',note:'Сначала определи фигуру и порядок точек, затем единицы и только потом действие.',sourceTag:'Методическое пособие Мерзляка · технологическая карта урока № 9'},
  {id:'l9-map',kind:'model',eyebrow:'Карта темы',title:'От точки к маршруту',body:'Две точки задают отрезок. Ломаную образует последовательная цепочка отрезков, в которой соседние звенья имеют общий конец и не лежат на одной прямой.',note:'Ключевые понятия урока: точка, отрезок, длина, единичный отрезок, равные отрезки, ломаная, длина ломаной, замкнутая ломаная.',sourceTag:'Методическое пособие · урок № 9 · основные понятия'},
  {id:'l9-diagnostic',kind:'guided',eyebrow:'Актуализация',title:'Узнай фигуру по полному определению',body:'Одного последовательного соединения недостаточно: в вершине ломаной соседние звенья должны менять направление.',activity:{id:'l9-a1',type:'choice',prompt:'Когда отрезки AB, BC и CD образуют ломаную ABCD?',options:['Когда они соединены последовательно и соседние звенья не лежат на одной прямой','Когда все три отрезка лежат на одной прямой','Когда AB и CD не имеют общих точек','Когда все звенья имеют одинаковую длину'],answer:'Когда они соединены последовательно и соседние звенья не лежат на одной прямой',explanation:'У ломаной соседние звенья имеют общий конец и не лежат на одной прямой, поэтому в каждой внутренней вершине направление меняется.'},sourceTag:'Методическое пособие · урок № 9 · актуализация знаний'},
  {id:'l9-segment-rule',kind:'model',eyebrow:'Свойство длины',title:'Целый отрезок складывается из частей',body:'Если точка C лежит на отрезке AB, то длина всего отрезка равна сумме длин его частей.',note:'AB = AC + CB.',sourceTag:'Мерзляк § 3 · свойство длины отрезка'},
  {id:'l9-segment-part',kind:'guided',eyebrow:'Проверяем правило',title:'Найди неизвестную часть',body:'Точка C лежит между A и B. Известны весь отрезок и одна часть.',activity:{id:'l9-a2',type:'input',prompt:'AB = 35 см, AC = 12 см. Чему равен CB?',answer:'23',placeholder:'Ответ в см',explanation:'CB = AB − AC = 35 − 12 = 23 см.'}},
  {id:'l9-polyline-rule',kind:'model',eyebrow:'Длина ломаной',title:'Маршрут складывается из всех звеньев',body:'Чтобы найти длину ломаной, нужно учесть каждое её звено и сложить их длины.',note:'Для CDEF: длина = CD + DE + EF.',sourceTag:'Мерзляк § 3 · длина ломаной'},
  {id:'l9-polyline-length',kind:'guided',eyebrow:'Математический диктант',title:'Три звена — одна длина',body:'В методическом пособии дана ломаная CDEF: CD = 8 мм, DE = 10 мм, EF = 14 мм.',activity:{id:'l9-a3',type:'input',prompt:'Какова длина ломаной CDEF?',answer:'32',placeholder:'Ответ в мм',explanation:'8 + 10 + 14 = 32 мм.'},sourceTag:'Методическое пособие · математический диктант 2 · задание 7'},
  {id:'l9-units',kind:'guided',eyebrow:'Единицы длины',title:'Сравнивать можно после перевода',body:'Равные длины могут выглядеть по-разному, если записаны в разных единицах.',activity:{id:'l9-a4',type:'choice',prompt:'Какие равенства верны, если AB = 4 см 8 мм, NP = 48 мм, MK = 5 дм 4 мм, ST = 504 мм?',options:['AB = NP и MK = ST','только AB = NP','только MK = ST','ни одно из равенств'],answer:'AB = NP и MK = ST',explanation:'4 см 8 мм = 48 мм, поэтому AB = NP. 5 дм 4 мм = 504 мм, поэтому одновременно MK = ST.'},sourceTag:'Методическое пособие · математический диктант 2 · задание 5'},
  {id:'l9-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'№ 68: длина ломаной ACDM',body:'AC = 15 мм, CD = 24 мм, DM = 32 мм.',activity:{id:'l9-p1',type:'input',prompt:'Вычисли длину ломаной ACDM.',answer:'71',placeholder:'Ответ в мм',explanation:'15 + 24 + 32 = 71 мм.'},sourceTag:'Мерзляк § 3 · № 68'},
  {id:'l9-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'№ 71: внимательно прочитай порядок точек',body:'Точки идут A—B—C—D. Даны AC = 8 см, BC = 2 см, BD = 6 см.',activity:{id:'l9-p2',type:'input',prompt:'Найди AD.',answer:'12',placeholder:'Ответ в см',explanation:'Сначала AB = AC − BC = 8 − 2 = 6 см. Затем AD = AB + BD = 6 + 6 = 12 см.'},sourceTag:'Мерзляк § 3 · № 71'},
  {id:'l9-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'№ 74: точки и соседние промежутки',body:'На первом отрезке отмечено 7 точек через 3 см, на втором — 10 точек через 2 см.',activity:{id:'l9-p3',type:'choice',prompt:'Как соотносятся расстояния между крайними отмеченными точками?',options:['равны','первое больше','второе больше','данных недостаточно'],answer:'равны',explanation:'Первое расстояние: (7 − 1)·3 = 18 см. Второе: (10 − 1)·2 = 18 см.'},sourceTag:'Мерзляк § 3 · № 74 · методический комментарий'},
  {id:'l9-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Равные отрезки в разных единицах',body:'Продолжаем контроль единиц измерения.',activity:{id:'l9-p4',type:'choice',prompt:'Чему равны 5 дм 4 мм?',options:['504 мм','54 мм','540 мм','5 004 мм'],answer:'504 мм',explanation:'5 дм = 500 мм; 500 + 4 = 504 мм.'},sourceTag:'Методическое пособие · математический диктант 2'},
  {id:'l9-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Ломаная со смешанными единицами',body:'Два звена имеют длины 28 мм и 2 см.',activity:{id:'l9-p5',type:'input',prompt:'Найди длину ломаной в миллиметрах.',answer:'48',placeholder:'Ответ в мм',explanation:'2 см = 20 мм; 28 + 20 = 48 мм.'},sourceTag:'Методическое пособие · математический диктант 2 · задание 8'},
  {id:'l9-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Универсальный алгоритм § 3',body:'На обобщающем уроке важно не угадывать действие, а проходить одни и те же шаги.',activity:{id:'l9-p6',type:'order',prompt:'Расставь шаги решения геометрической задачи',items:['Проверить ответ и подписать единицу','Привести величины к одной единице','Определить фигуру и порядок точек','Выбрать сложение, вычитание или построение','Выделить известные и искомые длины'],answer:['Определить фигуру и порядок точек','Выделить известные и искомые длины','Привести величины к одной единице','Выбрать сложение, вычитание или построение','Проверить ответ и подписать единицу'],explanation:'Такой порядок объединяет задачи на отрезки, ломаные, измерение и построение.'},sourceTag:'Методическое пособие · урок № 9 · обобщение и систематизация'},
  {id:'l9-control',kind:'model',eyebrow:'Контроль и коррекция',title:'Проверяем не только арифметику',body:'Ошибка в геометрической задаче часто появляется раньше вычислений: перепутан порядок точек, пропущено звено или смешаны единицы.',note:'Проверка: фигура → части → единицы → действие → результат.',sourceTag:'Методическое пособие · урок № 9 · контроль и коррекция знаний'},
  {id:'l9-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Целое из двух частей',body:'Без подсказки.',activity:{id:'l9-q1',type:'input',prompt:'A—C—B, AC = 23 см, CB = 17 см. Найди AB.',answer:'40',placeholder:'Ответ в см',explanation:'AB = AC + CB = 23 + 17 = 40 см.'}},
  {id:'l9-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Неизвестная часть',body:'Без подсказки.',activity:{id:'l9-q2',type:'input',prompt:'A—C—B, AB = 52 см, AC = 31 см. Найди CB.',answer:'21',placeholder:'Ответ в см',explanation:'CB = 52 − 31 = 21 см.'}},
  {id:'l9-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Длина ломаной',body:'Без подсказки.',activity:{id:'l9-q3',type:'input',prompt:'Звенья ломаной равны 12 мм, 9 мм и 15 мм. Найди её длину.',answer:'36',placeholder:'Ответ в мм',explanation:'12 + 9 + 15 = 36 мм.'}},
  {id:'l9-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Перевод единиц',body:'Без подсказки.',activity:{id:'l9-q4',type:'input',prompt:'Сколько миллиметров в 6 см 4 мм?',answer:'64',placeholder:'Ответ в мм',explanation:'6 см = 60 мм; 60 + 4 = 64 мм.'}},
  {id:'l9-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Замкнутая ломаная',body:'Без подсказки.',activity:{id:'l9-q5',type:'choice',prompt:'Какой признак определяет замкнутую ломаную?',options:['её концы совпадают','все звенья равны','у неё три вершины','она состоит только из горизонтальных звеньев'],answer:'её концы совпадают',explanation:'У замкнутой ломаной начало и конец совпадают.'}},
  {id:'l9-challenge',kind:'challenge',eyebrow:'Задача повышенного уровня · № 77',title:'Линейка с отметками 0, 5 и 13',body:'Используй только реально доступные отметки и уже построенные расстояния: получи 8 и 3 см, отметь 15 см тремя шагами по 5, затем построй 16 см как 13 + 3.',activity:{id:'l9-c1',type:'order',prompt:'Расставь корректные шаги получения длины 1 см',items:['Получить 1 см как 16 − 15','Получить 3 см как 13 − 5 − 5','Получить 8 см как 13 − 5','Получить 2 см как 15 − 13'],answer:['Получить 8 см как 13 − 5','Получить 3 см как 13 − 5 − 5','Получить 2 см как 15 − 13','Получить 1 см как 16 − 15'],explanation:'13 − 5 = 8 см; внутри 13 см после двух отрезков по 5 см остаётся 3 см; три шага по 5 дают отметку 15, поэтому 15 − 13 = 2 см; 13 + 3 = 16, значит 16 − 15 = 1 см.'},sourceTag:'Мерзляк § 3 · № 77; технологическая карта урока № 9'},
  {id:'l9-reflection',kind:'model',eyebrow:'Рефлексия',title:'Что теперь стало навыком?',body:'Заверши три фразы из технологической карты: «У меня получилось …», «Меня удивило …», «Теперь я умею …».',note:'Смысл рефлексии — заметить не только правильный ответ, но и способ, который теперь можешь повторить самостоятельно.',sourceTag:'Методическое пособие · урок № 9 · рефлексия'},
  {id:'l9-summary',kind:'summary',eyebrow:'Итог основной части § 3',title:'Отрезки и ломаные собраны в единую систему',body:'Ты повторил точку и отрезок, свойство AB = AC + CB, измерение и перевод единиц, равные отрезки, полное определение ломаной и её длину, а затем прошёл контроль по всей теме.',note:'Основная часть закончена. Дальше — обязательная практика и собственное итоговое объяснение. Следующий урок откроет § 4 — «Плоскость. Прямая. Луч».'}
];

const empty:Saved={version:2,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonNineStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

export function GeometrySummaryPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
  const stage=lessonNineStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l9-q1','l9-q2','l9-q3','l9-q4','l9-q5'];const practice=['l9-p1','l9-p2','l9-p3','l9-p4','l9-p5','l9-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonNineStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===9&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonNineStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:9}}))}
  const model=useMemo(()=>{
    if(['l9-story','l9-map','l9-diagnostic'].includes(stage.id))return <div className="polyline-unit-model"><span>точка</span><b>→</b><span>отрезок</span><b>→</b><strong>ломаная с поворотами</strong></div>;
    if(['l9-segment-rule','l9-segment-part','l9-quiz1','l9-quiz2'].includes(stage.id))return <div className="l6-addition-model"><div><span>A</span><i/><span>C</span><i/><span>B</span></div><strong>AB = AC + CB</strong></div>;
    if(['l9-polyline-rule','l9-polyline-length','l9-practice1','l9-quiz3'].includes(stage.id))return <div className="polyline-sum"><div className="mini-zig"><i/><i/><i/></div><strong>длина ломаной = сумма длин звеньев</strong></div>;
    if(['l9-units','l9-practice4','l9-practice5','l9-quiz4'].includes(stage.id))return <div className="polyline-unit-model"><span>1 см = 10 мм</span><b>·</b><span>1 дм = 100 мм</span><b>→</b><strong>одна единица</strong></div>;
    if(stage.id==='l9-practice2')return <div className="l7-chain-model"><span>A</span><i/><span>B</span><i/><span>C</span><i/><span>D</span><strong>AC = AB + BC · AD = AB + BD</strong></div>;
    if(stage.id==='l9-practice3')return <div className="polyline-points-rule"><div>{Array.from({length:7},(_,i)=><span key={i}/>)}</div><strong>7 точек → 6·3 = 18 см · 10 точек → 9·2 = 18 см</strong></div>;
    if(['l9-practice6','l9-control'].includes(stage.id))return <div className="polyline-unit-model"><span>фигура</span><b>→</b><span>части</span><b>→</b><span>единицы</span><b>→</b><strong>действие</strong></div>;
    if(stage.id==='l9-quiz5')return <div className="polyline-closed"><div><span>A</span><span>B</span><span>C</span><span>D</span><i/><i/><i/><i/></div><strong>начало = конец</strong></div>;
    if(stage.id==='l9-challenge')return <div className="polyline-ruler"><div><span>0</span><i/><span>5</span><i className="long"/><span>13</span></div><strong>8 = 13 − 5 → 3 = 13 − 5 − 5 → 2 = 15 − 13 → 1 = 16 − 15</strong></div>;
    if(stage.id==='l9-reflection')return <div className="polyline-unit-model"><span>Получилось</span><b>·</b><span>Удивило</span><b>·</b><strong>Теперь умею</strong></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page segment-length-page polyline-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 9 из 175 · § 3</span><h1>Отрезок. Длина отрезка. Ломаная — обобщение</h1><p>Урок обобщения по технологической карте Мерзляка: точка, отрезок, измерение и построение, равные длины, ломаная и контроль всей темы.</p></div><div className="lesson-duration">План · 45 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonNineStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Сначала определи фигуру, порядок точек и единицы. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'§ 3 закреплён':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>Основная часть ✓</b><small>дальше — обязательная практика</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% основной части</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonNineStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
