import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-31-progress-v1';

export const lessonThirtyOneStages:Stage[]=[
  {id:'l31-mission',kind:'story',eyebrow:'Урок 31 · § 9 · закрепление',title:'Буква хранит место для числа',body:'Выражение a + 7 не имеет одного постоянного значения. Если a = 5, получаем 12; если a = 100, получаем 107. Буква позволяет одной записью описать сразу много похожих вычислений.',note:'Сегодня важен не только ответ, но и алгоритм: понять смысл буквы → подставить число → получить числовое выражение → вычислить.'},
  {id:'l31-variable',kind:'model',eyebrow:'Главная идея',title:'Переменная может принимать разные значения',body:'Букву, вместо которой можно подставлять разные числа, называют переменной. В выражении x + 12 переменная x может быть равна 3, 20, 105 и другим допустимым значениям.'},
  {id:'l31-recognize',kind:'guided',eyebrow:'Различаем записи',title:'Найди буквенное выражение',body:'Буквенное выражение содержит число или букву, соединённые действиями, но само по себе не обязано быть равенством.',activity:{id:'l31-a1',type:'choice',prompt:'Какая запись является буквенным выражением?',options:['37 + 18','5a + 2','P = 4a','48 = 48'],answer:'5a + 2',hint:'Ищи запись с буквой и действиями, но без формулы-равенства.',explanation:'5a + 2 — буквенное выражение. P = 4a — уже формула, то есть равенство.'}},
  {id:'l31-implicit-multiply',kind:'model',eyebrow:'Короткая запись',title:'3a означает 3 · a',body:'В буквенных выражениях знак умножения между числом и буквой часто опускают: 3 · a = 3a. Но 3a нельзя путать с 3 + a.'},
  {id:'l31-practice1',kind:'practice',eyebrow:'Практика · 1/7',title:'Первая подстановка',body:'Замени букву её значением, затем вычисли.',activity:{id:'l31-p1',type:'input',prompt:'Найди значение b + 15 при b = 20.',answer:'35',placeholder:'Ответ',hint:'Вместо b поставь 20.',explanation:'20 + 15 = 35.'}},
  {id:'l31-substitution-algorithm',kind:'model',eyebrow:'Алгоритм',title:'Подстановка превращает буквенную запись в числовую',body:'Например, 3x − 2 при x = 4 превращается в 3 · 4 − 2. После подстановки букв не остаётся, поэтому дальше действуют обычные правила вычислений.'},
  {id:'l31-practice2',kind:'practice',eyebrow:'Практика · 2/7',title:'Буква встречается в произведении',body:'Не забудь скрытый знак умножения.',activity:{id:'l31-p2',type:'input',prompt:'Найди значение 3x − 2 при x = 4.',answer:'10',placeholder:'Ответ',hint:'3x = 3 · x.',explanation:'3 · 4 − 2 = 12 − 2 = 10.'}},
  {id:'l31-repeat-variable',kind:'model',eyebrow:'Одна буква несколько раз',title:'Подставляй значение вместо каждого появления буквы',body:'Если a = 6, то в выражении 2a + a + 5 число 6 нужно поставить три раза: 2 · 6 + 6 + 5.'},
  {id:'l31-practice3',kind:'practice',eyebrow:'Практика · 3/7',title:'Повторяющаяся переменная',body:'Проследи, чтобы ни одна буква не осталась без подстановки.',activity:{id:'l31-p3',type:'input',prompt:'Найди значение 2a + a + 5 при a = 6.',answer:'23',placeholder:'Ответ',hint:'Получится 2 · 6 + 6 + 5.',explanation:'12 + 6 + 5 = 23.'}},
  {id:'l31-two-variables',kind:'model',eyebrow:'Две переменные',title:'У каждой буквы — своё значение',body:'В выражении a + 2b при a = 7 и b = 5 нужно следить, какая цифра заменяет какую букву: 7 + 2 · 5.'},
  {id:'l31-practice4',kind:'practice',eyebrow:'Практика · 4/7',title:'Две буквы',body:'Подставь оба значения.',activity:{id:'l31-p4',type:'input',prompt:'Найди a + 2b при a = 7, b = 5.',answer:'17',placeholder:'Ответ',hint:'Получится 7 + 2 · 5.',explanation:'7 + 10 = 17.'}},
  {id:'l31-parentheses',kind:'model',eyebrow:'Скобки',title:'Сначала подстановка, затем порядок действий',body:'Для 2(a + 5) при a = 8 получаем 2 · (8 + 5). Скобки по-прежнему выполняются раньше умножения.'},
  {id:'l31-practice5',kind:'practice',eyebrow:'Практика · 5/7',title:'Выражение со скобками',body:'Соблюдай порядок действий.',activity:{id:'l31-p5',type:'input',prompt:'Найди 2(a + 5) при a = 8.',answer:'26',placeholder:'Ответ',hint:'Сначала вычисли 8 + 5.',explanation:'2 · (8 + 5) = 2 · 13 = 26.'}},
  {id:'l31-text-language',kind:'model',eyebrow:'Перевод с русского на математический',title:'Текст можно сжать до одной буквенной записи',body:'«У Пифагора было m монет, он получил ещё 12» записывается как m + 12. Если затем потратил k монет — m + 12 − k.'},
  {id:'l31-practice6',kind:'practice',eyebrow:'Практика · 6/7',title:'Составь выражение',body:'Смотри на изменение количества, а не на отдельные слова.',activity:{id:'l31-p6',type:'choice',prompt:'Было n книг, подарили ещё 9, затем 4 книги отдали. Какое выражение показывает, сколько осталось?',options:['n + 9 − 4','n − 9 + 4','9 − n − 4','n + 9 + 4'],answer:'n + 9 − 4',hint:'Подарили — прибавили, отдали — вычли.',explanation:'Количество сначала увеличилось на 9, затем уменьшилось на 4.'}},
  {id:'l31-same-expression',kind:'model',eyebrow:'Одна запись — таблица значений',title:'Меняется переменная — меняется значение выражения',body:'Для выражения 2x + 3 при x = 1 получаем 5, при x = 4 — 11, при x = 10 — 23. Именно поэтому буквенная запись заменяет множество отдельных примеров.'},
  {id:'l31-practice7',kind:'practice',eyebrow:'Практика · 7/7',title:'Новое значение той же записи',body:'Используй то же выражение, меняя только x.',activity:{id:'l31-p7',type:'input',prompt:'Найди 2x + 3 при x = 12.',answer:'27',placeholder:'Ответ',hint:'Подставь x = 12.',explanation:'2 · 12 + 3 = 24 + 3 = 27.'}},
  {id:'l31-compare',kind:'guided',eyebrow:'Сравнение без длинных вычислений',title:'Иногда структура выражения говорит больше, чем конкретное значение',body:'Для одного и того же натурального a выражение a + 12 всегда на 3 больше, чем a + 9. Значение a можно даже не знать.',activity:{id:'l31-a2',type:'choice',prompt:'Что больше при одном и том же a: a + 12 или a + 9?',options:['a + 12','a + 9','Они всегда равны','Зависит от a'],answer:'a + 12',hint:'Обе записи содержат одинаковое a. Сравни только прибавляемые числа.',explanation:'12 на 3 больше 9, поэтому a + 12 всегда на 3 больше a + 9.'}},
  {id:'l31-mistake',kind:'model',eyebrow:'Типичная ошибка',title:'3a и 3 + a — разные выражения',body:'При a = 5 выражение 3a равно 15, а 3 + a равно 8. Потерянный или придуманный знак действия полностью меняет смысл записи.'},
  {id:'l31-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Подстановка',body:'Без подсказки из теории.',activity:{id:'l31-q1',type:'input',prompt:'a + 9 при a = 11.',answer:'20',placeholder:'Ответ',hint:'Замени a числом 11.',explanation:'11 + 9 = 20.'}},
  {id:'l31-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Вычитание',body:'Следи за порядком чисел.',activity:{id:'l31-q2',type:'input',prompt:'50 − x при x = 18.',answer:'32',placeholder:'Ответ',hint:'Получится 50 − 18.',explanation:'50 − 18 = 32.'}},
  {id:'l31-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Произведение',body:'Вспомни короткую запись.',activity:{id:'l31-q3',type:'input',prompt:'4n при n = 7.',answer:'28',placeholder:'Ответ',hint:'4n = 4 · n.',explanation:'4 · 7 = 28.'}},
  {id:'l31-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Две переменные',body:'Подставь каждое число на своё место.',activity:{id:'l31-q4',type:'input',prompt:'2a + b при a = 9, b = 4.',answer:'22',placeholder:'Ответ',hint:'2 · 9 + 4.',explanation:'18 + 4 = 22.'}},
  {id:'l31-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Перевод условия',body:'Выбери запись, которая точно сохраняет смысл.',activity:{id:'l31-q5',type:'choice',prompt:'У Маши было m наклеек, она купила ещё k наборов по 6 наклеек. Сколько стало?',options:['m + 6k','6m + k','m + 6 + k','m − 6k'],answer:'m + 6k',hint:'В k наборах по 6 наклеек находится 6k наклеек.',explanation:'К исходным m наклейкам прибавили 6k новых.'}},
  {id:'l31-thinking',kind:'model',eyebrow:'Сильное понимание',title:'Буквенное выражение описывает зависимость',body:'Когда число наборов k увеличивается на 1, выражение m + 6k увеличивается на 6. Можно рассуждать о результате ещё до конкретной подстановки.'},
  {id:'l31-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Найди все подходящие значения буквы',body:'Проверь натуральные значения a и используй неравенство как ограничение.',activity:{id:'l31-c1',type:'choice',prompt:'Какие натуральные a удовлетворяют условию a + 5 < 10?',options:['1, 2, 3, 4','1, 2, 3, 4, 5','5, 6, 7, 8','Только 4'],answer:'1, 2, 3, 4',hint:'Из a + 5 < 10 следует, что a < 5.',explanation:'Натуральные числа меньше 5: 1, 2, 3, 4.'}},
  {id:'l31-selfcheck',kind:'model',eyebrow:'Самопроверка',title:'Читай выражение обратно как предложение',body:'После составления записи проверь её смысл словами. Например, 80 − 4x — «из 80 вычитают по 4, x раз». Такое обратное чтение быстро обнаруживает перепутанные действия.'},
  {id:'l31-summary',kind:'summary',eyebrow:'Итог урока 31',title:'Одна буква — множество вычислений',body:'Ты понимаешь переменную, превращаешь буквенное выражение в числовое подстановкой, работаешь с одной и двумя буквами, читаешь скрытое умножение, соблюдаешь скобки и переводишь текстовые ситуации в буквенные выражения.',note:'Дальше — обязательная практика из 20 заданий и собственное объяснение главной идеи урока.'},
];

function normalize(value:string){return value.trim().toLowerCase().replace(/\s+/g,'').replace(/[×*]/g,'·').replace(/,/g,'.')}
function loadSaved():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Saved|null;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return parsed}catch{/* ignore */}return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}

export function LetterExpressionsPracticePlayer(){
  const initial=useMemo(loadSaved,[]);
  const[stageIndex,setStageIndex]=useState(Math.min(initial.stageIndex,lessonThirtyOneStages.length-1));
  const[responses,setResponses]=useState<Record<string,string>>(initial.responses);
  const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);
  const[results,setResults]=useState<Record<string,boolean>>(initial.results);
  const stage=lessonThirtyOneStages[stageIndex];const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const jump=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==31||!Number.isInteger(detail.stageIndex))return;stopVoice();setStageIndex(Math.max(0,Math.min(Number(detail.stageIndex),lessonThirtyOneStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('mathnikita-go-to-stage',jump);return()=>window.removeEventListener('mathnikita-go-to-stage',jump)},[]);
  function stopVoice(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));window.speechSynthesis?.cancel()}
  function moveTo(index:number){stopVoice();setStageIndex(Math.max(0,Math.min(index,lessonThirtyOneStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})}
  function choose(value:string){if(!activity)return;setResponses(current=>({...current,[activity.id]:value}));setChecked(current=>({...current,[activity.id]:false}));setResults(current=>({...current,[activity.id]:false}))}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(current=>({...current,[activity.id]:true}));setResults(current=>({...current,[activity.id]:correct}))}
  const canAdvance=!activity||isCorrect;const percent=Math.round(((stageIndex+1)/lessonThirtyOneStages.length)*100);
  return <main className="lesson-player"><div className="lesson-progress" aria-label={`Пройдено ${percent}% урока`}><i style={{width:`${percent}%`}}/></div><section className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}>
    <div className="stage-counter"><span>Этап {stageIndex+1} из {lessonThirtyOneStages.length}</span><div><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0} aria-label="Предыдущий этап">←</button><button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={stageIndex===lessonThirtyOneStages.length-1||!canAdvance} aria-label="Следующий этап">→</button></div></div>
    <div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside>{stage.note}</aside>:null}</div>
    {activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<><div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>choose(option)} disabled={isCorrect}>{option}</button>)}</div><button type="button" className="check-button" onClick={checkAnswer} disabled={!response.trim()||isCorrect}>Проверить</button></>:<div className="inline-answer"><input value={response} onChange={event=>choose(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Введи ответ'} disabled={isCorrect}/><button type="button" className="check-button" onClick={checkAnswer} disabled={!response.trim()||isCorrect}>Проверить</button></div>}{isChecked&&!isCorrect?<div className="instant-feedback bad" data-explanation={activity.explanation}><b>Пока не так.</b><span>{activity.hint}</span></div>:null}{isCorrect?<div className="instant-feedback good"><b>Верно!</b><span>{activity.explanation}</span></div>:null}</div>:null}
    {stage.kind==='summary'?<div className="summary-card"><b>Основная часть урока 31 завершена</b><span>Теперь закрепи буквенные выражения в 20 обязательных заданиях и объясни главный принцип своими словами.</span></div>:null}
    {stage.kind!=='summary'?<div className="lesson-controls"><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={!canAdvance}>{activity&&!isCorrect?'Сначала реши задание':'Дальше →'}</button></div>:null}
  </section></main>;
}
