import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './multiplicationMeaning.css';
import './multiplicationPractice.css';

type Activity={
  id:string;
  type:'choice'|'input';
  prompt:string;
  options?:string[];
  answer:string|string[];
  explanation:string;
  hint:string;
  placeholder?:string;
};
type VisualKind='fact-grid'|'neighbor'|'power'|'place-shift'|'round-rule'|'explorer'|'estimate'|'column'|'alignment'|'operations'|'substitution'|'methods'|'final';
type Stage={
  id:string;
  title:string;
  eyebrow:string;
  kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';
  body:string;
  note?:string;
  activity?:Activity;
  visual?:VisualKind;
  sourceExercise?:string;
};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-55-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/[\s.,;:!?()[\]{}'"«»]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonFiftyFiveStages:Stage[]=[
  {id:'l55-mission',kind:'story',eyebrow:'Урок 55 · § 16 · практика',title:'Произведение без лишних действий',body:'На прошлом уроке мы раскрыли смысл умножения. Теперь превратим свойства и разрядный состав числа в надёжные вычислительные инструменты: восстановим табличные факты, освоим круглые множители и проверим письменное умножение.',note:'Маршрут: соседний факт → ×10, ×100, ×1000 → нули в круглых множителях → прикидка → письменная запись → выражения № 385–392.',visual:'fact-grid'},
  {id:'l55-facts-map',kind:'model',eyebrow:'Таблица умножения',title:'Известный факт — опора, а не догадка',body:'Таблицу не обязательно вспоминать как набор разрозненных ответов. Если известны 7·7=49 и переместительное свойство, то рядом уже находятся 7·8, 8·7 и другие связанные произведения.',note:'Сначала назови опорный факт, затем точно опиши один шаг от него.',visual:'fact-grid'},
  {id:'l55-swap-fact',kind:'practice',eyebrow:'Переместительное свойство',title:'Поворачиваем знакомый факт',body:'Из равенства 7·8=56 по свойству ab=ba сразу получаем ещё одно равенство.',activity:{id:'l55-p1',type:'choice',prompt:'Какое произведение равно 8·7?',options:['7·8','8·8','7·7','8+7'],answer:'7·8',hint:'Поменяй местами только множители.','explanation':'8·7=7·8=56.'},visual:'fact-grid'},
  {id:'l55-neighbor-model',kind:'model',eyebrow:'Соседний табличный факт',title:'Ещё одна семёрка',body:'В произведении 7·8 число 7 повторяется восемь раз, а в 7·7 — семь раз. Поэтому от 7·7 до 7·8 нужно прибавить ровно одно число 7.',note:'Получаем цепочку: 7·8=7·7+7=49+7=56.',visual:'neighbor'},
  {id:'l55-neighbor-plus',kind:'practice',eyebrow:'Опора 7·7',title:'Восстанавливаем 7·8',body:'Используй известное значение 7·7=49 и добавь ещё одну семёрку.',activity:{id:'l55-p2',type:'input',prompt:'Вычисли 7·8.',answer:'56',placeholder:'Ответ',hint:'49+7.','explanation':'7·8=7·7+7=49+7=56.'},visual:'neighbor'},
  {id:'l55-neighbor-minus',kind:'practice',eyebrow:'Опора 6·10',title:'Один раз по 6 убираем',body:'До круглого произведения 6·10=60 не хватает одного шага назад: в 6·9 девять шестёрок, а не десять.',activity:{id:'l55-p3',type:'input',prompt:'Вычисли 6·9.',answer:'54',placeholder:'Ответ',hint:'60−6.','explanation':'6·9=6·10−6=60−6=54.'},visual:'neighbor'},
  {id:'l55-fact-link',kind:'quiz',eyebrow:'Проверка рассуждения',title:'Равенство должно объяснять шаг',body:'Для восстановления 7·8 из 7·7 нужна связь между соседними произведениями.',activity:{id:'l55-p4',type:'choice',prompt:'Какое равенство объясняет вычисление?',options:['7·8=7·7+7','7·8=7·7+8','7·8=8·8+7','7·8=7+8'],answer:'7·8=7·7+7',hint:'Восьмая группа содержит ещё 7 предметов.','explanation':'К семи семёркам добавили восьмую семёрку: 7·8=7·7+7.'},visual:'neighbor'},
  {id:'l55-table-check',kind:'practice',eyebrow:'Табличная уверенность',title:'От 8·10 к 8·9',body:'Десять восьмёрок дают 80. Для девяти восьмёрок убери одну восьмёрку.',activity:{id:'l55-p5',type:'input',prompt:'Вычисли 8·9.',answer:'72',placeholder:'Ответ',hint:'80−8.','explanation':'8·9=8·10−8=80−8=72.'},visual:'fact-grid'},
  {id:'l55-powers-model',kind:'model',eyebrow:'Разрядные единицы',title:'Умножение на 10, 100 и 1000',body:'При умножении натурального числа на 10 каждая цифра переходит на один разряд влево; на 100 — на два; на 1000 — на три. В записи результата справа появляются один, два или три нуля.',note:'Это разрядный сдвиг, а не изменение самих цифр.',visual:'power'},
  {id:'l55-times-ten',kind:'practice',eyebrow:'Учебник · № 392(1)',title:'Один разрядный шаг',body:'Во втором множителе 10 один нуль, поэтому каждая цифра числа 214 переходит на один разряд влево.',sourceExercise:'392.1',activity:{id:'l55-p6',type:'input',prompt:'Вычисли 214·10.',answer:['2140','2 140'],placeholder:'Ответ',hint:'Справа появится один нуль.','explanation':'214·10=2140.'},visual:'place-shift'},
  {id:'l55-hundred-first',kind:'practice',eyebrow:'Учебник · № 392(2)',title:'Разрядный множитель можно поставить первым',body:'Запись 100·328 удобнее мысленно переставить: 328·100. Значение произведения не изменится.',sourceExercise:'392.2',activity:{id:'l55-p7',type:'input',prompt:'Вычисли 100·328.',answer:['32800','32 800'],placeholder:'Ответ',hint:'Используй 100·328=328·100.','explanation':'100·328=328·100=32800.'},visual:'power'},
  {id:'l55-place-check',kind:'quiz',eyebrow:'Смысл правила',title:'Не «нули приклеились», а разряды сдвинулись',body:'В числе 46 цифры обозначают десятки и единицы. После умножения на 100 каждая из них переходит на два разряда влево, а нули удерживают освободившиеся разряды.',activity:{id:'l55-p8',type:'choice',prompt:'Почему 46·100=4600?',options:['Каждая цифра переходит на два разряда влево','Число 46 увеличивается на 100','К числу прибавляют два нуля как отдельные слагаемые','Меняется только цифра 6'],answer:'Каждая цифра переходит на два разряда влево',hint:'Во сколько раз сотня больше единицы?','explanation':'Умножение на 100 переводит каждую разрядную единицу в разряд, который в 100 раз крупнее.'},visual:'place-shift'},
  {id:'l55-round-rule',kind:'model',eyebrow:'Круглые множители',title:'Сначала значащие части, затем все нули',body:'Чтобы умножить 140·80, сначала вычисли 14·8=112. В исходных множителях вместе два нуля, поэтому допиши к 112 два нуля: 11 200.',note:'Контроль: 140≈100 и 80≈100, значит ответ должен быть порядка десятков тысяч.',visual:'round-rule'},
  {id:'l55-round-first',kind:'practice',eyebrow:'Учебник · № 392(4)',title:'Два нуля в двух множителях',body:'У числа 140 один конечный нуль, у 80 — ещё один. Значащие части 14 и 8 дают 112.',sourceExercise:'392.4',activity:{id:'l55-p9',type:'input',prompt:'Вычисли 140·80.',answer:['11200','11 200'],placeholder:'Ответ',hint:'14·8=112 и всего два конечных нуля.','explanation':'140·80=11200.'},visual:'round-rule'},
  {id:'l55-zero-lab',kind:'guided',eyebrow:'Интерактивная лаборатория',title:'Управляй разрядным масштабом',body:'Ползунками меняй число конечных нулей у множителей 14 и 8. Значащие части остаются прежними, а каждый добавленный нуль увеличивает произведение в 10 раз.',note:'Следи одновременно за множителями, общим числом нулей и произведением.',visual:'explorer'},
  {id:'l55-zero-lab-check',kind:'practice',eyebrow:'Лаборатория · перенос правила',title:'Один нуль и два нуля',body:'У числа 230 один конечный нуль, у 400 — два. Значащие части дают 23·4=92.',activity:{id:'l55-p10',type:'input',prompt:'Вычисли 230·400.',answer:['92000','92 000'],placeholder:'Ответ',hint:'К 92 допиши три нуля.','explanation':'230·400=92000.'},visual:'explorer'},
  {id:'l55-round-second',kind:'practice',eyebrow:'Учебник · № 392(5)',title:'Нули не заменяют табличный факт',body:'Сначала вычисли 58·24, только затем верни два конечных нуля исходных множителей.',sourceExercise:'392.5',activity:{id:'l55-p11',type:'input',prompt:'Вычисли 580·240.',answer:['139200','139 200'],placeholder:'Ответ',hint:'58·24=1392; в исходных множителях два конечных нуля.','explanation':'580·240=139200.'},visual:'round-rule'},
  {id:'l55-round-third',kind:'practice',eyebrow:'Учебник · № 392(6)',title:'Четыре конечных нуля',body:'У 270 один конечный нуль, у 3000 — три. Значащие части 27 и 3 дают 81.',sourceExercise:'392.6',activity:{id:'l55-p12',type:'input',prompt:'Вычисли 270·3000.',answer:['810000','810 000'],placeholder:'Ответ',hint:'К 81 допиши 1+3=4 нуля.','explanation':'270·3000=810000.'},visual:'round-rule'},
  {id:'l55-zero-error',kind:'quiz',eyebrow:'Диагностика ошибки',title:'Сколько нулей возвращать?',body:'Ученик вычислил 46·18=828, но для 460·1800 записал 82 800 и потерял один разрядный множитель.',activity:{id:'l55-p13',type:'choice',prompt:'Как исправить правило?',options:['После 46·18 дописать три нуля','После 46·18 дописать два нуля','После 46·18 дописать четыре нуля','Убрать нули совсем'],answer:'После 46·18 дописать три нуля',hint:'Один конечный нуль у 460 и два у 1800.','explanation':'Всего три конечных нуля: 460·1800=828000.'},visual:'round-rule'},
  {id:'l55-estimate-model',kind:'model',eyebrow:'Прикидка',title:'Порядок величины ловит потерянный нуль',body:'Для 580·240 можно оценить 600·200=120 000. Значит ответ 13 920 слишком мал, а 1 392 000 слишком велик; точное 139 200 согласуется с прикидкой.',note:'Прикидка не заменяет точный расчёт, но проверяет его масштаб.',visual:'estimate'},
  {id:'l55-estimate-check',kind:'practice',eyebrow:'Контроль масштаба',title:'Коридор для произведения',body:'Числа 580 и 240 близки к 600 и 200, поэтому произведение находится около 120 000.',activity:{id:'l55-p14',type:'choice',prompt:'В каком диапазоне должно лежать 580·240?',options:['От 100 000 до 200 000','От 10 000 до 20 000','От 1 000 до 2 000','Больше 1 000 000'],answer:'От 100 000 до 200 000',hint:'Оцени 600·200.','explanation':'600·200=120000, а точное произведение 139200 лежит в выбранном диапазоне.'},visual:'estimate'},
  {id:'l55-column-model',kind:'model',eyebrow:'Учебник · № 385(1)',title:'Письменное умножение хранит разряды',body:'Для 516·32 сначала находят 516·2=1032, затем 516·30=15 480. Второе неполное произведение начинается в разряде десятков, после чего результаты складывают.',sourceExercise:'385.1',note:'В следующем уроке разберём письменный алгоритм ещё глубже; сейчас читаем и проверяем готовую разрядную запись.',visual:'column'},
  {id:'l55-first-partial',kind:'practice',eyebrow:'Письменная запись · первый шаг',title:'Умножаем на единицы',body:'Цифра 2 в множителе 32 обозначает две единицы, поэтому первое неполное произведение равно 516·2.',sourceExercise:'385.1',activity:{id:'l55-p15',type:'input',prompt:'Вычисли 516·2.',answer:['1032','1 032'],placeholder:'Ответ',hint:'Умножай справа налево и учитывай перенос.','explanation':'516·2=1032.'},visual:'column'},
  {id:'l55-column-total',kind:'practice',eyebrow:'Учебник · № 385(1)',title:'Складываем неполные произведения',body:'Первое неполное произведение 1032, второе 15 480. Их сумма даёт значение 516·32.',sourceExercise:'385.1',activity:{id:'l55-p16',type:'input',prompt:'Вычисли 516·32.',answer:['16512','16 512'],placeholder:'Ответ',hint:'1032+15480.','explanation':'516·32=16512.'},visual:'column'},
  {id:'l55-alignment-check',kind:'quiz',eyebrow:'Разрядная точность',title:'Почему вторая строка сдвинута?',body:'При умножении на цифру 3 числа 32 фактически умножают на 30, то есть на три десятка.',activity:{id:'l55-p17',type:'choice',prompt:'Как правильно объяснить сдвиг второго неполного произведения?',options:['Оно соответствует умножению на 30','Оно всегда должно быть длиннее первого','Так удобнее рисовать столбик','Сдвиг заменяет сложение'],answer:'Оно соответствует умножению на 30',hint:'Какой разряд занимает цифра 3 в числе 32?','explanation':'Цифра 3 означает три десятка, поэтому 516·30 записывают со сдвигом на один разряд.'},visual:'alignment'},
  {id:'l55-operations-model',kind:'model',eyebrow:'Выражения',title:'Умножение раньше сложения и вычитания',body:'В выражении без скобок сначала выполняют умножение. Так 704·69+1424 превращается в 48 576+1424 и только потом — в 50 000.',visual:'operations'},
  {id:'l55-ex387',kind:'practice',eyebrow:'Учебник · № 387(1)',title:'Произведение, затем сумма',body:'Сначала вычисли 704·69=48 576, затем прибавь 1424.',sourceExercise:'387.1',activity:{id:'l55-p18',type:'input',prompt:'Вычисли 704·69+1424.',answer:['50000','50 000'],placeholder:'Ответ',hint:'48576+1424.','explanation':'704·69+1424=48576+1424=50000.'},visual:'operations'},
  {id:'l55-parentheses',kind:'practice',eyebrow:'Учебник · № 388(4)',title:'Скобки меняют первый шаг',body:'В выражении 64·(96−77) сначала нужно найти разность в скобках.',sourceExercise:'388.4',activity:{id:'l55-p19',type:'input',prompt:'Вычисли 64·(96−77).',answer:['1216','1 216'],placeholder:'Ответ',hint:'96−77=19, затем 64·19.','explanation':'64·(96−77)=64·19=1216.'},visual:'operations'},
  {id:'l55-substitution-model',kind:'model',eyebrow:'Буквенное выражение',title:'Подстановка не отменяет порядок действий',body:'В выражении 17x+432 при x=58 сначала заменяем букву числом: 17·58+432. Затем выполняем умножение и только после него сложение.',note:'Подстановка — это точная замена, а не отдельное арифметическое действие.',visual:'substitution'},
  {id:'l55-ex389',kind:'practice',eyebrow:'Учебник · № 389(1)',title:'Подставляем x=58',body:'После подстановки получаем 17·58+432. Произведение 17·58 равно 986.',sourceExercise:'389.1',activity:{id:'l55-p20',type:'input',prompt:'Найди значение 17x+432 при x=58.',answer:['1418','1 418'],placeholder:'Ответ',hint:'986+432.','explanation':'17·58+432=986+432=1418.'},visual:'substitution'},
  {id:'l55-ex390',kind:'guided',eyebrow:'Учебник · № 390(1)',title:'Вычитание после умножения',body:'При x=36 выражение 976−24x превращается в 976−24·36. Сначала 24·36=864, затем 976−864=112.',sourceExercise:'390.1',note:'Частая ошибка — сначала вычесть 24 из 976. Порядок действий этого не разрешает.',visual:'substitution'},
  {id:'l55-methods',kind:'guided',eyebrow:'Выбираем способ',title:'Один пример — несколько проверок',body:'Произведение 460·1800 удобно считать по значащим частям и нулям: 46·18=828, затем три нуля. Результат 828 000 можно проверить прикидкой 500·2000≈1 000 000.',note:'Надёжный вычислитель умеет получить ответ одним способом и независимо проверить другим.',visual:'methods'},
  {id:'l55-ex391',kind:'guided',eyebrow:'Учебник · № 391',title:'Шесть произведений круглых чисел',body:'В № 391 встречаются 693·100, 974·1000, 540·20, 120·400, 760·350 и 460·1800. Во всех примерах отделяй значащие части, считай произведение и возвращай общее число конечных нулей.',sourceExercise:'391',note:'Особенно внимательно проверь 760·350=266 000 и 460·1800=828 000.',visual:'round-rule'},
  {id:'l55-ex392',kind:'challenge',eyebrow:'Учебник · № 392',title:'Разрядный тренажёр § 16',body:'Набор № 392 начинается с умножения на 10, 100 и 10 000, затем соединяет круглые множители. Это один и тот же разрядный принцип, а не шесть несвязанных приёмов.',sourceExercise:'392',note:'214·10=2140; 100·328=32800; 10000·546=5460000; 140·80=11200; 580·240=139200; 270·3000=810000.',visual:'power'},
  {id:'l55-mastery-gate',kind:'quiz',eyebrow:'Mastery gate',title:'Всё вместе: круглые числа и порядок действий',body:'Вычисли разность 460·1800−693·100. Сначала найди оба произведения, затем выполни вычитание.',activity:{id:'l55-p21',type:'input',prompt:'Чему равно выражение?',answer:['758700','758 700'],placeholder:'Ответ',hint:'828000−69300.','explanation':'460·1800−693·100=828000−69300=758700.'},visual:'methods'},
  {id:'l55-summary',kind:'summary',eyebrow:'Итог урока',title:'Круглые множители под контролем',body:'Ты восстанавливаешь табличный факт через соседний, объясняешь разрядный сдвиг при умножении на 10, 100 и 1000, считаешь произведения круглых чисел, проверяешь масштаб прикидкой, читаешь письменное умножение и соблюдаешь порядок действий.',note:'Дальше — обязательная тренировка: 20 задач и 50 ответов с мгновенной проверкой и помощью Пифагора.',visual:'final'}
];

function RoundNumberExplorer(){
  const[zerosA,setZerosA]=useState(1);const[zerosB,setZerosB]=useState(1);const coreA=14;const coreB=8;const factorA=coreA*10**zerosA;const factorB=coreB*10**zerosB;const product=factorA*factorB;
  return <div className="multiplication-round-explorer" data-round-lab="interactive" data-core-a={coreA} data-core-b={coreB} data-zeros-a={zerosA} data-zeros-b={zerosB} data-total-zeros={zerosA+zerosB} data-product={product}>
    <div className="multiplication-round-controls">
      <label><span>Нули первого множителя: <b>{zerosA}</b></span><input aria-label="Нули первого множителя" type="range" min="0" max="3" value={zerosA} onChange={event=>setZerosA(Number(event.target.value))}/></label>
      <label><span>Нули второго множителя: <b>{zerosB}</b></span><input aria-label="Нули второго множителя" type="range" min="0" max="3" value={zerosB} onChange={event=>setZerosB(Number(event.target.value))}/></label>
    </div>
    <div className="multiplication-round-equation"><b>{factorA.toLocaleString('ru-RU')} · {factorB.toLocaleString('ru-RU')}</b><span>=</span><strong>{product.toLocaleString('ru-RU')}</strong></div>
    <div className="multiplication-round-proof"><span>14·8 = 112</span><span>конечных нулей: {zerosA}+{zerosB}={zerosA+zerosB}</span></div>
  </div>;
}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='explorer')return <RoundNumberExplorer/>;
  if(kind==='fact-grid')return <div className="multiplication-practice-visual" data-visual="fact-grid"><div className="multiplication-fact-grid"><span><b>7·7</b><strong>49</strong></span><span><b>7·8</b><strong>56</strong></span><span><b>8·7</b><strong>56</strong></span><span><b>8·8</b><strong>64</strong></span></div></div>;
  if(kind==='neighbor')return <div className="multiplication-practice-visual" data-visual="neighbor-fact"><div className="multiplication-neighbor"><b>7·7</b><span>= 49</span><i>+ 7</i><b>7·8</b><span>= 56</span></div></div>;
  if(kind==='power')return <div className="multiplication-practice-visual" data-visual="powers-of-ten"><div className="multiplication-powers"><span><b>214·10</b><strong>2 140</strong></span><span><b>328·100</b><strong>32 800</strong></span><span><b>546·10 000</b><strong>5 460 000</strong></span></div></div>;
  if(kind==='place-shift')return <div className="multiplication-practice-visual" data-visual="place-shift"><div className="multiplication-shift"><span><small>до</small><b>328</b></span><i>×100 →</i><span><small>после</small><b>32 800</b></span></div><p>единицы → сотни · десятки → тысячи · сотни → десятки тысяч</p></div>;
  if(kind==='round-rule')return <div className="multiplication-practice-visual" data-visual="round-rule"><div className="multiplication-round-steps"><span><small>1 · значащие части</small><b>14·8</b></span><span><small>2 · произведение</small><b>112</b></span><span><small>3 · два нуля</small><strong>11 200</strong></span></div></div>;
  if(kind==='estimate')return <div className="multiplication-practice-visual" data-visual="estimate"><div className="multiplication-estimate"><b>580·240</b><span>≈</span><b>600·200</b><span>=</span><strong>120 000</strong></div><small>точный ответ 139 200 имеет верный порядок величины</small></div>;
  if(kind==='column')return <div className="multiplication-practice-visual" data-visual="column-multiplication"><div className="multiplication-column" aria-label="Письменное умножение 516 на 32"><span>×</span><b>516</b><b>32</b><i/><strong>1 032</strong><strong>15 480</strong><i/><em>16 512</em></div><div className="multiplication-column-notes"><span>516·2</span><span>516·30</span><b>сумма</b></div></div>;
  if(kind==='alignment')return <div className="multiplication-practice-visual" data-visual="partial-product-alignment"><div className="multiplication-alignment"><span><b>1 032</b><small>единицы</small></span><span><b>15 480</b><small>десятки: сдвиг на 1 разряд</small></span></div></div>;
  if(kind==='operations')return <div className="multiplication-practice-visual" data-visual="operation-order"><div className="multiplication-practice-operation"><b><mark>704·69</mark>+1424</b><span>→</span><b>48 576+1424</b><span>→</span><strong>50 000</strong></div></div>;
  if(kind==='substitution')return <div className="multiplication-practice-visual" data-visual="substitution"><div className="multiplication-substitution"><b>17x+432</b><span>x=58</span><b>17·58+432</b><strong>1 418</strong></div></div>;
  if(kind==='methods')return <div className="multiplication-practice-visual" data-visual="method-check"><div className="multiplication-methods"><span><small>точно</small><b>46·18=828</b><strong>828 000</strong></span><span><small>прикидка</small><b>500·2000</b><strong>≈1 000 000</strong></span></div></div>;
  return <div className="multiplication-practice-visual" data-visual="final"><div className="multiplication-practice-final"><b>соседний факт ✓</b><b>разрядный сдвиг ✓</b><b>круглые множители ✓</b><b>прикидка ✓</b><b>столбик ✓</b><b>порядок действий ✓</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyFiveStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function MultiplicationPracticePlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyFiveStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyFiveStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==55||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyFiveStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyFiveStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player multiplication-practice-player" data-lesson-number="55" data-source-reference="Мерзляк § 16 · с. 106–113 · № 385–392" data-source-exercise-range="385-392"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFiftyFiveStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyFiveStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyFiveStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
