import { useEffect, useMemo, useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './naturalRowPractice.css';

type Activity=
|{id:string;type:'choice';prompt:string;options:string[];answer:string;explanation:string}
|{id:string;type:'input';prompt:string;answer:string;explanation:string;placeholder?:string}
|{id:string;type:'order';prompt:string;items:string[];answer:string[];explanation:string};

type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type SavedProgress={version:2;stageIndex:number;answer:string;ordered:string[];checked:boolean;correct:boolean;results:Record<string,boolean>;completedAt?:string};

const STORAGE_KEY='mathnikita-lesson-2-progress-v2';
export const lessonTwoStages:Stage[]=[
{id:'l2-story',kind:'story',eyebrow:'Проблемная ситуация',title:'Сколько домов стоит между домами № 27 и № 35?',body:'Можно выписать номера 28, 29, 30, 31, 32, 33, 34 и пересчитать. Но что делать, если номера отличаются не на 8, а на сто тысяч?',note:'Сегодня выведем правило, которое работает для любых натуральных чисел и не требует выписывать весь ряд.',sourceTag:'Мерзляк § 1; методическое пособие, упражнения № 8–9'},
{id:'l2-step-one',kind:'guided',eyebrow:'Вспоминаем основу',title:'У натурального ряда всегда шаг 1',body:'Каждое следующее число натурального ряда на единицу больше предыдущего.',activity:{id:'l2-a1',type:'choice',prompt:'Какая запись является фрагментом натурального ряда?',options:['17, 18, 19, 20','17, 19, 21, 23','20, 19, 18, 17','1, 2, 4, 8'],answer:'17, 18, 19, 20',explanation:'В натуральном ряду числа идут по возрастанию с постоянным шагом 1.'}},
{id:'l2-between-model',kind:'model',eyebrow:'Считаем промежуток',title:'Между 7 и 12 находятся четыре числа',body:'Разность границ 12 − 7 = 5 показывает количество шагов. Промежуточных чисел на одно меньше: 5 − 1 = 4.',note:'Между числами n и n + k находится k − 1 натуральное число.',sourceTag:'Методическое пособие Мерзляка'},
{id:'l2-between-guided',kind:'guided',eyebrow:'Решаем вместе',title:'Границы не входят в ответ',body:'Когда спрашивают числа между 20 и 26, сами числа 20 и 26 не считаются.',activity:{id:'l2-a2',type:'choice',prompt:'Сколько натуральных чисел находится между 20 и 26?',options:['4','5','6','7'],answer:'5',explanation:'Это 21, 22, 23, 24, 25. Или: 26 − 20 − 1 = 5.'}},
{id:'l2-between-input',kind:'practice',eyebrow:'Самостоятельно',title:'Не выписывай числа без необходимости',body:'Для большого промежутка найди разность границ, затем вычти 1.',activity:{id:'l2-p1',type:'input',prompt:'Сколько натуральных чисел находится между 300 и 310?',answer:'9',placeholder:'Введи количество',explanation:'310 − 300 − 1 = 9.'}},
{id:'l2-inclusive',kind:'guided',eyebrow:'Точная формулировка',title:'«Между» и «от… до… включительно» — разные задачи',body:'Если обе границы включаются, к промежуточным числам добавляются левая и правая границы.',activity:{id:'l2-a3',type:'choice',prompt:'Сколько натуральных чисел от 300 до 310 включительно?',options:['9','10','11','12'],answer:'11',explanation:'310 − 300 + 1 = 11.'}},
{id:'l2-successor-crossing',kind:'guided',eyebrow:'Переходим через разряд',title:'Следующее число может изменить сразу несколько цифр',body:'После 99 идёт 100, после 999 — 1000. Правило не меняется: прибавляем 1.',activity:{id:'l2-a4',type:'input',prompt:'Какое число следует за 99 999?',answer:'100000',placeholder:'Введи число',explanation:'99 999 + 1 = 100 000.'}},
{id:'l2-predecessor-crossing',kind:'practice',eyebrow:'Движемся назад',title:'Предыдущее число на единицу меньше',body:'Для любого натурального числа, кроме 1, предыдущее получается вычитанием единицы.',activity:{id:'l2-p2',type:'input',prompt:'Какое натуральное число стоит перед 100 000?',answer:'99999',placeholder:'Введи число',explanation:'100 000 − 1 = 99 999.'}},
{id:'l2-sequence-model',kind:'model',eyebrow:'Числовые закономерности',title:'Последовательность может иметь другой шаг',body:'5, 8, 11, 14 — отдельная последовательность с шагом 3.',note:'Сначала сравни соседние члены и найди разность.'},
{id:'l2-sequence-up',kind:'guided',eyebrow:'Находим шаг',title:'Возрастающая последовательность',body:'Разность соседних членов равна 3.',activity:{id:'l2-a5',type:'input',prompt:'Какое число будет следующим: 5, 8, 11, 14, …?',answer:'17',explanation:'14 + 3 = 17.'}},
{id:'l2-sequence-down',kind:'practice',eyebrow:'Шаг может быть отрицательным',title:'Убывающая последовательность',body:'Если каждое следующее число меньше на одно и то же число, шаг отрицательный.',activity:{id:'l2-p3',type:'input',prompt:'Продолжи: 40, 35, 30, 25, …',answer:'20',explanation:'Каждый раз вычитают 5.'}},
{id:'l2-missing',kind:'practice',eyebrow:'Восстанавливаем пропуск',title:'Проверь правило с обеих сторон',body:'Пропущенное число должно подходить и к предыдущему, и к следующему члену.',activity:{id:'l2-p4',type:'input',prompt:'Найди пропуск: 4, 9, __, 19',answer:'14',explanation:'Шаг равен 5: 4, 9, 14, 19.'}},
{id:'l2-natural-vs-sequence',kind:'guided',eyebrow:'Различаем объекты',title:'Не всякая закономерность — натуральный ряд',body:'Натуральный ряд содержит все натуральные числа подряд. Последовательность может начинаться с любого числа и иметь другой шаг.',activity:{id:'l2-a6',type:'choice',prompt:'Какая запись может быть фрагментом натурального ряда?',options:['37, 38, 39, 40','37, 39, 41, 43','40, 39, 38, 37','1, 3, 9, 27'],answer:'37, 38, 39, 40',explanation:'Здесь перечислены соседние натуральные числа по возрастанию.'}},
{id:'l2-counterexample',kind:'practice',eyebrow:'Проверяем утверждение',title:'Одного контрпримера достаточно',body:'Чтобы опровергнуть утверждение, достаточно одного подходящего случая.',activity:{id:'l2-p5',type:'choice',prompt:'Какая последовательность опровергает утверждение «любая возрастающая последовательность является натуральным рядом»?',options:['1, 2, 3, 4','8, 9, 10, 11','2, 4, 6, 8','101, 102, 103, 104'],answer:'2, 4, 6, 8',explanation:'Последовательность возрастает, но пропускает нечётные числа.'}},
{id:'l2-order',kind:'practice',eyebrow:'Восстанавливаем участок ряда',title:'Верни числа на свои места',body:'В натуральном ряду каждое следующее число на 1 больше предыдущего.',activity:{id:'l2-p6',type:'order',prompt:'Расположи числа как в натуральном ряду',items:['22','18','20','19','21'],answer:['18','19','20','21','22'],explanation:'18, 19, 20, 21, 22.'}},
{id:'l2-general-rule',kind:'model',eyebrow:'Обобщаем',title:'От конкретного примера — к формуле',body:'От n до n + k нужно сделать k шагов. Промежуточных точек на одну меньше — k − 1.',note:'Между n и n + k находится k − 1 натуральное число.',sourceTag:'Методическое пособие Мерзляка',activity:{id:'l2-a7',type:'choice',prompt:'Сколько натуральных чисел находится между n и n + 7?',options:['5','6','7','8'],answer:'6',explanation:'7 − 1 = 6.'}},
{id:'l2-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Следующее число',body:'Ответь без подсказки.',activity:{id:'l2-q1',type:'input',prompt:'Какое число следует за 399?',answer:'400',explanation:'399 + 1 = 400.'}},
{id:'l2-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Числа между границами',body:'Границы в ответ не входят.',activity:{id:'l2-q2',type:'input',prompt:'Сколько натуральных чисел находится между 100 и 105?',answer:'4',explanation:'101, 102, 103, 104.'}},
{id:'l2-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Шаг последовательности',body:'Сначала найди разность соседних членов.',activity:{id:'l2-q3',type:'choice',prompt:'В какой последовательности постоянный шаг равен 5?',options:['12, 17, 22, 27','12, 16, 20, 24','5, 10, 20, 40','30, 25, 19, 12'],answer:'12, 17, 22, 27',explanation:'Каждый следующий член на 5 больше.'}},
{id:'l2-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Предыдущее число',body:'Ответь без подсказки.',activity:{id:'l2-q4',type:'input',prompt:'Какое число предшествует 1000?',answer:'999',explanation:'1000 − 1 = 999.'}},
{id:'l2-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Продолжение последовательности',body:'Ответь без подсказки.',activity:{id:'l2-q5',type:'input',prompt:'Продолжи: 90, 80, 70, …',answer:'60',explanation:'Шаг равен −10.'}},
{id:'l2-challenge',kind:'challenge',eyebrow:'Исследовательская задача',title:'Большой промежуток без перебора',body:'Между 1 000 000 и 1 000 100 числа выписывать не нужно.',note:'Найди количество шагов, затем вычти 1.',activity:{id:'l2-c1',type:'input',prompt:'Сколько натуральных чисел находится между 1 000 000 и 1 000 100?',answer:'99',explanation:'1 000 100 − 1 000 000 − 1 = 99.'}},
{id:'l2-summary',kind:'summary',eyebrow:'Итог',title:'Урок завершён',body:'Ты умеешь считать числа между границами, объяснять правило k − 1, находить шаг последовательности и отличать последовательность от натурального ряда.'}
];

const emptyProgress:SavedProgress={version:2,stageIndex:0,answer:'',ordered:[],checked:false,correct:false,results:{}};
function normalize(value:string){return value.trim().toLowerCase().replace(/\s+/g,'').replace(/,/g,'.')}
function loadProgress():SavedProgress{try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)??'null') as Partial<SavedProgress>|null;if(!parsed||parsed.version!==2)return emptyProgress;return{...emptyProgress,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonTwoStages.length-1),ordered:Array.isArray(parsed.ordered)?parsed.ordered:[],results:parsed.results??{}}}catch{return emptyProgress}}

export function NaturalRowPracticePlayer(){
const saved=useMemo(loadProgress,[]);
const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[answer,setAnswer]=useState(saved.answer);const[ordered,setOrdered]=useState<string[]>(saved.ordered);const[checked,setChecked]=useState(saved.checked);const[correct,setCorrect]=useState(saved.correct);const[results,setResults]=useState<Record<string,boolean>>(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);const[restored,setRestored]=useState(saved.stageIndex>0||Object.keys(saved.results).length>0);
const stage=lessonTwoStages[stageIndex];const activity=stage.activity;const progress=Math.round(((stageIndex+1)/lessonTwoStages.length)*100);const quizIds=['l2-q1','l2-q2','l2-q3','l2-q4','l2-q5'];const practiceIds=['l2-p1','l2-p2','l2-p3','l2-p4','l2-p5','l2-p6'];const quizScore=quizIds.filter(id=>results[id]).length;const practiceScore=practiceIds.filter(id=>results[id]).length;
useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:2,stageIndex,answer,ordered,checked,correct,results,completedAt} satisfies SavedProgress))},[stageIndex,answer,ordered,checked,correct,results,completedAt]);
useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{lessonNumber:number;stageIndex:number}>).detail;if(detail?.lessonNumber===2)goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function resetStage(){setAnswer('');setOrdered([]);setChecked(false);setCorrect(false)}
function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonTwoStages.length-1));resetStage();window.scrollTo({top:0,behavior:'smooth'})}
function go(delta:number){goTo(stageIndex+delta)}
function resetLesson(){localStorage.removeItem(STORAGE_KEY);setStageIndex(0);setAnswer('');setOrdered([]);setChecked(false);setCorrect(false);setResults({});setCompletedAt(undefined);setRestored(false);window.scrollTo({top:0,behavior:'smooth'})}
function submit(value?:string){if(!activity)return;const isCorrect=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):normalize(value??answer)===normalize(activity.answer);setCorrect(isCorrect);setChecked(true);setResults(previous=>({...previous,[activity.id]:isCorrect}))}
const visualModel=useMemo(()=>{if(stage.id==='l2-story')return <div className="house-number-model">{[27,28,29,30,31,32,33,34,35].map(number=><div key={number} className={number===27||number===35?'boundary':''}><span>⌂</span><b>{number}</b></div>)}</div>;if(['l2-between-model','l2-between-guided','l2-between-input','l2-inclusive'].includes(stage.id))return <div className="interval-number-model"><b className="boundary">7</b>{[8,9,10,11].map(number=><span key={number}>{number}</span>)}<b className="boundary">12</b><small>4 числа между границами</small></div>;if(['l2-successor-crossing','l2-predecessor-crossing'].includes(stage.id))return <div className="crossing-model"><span>99 998</span><i>→</i><span>99 999</span><i>→</i><b>100 000</b></div>;if(['l2-sequence-model','l2-sequence-up'].includes(stage.id))return <div className="step-sequence-model"><span>5</span><i>+3</i><span>8</span><i>+3</i><span>11</span><i>+3</i><span>14</span></div>;if(stage.id==='l2-sequence-down')return <div className="step-sequence-model"><span>40</span><i>−5</i><span>35</span><i>−5</i><span>30</span><i>−5</i><span>25</span></div>;if(stage.id==='l2-missing')return <div className="step-sequence-model"><span>4</span><i>+5</i><span>9</span><i>+5</i><b>?</b><i>+5</i><span>19</span></div>;if(['l2-natural-vs-sequence','l2-counterexample'].includes(stage.id))return <div className="row-contrast-model"><div><small>Натуральный ряд</small><b>1, 2, 3, 4, 5, …</b></div><strong>≠</strong><div><small>Последовательность</small><b>2, 4, 6, 8, …</b></div></div>;if(stage.id==='l2-general-rule')return <div className="gap-formula-model"><b>n</b><span>k шагов</span><b>n + k</b><strong>между ними: k − 1</strong></div>;if(stage.id==='l2-challenge')return <div className="large-gap-model"><b>1 000 000</b><span>100 шагов</span><b>1 000 100</b><strong>99 чисел между</strong></div>;return null},[stage.id]);
function renderActivity(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>{setAnswer(option);setChecked(false)}}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={()=>submit()}>Проверить</button></div>;if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>{setAnswer(event.target.value);setChecked(false)}} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={()=>submit()}>Проверить</button></div></div>;return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{current.items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>{setOrdered(list=>[...list,item]);setChecked(false)}}>{item}</button>)}</div><div className="order-result">{ordered.length?ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>{setOrdered(list=>list.filter((_,i)=>i!==index));setChecked(false)}}>{item}</button>):<span>Нажимай числа по порядку</span>}</div><div className="activity-actions"><button className="secondary" onClick={()=>setOrdered([])}>Сбросить</button><button className="check-button" disabled={ordered.length!==current.items.length} onClick={()=>submit()}>Проверить</button></div></div>}
return <main className="lesson-player-page natural-row-practice-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 2 из 175 · Натуральный ряд</span><h1>Натуральный ряд и закономерности</h1><p>Промежутки натурального ряда, правило k − 1 и числовые закономерности.</p></div><div className="lesson-duration">30–35 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonTwoStages.length}</span><div>{restored?<small>Прогресс восстановлен</small>:null}<button type="button" onClick={resetLesson}>Начать заново</button></div></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{visualModel}{activity&&renderActivity(activity)}{checked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь правило ещё раз. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&checked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<><div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно короткое повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>заданий выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div><details className="lesson-sources"><summary>Методическая основа урока</summary><div><b>Мерзляк, § 1</b><span>Ряд натуральных чисел</span><small>Свойства натурального ряда.</small></div><div><b>Методическое пособие</b><span>Урок № 2</span><small>Правило k − 1.</small></div><div><b>Дорофеев–Петерсон</b><span>Контрпримеры</span><small>Различение ряда и последовательностей.</small></div></details></>:null}</article><footer className="lesson-controls"><button onClick={()=>go(-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>go(1)} disabled={stageIndex===lessonTwoStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
