import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';
import './angleMeasurement.css';
import './protractorPractice.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='right-overlap'|'straight-overlap'|'formula'|'truth'|'clock'|'check'|'error';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-42-progress-v1';
const normalize=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/\s+/g,'').replace(/[°º]/g,'').replace(/Ё/g,'Е');

export const lessonFortyTwoStages:Stage[]=[
  {id:'l42-mission',kind:'story',eyebrow:'Урок 42 · § 12 · закрепление',title:'Когда известные углы перекрываются',body:'На прошлом уроке мы искали неизвестную часть внутри одного целого. Теперь ситуация сложнее: два известных угла могут иметь общую внутреннюю часть. Наша задача — увидеть перекрытие, записать его арифметически и проверить ответ по всему чертежу.',note:'Стратегия: обозначь три соседние части → вырази два известных составных угла → используй 90° или 180° → найди общую часть → восстанови все части.',diagram:'right-overlap'},
  {id:'l42-bridge',kind:'model',eyebrow:'Гипотеза перед вычислением',title:'Сначала назови, что именно неизвестно',body:'Если внутри прямого угла стоят два внутренних луча, удобно мысленно получить три соседние части: левую, общую и правую. Два данных угла захватывают общую часть дважды. Именно это двойное включение и позволяет её найти.',diagram:'formula'},
  {id:'l42-right-model',kind:'model',eyebrow:'Прямой угол · 90°',title:'Формула общей части',body:'Пусть два перекрывающихся составных угла внутри прямого угла равны α и β. Если их объединение заполняет весь прямой угол, то α + β считает общую часть два раза. Поэтому общая часть = α + β − 90°.',note:'Это не формула для любого рисунка. Сначала нужно убедиться, что объединение двух известных углов действительно даёт весь прямой угол.',diagram:'right-overlap'},
  {id:'l42-practice1',kind:'practice',eyebrow:'Учебник № 308',title:'74°, 62° и прямой угол',body:'Из вершины прямого угла BOM проведены лучи OA и OC. ∠BOC = 74°, ∠AOM = 62°. Найди общую часть ∠AOC.',activity:{id:'l42-p1',type:'input',prompt:'Чему равен ∠AOC?',answer:'46',placeholder:'Градусы',hint:'Сложи два известных составных угла и вычти весь прямой угол: 74 + 62 − 90.',explanation:'∠AOC = 74° + 62° − 90° = 46°. Проверка: слева 90° − 62° = 28°, справа 90° − 74° = 16°, и 28° + 46° + 16° = 90°.'},diagram:'right-overlap'},
  {id:'l42-proof-model',kind:'guided',eyebrow:'Проверка решения',title:'Восстанови весь чертёж',body:'После ответа 46° можно найти крайние части: от B до A — 74° − 46° = 28°, от C до M — 62° − 46° = 16°. Все три соседние части дают 28° + 46° + 16° = 90°. Это полноценная проверка, а не просто повтор вычисления.',diagram:'check'},
  {id:'l42-practice2',kind:'practice',eyebrow:'Практика · прямой угол',title:'Другое перекрытие',body:'Два составных угла внутри прямого угла равны 68° и 57°. Их объединение — весь прямой угол.',activity:{id:'l42-p2',type:'input',prompt:'Найди их общую часть.',answer:'35',placeholder:'Градусы',hint:'68 + 57 − 90.',explanation:'68° + 57° − 90° = 35°. Общая часть положительна и меньше каждого из данных углов.'},diagram:'right-overlap'},
  {id:'l42-straight-model',kind:'model',eyebrow:'Развёрнутый угол · 180°',title:'Тот же принцип работает на прямой',body:'Если два составных угла перекрываются внутри развёрнутого угла и вместе заполняют все 180°, их общая часть равна сумме двух данных углов минус 180°.',note:'Для развёрнутого угла меняется только известное целое: вместо 90° используем 180°.',diagram:'straight-overlap'},
  {id:'l42-practice3',kind:'practice',eyebrow:'Учебник № 309 · усиление',title:'158°, 134° и развёрнутый угол',body:'Внутри развёрнутого угла два составных угла равны 158° и 134°. Найди их общую часть.',activity:{id:'l42-p3',type:'input',prompt:'Чему равна общая часть?',answer:'112',placeholder:'Градусы',hint:'158 + 134 − 180.',explanation:'158° + 134° − 180° = 112°. Это тупой угол; результат меньше обоих исходных составных углов.'},diagram:'straight-overlap'},
  {id:'l42-formula-model',kind:'model',eyebrow:'Обобщение',title:'Почему мы вычитаем целое',body:'Сумма двух перекрывающихся углов содержит весь объединённый угол один раз и общую часть ещё один раз. Поэтому, когда объединение равно известному целому T, общая часть x = α + β − T. Для наших задач T равно 90° или 180°.',diagram:'formula'},
  {id:'l42-practice4',kind:'practice',eyebrow:'Практика · развёрнутый угол',title:'147° и 129°',body:'Два перекрывающихся угла вместе заполняют развёрнутый угол.',activity:{id:'l42-p4',type:'input',prompt:'Если их меры 147° и 129°, чему равна общая часть?',answer:'96',placeholder:'Градусы',hint:'147 + 129 − 180.',explanation:'147° + 129° − 180° = 96°. Проверка диапазона: 96° меньше 129° и 147°.'},diagram:'straight-overlap'},
  {id:'l42-truth-model',kind:'model',eyebrow:'Учебник № 310',title:'Истинность нельзя определять «на глаз»',body:'Общее утверждение должно быть верно для всех допустимых углов. Чтобы опровергнуть его, достаточно одного контрпримера. Чтобы подтвердить — нужно опереться на точные диапазоны: острый < 90°, прямой = 90°, тупой между 90° и 180°, развёрнутый = 180°.',diagram:'truth'},
  {id:'l42-practice5',kind:'practice',eyebrow:'№ 310 · утверждение 1',title:'Меньше тупого — обязательно острый?',body:'Проверь утверждение и выбери строгий аргумент.',activity:{id:'l42-p5',type:'choice',prompt:'«Угол, который меньше тупого, — острый». Верно?',options:['Да: любой меньший угол острый','Нет: например, 100° меньше тупого угла 120°, но 100° тоже тупой','Да, если тупой угол меньше 180°','Нет: потому что острых углов не бывает больше 45°'],answer:'Нет: например, 100° меньше тупого угла 120°, но 100° тоже тупой',hint:'Попробуй найти два разных тупых угла.',explanation:'Неверно. 100° < 120°, но оба угла тупые. Один контрпример опровергает общее утверждение.'},diagram:'truth'},
  {id:'l42-practice6',kind:'practice',eyebrow:'№ 310 · утверждение 2',title:'Меньше 180° — обязательно тупой?',body:'Снова ищем контрпример.',activity:{id:'l42-p6',type:'choice',prompt:'«Угол, который меньше развёрнутого, — тупой». Верно?',options:['Да: всё меньше 180° — тупое','Нет: 60° меньше 180°, но он острый','Да: кроме прямого','Нет: только потому, что 180° не измеряют'],answer:'Нет: 60° меньше 180°, но он острый',hint:'Возьми знакомый острый угол.',explanation:'Неверно: 60° < 180°, но 60° — острый угол.'},diagram:'truth'},
  {id:'l42-practice7',kind:'practice',eyebrow:'№ 310 · утверждение 3',title:'Половина тупого угла',body:'Здесь нужен не один пример, а рассуждение по диапазону.',activity:{id:'l42-p7',type:'choice',prompt:'«Половина тупого угла — острый угол». Верно?',options:['Да: половина числа между 90° и 180° лежит между 45° и 90°','Нет: половина всегда прямой угол','Нет: половина тупого угла тоже тупая','Да: потому что любой угол можно делить пополам'],answer:'Да: половина числа между 90° и 180° лежит между 45° и 90°',hint:'Если 90° < α < 180°, раздели все части неравенства на 2.',explanation:'Верно: из 90° < α < 180° следует 45° < α/2 < 90°, значит половина острая.'},diagram:'truth'},
  {id:'l42-practice8',kind:'practice',eyebrow:'№ 310 · утверждение 4',title:'Сумма двух острых',body:'Проверь, обязана ли сумма превышать 90°.',activity:{id:'l42-p8',type:'choice',prompt:'«Сумма градусных мер двух острых углов больше 90°». Верно?',options:['Да, всегда','Нет: 20° + 30° = 50°','Да, если углы разные','Нет: сумма двух углов не определена'],answer:'Нет: 20° + 30° = 50°',hint:'Возьми два небольших острых угла.',explanation:'Неверно. 20° и 30° острые, а их сумма 50° меньше 90°.'},diagram:'truth'},
  {id:'l42-practice9',kind:'practice',eyebrow:'№ 310 · утверждение 5',title:'Больше прямого — обязательно тупой?',body:'Следи за граничным случаем 180°.',activity:{id:'l42-p9',type:'choice',prompt:'«Угол, который больше прямого, — тупой». Верно?',options:['Да: всё больше 90° тупое','Нет: развёрнутый угол 180° больше 90°, но не тупой','Да, потому что 180° тоже тупой','Нет: 91° — острый'],answer:'Нет: развёрнутый угол 180° больше 90°, но не тупой',hint:'Проверь крайнее значение, которое уже изучено.',explanation:'Неверно: 180° больше 90°, но 180° — развёрнутый, а не тупой угол.'},diagram:'truth'},
  {id:'l42-clock-model',kind:'model',eyebrow:'Учебник № 311',title:'Часы превращаем в градусы',body:'Полный круг 360° разделён на 12 равных часовых промежутков, значит один промежуток равен 30°. В целые часы минутная стрелка стоит на 12, поэтому достаточно посчитать количество промежутков до часовой стрелки и выбрать меньший угол.',note:'Если путь по циферблату длиннее шести промежутков, меньший угол идёт в другую сторону.',diagram:'clock'},
  {id:'l42-practice10',kind:'practice',eyebrow:'№ 311 · 1',title:'3:00',body:'Три промежутка по 30°.',activity:{id:'l42-p10',type:'input',prompt:'Найди меньший угол между стрелками в 3:00.',answer:'90',placeholder:'Градусы',hint:'3 · 30.',explanation:'3 · 30° = 90°.'},diagram:'clock'},
  {id:'l42-practice11',kind:'practice',eyebrow:'№ 311 · 2',title:'6:00',body:'Стрелки направлены в противоположные стороны.',activity:{id:'l42-p11',type:'input',prompt:'Найди угол между стрелками в 6:00.',answer:'180',placeholder:'Градусы',hint:'6 · 30.',explanation:'6 · 30° = 180° — развёрнутый угол.'},diagram:'clock'},
  {id:'l42-practice12',kind:'practice',eyebrow:'№ 311 · 3',title:'4:00',body:'Четыре промежутка от 12 до 4.',activity:{id:'l42-p12',type:'input',prompt:'Найди меньший угол между стрелками в 4:00.',answer:'120',placeholder:'Градусы',hint:'4 · 30.',explanation:'4 · 30° = 120°.'},diagram:'clock'},
  {id:'l42-practice13',kind:'practice',eyebrow:'№ 311 · 4',title:'11:00',body:'Считать одиннадцать промежутков не нужно: ищем меньший угол.',activity:{id:'l42-p13',type:'input',prompt:'Найди меньший угол между стрелками в 11:00.',answer:'30',placeholder:'Градусы',hint:'От 11 до 12 всего один промежуток.',explanation:'Меньший угол занимает один часовой промежуток: 30°.'},diagram:'clock'},
  {id:'l42-practice14',kind:'practice',eyebrow:'№ 311 · 5',title:'7:00',body:'По короткой дуге от 7 до 12 пять промежутков.',activity:{id:'l42-p14',type:'input',prompt:'Найди меньший угол между стрелками в 7:00.',answer:'150',placeholder:'Градусы',hint:'5 · 30, а не 7 · 30.',explanation:'Меньшая дуга содержит 5 промежутков: 5 · 30° = 150°.'},diagram:'clock'},
  {id:'l42-hypothesis-model',kind:'guided',eyebrow:'Алгоритм решения',title:'Гипотеза должна пережить проверку',body:'Перед вычислением сформулируй гипотезу: какая часть общая, какое целое объединяют два данных угла, какое значение должно получиться примерно. После вычисления проверь: результат положителен, не больше каждого составного угла и позволяет восстановить целое.',diagram:'formula'},
  {id:'l42-practice15',kind:'practice',eyebrow:'Формула как модель',title:'Выбери выражение',body:'Два перекрывающихся угла α и β вместе заполняют прямой угол.',activity:{id:'l42-p15',type:'choice',prompt:'Как выразить их общую часть?',options:['α + β − 90°','90° − α − β','α + β + 90°','α − β'],answer:'α + β − 90°',hint:'В сумме α + β общая часть посчитана дважды.',explanation:'Общая часть = α + β − 90°.'},diagram:'formula'},
  {id:'l42-check-model',kind:'model',eyebrow:'Обратная проверка',title:'Не останавливайся на одном числе',body:'Если общая часть x найдена, крайние части равны α − x и β − x. Их сумма с x должна дать всё целое. Так мы одновременно проверяем арифметику и правильность чтения рисунка.',diagram:'check'},
  {id:'l42-practice16',kind:'practice',eyebrow:'Самостоятельно · 1',title:'112° и 135° внутри 180°',body:'Два составных угла перекрываются и вместе дают развёрнутый угол.',activity:{id:'l42-p16',type:'input',prompt:'Найди общую часть.',answer:'67',placeholder:'Градусы',hint:'112 + 135 − 180.',explanation:'112° + 135° − 180° = 67°. Крайние части: 45° и 68°; 45° + 67° + 68° = 180°.'},diagram:'straight-overlap'},
  {id:'l42-multi-right-model',kind:'model',eyebrow:'Сложный прямой угол',title:'Чертёж может выглядеть иначе — инвариант тот же',body:'Поворот рисунка, длина лучей и подписи не меняют отношения частей. Если объединение двух составных углов — прямой угол, всё равно вычитаем 90° после сложения данных мер.',diagram:'right-overlap'},
  {id:'l42-practice17',kind:'practice',eyebrow:'Самостоятельно · 2',title:'66° и 62° внутри 90°',body:'Найди перекрытие без рисунка в стандартном положении.',activity:{id:'l42-p17',type:'input',prompt:'Два перекрывающихся угла 66° и 62° вместе заполняют прямой угол. Общая часть?',answer:'38',placeholder:'Градусы',hint:'66 + 62 − 90.',explanation:'66° + 62° − 90° = 38°.'},diagram:'right-overlap'},
  {id:'l42-multi-straight-model',kind:'model',eyebrow:'Сложный развёрнутый угол',title:'Проверяй границы результата',body:'Общая часть перекрывающихся углов должна быть меньше или равна каждому из них. Если формула дала число больше меньшего исходного угла, значит неверно определено целое или данные углы не заполняют его так, как предполагалось.',diagram:'straight-overlap'},
  {id:'l42-practice18',kind:'practice',eyebrow:'Самостоятельно · 3',title:'166° и 151° внутри 180°',body:'Большое перекрытие в развёрнутом угле.',activity:{id:'l42-p18',type:'input',prompt:'Найди общую часть.',answer:'137',placeholder:'Градусы',hint:'166 + 151 − 180.',explanation:'166° + 151° − 180° = 137°. Проверка: 137° меньше и 151°, и 166°.'},diagram:'straight-overlap'},
  {id:'l42-error-model',kind:'model',eyebrow:'Диагностика ошибки',title:'Формула без проверки рисунка опасна',body:'Нельзя автоматически складывать любые два угла и вычитать 90° или 180°. Сначала докажи, что они перекрываются и что их объединение — именно известный прямой или развёрнутый угол. Геометрическая модель важнее запомненной формулы.',diagram:'error'},
  {id:'l42-quiz1',kind:'quiz',eyebrow:'Мини-контроль · 1/2',title:'Вернись к № 308 без подсказки',body:'Прямой угол; два перекрывающихся угла 74° и 62°.',activity:{id:'l42-q1',type:'input',prompt:'Общая часть равна…',answer:'46',placeholder:'Градусы',hint:'Какую величину нужно вычесть из суммы двух составных углов?',explanation:'74° + 62° − 90° = 46°.'},diagram:'right-overlap'},
  {id:'l42-quiz2',kind:'quiz',eyebrow:'Мини-контроль · 2/2',title:'Классифицируй по числу',body:'После вычисления обязательно оцени вид угла.',activity:{id:'l42-q2',type:'choice',prompt:'Как правильно классифицировать угол 75°?',options:['Острый: 75°','Прямой: 75°','Тупой: 75°','Развёрнутый: 75°'],answer:'Острый: 75°',hint:'Сравни с 90°.',explanation:'75° < 90°, поэтому угол острый.'},diagram:'truth'},
  {id:'l42-challenge1',kind:'challenge',eyebrow:'Задача со звёздочкой · 1',title:'83° и 71° внутри прямого угла',body:'Сначала предскажи: перекрытие должно быть заметно больше 50°, потому что сумма данных углов намного больше 90°.',activity:{id:'l42-c1',type:'input',prompt:'Найди общую часть.',answer:'64',placeholder:'Градусы',hint:'83 + 71 − 90.',explanation:'83° + 71° − 90° = 64°. Крайние части 19° и 7°, вместе с 64° они дают 90°.'},diagram:'check'},
  {id:'l42-challenge2',kind:'challenge',eyebrow:'Задача со звёздочкой · 2',title:'Контрпример за один ход',body:'Нужно опровергнуть утверждение «сумма любых двух острых углов больше прямого».',activity:{id:'l42-c2',type:'choice',prompt:'Какой вариант является достаточным контрпримером?',options:['20° + 30° = 50°','50° + 50° = 100°','45° + 45° = 90°','100° + 20° = 120°'],answer:'20° + 30° = 50°',hint:'Оба исходных угла должны быть острыми, а сумма — не больше 90°.',explanation:'20° и 30° острые, но их сумма 50°. Этого одного примера достаточно, чтобы опровергнуть утверждение.'},diagram:'truth'},
  {id:'l42-summary',kind:'summary',eyebrow:'Итоги урока',title:'Ты решаешь угол как систему условий',body:'Теперь ты умеешь видеть общую часть двух составных углов, использовать 90° и 180°, проверять гипотезу восстановлением чертежа, опровергать неверные утверждения контрпримером и переводить часовые промежутки в градусы. Следующий урок § 12 будет обобщением всей темы перед переходом к многоугольникам.',note:'Главная привычка: не применять формулу раньше, чем понял геометрию рисунка.',diagram:'check'},
];

function DiagramView({kind}:{kind:Diagram}){
  if(kind==='right-overlap')return <div className="angle-diagram" aria-label="Перекрывающиеся углы внутри прямого угла"><svg viewBox="0 0 620 320" role="img"><g transform="translate(310 260)"><line className="angle-ray" x1="0" y1="0" x2="-220" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="0" y2="-220"/><line className="measure-mark" x1="0" y1="0" x2="-155" y2="-155"/><line className="measure-mark" x1="0" y1="0" x2="-65" y2="-205"/><text className="measure-small" x="-185" y="-45">28°</text><text className="measure-label" x="-115" y="-120">46°</text><text className="measure-small" x="-45" y="-155">16°</text><text className="measure-small" x="-210" y="32">B</text><text className="measure-small" x="12" y="-205">M</text></g></svg><span className="angle-caption">74° + 62° − 90° = 46°</span></div>;
  if(kind==='straight-overlap')return <div className="angle-diagram" aria-label="Перекрывающиеся углы внутри развёрнутого угла"><svg viewBox="0 0 620 300" role="img"><g transform="translate(310 235)"><line className="angle-ray" x1="0" y1="0" x2="-250" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="250" y2="0"/><line className="measure-mark" x1="0" y1="0" x2="-95" y2="-195"/><line className="measure-mark" x1="0" y1="0" x2="130" y2="-175"/><text className="measure-label" x="-55" y="-115">общая часть</text><text className="measure-small" x="-230" y="30">180° целиком</text></g></svg><span className="angle-caption">общая часть = α + β − 180°</span></div>;
  if(kind==='formula')return <div className="angle-diagram" aria-label="Формула перекрывающихся углов"><svg viewBox="0 0 620 280" role="img"><text className="measure-label" x="70" y="80">α = левая часть + x</text><text className="measure-label" x="70" y="135">β = x + правая часть</text><text className="measure-label" x="70" y="205">x = α + β − целое</text></svg><span className="angle-caption">Сначала докажи, что объединение равно целому</span></div>;
  if(kind==='truth')return <div className="angle-diagram" aria-label="Классификация углов по градусной мере"><svg viewBox="0 0 620 260" role="img"><line className="angle-ray" x1="70" y1="145" x2="550" y2="145"/><text className="measure-small" x="62" y="185">0°</text><text className="measure-label" x="285" y="105">90°</text><text className="measure-label" x="500" y="105">180°</text><text className="measure-small" x="140" y="205">острые</text><text className="measure-small" x="380" y="205">тупые</text></svg><span className="angle-caption">Контрпример проверяет общее утверждение</span></div>;
  if(kind==='clock')return <div className="angle-diagram" aria-label="Циферблат с часовыми промежутками"><svg viewBox="0 0 620 330" role="img"><circle className="measure-protractor" cx="310" cy="165" r="125"/><line className="angle-ray" x1="310" y1="165" x2="310" y2="55"/><line className="angle-ray" x1="310" y1="165" x2="420" y2="165"/><text className="measure-label" x="335" y="112">30° × n</text><text className="measure-small" x="300" y="42">12</text><text className="measure-small" x="438" y="172">3</text><text className="measure-small" x="304" y="310">6</text><text className="measure-small" x="165" y="172">9</text></svg><span className="angle-caption">Один часовой промежуток = 30°</span></div>;
  if(kind==='check')return <div className="angle-diagram" aria-label="Обратная проверка частей угла"><svg viewBox="0 0 620 280" role="img"><text className="measure-label" x="65" y="80">левая = α − x</text><text className="measure-label" x="65" y="135">правая = β − x</text><text className="measure-label" x="65" y="205">левая + x + правая = целое ✓</text></svg><span className="angle-caption">Проверка восстанавливает весь угол</span></div>;
  return <div className="angle-diagram" aria-label="Предупреждение о неверном применении формулы"><svg viewBox="0 0 620 270" role="img"><text className="measure-label" x="70" y="85">α + β − 90° ?</text><text className="measure-label" x="70" y="145">Сначала: объединение = 90°?</text><text className="measure-small" x="70" y="210">Формула без геометрического основания не доказательство.</text></svg></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyTwoStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function OverlappingAngleProblemsPlayer(){
  const initial=useMemo(loadSaved,[]);
  const[stageIndex,setStageIndex]=useState(initial.stageIndex);
  const[responses,setResponses]=useState<Record<string,string>>(initial.responses);
  const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);
  const[results,setResults]=useState<Record<string,boolean>>(initial.results);
  const stage=lessonFortyTwoStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==42||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonFortyTwoStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonFortyTwoStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player measurement-player" aria-label="Урок 42. Геометрические задачи на градусную меру"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<DiagramView kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>setResponse(option)} disabled={isCorrect}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric" disabled={isCorrect}/></div>}<button type="button" className="check-button" disabled={!response.trim()||isCorrect} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 12 · урок 4 из 5 завершён</strong><span>перекрывающиеся углы · 90° · 180° · доказательство и контрпример · часы · обратная проверка</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonFortyTwoStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonFortyTwoStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonFortyTwoStages.length-1?'Готово':'Дальше →'}</button></div></article></section>;
}
