import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'solid'|'wire'|'surface'|'net'|'polyhedron'|'source'|'verify'|'final';
export type LessonSeventyNineStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-79-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyNineStages:LessonSeventyNineStage[]=[
{id:'l79-mission',kind:'story',eyebrow:'Урок 79 · § 22 · продолжение',title:'Развернуть тело на плоскости',body:'В прошлом уроке мы разобрали грани, рёбра, вершины и площадь поверхности. Теперь научимся мысленно раскрывать прямоугольный параллелепипед в плоскую развёртку и собирать обратно.',note:'Технологическая карта урока 79: устно № 3–4, с. 150; № 608, 610; теория § 22, с. 147–148; № 606; повторение № 613; домашнее № 607, 609, доп. № 616.',visual:'mission'},
{id:'l79-oral3-model',kind:'guided',eyebrow:'Актуализация · устно № 3, с. 150',title:'Распределительное свойство перед геометрией',body:'Раскроем скобки: множитель перед скобками умножается на каждое слагаемое внутри. Это тот же приём, который помогает преобразовывать формулы площади.',visual:'verify',sourceExercise:'Устно № 3, с. 150'},
{id:'l79-oral3-a',kind:'practice',eyebrow:'Устно № 3(1)',title:'2(a+b)',body:'Умножь 2 на каждое слагаемое.',activity:{id:'l79-p1',type:'input',prompt:'2(a+b) = ?',answer:['2a+2b','2·a+2·b'],hint:'2 умножается и на a, и на b.',explanation:'2(a+b)=2a+2b.'},visual:'verify',sourceExercise:'Устно № 3(1), с. 150'},
{id:'l79-oral3-b',kind:'practice',eyebrow:'Устно № 3(2)',title:'(3-b)·5',body:'Умножь оба члена разности на 5.',activity:{id:'l79-p2',type:'input',prompt:'(3-b)·5 = ?',answer:['15-5b','15-5·b'],hint:'3·5=15, b·5=5b.',explanation:'(3-b)·5=15-5b.'},visual:'verify',sourceExercise:'Устно № 3(2), с. 150'},
{id:'l79-oral3-c',kind:'practice',eyebrow:'Устно № 3(3)',title:'6m(7n+8p)',body:'Сохрани буквенные множители и вычисли числовые коэффициенты.',activity:{id:'l79-p3',type:'input',prompt:'6m(7n+8p) = ?',answer:['42mn+48mp','42·m·n+48·m·p'],hint:'6·7=42, 6·8=48.',explanation:'6m(7n+8p)=42mn+48mp.'},visual:'verify',sourceExercise:'Устно № 3(3), с. 150'},
{id:'l79-oral4-model',kind:'guided',eyebrow:'Актуализация · устно № 4, с. 150',title:'Площадь известна — восстанови сторону',body:'Площадь прямоугольника 28 см², одна сторона 7 см. Сначала найдём вторую сторону, затем периметр.',visual:'surface',sourceExercise:'Устно № 4, с. 150'},
{id:'l79-oral4-side',kind:'practice',eyebrow:'Устно № 4 · шаг 1',title:'Обратная задача к S=ab',body:'Если 7·b=28, то b=28:7.',activity:{id:'l79-p4',type:'input',prompt:'Вторая сторона = ? см',answer:'4',placeholder:'см',hint:'28:7.',explanation:'Вторая сторона равна 4 см.'},visual:'surface',sourceExercise:'Устно № 4, с. 150'},
{id:'l79-oral4-perimeter',kind:'practice',eyebrow:'Устно № 4 · шаг 2',title:'Теперь периметр',body:'P=2(a+b).',activity:{id:'l79-p5',type:'input',prompt:'P=2·(7+4) = ? см',answer:'22',placeholder:'см',hint:'7+4=11.',explanation:'P=22 см.'},visual:'surface',sourceExercise:'Устно № 4, с. 150'},
{id:'l79-refresh-model',kind:'model',eyebrow:'§ 22 · закрепление',title:'Каркас знаний 6–12–8',body:'У прямоугольного параллелепипеда 6 прямоугольных граней, 12 рёбер и 8 вершин. Противолежащие грани попарно равны.',visual:'solid',sourceExercise:'§ 22'},
{id:'l79-faces-count',kind:'quiz',eyebrow:'§ 22 · быстрая проверка',title:'Грани',body:'Каждая грань — прямоугольник.',activity:{id:'l79-p6',type:'input',prompt:'Сколько граней?',answer:'6',hint:'Верх, низ и четыре боковые.',explanation:'6 граней.'},visual:'solid',sourceExercise:'§ 22'},
{id:'l79-edges-count',kind:'quiz',eyebrow:'§ 22 · быстрая проверка',title:'Рёбра',body:'Стороны граней образуют рёбра тела.',activity:{id:'l79-p7',type:'input',prompt:'Сколько рёбер?',answer:'12',hint:'Четыре сверху, четыре снизу и четыре вертикальных.',explanation:'12 рёбер.'},visual:'wire',sourceExercise:'§ 22'},
{id:'l79-vertices-count',kind:'quiz',eyebrow:'§ 22 · быстрая проверка',title:'Вершины',body:'В каждой вершине сходятся три ребра.',activity:{id:'l79-p8',type:'input',prompt:'Сколько вершин?',answer:'8',hint:'Четыре на одном основании и четыре на противоположном.',explanation:'8 вершин.'},visual:'wire',sourceExercise:'§ 22'},
{id:'l79-surface-model',kind:'model',eyebrow:'§ 22 · формула поверхности',title:'Три пары равных граней',body:'Для измерений a, b, c площади трёх типов граней равны ab, bc и ac. Каждая встречается дважды, поэтому Sпов=2(ab+bc+ac).',visual:'surface',sourceExercise:'§ 22'},
{id:'l79-drawing-model',kind:'model',eyebrow:'Методический акцент',title:'Как изображать объёмное тело',body:'Каркасная модель помогает различать видимые и невидимые рёбра. На клетчатой бумаге сначала удобно построить две смещённые одинаковые прямоугольные грани, затем соединить соответствующие вершины.',note:'Методическое пособие специально рекомендует сопоставлять сплошную и каркасную модели и тренировать изображение прямоугольного параллелепипеда на клетчатой бумаге.',visual:'wire',sourceExercise:'§ 22 · построение изображения'},
{id:'l79-608-model',kind:'guided',eyebrow:'№ 608',title:'Сначала восстановим три измерения',body:'Высота равна 20 см. Она на 5 см больше ширины и в 3 раза меньше длины. Значит ширину и длину нельзя подставлять в формулу до восстановления.',visual:'solid',sourceExercise:'№ 608'},
{id:'l79-608-width',kind:'practice',eyebrow:'№ 608 · шаг 1',title:'Ширина',body:'Высота на 5 см больше ширины.',activity:{id:'l79-p9',type:'input',prompt:'Ширина = 20−5 = ? см',answer:'15',placeholder:'см',hint:'20−5.',explanation:'Ширина 15 см.'},visual:'solid',sourceExercise:'№ 608'},
{id:'l79-608-length',kind:'practice',eyebrow:'№ 608 · шаг 2',title:'Длина',body:'Высота в 3 раза меньше длины.',activity:{id:'l79-p10',type:'input',prompt:'Длина = 20·3 = ? см',answer:'60',placeholder:'см',hint:'Если 20 в 3 раза меньше длины, длина в 3 раза больше 20.',explanation:'Длина 60 см.'},visual:'solid',sourceExercise:'№ 608'},
{id:'l79-608-surface',kind:'practice',eyebrow:'№ 608 · шаг 3',title:'Площадь всей поверхности',body:'Подставляем 60, 15 и 20: S=2(60·15+15·20+60·20).',activity:{id:'l79-p11',type:'input',prompt:'Sпов = ? см²',answer:'4800',placeholder:'см²',hint:'900+300+1200=2400; удвой.',explanation:'Sпов=4800 см².'},visual:'surface',sourceExercise:'№ 608'},
{id:'l79-610-model',kind:'guided',eyebrow:'№ 610',title:'Параллелепипед и куб с равными площадями',body:'Длина параллелепипеда 18 м: она в 2 раза больше ширины и на 8 м больше высоты. После площади поверхности найдём ребро куба с такой же площадью.',visual:'solid',sourceExercise:'№ 610'},
{id:'l79-610-width',kind:'practice',eyebrow:'№ 610 · шаг 1',title:'Ширина',body:'18 м — это удвоенная ширина.',activity:{id:'l79-p12',type:'input',prompt:'Ширина = 18:2 = ? м',answer:'9',placeholder:'м',hint:'18:2.',explanation:'Ширина 9 м.'},visual:'solid',sourceExercise:'№ 610'},
{id:'l79-610-height',kind:'practice',eyebrow:'№ 610 · шаг 2',title:'Высота',body:'Длина на 8 м больше высоты.',activity:{id:'l79-p13',type:'input',prompt:'Высота = 18−8 = ? м',answer:'10',placeholder:'м',hint:'18−8.',explanation:'Высота 10 м.'},visual:'solid',sourceExercise:'№ 610'},
{id:'l79-610-surface',kind:'practice',eyebrow:'№ 610 · шаг 3',title:'Поверхность параллелепипеда',body:'S=2(18·9+9·10+18·10).',activity:{id:'l79-p14',type:'input',prompt:'Sпов = ? м²',answer:'864',placeholder:'м²',hint:'162+90+180=432; удвой.',explanation:'Sпов=864 м².'},visual:'surface',sourceExercise:'№ 610'},
{id:'l79-610-cube-model',kind:'model',eyebrow:'№ 610 · шаг 4',title:'Та же площадь у куба',body:'У куба S=6a². Поэтому 6a²=864, откуда a²=144.',visual:'surface',sourceExercise:'№ 610'},
{id:'l79-610-cube-edge',kind:'practice',eyebrow:'№ 610 · ответ',title:'Ребро куба',body:'Нужно натуральное число, квадрат которого равен 144.',activity:{id:'l79-p15',type:'input',prompt:'a = ? м',answer:'12',placeholder:'м',hint:'12·12=144.',explanation:'Ребро куба равно 12 м.'},visual:'solid',sourceExercise:'№ 610'},
{id:'l79-net-theory',kind:'model',eyebrow:'§ 22 · с. 147–148',title:'Развёртка — поверхность, раскрытая на плоскости',body:'Чтобы получить модель прямоугольного параллелепипеда, его развёртку чертят на бумаге, вырезают, сгибают по отрезкам, соответствующим рёбрам, и склеивают.',visual:'net',sourceExercise:'§ 22, с. 147–148'},
{id:'l79-net-sequence',kind:'quiz',eyebrow:'§ 22 · сборка модели',title:'Правильная последовательность',body:'Развёртка связывает плоский чертёж и пространственное тело.',activity:{id:'l79-p16',type:'choice',prompt:'Какой порядок соответствует изготовлению модели из развёртки?',options:['начертить → вырезать → согнуть → склеить','склеить → начертить → вырезать → согнуть','согнуть → склеить → начертить → вырезать'],answer:'начертить → вырезать → согнуть → склеить',hint:'Сначала нужна плоская заготовка.',explanation:'Сначала чертят развёртку, затем вырезают, сгибают и склеивают.'},visual:'net',sourceExercise:'§ 22, с. 148'},
{id:'l79-polyhedron-model',kind:'model',eyebrow:'§ 22 · с. 148',title:'Прямоугольный параллелепипед — многогранник',body:'Многогранник — фигура, поверхность которой состоит из многоугольников. Прямоугольный параллелепипед является одним из видов многогранника и одновременно видом призмы.',visual:'polyhedron',sourceExercise:'§ 22, с. 148'},
{id:'l79-polyhedron-choice',kind:'quiz',eyebrow:'§ 22 · понятие',title:'Что делает тело многогранником?',body:'Смотрим именно на поверхность тела.',activity:{id:'l79-p17',type:'choice',prompt:'Из чего состоит поверхность многогранника?',options:['из многоугольников','только из кругов','из одной прямой'],answer:'из многоугольников',hint:'Название связано со словом «грань».',explanation:'Поверхность многогранника состоит из многоугольников.'},visual:'polyhedron',sourceExercise:'§ 22, с. 148'},
{id:'l79-606-model',kind:'guided',eyebrow:'№ 606 · рис. 174',title:'Читаем развёртку по исходному рисунку',body:'В № 606 дана развёртка прямоугольного параллелепипеда и размеры 10 см, 7 см и 3 см. Нужно связать плоскую развёртку с шестью гранями тела.',note:'Форма развёртки зависит от исходного рисунка. Приложение не подменяет рисунок 174 приблизительной копией: здесь проверяются только свойства и вычисления, которые однозначно следуют из точного условия.',visual:'source',sourceExercise:'№ 606 · рис. 174'},
{id:'l79-606-rectangles',kind:'practice',eyebrow:'№ 606(1)',title:'Сколько прямоугольников?',body:'Каждый прямоугольник развёртки станет одной гранью.',activity:{id:'l79-p18',type:'input',prompt:'Из скольких прямоугольников состоит развёртка?',answer:'6',hint:'У тела 6 граней.',explanation:'Развёртка содержит 6 прямоугольников.'},visual:'net',sourceExercise:'№ 606(1)'},
{id:'l79-606-pairs',kind:'practice',eyebrow:'№ 606(2)',title:'Равные пары',body:'Противолежащие грани равны, поэтому шесть прямоугольников образуют три пары.',activity:{id:'l79-p19',type:'input',prompt:'Сколько пар равных прямоугольников?',answer:'3',hint:'6 прямоугольников попарно соответствуют противолежащим граням.',explanation:'3 пары равных прямоугольников.'},visual:'net',sourceExercise:'№ 606(2)'},
{id:'l79-606-area',kind:'practice',eyebrow:'№ 606(3)',title:'Площадь развёртки = площадь поверхности',body:'Для размеров 10, 7, 3 получаем 2(10·7+7·3+10·3).',activity:{id:'l79-p20',type:'input',prompt:'Площадь развёртки = ? см²',answer:'242',placeholder:'см²',hint:'70+21+30=121; удвой.',explanation:'Площадь развёртки равна 242 см².'},visual:'surface',sourceExercise:'№ 606(3)'},
{id:'l79-613',kind:'practice',eyebrow:'Повторение · № 613',title:'Шесть квадратов с одного листа',body:'Из одного листа картона вырезают 6 одинаковых квадратов. Для 50 квадратов нужно целое число листов.',activity:{id:'l79-p21',type:'input',prompt:'Сколько листов нужно?',answer:'9',hint:'8 листов дадут только 48 квадратов.',explanation:'Нужно 9 листов: 8 недостаточно, а 9 дают не меньше 50 квадратов.'},visual:'verify',sourceExercise:'№ 613'},
{id:'l79-home-transfer',kind:'model',eyebrow:'Домашний маршрут',title:'№ 607, 609 и дополнительное № 616',body:'№ 607: по развёртке с измерениями 4 см, 6 см и 2 см площадь поверхности равна 88 см². № 609: если сумма длин всех 12 рёбер равна 28 см, то a+b+c=7 см.',note:'Дополнительное № 616 просит придумать способ измерить диагональ кирпича линейкой, имея ещё несколько таких кирпичей. Это оставлено как исходная задача на пространственную смекалку без подмены авторского решения.',visual:'source',sourceExercise:'ДЗ § 22 · № 607, 609 · доп. № 616'},
{id:'l79-source-reflection',kind:'story',eyebrow:'Рефлексия',title:'Плоский чертёж и объёмное тело — две стороны одной модели',body:'Проверь себя: можешь ли ты объяснить, какие прямоугольники развёртки станут противолежащими гранями, и почему площадь развёртки равна площади поверхности собранного тела?',visual:'net'},
{id:'l79-summary',kind:'summary',eyebrow:'Итог урока 79',title:'Ты умеешь читать параллелепипед и в 3D, и на плоскости',body:'Ты закрепил формулу Sпов=2(ab+bc+ac), восстановил измерения в № 608 и 610, связал шесть граней с развёрткой и освоил понятие многогранника. Теперь пространственный чертёж, каркас и развёртка описывают одно и то же тело разными способами.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 80 — «Пирамида» — уже доступен в каталоге.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'3D↔2D',solid:'▣',wire:'⌗',surface:'S',net:'✣',polyhedron:'⬡',source:'§22',verify:'✓',final:'79'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='net'?'развёртка: 6 граней на плоскости':kind==='polyhedron'?'поверхность из многоугольников':kind==='surface'?'Sпов = 2(ab + bc + ac)':kind==='wire'?'каркас · видимые и невидимые рёбра':'пространственная геометрия · § 22'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyNineStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function ParallelepipedNetsPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyNineStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyNineStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==79||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyNineStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyNineStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player parallelepiped-nets-player" data-lesson-number="79" data-source-reference="Мерзляк § 22 · технологическая карта урока 79 · устно 3–4 · № 608, 610, 606 · повторение № 613" data-source-exercise-range="606,608,610,613"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyNineStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonSeventyNineStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
