import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './segmentLength.css';
import './polyline.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type PolylineStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-8-progress-v2';
const LEGACY_KEY='mathnikita-lesson-8-progress-v1';

export const lessonEightStages:PolylineStage[]=[
  {id:'l8-story',kind:'story',eyebrow:'Новая геометрическая фигура',title:'Маршрут из отрезков превращается в ломаную',body:'Отрезок соединяет две точки напрямую. Но реальный маршрут часто меняет направление: один отрезок заканчивается там, где начинается следующий. Так появляется ломаная.',note:'Сегодня три главных понятия: ломаная, длина ломаной, замкнутая ломаная.',sourceTag:'Мерзляк § 3 · урок 8 · изучение нового материала'},
  {id:'l8-definition',kind:'model',eyebrow:'Определение',title:'Ломаная — это последовательная цепочка отрезков',body:'Отрезки образуют ломаную, когда конец первого совпадает с концом второго, другой конец второго — с концом третьего и так далее. При этом соседние звенья не лежат на одной прямой.',note:'Два условия: звенья соединены последовательно и в общей вершине действительно меняют направление.',sourceTag:'Мерзляк § 3 · теория · методический комментарий'},
  {id:'l8-recognize',kind:'guided',eyebrow:'Проверяем определение',title:'Не всякий набор отрезков — ломаная',body:'Проверь оба условия: соседние звенья должны иметь общий конец и не должны лежать на одной прямой.',activity:{id:'l8-a1',type:'choice',prompt:'Какая запись точно описывает ломаную ABCD?',options:['AB, BC, CD соединены последовательно и соседние звенья меняют направление','AB, BC, CD лежат на одной прямой','AB и CD не соединены через BC','есть только один отрезок AB'],answer:'AB, BC, CD соединены последовательно и соседние звенья меняют направление',explanation:'У ломаной звенья AB, BC и CD соединены последовательно, а соседние звенья не лежат на одной прямой.'},sourceTag:'Мерзляк § 3 · рис. 10–11 · методический комментарий'},
  {id:'l8-parts',kind:'model',eyebrow:'Язык геометрии',title:'Вершины, звенья и концы',body:'В ломаной ABCDE точки A, B, C, D, E называют вершинами; AB, BC, CD, DE — звеньями; A и E — концами ломаной.',note:'У открытой ломаной число звеньев на единицу меньше числа перечисленных вершин.',sourceTag:'Мерзляк § 3 · теория'},
  {id:'l8-links',kind:'guided',eyebrow:'Считаем звенья',title:'Пять вершин — четыре перехода',body:'Чтобы не пересчитывать линии на глаз, выпиши соседние пары букв.',activity:{id:'l8-a2',type:'input',prompt:'Сколько звеньев у ломаной ABCDE?',answer:'4',placeholder:'Количество звеньев',explanation:'Это AB, BC, CD и DE — всего 4 звена.'}},
  {id:'l8-length-rule',kind:'model',eyebrow:'Главное правило',title:'Длина ломаной — сумма длин всех её звеньев',body:'Каждое звено вносит свой участок пути. Поэтому длину ломаной получают сложением длин всех звеньев.',note:'Для ABCD: длина = AB + BC + CD.',sourceTag:'Мерзляк § 3 · теория'},
  {id:'l8-length-guided',kind:'guided',eyebrow:'Быстрая проверка',title:'Сложи три звена в одной единице',body:'В математическом диктанте по теме дана ломаная CDEF: CD = 8 мм, DE = 10 мм, EF = 14 мм.',activity:{id:'l8-a3',type:'input',prompt:'Какова длина ломаной CDEF в миллиметрах?',answer:'32',placeholder:'Ответ в мм',explanation:'8 + 10 + 14 = 32 мм.'},sourceTag:'Методическое пособие · математический диктант 2'},
  {id:'l8-closed',kind:'model',eyebrow:'Ещё один вид ломаной',title:'Если концы совпали — ломаная замкнутая',body:'У замкнутой ломаной последний участок возвращает маршрут в начальную точку. Начало и конец совпадают.',note:'Замкнутая ломаная не имеет двух разных концов.',sourceTag:'Мерзляк § 3 · технологическая карта урока 8'},
  {id:'l8-closed-check',kind:'guided',eyebrow:'Узнай по признаку',title:'Открытая или замкнутая?',body:'Не ориентируйся на внешний вид — проверь, совпадают ли начало и конец.',activity:{id:'l8-a4',type:'choice',prompt:'Какой признак точно означает, что ломаная замкнутая?',options:['её концы совпадают','у неё ровно три звена','все звенья равны','она нарисована горизонтально'],answer:'её концы совпадают',explanation:'По определению замкнутой называют ломаную, концы которой совпадают.'}},
  {id:'l8-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Задача № 68: собери длину из трёх звеньев',body:'AC = 15 мм, CD = 24 мм, DM = 32 мм. После построения ломаной ACDM нужно вычислить её длину.',activity:{id:'l8-p1',type:'input',prompt:'Чему равна длина ломаной ACDM в миллиметрах?',answer:'71',placeholder:'Ответ в мм',explanation:'15 + 24 + 32 = 71 мм.'},sourceTag:'Мерзляк § 3 · № 68'},
  {id:'l8-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Задача № 71: не сложи перекрывающиеся отрезки',body:'На рисунке точки расположены A—B—C—D. Даны AC = 8 см, BC = 2 см и BD = 6 см. Отрезки AC и BD перекрываются на участке BC, поэтому складывать 8 + 2 + 6 нельзя.',activity:{id:'l8-p2',type:'input',prompt:'Найди AD в сантиметрах.',answer:'12',placeholder:'Ответ в см',explanation:'AB = AC − BC = 8 − 2 = 6 см. Затем AD = AB + BD = 6 + 6 = 12 см.'},sourceTag:'Мерзляк § 3 · № 71'},
  {id:'l8-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Задача № 74: точки задают соседние отрезки',body:'На первом отрезке отмечено 7 точек с шагом 3 см, на втором — 10 точек с шагом 2 см. Между n точками подряд получается n − 1 промежутков.',activity:{id:'l8-p3',type:'choice',prompt:'Расстояние между крайними отмеченными точками где больше?',options:['на первом отрезке','на втором отрезке','расстояния равны','данных недостаточно'],answer:'расстояния равны',explanation:'Первый: (7 − 1)·3 = 18 см. Второй: (10 − 1)·2 = 18 см. Расстояния равны.'},sourceTag:'Мерзляк § 3 · № 74 · методический комментарий'},
  {id:'l8-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Задача № 77: необычная линейка',body:'На линейке отмечены только 0 см, 5 см и 13 см. Нужно строить новые длины, каждый раз используя доступные расстояния между отметками или повторяя их.',activity:{id:'l8-p4',type:'choice',prompt:'Как корректно построить отрезок длиной 3 см?',options:['построить 13 см и отложить внутрь по 5 см от обоих концов','взять только расстояние 13 − 5','сложить два отрезка по 5 см','считать, что на линейке уже есть отметка 3 см'],answer:'построить 13 см и отложить внутрь по 5 см от обоих концов',explanation:'На отрезке 13 см откладываем по 5 см от каждого конца. Между двумя полученными точками остаётся 13 − 5 − 5 = 3 см.'},sourceTag:'Мерзляк § 3 · № 77'},
  {id:'l8-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Перед сложением приведи единицы',body:'Ломаная состоит из двух звеньев длиной 28 мм и 2 см.',activity:{id:'l8-p5',type:'input',prompt:'Какова длина ломаной в миллиметрах?',answer:'48',placeholder:'Ответ в мм',explanation:'2 см = 20 мм; 28 + 20 = 48 мм.'},sourceTag:'Методическое пособие · математический диктант 2'},
  {id:'l8-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Алгоритм вычисления длины ломаной',body:'Правильный порядок особенно важен, когда в условии смешаны сантиметры и миллиметры.',activity:{id:'l8-p6',type:'order',prompt:'Расставь шаги решения',items:['Назвать все звенья ломаной','Привести длины к одной единице','Сложить длины всех звеньев','Записать ответ с единицей измерения'],answer:['Назвать все звенья ломаной','Привести длины к одной единице','Сложить длины всех звеньев','Записать ответ с единицей измерения'],explanation:'Сначала убеждаемся, что учтены все звенья, затем приводим единицы, складываем и подписываем единицу результата.'}},
  {id:'l8-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Длина ломаной',body:'Без подсказки.',activity:{id:'l8-q1',type:'input',prompt:'AB = 7 см, BC = 5 см, CD = 8 см. Найди длину ломаной ABCD.',answer:'20',placeholder:'Ответ в см',explanation:'7 + 5 + 8 = 20 см.'}},
  {id:'l8-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Вершины и звенья',body:'Без подсказки.',activity:{id:'l8-q2',type:'choice',prompt:'Сколько звеньев у открытой ломаной KLMNP?',options:['3','4','5','6'],answer:'4',explanation:'KL, LM, MN и NP — четыре звена.'}},
  {id:'l8-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Замкнутая ломаная',body:'Без подсказки.',activity:{id:'l8-q3',type:'choice',prompt:'Что обязательно верно для замкнутой ломаной?',options:['её концы совпадают','все звенья одинаковы','она имеет четыре вершины','она не меняет направление'],answer:'её концы совпадают',explanation:'Это определяющий признак замкнутой ломаной.'}},
  {id:'l8-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Смешанные единицы',body:'Без подсказки.',activity:{id:'l8-q4',type:'input',prompt:'Два звена имеют длины 35 мм и 4 см. Какова общая длина в миллиметрах?',answer:'75',placeholder:'Ответ в мм',explanation:'4 см = 40 мм; 35 + 40 = 75 мм.'}},
  {id:'l8-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Точки и промежутки',body:'Используй идею задачи № 74.',activity:{id:'l8-q5',type:'input',prompt:'На прямой подряд отметили 12 точек. Сколько отрезков между соседними отмеченными точками?',answer:'11',placeholder:'Количество',explanation:'Между n последовательными точками находится n − 1 промежутков: 12 − 1 = 11.'}},
  {id:'l8-challenge',kind:'challenge',eyebrow:'Задача повышенного уровня',title:'Построй 3 см, 2 см и 1 см линейкой с отметками 0, 5 и 13',body:'Нельзя воображать на линейке новые деления. Каждую следующую длину нужно получить реальным построением из расстояний 5 см, 8 см и 13 см и их повторений.',activity:{id:'l8-c1',type:'order',prompt:'Расставь корректную цепочку построений из задачи № 77',items:['Получить 3 см как остаток 13 − 5 − 5','Построить 15 см тремя шагами по 5 см','Получить 2 см как разность 15 − 13','Получить 8 см как 13 − 5 и построить 16 см двумя шагами по 8 см','Получить 1 см как разность 16 − 15'],answer:['Получить 3 см как остаток 13 − 5 − 5','Построить 15 см тремя шагами по 5 см','Получить 2 см как разность 15 − 13','Получить 8 см как 13 − 5 и построить 16 см двумя шагами по 8 см','Получить 1 см как разность 16 − 15'],explanation:'Получаем 3 см как 13 − 10, 2 см как 15 − 13, а 1 см как 16 − 15, где 16 = 8 + 8 и 8 = 13 − 5. Все построения используют только расстояния, доступные этой линейкой.'},sourceTag:'Мерзляк § 3 · № 77 · технологическая карта урока'},
  {id:'l8-reflection',kind:'model',eyebrow:'Рефлексия',title:'Сформулируй, что изменилось в твоём понимании',body:'Продолжи три фразы из технологической карты урока: «У меня получилось…», «Меня удивило…», «Теперь я умею…».',note:'Хороший итог — уметь своими словами объяснить, что такое звено, вершина и как найти длину ломаной.',sourceTag:'Методическое пособие · урок 8'},
  {id:'l8-summary',kind:'summary',eyebrow:'Итог основной части',title:'Ломаная стала понятной системой отрезков',body:'Ты научился распознавать ломаную, называть её вершины и звенья, находить длину, отличать открытую ломаную от замкнутой и решать задачи с последовательными точками. Теперь впереди обязательная практика и итоговое объяснение своими словами.',note:'Урок получит статус «завершён» только после обязательной практики и итоговой рефлексии.'}
];

const empty:Saved={version:2,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonEightStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}
function pointChain(points:string[],caption:string){return <div className="l7-chain-model">{points.flatMap((point,index)=>index===points.length-1?[<span key={`${point}-${index}`}>{point}</span>]:[<span key={`${point}-${index}`}>{point}</span>,<i key={`line-${index}`}/>])}<strong>{caption}</strong></div>}
function pointsRule(count:number,caption:string){return <div className="polyline-points-rule"><div>{Array.from({length:count},(_,index)=><span key={index}/>)}</div><strong>{caption}</strong></div>}
function unitModel(left:string,right:string,result:string){return <div className="polyline-unit-model"><span>{left}</span><b>+</b><span>{right}</span><b>→</b><strong>{result}</strong></div>}

export function PolylineLessonPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
  const stage=lessonEightStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l8-q1','l8-q2','l8-q3','l8-q4','l8-q5'];const practice=['l8-p1','l8-p2','l8-p3','l8-p4','l8-p5','l8-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonEightStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===8&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonEightStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:8}}))}
  const model=useMemo(()=>{
    if(['l8-story','l8-definition','l8-recognize'].includes(stage.id))return <div className="polyline-board open"><span className="p a">A</span><span className="p b">B</span><span className="p c">C</span><span className="p d">D</span><i className="s ab"/><i className="s bc"/><i className="s cd"/><strong>AB → BC → CD · соседние звенья меняют направление</strong></div>;
    if(['l8-parts','l8-links'].includes(stage.id))return <div className="polyline-board labeled"><span className="p a">A</span><span className="p b">B</span><span className="p c">C</span><span className="p d">D</span><span className="p e">E</span><i className="s ab"/><i className="s bc"/><i className="s cd"/><i className="s de"/><strong>5 вершин · 4 звена</strong></div>;
    if(stage.id==='l8-length-rule')return <div className="polyline-sum"><div className="mini-zig"><i/><i/><i/></div><strong>длина ABCD = AB + BC + CD</strong></div>;
    if(stage.id==='l8-length-guided')return <div className="polyline-sum"><div className="mini-zig"><i/><i/><i/></div><strong>8 мм + 10 мм + 14 мм = 32 мм</strong></div>;
    if(stage.id==='l8-practice1')return <div className="polyline-sum"><div className="mini-zig"><i/><i/><i/></div><strong>AC 15 мм + CD 24 мм + DM 32 мм = 71 мм</strong></div>;
    if(stage.id==='l8-quiz1')return <div className="polyline-sum"><div className="mini-zig"><i/><i/><i/></div><strong>AB 7 см + BC 5 см + CD 8 см</strong></div>;
    if(['l8-closed','l8-closed-check','l8-quiz3'].includes(stage.id))return <div className="polyline-closed"><div><span>A</span><span>B</span><span>C</span><span>D</span><i/><i/><i/><i/></div><strong>маршрут ABCDA: начало A = конец A</strong></div>;
    if(stage.id==='l8-practice2')return pointChain(['A','B','C','D'],'AC = AB + BC; AD = AB + BD');
    if(stage.id==='l8-practice3')return pointsRule(7,'7 точек → 6 промежутков; 10 точек → 9 промежутков');
    if(stage.id==='l8-quiz5')return pointsRule(12,'12 точек → 11 соседних промежутков');
    if(stage.id==='l8-practice4')return <div className="polyline-ruler"><div><span>0</span><i/><span>5</span><i className="long"/><span>13</span></div><strong>3 см = 13 − 5 − 5: по 5 см от каждого конца отрезка 13 см</strong></div>;
    if(stage.id==='l8-challenge')return <div className="polyline-ruler"><div><span>0</span><i/><span>5</span><i className="long"/><span>13</span></div><strong>3 = 13 − 10 · 2 = 15 − 13 · 1 = 16 − 15, где 8 = 13 − 5 и 16 = 8 + 8</strong></div>;
    if(stage.id==='l8-practice5')return unitModel('28 мм','2 см = 20 мм','48 мм');
    if(stage.id==='l8-practice6')return unitModel('все звенья','одна единица','сумма с единицей');
    if(stage.id==='l8-quiz4')return unitModel('35 мм','4 см = 40 мм','75 мм');
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page segment-length-page polyline-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 8 из 175 · § 3</span><h1>Ломаная</h1><p>Новая геометрическая фигура по Мерзляку: вершины и звенья, длина ломаной, замкнутые ломаные и задачи на построение.</p></div><div className="lesson-duration">план · 40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonEightStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь определение ломаной, список звеньев и единицы измерения. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>основная часть</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>основная часть</small></div><div><span>Статус</span><b>Основная часть ✓</b><small>дальше — обязательная практика</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% основной части</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonEightStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}