import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'power'|'product'|'order'|'verify'|'challenge'|'final';
export type LessonSeventyTwoStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-72-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyTwoStages:LessonSeventyTwoStage[]=[
{id:'l72-mission',kind:'story',eyebrow:'Урок 72 · § 20 · закрепление',title:'Степень должна стать рабочим инструментом',body:'На прошлом уроке появилась запись aⁿ. Теперь закрепляем вычисление степеней, подстановку значений букв, строгий порядок действий, перевод обычных чисел в степени заданного основания и перевод словесных формулировок в числовые выражения.',note:'Технологическая карта урока 72: устно № 3–5, с. 136; закрепление № 554, 556, 558; повторение № 560 (3–4), 562; домашний перенос § 20, № 555, 557, 559, доп. № 563.',visual:'mission'},
{id:'l72-oral-3',kind:'quiz',eyebrow:'Актуализация · устно № 3, с. 136',title:'Деление с остатком — быстрый разогрев',body:'Вася разложил 60 яблок на кучки по 8, и 4 яблока осталось.',activity:{id:'l72-p1',type:'input',prompt:'Сколько полных кучек получилось?',answer:'7',placeholder:'кучек',hint:'Из 60 убери остаток 4 и раздели оставшееся на 8.',explanation:'(60−4):8=7 кучек.'},visual:'verify',sourceExercise:'Устно № 3, с. 136'},
{id:'l72-oral-4',kind:'quiz',eyebrow:'Актуализация · устно № 4, с. 136',title:'Скорость по пройденному пути',body:'Маршрут 25 км. За 4 часа туристу осталось пройти 1 км.',activity:{id:'l72-p2',type:'input',prompt:'С какой скоростью шёл турист, км/ч?',answer:['6','6 км/ч'],placeholder:'км/ч',hint:'Сначала найди уже пройденный путь: 25−1.',explanation:'24:4=6 км/ч.'},visual:'verify',sourceExercise:'Устно № 4, с. 136'},
{id:'l72-oral-5',kind:'quiz',eyebrow:'Актуализация · устно № 5, с. 136',title:'Восстанови исходное количество',body:'После пересадки 2 кустов с первого участка на второй на каждом стало по 10 кустов.',activity:{id:'l72-p3',type:'input',prompt:'Сколько кустов было сначала на первом и втором участках? Запиши через запятую.',answer:['12,8','12;8'],placeholder:'первый, второй',hint:'Верни пересаженные 2 куста обратно.',explanation:'Сначала было 12 кустов на первом и 8 на втором.'},visual:'verify',sourceExercise:'Устно № 5, с. 136'},
{id:'l72-recall',kind:'model',eyebrow:'§ 20 · опорная карта',title:'Четыре правила перед практикой',body:'aⁿ — произведение n одинаковых множителей a; a — основание, n — показатель; a² — квадрат, a³ — куб, a¹=a. В числовом выражении сначала вычисляют степени, затем остальные действия по обычным правилам.',visual:'map'},
{id:'l72-power-fluency',kind:'guided',eyebrow:'Закрепление',title:'Степень сначала вычисли, потом используй',body:'Если вместо буквы подставлено число, сначала вычисли его степень. Только после этого выполняй умножение, деление, сложение или вычитание.',visual:'power'},
{id:'l72-order-rule',kind:'model',eyebrow:'§ 20 · порядок действий',title:'Скобки и степень меняют структуру выражения',body:'(6−2)² и 6²−2² — разные выражения. В первом случае квадрат относится ко всей разности, во втором — отдельно к числам 6 и 2.',visual:'order'},
{id:'l72-order-check',kind:'quiz',eyebrow:'Самопроверка',title:'Не потеряй границы основания',body:'Квадрат суммы — это степень всего выражения в скобках.',activity:{id:'l72-p4',type:'choice',prompt:'Какая запись означает «квадрат суммы чисел 8 и 7»?',options:['(8+7)²','8²+7²','8+7²','(8²+7)'],answer:'(8+7)²',hint:'Сначала должна образоваться сумма, затем весь результат возводится в квадрат.',explanation:'Квадрат суммы записывается (8+7)².'},visual:'order'},
{id:'l72-554-map',kind:'guided',eyebrow:'№ 554',title:'Подстановка в выражения со степенями',body:'№ 554 проверяет сразу три навыка: подставить значения букв, правильно вычислить степени и сохранить исходный порядок действий.',visual:'map',sourceExercise:'№ 554'},
{id:'l72-554-1',kind:'practice',eyebrow:'№ 554(1)',title:'16−c³ при c=2',body:'После подстановки получаем 16−2³.',activity:{id:'l72-p5',type:'input',prompt:'Найди значение выражения.',answer:'8',placeholder:'значение',hint:'2³=8.',explanation:'16−2³=16−8=8.'},visual:'verify',sourceExercise:'№ 554(1)'},
{id:'l72-554-2',kind:'practice',eyebrow:'№ 554(2)',title:'x³−x² при x=10',body:'Одинаковое основание имеет разные показатели — каждую степень вычисляем отдельно.',activity:{id:'l72-p6',type:'input',prompt:'Найди значение.',answer:'900',placeholder:'значение',hint:'10³=1000, 10²=100.',explanation:'1000−100=900.'},visual:'verify',sourceExercise:'№ 554(2)'},
{id:'l72-554-3',kind:'practice',eyebrow:'№ 554(3)',title:'15a² при a=4',body:'Сначала 4², затем умножение на коэффициент 15.',activity:{id:'l72-p7',type:'input',prompt:'Найди значение 15a².',answer:'240',placeholder:'значение',hint:'4²=16.',explanation:'15·16=240.'},visual:'order',sourceExercise:'№ 554(3)'},
{id:'l72-554-4',kind:'practice',eyebrow:'№ 554(4)',title:'a²b³ при a=6, b=10',body:'Вычисли обе степени, затем перемножь результаты.',activity:{id:'l72-p8',type:'input',prompt:'Найди значение a²b³.',answer:'36000',placeholder:'значение',hint:'6²=36, 10³=1000.',explanation:'36·1000=36000.'},visual:'order',sourceExercise:'№ 554(4)'},
{id:'l72-554-parentheses',kind:'model',eyebrow:'№ 554(5–8)',title:'Четыре почти одинаковые записи — четыре разных ответа',body:'Пункты 5–8 специально меняют скобки. Нельзя переносить их «по памяти»: нужно читать точную структуру каждого выражения.',note:'Для x=4 и y=2: x²=16, y²=4, x−y=2. Дальше различается только группировка действий.',visual:'challenge',sourceExercise:'№ 554(5–8)'},
{id:'l72-554-5',kind:'practice',eyebrow:'№ 554(5)',title:'(x²−y²):(x−y)',body:'И числитель, и делитель собраны скобками.',activity:{id:'l72-p9',type:'input',prompt:'Вычисли при x=4, y=2.',answer:'6',placeholder:'значение',hint:'(16−4):(4−2)=12:2.',explanation:'Ответ 6.'},visual:'verify',sourceExercise:'№ 554(5)'},
{id:'l72-554-6',kind:'practice',eyebrow:'№ 554(6)',title:'(x²−y²):x−y',body:'После деления на x отдельно вычитается y.',activity:{id:'l72-p10',type:'input',prompt:'Вычисли при x=4, y=2.',answer:'1',placeholder:'значение',hint:'(16−4):4−2=3−2.',explanation:'Ответ 1.'},visual:'verify',sourceExercise:'№ 554(6)'},
{id:'l72-554-7',kind:'practice',eyebrow:'№ 554(7)',title:'x²−y²:(x−y)',body:'Деление выполняется раньше вычитания.',activity:{id:'l72-p11',type:'input',prompt:'Вычисли при x=4, y=2.',answer:'14',placeholder:'значение',hint:'16−4:(4−2)=16−2.',explanation:'Ответ 14.'},visual:'verify',sourceExercise:'№ 554(7)'},
{id:'l72-554-8',kind:'practice',eyebrow:'№ 554(8)',title:'x²−y²:x−y',body:'После степеней сначала выполняется деление y²:x.',activity:{id:'l72-p12',type:'input',prompt:'Вычисли при x=4, y=2.',answer:'13',placeholder:'значение',hint:'16−4:4−2=16−1−2.',explanation:'Ответ 13.'},visual:'verify',sourceExercise:'№ 554(8)'},
{id:'l72-554-compare',kind:'model',eyebrow:'№ 554 · вывод',title:'Скобки — часть условия, а не украшение',body:'Пункты 5–8 дают соответственно 6, 1, 14 и 13. Такой разброс — лучший сигнал, почему структуру выражения нельзя угадывать по похожему виду.',visual:'map',sourceExercise:'№ 554(5–8)'},
{id:'l72-556-map',kind:'guided',eyebrow:'№ 556',title:'Теперь обратная задача: число → степень с основанием 3',body:'Нужно представить число как произведение одинаковых троек и определить, сколько множителей получилось.',visual:'product',sourceExercise:'№ 556'},
{id:'l72-556-a',kind:'practice',eyebrow:'№ 556(1–2)',title:'9 и 27 как степени тройки',body:'9=3·3, а 27=3·3·3.',activity:{id:'l72-p13',type:'input',prompt:'Запиши две степени через запятую.',answer:['3²,3³','3^2,3^3','3²;3³','3^2;3^3'],placeholder:'9, 27',hint:'Сосчитай множители 3.',explanation:'9=3², 27=3³.'},visual:'power',sourceExercise:'№ 556(1–2)'},
{id:'l72-556-b',kind:'practice',eyebrow:'№ 556(3–4)',title:'243 и 81 как степени тройки',body:'Проверяй последовательность: 3²=9, 3³=27, 3⁴=81, 3⁵=243.',activity:{id:'l72-p14',type:'input',prompt:'Запиши степени для 243 и 81 через запятую.',answer:['3⁵,3⁴','3^5,3^4','3⁵;3⁴','3^5;3^4'],placeholder:'243, 81',hint:'243 идёт после 81 в цепочке степеней 3.',explanation:'243=3⁵, 81=3⁴.'},visual:'power',sourceExercise:'№ 556(3–4)'},
{id:'l72-power-chain',kind:'model',eyebrow:'№ 556 · стратегия',title:'Цепочка степеней помогает видеть число, а не угадывать показатель',body:'Для основания 3 полезно держать цепочку 3¹=3, 3²=9, 3³=27, 3⁴=81, 3⁵=243. Важно понимать происхождение каждого следующего числа: оно в 3 раза больше предыдущего.',visual:'map'},
{id:'l72-558-map',kind:'guided',eyebrow:'№ 558',title:'Слова → математическая запись → значение',body:'№ 558 требует сначала точно перевести фразу в выражение. Только после этого можно считать.',visual:'map',sourceExercise:'№ 558'},
{id:'l72-558-1',kind:'practice',eyebrow:'№ 558(1)',title:'Сумма куба 5 и квадрата 8',body:'Запись: 5³+8².',activity:{id:'l72-p15',type:'input',prompt:'Найди значение.',answer:'189',placeholder:'значение',hint:'125+64.',explanation:'5³+8²=125+64=189.'},visual:'order',sourceExercise:'№ 558(1)'},
{id:'l72-558-2',kind:'practice',eyebrow:'№ 558(2)',title:'Разность квадратов 6 и 2',body:'Запись: 6²−2².',activity:{id:'l72-p16',type:'input',prompt:'Найди значение.',answer:'32',placeholder:'значение',hint:'36−4.',explanation:'6²−2²=32.'},visual:'order',sourceExercise:'№ 558(2)'},
{id:'l72-558-3',kind:'practice',eyebrow:'№ 558(3)',title:'Квадрат разности 6 и 2',body:'Здесь квадрат относится ко всей разности: (6−2)².',activity:{id:'l72-p17',type:'input',prompt:'Найди значение.',answer:'16',placeholder:'значение',hint:'Сначала 6−2=4.',explanation:'(6−2)²=4²=16.'},visual:'order',sourceExercise:'№ 558(3)'},
{id:'l72-558-4',kind:'practice',eyebrow:'№ 558(4)',title:'Разность куба 3 и квадрата 5',body:'Запись: 3³−5².',activity:{id:'l72-p18',type:'input',prompt:'Найди значение.',answer:'2',placeholder:'значение',hint:'27−25.',explanation:'3³−5²=2.'},visual:'order',sourceExercise:'№ 558(4)'},
{id:'l72-contrast',kind:'model',eyebrow:'№ 558 · ключевой контраст',title:'Разность квадратов ≠ квадрат разности',body:'6²−2²=32, а (6−2)²=16. Слова «разность квадратов» и «квадрат разности» задают принципиально разные выражения.',visual:'challenge',sourceExercise:'№ 558(2–3)'},
{id:'l72-560-map',kind:'guided',eyebrow:'Повторение · № 560(3–4)',title:'Вернёмся к уравнениям с делением',body:'Степени закрепили, теперь методичка возвращает старый навык: сначала найти значение выражения в знаменателе деления, затем восстановить x.',visual:'map',sourceExercise:'№ 560(3–4)'},
{id:'l72-560-3',kind:'practice',eyebrow:'№ 560(3)',title:'1344:(x+26)=32',body:'Делитель равен 1344:32.',activity:{id:'l72-p19',type:'input',prompt:'Найди x.',answer:'16',placeholder:'x',hint:'x+26=42.',explanation:'1344:32=42, поэтому x=16.'},visual:'verify',sourceExercise:'№ 560(3)'},
{id:'l72-560-4',kind:'practice',eyebrow:'№ 560(4)',title:'384:(51−5x)=24',body:'Сначала восстанови делитель, затем реши линейное уравнение.',activity:{id:'l72-p20',type:'input',prompt:'Найди x.',answer:'7',placeholder:'x',hint:'51−5x=384:24=16.',explanation:'5x=35, поэтому x=7.'},visual:'verify',sourceExercise:'№ 560(4)'},
{id:'l72-562-map',kind:'model',eyebrow:'Повторение · № 562',title:'Логика разрядов: ровно одно совпадение с каждым числом',body:'Ищем трёхзначное число, у которого с каждым из 652, 153 и 673 совпадает ровно один разряд, а два других разряда не совпадают.',visual:'challenge',sourceExercise:'№ 562'},
{id:'l72-562',kind:'challenge',eyebrow:'№ 562',title:'Проверь все три условия одновременно',body:'Подходящий ответ должен иметь ровно одну совпадающую позицию с каждым из трёх данных чисел.',activity:{id:'l72-p21',type:'input',prompt:'Какое число задумал Вася?',answer:'172',placeholder:'трёхзначное число',hint:'Проверь 172: с 652 совпадает разряд единиц 2; с 153 — разряд сотен 1; с 673 — разряд десятков 7.',explanation:'Ответ 172: с каждым из трёх чисел совпадает ровно одна позиция.'},visual:'challenge',sourceExercise:'№ 562'},
{id:'l72-transfer',kind:'model',eyebrow:'Домашний перенос',title:'Тот же навык — новые числа и формулировки',body:'По карте урока дома: § 20, № 555, 557, 559 и дополнительное № 563. № 555 продолжает подстановку в выражения, № 557 — запись чисел степенями двойки, № 559 — перевод словесных формулировок в выражения.',note:'№ 563 оставлен как дополнительный источник задания и не подменяется придуманной формулировкой.',visual:'map',sourceExercise:'№ 555, 557, 559; доп. № 563'},
{id:'l72-summary',kind:'summary',eyebrow:'Итог урока 72',title:'§ 20 закреплён: степень, скобки и порядок действий работают вместе',body:'Ты умеешь вычислять выражения со степенями после подстановки, различать похожие записи со скобками, представлять числа степенями заданного основания и переводить фразы «разность квадратов» и «квадрат разности» в разные математические выражения.',note:'Обязательная практика: 20 задач / 50 ответов. Урок 73 — контрольная работа № 4 — остаётся заблокирован до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'aⁿ',map:'§20',power:'3ⁿ',product:'3·3·…',order:'1 → n',verify:'✓',challenge:'★',final:'72'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='power'?'степень без угадывания':kind==='product'?'одинаковые множители':kind==='order'?'сначала степень':kind==='verify'?'проверь вычисление':kind==='challenge'?'читай структуру точно':'закрепление степени · § 20'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyTwoStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function PowerReinforcementPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyTwoStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyTwoStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==72||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyTwoStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyTwoStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player power-reinforcement-player" data-lesson-number="72" data-source-reference="Мерзляк § 20 · технологическая карта урока 72 · № 554, 556, 558; повторение № 560 (3–4), 562" data-source-exercise-range="554,556,558,560,562"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyTwoStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSeventyTwoStages.length-1||!canContinue}>{saved.stageIndex===lessonSeventyTwoStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
