import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'pyramid'|'base'|'faces'|'edges'|'classify'|'net'|'tetra'|'polyhedron'|'source'|'train'|'verify'|'final';
export type LessonEightyStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-80-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonEightyStages:LessonEightyStage[]=[
{id:'l80-mission',kind:'story',eyebrow:'Урок 80 · § 22 · пирамида',title:'От основания — к общей вершине',body:'Сегодня завершаем § 22. У пирамиды есть одно основание, а все боковые грани — треугольники, сходящиеся в общей вершине. Научимся читать это пространственное тело и его развёртку.',note:'Технологическая карта урока 80: устно № 5–6, с. 150; теория § 22, с. 148–149; № 604; повторение № 614; вопросы 14–18; домашнее № 605, 611, 615.',visual:'mission'},
{id:'l80-oral5-model',kind:'guided',eyebrow:'Актуализация · устно № 5, с. 150',title:'Центнеры переводим до деления',body:'В магазине 6 ц яблок раскладывают по 12 кг в ящик. Сначала приводим массу к килограммам: 1 ц = 100 кг.',visual:'verify',sourceExercise:'Устно № 5, с. 150'},
{id:'l80-oral5-kg',kind:'practice',eyebrow:'Устно № 5 · шаг 1',title:'Шесть центнеров',body:'6·100 кг.',activity:{id:'l80-p1',type:'input',prompt:'6 ц = ? кг',answer:'600',placeholder:'кг',hint:'1 ц = 100 кг.',explanation:'6 ц = 600 кг.'},visual:'verify',sourceExercise:'Устно № 5, с. 150'},
{id:'l80-oral5-boxes',kind:'practice',eyebrow:'Устно № 5 · шаг 2',title:'По 12 кг в каждый ящик',body:'Количество ящиков находим делением всей массы на массу одного ящика.',activity:{id:'l80-p2',type:'input',prompt:'600:12 = ? ящиков',answer:'50',placeholder:'ящиков',hint:'12·50=600.',explanation:'Заполнили 50 ящиков.'},visual:'verify',sourceExercise:'Устно № 5, с. 150'},
{id:'l80-oral6-model',kind:'guided',eyebrow:'Актуализация · устно № 6, с. 150',title:'Сравниваем площади квадратов',body:'Нужно узнать, во сколько раз площадь квадрата со стороной 6 см больше площади квадрата со стороной 2 см. Сначала вычислим обе площади.',visual:'verify',sourceExercise:'Устно № 6, с. 150'},
{id:'l80-oral6-large',kind:'practice',eyebrow:'Устно № 6 · большой квадрат',title:'Сторона 6 см',body:'S=a².',activity:{id:'l80-p3',type:'input',prompt:'6² = ? см²',answer:'36',placeholder:'см²',hint:'6·6.',explanation:'Площадь 36 см².'},visual:'verify',sourceExercise:'Устно № 6, с. 150'},
{id:'l80-oral6-small',kind:'practice',eyebrow:'Устно № 6 · малый квадрат',title:'Сторона 2 см',body:'S=a².',activity:{id:'l80-p4',type:'input',prompt:'2² = ? см²',answer:'4',placeholder:'см²',hint:'2·2.',explanation:'Площадь 4 см².'},visual:'verify',sourceExercise:'Устно № 6, с. 150'},
{id:'l80-oral6-ratio',kind:'practice',eyebrow:'Устно № 6 · сравнение',title:'Во сколько раз?',body:'Сравниваем площади делением.',activity:{id:'l80-p5',type:'input',prompt:'36:4 = ?',answer:'9',hint:'Площадь меняется как квадрат стороны.',explanation:'Площадь большего квадрата в 9 раз больше.'},visual:'verify',sourceExercise:'Устно № 6, с. 150'},
{id:'l80-pyramid-theory',kind:'model',eyebrow:'§ 22 · с. 148–149',title:'Из чего состоит поверхность пирамиды?',body:'Поверхность пирамиды состоит из основания и боковых граней — треугольников, имеющих общую вершину.',visual:'pyramid',sourceExercise:'§ 22, с. 148–149 · вопрос 14'},
{id:'l80-surface-check',kind:'quiz',eyebrow:'Вопрос 14 · с. 150',title:'Поверхность пирамиды',body:'У основания форма зависит от вида пирамиды, а боковые грани всегда треугольные.',activity:{id:'l80-p6',type:'choice',prompt:'Какими фигурами являются боковые грани пирамиды?',options:['треугольниками','кругами','только квадратами'],answer:'треугольниками',hint:'Все они имеют общую вершину пирамиды.',explanation:'Боковые грани пирамиды — треугольники.'},visual:'faces',sourceExercise:'Вопрос 14, с. 150'},
{id:'l80-apex-model',kind:'model',eyebrow:'§ 22 · вершина',title:'Общая вершина боковых граней',body:'Общую вершину всех боковых треугольных граней называют вершиной пирамиды.',visual:'pyramid',sourceExercise:'§ 22, с. 148–149 · вопрос 16'},
{id:'l80-apex-term',kind:'quiz',eyebrow:'Вопрос 16 · с. 150',title:'Назови элемент',body:'Все боковые грани сходятся в одной точке.',activity:{id:'l80-p7',type:'choice',prompt:'Как называется эта общая точка?',options:['вершина пирамиды','центр основания','середина ребра'],answer:'вершина пирамиды',hint:'Это термин из определения пирамиды.',explanation:'Общая вершина боковых граней — вершина пирамиды.'},visual:'pyramid',sourceExercise:'Вопрос 16, с. 150'},
{id:'l80-base-model',kind:'model',eyebrow:'§ 22 · основание',title:'Одна грань играет особую роль',body:'Многоугольник, к которому примыкают все боковые треугольники, служит основанием пирамиды. Именно по числу его сторон классифицируют пирамиды.',visual:'base',sourceExercise:'§ 22, с. 148–149'},
{id:'l80-base-role',kind:'quiz',eyebrow:'§ 22 · основание',title:'По чему называют пирамиду?',body:'Треугольное основание даёт треугольную пирамиду, четырёхугольное — четырёхугольную.',activity:{id:'l80-p8',type:'choice',prompt:'Что определяет название пирамиды?',options:['число сторон основания','длина бокового ребра','площадь поверхности'],answer:'число сторон основания',hint:'Смотри на многоугольник в основании.',explanation:'Пирамиды классифицируют по количеству сторон основания.'},visual:'classify',sourceExercise:'§ 22 · вопрос 15'},
{id:'l80-lateral-faces-model',kind:'model',eyebrow:'§ 22 · боковые грани',title:'Треугольники вокруг основания',body:'Каждой стороне основания соответствует одна боковая треугольная грань, соединяющая эту сторону с вершиной пирамиды.',visual:'faces',sourceExercise:'§ 22, с. 148–149'},
{id:'l80-lateral-shape',kind:'quiz',eyebrow:'§ 22 · связь элементов',title:'Форма боковой грани',body:'Основание может быть разным многоугольником, но боковая грань устроена одинаково.',activity:{id:'l80-p9',type:'choice',prompt:'Боковая грань пирамиды — это…',options:['треугольник','окружность','отрезок'],answer:'треугольник',hint:'Она содержит вершину пирамиды и одну сторону основания.',explanation:'Каждая боковая грань — треугольник.'},visual:'faces'},
{id:'l80-base-edges',kind:'quiz',eyebrow:'Вопрос 17 · с. 150',title:'Рёбра основания',body:'Стороны многоугольника-основания получают отдельное название.',activity:{id:'l80-p10',type:'choice',prompt:'Что называют рёбрами основания пирамиды?',options:['стороны основания','все высоты треугольников','только боковые стороны'],answer:'стороны основания',hint:'Термин относится к сторонам основания.',explanation:'Стороны основания пирамиды называют рёбрами основания.'},visual:'edges',sourceExercise:'Вопрос 17, с. 150'},
{id:'l80-lateral-edges',kind:'quiz',eyebrow:'Вопрос 18 · с. 150',title:'Боковые рёбра',body:'Это стороны боковых граней, которые не лежат в основании.',activity:{id:'l80-p11',type:'choice',prompt:'Что называют боковыми рёбрами?',options:['стороны боковых граней, не принадлежащие основанию','стороны основания','любые диагонали'],answer:'стороны боковых граней, не принадлежащие основанию',hint:'Они идут от вершины пирамиды к вершинам основания.',explanation:'Это стороны боковых граней, не принадлежащие основанию.'},visual:'edges',sourceExercise:'Вопрос 18, с. 150'},
{id:'l80-classify-model',kind:'model',eyebrow:'§ 22 · классификация',title:'Название читает основание',body:'По количеству сторон основания различают треугольные, четырёхугольные, пятиугольные пирамиды и т. д.',visual:'classify',sourceExercise:'§ 22, с. 149 · вопрос 15'},
{id:'l80-triangular-name',kind:'practice',eyebrow:'Классификация · 3 стороны',title:'Треугольное основание',body:'В основании три стороны.',activity:{id:'l80-p12',type:'choice',prompt:'Как называется такая пирамида?',options:['треугольная','четырёхугольная','пятиугольная'],answer:'треугольная',hint:'Название повторяет тип основания.',explanation:'Это треугольная пирамида.'},visual:'classify',sourceExercise:'Вопрос 15, с. 150'},
{id:'l80-quadrangular-name',kind:'practice',eyebrow:'Классификация · 4 стороны',title:'Четырёхугольное основание',body:'В основании четыре стороны.',activity:{id:'l80-p13',type:'choice',prompt:'Как называется такая пирамида?',options:['четырёхугольная','треугольная','пятиугольная'],answer:'четырёхугольная',hint:'Четыре стороны основания.',explanation:'Это четырёхугольная пирамида.'},visual:'classify',sourceExercise:'Вопрос 15, с. 150'},
{id:'l80-pentagonal-name',kind:'practice',eyebrow:'Классификация · 5 сторон',title:'Пятиугольное основание',body:'В основании пять сторон.',activity:{id:'l80-p14',type:'choice',prompt:'Как называется такая пирамида?',options:['пятиугольная','четырёхугольная','треугольная'],answer:'пятиугольная',hint:'Пять сторон основания.',explanation:'Это пятиугольная пирамида.'},visual:'classify',sourceExercise:'§ 22, с. 149'},
{id:'l80-triangular-special',kind:'model',eyebrow:'§ 22 · особый случай',title:'У треугольной пирамиды четыре треугольные грани',body:'Поверхность треугольной пирамиды состоит из четырёх треугольников. Любой из этих треугольников может служить основанием — это уникальное свойство среди пирамид.',visual:'tetra',sourceExercise:'§ 22, с. 149'},
{id:'l80-triangular-faces',kind:'practice',eyebrow:'Треугольная пирамида',title:'Считаем все грани',body:'Одно треугольное основание и три боковые треугольные грани.',activity:{id:'l80-p15',type:'input',prompt:'Сколько всего граней?',answer:'4',hint:'1+3.',explanation:'Всего 4 треугольные грани.'},visual:'tetra',sourceExercise:'§ 22, с. 149'},
{id:'l80-any-base',kind:'quiz',eyebrow:'§ 22 · уникальное свойство',title:'Можно перевернуть роль основания',body:'У треугольной пирамиды каждая грань — треугольник.',activity:{id:'l80-p16',type:'choice',prompt:'Может ли любая её грань служить основанием?',options:['да','нет'],answer:'да',hint:'Учебник отмечает это как единственный такой вид пирамиды.',explanation:'Да. Любая грань треугольной пирамиды может служить основанием.'},visual:'tetra',sourceExercise:'§ 22, с. 149'},
{id:'l80-net-model',kind:'model',eyebrow:'§ 22 · развёртка',title:'Пирамиду тоже можно раскрыть на плоскость',body:'Развёртка показывает все грани пирамиды в одной плоской фигуре. Для четырёхугольной пирамиды учебник показывает развёртку из квадрата и четырёх равных равнобедренных треугольников.',note:'Методическое пособие рекомендует рассматривать реальные модели и изготавливать пирамиды из развёрток — это ключевой приём развития пространственного воображения.',visual:'net',sourceExercise:'§ 22 · рис. 166'},
{id:'l80-net-pieces',kind:'practice',eyebrow:'Развёртка четырёхугольной пирамиды',title:'Один квадрат и четыре треугольника',body:'Считаем все части развёртки.',activity:{id:'l80-p17',type:'input',prompt:'Сколько многоугольников в такой развёртке?',answer:'5',hint:'1 квадрат + 4 треугольника.',explanation:'Всего 5 многоугольников.'},visual:'net',sourceExercise:'§ 22 · рис. 166'},
{id:'l80-tetra-model',kind:'model',eyebrow:'§ 22 · правильный тетраэдр',title:'Четыре равносторонних треугольника',body:'Из четырёх равных равносторонних треугольников можно сделать треугольную пирамиду, у которой все грани равносторонние. Такую пирамиду называют правильным тетраэдром.',visual:'tetra',sourceExercise:'§ 22 · рис. 167'},
{id:'l80-tetra-count',kind:'practice',eyebrow:'Правильный тетраэдр',title:'Количество граней',body:'Название «тетраэдр» связано с четырьмя гранями.',activity:{id:'l80-p18',type:'input',prompt:'Сколько граней у правильного тетраэдра?',answer:'4',hint:'Он является треугольной пирамидой.',explanation:'У тетраэдра 4 грани.'},visual:'tetra',sourceExercise:'§ 22, с. 149'},
{id:'l80-tetra-shape',kind:'quiz',eyebrow:'Правильный тетраэдр',title:'Какие у него грани?',body:'В рассматриваемой модели все четыре грани равны.',activity:{id:'l80-p19',type:'choice',prompt:'Из каких фигур состоят его грани?',options:['равносторонних треугольников','квадратов','прямоугольников'],answer:'равносторонних треугольников',hint:'Рис. 167 состоит из четырёх одинаковых равносторонних треугольников.',explanation:'Все грани — равносторонние треугольники.'},visual:'tetra',sourceExercise:'§ 22 · рис. 167'},
{id:'l80-polyhedron-model',kind:'model',eyebrow:'§ 22 · обобщение',title:'Пирамида — многогранник',body:'Многогранник — геометрическое тело, поверхность которого состоит из многоугольников. Пирамида является одним из видов многогранника.',note:'Не каждое геометрическое тело является многогранником: поверхность многогранника должна быть составлена из многоугольников.',visual:'polyhedron',sourceExercise:'§ 22, с. 148–149'},
{id:'l80-polyhedron-check',kind:'quiz',eyebrow:'§ 22 · связь понятий',title:'Проверка определения',body:'У пирамиды основание — многоугольник, боковые грани — треугольники.',visual:'polyhedron',sourceExercise:'§ 22'},
{id:'l80-604-source',kind:'guided',eyebrow:'№ 604 · рис. 172',title:'Читаем пирамиду MABC',body:'На рисунке 172 изображена пирамида MABC. Основание — ABC, вершина пирамиды — M, боковые грани — MAB, MBC, MAC, боковые рёбра — MA, MB, MC, рёбра основания — AB, BC, AC.',note:'Здесь используются буквенные обозначения исходного рисунка 172 учебника; они не заменены придуманной схемой.',visual:'source',sourceExercise:'№ 604 · рис. 172'},
{id:'l80-604-base',kind:'practice',eyebrow:'№ 604 · пункт 1',title:'Основание пирамиды MABC',body:'Выбери грань, которая не содержит вершину M.',activity:{id:'l80-p20',type:'input',prompt:'Запиши основание тремя буквами',answer:['ABC','ACB','BCA','BAC','CAB','CBA'],placeholder:'например ABC',hint:'Это треугольник из точек A, B и C.',explanation:'Основание — треугольник ABC.'},visual:'source',sourceExercise:'№ 604(1)'},
{id:'l80-614-train',kind:'practice',eyebrow:'Повторение · № 614',title:'Два поезда в противоположных направлениях',body:'Первый поезд идёт с 16:00 до 24:00: 8·54=432 км. Второй идёт с 19:00 до 24:00, то есть 5 ч. Из общей дистанции 642 км ему осталось пройти 642−432=210 км.',activity:{id:'l80-p21',type:'input',prompt:'Скорость второго поезда = 210:5 = ? км/ч',answer:'42',placeholder:'км/ч',hint:'Сначала 642−432=210, затем раздели на 5 ч.',explanation:'Скорость второго поезда 42 км/ч.'},visual:'train',sourceExercise:'№ 614'},
{id:'l80-summary',kind:'summary',eyebrow:'Итог урока 80 · § 22 завершён',title:'Пирамида читается от основания к вершине',body:'Ты умеешь распознавать основание и вершину, различать рёбра основания и боковые рёбра, классифицировать пирамиды по основанию, понимать их развёртки и узнавать правильный тетраэдр. Пирамида — частный вид многогранника.',note:'Домашний маршрут по технологической карте: § 22, вопросы 14–18, № 605, 611, 615. Обязательная практика урока: 20 задач / ровно 50 ответов. Следующий урок 81 откроет § 23 — объём прямоугольного параллелепипеда.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'△',pyramid:'M△',base:'ABC',faces:'△△',edges:'↗',classify:'3·4·5',net:'✣',tetra:'△₄',polyhedron:'⬡',source:'№604',train:'54↔?',verify:'✓',final:'80'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='pyramid'?'боковые треугольники сходятся в одной вершине':kind==='base'?'основание определяет вид пирамиды':kind==='net'?'развёртка: поверхность на плоскости':kind==='tetra'?'4 равносторонних треугольника':kind==='polyhedron'?'поверхность состоит из многоугольников':'пирамида · § 22'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function PyramidPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==80||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player pyramid-player" data-lesson-number="80" data-source-reference="Мерзляк § 22 · технологическая карта урока 80 · устно 5–6 · № 604 · повторение № 614 · вопросы 14–18" data-source-exercise-range="604,614"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
