import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'division'|'equation'|'work'|'expression'|'verify'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-68-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyEightStages:Stage[]=[
{id:'l68-mission',kind:'story',eyebrow:'Урок 68 · § 19 · новое понятие',title:'Что делать, когда деление не заканчивается нацело?',body:'Начинаем § 19. Теперь деление должно описывать две величины: сколько полных групп получилось и сколько единиц осталось. Главная цель — понимать смысл неполного частного и остатка, а не просто запоминать запись.',note:'Технологическая карта урока 68: теория § 19; первичное закрепление № 521, 523, 525, 527; повторение № 545 (1, 2); домашний перенос № 522, 524, 526.',visual:'mission'},
{id:'l68-groups',kind:'model',eyebrow:'Смысл действия',title:'17 предметов раскладываем по 5',body:'Можно собрать 3 полные группы по 5 предметов: это 15 предметов. Ещё 2 предмета останутся. Поэтому 17 при делении на 5 даёт неполное частное 3 и остаток 2.',visual:'work'},
{id:'l68-terms',kind:'model',eyebrow:'Новые слова',title:'Четыре компонента одной записи',body:'В записи 17 = 5·3 + 2 число 17 — делимое, 5 — делитель, 3 — неполное частное, 2 — остаток. Неполное частное показывает число полных групп.',visual:'map'},
{id:'l68-formula',kind:'model',eyebrow:'Главная связь § 19',title:'Делимое восстанавливается точно',body:'Если a делят на b с неполным частным q и остатком r, то a = b·q + r. Эта формула — одновременно запись результата и способ проверки.',visual:'equation'},
{id:'l68-invariant',kind:'model',eyebrow:'Главное ограничение',title:'Остаток всегда меньше делителя',body:'Если r ≥ b, из остатка можно собрать ещё одну полную группу. Значит выбранное q было не максимальным. Поэтому при корректном делении 0 ≤ r < b.',visual:'verify'},
{id:'l68-exact',kind:'model',eyebrow:'Важный частный случай',title:'Деление нацело тоже имеет остаток',body:'30 : 5 = 6 означает 30 = 5·6 + 0. Деление нацело — это деление с остатком, где остаток равен нулю.',visual:'division'},
{id:'l68-small',kind:'model',eyebrow:'Ещё один важный случай',title:'Если делимое меньше делителя',body:'5 : 30. Ни одной полной группы по 30 собрать нельзя, поэтому q = 0, а всё делимое остаётся: r = 5. Получаем 5 = 30·0 + 5.',visual:'division'},
{id:'l68-warmup',kind:'quiz',eyebrow:'Проверка понимания',title:'Формула должна вернуть делимое',body:'47 : 5 даёт неполное частное 9 и остаток 2.',activity:{id:'l68-p1',type:'choice',prompt:'Какая запись правильно проверяет результат?',options:['47=5·9+2','47=5·2+9','47=9·2+5','47=5·10+2'],answer:'47=5·9+2',hint:'Делитель · неполное частное + остаток.',explanation:'5·9+2=45+2=47, а 2<5.'},visual:'verify'},
{id:'l68-521-map',kind:'guided',eyebrow:'№ 521',title:'Первое системное упражнение учебника',body:'№ 521 просит выполнить деление с остатком для девяти пар чисел. Для каждого примера ищи наибольшее произведение делителя, не превосходящее делимое, а затем вычисляй остаток.',note:'В уроке разбираем первые четыре пункта и один более крупный пример; остальные остаются для самостоятельного применения алгоритма.',visual:'division',sourceExercise:'№ 521'},
{id:'l68-521-1',kind:'practice',eyebrow:'№ 521(1)',title:'42 : 5',body:'5·8=40, а 5·9 уже больше 42.',activity:{id:'l68-p2',type:'input',prompt:'Запиши q и r двумя числами: q, r',answer:['8,2','8;2','8 2'],placeholder:'например: 8, 2',hint:'Остаток = 42−40.',explanation:'q=8, r=2: 42=5·8+2, 2<5.'},visual:'division',sourceExercise:'№ 521(1)'},
{id:'l68-521-2',kind:'practice',eyebrow:'№ 521(2)',title:'592 : 24',body:'Ищи ближайшее произведение 24, которое не превосходит 592.',activity:{id:'l68-p3',type:'input',prompt:'Запиши q и r: q, r',answer:['24,16','24;16','24 16'],placeholder:'q, r',hint:'24·24=576.',explanation:'592=24·24+16; 16<24.'},visual:'division',sourceExercise:'№ 521(2)'},
{id:'l68-521-3',kind:'practice',eyebrow:'№ 521(3)',title:'428 : 37',body:'37·11=407, а 37·12=444 — уже слишком много.',activity:{id:'l68-p4',type:'input',prompt:'Запиши q и r: q, r',answer:['11,21','11;21','11 21'],placeholder:'q, r',hint:'428−407=21.',explanation:'428=37·11+21; 21<37.'},visual:'division',sourceExercise:'№ 521(3)'},
{id:'l68-521-4',kind:'practice',eyebrow:'№ 521(4)',title:'684 : 30',body:'30·22=660; следующая полная группа дала бы 690.',activity:{id:'l68-p5',type:'input',prompt:'Запиши q и r: q, r',answer:['22,24','22;24','22 24'],placeholder:'q, r',hint:'684−660=24.',explanation:'684=30·22+24; 24<30.'},visual:'division',sourceExercise:'№ 521(4)'},
{id:'l68-521-check',kind:'practice',eyebrow:'№ 521 · проверка',title:'Остаток восстанавливает точное число',body:'Для 684 : 30 мы получили q=22.',activity:{id:'l68-p6',type:'input',prompt:'Найди r в равенстве 684=30·22+r.',answer:'24',placeholder:'r',hint:'Вычти 30·22 из 684.',explanation:'r=24, и 24<30.'},visual:'verify',sourceExercise:'№ 521(4)'},
{id:'l68-521-hard',kind:'practice',eyebrow:'№ 521(7)',title:'3 196 : 74',body:'Проверяем, что алгоритм работает и на многозначных числах.',activity:{id:'l68-p7',type:'input',prompt:'Запиши q и r: q, r',answer:['43,14','43;14','43 14'],placeholder:'q, r',hint:'74·43=3182.',explanation:'3196=74·43+14; 14<74.'},visual:'division',sourceExercise:'№ 521(7)'},
{id:'l68-523-ten-model',kind:'model',eyebrow:'№ 523(1)',title:'Деление на 10: остаток уже виден в записи числа',body:'Каждые 10 единиц образуют полную десятку. Поэтому при делении натурального числа на 10 остаток равен последней цифре. Это не трюк, а следствие разрядной записи.',visual:'map',sourceExercise:'№ 523(1)'},
{id:'l68-523-ten-31',kind:'practice',eyebrow:'№ 523(1)',title:'31 : 10',body:'Три полных десятка и ещё одна единица.',activity:{id:'l68-p8',type:'input',prompt:'Какой остаток?',answer:'1',placeholder:'r',hint:'Посмотри на последнюю цифру.',explanation:'31=10·3+1.'},visual:'division',sourceExercise:'№ 523(1)'},
{id:'l68-523-ten-1596',kind:'practice',eyebrow:'№ 523(1)',title:'1 596 : 10',body:'Полные десятки забирают все цифры, кроме единиц.',activity:{id:'l68-p9',type:'input',prompt:'Какой остаток?',answer:'6',placeholder:'r',hint:'Остаток при делении на 10 — цифра единиц.',explanation:'1596=10·159+6.'},visual:'division',sourceExercise:'№ 523(1)'},
{id:'l68-523-ten-240750',kind:'practice',eyebrow:'№ 523(1)',title:'240 750 : 10',body:'Число оканчивается нулём.',activity:{id:'l68-p10',type:'input',prompt:'Какой остаток?',answer:'0',placeholder:'r',hint:'Если последняя цифра 0, число делится на 10 нацело.',explanation:'Остаток 0: это деление нацело.'},visual:'division',sourceExercise:'№ 523(1)'},
{id:'l68-523-five-model',kind:'model',eyebrow:'№ 523(2)',title:'При делении на 5 остатки повторяются циклом',body:'Для делителя 5 возможны только 0, 1, 2, 3, 4. У чисел, оканчивающихся на 0 или 5, остаток равен 0; для остальных последнюю цифру можно разложить относительно ближайшего меньшего кратного 5.',visual:'map',sourceExercise:'№ 523(2)'},
{id:'l68-523-five-86',kind:'practice',eyebrow:'№ 523(2)',title:'86 : 5',body:'Ближайшее меньшее кратное 5 — 85.',activity:{id:'l68-p11',type:'input',prompt:'Какой остаток?',answer:'1',placeholder:'r',hint:'86−85.',explanation:'86=5·17+1.'},visual:'division',sourceExercise:'№ 523(2)'},
{id:'l68-523-five-235',kind:'practice',eyebrow:'№ 523(2)',title:'235 : 5',body:'Последняя цифра — 5.',activity:{id:'l68-p12',type:'input',prompt:'Какой остаток?',answer:'0',placeholder:'r',hint:'235 делится на 5 нацело.',explanation:'235=5·47+0.'},visual:'division',sourceExercise:'№ 523(2)'},
{id:'l68-525-model',kind:'model',eyebrow:'№ 525',title:'Какие остатки вообще возможны?',body:'При делении на b остаток может принимать все целые значения от 0 до b−1. Число b уже не может быть остатком: из него образуется ещё одна полная группа.',visual:'map',sourceExercise:'№ 525'},
{id:'l68-525-seven',kind:'quiz',eyebrow:'№ 525(1)',title:'Деление на 7',body:'Перечисляем все допустимые остатки.',activity:{id:'l68-p13',type:'choice',prompt:'Какой список полный?',options:['0,1,2,3,4,5,6','1,2,3,4,5,6,7','0,1,2,3,4,5,6,7','0,7'],answer:'0,1,2,3,4,5,6',hint:'Начинаем с 0 и заканчиваем на b−1.',explanation:'Для b=7 возможны остатки 0–6.'},visual:'verify',sourceExercise:'№ 525(1)'},
{id:'l68-525-thirteen',kind:'practice',eyebrow:'№ 525(2)',title:'Деление на 13',body:'Не нужно выписывать весь список, если спрашивают границу.',activity:{id:'l68-p14',type:'input',prompt:'Каков наибольший возможный остаток?',answer:'12',placeholder:'максимальный r',hint:'b−1.',explanation:'При делении на 13: 0≤r<13, значит максимум 12.'},visual:'verify',sourceExercise:'№ 525(2)'},
{id:'l68-525-twentyfour',kind:'practice',eyebrow:'№ 525(3)',title:'Деление на 24',body:'Та же закономерность для более крупного делителя.',activity:{id:'l68-p15',type:'input',prompt:'Каков наибольший возможный остаток?',answer:'23',placeholder:'максимальный r',hint:'24−1.',explanation:'Максимальный остаток равен 23.'},visual:'verify',sourceExercise:'№ 525(3)'},
{id:'l68-527-model',kind:'guided',eyebrow:'№ 527',title:'Блокнот стоит 130 р. Сколько можно купить на 700 р.?',body:'Здесь неполное частное имеет жизненный смысл: число полностью оплаченных блокнотов. Остаток — деньги, которых уже недостаточно на ещё один блокнот.',note:'Точное условие учебника: «Блокнот стоит 130 р. Сколько блокнотов можно купить на 700 р.?»',visual:'work',sourceExercise:'№ 527'},
{id:'l68-527-count',kind:'practice',eyebrow:'№ 527 · неполное частное',title:'Сколько полных покупок?',body:'130·5=650, а 130·6=780>700.',activity:{id:'l68-p16',type:'input',prompt:'Сколько блокнотов можно купить?',answer:['5','5 блокнотов'],placeholder:'блокнотов',hint:'Нужна максимальная целая покупка, не превышающая 700 р.',explanation:'Можно купить 5 блокнотов.'},visual:'work',sourceExercise:'№ 527'},
{id:'l68-527-money',kind:'practice',eyebrow:'№ 527 · остаток',title:'Что осталось после покупки?',body:'Пять блокнотов стоят 650 р.',activity:{id:'l68-p17',type:'input',prompt:'Сколько рублей останется?',answer:['50','50 р','50 рублей'],placeholder:'руб.',hint:'700−650.',explanation:'Останется 50 р.; 50<130.'},visual:'work',sourceExercise:'№ 527'},
{id:'l68-527-check',kind:'quiz',eyebrow:'№ 527 · формула',title:'Записываем модель целиком',body:'Покупка должна удовлетворять общей формуле деления с остатком.',activity:{id:'l68-p18',type:'choice',prompt:'Какая запись верна?',options:['700=130·5+50','700=130·50+5','700=130·6+50','700=5·50+130'],answer:'700=130·5+50',hint:'Цена · число блокнотов + оставшиеся деньги.',explanation:'700=650+50, и 50<130.'},visual:'verify',sourceExercise:'№ 527'},
{id:'l68-545-source',kind:'guided',eyebrow:'Повторение · № 545(1, 2)',title:'Не теряем навыки предыдущей темы',body:'Выполни пункты 1–2 упражнения № 545 непосредственно по учебнику. Формулировку здесь не реконструируем: этот этап фиксирует точный маршрут технологической карты и отделяет исходное упражнение от дополнительной тренировки ниже.',visual:'work',sourceExercise:'№ 545(1, 2)'},
{id:'l68-repeat-a',kind:'practice',eyebrow:'Связанное повторение',title:'Деление нацело — случай r=0',body:'Повтори обычное деление и сразу переведи его на новый язык.',activity:{id:'l68-p19',type:'input',prompt:'960 : 32. Каково неполное частное?',answer:'30',placeholder:'q',hint:'32·30=960.',explanation:'q=30, r=0: 960=32·30+0.'},visual:'division'},
{id:'l68-repeat-b',kind:'practice',eyebrow:'Связанное повторение',title:'Делимое меньше делителя',body:'Проверим особый случай без угадывания.',activity:{id:'l68-p20',type:'input',prompt:'5 : 30. Запиши q и r: q, r',answer:['0,5','0;5','0 5'],placeholder:'q, r',hint:'Полной группы из 30 нет ни одной.',explanation:'q=0, r=5: 5=30·0+5.'},visual:'division'},
{id:'l68-error',kind:'quiz',eyebrow:'Лаборатория ошибок',title:'Правильного равенства недостаточно — остаток обязан быть мал',body:'Для 29 : 6 можно написать разные арифметически верные суммы, но только одна является корректным результатом деления с остатком.',activity:{id:'l68-p21',type:'choice',prompt:'Какая запись корректна?',options:['29=6·4+5','29=6·3+11','29=6·2+17','29=6·1+23'],answer:'29=6·4+5',hint:'Проверь не только равенство, но и условие r<6.',explanation:'5<6. В остальных вариантах из остатка можно собрать ещё полную шестёрку.'},visual:'error'},
{id:'l68-transfer',kind:'model',eyebrow:'Перенос и рефлексия',title:'Алгоритм, который нужно унести с урока',body:'1) Найди максимальное q, для которого b·q≤a. 2) Вычисли r=a−b·q. 3) Проверь 0≤r<b. 4) Запиши a=b·q+r. Для домашнего переноса методичка даёт № 522, 524, 526 и вопросы 1–5 § 19. Перед уроком 69 сформулируй своими словами, почему остаток не может быть равен делителю.',visual:'map'},
{id:'l68-summary',kind:'summary',eyebrow:'Итог урока 68',title:'Деление с остатком — это точная модель полных групп и остатка',body:'Ты ввёл неполное частное и остаток, освоил формулу a=b·q+r и ограничение r<b, разобрал деление нацело и случай a<b, выполнил маршрут № 521, 523, 525, 527 и сохранил повторение № 545(1,2). Теперь обязательная практика проверит 20 задач и 50 ответов.',note:'Следующий урок 69 продолжит § 19 уже как закрепление навыка.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'÷r',map:'0≤r<b',division:'q,r',equation:'a=bq+r',work:'●●●',expression:'r',verify:'✓',error:'!',challenge:'★',final:'68'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='division'?'неполное частное + остаток':kind==='equation'?'делитель · q + r':kind==='verify'?'проверка r < b':kind==='work'?'полные группы и остаток':kind==='error'?'равенство + ограничение':'деление с остатком · смысл · проверка'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSixtyEightStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function RemainderDivisionPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSixtyEightStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyEightStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==68||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSixtyEightStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSixtyEightStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player remainder-division-player" data-lesson-number="68" data-source-reference="Мерзляк § 19 · технологическая карта урока 68 · № 521, 523, 525, 527; повторение № 545 (1, 2)" data-source-exercise-range="521,523,525,527,545"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyEightStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyEightStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyEightStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
