import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'volume'|'parts'|'unit'|'units'|'cubes'|'convert'|'source'|'verify'|'next'|'final';
export type LessonEightyOneStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-81-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[³^]/g,'3').replace(/[²]/g,'2').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actualNumber=numericValue(value);const expectedNumber=numericValue(item);if(actualNumber!==null&&expectedNumber!==null)return actualNumber===expectedNumber;return normalize(value)===normalize(item)})};

export const lessonEightyOneStages:LessonEightyOneStage[]=[
{id:'l81-mission',kind:'story',eyebrow:'Урок 81 · § 23 · объём фигуры',title:'Измеряем пространство кубиками',body:'Мы уже измеряли длину отрезком и площадь квадратом. Теперь появляется третья величина — объём. Его единицей служит куб, а измерение отвечает на вопрос: сколько таких единичных кубов помещается в фигуре.',note:'Технологическая карта урока 81: устно № 2, с. 156; теория § 23, с. 153–154; № 617, 618, 622; повторение № 643 (1, 2); домашнее — вопросы 1–4, № 623, 641.',visual:'mission'},
{id:'l81-oral2-model',kind:'guided',eyebrow:'Актуализация · устно № 2, с. 156',title:'Куб 2 см собираем из кубиков 1 см',body:'По каждому из трёх направлений помещается по 2 маленьких кубика. Значит получаются два слоя по четыре кубика.',visual:'cubes',sourceExercise:'Устно № 2, с. 156'},
{id:'l81-oral2-count',kind:'practice',eyebrow:'Устно № 2 · ответ',title:'Сколько единичных кубиков?',body:'Считаем 2·2·2, но пока воспринимаем это именно как счёт кубиков, а не как новую формулу.',activity:{id:'l81-p1',type:'input',prompt:'Сколько кубиков с ребром 1 см нужно для куба с ребром 2 см?',answer:'8',placeholder:'кубиков',hint:'В одном слое 2·2=4 кубика, слоёв два.',explanation:'Нужно 8 кубиков.'},visual:'cubes',sourceExercise:'Устно № 2, с. 156'},
{id:'l81-volume-meaning',kind:'model',eyebrow:'§ 23 · с. 153–154',title:'Объём сравнивает, сколько пространства занимает фигура',body:'Фигуры можно сравнивать не только по длине или площади. Объём характеризует пространственный размер тела: например, объём бака, бассейна или комнаты.',visual:'volume',sourceExercise:'§ 23, с. 153–154'},
{id:'l81-equal-property',kind:'quiz',eyebrow:'§ 23 · свойство 1',title:'Равные фигуры',body:'Учебник формулирует первое свойство объёма: равные фигуры имеют равные объёмы.',activity:{id:'l81-p2',type:'choice',prompt:'Если две пространственные фигуры равны, равны ли их объёмы?',options:['да','нет'],answer:'да',hint:'Это первое свойство объёма.',explanation:'Да. Равные фигуры имеют равные объёмы.'},visual:'volume',sourceExercise:'§ 23, с. 154'},
{id:'l81-additive-property',kind:'quiz',eyebrow:'§ 23 · свойство 2',title:'Составная фигура',body:'Если фигура составлена из неперекрывающихся частей, её объём равен сумме объёмов этих частей.',activity:{id:'l81-p3',type:'choice',prompt:'Объём всей фигуры равен сумме объёмов её частей?',options:['да','нет'],answer:'да',hint:'В учебнике примером служит двухкамерный холодильник.',explanation:'Да. Это второе свойство объёма.'},visual:'parts',sourceExercise:'§ 23, с. 154'},
{id:'l81-unit-cube-model',kind:'model',eyebrow:'§ 23 · единица измерения',title:'Единичный куб',body:'За единицу измерения объёма выбирают куб, ребро которого равно единичному отрезку. Такой куб называют единичным.',visual:'unit',sourceExercise:'§ 23, с. 154'},
{id:'l81-unit-cube-edge',kind:'quiz',eyebrow:'§ 23 · определение',title:'Что делает куб единичным?',body:'Ключевое условие относится к длине ребра.',activity:{id:'l81-p4',type:'choice',prompt:'Ребро единичного куба равно…',options:['единичному отрезку','двум единичным отрезкам','площади единичного квадрата'],answer:'единичному отрезку',hint:'Так единица длины превращается в единицу объёма.',explanation:'Ребро единичного куба равно единичному отрезку.'},visual:'unit',sourceExercise:'§ 23, с. 154'},
{id:'l81-cubic-centimeter',kind:'practice',eyebrow:'§ 23 · кубический сантиметр',title:'Куб с ребром 1 см',body:'Объём такого единичного куба называют одним кубическим сантиметром.',activity:{id:'l81-p5',type:'input',prompt:'Объём куба с ребром 1 см = ? см³',answer:'1',placeholder:'см³',hint:'Сам куб и задаёт единицу.',explanation:'Это 1 см³.'},visual:'unit',sourceExercise:'§ 23, с. 154'},
{id:'l81-units-map',kind:'model',eyebrow:'§ 23 · единицы объёма',title:'мм³, см³, дм³, м³, км³',body:'Название кубической единицы определяется длиной ребра единичного куба: 1 мм даёт мм³, 1 см — см³, 1 дм — дм³, 1 м — м³, 1 км — км³.',visual:'units',sourceExercise:'§ 23, с. 154'},
{id:'l81-liter',kind:'practice',eyebrow:'§ 23 · бытовая связь',title:'Литр — это кубический дециметр',body:'Для жидкостей и газов объём 1 дм³ называют литром.',activity:{id:'l81-p6',type:'input',prompt:'1 л = ? дм³',answer:'1',placeholder:'дм³',hint:'Эта связь дана прямо в § 23.',explanation:'1 л = 1 дм³.'},visual:'units',sourceExercise:'§ 23, с. 154'},
{id:'l81-measure-model',kind:'model',eyebrow:'§ 23 · измерение объёма',title:'Что значит измерить объём?',body:'Измерить объём фигуры — значит подсчитать, сколько выбранных единичных кубов в ней помещается.',visual:'cubes',sourceExercise:'§ 23, с. 154'},
{id:'l81-figure-a',kind:'practice',eyebrow:'§ 23 · рис. 176а',title:'Первая фигура',body:'Если красный кубик на рисунке 176д принять за единицу, учебник указывает объём фигуры 176а.',activity:{id:'l81-p7',type:'input',prompt:'Объём фигуры 176а = ? кубических единиц',answer:'5',hint:'Считай единичные кубики.',explanation:'Объём равен 5 кубическим единицам.'},visual:'cubes',sourceExercise:'Рис. 176а'},
{id:'l81-figure-b',kind:'practice',eyebrow:'§ 23 · рис. 176б',title:'Равная по объёму фигура',body:'Фигура может выглядеть иначе, но состоять из того же количества одинаковых кубиков.',activity:{id:'l81-p8',type:'input',prompt:'Объём фигуры 176б = ? кубических единиц',answer:'5',hint:'В тексте § 23 для а и б указаны равные объёмы.',explanation:'Объём равен 5 кубическим единицам.'},visual:'cubes',sourceExercise:'Рис. 176б'},
{id:'l81-figure-c',kind:'practice',eyebrow:'§ 23 · рис. 176в',title:'Больше единичных кубиков — больше объём',body:'Для фигуры 176в количество единичных кубов дано в тексте параграфа.',activity:{id:'l81-p9',type:'input',prompt:'Объём фигуры 176в = ? кубических единиц',answer:'18',hint:'Эта фигура вдвое объёмнее фигуры 176г.',explanation:'Объём равен 18 кубическим единицам.'},visual:'cubes',sourceExercise:'Рис. 176в'},
{id:'l81-figure-d',kind:'practice',eyebrow:'§ 23 · рис. 176г',title:'Сравнение с предыдущей фигурой',body:'Фигура 176г составлена из девяти таких же кубиков.',activity:{id:'l81-p10',type:'input',prompt:'Объём фигуры 176г = ? кубических единиц',answer:'9',hint:'18 в два раза больше этого объёма.',explanation:'Объём равен 9 кубическим единицам.'},visual:'cubes',sourceExercise:'Рис. 176г'},
{id:'l81-617-model',kind:'guided',eyebrow:'№ 617(1)',title:'Длина, площадь, объём растут по-разному',body:'В одном дециметре 10 сантиметров. Для квадрата это сетка 10×10, а для куба — 10×10×10 единичных кубиков.',visual:'convert',sourceExercise:'№ 617(1)'},
{id:'l81-617-length',kind:'practice',eyebrow:'№ 617(1) · длина',title:'Один дециметр',body:'Начинаем с линейной единицы.',activity:{id:'l81-p11',type:'input',prompt:'1 дм = ? см',answer:'10',placeholder:'см',hint:'Деци- и санти-: 1 дм = 10 см.',explanation:'1 дм = 10 см.'},visual:'convert',sourceExercise:'№ 617(1)'},
{id:'l81-617-area',kind:'practice',eyebrow:'№ 617(1) · площадь',title:'Квадратный дециметр',body:'По каждой стороне квадрата помещается 10 сантиметров.',activity:{id:'l81-p12',type:'input',prompt:'1 дм² = ? см²',answer:'100',placeholder:'см²',hint:'10·10.',explanation:'1 дм² = 100 см².'},visual:'convert',sourceExercise:'№ 617(1)'},
{id:'l81-617-volume',kind:'practice',eyebrow:'№ 617(1) · объём',title:'Кубический дециметр',body:'Теперь куб имеет три направления по 10 сантиметров.',activity:{id:'l81-p13',type:'input',prompt:'1 дм³ = ? см³',answer:'1000',placeholder:'см³',hint:'10·10·10.',explanation:'1 дм³ = 1000 см³.'},visual:'convert',sourceExercise:'№ 617(1)'},
{id:'l81-617-meter-model',kind:'guided',eyebrow:'№ 617(2)',title:'То же сравнение для метра и сантиметра',body:'В одном метре 100 сантиметров. Квадратная единица получает два множителя 100, кубическая — три.',visual:'convert',sourceExercise:'№ 617(2)'},
{id:'l81-617-meter-length',kind:'practice',eyebrow:'№ 617(2) · длина',title:'Один метр',body:'Линейный переход.',activity:{id:'l81-p14',type:'input',prompt:'1 м = ? см',answer:'100',placeholder:'см',hint:'В метре 100 сантиметров.',explanation:'1 м = 100 см.'},visual:'convert',sourceExercise:'№ 617(2)'},
{id:'l81-617-meter-area',kind:'practice',eyebrow:'№ 617(2) · площадь',title:'Квадратный метр',body:'100 сантиметров по длине и 100 по ширине.',activity:{id:'l81-p15',type:'input',prompt:'1 м² = ? см²',answer:'10000',placeholder:'см²',hint:'100·100.',explanation:'1 м² = 10 000 см².'},visual:'convert',sourceExercise:'№ 617(2)'},
{id:'l81-617-meter-volume',kind:'practice',eyebrow:'№ 617(2) · объём',title:'Кубический метр',body:'В единичном метровом кубе по 100 сантиметров в каждом из трёх направлений.',activity:{id:'l81-p16',type:'input',prompt:'1 м³ = ? см³',answer:'1000000',placeholder:'см³',hint:'100·100·100.',explanation:'1 м³ = 1 000 000 см³.'},visual:'convert',sourceExercise:'№ 617(2)'},
{id:'l81-618-source',kind:'model',eyebrow:'№ 618 · source checkpoint',title:'Фигуры на рисунке 179 считаются по кубикам',body:'В № 618 требуется найти объём каждой фигуры на рисунке 179, сложенной из кубиков с ребром 1 см.',note:'В доступном текстовом извлечении условие № 618 подтверждено, но сам рисунок 179 не восстановлен с достаточной точностью. Поэтому приложение не придумывает форму фигур и не подменяет авторский рисунок приблизительной схемой.',visual:'source',sourceExercise:'№ 618 · рис. 179'},
{id:'l81-622-model',kind:'guided',eyebrow:'№ 622 · перевод кубических единиц',title:'Кубический переход учитывает три измерения',body:'При переходе от см³ к мм³ каждый сантиметр даёт 10 миллиметров по трём направлениям, поэтому множитель равен 1000.',visual:'convert',sourceExercise:'№ 622'},
{id:'l81-622-seven',kind:'practice',eyebrow:'№ 622(1)',title:'7 см³ в мм³',body:'Каждый кубический сантиметр содержит 1000 кубических миллиметров.',activity:{id:'l81-p17',type:'input',prompt:'7 см³ = ? мм³',answer:'7000',placeholder:'мм³',hint:'7·1000.',explanation:'7 см³ = 7000 мм³.'},visual:'convert',sourceExercise:'№ 622(1)'},
{id:'l81-622-mixed-mm',kind:'practice',eyebrow:'№ 622(1)',title:'Смешанная запись',body:'Сначала 12 см³ переводим в мм³, затем добавляем 243 мм³.',activity:{id:'l81-p18',type:'input',prompt:'12 см³ 243 мм³ = ? мм³',answer:'12243',placeholder:'мм³',hint:'12·1000+243.',explanation:'12 243 мм³.'},visual:'convert',sourceExercise:'№ 622(1)'},
{id:'l81-622-four-m3',kind:'practice',eyebrow:'№ 622(2)',title:'4 м³ в дм³',body:'В одном метре 10 дециметров, значит в одном кубическом метре 10·10·10 кубических дециметров.',activity:{id:'l81-p19',type:'input',prompt:'4 м³ = ? дм³',answer:'4000',placeholder:'дм³',hint:'4·1000.',explanation:'4 м³ = 4000 дм³.'},visual:'convert',sourceExercise:'№ 622(2)'},
{id:'l81-622-cm-to-dm',kind:'practice',eyebrow:'№ 622(2)',title:'44 000 см³ в дм³',body:'Один кубический дециметр — это 1000 кубических сантиметров.',activity:{id:'l81-p20',type:'input',prompt:'44 000 см³ = ? дм³',answer:'44',placeholder:'дм³',hint:'44 000:1000.',explanation:'44 000 см³ = 44 дм³.'},visual:'convert',sourceExercise:'№ 622(2)'},
{id:'l81-623-transfer',kind:'guided',eyebrow:'Домашний маршрут · № 623',title:'Обратный перевод в кубические сантиметры',body:'В домашнем № 623 встречается, например, перевод 8 дм³ в см³. Это прямая обратная связь к № 622.',visual:'convert',sourceExercise:'№ 623'},
{id:'l81-623-eight',kind:'practice',eyebrow:'№ 623 · подготовка',title:'8 дм³ в см³',body:'В одном дм³ — 1000 см³.',activity:{id:'l81-p21',type:'input',prompt:'8 дм³ = ? см³',answer:'8000',placeholder:'см³',hint:'8·1000.',explanation:'8 дм³ = 8000 см³.'},visual:'convert',sourceExercise:'№ 623'},
{id:'l81-643-source',kind:'model',eyebrow:'Повторение · № 643 (1, 2)',title:'Повторение сохраняем как авторский checkpoint',body:'Технологическая карта урока 81 задаёт повторение № 643 (1, 2).',note:'Полное условие этих подпунктов не удалось надёжно восстановить из доступного извлечения именно этой редакции учебника. Номер сохранён в маршруте без выдуманного текста.',visual:'source',sourceExercise:'№ 643 (1, 2)'},
{id:'l81-questions',kind:'story',eyebrow:'§ 23 · вопросы 1–4',title:'Четыре вопроса для самопроверки',body:'Сформулируй своими словами: какими свойствами обладает объём; какой куб называют единичным; какие единицы объёма ты знаешь; что означает измерить объём фигуры.',visual:'verify',sourceExercise:'§ 23 · вопросы 1–4'},
{id:'l81-next',kind:'model',eyebrow:'Граница урока',title:'Формула объёма — следующий шаг',body:'Сегодня мы научились измерять объём кубическими единицами. На уроке 82 эта идея приведёт к вычислению объёма прямоугольного параллелепипеда по его измерениям.',note:'Урок 82 остаётся заблокирован до отдельного релиза. Формула V=abc не используется как новое правило урока 81.',visual:'next'},
{id:'l81-summary',kind:'summary',eyebrow:'Итог урока 81',title:'Теперь объём — не просто слово, а измеряемая величина',body:'Ты знаешь два свойства объёма, понимаешь роль единичного куба, умеешь читать кубические единицы и переводить их через линейный масштаб. Главное: измерить объём — значит выяснить, сколько единичных кубов помещается в фигуре.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 82 — «Объём прямоугольного параллелепипеда» — пока закрыт.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'V',volume:'▣',parts:'▦',unit:'1³',units:'мм³→м³',cubes:'▦▦',convert:'×1000',source:'§23',verify:'✓',next:'82',final:'81'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='unit'?'единичный куб':kind==='units'?'кубические единицы':kind==='convert'?'масштаб по трём направлениям':kind==='parts'?'объём целого = сумма объёмов частей':kind==='cubes'?'считаем единичные кубы':'объём фигуры · § 23'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyOneStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function VolumeFigurePlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyOneStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyOneStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==81||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyOneStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyOneStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player volume-figure-player" data-lesson-number="81" data-source-reference="Мерзляк § 23 · технологическая карта урока 81 · устно № 2 · № 617, 618, 622 · повторение № 643 (1, 2)" data-source-exercise-range="617,618,622,643"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyOneStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyOneStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
