import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';
import './angleMeasurement.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='straight'|'degree'|'protractor'|'measure60'|'measure120'|'parts'|'types';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-39-progress-v1';
const normalize=(value:string)=>value.trim().toUpperCase().replace(/\s+/g,'').replace(/[°º]/g,'').replace(/Ё/g,'Е');

export const lessonThirtyNineStages:Stage[]=[
  {id:'l39-mission',kind:'story',eyebrow:'Урок 39 · § 12 · новая тема',title:'Сегодня угол получает точное число',body:'В § 11 мы научились видеть угол, его вершину и стороны. Теперь рисунка недостаточно: нужно измерять величину угла. Для этого вводим градус и транспортир, а затем по градусной мере определяем вид угла.',note:'Главная ловушка урока — две шкалы транспортира. Читаем не ближайшее число, а ту шкалу, которая начинается с 0° на выбранной стороне.',diagram:'protractor'},
  {id:'l39-straight-model',kind:'model',eyebrow:'Шаг 1',title:'Развёрнутый угол образует прямую',body:'Если две стороны угла — противоположные лучи с общей вершиной O, вместе они образуют прямую. Такой угол называют развёрнутым.',diagram:'straight'},
  {id:'l39-practice1',kind:'practice',eyebrow:'Практика · 1/13',title:'Узнай развёрнутый угол',body:'Сначала проверяем направление двух лучей.',activity:{id:'l39-p1',type:'choice',prompt:'Какие стороны образуют развёрнутый угол?',options:['Два противоположных луча с общим началом','Два любых пересекающихся отрезка','Два параллельных луча','Любые два луча из разных точек'],answer:'Два противоположных луча с общим началом',hint:'У сторон угла должна быть общая вершина, а вместе они должны образовать прямую.',explanation:'Развёрнутый угол задают два противоположных луча с общим началом.'}},
  {id:'l39-degree-model',kind:'model',eyebrow:'Шаг 2',title:'Один градус — одна из 180 равных частей',body:'Разделим развёрнутый угол на 180 равных маленьких углов. Один такой угол принимают за единицу измерения и называют градусом: 1°. Значит, развёрнутый угол равен 180°.',diagram:'degree'},
  {id:'l39-practice2',kind:'practice',eyebrow:'Практика · 2/13',title:'Главное число параграфа',body:'Запомни его как опорную точку всей шкалы.',activity:{id:'l39-p2',type:'input',prompt:'Сколько градусов содержит развёрнутый угол?',answer:'180',placeholder:'Число градусов',hint:'Развёрнутый угол разделили на 180 равных единичных углов.',explanation:'Градусная мера развёрнутого угла — 180°.'}},
  {id:'l39-protractor-model',kind:'model',eyebrow:'Шаг 3',title:'Транспортир: центр, основание и шкала',body:'У обычного транспортира есть центр, который совмещают с вершиной угла; прямая линия основания, на которой лежит одна сторона; и шкала от 0° до 180°. Часто шкал две — они идут навстречу друг другу.',diagram:'protractor'},
  {id:'l39-practice3',kind:'practice',eyebrow:'Практика · 3/13',title:'Куда ставить центр?',body:'Без этого любое считывание становится случайным.',activity:{id:'l39-p3',type:'choice',prompt:'С чем нужно совместить центр транспортира?',options:['С вершиной угла','С концом любой стороны','С отметкой 90°','С серединой рисунка'],answer:'С вершиной угла',hint:'Из вершины выходят обе стороны угла.',explanation:'Центр транспортира обязательно совмещают с вершиной угла.'}},
  {id:'l39-zero-line',kind:'model',eyebrow:'Шаг 4',title:'Одна сторона угла должна идти через 0°',body:'После совмещения центра поверни транспортир так, чтобы одна сторона угла легла вдоль основания. На той шкале, которую будем читать, эта сторона должна указывать на 0°.',note:'Если сторона показывает 180°, значит ты смотришь на противоположную шкалу.',diagram:'protractor'},
  {id:'l39-practice4',kind:'practice',eyebrow:'Практика · 4/13',title:'Как выбрать шкалу?',body:'Это защита от ошибки 60° ↔ 120°.',activity:{id:'l39-p4',type:'choice',prompt:'Как понять, какую из двух шкал транспортира читать?',options:['Выбрать ту, где исходная сторона угла стоит на 0°','Всегда читать внешнюю шкалу','Всегда читать внутреннюю шкалу','Выбрать шкалу с большим числом'],answer:'Выбрать ту, где исходная сторона угла стоит на 0°',hint:'Начало измерения — 0° на стороне, лежащей вдоль основания.',explanation:'Правильная шкала начинается с 0° на выбранной исходной стороне.'}},
  {id:'l39-measure60-model',kind:'model',eyebrow:'Шаг 5',title:'Пример: читаем угол 60°',body:'Вершина O стоит в центре, луч OA лежит на основании и проходит через 0°. Вторая сторона OB пересекает правильную шкалу на отметке 60°. Поэтому ∠AOB = 60°.',diagram:'measure60'},
  {id:'l39-practice5',kind:'practice',eyebrow:'Практика · 5/13',title:'Считай показание',body:'Сначала найди ноль, потом вторую сторону.',diagram:'measure60',activity:{id:'l39-p5',type:'input',prompt:'Какова градусная мера показанного угла?',answer:'60',placeholder:'Градусы',hint:'Луч OA начинается на 0°, луч OB проходит через отметку 60°.',explanation:'Градусная мера угла равна 60°.'}},
  {id:'l39-scale-trap',kind:'model',eyebrow:'Критическая ошибка',title:'На одном штрихе могут стоять 60° и 120°',body:'Две шкалы транспортира читаются в противоположных направлениях. Один и тот же штрих может быть подписан 60 и 120. Ответ выбираем по нулю: если исходная сторона стоит на 0° шкалы, идущей к 60°, угол равен 60°, а не 120°.',diagram:'measure60'},
  {id:'l39-practice6',kind:'practice',eyebrow:'Практика · 6/13',title:'Не попади в ловушку шкал',body:'Проверь, откуда начинается отсчёт.',activity:{id:'l39-p6',type:'choice',prompt:'Вторая сторона проходит через штрих 60/120. Исходная сторона лежит на 0° той шкалы, которая возрастает к 60. Что записать?',options:['60°','120°','180°','30°'],answer:'60°',hint:'Иди по шкале от того нуля, на котором лежит исходная сторона.',explanation:'Если отсчёт начинается с 0° и до второй стороны проходит 60 делений, угол равен 60°.'}},
  {id:'l39-measure120-model',kind:'model',eyebrow:'Шаг 6',title:'Тупой пример: 120°',body:'Теперь вторая сторона прошла дальше прямого угла. По правильной шкале получаем 120°. Число больше 90°, но меньше 180° — позже это сразу подскажет вид угла.',diagram:'measure120'},
  {id:'l39-practice7',kind:'practice',eyebrow:'Практика · 7/13',title:'Прочитай тупой угол',body:'Снова начинай с нуля на исходной стороне.',diagram:'measure120',activity:{id:'l39-p7',type:'input',prompt:'Какова градусная мера показанного угла?',answer:'120',placeholder:'Градусы',hint:'Вторая сторона проходит через отметку 120° правильной шкалы.',explanation:'Показанный угол равен 120°.'}},
  {id:'l39-equal-measures',kind:'model',eyebrow:'Связь с § 11',title:'Равные углы имеют равные градусные меры',body:'Раньше равенство углов мы понимали через наложение. Теперь появляется числовая проверка: если углы равны, их градусные меры одинаковы. А из двух неравных углов больше тот, у которого градусная мера больше.'},
  {id:'l39-practice8',kind:'practice',eyebrow:'Практика · 8/13',title:'Сравни углы числами',body:'Градусная мера превращает сравнение в обычное сравнение чисел.',activity:{id:'l39-p8',type:'choice',prompt:'Какой угол больше: 72° или 105°?',options:['105°','72°','Они равны','По градусам сравнить нельзя'],answer:'105°',hint:'Большему углу соответствует большая градусная мера.',explanation:'105 > 72, значит угол 105° больше.'}},
  {id:'l39-parts-model',kind:'model',eyebrow:'Шаг 7',title:'Если луч проходит внутри угла, части складываются',body:'Если луч OD лежит между сторонами угла AOB, то ∠AOB = ∠AOD + ∠DOB. Это то же правило «целое равно сумме частей», знакомое по длинам отрезков.',diagram:'parts'},
  {id:'l39-practice9',kind:'practice',eyebrow:'Практика · 9/13',title:'Сложи части угла',body:'Сначала убедись, что две части действительно составляют целый угол.',diagram:'parts',activity:{id:'l39-p9',type:'input',prompt:'∠AOD = 35°, ∠DOB = 45°. Чему равен ∠AOB?',answer:'80',placeholder:'Градусы',hint:'Целый угол равен сумме двух частей.',explanation:'35° + 45° = 80°.'}},
  {id:'l39-types-model',kind:'model',eyebrow:'Шаг 8',title:'Четыре вида углов по градусной мере',body:'Острый угол меньше 90°. Прямой равен 90°. Тупой больше 90°, но меньше 180°. Развёрнутый равен 180°. Границы здесь строгие: 90° — уже не острый и не тупой.',diagram:'types'},
  {id:'l39-practice10',kind:'practice',eyebrow:'Практика · 10/13',title:'Острый или нет?',body:'Сравни с 90°.',activity:{id:'l39-p10',type:'choice',prompt:'Какой вид имеет угол 38°?',options:['Острый','Прямой','Тупой','Развёрнутый'],answer:'Острый',hint:'38 меньше 90.',explanation:'38° < 90°, значит угол острый.'}},
  {id:'l39-practice11',kind:'practice',eyebrow:'Практика · 11/13',title:'Граница 90°',body:'На границе название меняется.',activity:{id:'l39-p11',type:'choice',prompt:'Какой вид имеет угол 90°?',options:['Прямой','Острый','Тупой','Развёрнутый'],answer:'Прямой',hint:'90° — точное определение прямого угла.',explanation:'Угол 90° называют прямым.'}},
  {id:'l39-practice12',kind:'practice',eyebrow:'Практика · 12/13',title:'Между 90° и 180°',body:'Проверяем обе границы.',activity:{id:'l39-p12',type:'choice',prompt:'Какой вид имеет угол 127°?',options:['Тупой','Острый','Прямой','Развёрнутый'],answer:'Тупой',hint:'127 больше 90 и меньше 180.',explanation:'90° < 127° < 180°, значит угол тупой.'}},
  {id:'l39-practice13',kind:'practice',eyebrow:'Практика · 13/13',title:'Вторая точная граница',body:'Здесь тоже нельзя выбирать «почти тупой».',activity:{id:'l39-p13',type:'choice',prompt:'Какой вид имеет угол 180°?',options:['Развёрнутый','Тупой','Прямой','Острый'],answer:'Развёрнутый',hint:'180° — точная мера развёрнутого угла.',explanation:'Угол 180° — развёрнутый.'}},
  {id:'l39-boundaries',kind:'model',eyebrow:'Антиошибка',title:'89°, 90°, 91° — три разных ситуации',body:'89° — острый; 90° — прямой; 91° — тупой. Нельзя определять вид «на глаз»: достаточно одного градуса, чтобы перейти через границу.'},
  {id:'l39-quiz1',kind:'quiz',eyebrow:'Мини-контроль · 1/6',title:'Граница слева',body:'Без рисунка.',activity:{id:'l39-q1',type:'choice',prompt:'Угол 89° — это…',options:['острый','прямой','тупой','развёрнутый'],answer:'острый',hint:'89 < 90.',explanation:'89° — острый угол.'}},
  {id:'l39-quiz2',kind:'quiz',eyebrow:'Мини-контроль · 2/6',title:'Граница справа',body:'Один градус после 90° уже меняет вид.',activity:{id:'l39-q2',type:'choice',prompt:'Угол 91° — это…',options:['тупой','прямой','острый','развёрнутый'],answer:'тупой',hint:'91 > 90 и 91 < 180.',explanation:'91° — тупой угол.'}},
  {id:'l39-quiz3',kind:'quiz',eyebrow:'Мини-контроль · 3/6',title:'Максимум этого параграфа',body:'Вспомни прямую.',activity:{id:'l39-q3',type:'input',prompt:'Сколько градусов в развёрнутом угле?',answer:'180',placeholder:'Градусы',hint:'Противоположные лучи образуют развёрнутый угол.',explanation:'Развёрнутый угол равен 180°.'}},
  {id:'l39-quiz4',kind:'quiz',eyebrow:'Мини-контроль · 4/6',title:'Установка транспортира',body:'Проверяем главный технический шаг.',activity:{id:'l39-q4',type:'choice',prompt:'Что должно совпасть с центром транспортира?',options:['Вершина угла','Вторая сторона угла','Отметка 90°','Середина дуги'],answer:'Вершина угла',hint:'Обе стороны выходят из вершины.',explanation:'Центр транспортира совмещают с вершиной угла.'}},
  {id:'l39-quiz5',kind:'quiz',eyebrow:'Мини-контроль · 5/6',title:'Две шкалы',body:'Применяй правило нуля.',activity:{id:'l39-q5',type:'choice',prompt:'Один штрих подписан 60 и 120. Исходная сторона стоит на 0° шкалы, которая идёт к 120. Какова мера?',options:['120°','60°','90°','180°'],answer:'120°',hint:'Следуй от нуля именно по выбранной шкале.',explanation:'По шкале, начинающейся с 0° на исходной стороне, получаем 120°.'}},
  {id:'l39-quiz6',kind:'quiz',eyebrow:'Мини-контроль · 6/6',title:'Целое из частей',body:'Последняя базовая проверка.',activity:{id:'l39-q6',type:'input',prompt:'Луч делит угол на части 42° и 38°. Чему равен весь угол?',answer:'80',placeholder:'Градусы',hint:'Сложи градусные меры частей.',explanation:'42° + 38° = 80°.'}},
  {id:'l39-challenge1',kind:'challenge',eyebrow:'Challenge · 1/2',title:'Классификация без рисунка',body:'Нужно назвать вид по числу.',activity:{id:'l39-c1',type:'choice',prompt:'Угол 135° относится к какому виду?',options:['Тупой','Острый','Прямой','Развёрнутый'],answer:'Тупой',hint:'Сравни 135 с 90 и 180.',explanation:'90° < 135° < 180°, поэтому угол тупой.'}},
  {id:'l39-challenge2',kind:'challenge',eyebrow:'Challenge · 2/2',title:'Найди неизвестную часть',body:'Теперь правило суммы работает в обратную сторону.',activity:{id:'l39-c2',type:'input',prompt:'Весь угол равен 128°. Одна часть равна 53°. Сколько градусов во второй части?',answer:'75',placeholder:'Градусы',hint:'Из целого вычти известную часть.',explanation:'128° − 53° = 75°.'}},
  {id:'l39-final-map',kind:'model',eyebrow:'Карта урока',title:'Пять шагов измерения, которые нельзя менять местами',body:'1) Совместить вершину с центром. 2) Положить одну сторону на основание. 3) Найти на этой стороне 0°. 4) Читать именно эту шкалу. 5) Считать число у второй стороны. После этого сравнить результат с 90° и 180°, чтобы назвать вид угла.',diagram:'protractor'},
  {id:'l39-summary',kind:'summary',eyebrow:'Финиш урока 39',title:'Теперь угол можно измерить и классифицировать',body:'Ты знаешь градус, развёрнутый угол 180°, алгоритм работы с транспортиром, ловушку двух шкал, виды углов и правило сложения частей. Следующие уроки § 12 превратят это в уверенное построение и сложные вычисления.',note:'До полного завершения урока остаётся обязательная практика из 20 заданий.'},
];

function MeasurementDiagram({kind}:{kind:Diagram}){
  if(kind==='straight')return <div className="angle-diagram" aria-label="Развёрнутый угол 180 градусов"><svg viewBox="0 0 620 260" role="img"><line className="angle-ray" x1="310" y1="170" x2="70" y2="170"/><line className="angle-ray" x1="310" y1="170" x2="550" y2="170"/><circle className="angle-point" cx="310" cy="170" r="6"/><path className="angle-arc" d="M220 170 A90 90 0 0 1 400 170"/><text className="angle-label" x="292" y="205">O</text><text className="measure-label" x="288" y="70">180°</text></svg><span className="angle-caption">Противоположные лучи образуют развёрнутый угол</span></div>;
  if(kind==='degree')return <div className="angle-diagram" aria-label="Развёрнутый угол разделён на 180 равных частей"><svg viewBox="0 0 620 300" role="img"><line className="measure-base" x1="70" y1="245" x2="550" y2="245"/><path className="measure-protractor" d="M70 245 A240 240 0 0 1 550 245"/><line className="measure-mark" x1="310" y1="245" x2="310" y2="35"/><line className="measure-mark" x1="310" y1="245" x2="430" y2="38"/><line className="measure-mark" x1="310" y1="245" x2="190" y2="38"/><text className="measure-label" x="287" y="285">180 частей</text><text className="measure-small" x="420" y="74">1° = 1/180</text></svg><span className="angle-caption">1° — одна из 180 равных частей развёрнутого угла</span></div>;
  if(kind==='protractor')return <div className="angle-diagram" aria-label="Схема транспортира с центром, основанием и шкалой"><svg viewBox="0 0 620 330" role="img"><line className="measure-base" x1="70" y1="270" x2="550" y2="270"/><path className="measure-protractor" d="M70 270 A240 240 0 0 1 550 270"/><circle className="measure-center" cx="310" cy="270" r="7"/><line className="measure-tick" x1="310" y1="30" x2="310" y2="50"/><line className="measure-tick" x1="190" y1="62" x2="200" y2="80"/><line className="measure-tick" x1="430" y1="62" x2="420" y2="80"/><text className="measure-small" x="54" y="300">0° / 180°</text><text className="measure-small" x="520" y="300">180° / 0°</text><text className="measure-label" x="286" y="310">центр</text><text className="measure-small" x="287" y="25">90°</text></svg><span className="angle-caption">Центр ставим в вершину; исходная сторона должна пройти через 0° выбранной шкалы</span></div>;
  if(kind==='measure60')return <div className="angle-diagram" aria-label="Измерение угла 60 градусов транспортиром"><svg viewBox="0 0 620 330" role="img"><line className="measure-base" x1="70" y1="270" x2="550" y2="270"/><path className="measure-protractor" d="M70 270 A240 240 0 0 1 550 270"/><circle className="measure-center" cx="310" cy="270" r="7"/><line className="angle-ray" x1="310" y1="270" x2="545" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="430" y2="62"/><path className="angle-arc" d="M385 270 A75 75 0 0 0 348 205"/><text className="measure-label" x="424" y="54">60° / 120°</text><text className="measure-small" x="520" y="300">0°</text><text className="angle-label" x="292" y="310">O</text></svg><span className="angle-caption">Исходный луч стоит на правом 0° → читаем 60°</span></div>;
  if(kind==='measure120')return <div className="angle-diagram" aria-label="Измерение угла 120 градусов транспортиром"><svg viewBox="0 0 620 330" role="img"><line className="measure-base" x1="70" y1="270" x2="550" y2="270"/><path className="measure-protractor" d="M70 270 A240 240 0 0 1 550 270"/><circle className="measure-center" cx="310" cy="270" r="7"/><line className="angle-ray" x1="310" y1="270" x2="545" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="190" y2="62"/><path className="angle-arc" d="M385 270 A75 75 0 0 0 273 205"/><text className="measure-label" x="132" y="54">120° / 60°</text><text className="measure-small" x="520" y="300">0°</text><text className="angle-label" x="292" y="310">O</text></svg><span className="angle-caption">От правого 0° до второй стороны — 120°</span></div>;
  if(kind==='parts')return <div className="angle-diagram" aria-label="Угол разделён внутренним лучом на две части"><svg viewBox="0 0 620 300" role="img"><line className="angle-ray" x1="150" y1="245" x2="535" y2="245"/><line className="angle-ray" x1="150" y1="245" x2="430" y2="65"/><line className="angle-ray" x1="150" y1="245" x2="275" y2="65"/><circle className="angle-point" cx="150" cy="245" r="6"/><path className="angle-arc" d="M225 245 A75 75 0 0 0 210 202"/><path className="angle-arc" d="M210 202 A75 75 0 0 0 190 185"/><text className="angle-label" x="130" y="280">O</text><text className="measure-label" x="225" y="202">часть 1</text><text className="measure-label" x="325" y="165">часть 2</text></svg><span className="angle-caption">Целый угол = сумма градусных мер двух частей</span></div>;
  return <div className="angle-diagram" aria-label="Острый, прямой, тупой и развёрнутый углы"><svg viewBox="0 0 620 360" role="img"><g transform="translate(85 95)"><line className="angle-ray" x1="0" y1="70" x2="110" y2="70"/><line className="angle-ray" x1="0" y1="70" x2="80" y2="15"/><text className="measure-small" x="12" y="105">острый &lt; 90°</text></g><g transform="translate(350 95)"><line className="angle-ray" x1="0" y1="70" x2="110" y2="70"/><line className="angle-ray" x1="0" y1="70" x2="0" y2="-40"/><rect className="right-marker" x="0" y="48" width="22" height="22"/><text className="measure-small" x="8" y="105">прямой = 90°</text></g><g transform="translate(85 245)"><line className="angle-ray" x1="0" y1="70" x2="110" y2="70"/><line className="angle-ray" x1="0" y1="70" x2="-55" y2="5"/><text className="measure-small" x="-5" y="105">тупой: 90° &lt; α &lt; 180°</text></g><g transform="translate(350 245)"><line className="angle-ray" x1="0" y1="70" x2="110" y2="70"/><line className="angle-ray" x1="0" y1="70" x2="-110" y2="70"/><text className="measure-small" x="-18" y="105">развёрнутый = 180°</text></g></svg><span className="angle-caption">Вид угла определяется числом градусов, а не внешним впечатлением</span></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirtyNineStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function AngleMeasurementPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonThirtyNineStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==39||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonThirtyNineStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonThirtyNineStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player measurement-player" aria-label="Урок 39. Виды углов. Измерение углов"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<MeasurementDiagram kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric"/></div>}<button type="button" className="check-button" disabled={!response.trim()} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 12 · урок 1 из 5 завершён</strong><span>Развёрнутый угол · градус · транспортир · две шкалы · виды углов · сумма частей</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonThirtyNineStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonThirtyNineStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonThirtyNineStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}
