import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'rectangle'|'square'|'scale'|'convert'|'equal'|'verify'|'construct'|'final';
export type LessonSeventySevenStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-77-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventySevenStages:LessonSeventySevenStage[]=[
{id:'l77-mission',kind:'story',eyebrow:'Урок 77 · § 21 · итоговое обобщение',title:'Собираем площадь в одну систему',body:'Это финальный урок § 21. Теперь нужно самостоятельно видеть, где работает площадь, где периметр, где обратное действие, а где сравнение или доказательство. Формулы становятся инструментами выбора, а не отдельными правилами.',note:'Технологическая карта урока 77: устно № 4, с. 142; обобщение № 584, 586, 587, 593, 594; повторение № 597.',visual:'mission'},
{id:'l77-oral-source',kind:'model',eyebrow:'Актуализация · устно № 4, с. 142',title:'Источник отмечен без выдуманного условия',body:'Технологическая карта требует устное № 4 на с. 142. Его полная формулировка в доступном извлечении учебника не восстановлена надёжно, поэтому приложение не выдаёт похожую задачу за оригинал.',note:'Выполни устно № 4 непосредственно по учебнику; дальше урок проверяет все ключевые связи § 21.',visual:'map',sourceExercise:'Устно № 4, с. 142 · source checkpoint'},
{id:'l77-formula-map',kind:'model',eyebrow:'§ 21 · карта формул',title:'Четыре опоры',body:'Прямоугольник: S=ab и P=2(a+b). Квадрат: S=a² и P=4a. В обратной задаче неизвестная сторона прямоугольника равна S:a, если известны площадь и другая сторона.',visual:'map'},
{id:'l77-unit-map',kind:'model',eyebrow:'§ 21 · единицы площади',title:'Линейная и квадратная шкалы — не одно и то же',body:'1 дм²=100 см², 1 м²=100 дм²=10 000 см², 1 а=100 м², 1 га=10 000 м². При переводе площади коэффициент возникает из двух измерений.',visual:'convert'},
{id:'l77-584-model',kind:'guided',eyebrow:'№ 584',title:'Равновеликость восстанавливает неизвестную сторону',body:'Точное условие: квадрат со стороной 12 см и прямоугольник длиной 18 см равновелики. Нужно найти периметр прямоугольника.',visual:'equal',sourceExercise:'№ 584'},
{id:'l77-584-square-area',kind:'practice',eyebrow:'№ 584 · шаг 1',title:'Площадь квадрата',body:'Сторона квадрата равна 12 см.',activity:{id:'l77-p1',type:'input',prompt:'12² = ? см²',answer:'144',placeholder:'см²',hint:'12·12.',explanation:'Площадь квадрата равна 144 см².'},visual:'square',sourceExercise:'№ 584'},
{id:'l77-584-width',kind:'practice',eyebrow:'№ 584 · шаг 2',title:'Ширина равновеликого прямоугольника',body:'Площадь прямоугольника тоже равна 144 см², а его длина — 18 см.',activity:{id:'l77-p2',type:'input',prompt:'144 : 18 = ? см',answer:'8',placeholder:'см',hint:'Неизвестная сторона b=S:a.',explanation:'Ширина прямоугольника равна 8 см.'},visual:'rectangle',sourceExercise:'№ 584'},
{id:'l77-584-perimeter',kind:'practice',eyebrow:'№ 584 · шаг 3',title:'Периметр после восстановления сторон',body:'Соседние стороны прямоугольника 18 см и 8 см.',activity:{id:'l77-p3',type:'input',prompt:'2·(18+8) = ? см',answer:'52',placeholder:'см',hint:'18+8=26.',explanation:'P=2·26=52 см.'},visual:'verify',sourceExercise:'№ 584'},
{id:'l77-585-model',kind:'guided',eyebrow:'Точная соседняя задача · № 585',title:'Равновеликость в обратную сторону',body:'Квадрат равновелик прямоугольнику со сторонами 3 см и 12 см. Эта точная соседняя задача помогает проверить тот же навык перед дальнейшим обобщением.',visual:'equal',sourceExercise:'№ 585'},
{id:'l77-585-area',kind:'practice',eyebrow:'№ 585 · шаг 1',title:'Площадь прямоугольника',body:'Стороны 3 см и 12 см.',activity:{id:'l77-p4',type:'input',prompt:'3·12 = ? см²',answer:'36',placeholder:'см²',hint:'S=ab.',explanation:'Площадь равна 36 см².'},visual:'rectangle',sourceExercise:'№ 585'},
{id:'l77-585-side',kind:'practice',eyebrow:'№ 585 · шаг 2',title:'Сторона равновеликого квадрата',body:'Площадь квадрата равна 36 см².',activity:{id:'l77-p5',type:'input',prompt:'Какова сторона квадрата, см?',answer:'6',placeholder:'см',hint:'Найди натуральное число a, для которого a²=36.',explanation:'6²=36, значит сторона квадрата 6 см.'},visual:'square',sourceExercise:'№ 585'},
{id:'l77-585-perimeter',kind:'practice',eyebrow:'№ 585 · шаг 3',title:'Периметр квадрата',body:'Сторона квадрата равна 6 см.',activity:{id:'l77-p6',type:'input',prompt:'4·6 = ? см',answer:'24',placeholder:'см',hint:'P=4a.',explanation:'Периметр квадрата 24 см.'},visual:'verify',sourceExercise:'№ 585'},
{id:'l77-586-model',kind:'guided',eyebrow:'№ 586',title:'Изменение площади как добавленная полоса',body:'Точное условие: ширина прямоугольника 26 см. Длину увеличили на 4 см. Не зная исходной длины, всё равно можно найти, на сколько увеличилась площадь: добавилась полоса 26 см × 4 см.',visual:'rectangle',sourceExercise:'№ 586'},
{id:'l77-586-increase',kind:'practice',eyebrow:'№ 586 · решение',title:'Площадь добавленной полосы',body:'Изменение площади не зависит от исходной длины прямоугольника.',activity:{id:'l77-p7',type:'input',prompt:'26·4 = ? см²',answer:'104',placeholder:'см²',hint:'Добавленная часть — прямоугольник 26×4.',explanation:'Площадь увеличится на 104 см².'},visual:'verify',sourceExercise:'№ 586'},
{id:'l77-587-model',kind:'guided',eyebrow:'№ 587',title:'Масштаб: длина и площадь растут по-разному',body:'Точное условие: каждую сторону прямоугольника увеличили в 4 раза. Периметр состоит из длин и растёт в 4 раза, а площадь содержит произведение двух сторон — поэтому множитель 4 применяется дважды.',visual:'scale',sourceExercise:'№ 587'},
{id:'l77-587-perimeter-factor',kind:'practice',eyebrow:'№ 587 · периметр',title:'Линейный масштаб',body:'Если a→4a и b→4b, то P=2(a+b) превращается в 2(4a+4b)=4P.',activity:{id:'l77-p8',type:'input',prompt:'Во сколько раз увеличится периметр?',answer:'4',hint:'Вынеси общий множитель 4.',explanation:'Периметр увеличится в 4 раза.'},visual:'scale',sourceExercise:'№ 587'},
{id:'l77-587-area-factor',kind:'practice',eyebrow:'№ 587 · площадь',title:'Квадрат линейного масштаба',body:'Новая площадь равна (4a)(4b)=16ab.',activity:{id:'l77-p9',type:'input',prompt:'Во сколько раз увеличится площадь?',answer:'16',hint:'4·4=16.',explanation:'Площадь увеличится в 16 раз.'},visual:'scale',sourceExercise:'№ 587'},
{id:'l77-dictation-map',kind:'model',eyebrow:'Методическое пособие · диктант 18',title:'Быстрая итоговая диагностика § 21',body:'Диктант 18 проверяет формулы, единицы площади и логические свойства. Используем его точные задания как независимую проверку итогового владения темой.',visual:'map',sourceExercise:'Диктант 18'},
{id:'l77-dictation-1',kind:'practice',eyebrow:'Диктант 18 · № 1',title:'Разные единицы сторон',body:'Прямоугольник имеет стороны 20 дм и 4 м. Сначала 4 м=40 дм.',activity:{id:'l77-p10',type:'input',prompt:'Найди площадь, дм².',answer:'800',placeholder:'дм²',hint:'20·40.',explanation:'S=20·40=800 дм².'},visual:'rectangle',sourceExercise:'Диктант 18 · № 1'},
{id:'l77-dictation-2',kind:'practice',eyebrow:'Диктант 18 · № 2',title:'Квадрат по периметру',body:'Периметр квадрата равен 36 см. Его сторона 36:4=9 см.',activity:{id:'l77-p11',type:'input',prompt:'Чему равна площадь, см²?',answer:'81',placeholder:'см²',hint:'9².',explanation:'Площадь квадрата 81 см².'},visual:'square',sourceExercise:'Диктант 18 · № 2'},
{id:'l77-dictation-3',kind:'practice',eyebrow:'Диктант 18 · № 3',title:'Периметр по площади квадрата',body:'Площадь квадрата равна 49 м², значит его сторона 7 м.',activity:{id:'l77-p12',type:'input',prompt:'Найди периметр, м.',answer:'28',placeholder:'м',hint:'4·7.',explanation:'Периметр равен 28 м.'},visual:'square',sourceExercise:'Диктант 18 · № 3'},
{id:'l77-dictation-4',kind:'practice',eyebrow:'Диктант 18 · № 4',title:'Гектар как площадь квадрата',body:'1 га=10 000 м².',activity:{id:'l77-p13',type:'input',prompt:'Если S квадрата=1 га, какова его сторона, м?',answer:'100',placeholder:'м',hint:'100²=10 000.',explanation:'Сторона квадрата 100 м.'},visual:'convert',sourceExercise:'Диктант 18 · № 4'},
{id:'l77-dictation-5',kind:'practice',eyebrow:'Диктант 18 · № 5',title:'Ары в квадратные метры',body:'1 а=100 м².',activity:{id:'l77-p14',type:'input',prompt:'4 а = ? м²',answer:'400',placeholder:'м²',hint:'4·100.',explanation:'4 а=400 м².'},visual:'convert',sourceExercise:'Диктант 18 · № 5'},
{id:'l77-dictation-6',kind:'practice',eyebrow:'Диктант 18 · № 6',title:'Составные квадратные единицы',body:'1 дм²=100 см², поэтому 2 дм²=200 см².',activity:{id:'l77-p15',type:'input',prompt:'2 дм² 4 см² = ? см²',answer:'204',placeholder:'см²',hint:'200+4.',explanation:'Получаем 204 см².'},visual:'convert',sourceExercise:'Диктант 18 · № 6'},
{id:'l77-dictation-7',kind:'practice',eyebrow:'Диктант 18 · № 7',title:'Участок в арах',body:'Участок 40 м × 25 м имеет площадь 1000 м².',activity:{id:'l77-p16',type:'input',prompt:'1000 м² = ? а',answer:'10',placeholder:'а',hint:'1 а=100 м².',explanation:'1000:100=10 а.'},visual:'convert',sourceExercise:'Диктант 18 · № 7'},
{id:'l77-statements-intro',kind:'model',eyebrow:'Диктант 18 · № 8',title:'Площадь, равенство и периметр',body:'Последний блок отделяет действительно связанные свойства от похожих, но неверных выводов. Для опровержения достаточно одного контрпримера.',visual:'verify',sourceExercise:'Диктант 18 · № 8'},
{id:'l77-statement-1',kind:'quiz',eyebrow:'Диктант 18 · № 8(1)',title:'Равные фигуры',body:'Если фигуры совпадают при наложении, их площади одинаковы.',activity:{id:'l77-p17',type:'choice',prompt:'Если две фигуры равны, то их площади равны?',options:['да','нет'],answer:'да',hint:'Это одно из свойств площади.',explanation:'Да. Равные фигуры имеют равные площади.'},visual:'equal',sourceExercise:'Диктант 18 · № 8(1)'},
{id:'l77-statement-2',kind:'quiz',eyebrow:'Диктант 18 · № 8(2)',title:'Обратное утверждение неверно',body:'Разные по форме фигуры могут занимать одинаковую площадь.',activity:{id:'l77-p18',type:'choice',prompt:'Если площади двух фигур равны, то сами фигуры обязательно равны?',options:['нет','да'],answer:'нет',hint:'Равновеликие фигуры не обязаны совпадать.',explanation:'Нет. Равенство площадей не гарантирует равенство фигур.'},visual:'equal',sourceExercise:'Диктант 18 · № 8(2)'},
{id:'l77-statement-3',kind:'quiz',eyebrow:'Диктант 18 · № 8(3)',title:'Для квадратов обратимость работает',body:'Площадь квадрата однозначно определяет длину его положительной стороны.',activity:{id:'l77-p19',type:'choice',prompt:'Если два квадрата имеют равные площади, то они равны?',options:['да','нет'],answer:'да',hint:'a²=b² для положительных длин сторон означает a=b.',explanation:'Да. У квадратов равная площадь означает равную сторону.'},visual:'square',sourceExercise:'Диктант 18 · № 8(3)'},
{id:'l77-statement-4',kind:'quiz',eyebrow:'Диктант 18 · № 8(4)',title:'Равный периметр не фиксирует площадь',body:'При одном и том же полупериметре стороны прямоугольников могут быть разными.',activity:{id:'l77-p20',type:'choice',prompt:'Если два прямоугольника имеют равные периметры, то их площади обязательно равны?',options:['нет','да'],answer:'нет',hint:'Например, 1×5 и 2×4 имеют одинаковый периметр 12, но площади 5 и 8.',explanation:'Нет. Равенство периметров не гарантирует равенство площадей.'},visual:'verify',sourceExercise:'Диктант 18 · № 8(4)'},
{id:'l77-593-source',kind:'model',eyebrow:'№ 593 · source checkpoint',title:'Рисунок № 593 не реконструируем',body:'Технологическая карта включает № 593, а авторский раздел ответов отсылает к рисунку 224. Полное условие и исходный рисунок в доступном извлечении не восстановлены достаточно надёжно, поэтому приложение не заменяет их приблизительной схемой.',note:'Выполни № 593 по исходному рисунку учебника. Здесь важна точность исходной геометрической конфигурации.',visual:'construct',sourceExercise:'№ 593 · source checkpoint · ответ: рис. 224'},
{id:'l77-594-author',kind:'guided',eyebrow:'№ 594 · авторское указание',title:'Конструкция проверяется через площади квадратов',body:'Полный рисунок задания не реконструируем, но авторское указание подтверждает две идеи: 25 можно представить как 3²+4², а 36 нельзя представить как сумму квадратов двух положительных натуральных чисел.',note:'Это именно подтверждённое авторское указание к № 594, а не восстановленная формулировка задания.',visual:'construct',sourceExercise:'№ 594 · авторское указание'},
{id:'l77-594-check',kind:'practice',eyebrow:'№ 594 · подтверждённая идея',title:'Проверка первой конструкции',body:'Квадраты со сторонами 3 см и 4 см имеют площади 9 см² и 16 см².',activity:{id:'l77-p21',type:'input',prompt:'3²+4² = ?',answer:'25',hint:'9+16.',explanation:'3²+4²=9+16=25. Поэтому авторская конструкция для площади 25 возможна.'},visual:'construct',sourceExercise:'№ 594 · авторское указание'},
{id:'l77-597-source',kind:'model',eyebrow:'Повторение · № 597',title:'Повторение по точному источнику',body:'Технологическая карта назначает № 597 как повторение. Полное условие именно этого номера из используемого издания в доступном извлечении не восстановлено надёжно, поэтому оставляем явный source-checkpoint.',note:'Реши № 597 непосредственно по учебнику. Приложение не подменяет номер заданием из другого издания или другой программы.',visual:'map',sourceExercise:'№ 597 · source checkpoint'},
{id:'l77-reflection',kind:'model',eyebrow:'Рефлексия',title:'Какой инструмент ты теперь выбираешь без подсказки?',body:'Сформулируй для себя три решения: когда сначала переводить единицы, когда восстанавливать сторону через деление площади и когда искать контрпример вместо вычисления.',visual:'verify'},
{id:'l77-summary',kind:'summary',eyebrow:'Итог урока 77 · итог § 21',title:'Тема площади собрана в единую систему',body:'Ты связываешь площадь и периметр, решаешь прямые и обратные задачи, работаешь с равновеликостью, понимаешь квадрат масштабного коэффициента для площади и отличаешь верные свойства от ложных обратных утверждений.',note:'Обязательная практика: 20 задач / ровно 50 ответов. § 21 завершён. Следующий урок 78 открывает § 22 и остаётся заблокирован до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'ΣS',map:'§21',rectangle:'a·b',square:'a²',scale:'×k',convert:'↔',equal:'=',verify:'✓',construct:'◇',final:'77'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='rectangle'?'S=ab · P=2(a+b)':kind==='square'?'S=a² · P=4a':kind==='scale'?'стороны ×k → площадь ×k²':kind==='convert'?'см² ↔ дм² ↔ м² ↔ а ↔ га':kind==='equal'?'равновеликость → одинаковая площадь':kind==='construct'?'площадь проверяет конструкцию':'итог площади · § 21'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventySevenStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function AreaSynthesisPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventySevenStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventySevenStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==77||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventySevenStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventySevenStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player area-synthesis-player" data-lesson-number="77" data-source-reference="Мерзляк § 21 · технологическая карта урока 77 · № 584, 586, 587, 593, 594; повторение № 597" data-source-exercise-range="584,586,587,593,594,597"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventySevenStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonSeventySevenStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
