import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'multiply'|'division'|'remainder'|'power'|'area'|'solid'|'volume'|'tree'|'test'|'verify'|'final';
export type LessonEightyEightStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceItem?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-88-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightyEightStages:LessonEightyEightStage[]=[
{id:'l88-mission',kind:'story',eyebrow:'Урок 88 · повторение главы 3 · 1 из 2',title:'Глава 3 как единая система',body:'Перед контрольной №5 у нас два урока повторения. Сегодня сначала восстановим карту правил §§16–24, затем полностью пройдём авторское «Задание №3 “Проверьте себя”» из 12 вопросов.',note:'Источник: учебник Мерзляка, «Проверьте себя» №3, с.167–168, и «Итоги главы 3», с.168–169. Отдельной технологической карты для уроков 88–89 в методическом пособии нет.',visual:'mission'},
{id:'l88-map',kind:'model',eyebrow:'Итоги главы 3',title:'Девять тем — четыре больших блока',body:'Вычисления: умножение, свойства, деление, остаток и степень. Геометрия: площадь, параллелепипед, пирамида и объём. Комбинаторика: полный перебор и дерево вариантов. На контрольной важно не помнить номер параграфа, а узнавать нужную модель.',visual:'verify'},
{id:'l88-multiply-model',kind:'model',eyebrow:'§§16–17 · умножение',title:'Произведение и свойства',body:'Переместительное свойство меняет порядок множителей, сочетательное — группировку, распределительное раскрывает или собирает скобки. Особые случаи: a·1=a и a·0=0.',visual:'multiply'},
{id:'l88-multiply-check',kind:'practice',eyebrow:'Свойства умножения',title:'Собери удобное произведение',body:'В произведении 25·17·4 удобно сначала объединить 25 и 4.',activity:{id:'l88-p1',type:'input',prompt:'Вычисли 25·17·4.',answer:'1700',hint:'25·4=100.',explanation:'По переместительному и сочетательному свойствам 25·17·4=(25·4)·17=100·17=1700.'},visual:'multiply'},
{id:'l88-distributive-check',kind:'practice',eyebrow:'Распределительное свойство',title:'Общий множитель экономит действия',body:'Выражение 167·92−92·67 имеет общий множитель 92.',activity:{id:'l88-p2',type:'input',prompt:'Вычисли удобным способом.',answer:'9200',hint:'92·(167−67).',explanation:'167·92−92·67=92·(167−67)=92·100=9200.'},visual:'multiply'},
{id:'l88-division-model',kind:'model',eyebrow:'§18 · деление',title:'Деление проверяется умножением',body:'Равенство a:b=c верно тогда, когда b·c=a. На нуль делить нельзя. Для натурального a: a:1=a, a:a=1, 0:a=0.',visual:'division'},
{id:'l88-division-check',kind:'practice',eyebrow:'Деление · обратная связь',title:'Восстанови делимое',body:'Если частное 48, а делитель 25, то делимое находится умножением.',activity:{id:'l88-p3',type:'input',prompt:'Чему равно делимое?',answer:'1200',hint:'25·48.',explanation:'25·48=1200, значит 1200:25=48.'},visual:'division'},
{id:'l88-remainder-model',kind:'model',eyebrow:'§19 · деление с остатком',title:'Два условия правильной записи',body:'При делении с остатком a=b·q+r, где q — неполное частное, r — остаток. Обязательно 0≤r<b: остаток всегда меньше делителя.',visual:'remainder'},
{id:'l88-remainder-check',kind:'practice',eyebrow:'Деление с остатком',title:'Проверь и равенство, и границу остатка',body:'Разделим 478 на 15: 15·31=465.',activity:{id:'l88-p4',type:'input',prompt:'Каков остаток?',answer:'13',hint:'478−465.',explanation:'478=15·31+13, и 13<15, значит остаток 13.'},visual:'remainder'},
{id:'l88-power-model',kind:'model',eyebrow:'§20 · степень',title:'Показатель говорит, сколько множителей',body:'aⁿ — произведение n одинаковых множителей a. a² называют квадратом числа, a³ — кубом числа. В выражениях степень выполняют раньше умножения, деления, сложения и вычитания.',visual:'power'},
{id:'l88-power-check',kind:'practice',eyebrow:'Степень · вычисление',title:'Не умножай основание на показатель',body:'Запись 3⁴ означает четыре множителя, равных 3.',activity:{id:'l88-p5',type:'input',prompt:'Вычисли 3⁴.',answer:'81',hint:'3·3·3·3.',explanation:'3⁴=3·3·3·3=81.'},visual:'power'},
{id:'l88-area-model',kind:'model',eyebrow:'§21 · площадь',title:'Площадь измеряется квадратными единицами',body:'Для прямоугольника S=ab, для квадрата S=a². Перед вычислением длины должны быть выражены в одинаковых единицах. 1 га — единица площади.',visual:'area'},
{id:'l88-area-check',kind:'practice',eyebrow:'Площадь · применение',title:'Сначала найди вторую сторону',body:'Одна сторона прямоугольника 14 см, вторая в 3 раза больше.',activity:{id:'l88-p6',type:'input',prompt:'Найди площадь, см².',answer:'588',hint:'Вторая сторона 14·3=42 см.',explanation:'S=14·42=588 см².'},visual:'area'},
{id:'l88-solid-model',kind:'model',eyebrow:'§22 · параллелепипед',title:'Рёбра, грани и поверхность',body:'У прямоугольного параллелепипеда 6 граней и 12 рёбер. Площадь поверхности равна сумме площадей всех шести граней; для куба с ребром a она равна 6a².',visual:'solid'},
{id:'l88-solid-check',kind:'practice',eyebrow:'Куб · поверхность',title:'Шесть одинаковых квадратов',body:'Ребро куба равно 3 см.',activity:{id:'l88-p7',type:'input',prompt:'Найди площадь поверхности куба, см².',answer:'54',hint:'6·3².',explanation:'Площадь одной грани 9 см², всех шести — 54 см².'},visual:'solid'},
{id:'l88-volume-model',kind:'model',eyebrow:'§23 · объём',title:'Три измерения дают кубические единицы',body:'Объём прямоугольного параллелепипеда V=abc, а также V=Sh. Для куба V=a³. Все линейные размеры перед вычислением должны быть в одной единице.',visual:'volume'},
{id:'l88-volume-check',kind:'practice',eyebrow:'Объём · применение',title:'Найди неизвестное измерение',body:'Объём 120 000 см³, длина 60 см, ширина 40 см.',activity:{id:'l88-p8',type:'input',prompt:'Какова высота, см?',answer:'50',hint:'120000:(60·40).',explanation:'60·40=2400, поэтому h=120000:2400=50 см.'},visual:'volume'},
{id:'l88-comb-model',kind:'model',eyebrow:'§24 · комбинаторика',title:'Считай конечные ветви',body:'Если последовательные выборы независимы, число вариантов перемножается. Если есть ограничения, сначала оставь только допустимые ветви. Полноту удобно проверять деревом вариантов.',visual:'tree'},
{id:'l88-comb-check',kind:'practice',eyebrow:'Комбинаторика · правило произведения',title:'Три независимых выбора',body:'Есть 3 вида напитка, 4 вида выпечки и 2 вида фруктов; выбирают по одному из каждой группы.',activity:{id:'l88-p9',type:'input',prompt:'Сколько наборов?',answer:'24',hint:'3·4·2.',explanation:'Каждый из 3 напитков сочетается с 4 видами выпечки и 2 фруктами: 3·4·2=24.'},visual:'tree'},
{id:'l88-test-intro',kind:'guided',eyebrow:'Учебник · «Проверьте себя» №3',title:'Теперь — авторская диагностика без перестановок',body:'Следующие 12 вопросов идут в исходном порядке учебника. Мы не меняем условия и варианты ответов. После каждого выбора приложение объяснит математическую причину.',note:'Ключ учебника: ВААГБГББВВБА.',visual:'test'},
{id:'l88-test-01',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 1',title:'Единица площади',body:'Какую из данных единиц измерения используют при измерении площади?',sourceItem:'1',activity:{id:'l88-p10',type:'choice',prompt:'Выбери ответ.',options:['1 см','1 с','1 га','1 г'],answer:'1 га',hint:'Площадь измеряют квадратными единицами и специальными единицами площади.',explanation:'Гектар — единица площади, поэтому верный ответ В: 1 га.'},visual:'area'},
{id:'l88-test-02',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 2',title:'Уравнение с произведением',body:'Чему равен корень уравнения (x−28)·16=1632?',sourceItem:'2',activity:{id:'l88-p11',type:'choice',prompt:'Выбери ответ.',options:['130','120','60','40'],answer:'130',hint:'Сначала найди x−28: 1632:16.',explanation:'1632:16=102, поэтому x−28=102 и x=130. Ответ А.'},visual:'division'},
{id:'l88-test-03',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 3',title:'Коэффициент буквенного выражения',body:'Упростите выражение 52·m·3.',sourceItem:'3',activity:{id:'l88-p12',type:'choice',prompt:'Выбери ответ.',options:['156m','52m','55m','126m'],answer:'156m',hint:'Сгруппируй числовые множители.',explanation:'52·3=156, значит выражение равно 156m. Ответ А.'},visual:'multiply'},
{id:'l88-test-04',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 4',title:'Раскрытие скобок',body:'Укажите верное равенство.',sourceItem:'4',activity:{id:'l88-p13',type:'choice',prompt:'Что верно?',options:['2(5+x)=5+2x','2(5+x)=12x','2(5+x)=10+x','2(5+x)=10+2x'],answer:'2(5+x)=10+2x',hint:'Умножь 2 на каждое слагаемое в скобках.',explanation:'По распределительному свойству 2·5+2·x=10+2x. Ответ Г.'},visual:'multiply'},
{id:'l88-test-05',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 5',title:'Приведение подобных слагаемых',body:'Чему равен корень уравнения 7x+x−5x=132?',sourceItem:'5',activity:{id:'l88-p14',type:'choice',prompt:'Выбери ответ.',options:['66','44','12','11'],answer:'44',hint:'7x+x−5x=3x.',explanation:'3x=132, поэтому x=44. Ответ Б.'},visual:'multiply'},
{id:'l88-test-06',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 6',title:'Граница остатка',body:'Укажите число, которое может быть остатком при делении натурального числа a на 98.',sourceItem:'6',activity:{id:'l88-p15',type:'choice',prompt:'Выбери ответ.',options:['102','100','98','96'],answer:'96',hint:'Остаток должен быть меньше 98.',explanation:'Из вариантов только 96 меньше 98. Ответ Г.'},visual:'remainder'},
{id:'l88-test-07',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 7',title:'Догоняющее движение',body:'Из двух сёл, расстояние между которыми 18 км, одновременно в одном направлении отправились пешеход и велосипедист. Пешеход шёл впереди со скоростью 3 км/ч, велосипедист ехал 12 км/ч. Через сколько часов велосипедист догонит пешехода?',sourceItem:'7',activity:{id:'l88-p16',type:'choice',prompt:'Выбери ответ.',options:['1 ч','2 ч','3 ч','4 ч'],answer:'2 ч',hint:'Скорость сближения 12−3=9 км/ч.',explanation:'18:9=2 ч. Ответ Б.'},visual:'division'},
{id:'l88-test-08',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 8',title:'Квартира и этаж',body:'В каждом подъезде на каждом этаже девятиэтажного дома расположено по 8 квартир. Найдите номер этажа, на котором находится квартира №173.',sourceItem:'8',activity:{id:'l88-p17',type:'choice',prompt:'Выбери ответ.',options:['3','4','5','6'],answer:'4',hint:'В одном подъезде 9·8=72 квартиры; сначала найди положение квартиры 173 внутри её подъезда.',explanation:'Два подъезда содержат 144 квартиры. №173 — 29-я квартира третьего подъезда; квартиры 25–32 этого подъезда находятся на 4-м этаже. Ответ Б.'},visual:'verify'},
{id:'l88-test-09',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 9',title:'Кафель и запас коробок',body:'Стену 6 м × 3 м выкладывают квадратной плиткой со стороной 15 см. В одном ящике 150 плиток. Какое наименьшее количество ящиков надо приобрести?',sourceItem:'9',activity:{id:'l88-p18',type:'choice',prompt:'Выбери ответ.',options:['4 ящика','5 ящиков','6 ящиков','7 ящиков'],answer:'6 ящиков',hint:'Переведи 6 м и 3 м в сантиметры или площадь стены в см².',explanation:'Площадь стены 180000 см², плитки 225 см²; нужно 800 плиток. 800:150=5 остаток 50, значит нужны 6 ящиков. Ответ В.'},visual:'area'},
{id:'l88-test-10',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 10',title:'Высота аквариума',body:'Объём аквариума 120000 см³, длина 60 см, ширина 40 см. Найдите высоту.',sourceItem:'10',activity:{id:'l88-p19',type:'choice',prompt:'Выбери ответ.',options:['5000 см','500 см','50 см','5 см'],answer:'50 см',hint:'h=V:(a·b).',explanation:'120000:(60·40)=50 см. Ответ В.'},visual:'volume'},
{id:'l88-test-11',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 11',title:'Встречный поезд',body:'Машинист пассажирского поезда, двигавшегося со скоростью 56 км/ч, заметил, что встречный товарный поезд со скоростью 34 км/ч прошёл мимо него за 15 с. Какова длина товарного поезда?',sourceItem:'11',activity:{id:'l88-p20',type:'choice',prompt:'Выбери ответ.',options:['360 м','375 м','400 м','425 м'],answer:'375 м',hint:'Скорости встречного движения складываются: 90 км/ч = 25 м/с.',explanation:'25 м/с·15 с=375 м. Ответ Б.'},visual:'division'},
{id:'l88-test-12',kind:'quiz',eyebrow:'Проверьте себя №3 · вопрос 12',title:'Варианты школьного обеда',body:'Есть 2 вида салата, 2 вида первого блюда и 2 вида второго. Обед состоит из одного салата, одного первого и одного второго блюда.',sourceItem:'12',activity:{id:'l88-p21',type:'choice',prompt:'Сколько вариантов обеда?',options:['8','12','9','3'],answer:'8',hint:'Три независимых выбора по 2 варианта.',explanation:'2·2·2=8 вариантов. Ответ А.'},visual:'tree'},
{id:'l88-diagnostic',kind:'model',eyebrow:'Диагностика',title:'Ключ — не оценка, а карта слабых мест',body:'Вопросы 2–5 проверяют вычисления и свойства, 6 — остаток, 7 и 11 — движение, 1 и 9 — площадь, 10 — объём, 12 — комбинаторику. Ошибка показывает конкретную тему для повторения на уроке 89.',note:'Авторский ключ всех 12 вопросов: ВААГБГББВВБА.',visual:'test'},
{id:'l88-correction',kind:'model',eyebrow:'Самопроверка',title:'Исправляй причину, а не только ответ',body:'Для каждой ошибки задай три вопроса: какое правило нужно было распознать, где произошло неверное действие, как проверить результат обратным действием, оценкой или единицами измерения.',visual:'verify'},
{id:'l88-next',kind:'story',eyebrow:'Что дальше',title:'Урок 89 — коррекция и контрольная готовность',body:'Сегодня мы получили честную диагностику всей главы. На следующем уроке повторения соберём смешанные задачи именно по типам контрольной №5 и отдельно отработаем места, где легко ошибиться.',note:'Урок 90 остаётся контрольной работой №5.',visual:'verify'},
{id:'l88-summary',kind:'summary',eyebrow:'Итог урока 88',title:'Диагностическое повторение главы 3 завершено',body:'Ты восстановил опорные правила §§16–24 и прошёл все 12 вопросов авторского «Проверьте себя» №3. Обязательная практика ниже закрепит те же связи ещё на 20 задачах и подготовит данные для урока 89.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'Г3',multiply:'a·b',division:'a:b',remainder:'r<b',power:'aⁿ',area:'S',solid:'▣',volume:'V',tree:'Y',test:'12',verify:'✓',final:'88'};const captions:Record<VisualKind,string>={mission:'повторяем главу 3',multiply:'умножение и свойства',division:'деление и обратная проверка',remainder:'неполное частное и остаток',power:'степень числа',area:'квадратные единицы',solid:'грани и рёбра',volume:'кубические единицы',tree:'полный перебор вариантов',test:'авторская диагностика',verify:'проверка решения',final:'первый урок повторения завершён'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{captions[kind]}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyEightStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function ChapterThreeReviewPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyEightStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyEightStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==88||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyEightStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyEightStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player chapter-three-review-player" data-lesson-number="88" data-source-reference="Мерзляк · глава 3 · Задание №3 «Проверьте себя» с.167–168 · Итоги главы 3 с.168–169" data-source-exercise-range="chapter3-self-check-1-12"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceItem}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area" data-checked-problem={activity.id}><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyEightStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyEightStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
