import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'remainder'|'area'|'cube'|'solid'|'volume'|'field'|'digits'|'edges'|'rehearsal'|'verify'|'final';
export type LessonEightyNineStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceItem?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-89-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightyNineStages:LessonEightyNineStage[]=[
{id:'l89-mission',kind:'story',eyebrow:'Урок 89 · повторение главы 3 · 2 из 2',title:'Исправляем слабые места перед контрольной №5',body:'На уроке 88 мы прошли авторскую диагностику всей главы. Сегодня не повторяем те же вопросы: тренируем восемь типов задач, которые проверяет контрольная №5, но на других числах — чтобы отработать метод, а не запомнить готовые ответы.',note:'Источник структуры: методическое пособие Мерзляка — уроки 88–89 «Повторение и систематизация учебного материала»; контрольная №5 проверяет деление с остатком, площадь, куб и параллелепипед, объём и комбинаторику. Отдельной технологической карты для уроков повторения нет.',visual:'mission'},
{id:'l89-source-map',kind:'model',eyebrow:'Перед контрольной №5',title:'Восемь типов задач — восемь алгоритмов',body:'1) деление с остатком; 2) площадь прямоугольника; 3) куб: объём и поверхность; 4) объём параллелепипеда; 5) восстановление делимого; 6) гектары и периметр; 7) перебор трёхзначных чисел; 8) сумма длин рёбер. Все тренировочные числа в этом уроке специально отличаются от контрольной.',visual:'verify'},
{id:'l89-scope-check',kind:'practice',eyebrow:'Карта готовности',title:'Сначала отдели изученное от следующей главы',body:'Контрольная №5 завершает главу 3. Обыкновенные дроби начнутся только после неё.',activity:{id:'l89-p1',type:'choice',prompt:'Какая тема НЕ входит в контрольную №5?',options:['Деление с остатком','Площадь прямоугольника','Обыкновенные дроби','Объём параллелепипеда'],answer:'Обыкновенные дроби',hint:'Контрольная №5 стоит перед §25.',explanation:'Обыкновенные дроби — тема главы 4, поэтому в контрольную №5 они не входят.'},visual:'verify'},
{id:'l89-remainder-model',kind:'model',eyebrow:'Тип 1 · деление с остатком',title:'Запись должна выполнять два условия',body:'Если a:b=q (ост. r), то a=b·q+r и 0≤r<b. Сначала ищем наибольшее произведение b·q, не превосходящее a, затем вычитаем.',visual:'remainder'},
{id:'l89-remainder-q',kind:'practice',eyebrow:'Теневая репетиция · тип 1',title:'Найди неполное частное',body:'Раздели 563 на 17. Число 17·33=561, а 17·34 уже больше 563.',activity:{id:'l89-p2',type:'input',prompt:'Чему равно неполное частное?',answer:'33',hint:'Выбери максимальное q, для которого 17q≤563.',explanation:'17·33=561≤563, а 17·34=578>563. Значит неполное частное 33.'},visual:'remainder'},
{id:'l89-remainder-r',kind:'practice',eyebrow:'Теневая репетиция · тип 1',title:'Остаток — разница до делимого',body:'Мы уже нашли 17·33=561.',activity:{id:'l89-p3',type:'input',prompt:'Каков остаток при делении 563 на 17?',answer:'2',hint:'563−561.',explanation:'563=17·33+2, значит остаток равен 2.'},visual:'remainder'},
{id:'l89-remainder-proof',kind:'quiz',eyebrow:'Контроль ошибки',title:'Запись должна быть доказана',body:'Одного вычисления 563−561 недостаточно: остаток нужно сравнить с делителем.',activity:{id:'l89-p4',type:'choice',prompt:'Какая проверка полностью подтверждает ответ?',options:['563=17·33+2 и 2<17','563=17·33+2 и 2<33','563=17·34−15','33<563'],answer:'563=17·33+2 и 2<17',hint:'Вспомни формулу a=bq+r и условие r<b.',explanation:'Правильная проверка одновременно подтверждает равенство 563=17·33+2 и ограничение 2<17.'},visual:'remainder'},
{id:'l89-area-model',kind:'model',eyebrow:'Тип 2 · площадь прямоугольника',title:'Связь сторон сначала, формула площади потом',body:'Если одна сторона дана через другую, не подставляй отношение прямо в S=ab. Сначала найди обе длины, затем перемножь их в одинаковых единицах.',visual:'area'},
{id:'l89-area-side',kind:'practice',eyebrow:'Теневая репетиция · тип 2',title:'Восстанови вторую сторону',body:'Одна сторона прямоугольника равна 16 см, вторая в 3 раза больше.',activity:{id:'l89-p5',type:'input',prompt:'Чему равна вторая сторона, см?',answer:'48',hint:'16·3.',explanation:'48 см.'},visual:'area'},
{id:'l89-area-value',kind:'practice',eyebrow:'Теневая репетиция · тип 2',title:'Теперь вычисли площадь',body:'Стороны прямоугольника 16 см и 48 см.',activity:{id:'l89-p6',type:'input',prompt:'Найди площадь, см².',answer:'768',hint:'16·48.',explanation:'S=16·48=768 см².'},visual:'area'},
{id:'l89-cube-model',kind:'model',eyebrow:'Тип 3 · куб',title:'Не смешивай объём и площадь поверхности',body:'Для куба с ребром a: V=a³ — кубические единицы; Sпов=6a² — квадратные единицы. Это два разных результата и две разные размерности.',visual:'cube'},
{id:'l89-cube-volume',kind:'practice',eyebrow:'Теневая репетиция · тип 3',title:'Объём куба',body:'Ребро куба равно 5 см.',activity:{id:'l89-p7',type:'input',prompt:'Найди объём куба, см³.',answer:'125',hint:'5³.',explanation:'V=5³=125 см³.'},visual:'cube'},
{id:'l89-cube-surface',kind:'practice',eyebrow:'Теневая репетиция · тип 3',title:'Площадь поверхности куба',body:'У куба шесть одинаковых квадратных граней со стороной 5 см.',activity:{id:'l89-p8',type:'input',prompt:'Найди площадь поверхности, см².',answer:'150',hint:'6·5².',explanation:'Sпов=6·25=150 см².'},visual:'cube'},
{id:'l89-prism-model',kind:'model',eyebrow:'Тип 4 · объём параллелепипеда',title:'Сначала восстанови три измерения',body:'Формула V=abc работает только после того, как известны длина, ширина и высота. В задачах контрольного типа два измерения часто заданы через третье.',visual:'solid'},
{id:'l89-prism-width',kind:'practice',eyebrow:'Теневая репетиция · тип 4',title:'Найди ширину',body:'Длина параллелепипеда 20 см, ширина в 2 раза меньше длины.',activity:{id:'l89-p9',type:'input',prompt:'Ширина, см?',answer:'10',hint:'20:2.',explanation:'Ширина равна 10 см.'},visual:'solid'},
{id:'l89-prism-height',kind:'practice',eyebrow:'Теневая репетиция · тип 4',title:'Найди высоту',body:'Высота на 6 см больше ширины 10 см.',activity:{id:'l89-p10',type:'input',prompt:'Высота, см?',answer:'16',hint:'10+6.',explanation:'Высота равна 16 см.'},visual:'solid'},
{id:'l89-prism-volume',kind:'practice',eyebrow:'Теневая репетиция · тип 4',title:'Три измерения готовы',body:'Длина 20 см, ширина 10 см, высота 16 см.',activity:{id:'l89-p11',type:'input',prompt:'Найди объём, см³.',answer:'3200',hint:'20·10·16.',explanation:'V=20·10·16=3200 см³.'},visual:'volume'},
{id:'l89-dividend-model',kind:'model',eyebrow:'Тип 5 · восстановление делимого',title:'Формула остаточного деления работает в обратную сторону',body:'Если известны делитель b, неполное частное q и остаток r, то делимое a=bq+r. После вычисления обязательно проверь, что r<b.',visual:'remainder'},
{id:'l89-dividend-value',kind:'practice',eyebrow:'Теневая репетиция · тип 5',title:'Восстанови делимое',body:'Делитель 13, неполное частное 8, остаток 5.',activity:{id:'l89-p12',type:'input',prompt:'Чему равно делимое?',answer:'109',hint:'13·8+5.',explanation:'a=13·8+5=104+5=109; остаток 5<13.'},visual:'remainder'},
{id:'l89-field-model',kind:'model',eyebrow:'Тип 6 · гектары и периметр',title:'Площадь сначала переведи в квадратные метры',body:'1 га=10 000 м². Если известны площадь поля и одна сторона, вторую сторону находим делением S:a, затем P=2(a+b).',visual:'field'},
{id:'l89-field-square',kind:'practice',eyebrow:'Теневая репетиция · тип 6',title:'Переведи гектары',body:'Площадь прямоугольного поля равна 8 га.',activity:{id:'l89-p13',type:'input',prompt:'Сколько это квадратных метров?',answer:'80000',hint:'8·10000.',explanation:'8 га=80 000 м².'},visual:'field'},
{id:'l89-field-length',kind:'practice',eyebrow:'Теневая репетиция · тип 6',title:'Найди вторую сторону',body:'Площадь 80 000 м², ширина 200 м.',activity:{id:'l89-p14',type:'input',prompt:'Найди длину поля, м.',answer:'400',hint:'80000:200.',explanation:'Длина равна 400 м.'},visual:'field'},
{id:'l89-field-perimeter',kind:'practice',eyebrow:'Теневая репетиция · тип 6',title:'Периметр — не площадь',body:'Стороны поля 400 м и 200 м.',activity:{id:'l89-p15',type:'input',prompt:'Найди периметр, м.',answer:'1200',hint:'2·(400+200).',explanation:'P=2·600=1200 м.'},visual:'field'},
{id:'l89-digits-model',kind:'model',eyebrow:'Тип 7 · комбинаторика',title:'Ноль нельзя ставить в сотни',body:'Чтобы составить трёхзначные числа без повторения из цифр 0, 3 и 7, удобно перечислить допустимые первые цифры 3 и 7, а затем переставить две оставшиеся цифры.',visual:'digits'},
{id:'l89-digits-count',kind:'practice',eyebrow:'Теневая репетиция · тип 7',title:'Сколько допустимых чисел?',body:'Используются только цифры 0, 3 и 7, цифры не повторяются.',activity:{id:'l89-p16',type:'input',prompt:'Сколько трёхзначных чисел можно составить?',answer:'4',hint:'Первая цифра: 2 варианта; после неё оставшиеся цифры можно переставить 2 способами.',explanation:'2·2=4 числа.'},visual:'digits'},
{id:'l89-digits-list',kind:'quiz',eyebrow:'Теневая репетиция · тип 7',title:'Полный список — лучшая проверка',body:'Список должен содержать все варианты и ни одного числа, начинающегося с нуля.',activity:{id:'l89-p17',type:'choice',prompt:'Какой список полный?',options:['307, 370, 703, 730','037, 073, 307, 370, 703, 730','307, 370, 703','303, 337, 707, 773'],answer:'307, 370, 703, 730',hint:'Трёхзначная запись не начинается с 0, а цифры не повторяются.',explanation:'Допустимы ровно 307, 370, 703 и 730.'},visual:'digits'},
{id:'l89-edges-model',kind:'model',eyebrow:'Тип 8 · сумма рёбер',title:'Каждое измерение встречается на четырёх параллельных рёбрах',body:'У прямоугольного параллелепипеда сумма длин всех 12 рёбер равна 4(a+b+c). Поэтому сначала делим общую сумму на 4, затем вычитаем два известных измерения.',visual:'edges'},
{id:'l89-edges-sum',kind:'practice',eyebrow:'Теневая репетиция · тип 8',title:'Найди сумму трёх измерений',body:'Сумма длин всех рёбер равна 132 см.',activity:{id:'l89-p18',type:'input',prompt:'Чему равно a+b+c, см?',answer:'33',hint:'132:4.',explanation:'a+b+c=33 см.'},visual:'edges'},
{id:'l89-edges-third',kind:'practice',eyebrow:'Теневая репетиция · тип 8',title:'Вычти два известных измерения',body:'a+b+c=33 см, два измерения равны 14 см и 10 см.',activity:{id:'l89-p19',type:'input',prompt:'Найди третье измерение, см.',answer:'9',hint:'33−14−10.',explanation:'c=9 см.'},visual:'edges'},
{id:'l89-rehearsal-model',kind:'guided',eyebrow:'Финальная репетиция',title:'Две задачи подряд без подсказки из названия темы',body:'На контрольной тебе не скажут, какой параграф использовать. Поэтому сейчас решаем две короткие задачи вперемешку и выбираем алгоритм по условию.',visual:'rehearsal'},
{id:'l89-rehearsal-remainder',kind:'challenge',eyebrow:'Финальная репетиция · 1',title:'Определи остаток самостоятельно',body:'Выполни деление 742:23 с остатком.',activity:{id:'l89-p20',type:'input',prompt:'Каков остаток?',answer:'6',hint:'23·32=736.',explanation:'742=23·32+6, причём 6<23.'},visual:'rehearsal'},
{id:'l89-rehearsal-comb',kind:'challenge',eyebrow:'Финальная репетиция · 2',title:'Следи за ведущим нулём',body:'Используются только цифры 0, 4 и 9, без повторений.',activity:{id:'l89-p21',type:'input',prompt:'Сколько трёхзначных чисел можно составить?',answer:'4',hint:'Первая цифра не ноль.',explanation:'Допустимы 409, 490, 904, 940 — всего 4.'},visual:'rehearsal'},
{id:'l89-error-map',kind:'model',eyebrow:'Карта типичных ошибок',title:'Восемь красных флажков',body:'Остаток не меньше делителя; площадь и периметр перепутаны; квадратные и кубические единицы смешаны; не восстановлены все измерения; забыта формула a=bq+r; гектары не переведены; ноль поставлен первым; сумма рёбер не поделена на 4. Перед сдачей проверь именно эти места.',visual:'verify'},
{id:'l89-checklist',kind:'model',eyebrow:'Стратегия контрольной',title:'Сначала надёжные баллы, затем сложные задачи',body:'Прочитай всю работу. Реши короткие алгоритмические задания, затем геометрию и составные задачи. После каждого результата подпиши единицы. В конце сделай обратную проверку формулой или подстановкой.',visual:'verify'},
{id:'l89-practice-bridge',kind:'guided',eyebrow:'Обязательная практика',title:'После урока — ещё 20 задач / 50 ответов',body:'Тренировочная мастерская смешивает все восемь типов, чтобы метод выбирался по смыслу условия. Она не копирует задания контрольной №5 и не раскрывает её ответы.',visual:'verify'},
{id:'l89-summary',kind:'summary',eyebrow:'Урок 89 · итог',title:'Глава 3 готова к контрольной №5',body:'Ты повторил все восемь контрольных моделей на новых числах: остаток, площадь, куб, объём, восстановление делимого, гектары и периметр, перебор чисел и сумму рёбер. Следующий урок 90 — контрольная работа №5; до её сдачи подсказки и разбор ответов должны быть недоступны.',note:'Урок 89 завершает двухурочное повторение главы 3.',visual:'final'}
];

function loadSaved():Saved|undefined{try{const raw=localStorage.getItem(KEY);if(!raw)return;const parsed=JSON.parse(raw) as Saved;return parsed?.version===1?parsed:undefined}catch{return undefined}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function ChapterThreeCorrectionPlayer(){const saved=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(()=>Math.min(saved?.stageIndex??0,lessonEightyNineStages.length-1));const[responses,setResponses]=useState<Record<string,string>>(saved?.responses??{});const[checked,setChecked]=useState<Record<string,boolean>>(saved?.checked??{});const[results,setResults]=useState<Record<string,boolean>>(saved?.results??{});const[attempts,setAttempts]=useState<Record<string,number>>(saved?.attempts??{});const stage=lessonEightyNineStages[stageIndex];const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const wasChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;const attemptCount=activity?attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attemptCount>=2;
useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results,attempts} satisfies Saved))},[stageIndex,responses,checked,results,attempts]);
useEffect(()=>{const jump=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==89||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.max(0,Math.min(lessonEightyNineStages.length-1,detail.stageIndex)))};window.addEventListener('mathnikita-go-to-stage',jump);return()=>window.removeEventListener('mathnikita-go-to-stage',jump)},[]);
function answer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
function check(){if(!activity)return;const correct=answerMatches(response,activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}));setAttempts(previous=>({...previous,[activity.id]:(previous[activity.id]??0)+1}))}
function go(delta:number){if(delta>0&&!canContinue)return;stopNarration();setStageIndex(index=>Math.max(0,Math.min(lessonEightyNineStages.length-1,index+delta)))}
return <section className="interactive-lesson division-meaning lesson-eighty-nine" data-lesson-number="89"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary summary-card':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><header className="stage-heading"><span>{stage.eyebrow}</span><b>{stageIndex+1} / {lessonEightyNineStages.length}</b></header><div className="stage-copy"><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="stage-note">{stage.note}</aside>:null}</div>{stage.visual?<div className={`lesson-visual visual-${stage.visual}`} aria-hidden="true"><span>{stage.visual==='remainder'?'a=b·q+r':stage.visual==='area'?'S=a·b':stage.visual==='cube'?'V=a³ · S=6a²':stage.visual==='volume'?'V=a·b·c':stage.visual==='field'?'1 га = 10 000 м²':stage.visual==='digits'?'0 ≠ первая цифра':stage.visual==='edges'?'4(a+b+c)':stage.visual==='rehearsal'?'8 типов → 1 стратегия':stage.visual==='final'?'✓ №5':'Глава 3'}</span></div>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'is-selected':''} onClick={()=>answer(option)}>{option}</button>)}</div>:<label className="inline-answer"><span className="sr-only">Ответ</span><input value={response} onChange={event=>answer(event.target.value)} placeholder={activity.placeholder??'Ответ'}/></label>}<button type="button" className="check-button" disabled={!response.trim()} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно':'Пока нет'}</b><span>{isCorrect?activity.explanation:attemptCount>=2?`${activity.hint} ${activity.explanation}`:activity.hint}</span></div>:null}</div>:null}<footer className="lesson-controls"><button type="button" disabled={stageIndex===0} onClick={()=>go(-1)}>← Назад</button><button type="button" disabled={stageIndex===lessonEightyNineStages.length-1||!canContinue} onClick={()=>go(1)}>Дальше →</button></footer></article></section>}
