import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'tree'|'digits'|'sum'|'product'|'zero'|'source'|'repeat'|'homework'|'verify'|'final';
export type LessonEightyFiveStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-85-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightyFiveStages:LessonEightyFiveStage[]=[
{id:'l85-mission',kind:'story',eyebrow:'Урок 85 · § 24 · комбинаторные задачи',title:'Как посчитать все варианты и ничего не пропустить',body:'Начинаем §24. Комбинаторная задача спрашивает, какие варианты возможны или сколько их существует. Сегодня строим систематический перебор, читаем дерево возможных вариантов и учимся быстро считать сочетания независимых выборов.',note:'Точный маршрут первого урока §24: теория; №645, 647, 649, 650; повторение №669(1,2); вопросы 1–2; домашнее №646, 648, 668.',visual:'mission'},
{id:'l85-theory',kind:'model',eyebrow:'§24 · теория',title:'Перебор должен быть полным и без повторов',body:'В комбинаторике недостаточно назвать несколько подходящих примеров. Нужно организовать варианты так, чтобы каждый допустимый вариант появился ровно один раз. Для этого удобно фиксировать первый выбор и последовательно перебирать второй.',visual:'tree',sourceExercise:'§24'},
{id:'l85-tree',kind:'guided',eyebrow:'§24 · дерево возможных вариантов',title:'Каждая ветвь — отдельный выбор',body:'Дерево возможных вариантов показывает ход выбора по шагам. От каждого варианта первого шага отходят ветви второго шага; конечные ветви соответствуют готовым вариантам.',note:'Название «дерево возможных вариантов» используется в теории §24.',visual:'tree',sourceExercise:'§24'},
{id:'l85-645-model',kind:'guided',eyebrow:'№645',title:'Двузначные числа из цифр 1, 2 и 3',body:'Разрешены только цифры 1, 2 и 3, причём цифры могут повторяться. Фиксируем цифру десятков, а затем перебираем три варианта цифры единиц.',note:'Полный список: 11, 12, 13, 21, 22, 23, 31, 32, 33.',visual:'digits',sourceExercise:'№645'},
{id:'l85-645-tens',kind:'practice',eyebrow:'№645 · шаг 1',title:'Выбор цифры десятков',body:'На месте десятков может стоять любая из трёх разрешённых цифр.',activity:{id:'l85-p1',type:'input',prompt:'Сколько вариантов для цифры десятков?',answer:'3',hint:'Доступны 1, 2 и 3.',explanation:'Для десятков есть 3 варианта.'},visual:'digits',sourceExercise:'№645'},
{id:'l85-645-units',kind:'practice',eyebrow:'№645 · шаг 2',title:'После каждого десятка снова три варианта',body:'Повторы разрешены, поэтому после 1, после 2 и после 3 на месте единиц снова можно выбрать 1, 2 или 3.',activity:{id:'l85-p2',type:'input',prompt:'Сколько вариантов единиц после фиксированной цифры десятков?',answer:'3',hint:'Повторы разрешены.',explanation:'После каждого десятка остаются 3 варианта единиц.'},visual:'tree',sourceExercise:'№645'},
{id:'l85-645-product',kind:'practice',eyebrow:'№645 · счёт ветвей',title:'Три группы по три числа',body:'Получаются три ветви первого уровня, и у каждой по три продолжения.',activity:{id:'l85-p3',type:'input',prompt:'3·3 = ? вариантов',answer:'9',hint:'Сложи 3+3+3 или перемножь 3·3.',explanation:'Всего 9 двузначных чисел.'},visual:'product',sourceExercise:'№645'},
{id:'l85-645-check',kind:'practice',eyebrow:'№645 · проверка полноты',title:'Сверь перебор с числом вариантов',body:'Список 11, 12, 13, 21, 22, 23, 31, 32, 33 содержит все ветви дерева и не содержит повторов.',activity:{id:'l85-p4',type:'input',prompt:'Сколько чисел в полном списке №645?',answer:'9',hint:'Посчитай три строки по три числа.',explanation:'В полном списке 9 чисел.'},visual:'verify',sourceExercise:'№645'},
{id:'l85-647-model',kind:'guided',eyebrow:'№647',title:'Теперь ограничение задаёт сумма цифр',body:'Нужно записать все двузначные числа с суммой цифр 6. Перебираем возможную цифру десятков от 1 до 6 и однозначно восстанавливаем цифру единиц.',note:'Получаем 15, 24, 33, 42, 51, 60.',visual:'sum',sourceExercise:'№647'},
{id:'l85-647-first',kind:'practice',eyebrow:'№647 · начало перебора',title:'Минимальная цифра десятков — 1',body:'Если десятки равны 1, до суммы 6 не хватает 5.',activity:{id:'l85-p5',type:'input',prompt:'Какое первое число получается?',answer:'15',hint:'1+5=6.',explanation:'Первый вариант — 15.'},visual:'sum',sourceExercise:'№647'},
{id:'l85-647-count',kind:'practice',eyebrow:'№647 · полнота',title:'Каждому десятку соответствует одна цифра единиц',body:'Пары цифр: 1+5, 2+4, 3+3, 4+2, 5+1, 6+0.',activity:{id:'l85-p6',type:'input',prompt:'Сколько двузначных чисел имеют сумму цифр 6?',answer:'6',hint:'Посчитай перечисленные пары.',explanation:'Таких двузначных чисел 6.'},visual:'tree',sourceExercise:'№647'},
{id:'l85-647-last',kind:'practice',eyebrow:'№647 · конец перебора',title:'Ноль допустим в единицах',body:'Последняя пара 6+0 даёт корректное двузначное число.',activity:{id:'l85-p7',type:'input',prompt:'Какое последнее число в систематическом переборе?',answer:'60',hint:'6+0=6.',explanation:'Последний вариант — 60.'},visual:'zero',sourceExercise:'№647'},
{id:'l85-649-model',kind:'guided',eyebrow:'№649',title:'Сколько двузначных чисел из 4, 5 и 6?',body:'Цифры могут повторяться. Это та же структура выбора, что в №645: три возможности для десятков и три для единиц.',visual:'digits',sourceExercise:'№649'},
{id:'l85-649-tens',kind:'practice',eyebrow:'№649 · первый выбор',title:'Выбираем десятки',body:'Все три цифры ненулевые, поэтому каждая может стоять первой.',activity:{id:'l85-p8',type:'input',prompt:'Сколько вариантов для десятков?',answer:'3',hint:'4, 5 или 6.',explanation:'Для десятков 3 варианта.'},visual:'digits',sourceExercise:'№649'},
{id:'l85-649-units',kind:'practice',eyebrow:'№649 · второй выбор',title:'Выбираем единицы',body:'Повторы разрешены, ограничений на второй выбор нет.',activity:{id:'l85-p9',type:'input',prompt:'Сколько вариантов для единиц после любого десятка?',answer:'3',hint:'Снова 4, 5 или 6.',explanation:'Для единиц 3 варианта.'},visual:'tree',sourceExercise:'№649'},
{id:'l85-649-total',kind:'practice',eyebrow:'№649 · ответ',title:'Правило произведения видно на дереве',body:'У каждой из трёх ветвей первого выбора по три продолжения.',activity:{id:'l85-p10',type:'input',prompt:'Сколько всего двузначных чисел?',answer:'9',hint:'3·3.',explanation:'Можно записать 9 двузначных чисел.'},visual:'product',sourceExercise:'№649'},
{id:'l85-650-model',kind:'guided',eyebrow:'№650',title:'Трёхзначные числа из 0, 1 и 2 без повторов',body:'Здесь два ограничения: цифры не могут повторяться, а 0 не может стоять первым, иначе запись не будет трёхзначным числом.',note:'Допустимые числа: 102, 120, 201, 210.',visual:'zero',sourceExercise:'№650'},
{id:'l85-650-first',kind:'practice',eyebrow:'№650 · сотни',title:'Первый разряд выбираем особенно внимательно',body:'На месте сотен допустимы только 1 и 2.',activity:{id:'l85-p11',type:'input',prompt:'Сколько вариантов для цифры сотен?',answer:'2',hint:'0 впереди запрещён.',explanation:'Для сотен есть 2 варианта: 1 или 2.'},visual:'zero',sourceExercise:'№650'},
{id:'l85-650-second',kind:'practice',eyebrow:'№650 · продолжение ветви',title:'После выбора сотен остаются две цифры',body:'Например, после сотни 1 остаются 0 и 2. Любая из них может стать десятком, а последняя автоматически станет единицей.',activity:{id:'l85-p12',type:'input',prompt:'Сколько вариантов десятков после фиксированной цифры сотен?',answer:'2',hint:'Остаются две неиспользованные цифры.',explanation:'После выбора сотен остаются 2 варианта десятков.'},visual:'tree',sourceExercise:'№650'},
{id:'l85-650-total',kind:'practice',eyebrow:'№650 · ответ',title:'Последний разряд уже определяется',body:'Две возможности для сотен, две для десятков и одна для единиц.',activity:{id:'l85-p13',type:'input',prompt:'2·2·1 = ? трёхзначных числа',answer:'4',hint:'Последняя неиспользованная цифра выбирается автоматически.',explanation:'Получаем 4 числа: 102, 120, 201, 210.'},visual:'product',sourceExercise:'№650'},
{id:'l85-650-zero-ending',kind:'practice',eyebrow:'№650 · проверка списка',title:'Два допустимых числа оканчиваются нулём',body:'В полном списке 120 и 210 имеют 0 в разряде единиц.',activity:{id:'l85-p14',type:'input',prompt:'Сколько допустимых чисел №650 оканчиваются цифрой 0?',answer:'2',hint:'Посмотри на 102, 120, 201, 210.',explanation:'Нулём оканчиваются 120 и 210 — два числа.'},visual:'verify',sourceExercise:'№650'},
{id:'l85-669-model',kind:'guided',eyebrow:'Повторение · №669(1,2)',title:'Выбор одного ученика — тоже комбинаторная задача',body:'В классе 12 девочек и 15 мальчиков. В подпунктах 1–2 нужно посчитать способы выбрать одного человека из заданной группы.',visual:'repeat',sourceExercise:'№669(1,2)'},
{id:'l85-669-girls',kind:'practice',eyebrow:'№669(1)',title:'Выбрать одну девочку',body:'Каждая из 12 девочек даёт отдельный способ выбора.',activity:{id:'l85-p15',type:'input',prompt:'Сколькими способами можно выбрать одну девочку?',answer:'12',hint:'Можно выбрать любую из 12.',explanation:'Есть 12 способов.'},visual:'repeat',sourceExercise:'№669(1)'},
{id:'l85-669-boys',kind:'practice',eyebrow:'№669(2)',title:'Выбрать одного мальчика',body:'Аналогично считаем варианты внутри группы мальчиков.',activity:{id:'l85-p16',type:'input',prompt:'Сколькими способами можно выбрать одного мальчика?',answer:'15',hint:'Можно выбрать любого из 15.',explanation:'Есть 15 способов.'},visual:'repeat',sourceExercise:'№669(2)'},
{id:'l85-questions-source',kind:'model',eyebrow:'Вопросы 1–2 · source checkpoint',title:'Закрепление теории §24',body:'Технологический маршрут первого урока §24 включает вопросы 1–2 после основных задач.',note:'Точная формулировка вопросов используемой редакции не восстановлена с достаточной надёжностью. Поэтому сохраняем авторский checkpoint и не выдаём реконструкцию за текст учебника.',visual:'source',sourceExercise:'Вопросы 1–2 §24'},
{id:'l85-product-rule',kind:'quiz',eyebrow:'§24 · обобщение',title:'Когда варианты образуют независимые шаги',body:'Если первый выбор можно сделать m способами, а после каждого из них второй — n способами, дерево содержит m·n конечных ветвей.',activity:{id:'l85-p17',type:'choice',prompt:'Как получить число конечных вариантов при двух последовательных независимых выборах?',options:['сложить m+n','перемножить m·n','вычесть m−n'],answer:'перемножить m·n',hint:'У каждой из m первых ветвей есть n продолжений.',explanation:'Число конечных вариантов равно m·n.'},visual:'product',sourceExercise:'§24'},
{id:'l85-646-model',kind:'guided',eyebrow:'Домашнее · №646',title:'Цифры 0, 4, 7 и 9 с повторениями',body:'Нужно записать все двузначные числа из цифр 0, 4, 7 и 9. Ноль разрешён в единицах, но не может быть цифрой десятков.',note:'Полный список: 40, 44, 47, 49, 70, 74, 77, 79, 90, 94, 97, 99.',visual:'homework',sourceExercise:'№646'},
{id:'l85-646-count',kind:'practice',eyebrow:'№646 · счёт',title:'Три варианта десятков и четыре единиц',body:'Для десятков доступны 4, 7, 9; для единиц — 0, 4, 7, 9.',activity:{id:'l85-p18',type:'input',prompt:'3·4 = ? двузначных чисел',answer:'12',hint:'Ноль исключаем только из первого разряда.',explanation:'В №646 получается 12 чисел.'},visual:'product',sourceExercise:'№646'},
{id:'l85-648-model',kind:'guided',eyebrow:'Домашнее · №648',title:'Сумма цифр равна 8',body:'Систематический перебор даёт 17, 26, 35, 44, 53, 62, 71, 80.',visual:'sum',sourceExercise:'№648'},
{id:'l85-648-count',kind:'practice',eyebrow:'№648 · ответ',title:'Посчитай найденные пары цифр',body:'Пары идут от 1+7 до 8+0.',activity:{id:'l85-p19',type:'input',prompt:'Сколько двузначных чисел имеют сумму цифр 8?',answer:'8',hint:'17, 26, 35, 44, 53, 62, 71, 80.',explanation:'Всего 8 чисел.'},visual:'sum',sourceExercise:'№648'},
{id:'l85-668-model',kind:'guided',eyebrow:'Домашнее · №668',title:'Конверт и марка: два последовательных выбора',body:'В киоске продаются 5 видов конвертов и 4 вида марок. Для каждого конверта можно выбрать любую из четырёх марок.',visual:'homework',sourceExercise:'№668'},
{id:'l85-668-total',kind:'practice',eyebrow:'№668 · ответ',title:'Пять ветвей, у каждой четыре продолжения',body:'Дерево выбора имеет 5·4 конечных ветвей.',activity:{id:'l85-p20',type:'input',prompt:'Сколькими способами можно выбрать один конверт и одну марку?',answer:'20',hint:'5·4.',explanation:'Есть 20 способов.'},visual:'product',sourceExercise:'№668'},
{id:'l85-leading-zero',kind:'quiz',eyebrow:'№646 · важное ограничение',title:'Ноль впереди меняет разрядность записи',body:'Запись 04 — это число 4, а не двузначное число. Поэтому ветвь с нулём в десятках надо исключить.',activity:{id:'l85-p21',type:'choice',prompt:'Можно ли считать 04 двузначным числом?',options:['да','нет'],answer:'нет',hint:'Ведущий ноль не создаёт новый разряд.',explanation:'Нет. 04 — это запись числа 4, поэтому для двузначных чисел ведущий ноль запрещён.'},visual:'zero',sourceExercise:'№646'},
{id:'l85-homework-map',kind:'model',eyebrow:'Домашний маршрут',title:'№646, 648 и 668 тренируют три разных типа перебора',body:'№646 — выбор цифр с ведущим нулём как ограничением; №648 — перебор пар по заданной сумме; №668 — два последовательных независимых выбора.',visual:'homework',sourceExercise:'№646, 648, 668'},
{id:'l85-source-close',kind:'model',eyebrow:'§24 · проверка метода',title:'Дерево — это способ не потерять ветви',body:'Полный перебор можно записывать списком, таблицей или деревом. Главное — заранее задать порядок выбора, учитывать ограничения на каждом шаге и проверить, что варианты не повторяются.',note:'Вопросы 1–2 остаются привязанными к авторскому источнику без выдуманной формулировки.',visual:'tree',sourceExercise:'§24 · вопросы 1–2'},
{id:'l85-summary',kind:'summary',eyebrow:'Итог урока 85 · §24 начат',title:'Теперь перебор можно строить системно',body:'Ты умеешь считать варианты по дереву, перечислять двузначные числа без пропусков, учитывать сумму цифр, ведущий ноль и запрет повторов, а также использовать произведение числа вариантов на последовательных шагах.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 86 продолжит §24 и остаётся закрытым до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'§24',tree:'Y',digits:'123',sum:'Σ',product:'m·n',zero:'0≠◻',source:'§24',repeat:'↺',homework:'ДЗ',verify:'✓',final:'85'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='tree'?'ветви выбора':kind==='digits'?'фиксируем разряд':kind==='sum'?'перебираем пары':kind==='product'?'считаем конечные ветви':kind==='zero'?'учитываем ограничение':kind==='source'?'авторский источник без реконструкции':kind==='homework'?'самостоятельное закрепление':'комбинаторный перебор'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyFiveStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function CombinatoricsIntroPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyFiveStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyFiveStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==85||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyFiveStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyFiveStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player combinatorics-intro-player" data-lesson-number="85" data-source-reference="Мерзляк § 24 · первый урок · №645, 647, 649, 650 · повторение №669(1,2) · ДЗ №646, 648, 668" data-source-exercise-range="645,647,649,650,669(1,2),646,648,668"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area" data-checked-problem={activity.id}><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="extended-practice" data-practice-task-count="20" data-practice-response-count="50"><strong>Обязательная практика · 20 заданий / 50 ответов</strong><p>Пройди все 20 задач по систематическому перебору, дереву вариантов и ограничениям. Пифагор раскрывает помощь постепенно и не подменяет самостоятельное решение.</p></div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyFiveStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyFiveStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
