import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'pairs'|'product'|'route'|'optimize'|'logic'|'source'|'repeat'|'homework'|'verify'|'final';
export type LessonEightySevenStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-87-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightySevenStages:LessonEightySevenStage[]=[
{id:'l87-mission',kind:'story',eyebrow:'Урок 87 · § 24 · итог',title:'Комбинаторика: выбрать правильную модель',body:'Завершаем §24. Сегодня важно не просто считать варианты, а сначала определить модель: порядок важен или нет, можно ли перемножать независимые выборы, нужно ли перечислять пары, маршруты или варианты знаков.',note:'Точный маршрут: устно №4 с.163; №659, 661, 663, 664, 666, 667; повторение №672; ДЗ №660, 662, 665; дополнительная №673.',visual:'mission'},
{id:'l87-oral-4a',kind:'quiz',eyebrow:'Устно · №4(1) с.163',title:'Квадрат суммы и сумма квадратов',body:'Сравни (4+3)² и 4²+3².',activity:{id:'l87-p1',type:'input',prompt:'На сколько первое выражение больше второго?',answer:'24',hint:'49−25.',explanation:'(4+3)²=49, а 4²+3²=25; разность равна 24.'},visual:'repeat',sourceExercise:'№4(1) с.163'},
{id:'l87-oral-4b',kind:'quiz',eyebrow:'Устно · №4(2) с.163',title:'Разность квадратов',body:'Сравни 10²−8² и (10−8)².',activity:{id:'l87-p2',type:'input',prompt:'На сколько первое выражение больше второго?',answer:'32',hint:'36−4.',explanation:'100−64=36, а 2²=4; разность равна 32.'},visual:'repeat',sourceExercise:'№4(2) с.163'},
{id:'l87-oral-4c',kind:'quiz',eyebrow:'Устно · №4(3) с.163',title:'Разность кубов',body:'Сравни 5³−3³ и (5−3)³.',activity:{id:'l87-p3',type:'input',prompt:'На сколько первое выражение больше второго?',answer:'90',hint:'98−8.',explanation:'125−27=98, а 2³=8; разность равна 90.'},visual:'repeat',sourceExercise:'№4(3) с.163'},
{id:'l87-method',kind:'model',eyebrow:'§24 · систематизация',title:'Три вопроса перед подсчётом',body:'Спроси: 1) порядок важен? 2) каждый следующий выбор независим? 3) одинаковые по смыслу перестановки считаются одним вариантом? Ответы определяют, нужна ли таблица, дерево, пары или правило произведения.',visual:'pairs',sourceExercise:'§24'},
{id:'l87-659-model',kind:'guided',eyebrow:'№659',title:'Прямоугольник задаётся неупорядоченной парой сторон',body:'Периметр 24 см означает 2(a+b)=24, то есть a+b=12. Пары (5;7) и (7;5) задают один и тот же прямоугольник.',note:'Полный список: (1;11), (2;10), (3;9), (4;8), (5;7), (6;6).',visual:'pairs',sourceExercise:'№659'},
{id:'l87-659-sum',kind:'practice',eyebrow:'№659 · условие',title:'Убираем множитель 2',body:'После деления периметра на 2 получаем сумму соседних сторон.',activity:{id:'l87-p4',type:'input',prompt:'Чему равна a+b?',answer:'12',hint:'24:2.',explanation:'a+b=12.'},visual:'verify',sourceExercise:'№659'},
{id:'l87-659-total',kind:'practice',eyebrow:'№659 · ответ',title:'Не считаем поворот новым прямоугольником',body:'Перебираем меньшую сторону от 1 до 6 и не повторяем зеркальные пары.',activity:{id:'l87-p5',type:'input',prompt:'Сколько различных прямоугольников существует?',answer:'6',hint:'Шесть неупорядоченных пар с суммой 12.',explanation:'Получается 6 прямоугольников.'},visual:'pairs',sourceExercise:'№659'},
{id:'l87-659-order',kind:'quiz',eyebrow:'№659 · смысл пары',title:'Порядок здесь не создаёт новый объект',body:'Прямоугольник со сторонами 5 и 7 см остаётся тем же после поворота.',activity:{id:'l87-p6',type:'choice',prompt:'Пары (5;7) и (7;5) — это один вариант?',options:['да','нет'],answer:'да',hint:'Стороны поменялись местами, фигура нет.',explanation:'Да. Это один прямоугольник.'},visual:'pairs',sourceExercise:'№659'},
{id:'l87-661-model',kind:'guided',eyebrow:'№661',title:'Отрезок определяется парой концов',body:'На прямой отмечены A, B, C, D. Каждый отрезок выбирает две разные точки, а AB и BA — один и тот же отрезок.',note:'AB, AC, AD, BC, BD, CD.',visual:'pairs',sourceExercise:'№661'},
{id:'l87-661-total',kind:'practice',eyebrow:'№661 · ответ',title:'Четыре точки дают шесть пар',body:'Перечисление всех пар исключает пропуски и повторный счёт.',activity:{id:'l87-p7',type:'input',prompt:'Сколько отрезков можно провести?',answer:'6',hint:'3+2+1.',explanation:'Всего 6 отрезков.'},visual:'verify',sourceExercise:'№661'},
{id:'l87-661-check',kind:'practice',eyebrow:'№661 · проверка',title:'Фиксируем первую точку',body:'Из точки A можно провести отрезки к B, C и D.',activity:{id:'l87-p8',type:'input',prompt:'Сколько отрезков начинается с A в систематическом списке?',answer:'3',hint:'AB, AC, AD.',explanation:'Три: AB, AC и AD.'},visual:'pairs',sourceExercise:'№661'},
{id:'l87-663-model',kind:'guided',eyebrow:'№663',title:'Форма = футболка × шорты',body:'Три цвета футболок и два цвета шорт — два последовательных независимых выбора.',visual:'product',sourceExercise:'№663'},
{id:'l87-663-first',kind:'practice',eyebrow:'№663 · первый выбор',title:'Три ветви первого уровня',body:'Сначала выбираем цвет футболки.',activity:{id:'l87-p9',type:'input',prompt:'Сколько вариантов футболки?',answer:'3',hint:'Красная, зелёная, синяя.',explanation:'Три варианта.'},visual:'product',sourceExercise:'№663'},
{id:'l87-663-total',kind:'practice',eyebrow:'№663 · ответ',title:'У каждой футболки два продолжения',body:'Для каждой из трёх футболок доступны белые или жёлтые шорты.',activity:{id:'l87-p10',type:'input',prompt:'Сколько вариантов формы?',answer:'6',hint:'3·2.',explanation:'3·2=6 вариантов.'},visual:'product',sourceExercise:'№663'},
{id:'l87-664-model',kind:'guided',eyebrow:'№664',title:'Наряд = платье × обувь',body:'У Тани четыре платья и две пары туфель. Каждый выбор платья можно соединить с каждым выбором обуви.',visual:'product',sourceExercise:'№664'},
{id:'l87-664-total',kind:'practice',eyebrow:'№664 · ответ',title:'Четыре ветви по два продолжения',body:'Применяем то же правило произведения.',activity:{id:'l87-p11',type:'input',prompt:'Сколько вариантов наряда?',answer:'8',hint:'4·2.',explanation:'4·2=8 вариантов.'},visual:'product',sourceExercise:'№664'},
{id:'l87-666-source',kind:'challenge',eyebrow:'№666 · рисунок 185',title:'Маршруты по городской сетке',body:'В учебнике маршруты из A в B считаются по рисунку 185 при движении только вверх или вправо. Геометрию рисунка не реконструируем по памяти; сохраняем авторский source-checkpoint и проверенный ответ.',activity:{id:'l87-p12',type:'input',prompt:'Каков авторский ответ для №666?',answer:'6',hint:'Сверь с ответами учебника.',explanation:'Авторский ответ: 6 маршрутов.'},visual:'route',sourceExercise:'№666'},
{id:'l87-667-model',kind:'guided',eyebrow:'№667',title:'Перебор знаков можно сократить оценкой',body:'В записи 1 * 2 * 3 * 4 каждую звёздочку заменяют на + или ·. Чтобы получить максимум, выгодно сохранить большой блок произведения 2·3·4 и прибавить 1.',note:'1+2·3·4=25.',visual:'optimize',sourceExercise:'№667'},
{id:'l87-667-total',kind:'practice',eyebrow:'№667 · максимум',title:'Считаем лучший вариант',body:'Сначала умножение: 2·3·4=24, затем прибавляем 1.',activity:{id:'l87-p13',type:'input',prompt:'Чему равно наибольшее значение?',answer:'25',hint:'1+24.',explanation:'Максимум равен 25.'},visual:'optimize',sourceExercise:'№667'},
{id:'l87-667-sign',kind:'quiz',eyebrow:'№667 · структура',title:'Первый знак отличается от двух следующих',body:'Максимальный вариант записывается как 1+2·3·4.',activity:{id:'l87-p14',type:'choice',prompt:'Какой знак стоит между 1 и 2 в максимальном варианте?',options:['+','·'],answer:'+',hint:'Сравни 1+24 и 1·24.',explanation:'Нужен знак +.'},visual:'optimize',sourceExercise:'№667'},
{id:'l87-672-source',kind:'model',eyebrow:'Повторение · №672',title:'Кроссворд: работаем только с исходным рисунком',body:'№672 — кроссворд с пересечениями. Текст определений восстановлен, но полную сетку и расположение букв приложение не реконструирует. Задание сохранено как source-checkpoint.',note:'По горизонтали: результат арифметического действия, единица времени, единица углов, компонент умножения, компонент сложения; по вертикали — «царица наук».',visual:'source',sourceExercise:'№672'},
{id:'l87-660-model',kind:'guided',eyebrow:'Домашнее · №660',title:'30 кубиков: порядок размеров не важен',body:'Прямоугольный параллелепипед задаётся тройкой натуральных размеров с произведением 30. Перестановка размеров — поворот той же фигуры.',note:'Тройки: 1·1·30, 1·2·15, 1·3·10, 1·5·6, 2·3·5.',visual:'pairs',sourceExercise:'№660'},
{id:'l87-660-total',kind:'practice',eyebrow:'№660 · ответ',title:'Пять различных троек множителей',body:'Считаем только разные формы, а не перестановки длины, ширины и высоты.',activity:{id:'l87-p15',type:'input',prompt:'Сколько различных параллелепипедов?',answer:'5',hint:'Перечисли тройки множителей 30 без перестановок.',explanation:'Всего 5 различных параллелепипедов.'},visual:'verify',sourceExercise:'№660'},
{id:'l87-662-model',kind:'guided',eyebrow:'Домашнее · №662',title:'Подъём и спуск — два последовательных выбора',body:'От подножия к вершине ведут три тропы. Для каждого пути вверх можно независимо выбрать одну из трёх троп вниз.',visual:'route',sourceExercise:'№662'},
{id:'l87-662-total',kind:'practice',eyebrow:'№662 · ответ',title:'Три на три',body:'Маршрут включает выбор пути вверх и выбор пути вниз.',activity:{id:'l87-p16',type:'input',prompt:'Сколько маршрутов туда и обратно?',answer:'9',hint:'3·3.',explanation:'3·3=9 маршрутов.'},visual:'product',sourceExercise:'№662'},
{id:'l87-665',kind:'practice',eyebrow:'Домашнее · №665',title:'Экипаж из пилота и инженера',body:'Есть три пилота и два инженера. Любой пилот может быть в паре с любым инженером.',activity:{id:'l87-p17',type:'input',prompt:'Сколько способов составить экипаж?',answer:'6',hint:'3·2.',explanation:'Получается 6 экипажей.'},visual:'product',sourceExercise:'№665'},
{id:'l87-673-model',kind:'challenge',eyebrow:'Дополнительное · №673',title:'Рассадка и скрытая делимость',body:'В классе 30 учеников. Половина всех девочек сидит с мальчиками. Нужно решить, можно ли пересадить класс так, чтобы половина всех мальчиков сидела с девочками.',visual:'logic',sourceExercise:'№673'},
{id:'l87-673-girls',kind:'practice',eyebrow:'№673 · девочки',title:'Вторая половина девочек сидит парами',body:'Если половина девочек сидит с мальчиками, оставшаяся половина девочек должна разбиться на пары. Значит половина числа девочек чётна.',activity:{id:'l87-p18',type:'input',prompt:'На какое число тогда делится количество девочек?',answer:'4',hint:'Если G/2 чётно, то G кратно 4.',explanation:'Количество девочек делится на 4.'},visual:'logic',sourceExercise:'№673'},
{id:'l87-673-boys',kind:'practice',eyebrow:'№673 · гипотеза',title:'Для мальчиков возникло бы то же условие',body:'Если бы требуемая новая рассадка существовала, половина мальчиков тоже сидела бы с девочками, а вторая половина мальчиков — попарно.',activity:{id:'l87-p19',type:'input',prompt:'На какое число тогда делилось бы количество мальчиков?',answer:'4',hint:'Полностью аналогично рассуждению о девочках.',explanation:'Количество мальчиков тоже должно было бы делиться на 4.'},visual:'logic',sourceExercise:'№673'},
{id:'l87-673-conclusion',kind:'challenge',eyebrow:'№673 · вывод',title:'Но 30 не делится на 4',body:'Если и число девочек, и число мальчиков делятся на 4, то и их сумма должна делиться на 4. Условие даёт 30 учеников — противоречие.',activity:{id:'l87-p20',type:'choice',prompt:'Можно ли выполнить требуемую пересадку?',options:['да','нет'],answer:'нет',hint:'30 не делится на 4.',explanation:'Нет. Получаем противоречие с общим числом 30.'},visual:'logic',sourceExercise:'№673'},
{id:'l87-workbook',kind:'model',eyebrow:'Рабочая тетрадь / дидактика',title:'Source-checkpoint без подмены авторского текста',body:'Маршрут урока включает рабочую тетрадь №302–304 и дидактические №158, 160–162. Их точные формулировки надёжно не восстановлены, поэтому приложение фиксирует номера, но не придумывает похожие условия.',visual:'source',sourceExercise:'РТ №302–304; ДМ №158,160–162'},
{id:'l87-strategy',kind:'quiz',eyebrow:'Итог §24',title:'Выбери модель до вычислений',body:'Для прямоугольников №659 перестановка двух сторон не создаёт новую фигуру, а для формы №663 выбор футболки и шорт — два независимых шага.',activity:{id:'l87-p21',type:'choice',prompt:'Где напрямую применяется правило произведения независимых выборов?',options:['№663: футболка и шорты','№659: пары сторон без учёта порядка'],answer:'№663: футболка и шорты',hint:'В №663 каждый выбор первого вида сочетается с каждым выбором второго.',explanation:'Правило произведения напрямую работает в №663.'},visual:'product'},
{id:'l87-final-check',kind:'model',eyebrow:'Финальная самопроверка',title:'Пять вопросов перед ответом',body:'Проверь: все ли варианты учтены, нет ли повторов, важен ли порядок, независимы ли шаги и соблюдены ли ограничения. Только после этого фиксируй итог.',visual:'verify'},
{id:'l87-reflection',kind:'story',eyebrow:'Рефлексия',title:'Что теперь проверяем в любой комбинаторной задаче',body:'Полнота перебора, отсутствие повторов, роль порядка, независимость шагов и ограничения. Эти пять проверок превращают «угадывание вариантов» в строгий алгоритм.',visual:'verify'},
{id:'l87-summary',kind:'summary',eyebrow:'§24 завершён',title:'Комбинаторные задачи собраны в единую систему',body:'Ты умеешь перечислять неупорядоченные пары, применять правило произведения, считать маршруты и комплекты, оптимизировать перебор и использовать логическое противоречие. Уроки 85–87 полностью закрывают §24.',note:'Дальше по курсу — урок 88: повторение и систематизация материала главы 3.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'§24',pairs:'{a,b}',product:'m·n',route:'A→B',optimize:'max',logic:'⇒',source:'§24',repeat:'↺',homework:'ДЗ',verify:'✓',final:'87'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='pairs'?'порядок или пара?':kind==='product'?'независимые выборы':kind==='route'?'считаем маршруты':kind==='optimize'?'ищем максимум системно':kind==='logic'?'делимость и противоречие':kind==='source'?'точный авторский маршрут':kind==='homework'?'самостоятельное закрепление':'итог комбинаторики'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightySevenStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function CombinatoricsSynthesisPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightySevenStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightySevenStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==87||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightySevenStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightySevenStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player combinatorics-synthesis-player" data-lesson-number="87" data-source-reference="Мерзляк § 24 · итог · устно №4 с.163 · №659,661,663,664,666,667 · повторение №672 · ДЗ №660,662,665 · доп. №673" data-source-exercise-range="4p163,659,661,663,664,666,667,672,660,662,665,673"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area" data-checked-problem={activity.id}><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightySevenStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightySevenStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
