import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'tree'|'digits'|'sum'|'product'|'zero'|'source'|'repeat'|'homework'|'verify'|'final';
export type LessonEightySixStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-86-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightySixStages:LessonEightySixStage[]=[
{id:'l86-mission',kind:'story',eyebrow:'Урок 86 · § 24 · закрепление',title:'Ограничение меняет дерево вариантов',body:'Продолжаем §24. Теперь мало просто перемножить количество выборов: сначала нужно понять, какие ветви действительно разрешены. Будем сравнивать числа и коды, учитывать порядок цифр, фиксированную сумму и чётность суммы цифр.',note:'Точный маршрут: устно №2–3 с.163; №651, 653, 655, 656, 658; повторение №670; домашние №652, 654, 657, 671.',visual:'mission'},
{id:'l86-oral-2',kind:'quiz',eyebrow:'Устно · №2 с.163',title:'Быстрая проверка произведения',body:'Среди предложенных троек нужно узнать ту, произведение чисел которой равно 240.',activity:{id:'l86-p1',type:'input',prompt:'Какой номер варианта даёт произведение 240?',answer:'2',hint:'Проверь 5·6·8.',explanation:'5·6·8=240, поэтому верен вариант 2.'},visual:'product',sourceExercise:'№2 с.163'},
{id:'l86-oral-3',kind:'quiz',eyebrow:'Устно · №3 с.163',title:'Расход за несколько секунд',body:'За одну секунду проходит 16 м³ воды. За 8 секунд объём увеличивается в 8 раз.',activity:{id:'l86-p2',type:'input',prompt:'Сколько кубических метров воды пройдёт за 8 секунд?',answer:'128',hint:'16·8.',explanation:'16·8=128 м³.'},visual:'repeat',sourceExercise:'№3 с.163'},
{id:'l86-method',kind:'model',eyebrow:'§24 · стратегия',title:'Сначала ограничения, потом подсчёт',body:'Для каждого разряда или шага выпиши допустимые варианты. Если ограничение зависит от предыдущего выбора, число продолжений у ветвей может быть разным — тогда дерево или систематическая таблица надёжнее механического умножения.',visual:'tree',sourceExercise:'§24'},
{id:'l86-651-model',kind:'guided',eyebrow:'№651(1)',title:'Три разряда, две цифры, повторения разрешены',body:'Если трёхзначное число составляют только из 1 и 2, каждый из трёх разрядов имеет по два варианта.',note:'Получается 2·2·2=8 чисел.',visual:'digits',sourceExercise:'№651(1)'},
{id:'l86-651-branch',kind:'practice',eyebrow:'№651(1) · ветвь',title:'Фиксируем первую цифру',body:'Если сотни уже равны 1, десятки и единицы независимо могут быть 1 или 2.',activity:{id:'l86-p3',type:'input',prompt:'Сколько чисел начинается цифрой 1?',answer:'4',hint:'Для десятков 2 варианта и для единиц 2.',explanation:'2·2=4 числа начинаются с 1.'},visual:'tree',sourceExercise:'№651(1)'},
{id:'l86-651-total',kind:'practice',eyebrow:'№651(1) · ответ',title:'Две одинаковые большие ветви',body:'Четыре числа начинаются с 1 и ещё четыре — с 2.',activity:{id:'l86-p4',type:'input',prompt:'Сколько всего трёхзначных чисел?',answer:'8',hint:'2·2·2.',explanation:'Всего 8 трёхзначных чисел.'},visual:'product',sourceExercise:'№651(1)'},
{id:'l86-651-zero-model',kind:'guided',eyebrow:'№651(2)',title:'Цифры 0 и 1: первая позиция уже не симметрична',body:'В трёхзначном числе сотни не могут быть нулём. Поэтому первая цифра вынужденно равна 1, а два следующих разряда имеют по два варианта.',visual:'zero',sourceExercise:'№651(2)'},
{id:'l86-651-first',kind:'practice',eyebrow:'№651(2) · сотни',title:'Одна допустимая первая цифра',body:'Ноль в сотнях превратил бы запись в число с меньшим количеством разрядов.',activity:{id:'l86-p5',type:'input',prompt:'Сколько вариантов для цифры сотен?',answer:'1',hint:'Из 0 и 1 впереди допустима только 1.',explanation:'Для сотен есть ровно один вариант — 1.'},visual:'zero',sourceExercise:'№651(2)'},
{id:'l86-651-zero-total',kind:'practice',eyebrow:'№651(2) · ответ',title:'Один выбор, затем два по два',body:'После обязательной единицы в сотнях остаются два независимых разряда.',activity:{id:'l86-p6',type:'input',prompt:'Сколько всего трёхзначных чисел из 0 и 1?',answer:'4',hint:'1·2·2.',explanation:'Получаем 4 числа.'},visual:'product',sourceExercise:'№651(2)'},
{id:'l86-number-vs-code',kind:'quiz',eyebrow:'Число и код',title:'В коде ведущий ноль допустим, в числе — нет',body:'Это различие станет ключевым в №658: код 03 остаётся двухпозиционным кодом, хотя число 03 — это просто 3.',activity:{id:'l86-p7',type:'choice',prompt:'Можно ли использовать 0 в первой позиции двухзначного кода?',options:['да','нет'],answer:'да',hint:'Код — последовательность символов, а не запись двузначного числа.',explanation:'Да. Для кода ведущий ноль допустим.'},visual:'zero'},
{id:'l86-653-model',kind:'guided',eyebrow:'№653',title:'Цифры 6, 7, 8, 9 и строгий порядок',body:'Нужно составить двузначные числа только из 6, 7, 8, 9 так, чтобы цифра десятков была меньше цифры единиц.',note:'Систематический список: 67, 68, 69, 78, 79, 89.',visual:'digits',sourceExercise:'№653'},
{id:'l86-653-first',kind:'practice',eyebrow:'№653 · начало',title:'Начинаем с минимальных десятков',body:'При десятках 6 допустимы единицы 7, 8 и 9.',activity:{id:'l86-p8',type:'input',prompt:'Какое наименьшее число в списке?',answer:'67',hint:'Десятки 6, минимальная большая единица — 7.',explanation:'Наименьшее число — 67.'},visual:'digits',sourceExercise:'№653'},
{id:'l86-653-last',kind:'practice',eyebrow:'№653 · конец',title:'Последняя возможная возрастающая пара',body:'Когда десятки равны 9, большей цифры уже нет; последняя ветвь начинается с 8.',activity:{id:'l86-p9',type:'input',prompt:'Какое наибольшее допустимое число?',answer:'89',hint:'8<9.',explanation:'Наибольшее число — 89.'},visual:'verify',sourceExercise:'№653'},
{id:'l86-653-count',kind:'practice',eyebrow:'№653 · полнота',title:'3 + 2 + 1 продолжение',body:'После 6 есть три большие цифры, после 7 — две, после 8 — одна.',activity:{id:'l86-p10',type:'input',prompt:'Сколько всего допустимых чисел?',answer:'6',hint:'3+2+1.',explanation:'Всего 6 чисел.'},visual:'tree',sourceExercise:'№653'},
{id:'l86-655-model',kind:'guided',eyebrow:'№655',title:'Фиксированная сумма цифр',body:'Для суммы цифр 5 перебираем возможные десятки от 1 до 5 и единственным способом дополняем их до 5.',note:'Список: 14, 23, 32, 41, 50.',visual:'sum',sourceExercise:'№655'},
{id:'l86-655-first',kind:'practice',eyebrow:'№655 · начало',title:'Первая допустимая пара',body:'Десятки не могут быть нулём, поэтому перебор начинается с 1.',activity:{id:'l86-p11',type:'input',prompt:'Какое первое число получается?',answer:'14',hint:'1+4=5.',explanation:'Первый вариант — 14.'},visual:'sum',sourceExercise:'№655'},
{id:'l86-655-last',kind:'practice',eyebrow:'№655 · конец',title:'Ноль допустим в единицах',body:'При десятках 5 единицы должны быть 0.',activity:{id:'l86-p12',type:'input',prompt:'Какое последнее число получается?',answer:'50',hint:'5+0=5.',explanation:'Последний вариант — 50.'},visual:'zero',sourceExercise:'№655'},
{id:'l86-655-count',kind:'practice',eyebrow:'№655 · ответ',title:'Каждому десятку соответствует одна единица',body:'Пять допустимых значений десятков дают пять разных чисел.',activity:{id:'l86-p13',type:'input',prompt:'Сколько двузначных чисел имеют сумму цифр 5?',answer:'5',hint:'14, 23, 32, 41, 50.',explanation:'Таких чисел 5.'},visual:'verify',sourceExercise:'№655'},
{id:'l86-656-model',kind:'guided',eyebrow:'№656',title:'Чётной должна быть сумма цифр',body:'Используются цифры 1, 2, 3, 4, повторения разрешены. Сумма двух цифр чётна тогда и только тогда, когда обе цифры одной чётности.',note:'Нечётные цифры: 1,3. Чётные: 2,4.',visual:'sum',sourceExercise:'№656'},
{id:'l86-656-odd',kind:'practice',eyebrow:'№656 · нечётные',title:'Две нечётные цифры тоже дают чётную сумму',body:'В каждом разряде можно выбрать 1 или 3.',activity:{id:'l86-p14',type:'input',prompt:'Сколько вариантов нечётной цифры для каждого разряда?',answer:'2',hint:'1 и 3.',explanation:'Нечётных разрешённых цифр две.'},visual:'digits',sourceExercise:'№656'},
{id:'l86-656-even',kind:'practice',eyebrow:'№656 · чётные',title:'Две чётные цифры дают чётную сумму',body:'В каждом разряде можно выбрать 2 или 4.',activity:{id:'l86-p15',type:'input',prompt:'Сколько вариантов чётной цифры для каждого разряда?',answer:'2',hint:'2 и 4.',explanation:'Чётных разрешённых цифр две.'},visual:'digits',sourceExercise:'№656'},
{id:'l86-656-total',kind:'challenge',eyebrow:'№656 · ответ',title:'Складываем два класса ветвей',body:'Нечётная-нечётная даёт 2·2=4 числа, чётная-чётная — ещё 4.',activity:{id:'l86-p16',type:'input',prompt:'Сколько всего чисел с чётной суммой цифр?',answer:'8',hint:'4+4.',explanation:'Всего 8 чисел.'},visual:'product',sourceExercise:'№656'},
{id:'l86-658-model',kind:'guided',eyebrow:'№658',title:'Код двери: ведущий ноль снова разрешён',body:'Базилио помнит, что двухпозиционный код составлен из цифр 0, 1, 2, 3. Для каждой позиции доступны четыре цифры, включая 0 в начале.',visual:'zero',sourceExercise:'№658'},
{id:'l86-658-position',kind:'practice',eyebrow:'№658 · позиция',title:'Одинаковое число вариантов на каждом шаге',body:'Ограничений на первую позицию кода нет.',activity:{id:'l86-p17',type:'input',prompt:'Сколько вариантов для каждой позиции кода?',answer:'4',hint:'0, 1, 2, 3.',explanation:'На каждой позиции по 4 варианта.'},visual:'digits',sourceExercise:'№658'},
{id:'l86-658-total',kind:'practice',eyebrow:'№658 · максимум попыток',title:'Четыре ветви по четыре продолжения',body:'Если неизвестно ничего больше, нужно быть готовым проверить все конечные ветви.',activity:{id:'l86-p18',type:'input',prompt:'Сколько разных двухпозиционных кодов возможно?',answer:'16',hint:'4·4.',explanation:'Возможно 16 кодов.'},visual:'product',sourceExercise:'№658'},
{id:'l86-workbook-checkpoint',kind:'model',eyebrow:'Рабочая тетрадь',title:'№160, 161, 299, 301, 303, 305 — source-checkpoint',body:'Эти номера входят в технологическую карту урока, но точный текст заданий не восстановлен надёжно. Приложение сохраняет их как отметку авторского маршрута и не подменяет выдуманными условиями.',visual:'source',sourceExercise:'РТ №160,161,299,301,303,305'},
{id:'l86-670-model',kind:'guided',eyebrow:'Повторение · №670',title:'Отношение частей превращаем в одну переменную',body:'В первом подпункте большее слагаемое в 14 раз больше меньшего, поэтому сумма равна 15 долям меньшего. Во втором вычитаемое равно 12 разностям, значит уменьшаемое равно 13 разностям.',visual:'repeat',sourceExercise:'№670'},
{id:'l86-670-one',kind:'practice',eyebrow:'№670(1)',title:'Сумма относительно меньшего слагаемого',body:'Меньшее слагаемое — одна доля, большее — 14 таких долей.',activity:{id:'l86-p19',type:'input',prompt:'Во сколько раз сумма больше меньшего слагаемого?',answer:'15',hint:'1+14.',explanation:'Сумма состоит из 15 долей меньшего слагаемого.'},visual:'repeat',sourceExercise:'№670(1)'},
{id:'l86-670-two',kind:'practice',eyebrow:'№670(2)',title:'Уменьшаемое относительно разности',body:'Разность — одна доля, вычитаемое — 12 таких долей.',activity:{id:'l86-p20',type:'input',prompt:'Во сколько раз уменьшаемое больше разности?',answer:'13',hint:'12+1.',explanation:'Уменьшаемое состоит из 13 долей разности.'},visual:'repeat',sourceExercise:'№670(2)'},
{id:'l86-671-model',kind:'guided',eyebrow:'Домашнее · №671',title:'Сначала общий объём, потом вместимость тары',body:'12 бидонов по 156 л дают 1872 л молока. При переработке в бидоны по 40 л последний неполный бидон тоже нужен, поэтому округляем количество вверх.',note:'1872:40=46 ост. 32, значит требуется 47 бидонов; имеющихся 42 не хватает на 5.',visual:'homework',sourceExercise:'№671'},
{id:'l86-671-answer',kind:'practice',eyebrow:'№671 · контроль',title:'Остаток означает ещё один бидон',body:'46 полных бидонов вместят только 1840 л — ещё 32 л нужно куда-то перелить.',activity:{id:'l86-p21',type:'input',prompt:'Сколько бидонов по 40 л требуется всего?',answer:'47',hint:'46 полных плюс один для остатка.',explanation:'Нужно 47 бидонов; 42 имеющихся недостаточно.'},visual:'verify',sourceExercise:'№671'},
{id:'l86-home-652',kind:'model',eyebrow:'Домашнее · №652',title:'Цифры 2, 4, 9, 0 с повторениями',body:'Для двузначного числа десятки имеют 3 ненулевых варианта, единицы — 4. Поэтому всего 3·4=12 чисел.',visual:'homework',sourceExercise:'№652'},
{id:'l86-home-654-657',kind:'model',eyebrow:'Домашнее · №654 и 657',title:'Порядок цифр и нечётная сумма',body:'№654 зеркально тренирует строгий порядок для 6,7,8,9 и даёт 6 вариантов. В №657 используются 0,1,2,3 и условие нечётной суммы цифр; с учётом запрета ведущего нуля получается 6 двузначных чисел.',visual:'homework',sourceExercise:'№654,657'},
{id:'l86-source-close',kind:'model',eyebrow:'Проверка маршрута',title:'Авторские номера отделяем от тренировочных задач',body:'Рабочая тетрадь №159 и 162 тоже входит в домашний маршрут. Пока точный текст не восстановлен, приложение не реконструирует его по догадке.',visual:'source',sourceExercise:'РТ №159,162'},
{id:'l86-summary',kind:'summary',eyebrow:'Итог урока 86 · §24',title:'Теперь ты сначала читаешь ограничения, а уже потом считаешь варианты',body:'Ты закрепил дерево вариантов и правило произведения, различаешь число и код, умеешь учитывать ведущий ноль, строгий порядок цифр, фиксированную сумму и чётность суммы цифр.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 87 продолжит §24 и остаётся закрытым до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'§24',tree:'Y',digits:'0123',sum:'Σ',product:'m·n',zero:'0?',source:'§24',repeat:'↺',homework:'ДЗ',verify:'✓',final:'86'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='tree'?'ветви с ограничениями':kind==='digits'?'проверяем каждый разряд':kind==='sum'?'сумма и чётность цифр':kind==='product'?'считаем конечные ветви':kind==='zero'?'число или код?':kind==='source'?'точный авторский маршрут':kind==='homework'?'самостоятельное закрепление':'комбинаторное закрепление'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightySixStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function CombinatoricsReinforcementPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightySixStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightySixStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==86||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightySixStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightySixStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player combinatorics-reinforcement-player" data-lesson-number="86" data-source-reference="Мерзляк § 24 · второй урок · устно №2–3 с.163 · №651,653,655,656,658 · повторение №670 · ДЗ №652,654,657,671" data-source-exercise-range="2-3p163,651,653,655,656,658,670,652,654,657,671"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area" data-checked-problem={activity.id}><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightySixStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightySixStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
