import {useEffect,useMemo,useState} from 'react';
import {loadLessonTiming} from './lessonTiming';
import './lessonPlayer.css';
import './controlWork.css';
import {lessonOneHundredFiftySixFields,lessonOneHundredFiftySixProgressKey,lessonOneHundredFiftySixStages,type ControlField156} from './data/lessonOneHundredFiftySixControl';

type Saved={version:1;stageIndex:number;responses:Record<string,string>;submitted:boolean;completedAt?:string;submittedResponses?:Record<string,string>;correctionFieldIds?:string[];correctionCompletedAt?:string};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};
const COMPLETION_KEY='mathnikita:lesson-complete:156';
const fieldById=new Map(lessonOneHundredFiftySixFields.map(field=>[field.id,field]));
function normalizeText(value:string){return value.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/[−–—]/g,'-').replace(/,/g,'.')}
function canonicalDecimal(value:string){let s=normalizeText(value);if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s))return null;let sign='';if(s.startsWith('+')||s.startsWith('-')){sign=s.startsWith('-')?'-':'';s=s.slice(1)}let[whole,frac='']=s.split('.');whole=(whole||'0').replace(/^0+(?=\d)/,'');frac=frac.replace(/0+$/,'');if(whole==='0'&&!frac)sign='';return `${sign}${whole}${frac?`.${frac}`:''}`}
function correct(field:ControlField156,response:string){const normalized=normalizeText(response);if(!normalized)return false;const accepted=[field.answer,...(field.accepted??[])];if(accepted.some(answer=>normalized===normalizeText(answer)))return true;const responseDecimal=canonicalDecimal(response);const answerDecimal=canonicalDecimal(field.answer);return responseDecimal!==null&&answerDecimal!==null&&responseDecimal===answerDecimal}
function loadSaved():Saved{try{const raw=localStorage.getItem(lessonOneHundredFiftySixProgressKey);if(!raw)return{version:1,stageIndex:0,responses:{},submitted:false};const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1)return{version:1,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonOneHundredFiftySixStages.length-1)),responses:parsed.responses??{},submitted:Boolean(parsed.submitted),completedAt:parsed.completedAt,submittedResponses:parsed.submittedResponses,correctionFieldIds:parsed.correctionFieldIds??[],correctionCompletedAt:parsed.correctionCompletedAt}}catch{}return{version:1,stageIndex:0,responses:{},submitted:false}}

export function ControlWorkNinePlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[submitted,setSubmitted]=useState(initial.submitted);const[completedAt,setCompletedAt]=useState<string|undefined>(initial.completedAt);const[submittedResponses,setSubmittedResponses]=useState<Record<string,string>|undefined>(initial.submittedResponses);const[correctionFieldIds,setCorrectionFieldIds]=useState<string[]>(initial.correctionFieldIds??[]);const[correctionCompletedAt,setCorrectionCompletedAt]=useState<string|undefined>(initial.correctionCompletedAt);const stage=lessonOneHundredFiftySixStages[stageIndex];const answeredCount=lessonOneHundredFiftySixFields.filter(field=>Boolean(responses[field.id]?.trim())).length;const baselineResponses=submittedResponses??(submitted?responses:{});const score=lessonOneHundredFiftySixFields.filter(field=>correct(field,baselineResponses[field.id]??'')).length;const grade=score===6?'5':score===5?'4':score>=3?'3':'нужно повторить';const wrongFieldIds=submitted?lessonOneHundredFiftySixFields.filter(field=>!correct(field,baselineResponses[field.id]??'')).map(field=>field.id):[];const correctionMode=submitted&&correctionFieldIds.length>0&&!correctionCompletedAt;const correctionCorrectCount=correctionFieldIds.filter(id=>{const field=fieldById.get(id);return Boolean(field&&correct(field,responses[id]??''))}).length;const correctionStageIndexes=lessonOneHundredFiftySixStages.map((item,index)=>({item,index})).filter(({item})=>item.kind==='task'&&item.fieldIds?.some(id=>correctionFieldIds.includes(id))).map(({index})=>index);const correctionPosition=correctionStageIndexes.indexOf(stageIndex);const stageFields=(stage.fieldIds??[]).map(id=>fieldById.get(id)).filter(Boolean) as ControlField156[];const stageComplete=correctionMode?stageFields.filter(field=>correctionFieldIds.includes(field.id)).every(field=>correct(field,responses[field.id]??'')):stageFields.every(field=>Boolean(responses[field.id]?.trim()));
  useEffect(()=>{localStorage.setItem(lessonOneHundredFiftySixProgressKey,JSON.stringify({version:1,stageIndex,responses,submitted,completedAt,submittedResponses,correctionFieldIds,correctionCompletedAt} satisfies Saved))},[stageIndex,responses,submitted,completedAt,submittedResponses,correctionFieldIds,correctionCompletedAt]);
  useEffect(()=>{const go=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==156||typeof detail.stageIndex!=='number')return;moveTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',go);return()=>window.removeEventListener('mathnikita-go-to-stage',go)},[]);
  function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
  function moveTo(index:number){stopNarration();setStageIndex(Math.max(0,Math.min(index,lessonOneHundredFiftySixStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})}
  function canEdit(id:string){return!submitted||(correctionMode&&correctionFieldIds.includes(id))}
  function setResponse(id:string,value:string){if(canEdit(id))setResponses(previous=>({...previous,[id]:value}))}
  function submit(){if(answeredCount!==lessonOneHundredFiftySixFields.length||submitted)return;const now=new Date().toISOString();const snapshot={...responses};const activeSeconds=Math.round(loadLessonTiming(156).activeSeconds);setSubmittedResponses(snapshot);setSubmitted(true);setCompletedAt(now);setCorrectionFieldIds([]);setCorrectionCompletedAt(undefined);moveTo(lessonOneHundredFiftySixStages.length-1);localStorage.setItem(COMPLETION_KEY,JSON.stringify({completedAt:now,activeSeconds}));window.dispatchEvent(new CustomEvent('mathnikita-lesson-completed',{detail:{lessonNumber:156,completedAt:now,activeSeconds}}))}
  function startCorrection(){if(!wrongFieldIds.length)return;const indexes=lessonOneHundredFiftySixStages.map((item,index)=>({item,index})).filter(({item})=>item.kind==='task'&&item.fieldIds?.some(id=>wrongFieldIds.includes(id))).map(({index})=>index);setCorrectionFieldIds(wrongFieldIds);setCorrectionCompletedAt(undefined);moveTo(indexes[0]??lessonOneHundredFiftySixStages.length-1)}
  function finishCorrection(){if(!correctionFieldIds.length||correctionCorrectCount!==correctionFieldIds.length)return;setCorrectionCompletedAt(new Date().toISOString());moveTo(lessonOneHundredFiftySixStages.length-1)}
  function reset(){stopNarration();localStorage.removeItem(lessonOneHundredFiftySixProgressKey);localStorage.removeItem(COMPLETION_KEY);setResponses({});setSubmittedResponses(undefined);setSubmitted(false);setCompletedAt(undefined);setCorrectionFieldIds([]);setCorrectionCompletedAt(undefined);setStageIndex(0)}
  const visibleFields=correctionMode?stageFields.filter(field=>correctionFieldIds.includes(field.id)):stageFields;
  return <main className="control-work-page control-nine-page" data-control-work="9" data-lesson-number="156" data-source-reference="Мерзляк, Полонский, Якир · Математика 5 класс · контрольная работа № 9 · вариант 1" data-control-field-count={lessonOneHundredFiftySixFields.length}>
    <section className="lesson-player-shell"><div className="control-work-status"><div><span>Контрольная работа № 9</span><b>{submitted?`Первичный балл ${score}/${lessonOneHundredFiftySixFields.length}`:`Заполнено ${answeredCount}/${lessonOneHundredFiftySixFields.length}`}</b></div><div className="control-progress"><i style={{width:`${((stageIndex+1)/lessonOneHundredFiftySixStages.length)*100}%`}}/></div></div>
      <article className={`interactive-stage control-stage ${stage.kind==='summary'?'control-result-stage':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p></div>
        {stage.kind==='intro'?<><div className="control-source-badge"><b>Точный вариант</b><span>Контрольная работа № 9 «Среднее арифметическое. Проценты», вариант 1. 6 заданий, 45 минут, калькулятор не используется.</span></div><div className="control-rules"><b>Во время первичной работы</b><ul><li>ответы, решения и подсказки скрыты до сдачи;</li><li>можно возвращаться к заданиям и менять ответы;</li><li>после сдачи первичный балл фиксируется.</li></ul></div></>:null}
        {stage.kind==='task'?<div className="activity-area"><div className="answer-grid">{visibleFields.map(field=><label className="inline-answer" key={field.id}><span>{field.number}. {field.label}</span><input value={responses[field.id]??''} disabled={!canEdit(field.id)} placeholder={field.placeholder??'Введите ответ'} onChange={event=>setResponse(field.id,event.target.value)}/>{submitted&&!correctionMode?<small className={correct(field,baselineResponses[field.id]??'')?'control-correct':'control-wrong'}>{correct(field,baselineResponses[field.id]??'')?'Верно':`Ответ: ${field.answer}`}</small>:null}{submitted&&!correctionMode?<p className="control-explanation">{field.explanation}</p>:null}</label>)}</div>{correctionMode?<div className="control-correction-status">Исправлено {correctionCorrectCount}/{correctionFieldIds.length}</div>:null}</div>:null}
        {stage.kind==='submit'?<div className="control-submit-card"><b>Заполнено {answeredCount} из {lessonOneHundredFiftySixFields.length}</b><button type="button" disabled={answeredCount!==lessonOneHundredFiftySixFields.length||submitted} onClick={submit}>Сдать работу</button></div>:null}
        {stage.kind==='summary'&&submitted?<div className="control-submit-card control-result-card"><b>Первичный результат: {score}/{lessonOneHundredFiftySixFields.length} · оценка {grade}</b><span>{wrongFieldIds.length?`Ошибок: ${wrongFieldIds.length}. Первичный балл уже сохранён.`:'Все ответы верны.'}</span>{wrongFieldIds.length&&!correctionMode&&!correctionCompletedAt?<button type="button" onClick={startCorrection}>Исправить ошибки</button>:null}{correctionCompletedAt?<span>Коррекция завершена. Первичный результат не изменён.</span>:null}<button type="button" onClick={reset}>Пройти заново</button></div>:null}
      </article>
      <nav className="lesson-controls" aria-label="Навигация по контрольной работе № 9"><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0||correctionMode&&correctionPosition===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonOneHundredFiftySixStages.length}</span>{correctionMode?<button type="button" onClick={()=>{if(correctionPosition===correctionStageIndexes.length-1)finishCorrection();else moveTo(correctionStageIndexes[correctionPosition+1])}} disabled={!stageComplete}>{correctionPosition===correctionStageIndexes.length-1?'Завершить коррекцию':'Следующая ошибка →'}</button>:<button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={stageIndex===lessonOneHundredFiftySixStages.length-1||stage.kind==='task'&&!stageComplete}>Дальше →</button>}</nav>
    </section>
  </main>
}
