import {useEffect,useMemo,useState} from 'react';
import {loadLessonTiming} from './lessonTiming';
import './lessonPlayer.css';
import './controlWork.css';
import {lessonOneHundredTwentyFiveFields,lessonOneHundredTwentyFiveProgressKey,lessonOneHundredTwentyFiveStages,type ControlField125} from './data/lessonOneHundredTwentyFiveControl';

type Saved={version:1;stageIndex:number;responses:Record<string,string>;submitted:boolean;completedAt?:string;submittedResponses?:Record<string,string>;correctionFieldIds?:string[];correctionCompletedAt?:string};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};
const COMPLETION_KEY='mathnikita:lesson-complete:125';
const fieldById=new Map(lessonOneHundredTwentyFiveFields.map(field=>[field.id,field]));
function normalize(value:string){return value.trim().toLowerCase().replace(/\s+/g,'').replace(/[−–—]/g,'-').replace(/,/g,'.')}
function validIntervalTriple(value:string){const raw=value.replace(/,/g,'.').match(/\d+(?:\.\d+)?/g)??[];if(raw.length!==3)return false;const numbers=raw.map(Number);return new Set(numbers.map(item=>item.toString())).size===3&&numbers.every(item=>item>5.74&&item<5.76)}
function correct(field:ControlField125,response:string){if(field.mode==='decimal-between-three')return validIntervalTriple(response);return[field.answer,...(field.accepted??[])].some(answer=>normalize(response)===normalize(answer))}
function loadSaved():Saved{try{const raw=localStorage.getItem(lessonOneHundredTwentyFiveProgressKey);if(!raw)return{version:1,stageIndex:0,responses:{},submitted:false};const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1)return{version:1,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonOneHundredTwentyFiveStages.length-1)),responses:parsed.responses??{},submitted:Boolean(parsed.submitted),completedAt:parsed.completedAt,submittedResponses:parsed.submittedResponses,correctionFieldIds:parsed.correctionFieldIds??[],correctionCompletedAt:parsed.correctionCompletedAt}}catch{}return{version:1,stageIndex:0,responses:{},submitted:false}}

export function ControlWorkSevenPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[submitted,setSubmitted]=useState(initial.submitted);const[completedAt,setCompletedAt]=useState<string|undefined>(initial.completedAt);const[submittedResponses,setSubmittedResponses]=useState<Record<string,string>|undefined>(initial.submittedResponses);const[correctionFieldIds,setCorrectionFieldIds]=useState<string[]>(initial.correctionFieldIds??[]);const[correctionCompletedAt,setCorrectionCompletedAt]=useState<string|undefined>(initial.correctionCompletedAt);const stage=lessonOneHundredTwentyFiveStages[stageIndex];const answeredCount=lessonOneHundredTwentyFiveFields.filter(field=>Boolean(responses[field.id]?.trim())).length;const baselineResponses=submittedResponses??(submitted?responses:{});const score=lessonOneHundredTwentyFiveFields.filter(field=>correct(field,baselineResponses[field.id]??'')).length;const grade=score>=13?'5':score>=10?'4':score>=7?'3':'нужно повторить';const wrongFieldIds=submitted?lessonOneHundredTwentyFiveFields.filter(field=>!correct(field,baselineResponses[field.id]??'')).map(field=>field.id):[];const correctionMode=submitted&&correctionFieldIds.length>0&&!correctionCompletedAt;const correctionCorrectCount=correctionFieldIds.filter(id=>{const field=fieldById.get(id);return Boolean(field&&correct(field,responses[id]??''))}).length;const correctionStageIndexes=lessonOneHundredTwentyFiveStages.map((item,index)=>({item,index})).filter(({item})=>item.kind==='task'&&item.fieldIds?.some(id=>correctionFieldIds.includes(id))).map(({index})=>index);const correctionPosition=correctionStageIndexes.indexOf(stageIndex);const stageFields=(stage.fieldIds??[]).map(id=>fieldById.get(id)).filter(Boolean) as ControlField125[];const stageComplete=correctionMode?stageFields.filter(field=>correctionFieldIds.includes(field.id)).every(field=>correct(field,responses[field.id]??'')):stageFields.every(field=>Boolean(responses[field.id]?.trim()));
  useEffect(()=>{localStorage.setItem(lessonOneHundredTwentyFiveProgressKey,JSON.stringify({version:1,stageIndex,responses,submitted,completedAt,submittedResponses,correctionFieldIds,correctionCompletedAt} satisfies Saved))},[stageIndex,responses,submitted,completedAt,submittedResponses,correctionFieldIds,correctionCompletedAt]);
  useEffect(()=>{const go=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==125||typeof detail.stageIndex!=='number')return;moveTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',go);return()=>window.removeEventListener('mathnikita-go-to-stage',go)},[]);
  function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
  function moveTo(index:number){stopNarration();setStageIndex(Math.max(0,Math.min(index,lessonOneHundredTwentyFiveStages.length-1)));window.scrollTo({top:0,behavior:'smooth'})}
  function canEdit(id:string){return!submitted||(correctionMode&&correctionFieldIds.includes(id))}
  function setResponse(id:string,value:string){if(canEdit(id))setResponses(previous=>({...previous,[id]:value}))}
  function submit(){if(answeredCount!==lessonOneHundredTwentyFiveFields.length||submitted)return;const now=new Date().toISOString();const snapshot={...responses};const activeSeconds=Math.round(loadLessonTiming(125).activeSeconds);const summaryIndex=lessonOneHundredTwentyFiveStages.length-1;const saved:Saved={version:1,stageIndex:summaryIndex,responses:snapshot,submitted:true,completedAt:now,submittedResponses:snapshot,correctionFieldIds:[]};localStorage.setItem(lessonOneHundredTwentyFiveProgressKey,JSON.stringify(saved));localStorage.setItem(COMPLETION_KEY,JSON.stringify({completedAt:now,activeSeconds}));setSubmittedResponses(snapshot);setSubmitted(true);setCompletedAt(now);setCorrectionFieldIds([]);setCorrectionCompletedAt(undefined);stopNarration();setStageIndex(summaryIndex);window.scrollTo({top:0,behavior:'smooth'});window.setTimeout(()=>window.dispatchEvent(new CustomEvent('mathnikita-lesson-completed',{detail:{lessonNumber:125,completedAt:now,activeSeconds}})),0)}
  function startCorrection(){if(!wrongFieldIds.length)return;const indexes=lessonOneHundredTwentyFiveStages.map((item,index)=>({item,index})).filter(({item})=>item.kind==='task'&&item.fieldIds?.some(id=>wrongFieldIds.includes(id))).map(({index})=>index);setCorrectionFieldIds(wrongFieldIds);setCorrectionCompletedAt(undefined);moveTo(indexes[0]??lessonOneHundredTwentyFiveStages.length-1)}
  function finishCorrection(){if(!correctionFieldIds.length||correctionCorrectCount!==correctionFieldIds.length)return;const now=new Date().toISOString();const summaryIndex=lessonOneHundredTwentyFiveStages.length-1;localStorage.setItem(lessonOneHundredTwentyFiveProgressKey,JSON.stringify({version:1,stageIndex:summaryIndex,responses,submitted:true,completedAt,submittedResponses,correctionFieldIds,correctionCompletedAt:now} satisfies Saved));setCorrectionCompletedAt(now);moveTo(summaryIndex)}
  function reset(){stopNarration();localStorage.removeItem(lessonOneHundredTwentyFiveProgressKey);localStorage.removeItem(COMPLETION_KEY);setResponses({});setSubmittedResponses(undefined);setSubmitted(false);setCompletedAt(undefined);setCorrectionFieldIds([]);setCorrectionCompletedAt(undefined);setStageIndex(0)}
  const visibleFields=correctionMode?stageFields.filter(field=>correctionFieldIds.includes(field.id)):stageFields;
  return <main className="control-work-page control-seven-page" data-control-work="7" data-lesson-number="125" data-source-reference="Мерзляк · методическое пособие · контрольная работа № 7 · вариант 1" data-control-field-count={lessonOneHundredTwentyFiveFields.length}>
    <section className="lesson-player-shell"><div className="control-work-status"><div><span>Контрольная работа № 7</span><b>{submitted?`Первичный балл ${score}/${lessonOneHundredTwentyFiveFields.length}`:`Заполнено ${answeredCount}/${lessonOneHundredTwentyFiveFields.length}`}</b></div><div className="control-progress"><i style={{width:`${((stageIndex+1)/lessonOneHundredTwentyFiveStages.length)*100}%`}}/></div></div>
      <article className={`interactive-stage control-stage ${stage.kind==='summary'?'control-result-stage':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p></div>
        {stage.kind==='intro'?<><div className="control-source-badge"><b>Точный источник</b><span>Контрольная работа № 7 «Понятие о десятичной дроби. Сравнение, округление, сложение и вычитание десятичных дробей», вариант 1.</span></div><div className="control-rules"><b>Во время первичной работы</b><ul><li>ответы, объяснения и подсказки скрыты до сдачи;</li><li>можно возвращаться к заданиям и менять ответы;</li><li>после сдачи первичный балл фиксируется.</li></ul></div></>:null}
        {stage.kind==='task'?<div className="activity-area"><div className="answer-grid">{visibleFields.map(field=><label className="inline-answer" key={field.id}><span>{field.number}. {field.label}</span><input value={responses[field.id]??''} disabled={!canEdit(field.id)} placeholder={field.placeholder??'Введите ответ'} onChange={event=>setResponse(field.id,event.target.value)}/>{submitted&&!correctionMode?<small className={correct(field,baselineResponses[field.id]??'')?'control-correct':'control-wrong'}>{correct(field,baselineResponses[field.id]??'')?'Верно':`Ответ: ${field.answer}`}</small>:null}{submitted&&!correctionMode?<p className="control-explanation">{field.explanation}</p>:null}</label>)}</div>{correctionMode?<div className="control-correction-status">Исправлено {correctionCorrectCount}/{correctionFieldIds.length}</div>:null}</div>:null}
        {stage.kind==='submit'?<div className="control-submit-card"><b>Заполнено {answeredCount} из {lessonOneHundredTwentyFiveFields.length}</b><button type="button" disabled={answeredCount!==lessonOneHundredTwentyFiveFields.length||submitted} onClick={submit}>Сдать работу</button></div>:null}
        {stage.kind==='summary'&&submitted?<div className="control-submit-card control-result-card"><b>Первичный результат: {score}/{lessonOneHundredTwentyFiveFields.length} · оценка {grade}</b><span>{wrongFieldIds.length?`Ошибок: ${wrongFieldIds.length}. Первичный балл уже сохранён.`:'Все ответы верны.'}</span>{wrongFieldIds.length&&!correctionMode&&!correctionCompletedAt?<button type="button" onClick={startCorrection}>Исправить ошибки</button>:null}{correctionCompletedAt?<span>Коррекция завершена. Первичный результат не изменён.</span>:null}<button type="button" onClick={reset}>Пройти заново</button></div>:null}
      </article>
      <nav className="lesson-controls" aria-label="Навигация по контрольной работе № 7"><button type="button" onClick={()=>moveTo(stageIndex-1)} disabled={stageIndex===0||correctionMode&&correctionPosition===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonOneHundredTwentyFiveStages.length}</span>{correctionMode?<button type="button" onClick={()=>{if(correctionPosition===correctionStageIndexes.length-1)finishCorrection();else moveTo(correctionStageIndexes[correctionPosition+1])}} disabled={!stageComplete}>{correctionPosition===correctionStageIndexes.length-1?'Завершить коррекцию':'Следующая ошибка →'}</button>:<button type="button" onClick={()=>moveTo(stageIndex+1)} disabled={stageIndex===lessonOneHundredTwentyFiveStages.length-1||stage.kind==='task'&&!stageComplete}>Дальше →</button>}</nav>
    </section>
  </main>
}