import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyFourPractice,lessonOneHundredTwentyFourResponseCount,type Lesson124Field,type Lesson124Practice} from './data/lessonOneHundredTwentyFourPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson124Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-124-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—−]/g,'-');
const matchField=(value:string,field:Lesson124Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
 {id:'l124-map',eyebrow:'Урок 124 · § 33 · 6 из 6',title:'Перед контрольной собираем карту § 33',body:'В одной теме встретились четыре разных режима: точное сложение и вычитание по разрядам, составные задачи, удобная группировка и буквенные выражения. Сначала определи тип задачи, затем выбирай приём.',note:'Главный навык — не просто считать, а выбирать правильную стратегию.'},
 {id:'l124-composite',eyebrow:'Составная задача',title:'Связи между величинами идут раньше арифметики',body:'Если одна величина больше или меньше другой, сначала восстанови зависимые части. После этого найди итог и проверь, что он согласуется с исходными данными.',note:'№ 887 проверяет именно цепочку зависимостей.'},
 {id:'l124-group',eyebrow:'Удобный порядок',title:'При сложении ищем пары до круглых чисел',body:'Переместительное и сочетательное свойства позволяют менять порядок и группировку слагаемых. Это особенно полезно, когда две дроби дополняют друг друга до целого числа.',note:'Но у последовательного вычитания порядок действий сохраняется.'},
 {id:'l124-algebra',eyebrow:'Буквенные выражения',title:'Одинаковые буквенные части собираем вместе',body:'Сначала объедини одинаковые буквенные слагаемые, затем отдельно сложи постоянные числа. Получившаяся короткая запись должна иметь то же значение, что и исходная.',note:'Например, x + 3x превращается в 4x.'},
 {id:'l124-columns',eyebrow:'Письменные действия',title:'Запятая стоит под запятой',body:'При сложении и вычитании десятичных дробей одинаковые разряды должны быть строго друг под другом. Пропущенную цифру восстанавливай по одному разряду, учитывая перенос или заём.',note:'№ 898 — проверка разрядной дисциплины.'},
 {id:'l124-estimate',eyebrow:'Прикидка',title:'До точного ответа оцени диапазон результата',body:'Округли числа мысленно и проверь порядок величины. Если точный ответ сильно расходится с прикидкой, вернись к знаку действия, разрядам и запятой.',note:'Прикидка не заменяет точный расчёт, но ловит грубые ошибки.'},
 {id:'l124-reverse',eyebrow:'Проверка',title:'Обратное действие подтверждает ответ',body:'Сложение можно проверить вычитанием, вычитание — сложением. В составной задаче дополнительно проверь смысл: часть не должна неожиданно превышать целое.',note:'Проверка — обязательный последний шаг перед ответом.'},
 {id:'l124-ready',eyebrow:'Итог § 33',title:'Готовность к контрольной № 7',body:'Сначала пройди точные № 887, 889, 895 и 898, затем итоговые задания МатНикита. Не гонись за скоростью: цель — устойчиво выбирать правильный приём.',note:'20 обязательных задач и 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyFourPractice.map((practice,i)=>({id:`l124-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Опорное задание ${practice.source}`:`Итог § 33 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l124-summary',eyebrow:'§ 33 завершён',title:'Сложение и вычитание десятичных дробей систематизированы',body:'Ты умеешь складывать и вычитать десятичные дроби, решать составные задачи, группировать удобные суммы, упрощать выражения и контролировать письменные вычисления.',note:'Следующий урок 125 — контрольная работа № 7.',summary:true}];
export const lessonOneHundredTwentyFourStageCount=stages.length;
export const lessonOneHundredTwentyFourPracticeTaskCount=lessonOneHundredTwentyFourPractice.length;
export const lessonOneHundredTwentyFourPracticeResponseCount=lessonOneHundredTwentyFourResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalSectionFinalePlayer(){const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==124||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));return <section className="lesson-player theory-experience" aria-label="Урок 124: итог параграфа 33"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь тип задачи, порядок действий и разряды.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 124 завершён</b><span>20 задач · 50 ответов · § 33 · 6 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 124"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>}
