import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwelvePractice,lessonOneHundredTwelveResponseCount,type Lesson112Practice} from './data/lessonOneHundredTwelvePractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson112Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-112-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l112-power-division',eyebrow:'Урок 112 · § 30 · 4 из 4',title:'Деление на тысячу и десять тысяч',body:'Когда делим натуральное число на тысячу или десять тысяч, число нулей в делителе задаёт три или четыре десятичных разряда. Так 58, делённое на тысячу, превращается в 0,058.',note:'Не двигай запятую на глаз — сначала определи нужное число разрядов.'},
{id:'l112-leading-zero',eyebrow:'Разрядная запись',title:'Ведущие нули сохраняют место цифры',body:'Если цифр делимого меньше, чем нужно разрядов после запятой, дополняй запись нулями слева. Семь десятитысячных записываются как 0,0007.',note:'Ноль здесь не украшение, а указатель разряда.'},
{id:'l112-ray-unit',eyebrow:'Координатный луч',title:'Единичный отрезок можно разделить на десятые',body:'Если единичный отрезок разделён на десять равных частей, каждое малое деление соответствует одной десятой. Первое деление после нуля имеет координату 0,1, шестое — 0,6.',note:'Номер деления от нуля равен числу десятых.'},
{id:'l112-ray-beyond-one',eyebrow:'Точки правее единицы',title:'После единицы счёт десятых продолжается',body:'Число 1,4 находится на четырнадцатом малом делении от нуля, 1,9 — на девятнадцатом, а 2,2 — на двадцать втором.',note:'Координата 2,2 означает две целых и ещё две десятых.'},
{id:'l112-ray-reverse',eyebrow:'Обратная задача',title:'По номеру деления восстанавливаем координату',body:'Если шаг равен 0,1, то деление номер 15 соответствует числу 1,5. Если шаг равен 0,01, деление номер 35 соответствует числу 0,35.',note:'Всегда сначала выясни цену одного малого деления.'},
{id:'l112-masked-digits',eyebrow:'Разрядная оценка',title:'Иногда точные младшие цифры не нужны',body:'Если два пятизначных числа начинаются с 35 и 32, первое больше независимо от остальных цифр. А любое трёхзначное число меньше любого четырёхзначного.',note:'Сначала количество цифр, затем первая различающаяся старшая цифра.'},
{id:'l112-synthesis',eyebrow:'Связь идей',title:'Дробь, частное и точка на луче — одна разрядная система',body:'Запись 0,6 можно понимать как шесть десятых, как результат деления 6 на 10 и как координату шестого деления на луче с шагом 0,1.',note:'Одна и та же десятичная запись описывает число разными способами.'},
{id:'l112-ready',eyebrow:'Перед практикой',title:'Завершаем § 30',body:'Сначала выполни точные задания 810 пункты с четвёртого по шестой, 813 и 818. Затем закрепи ведущие нули, координатный луч, обратные переходы и разрядную оценку.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwelvePractice.map((practice,i)=>({id:`l112-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Итог § 30 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l112-summary',eyebrow:'Итог урока 112',title:'§ 30 завершён',body:'Ты уверенно записываешь частные при делении на тысячу и десять тысяч, сохраняешь ведущие нули, находишь десятичные дроби на координатном луче и используешь старшие разряды для оценки числа.',note:'Следующий урок 113 открывает § 31 — сравнение десятичных дробей.',summary:true}];
export const lessonOneHundredTwelveStageCount=stages.length;
export const lessonOneHundredTwelvePracticeTaskCount=lessonOneHundredTwelvePractice.length;
export const lessonOneHundredTwelvePracticeResponseCount=lessonOneHundredTwelveResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalRaySynthesisPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==112||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 112: координатный луч и итог параграфа 30"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь разряд, цену деления луча или первую различающуюся старшую цифру.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 112 завершён</b><span>20 задач · 50 ответов · § 30 завершён</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 112"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
