import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyThreePractice,lessonOneHundredTwentyThreeResponseCount,type Lesson123Field,type Lesson123Practice} from './data/lessonOneHundredTwentyThreePractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson123Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-123-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—−]/g,'-');
const matchField=(value:string,field:Lesson123Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
 {id:'l123-grouping',eyebrow:'Урок 123 · § 33 · 5 из 6',title:'Сначала ищем удобные пары',body:'В длинной сумме переместительное и сочетательное свойства позволяют поставить рядом числа, которые дают круглую сумму. Это сокращает вычисления и число ошибок.',note:'У сложения можно менять порядок слагаемых; у цепочки зависимых действий — нельзя.'},
 {id:'l123-like-terms',eyebrow:'Упрощение выражений',title:'Числа собираем с числами, одинаковые буквы — друг с другом',body:'В выражении с буквами сначала сгруппируй постоянные числовые слагаемые, а затем одинаковые буквенные части. Так длинная запись превращается в короткую.',note:'Например, m + m = 2m.'},
 {id:'l123-chains',eyebrow:'Цепочка',title:'Каждый шаг использует предыдущий результат',body:'В цепочках вычислений нельзя переставлять смысловые шаги. Записывай промежуточный результат после каждого действия и только затем переходи дальше.',note:'Это одновременно вычисление и самопроверка.'},
 {id:'l123-difference',eyebrow:'Разность',title:'Следим отдельно за уменьшаемым и вычитаемым',body:'Если уменьшаемое растёт, разность растёт на столько же. Если вычитаемое растёт, разность уменьшается на столько же. При двух изменениях учитывай оба эффекта.',note:'Разность = уменьшаемое − вычитаемое.'},
 {id:'l123-units',eyebrow:'Величины',title:'Перед вычислением единицы должны совпадать',body:'Нельзя напрямую складывать дециметры и сантиметры. Сначала переведи обе величины в одну единицу, а уже потом выполняй действие с десятичными дробями.',note:'1 дм = 10 см; 1 м = 10 дм.'},
 {id:'l123-backwards',eyebrow:'Обратный ход',title:'Иногда задачу проще решать с конца',body:'Если известен итог многошагового процесса, можно отменять действия в обратном порядке. Это особенно удобно в задаче № 908: сначала возвращаем отданные монеты, потом отменяем удвоение.',note:'Обратная операция к вычитанию — сложение, к удвоению — деление на 2.'},
 {id:'l123-check',eyebrow:'Самоконтроль',title:'Оцени результат до точного ответа',body:'Проверь порядок величины, единицы измерения и направление изменения. Затем точным обратным действием убедись, что результат возвращает исходные данные.',note:'Правильная цифра с неправильной единицей — неправильный ответ.'},
 {id:'l123-ready',eyebrow:'Перед практикой',title:'Шесть опорных маршрутов § 33',body:'Начни с № 889, 895, 896, 900, 901 и 908, затем закрепи те же навыки на авторских заданиях MathNikita.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyThreePractice.map((practice,i)=>({id:`l123-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Опорное задание ${practice.source}`:`Синтез § 33 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l123-summary',eyebrow:'Итог урока 123',title:'Навыки § 33 собраны в единую систему',body:'Ты умеешь группировать суммы, упрощать выражения, вести вычислительные цепочки, прогнозировать изменение разности и приводить величины к одинаковым единицам.',note:'Урок 124 завершит § 33 итоговым закреплением.',summary:true}];
export const lessonOneHundredTwentyThreeStageCount=stages.length;
export const lessonOneHundredTwentyThreePracticeTaskCount=lessonOneHundredTwentyThreePractice.length;
export const lessonOneHundredTwentyThreePracticeResponseCount=lessonOneHundredTwentyThreeResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalSynthesisMeasurementsPlayer(){const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==123||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));return <section className="lesson-player theory-experience" aria-label="Урок 123: сложение и вычитание десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь порядок действий, единицы и удобную группировку.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 123 завершён</b><span>20 задач · 50 ответов · § 33 · 5 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 123"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>}
