import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredFifteenPractice,lessonOneHundredFifteenResponseCount,type Lesson115Field,type Lesson115Practice} from './data/lessonOneHundredFifteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson115Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-115-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const matchField=(value:string,field:Lesson115Field)=>{const normalized=norm(value);if(field.minExclusive!==undefined||field.maxExclusive!==undefined){const number=Number(normalized);if(!Number.isFinite(number))return false;if(field.minExclusive!==undefined&&!(number>field.minExclusive))return false;if(field.maxExclusive!==undefined&&!(number<field.maxExclusive))return false;return true}return field.answers.some(answer=>normalized===norm(answer))};
const concepts:Stage[]=[
{id:'l115-fixed-step',eyebrow:'Урок 115 · § 31 · 3 из 3',title:'Фиксированная точность задаёт шаг',body:'Если разрешена ровно одна цифра после запятой, соседние допустимые записи отличаются на одну десятую. При двух цифрах шаг равен одной сотой, при трёх — одной тысячной.',note:'Именно поэтому у задачи на минимальную дробь появляется однозначный ответ только при заданном числе знаков.'},
{id:'l115-minimal-greater',eyebrow:'Минимум при заданном числе знаков',title:'Сдвинься на один последний разряд',body:'Чтобы получить наименьшую дробь, строго большую целого числа, поставь единицу в последний разрешённый десятичный разряд, а все предыдущие дробные разряды заполни нулями.',note:'Для четырёх знаков после запятой минимальный положительный шаг равен одной десятитысячной.'},
{id:'l115-density',eyebrow:'Числа внутри интервала',title:'Между разными десятичными дробями можно строить новые',body:'Если точность не ограничена, к записи можно добавлять новые разряды. Поэтому между двумя различными десятичными дробями всегда можно подобрать ещё одну, а затем ещё одну.',note:'У десятичных дробей без ограничения числа знаков нет «следующего» числа.'},
{id:'l115-build-between',eyebrow:'Конструирование',title:'Добавляй разряд и держись внутри обеих границ',body:'Для узкого интервала удобно дописать нули до одинаковой длины, затем добавить ещё один разряд и выбрать число, которое строго больше левой границы и строго меньше правой.',note:'После выбора обязательно проверь обе строгие границы.'},
{id:'l115-ordering',eyebrow:'Упорядочивание',title:'Сначала сравни старшие разряды',body:'Когда нужно расположить несколько чисел, сравнивай их слева направо. Для десятичных дробей при необходимости дописывай нули справа, а для натуральных чисел сначала сравни сотни, затем десятки и единицы.',note:'Системный порядок надёжнее случайного перебора.'},
{id:'l115-permutations',eyebrow:'Перестановки цифр',title:'Группируй числа по первой цифре',body:'Если из нескольких цифр строятся все числа без повторений, сначала выпиши варианты с наименьшей первой цифрой, внутри группы упорядочь оставшиеся, затем переходи к следующей первой цифре.',note:'Так легко получить полный список без пропусков и дублей.'},
{id:'l115-optimization',eyebrow:'Итоговая логика',title:'Иногда быстрее считать дополнение',body:'В задаче на минимальное время не всегда нужно выполнять действие буквально. Если требуется оставить большую часть набора, может быть быстрее отсчитать меньшую лишнюю часть и убрать её.',note:'Сравни объём прямого действия и дополнения до целого.'},
{id:'l115-ready',eyebrow:'Перед практикой',title:'Закрываем § 31 полностью',body:'Сначала реши точные задания 834, 836, 842 и дополнительную 843, затем закрепи минимальные дроби при фиксированной точности, числа внутри интервала и системное упорядочивание.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredFifteenPractice.map((practice,i)=>({id:`l115-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Итог сравнения · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l115-summary',eyebrow:'Итог урока 115',title:'§ 31 полностью завершён',body:'Ты умеешь сравнивать и упорядочивать десятичные дроби, находить числа внутри интервала, понимать роль фиксированной точности и строить минимальные или максимальные допустимые записи.',note:'Следующий урок 116 начинает § 32: округление чисел и прикидки.',summary:true}];
export const lessonOneHundredFifteenStageCount=stages.length;
export const lessonOneHundredFifteenPracticeTaskCount=lessonOneHundredFifteenPractice.length;
export const lessonOneHundredFifteenPracticeResponseCount=lessonOneHundredFifteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalComparisonSynthesisPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const fieldValues=task?task.fields.map(f=>responses[`${key}:${f.id}`]??''):[];const fieldsComplete=task?task.fields.every((f,index)=>matchField(fieldValues[index]??'',f)):true;const distinctComplete=task?.distinct?new Set(fieldValues.map(norm)).size===fieldValues.length&&fieldValues.every(v=>norm(v).length>0):true;const complete=fieldsComplete&&distinctComplete;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==115||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 115: итог сравнения десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь точность записи, обе границы интервала и порядок чисел.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 115 завершён</b><span>20 задач · 50 ответов · § 31 · 3 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 115"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
