import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredElevenPractice,lessonOneHundredElevenResponseCount,type Lesson111Practice} from './data/lessonOneHundredElevenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson111Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-111-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l111-unit-fraction',eyebrow:'Урок 111 · § 30 · 3 из 4',title:'Единицы измерения превращаются в десятичные дроби',body:'Чтобы выразить меньшую единицу через большую, сначала вспомни, сколько меньших единиц содержится в одной большой. Сантиметр — одна сотая метра, дециметр — одна десятая метра, грамм — одна тысячная килограмма.',note:'Сначала установи знаменатель, потом записывай десятичную дробь.'},
{id:'l111-centimeters',eyebrow:'Сантиметры и метры',title:'Сантиметры занимают сотые доли метра',body:'Сто сантиметров составляют один метр. Поэтому 18 сантиметров — это восемнадцать сотых метра, то есть 0,18 метра. Если сантиметров больше ста, появляется целая часть: 125 сантиметров — это 1,25 метра.',note:'Проверка: число сантиметров и сотые доли метра связаны напрямую.'},
{id:'l111-mixed-measure',eyebrow:'Смешанные меры длины',title:'Дециметры идут в десятые, сантиметры — в сотые',body:'В записи 4 метра 6 дециметров 5 сантиметров целая часть равна четырём, шесть занимает разряд десятых, пять — сотых. Получается 4,65 метра.',note:'Не складывай цифры: каждой единице соответствует свой разряд.'},
{id:'l111-division',eyebrow:'Деление на 10, 100 и 1000',title:'Частное можно сразу записать десятичной дробью',body:'Деление натурального числа на десять, сто или тысячу — это та же разрядная идея. 42 разделить на 10 даёт 4,2, а 35 разделить на 100 даёт 0,35.',note:'Количество нулей в делителе определяет число разрядов после запятой.'},
{id:'l111-zeroes',eyebrow:'Нули сохраняют разряд',title:'Маленькая величина требует ведущего нуля',body:'Семь сантиметров — это 0,07 метра, а двадцать четыре грамма — 0,024 килограмма. Нули показывают, что цифра стоит именно в сотых или тысячных.',note:'Перед ответом проверь, не стал ли он в десять или сто раз больше нужного.'},
{id:'l111-time',eyebrow:'Задачи с временем',title:'Сравнивай величины только после приведения к одной единице',body:'Если одна величина дана в часах и минутах, а другая — дробью часа, переведи обе в минуты. После этого отношение находится обычным делением.',note:'Для задачи № 816 обе величины удобно перевести в минуты.'},
{id:'l111-estimate',eyebrow:'Самопроверка',title:'Оценка величины ловит ошибку раньше вычислений',body:'Если 72 сантиметра меньше метра, ответ в метрах тоже должен быть меньше единицы. Если 605 сантиметров больше шести метров, запись 0,605 метра сразу выглядит неверно.',note:'Сначала оцени диапазон, затем проверяй цифры.'},
{id:'l111-ready',eyebrow:'Перед практикой',title:'Соедини измерения, дроби и деление',body:'Сначала выполни точные задания 808, 810 пункты с первого по третий и 816. Затем закрепи переводы между метрами, дециметрами, сантиметрами, килограммами и граммами, а также деление на десять, сто и тысячу.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredElevenPractice.map((practice,i)=>({id:`l111-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Переводы и десятичная запись · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l111-summary',eyebrow:'Итог урока 111',title:'Десятичная запись величин освоена',body:'Ты переводишь сантиметры и дециметры в метры, граммы в килограммы, записываешь частные при делении на десять, сто и тысячу десятичными дробями и приводишь величины к одной единице перед сравнением.',note:'Урок 112 завершит § 30 и подготовит переход к сравнению десятичных дробей.',summary:true}];
export const lessonOneHundredElevenStageCount=stages.length;
export const lessonOneHundredElevenPracticeTaskCount=lessonOneHundredElevenPractice.length;
export const lessonOneHundredElevenPracticeResponseCount=lessonOneHundredElevenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalMeasurementPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==111||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 111: десятичная запись единиц измерения"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Сначала приведи величину к нужной единице и определи разряд: десятые, сотые или тысячные.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 111 завершён</b><span>20 задач · 50 ответов · § 30 · единицы измерения</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 111"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
