import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyPractice,lessonOneHundredTwentyResponseCount,type Lesson120Field,type Lesson120Practice} from './data/lessonOneHundredTwentyPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson120Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-120-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—-]/g,'');
const matchField=(value:string,field:Lesson120Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l120-place-value',eyebrow:'Урок 120 · § 33 · 2 из 6',title:'Вычитаем только одинаковые разряды',body:'Как и при сложении, единицы должны стоять под единицами, десятые под десятыми, сотые под сотыми. Ошибка в выравнивании разрядов меняет само значение вычисления.',note:'Главный ориентир записи — запятая под запятой.'},
{id:'l120-equalize',eyebrow:'Подготовка записи',title:'Недостающие знаки после запятой дополняем нулями',body:'Нули справа в дробной части не меняют число. Поэтому 13,5 можно записать как 13,50, а 20 — как 20,00. Такая запись делает каждый разряд видимым.',note:'Перед вычитанием удобно сделать одинаковое количество знаков после запятой.'},
{id:'l120-comma-column',eyebrow:'Запись столбиком',title:'Вычитаемое ставим под уменьшаемым',body:'Запиши числа так, чтобы запятые совпали по вертикали. Тогда каждый разряд вычитаемого окажется под соответствующим разрядом уменьшаемого.',note:'Нельзя выравнивать числа просто по последней цифре.'},
{id:'l120-subtract-natural',eyebrow:'Само вычитание',title:'После выравнивания действуем как с натуральными числами',body:'Вычитай справа налево. Если цифры уменьшаемого недостаточно, переходи к старшему разряду и превращай одну его единицу в десять единиц текущего разряда.',note:'Механика перехода через разряд та же, что в натуральных числах.'},
{id:'l120-borrow-across-comma',eyebrow:'Переход через запятую',title:'Переход между целой и дробной частью разрешён',body:'Запятая не прерывает разрядную цепочку. Например, при вычислении 13,50 минус 8,28 единица из целой части может перейти в десятые, а затем в сотые.',note:'Запятая только отделяет целые разряды от дробных.'},
{id:'l120-zero-chain',eyebrow:'Цепочка нулей',title:'Целое число можно развернуть в дробные разряды',body:'В примере 20 минус 5,63 сначала полезно увидеть 20,00. Чтобы вычесть сотые и десятые, переход может пройти через нули и создать нужные единицы младших разрядов.',note:'Именно так получается 14,37.'},
{id:'l120-check',eyebrow:'Проверка результата',title:'Разность должна быть разумной',body:'Если из большего положительного числа вычитаем меньшее, ответ должен быть меньше уменьшаемого и неотрицательным. Быстрая прикидка помогает заметить ошибку в запятой или переходе через разряд.',note:'Для 19,8 минус 7,34 разумный ответ находится около 13.'},
{id:'l120-ready',eyebrow:'Перед практикой',title:'Правило → № 867 → № 873 → № 875',body:'Сначала восстанови правило вычитания, затем реши шесть точных разностей № 867 и две задачи на движение по реке. После этого закрепи нули справа, переход через разряд, цепочки нулей и проверку результата.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyPractice.map((practice,i)=>({id:`l120-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Вычитание десятичных дробей · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l120-summary',eyebrow:'Итог урока 120',title:'Вычитание десятичных дробей освоено',body:'Ты умеешь выравнивать одинаковые разряды, дописывать нули справа, вычитать поразрядно с переходом через разряд и применять сложение и вычитание скоростей в задачах на течение.',note:'Урок 121 объединит сложение и вычитание десятичных дробей в более сложных упражнениях § 33.',summary:true}];
export const lessonOneHundredTwentyStageCount=stages.length;
export const lessonOneHundredTwentyPracticeTaskCount=lessonOneHundredTwentyPractice.length;
export const lessonOneHundredTwentyPracticeResponseCount=lessonOneHundredTwentyResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalSubtractionFoundationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==120||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 120: вычитание десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Совмести одинаковые разряды: запятая должна стоять под запятой.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 120 завершён</b><span>20 задач · 50 ответов · § 33 · 2 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 120"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
