import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyOnePractice,lessonOneHundredTwentyOneResponseCount,type Lesson121Field,type Lesson121Practice} from './data/lessonOneHundredTwentyOnePractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson121Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-121-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—−]/g,'-');
const matchField=(value:string,field:Lesson121Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
 {id:'l121-inverse-operations',eyebrow:'Урок 121 · § 33 · 3 из 6',title:'Сложение и вычитание работают как обратные действия',body:'Уравнение показывает связь между компонентами действия. Чтобы найти неизвестное, сначала определи его роль, а затем используй обратное действие. Это надёжнее, чем угадывать знак операции.',note:'Смысл компонента важнее внешнего вида примера.'},
 {id:'l121-unknown-addend',eyebrow:'Неизвестное слагаемое',title:'Из суммы вычитаем известное слагаемое',body:'Если известно, что некоторое число вместе с 15,62 даёт 20, то неизвестную часть находим разностью 20 и 15,62. После вычисления обязательно проверь сумму.',note:'Неизвестное слагаемое = сумма минус известное слагаемое.'},
 {id:'l121-unknown-minuend',eyebrow:'Неизвестное уменьшаемое',title:'К разности прибавляем вычитаемое',body:'В равенстве x минус 36,76 равно 19,24 неизвестное стоит до знака вычитания. Чтобы восстановить исходное большее число, складываем 19,24 и 36,76.',note:'Неизвестное уменьшаемое = разность плюс вычитаемое.'},
 {id:'l121-unknown-subtrahend',eyebrow:'Неизвестное вычитаемое',title:'Из уменьшаемого вычитаем разность',body:'Если 9,54 минус x равно 7,268, неизвестное показывает, сколько отняли. Поэтому из 9,54 вычитаем 7,268.',note:'Неизвестное вычитаемое = уменьшаемое минус разность.'},
 {id:'l121-parentheses',eyebrow:'Уравнения со скобками',title:'Сначала считай скобки одним неизвестным компонентом',body:'В сложном уравнении не нужно раскрывать всё сразу. Например, выражение x минус 50,6 можно временно считать одним неизвестным слагаемым, найти его значение, а затем решить более простое уравнение.',note:'Двигайся от внешнего действия к внутреннему.'},
 {id:'l121-check-substitution',eyebrow:'Проверка',title:'Подстановка ловит ошибку в выбранном действии',body:'После нахождения корня подставь его в исходное уравнение и вычисли обе части. Если равенство не восстановилось, ошибка возникла либо при выборе обратного действия, либо в вычислениях.',note:'Проверка — часть решения, а не дополнительный шаг.'},
 {id:'l121-word-model',eyebrow:'Текстовая задача',title:'Сначала модель величин, потом вычисления',body:'В задаче про глубины сначала найди неизвестную глубину Байкала, затем сравни пары озёр. Одна длинная запись без промежуточного смысла чаще приводит к путанице единиц и действий.',note:'Каждое действие должно отвечать на конкретный вопрос задачи.'},
 {id:'l121-ready',eyebrow:'Перед практикой',title:'№ 869 → № 882 → № 892',body:'Начни с трёх точных заданий учебника: четыре базовых уравнения, задача про глубины озёр и два уравнения со скобками. Затем закрепи обратные действия, составные выражения, удобные вычисления, прикидку и проверку.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyOnePractice.map((practice,i)=>({id:`l121-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Сложение и вычитание · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l121-summary',eyebrow:'Итог урока 121',title:'Уравнения и составные задачи § 33 освоены',body:'Ты умеешь определять неизвестный компонент сложения или вычитания, выбирать обратное действие, решать уравнения со скобками, проверять корни подстановкой и строить последовательность действий в текстовых задачах.',note:'Урок 122 продолжит закрепление сложения и вычитания десятичных дробей по следующему маршруту § 33.',summary:true}];
export const lessonOneHundredTwentyOneStageCount=stages.length;
export const lessonOneHundredTwentyOnePracticeTaskCount=lessonOneHundredTwentyOnePractice.length;
export const lessonOneHundredTwentyOnePracticeResponseCount=lessonOneHundredTwentyOneResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalAddSubtractEquationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==121||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 121: сложение и вычитание десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Сначала определи неизвестный компонент или порядок действий.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 121 завершён</b><span>20 задач · 50 ответов · § 33 · 3 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 121"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
