import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyTwoPractice,lessonOneHundredTwentyTwoResponseCount,type Lesson122Field,type Lesson122Practice} from './data/lessonOneHundredTwentyTwoPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson122Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-122-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—−]/g,'-');
const matchField=(value:string,field:Lesson122Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
 {id:'l122-dependency-map',eyebrow:'Урок 122 · § 33 · 4 из 6',title:'Составная задача начинается с карты зависимостей',body:'Перед вычислениями выпиши, какая величина известна напрямую, какая сравнивается с ней и какая зависит от уже найденной суммы. Такой порядок не даёт потерять смысл между несколькими действиями.',note:'Сначала связи между величинами, затем арифметика.'},
 {id:'l122-more-less',eyebrow:'Слова-сигналы',title:'«На больше» и «на меньше» читаем относительно опорной величины',body:'Если первая величина на некоторое число больше второй, то вторую находим вычитанием из первой. Если нужно найти большую величину по меньшей, используем сложение. Всегда проговаривай, что с чем сравнивается.',note:'Не выбирай действие только по слову «больше» или «меньше».'},
 {id:'l122-total-parts',eyebrow:'Общее и части',title:'Неизвестная часть равна общему минус известные части',body:'Когда известна общая площадь или масса, сначала восстанови все известные части, затем сложи их и вычти из общего. После этого проверь, что сумма всех частей снова даёт исходное общее.',note:'Проверка суммой особенно полезна в задачах с тремя частями.'},
 {id:'l122-step-chain',eyebrow:'Последовательность действий',title:'Каждый промежуточный результат отвечает на отдельный вопрос',body:'В хорошей записи можно объяснить смысл каждого числа: сколько было во второй день, сколько вместе за два дня, сколько осталось или сколько пришлось на третью часть.',note:'Если промежуточное число нечем назвать, проверь логику решения.'},
 {id:'l122-commutative',eyebrow:'Удобные суммы',title:'Слагаемые можно менять местами',body:'При сложении десятичных дробей порядок слагаемых не меняет сумму. Поэтому полезно поставить рядом числа, которые дополняют друг друга до целого значения.',note:'Ищи пары до единицы, десяти, двадцати и других круглых чисел.'},
 {id:'l122-associative',eyebrow:'Группировка',title:'Слагаемые можно объединять в удобные пары',body:'После перестановки сгруппируй числа так, чтобы промежуточные суммы были простыми. Это снижает число переносов по разрядам и уменьшает риск арифметической ошибки.',note:'Меняем порядок и группировку только у сложения, не у смысловых шагов текстовой задачи.'},
 {id:'l122-estimate-check',eyebrow:'Самоконтроль',title:'Проверяй и точность, и смысл',body:'Для длинной суммы полезно заранее оценить порядок результата, а в текстовой задаче — проверить, может ли найденная часть быть отрицательной или превышать общее. Затем сделай точную обратную проверку.',note:'Правдоподобие результата проверяется до финального ответа.'},
 {id:'l122-ready',eyebrow:'Перед практикой',title:'№ 884 → № 886 → № 894',body:'Сначала реши три точных задания учебника: расход сахара по дням, площади трёх участков и две суммы с удобным порядком вычислений. Затем закрепи составные зависимости и рациональную группировку.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyTwoPractice.map((practice,i)=>({id:`l122-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Составные задачи и суммы · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l122-summary',eyebrow:'Итог урока 122',title:'Составные задачи и удобные вычисления освоены',body:'Ты умеешь строить цепочку зависимостей в текстовой задаче, восстанавливать неизвестную часть по общему, проверять сумму частей и переставлять слагаемые так, чтобы вычисления становились короче и надёжнее.',note:'Урок 123 продолжит § 33 следующими заданиями по 175-урочной КТП.',summary:true}];
export const lessonOneHundredTwentyTwoStageCount=stages.length;
export const lessonOneHundredTwentyTwoPracticeTaskCount=lessonOneHundredTwentyTwoPractice.length;
export const lessonOneHundredTwentyTwoPracticeResponseCount=lessonOneHundredTwentyTwoResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalCompositeSumsPlayer(){const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==122||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));return <section className="lesson-player theory-experience" aria-label="Урок 122: сложение и вычитание десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Сначала восстанови зависимости или найди удобную пару.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 122 завершён</b><span>20 задач · 50 ответов · § 33 · 4 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 122"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>}
