import { useEffect, useMemo, useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './decimalNotation.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type DecimalStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;answer:string;ordered:string[];checked:boolean;correct:boolean;results:Record<string,boolean>;completedAt?:string};
const KEY='mathnikita-lesson-3-progress-v1';

export const lessonThreeStages:DecimalStage[]=[
{id:'l3-story',kind:'story',eyebrow:'Проблемная ситуация',title:'Как прочитать число 17 025 543 607?',body:'Короткое число читается сразу. Но в длинной записи легко потерять разряды. Нужен способ, который работает с любым многозначным числом.',note:'Разобьём запись справа налево на группы по три цифры — классы.',sourceTag:'Мерзляк § 2'},
{id:'l3-digits',kind:'guided',eyebrow:'Математический алфавит',title:'Десять цифр — бесконечно много чисел',body:'Натуральные числа записывают десятью знаками: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Цифра — знак, число — запись из одной или нескольких цифр.',activity:{id:'l3-a1',type:'choice',prompt:'Что является цифрой, а не многозначным числом?',options:['7','17','507','7000'],answer:'7',explanation:'7 — одна цифра. Остальные записи состоят из нескольких цифр.'}},
{id:'l3-length',kind:'guided',eyebrow:'Количество цифр',title:'Однозначные и многозначные числа',body:'Число, записанное одной цифрой, называют однозначным; двумя — двузначным; тремя — трёхзначным. Все остальные — многозначные.',activity:{id:'l3-a2',type:'choice',prompt:'Как называют число 40 305?',options:['трёхзначным','четырёхзначным','пятизначным','шестизначным'],answer:'пятизначным',explanation:'В записи 40 305 пять цифр.'}},
{id:'l3-leading-zero',kind:'guided',eyebrow:'Важное ограничение',title:'Запись натурального числа не начинается с нуля',body:'Нуль внутри числа показывает отсутствующий разряд. Но ведущий нуль не создаёт нового числа: 007 и 7 — одно и то же число.',activity:{id:'l3-a3',type:'choice',prompt:'Какая запись является обычной десятичной записью числа семь?',options:['007','07','7','0007'],answer:'7',explanation:'Стандартная запись натурального числа начинается с ненулевой цифры.'}},
{id:'l3-place',kind:'model',eyebrow:'Позиционная система',title:'Значение цифры зависит от места',body:'В числе 5 505 первая цифра 5 означает пять тысяч, средняя — пять сотен, последняя — пять единиц.',note:'Место цифры в записи числа называют разрядом.',sourceTag:'Мерзляк § 2; алгоритмы чтения и записи'},
{id:'l3-classes',kind:'model',eyebrow:'Разбиваем запись',title:'В каждом классе три разряда',body:'Справа налево идут классы единиц, тысяч, миллионов, миллиардов. В каждом классе есть сотни, десятки и единицы.',note:'Крайний левый класс может содержать одну, две или три цифры.'},
{id:'l3-split',kind:'practice',eyebrow:'Пробуем сами',title:'Раздели число на классы',body:'Начинай справа и отделяй по три цифры.',activity:{id:'l3-p1',type:'input',prompt:'Запиши 17025543607, разделив классы пробелами',answer:'17 025 543 607',placeholder:'Например: 12 345 678',explanation:'Справа получаем классы 607, 543, 025 и 17.'}},
{id:'l3-class-names',kind:'guided',eyebrow:'Называем классы',title:'Единицы, тысячи, миллионы, миллиарды',body:'При чтении называют число внутри каждого ненулевого класса и добавляют название класса. Название класса единиц обычно не произносят.',activity:{id:'l3-a4',type:'choice',prompt:'Как называется класс 025 в числе 17 025 543 607?',options:['единиц','тысяч','миллионов','миллиардов'],answer:'миллионов',explanation:'Справа идут: единицы 607, тысячи 543, миллионы 025, миллиарды 17.'}},
{id:'l3-read',kind:'practice',eyebrow:'Читаем число',title:'Нулевые классы пропускаются',body:'Если все три цифры класса — нули, название этого класса при чтении не произносят.',activity:{id:'l3-p2',type:'choice',prompt:'Как правильно прочитать 8 000 045?',options:['восемь миллионов сорок пять','восемь миллионов ноль тысяч сорок пять','восемь тысяч сорок пять','восемь миллионов четыреста пять'],answer:'восемь миллионов сорок пять',explanation:'Класс тысяч равен 000, поэтому его название не произносят.'}},
{id:'l3-write',kind:'practice',eyebrow:'Записываем по названию',title:'Каждому классу — три места',body:'Если в названии отсутствует класс, в его трёх разрядах нужно поставить нули.',activity:{id:'l3-p3',type:'input',prompt:'Запиши цифрами: двенадцать миллионов пять тысяч семь',answer:'12005007',placeholder:'Только цифры',explanation:'12 миллионов, 005 тысяч и 007 единиц: 12 005 007.'}},
{id:'l3-zero-role',kind:'guided',eyebrow:'Роль нуля',title:'Нуль удерживает место разряда',body:'В числе 204 цифра 0 показывает отсутствие десятков. Без неё получилось бы число 24.',activity:{id:'l3-a5',type:'choice',prompt:'Что означает 0 в числе 70 406?',options:['нет тысяч','нет сотен','нет десятков тысяч','нет единиц'],answer:'нет тысяч',explanation:'70 406 = 70 тысяч 406; разряд единиц тысяч равен нулю.'}},
{id:'l3-expanded',kind:'model',eyebrow:'Разрядные слагаемые',title:'Число можно разложить по разрядам',body:'Например, 507 042 = 500 000 + 7 000 + 40 + 2. Разряды с нулевой цифрой в сумму не включают.',note:'Такое представление показывает значение каждой цифры.'},
{id:'l3-expand-practice',kind:'practice',eyebrow:'Закрепление',title:'Составь сумму разрядных слагаемых',body:'Смотри на значение каждой ненулевой цифры.',activity:{id:'l3-p4',type:'choice',prompt:'Как разложить число 63 205?',options:['60 000 + 3 000 + 200 + 5','6 000 + 300 + 20 + 5','60 000 + 300 + 20 + 5','60 000 + 3 000 + 20 + 5'],answer:'60 000 + 3 000 + 200 + 5',explanation:'6 десятков тысяч, 3 тысячи, 2 сотни и 5 единиц.'}},
{id:'l3-compose',kind:'practice',eyebrow:'Обратная задача',title:'Собери число из разрядных слагаемых',body:'Запиши каждое слагаемое на своём месте, не потеряв нулевые разряды.',activity:{id:'l3-p5',type:'input',prompt:'Какое число равно 400 000 + 20 000 + 300 + 8?',answer:'420308',explanation:'Получаем 420 308.'}},
{id:'l3-place-name',kind:'practice',eyebrow:'Точный язык',title:'Какой разряд занимает цифра?',body:'Двойное название разряда однозначно определяет место цифры: единицы тысяч, десятки миллионов и так далее.',activity:{id:'l3-p6',type:'choice',prompt:'Какой разряд занимает цифра 7 в числе 372 405 019?',options:['единицы миллионов','десятки миллионов','сотни миллионов','единицы тысяч'],answer:'десятки миллионов',explanation:'Класс миллионов — 372: 3 сотни миллионов, 7 десятков миллионов, 2 единицы миллионов.'}},
{id:'l3-order',kind:'guided',eyebrow:'Алгоритм',title:'Порядок чтения многозначного числа',body:'1) Разбей справа на классы. 2) Читай слева направо. 3) Добавляй название каждого ненулевого класса. 4) Класс единиц читай без названия.',activity:{id:'l3-a6',type:'order',prompt:'Расставь шаги алгоритма',answer:['Разбить справа по три цифры','Читать классы слева направо','Добавлять названия классов','Пропускать нулевые классы'],explanation:'Сначала формируем классы, затем читаем их слева направо.'}},
{id:'l3-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Цифры и числа',body:'Ответь без подсказки.',activity:{id:'l3-q1',type:'choice',prompt:'Сколько цифр используют в десятичной записи?',options:['9','10','11','бесконечно много'],answer:'10',explanation:'Используют цифры от 0 до 9.'}},
{id:'l3-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Классы числа',body:'Ответь без подсказки.',activity:{id:'l3-q2',type:'input',prompt:'Сколько классов в записи 702 354 023 009?',answer:'4',explanation:'Классы: миллиарды, миллионы, тысячи, единицы.'}},
{id:'l3-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Запись по названию',body:'Ответь без подсказки.',activity:{id:'l3-q3',type:'input',prompt:'Запиши: девять миллионов сорок два',answer:'9000042',explanation:'Классы: 9 | 000 | 042.'}},
{id:'l3-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Разряд цифры',body:'Ответь без подсказки.',activity:{id:'l3-q4',type:'choice',prompt:'Что означает цифра 6 в числе 861 204?',options:['6 единиц','6 тысяч','6 десятков тысяч','6 сотен тысяч'],answer:'6 десятков тысяч',explanation:'В классе тысяч 861: 8 сотен тысяч, 6 десятков тысяч, 1 тысяча.'}},
{id:'l3-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Разрядная сумма',body:'Ответь без подсказки.',activity:{id:'l3-q5',type:'input',prompt:'Собери число: 8 000 000 + 50 000 + 600 + 3',answer:'8050603',explanation:'Получаем 8 050 603.'}},
{id:'l3-challenge',kind:'challenge',eyebrow:'Исследовательская задача',title:'Сколько чисел можно составить?',body:'Используй цифры 0, 2 и 5 по одному разу. Первая цифра не может быть нулём.',activity:{id:'l3-c1',type:'input',prompt:'Сколько различных трёхзначных чисел можно составить?',answer:'4',explanation:'205, 250, 502 и 520. Записи 025 и 052 не являются трёхзначными.'}},
{id:'l3-summary',kind:'summary',eyebrow:'Итог',title:'Урок завершён',body:'Ты различаешь цифру и число, читаешь и записываешь многозначные числа, определяешь классы и разряды и представляешь число суммой разрядных слагаемых.'}
];

const empty:Saved={version:1,stageIndex:0,answer:'',ordered:[],checked:false,correct:false,results:{}};
function norm(v:string){return v.trim().toLowerCase().replace(/\s+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const p=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return p?.version===1?{...empty,...p,stageIndex:Math.min(Math.max(Number(p.stageIndex)||0,0),lessonThreeStages.length-1),ordered:Array.isArray(p.ordered)?p.ordered:[],results:p.results??{}}:empty}catch{return empty}}
export function DecimalNotationPlayer(){const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[answer,setAnswer]=useState(saved.answer);const[ordered,setOrdered]=useState<string[]>(saved.ordered);const[checked,setChecked]=useState(saved.checked);const[correct,setCorrect]=useState(saved.correct);const[results,setResults]=useState<Record<string,boolean>>(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);const stage=lessonThreeStages[stageIndex];const activity=stage.activity;const quiz=['l3-q1','l3-q2','l3-q3','l3-q4','l3-q5'];const practice=['l3-p1','l3-p2','l3-p3','l3-p4','l3-p5','l3-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonThreeStages.length)*100);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,answer,ordered,checked,correct,results,completedAt})),[stageIndex,answer,ordered,checked,correct,results,completedAt]);
useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
useEffect(()=>{const handler=(e:Event)=>{const d=(e as CustomEvent).detail;if(d?.lessonNumber===3&&Number.isInteger(d.stageIndex))goTo(d.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function resetStage(){setAnswer('');setOrdered([]);setChecked(false);setCorrect(false)}function goTo(i:number){setStageIndex(Math.min(Math.max(i,0),lessonThreeStages.length-1));resetStage();window.scrollTo({top:0,behavior:'smooth'})}function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setCorrect(ok);setChecked(true);setResults(r=>({...r,[activity.id]:ok}))}function reset(){localStorage.removeItem(KEY);setStageIndex(0);setAnswer('');setOrdered([]);setChecked(false);setCorrect(false);setResults({});setCompletedAt(undefined)}
const model=useMemo(()=>{if(stage.id==='l3-story'||stage.id==='l3-classes'||stage.id==='l3-split'||stage.id==='l3-class-names'||stage.id==='l3-read')return <div className="class-table"><div><small>миллиарды</small><b>17</b></div><div><small>миллионы</small><b>025</b></div><div><small>тысячи</small><b>543</b></div><div><small>единицы</small><b>607</b></div></div>;if(stage.id==='l3-digits')return <div className="digit-strip">{[0,1,2,3,4,5,6,7,8,9].map(n=><b key={n}>{n}</b>)}</div>;if(stage.id==='l3-place'||stage.id==='l3-zero-role'||stage.id==='l3-expanded'||stage.id==='l3-expand-practice'||stage.id==='l3-compose'||stage.id==='l3-place-name')return <div className="place-value-board"><b>507 042</b><span>500 000 + 7 000 + 40 + 2</span></div>;return null},[stage.id]);
function render(a:Activity){if(a.type==='choice')return <div className="activity-area"><h3>{a.prompt}</h3><div className="choice-grid">{a.options!.map(o=><button key={o} className={answer===o?'selected':''} onClick={()=>{setAnswer(o);setChecked(false)}}>{o}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;if(a.type==='input')return <div className="activity-area"><h3>{a.prompt}</h3><div className="inline-answer"><input value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false)}} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder={a.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;const items=['Разбить справа по три цифры','Читать классы слева направо','Добавлять названия классов','Пропускать нулевые классы'];return <div className="activity-area"><h3>{a.prompt}</h3><div className="order-bank">{items.map(i=><button key={i} disabled={ordered.includes(i)} onClick={()=>{setOrdered(v=>[...v,i]);setChecked(false)}}>{i}</button>)}</div><div className="order-result">{ordered.map((i,n)=><button key={i} onClick={()=>setOrdered(v=>v.filter((_,x)=>x!==n))}>{i}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>}
return <main className="lesson-player-page decimal-notation-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 3 из 175 · § 2</span><h1>Цифры. Десятичная запись натуральных чисел</h1><p>Урок построен по учебнику Мерзляка, технологической карте урока № 3 и алгоритмам чтения и записи многозначных чисел.</p></div><div className="lesson-duration">35–40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonThreeStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{checked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь классы и разряды. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&checked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonThreeStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>}
