import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredThirteenPractice,lessonOneHundredThirteenResponseCount,type Lesson113Practice} from './data/lessonOneHundredThirteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson113Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-113-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l113-trailing-zero',eyebrow:'Урок 113 · § 31 · 1 из 3',title:'Нули справа не меняют десятичную дробь',body:'Если после последней цифры дробной части приписать один или несколько нулей, значение числа не изменится. Поэтому 7,4, 7,40 и 7,400 обозначают одно число.',note:'Нули можно дописывать и убирать только справа в дробной части.'},
{id:'l113-equalize',eyebrow:'Подготовка к сравнению',title:'Уравняй количество знаков после запятой',body:'Чтобы разряды стояли друг под другом, допиши справа нули. Например, 24,9 удобно представить как 24,90, а 18,5 как 18,500.',note:'Это не меняет числа, но делает сравнение прозрачным.'},
{id:'l113-whole-part',eyebrow:'Первый шаг',title:'Сначала сравни целые части',body:'Если целые части различаются, большему целому соответствует большее число. Поэтому 16,8 меньше 17,3, а 9,999 меньше 10.',note:'К дробной части переходи только при равных целых частях.'},
{id:'l113-digit-by-digit',eyebrow:'Поразрядное сравнение',title:'Ищи первый различающийся разряд',body:'При равных целых частях сравни десятые, затем сотые, тысячные и дальше слева направо. Первый различающийся разряд сразу определяет результат.',note:'В 12,345 и 12,3449 первое различие находится в тысячных.'},
{id:'l113-different-length',eyebrow:'Разное число знаков',title:'Больше цифр после запятой не значит больше число',body:'Сравни 3,7 и 3,68 как 3,70 и 3,68. Две цифры после запятой сами по себе ничего не гарантируют: важны значения разрядов.',note:'Никогда не сравнивай десятичные дроби по длине записи.'},
{id:'l113-ordering',eyebrow:'Несколько чисел',title:'Упорядочивание — это серия сравнений',body:'Для набора чисел сначала уравняй дробные разряды, затем расставляй числа от меньшего к большему. Например, 9,6 удобно читать как 9,600 рядом с 9,613.',note:'Следи за первым различающимся разрядом в каждой паре.'},
{id:'l113-units',eyebrow:'Величины и задачи',title:'Сначала приведи величины к одной единице',body:'Сравнивать 1,2 метра и 125 сантиметров напрямую неудобно. Переведи 1,2 метра в 120 сантиметров, а затем сравни натуральные числа.',note:'В задаче № 839 скорость тоже удобно перевести в метры в минуту.'},
{id:'l113-ready',eyebrow:'Перед практикой',title:'Закрепляем основу § 31',body:'Сначала выполни точные задания 824, 826 и 839. Затем закрепи равные записи с нулями справа, поразрядное сравнение, упорядочивание и сравнение величин.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredThirteenPractice.map((practice,i)=>({id:`l113-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Сравнение десятичных дробей · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l113-summary',eyebrow:'Итог урока 113',title:'Основа сравнения десятичных дробей освоена',body:'Ты понимаешь равенство записей с конечными нулями, умеешь уравнивать дробные разряды, сравнивать числа слева направо и упорядочивать набор десятичных дробей.',note:'Урок 114 продолжит § 31: закрепление сравнения и координатный луч.',summary:true}];
export const lessonOneHundredThirteenStageCount=stages.length;
export const lessonOneHundredThirteenPracticeTaskCount=lessonOneHundredThirteenPractice.length;
export const lessonOneHundredThirteenPracticeResponseCount=lessonOneHundredThirteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalComparisonFoundationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==113||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 113: сравнение десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Сравни целые части, затем уравняй количество знаков после запятой и найди первый различающийся разряд.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 113 завершён</b><span>20 задач · 50 ответов · § 31 · 1 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 113"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
