import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentyEightPractice,lessonOneHundredTwentyEightResponseCount,type LessonOneHundredTwentyEightField,type LessonOneHundredTwentyEightTask} from './data/lessonOneHundredTwentyEightPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:LessonOneHundredTwentyEightTask;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-128-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const matchField=(value:string,field:LessonOneHundredTwentyEightField)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l128-idea',eyebrow:'Урок 128 · § 34 · 3 из 7',title:'Теперь важен не только ответ, но и самый удобный путь',body:'При умножении десятичных дробей можно переставлять множители и менять их группировку. Это те же переместительное и сочетательное свойства, что и для натуральных чисел.',note:'0,2 × 32,8 × 5 = (0,2 × 5) × 32,8 = 32,8.'},
{id:'l128-pairs',eyebrow:'Удобные пары',title:'Ищи множители, которые дают 1, 10 или 0,1',body:'Пары 0,2 и 5; 0,25 и 4; 0,8 и 12,5; 1,25 и 8 резко упрощают вычисления.',note:'0,8 × 47,5 × 12,5 = (0,8 × 12,5) × 47,5 = 10 × 47,5.'},
{id:'l128-associative',eyebrow:'Сочетательное свойство',title:'Группировка не меняет произведение',body:'Можно сначала перемножить ту пару, которая удобнее, даже если она не стоит рядом.',note:'a × b × c = (a × c) × b, если так считать проще.'},
{id:'l128-distributive',eyebrow:'Распределительное свойство',title:'Общий множитель можно вынести за скобки',body:'Если два произведения имеют одинаковый множитель, не нужно считать каждое отдельно.',note:'3,18×7,8 + 3,18×2,2 = 3,18×(7,8+2,2) = 31,8.'},
{id:'l128-units',eyebrow:'Величины',title:'В длинных задачах держи единицы под контролем',body:'При последовательных переводах длины или массы сначала вычисляй значение в текущих единицах и только потом переводи.',note:'В №934 сантиметры превращаются в метры, затем метры — в километры.'},
{id:'l128-motion',eyebrow:'Движение в одном направлении',title:'Расстояние растёт по разности скоростей',body:'Если два объекта стартуют вместе и движутся в одном направлении, скорость удаления равна разности их скоростей.',note:'(11,4−9,8)×6,5 = 10,4 км.'},
{id:'l128-route',eyebrow:'Маршрут урока',title:'Свойства → точные задания → закрепление',body:'Сначала разбираем №926, 928 (1–3), 930 (1–2), 934 и 936, затем закрепляем свойства на новых выражениях и прикладных задачах.',note:'20 задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentyEightPractice.map((practice,i)=>({id:`l128-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.sourceExact?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.title,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l128-summary',eyebrow:'Итог урока 128',title:'Третий урок § 34 завершён',body:'Ты умеешь использовать переместительное, сочетательное и распределительное свойства умножения десятичных дробей, выбирать удобные пары множителей и применять умножение в задачах.',note:'Домашнее задание: § 34, № 927, 931 (1–2), 935. Урок 129 продолжит § 34.',summary:true}];
export const lessonOneHundredTwentyEightStageCount=stages.length;
export const lessonOneHundredTwentyEightPracticeTaskCount=lessonOneHundredTwentyEightPractice.length;
export const lessonOneHundredTwentyEightPracticeResponseCount=lessonOneHundredTwentyEightResponseCount;
function load():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(raw) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalMultiplicationPropertiesPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(field=>matchField(responses[`${key}:${field.id}`]??'',field)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const handler=(event:Event)=>{const d=(event as CustomEvent<Jump>).detail;if(d?.lessonNumber!==128||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(delta:number)=>setStageIndex(i=>Math.max(0,Math.min(i+delta,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 128: свойства умножения десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.prompt}</h3><div className="answer-grid">{task.fields.map(field=>{const responseKey=`${key}:${field.id}`;return <label className="inline-answer" key={field.id}><span>{field.label}</span><input value={responses[responseKey]??''} placeholder={field.placeholder??'Введите ответ'} onChange={event=>{setResponses(p=>({...p,[responseKey]:event.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь, нельзя ли переставить или сгруппировать множители удобнее.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 128 завершён</b><span>20 задач · 50 ответов · § 34 · 3 из 7</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 128"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
