import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTwentySixPractice,lessonOneHundredTwentySixResponseCount,type LessonOneHundredTwentySixField,type LessonOneHundredTwentySixTask} from './data/lessonOneHundredTwentySixPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:LessonOneHundredTwentySixTask;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-126-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const matchField=(value:string,field:LessonOneHundredTwentySixField)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l126-idea',eyebrow:'Урок 126 · § 34 · 1 из 7',title:'Умножение десятичных дробей начинается как обычное умножение',body:'Временно не обращаем внимания на запятые и перемножаем цифры как натуральные числа. Затем возвращаем масштабы множителей.',note:'3,4 × 1,23: считаем 34 × 123 = 4182, затем отделяем три знака → 4,182.'},
{id:'l126-digits',eyebrow:'Главное правило',title:'Количество десятичных знаков складывается',body:'В произведении справа отделяют столько цифр, сколько знаков после запятой было в обоих множителях вместе.',note:'У 2,4 один знак, у 3,6 один знак: в 8,64 должно быть два.'},
{id:'l126-leading-zero',eyebrow:'Когда цифр не хватает',title:'Слева дописываем нули',body:'Если натуральное произведение короче нужного числа десятичных знаков, перед ним добавляют нули и только потом ставят запятую.',note:'0,09 × 0,07: 9 × 7 = 63, нужно четыре знака → 0,0063.'},
{id:'l126-times10',eyebrow:'Разрядные единицы',title:'×10, ×100, ×1000 двигают запятую вправо',body:'Каждый множитель 10 увеличивает число в десять раз. Поэтому запятая переносится вправо на столько позиций, сколько нулей у разрядной единицы.',note:'6,58 × 100 = 658.'},
{id:'l126-small',eyebrow:'Множители меньше единицы',title:'×0,1, ×0,01, ×0,001 двигают запятую влево',body:'Умножение на 0,1 равносильно делению на 10; на 0,01 — делению на 100; на 0,001 — делению на 1000.',note:'6,58 × 0,001 = 0,00658.'},
{id:'l126-estimate',eyebrow:'Самопроверка',title:'Оцени порядок величины до вычисления',body:'Если один множитель меньше 1, произведение положительных чисел должно быть меньше второго множителя. Такая оценка быстро обнаруживает ошибочную запятую.',note:'3,46 × 0,14 точно меньше 3,46; ответ 48,44 невозможен.'},
{id:'l126-route',eyebrow:'Маршрут урока',title:'Точные задания → закрепление → итог',body:'Сначала выполняем задания методической карты №909, 910, 913, 914 (1–8), 916. Затем закрепляем правило на коротких задачах.',note:'20 задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTwentySixPractice.map((practice,i)=>({id:`l126-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.sourceExact?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.title,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l126-summary',eyebrow:'Итог урока 126',title:'Первый урок § 34 завершён',body:'Ты умеешь определять количество десятичных знаков в произведении, умножать две десятичные дроби, работать с 10, 100, 1000 и с 0,1, 0,01, 0,001.',note:'Домашнее задание: § 34, вопросы 1–3, № 912, 915 (1–6), 917. Урок 127 продолжит § 34.',summary:true}];
export const lessonOneHundredTwentySixStageCount=stages.length;
export const lessonOneHundredTwentySixPracticeTaskCount=lessonOneHundredTwentySixPractice.length;
export const lessonOneHundredTwentySixPracticeResponseCount=lessonOneHundredTwentySixResponseCount;
function load():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(raw) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalMultiplicationFoundationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(field=>matchField(responses[`${key}:${field.id}`]??'',field)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const handler=(event:Event)=>{const d=(event as CustomEvent<Jump>).detail;if(d?.lessonNumber!==126||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(delta:number)=>setStageIndex(i=>Math.max(0,Math.min(i+delta,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 126: умножение десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.prompt}</h3><div className="answer-grid">{task.fields.map(field=>{const responseKey=`${key}:${field.id}`;return <label className="inline-answer" key={field.id}><span>{field.label}</span><input value={responses[responseKey]??''} placeholder={field.placeholder??'Введите ответ'} onChange={event=>{setResponses(p=>({...p,[responseKey]:event.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь количество десятичных знаков и порядок величины произведения.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 126 завершён</b><span>20 задач · 50 ответов · § 34 · 1 из 7</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 126"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
