import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredTenPractice,lessonOneHundredTenResponseCount,type Lesson110Practice} from './data/lessonOneHundredTenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson110Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-110-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l110-scale',eyebrow:'Урок 110 · § 30 · 2 из 4',title:'Знаменатель задаёт длину дробной части',body:'Десять даёт один знак после запятой, сто — два, тысяча — три, десять тысяч — четыре, сто тысяч — пять. Сначала считай нули в знаменателе, потом размещай числитель.',note:'Этот приём защищает от большинства ошибок с нулями.'},
{id:'l110-leading-zero',eyebrow:'Ведущие нули',title:'Числитель занимает последние позиции',body:'Если цифр числителя меньше, чем требуется позиций после запятой, свободные места слева заполняются нулями. Поэтому три тысячных — это 0,003, а тринадцать стотысячных — 0,00013.',note:'Нули здесь не декоративные: они показывают разряд.'},
{id:'l110-mixed',eyebrow:'Смешанные числа',title:'Целая часть остаётся слева от запятой',body:'У смешанного числа сначала записывается целая часть. Затем дробная часть размещается по разрядам знаменателя. Например, две целых три тысячных дают 2,003.',note:'Не переносим цифры дробной части ближе к запятой.'},
{id:'l110-improper',eyebrow:'Неправильные дроби',title:'Сначала выдели целые единицы',body:'Если числитель больше знаменателя, раздели его на знаменатель. Частное станет целой частью, остаток — дробной частью с тем же десятичным знаменателем.',note:'Так 9266/100 превращается в 92,66.'},
{id:'l110-back',eyebrow:'Обратная запись',title:'Число знаков после запятой восстанавливает знаменатель',body:'Для 5,06 дробная часть имеет две позиции, значит исходная разрядная дробь — 6/100. Для 12,018 три позиции дают 18/1000.',note:'После разрядной записи дробь можно сократить.'},
{id:'l110-read',eyebrow:'Чтение по разрядам',title:'Ноль внутри записи тоже надо учитывать',body:'В числе 15,304 три стоит в десятых, ноль — в сотых, четыре — в тысячных. Чтение по разрядам помогает проверить, не потеряна ли позиция.',note:'Разряд определяет место цифры, а не её величина.'},
{id:'l110-compose',eyebrow:'Составление числа',title:'Неназванный разряд заполняется нулём',body:'Если сказано шесть единиц, четыре сотых и девять десятитысячных, в разрядах десятых и тысячных должны стоять нули. Получается 6,0409.',note:'Сначала мысленно нарисуй сетку разрядов.'},
{id:'l110-ready',eyebrow:'Перед практикой',title:'Закрепи четыре типа переходов',body:'Сначала выполни точные задания семьсот девяносто девять, восемьсот один, восемьсот три и восемьсот пять. Затем потренируй длинные дробные части, чтение разрядов и обратную запись.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredTenPractice.map((practice,i)=>({id:`l110-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Закрепление десятичной записи · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l110-summary',eyebrow:'Итог урока 110',title:'Запись и чтение десятичных дробей закреплены',body:'Ты уверенно работаешь с десятыми, сотыми, тысячными, десятитысячными и стотысячными, сохраняешь ведущие нули, выделяешь целую часть неправильной дроби и выполняешь обратное преобразование.',note:'Урок 111 продолжит § 30: переход между единицами измерения и десятичной записью.',summary:true}];
export const lessonOneHundredTenStageCount=stages.length;
export const lessonOneHundredTenPracticeTaskCount=lessonOneHundredTenPractice.length;
export const lessonOneHundredTenPracticeResponseCount=lessonOneHundredTenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalRepresentationPracticePlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==110||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 110: закрепление представления о десятичных дробях"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Сначала посчитай нули в знаменателе или позиции после запятой, затем проверь ведущие нули и целую часть.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 110 завершён</b><span>20 задач · 50 ответов · § 30 закрепление</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 110"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
