import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredNineteenPractice,lessonOneHundredNineteenResponseCount,type Lesson119Field,type Lesson119Practice} from './data/lessonOneHundredNineteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson119Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-119-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—-]/g,'');
const matchField=(value:string,field:Lesson119Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l119-place-value',eyebrow:'Урок 119 · § 33 · 1 из 6',title:'Складываем одинаковые разряды',body:'Десятичная запись устроена по разрядам. Единицы складываются с единицами, десятые с десятыми, сотые с сотыми. Поэтому сначала нужно совместить одинаковые разряды двух чисел.',note:'В сумме 6,9 и 3,45 число 6,9 удобно записать как 6,90.'},
{id:'l119-equalize',eyebrow:'Подготовка записи',title:'Нули справа помогают выровнять дробную часть',body:'Нули, дописанные справа после последней значащей цифры дробной части, не меняют значение числа. Они только делают разрядную запись наглядной и уменьшают риск ошибки.',note:'4,8 и 4,80 — одно и то же число.'},
{id:'l119-comma-column',eyebrow:'Запись столбиком',title:'Главный ориентир — запятая под запятой',body:'Когда запятые находятся строго одна под другой, одинаковые разряды автоматически становятся в один столбец. Выравнивать числа по последней цифре нельзя: это может смешать десятые, сотые и тысячные.',note:'Сначала совмести запятые, затем при необходимости допиши нули справа.'},
{id:'l119-add-natural',eyebrow:'Само сложение',title:'После выравнивания действуем как с натуральными числами',body:'Складывай цифры справа налево по разрядам. Если в разряде получается десять или больше, запиши последнюю цифру и перенеси единицу в следующий разряд слева.',note:'Правила переноса полностью совпадают со сложением натуральных чисел.'},
{id:'l119-carry',eyebrow:'Перенос через запятую',title:'Перенос из десятых может изменить целую часть',body:'Перенос не останавливается у запятой. Если сумма десятых даёт полный десяток десятых, возникает дополнительная единица целой части. Цепочка переносов может пройти через несколько девяток.',note:'0,999 плюс 0,001 даёт ровно 1.'},
{id:'l119-trailing-zero',eyebrow:'Форма ответа',title:'Лишние нули справа можно убрать',body:'Числа 94,500 и 94,5 равны. После вычисления можно убрать нули в конце дробной части, если условие не требует сохранять определённое число знаков после запятой.',note:'Нуль справа меняет запись, но не значение десятичной дроби.'},
{id:'l119-word-problems',eyebrow:'Текстовые задачи',title:'Сначала определи, почему здесь нужно сложение',body:'Фразы «на столько больше» и «вместе» часто задают два последовательных сложения. В № 871 сначала находим площадь второй комнаты, затем складываем площади обеих комнат.',note:'Промежуточный ответ помогает не потерять смысл задачи.'},
{id:'l119-ready',eyebrow:'Перед практикой',title:'Правило → № 865 → № 871 → закрепление',body:'Сначала восстанови правило сложения десятичных дробей, затем реши шесть точных примеров № 865 и задачу № 871. После этого закрепи выравнивание разрядов, переносы, нули справа и сложение величин.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredNineteenPractice.map((practice,i)=>({id:`l119-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Сложение десятичных дробей · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l119-summary',eyebrow:'Итог урока 119',title:'Сложение десятичных дробей освоено',body:'Ты умеешь выравнивать разряды, дописывать нули справа, записывать запятую под запятой, складывать поразрядно с переносом и применять сложение десятичных дробей в текстовых задачах.',note:'Урок 120 продолжит § 33 и введёт правило вычитания десятичных дробей.',summary:true}];
export const lessonOneHundredNineteenStageCount=stages.length;
export const lessonOneHundredNineteenPracticeTaskCount=lessonOneHundredNineteenPractice.length;
export const lessonOneHundredNineteenPracticeResponseCount=lessonOneHundredNineteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalAdditionFoundationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==119||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 119: сложение десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Совмести одинаковые разряды: запятая должна стоять под запятой.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 119 завершён</b><span>20 задач · 50 ответов · § 33 · 1 из 6</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 119"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
