import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredFourteenPractice,lessonOneHundredFourteenResponseCount,type Lesson114Practice} from './data/lessonOneHundredFourteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson114Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-114-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l114-double-inequality',eyebrow:'Урок 114 · § 31 · 2 из 3',title:'Двойное неравенство задаёт две границы',body:'Запись «число больше левой границы и меньше правой» означает, что нужно выполнить оба условия одновременно. Для натуральных решений проверяй только целые положительные числа внутри интервала.',note:'Если знак строгий, сами границы в ответ не входят.'},
{id:'l114-natural-solutions',eyebrow:'Натуральные решения',title:'Перечисляй числа системно',body:'Сначала найди первое натуральное число, которое строго больше левой границы, затем двигайся по единице до последнего числа, которое ещё меньше правой границы.',note:'Так легче не пропустить крайнее значение.'},
{id:'l114-neighbours',eyebrow:'Соседние натуральные',title:'Целая часть показывает левую границу',body:'Если десятичная дробь не является натуральным числом, она лежит между своей целой частью и следующим натуральным числом. Например, число 5,32 находится между 5 и 6.',note:'Для 24,01 соседние натуральные числа — 24 и 25.'},
{id:'l114-coordinate-view',eyebrow:'Координатный смысл',title:'Интервал можно увидеть на луче',body:'На координатном луче десятичная дробь расположена правее меньшей натуральной границы и левее большей. Это связывает сравнение дробей с их положением на числовой прямой.',note:'Чем правее точка, тем больше число.'},
{id:'l114-star-digit',eyebrow:'Неизвестная цифра',title:'Звёздочка — это одна цифра от нуля до девяти',body:'Подбирая цифру, сравнивай числа по разрядам слева направо. Как только найден первый различающийся разряд, последующие цифры уже не меняют знак сравнения.',note:'Сначала определи критический разряд, потом перечисли все подходящие цифры.'},
{id:'l114-boundary-digit',eyebrow:'Граничная цифра',title:'Ищи минимальную или максимальную допустимую цифру',body:'Если условие требует строгого сравнения, равенство не подходит. Поэтому после нахождения пограничной цифры обязательно проверь, действительно ли получается строго больше или строго меньше.',note:'Особенно внимательно проверяй случаи, когда предыдущие разряды равны.'},
{id:'l114-check',eyebrow:'Самопроверка',title:'Подставь крайние ответы обратно',body:'Для интервала проверь первое и последнее найденные натуральные числа. Для звёздочки проверь минимальную и максимальную допустимые цифры — это быстро выявляет ошибку в границе.',note:'Проверка крайних значений надёжнее случайной подстановки.'},
{id:'l114-ready',eyebrow:'Перед практикой',title:'Закрепляем § 31 на интервалах и цифрах',body:'Сначала реши точные задания 828, 830 и 832, затем закрепи натуральные решения двойных неравенств, соседние натуральные границы и подбор неизвестной цифры.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredFourteenPractice.map((practice,i)=>({id:`l114-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Интервалы и сравнение · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l114-summary',eyebrow:'Итог урока 114',title:'Интервалы и неизвестная цифра освоены',body:'Ты умеешь находить натуральные решения двойных неравенств, определять соседние натуральные числа для десятичной дроби и подбирать цифры так, чтобы сравнение было верным.',note:'Урок 115 завершит § 31: числа между десятичными дробями и более сложные ограничения.',summary:true}];
export const lessonOneHundredFourteenStageCount=stages.length;
export const lessonOneHundredFourteenPracticeTaskCount=lessonOneHundredFourteenPractice.length;
export const lessonOneHundredFourteenPracticeResponseCount=lessonOneHundredFourteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function DecimalComparisonIntervalsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==114||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 114: интервалы и сравнение десятичных дробей"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь обе границы, а при звёздочке сравни разряды слева направо.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 114 завершён</b><span>20 задач · 50 ответов · § 31 · 2 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 114"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
