import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './dissectionReview.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type Diagram=
  |{type:'panel';kind:'invariants'|'straight-cut'|'fruit'|'equations'|'final'}
  |{type:'dissection';variant:'source-375'|'figure-221'|'figure-222'|'figure-223'}
  |{type:'mirror'}
  |{type:'park'}
  |{type:'dot-grid'}
  |{type:'diagonal-square'}
  |{type:'intersection'}
  |{type:'transport'}
  |{type:'jugs'};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-51-progress-v1';
const normalized=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[−–—]/g,'-').replace(/[×·]/g,'X').replace(/\s+/g,'').replace(/(?:СМ|М|КГ|МИН|Л|[.])$/,'');
const answerMatches=(response:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalized(response)===normalized(item))};

export const lessonFiftyOneStages:Stage[]=[
  {id:'l51-mission',kind:'story',eyebrow:'Урок 51 · § 15 · итог темы',title:'Разрезать — значит сначала доказать',body:'Маршрут завершает § 15 заданиями № 375–383. Мы воспроизведём точные разрезы, соберём новые фигуры, выполним зеркальное достроение и применим материал главы в задачах на построение, периметр, уравнения и переливания.',note:'Рабочая тетрадь дополняет маршрут заданиями № 161–163 и 165–166. Рисунки 221–223 восстановлены по ответам учебника.',diagram:{type:'panel',kind:'invariants'}},
  {id:'l51-cut-invariants',kind:'model',eyebrow:'Проверка до разреза',title:'Три условия точного разрезания',body:'Части должны покрывать исходную фигуру без щелей и наложений, быть равными там, где это требует условие, и после перемещения точно замыкать границу новой фигуры.',diagram:{type:'panel',kind:'invariants'}},
  {id:'l51-source375-model',kind:'guided',eyebrow:'Учебник № 375',title:'Соедини середины трёх сторон треугольника',body:'Три средние линии делят равнобедренный прямоугольный треугольник на четыре меньших треугольника с одинаковыми тремя сторонами.',diagram:{type:'dissection',variant:'source-375'}},
  {id:'l51-source375-pieces',kind:'practice',eyebrow:'№ 375 · равенство частей',title:'Три угловые части и одна центральная',body:'Каждая сторона малого треугольника равна половине одной из сторон исходного треугольника.',activity:{id:'l51-p1',type:'input',prompt:'Сколько равных частей получилось?',answer:'4',placeholder:'число частей',hint:'Посчитай все области между тремя средними линиями.',explanation:'Получились четыре равных прямоугольных равнобедренных треугольника.'},diagram:{type:'dissection',variant:'source-375'}},
  {id:'l51-source375-assembly',kind:'practice',eyebrow:'№ 375 · сборка квадрата',title:'Четыре прямых угла встречаются в центре',body:'Гипотенузы четырёх равных частей образуют четыре равные стороны внешней границы.',activity:{id:'l51-p2',type:'choice',prompt:'Как расположить четыре части?',options:['Совместить четыре прямых угла в одной точке','Выложить части в одну полосу','Наложить все части друг на друга','Соединить только две части'],answer:'Совместить четыре прямых угла в одной точке',hint:'Вокруг внутренней точки нужен полный угол 360°.',explanation:'4·90°=360°, поэтому прямые углы сходятся без щели, а гипотенузы дают квадрат.'},diagram:{type:'dissection',variant:'source-375'}},
  {id:'l51-source376-model',kind:'model',eyebrow:'Учебник № 376 · рисунок 221',title:'Прямоугольник 8 см × 4 см превращается в четыре равных треугольника',body:'Средняя вертикаль делит верхнюю сторону пополам. Два наклонных разреза идут от верхних вершин к середине нижней стороны.',diagram:{type:'dissection',variant:'figure-221'}},
  {id:'l51-source376-halves',kind:'practice',eyebrow:'Рисунок 221 · размеры',title:'Восемь сантиметров делятся на две равные части',body:'Средняя линия проходит ровно через середины верхней и нижней сторон.',activity:{id:'l51-p3',type:'input',prompt:'Запиши длины двух половин верхней стороны через «и», см.',answer:['4 и 4','4,4'],placeholder:'например: 4 и 4',hint:'Раздели 8 см пополам.',explanation:'8:2=4 см, поэтому верхняя сторона состоит из отрезков 4 см и 4 см.'},diagram:{type:'dissection',variant:'figure-221'}},
  {id:'l51-source376-pieces',kind:'practice',eyebrow:'Рисунок 221 · контроль частей',title:'Каждый треугольник имеет катеты по 4 см',body:'В каждой половине прямоугольника диагональ делит квадрат 4×4 на два равных треугольника.',activity:{id:'l51-p4',type:'input',prompt:'Сколько равных треугольников получилось?',answer:'4',placeholder:'число',hint:'В двух квадратах по два треугольника.',explanation:'Два квадрата 4×4 дают по две равные части — всего четыре.'},diagram:{type:'dissection',variant:'figure-221'}},
  {id:'l51-source376-assembly',kind:'quiz',eyebrow:'№ 376 · сборка',title:'Гипотенузы становятся сторонами квадрата',body:'Четыре прямых угла треугольных частей снова совмещают в одной точке.',activity:{id:'l51-p5',type:'choice',prompt:'Что образует внешнюю границу нового квадрата?',options:['Четыре равные гипотенузы','Четыре стороны исходного прямоугольника без перестановки','Две средние линии','Только два наклонных разреза'],answer:'Четыре равные гипотенузы',hint:'Катеты сходятся внутри новой фигуры.',explanation:'Все четыре треугольника равны, поэтому их гипотенузы образуют четыре равные стороны квадрата.'},diagram:{type:'dissection',variant:'figure-221'}},
  {id:'l51-source377-model',kind:'model',eyebrow:'Учебник № 377 · рисунок 222',title:'Один разрез: от вершины к середине противоположной стороны',body:'Линия идёт из нижней левой вершины квадрата к середине верхней стороны. Равные штрихи подтверждают точное деление верхней стороны пополам.',diagram:{type:'dissection',variant:'figure-222'}},
  {id:'l51-source377-midpoint',kind:'practice',eyebrow:'Рисунок 222 · читаем отметки',title:'Точка разреза делит верхнюю сторону на равные отрезки',body:'Это условие важно: только тогда после переноса наклонные границы продолжают одна другую.',activity:{id:'l51-p6',type:'choice',prompt:'Куда приходит линия разреза?',options:['В середину верхней стороны','В верхнюю правую вершину','В центр квадрата','В середину правой стороны'],answer:'В середину верхней стороны',hint:'Сравни две одинаковые отметки сверху.',explanation:'Штрихи показывают две равные половины верхней стороны.'},diagram:{type:'dissection',variant:'figure-222'}},
  {id:'l51-source377-pieces',kind:'practice',eyebrow:'№ 377 · две части',title:'Малую часть переносят к короткому верхнему отрезку',body:'После переноса две наклонные стороны становятся одной прямой, а внешняя граница — треугольником.',activity:{id:'l51-p7',type:'choice',prompt:'Какие фигуры получаются сразу после разреза?',options:['Треугольник и четырёхугольник','Два квадрата','Два треугольника','Пятиугольник и шестиугольник'],answer:'Треугольник и четырёхугольник',hint:'Посчитай стороны слева и справа от линии.',explanation:'Левая часть имеет три стороны, оставшаяся — четыре.'},diagram:{type:'dissection',variant:'figure-222'}},
  {id:'l51-source378-model',kind:'model',eyebrow:'Учебник № 378 · рисунок 223',title:'Ломаная из трёх звеньев делит квадрат на две одинаковые ступени',body:'В квадрате со стороной 6 см разрез идёт на 3 см вправо, на 2 см вниз и ещё на 3 см вправо. Слева сверху и справа снизу остаётся по 2 см.',diagram:{type:'dissection',variant:'figure-223'}},
  {id:'l51-source378-segments',kind:'practice',eyebrow:'Рисунок 223 · длины звеньев',title:'Середина стороны даёт горизонтальные отрезки по 3 см',body:'Вертикальное звено соединяет уровни 2 см и 4 см.',activity:{id:'l51-p8',type:'input',prompt:'Запиши длины трёх звеньев через запятую, см.',answer:['3,2,3','3;2;3'],placeholder:'например: 3, 2, 3',hint:'Половина 6 см равна 3 см, разность уровней 4−2 равна 2 см.',explanation:'Ломаная состоит из звеньев 3 см, 2 см и 3 см.'},diagram:{type:'dissection',variant:'figure-223'}},
  {id:'l51-source378-rectangle',kind:'practice',eyebrow:'№ 378 · перестроение',title:'Поверни одну ступенчатую часть на 180°',body:'Выступ одной части заполняет выемку другой, и получается прямоугольник без щелей.',activity:{id:'l51-p9',type:'choice',prompt:'Каковы размеры полученного прямоугольника?',options:['9 см × 4 см','6 см × 6 см','12 см × 3 см','8 см × 5 см'],answer:'9 см × 4 см',hint:'По длинной стороне складываются 3 см и 6 см, по короткой — 2 см и 2 см.',explanation:'Части образуют прямоугольник 9×4 см.'},diagram:{type:'dissection',variant:'figure-223'}},
  {id:'l51-workbook163-model',kind:'model',eyebrow:'Рабочая тетрадь № 163',title:'Один прямолинейный разрез добавляет каждой части не более одной новой стороны',body:'Если концы разреза лежат на соседних сторонах прямоугольника, одна часть — треугольник, другая — пятиугольник. Шестиугольнику не хватает ещё одной границы.',diagram:{type:'panel',kind:'straight-cut'}},
  {id:'l51-workbook163-impossible',kind:'quiz',eyebrow:'РТ № 163 · невозможная фигура',title:'Проверь максимальное число сторон',body:'Квадрат получают прямым разрезом параллельно стороне, прямоугольный треугольник — срезанием угла, пятиугольник — разрезом между соседними сторонами.',activity:{id:'l51-p10',type:'choice',prompt:'Какую фигуру нельзя получить одной из двух частей?',options:['Шестиугольник','Квадрат','Пятиугольник','Прямоугольный треугольник'],answer:'Шестиугольник',hint:'У части может быть не более пяти сторон.',explanation:'Один прямой разрез прямоугольника не создаёт часть с шестью сторонами.'},diagram:{type:'panel',kind:'straight-cut'}},
  {id:'l51-workbook161-model',kind:'model',eyebrow:'Рабочая тетрадь № 161',title:'Каждая клетка отражается на такое же расстояние от оси a',body:'В задании восемь половин фигур. Для каждой вершины проводим мысленный перпендикуляр к оси и откладываем то же число клеток с другой стороны.',diagram:{type:'mirror'}},
  {id:'l51-workbook161-rule',kind:'practice',eyebrow:'РТ № 161 · правило',title:'Ось проходит ровно посередине между зеркальными точками',body:'Точка на самой оси при отражении остаётся на месте.',activity:{id:'l51-p11',type:'choice',prompt:'Как построить зеркальную вершину?',options:['Отложить по перпендикуляру к оси такое же расстояние','Сдвинуть вершину на одну клетку вправо','Повернуть весь лист на 90°','Соединить вершину с любым концом оси'],answer:'Отложить по перпендикуляру к оси такое же расстояние',hint:'Ось должна делить соединяющий отрезок пополам.',explanation:'Зеркальные точки равноудалены от оси и лежат на одном перпендикуляре к ней.'},diagram:{type:'mirror'}},
  {id:'l51-workbook161-count',kind:'practice',eyebrow:'РТ № 161 · полнота',title:'Проверка охватывает все исходные рисунки',body:'На странице даны фигуры 1–8 с вертикальными и горизонтальными осями.',activity:{id:'l51-p12',type:'input',prompt:'Сколько фигур надо достроить?',answer:'8',placeholder:'число фигур',hint:'Посмотри номера заданий внутри рисунка.',explanation:'В упражнении восемь отдельных фигур.'},diagram:{type:'mirror'}},
  {id:'l51-workbook162-model',kind:'model',eyebrow:'Рабочая тетрадь № 162',title:'Квадратный парк составлен из сада, озера, кафе и площадки',body:'Озеро — квадрат с периметром 120 м, сад — квадрат с периметром 200 м. Их стороны задают ширину и высоту соседней игровой площадки.',diagram:{type:'park'}},
  {id:'l51-workbook162-lake',kind:'practice',eyebrow:'РТ № 162 · озеро',title:'Четыре равные стороны дают 120 м',body:'Для квадрата длина стороны равна четверти периметра.',activity:{id:'l51-p13',type:'input',prompt:'Найди сторону озера, м.',answer:'30',placeholder:'м',hint:'120:4.',explanation:'Сторона квадратного озера равна 30 м.'},diagram:{type:'park'}},
  {id:'l51-workbook162-garden',kind:'practice',eyebrow:'РТ № 162 · сад',title:'Периметр сада равен 200 м',body:'Сад тоже имеет форму квадрата.',activity:{id:'l51-p14',type:'input',prompt:'Найди сторону сада, м.',answer:'50',placeholder:'м',hint:'200:4.',explanation:'Сторона квадратного сада равна 50 м.'},diagram:{type:'park'}},
  {id:'l51-workbook162-playground',kind:'practice',eyebrow:'РТ № 162 · площадка',title:'Площадка имеет размеры 30 м × 50 м',body:'Её ширина совпадает со стороной озера, а высота — со стороной сада.',activity:{id:'l51-p15',type:'input',prompt:'Найди периметр игровой площадки, м.',answer:'160',placeholder:'м',hint:'Вычисли 2·(30+50).',explanation:'P=2·80=160 м.'},diagram:{type:'park'}},
  {id:'l51-workbook165-model',kind:'model',eyebrow:'Рабочая тетрадь № 165',title:'Четыре равные части — по одному кружку в каждой',body:'Цвет показывает один точный способ деления: в первой сетке получаются четыре квадрата 2×2, во второй — четыре полосы 1×4, в третьей — четыре равные Т-образные части по четыре клетки. Каждая часть содержит ровно один кружок.',diagram:{type:'dot-grid'}},
  {id:'l51-workbook165-parts',kind:'practice',eyebrow:'РТ № 165 · условие',title:'Число частей совпадает с числом кружков',body:'Каждый кружок должен попасть ровно в одну часть.',activity:{id:'l51-p16',type:'input',prompt:'На сколько равных частей делят каждый квадрат?',answer:'4',placeholder:'число частей',hint:'В каждой схеме четыре кружка.',explanation:'Каждую сетку делят на четыре равные части.'},diagram:{type:'dot-grid'}},
  {id:'l51-workbook166-model',kind:'model',eyebrow:'Рабочая тетрадь № 166',title:'Диагонали квадрата равны, пересекаются в середине и перпендикулярны',body:'На клетчатой сетке A=(2;2), C=(6;4). Середина AC — (4;3); поворот половины вектора диагонали на 90° даёт вершины (3;5) и (5;1).',diagram:{type:'diagonal-square'}},
  {id:'l51-workbook166-vertices',kind:'practice',eyebrow:'РТ № 166 · построение линейкой',title:'Осталось соединить четыре найденные точки',body:'Координаты введены только для точной проверки клетчатого рисунка источника.',activity:{id:'l51-p17',type:'choice',prompt:'Какие узлы сетки являются двумя недостающими вершинами?',options:['B(3;5) и D(5;1)','B(2;5) и D(6;1)','B(4;5) и D(4;1)','B(1;3) и D(7;3)'],answer:'B(3;5) и D(5;1)',hint:'От середины (4;3) отложи векторы (−1;+2) и (+1;−2).',explanation:'Точки (3;5) и (5;1) дают равные перпендикулярные диагонали с общей серединой.'},diagram:{type:'diagonal-square'}},
  {id:'l51-source379-model',kind:'model',eyebrow:'Учебник № 379 · повторение',title:'Один луч пересекает две фигуры, а прямая и отрезок не встречаются',body:'На точном чертеже луч PS сначала пересекает отрезок AB, затем прямую MK. Отрезок заканчивается выше прямой MK.',diagram:{type:'intersection'}},
  {id:'l51-source379-condition',kind:'practice',eyebrow:'№ 379 · три условия',title:'Проверь все пары, а не только одну',body:'Порядок точек на луче может быть другим, но каждая требуемая пара должна вести себя по условию.',activity:{id:'l51-p18',type:'choice',prompt:'Какое описание полностью верно?',options:['PS пересекает AB и MK; MK не пересекает AB','Все три фигуры проходят через одну точку','MK пересекает AB; PS не пересекает MK','AB лежит на MK'],answer:'PS пересекает AB и MK; MK не пересекает AB',hint:'Сверь каждую из трёх пар.',explanation:'Это точная запись всех условий № 379.'},diagram:{type:'intersection'}},
  {id:'l51-source380-remain',kind:'practice',eyebrow:'Учебник № 380 · общий остаток',title:'После продажи каждого вида осталось поровну',body:'Продали всего 55+36+34=125 кг. Из 740 кг осталось 615 кг, разделённых поровну между тремя видами.',activity:{id:'l51-p19',type:'input',prompt:'Сколько килограммов каждого вида осталось?',answer:'205',placeholder:'кг',hint:'(740−125):3.',explanation:'615:3=205 кг каждого вида.'},diagram:{type:'panel',kind:'fruit'}},
  {id:'l51-source380-masses',kind:'practice',eyebrow:'№ 380 · возвращаем проданное',title:'Восстанови первоначальные массы',body:'К общему остатку прибавляем массу, проданную именно для этого вида фруктов.',activity:{id:'l51-p20',type:'input',prompt:'Запиши массы лимонов, апельсинов и мандаринов по порядку, кг.',answer:['260,241,239','260;241;239'],placeholder:'например: 260, 241, 239',hint:'205+55; 205+36; 205+34.',explanation:'Лимонов было 260 кг, апельсинов 241 кг, мандаринов 239 кг.'},diagram:{type:'panel',kind:'fruit'}},
  {id:'l51-source381-fastest',kind:'practice',eyebrow:'Учебник № 381 · таблица времени',title:'Складывай все три участка каждого маршрута',body:'Автобус: 10+75+5=90 мин. Электропоезд: 8+56+10=74 мин. Маршрутное такси: 7+65+8=80 мин.',activity:{id:'l51-p21',type:'choice',prompt:'Какой путь самый быстрый?',options:['Электропоезд — 74 мин','Маршрутное такси — 65 мин','Автобус — 75 мин','Все пути занимают 90 мин'],answer:'Электропоезд — 74 мин',hint:'Не забудь время до остановки и после неё.',explanation:'Минимальная полная длительность — 74 минуты на электропоезде.'},diagram:{type:'transport'}},
  {id:'l51-source382-sums',kind:'practice',eyebrow:'Учебник № 382 · уравнения',title:'Реши четыре уравнения и сложи корни попарно',body:'В первой паре x=130 и y=109. Во второй паре x=28 и y=231.',activity:{id:'l51-p22',type:'input',prompt:'Запиши суммы корней первой и второй пар через «и».',answer:['239 и 259','259 и 239'],placeholder:'например: 239 и 259',hint:'130+109; 28+231.',explanation:'Суммы корней равны 239 и 259.'},diagram:{type:'panel',kind:'equations'}},
  {id:'l51-source383-jug',kind:'challenge',eyebrow:'Задача от мудрой совы № 383',title:'Сначала получи в трёхлитровой банке два литра',body:'Наполни бидон 5 л и перелей в банку 3 л — останется 2 л. Освободи банку, перелей в неё эти 2 л, снова наполни бидон и долей в банку 1 л.',activity:{id:'l51-p23',type:'choice',prompt:'Сколько воды останется в пятилитровом бидоне после последнего переливания?',options:['4 л','3 л','2 л','1 л'],answer:'4 л',hint:'Из полных 5 л в банку войдёт только 1 л.',explanation:'5−1=4 л — требуемый объём.'},diagram:{type:'jugs'}},
  {id:'l51-summary',kind:'summary',eyebrow:'Итог урока 51 и § 15',title:'Ты управляешь формой, а не угадываешь её',body:'Ты проверяешь равенство частей, читаешь точные линии разреза, складываешь новые фигуры, отражаешь клетки относительно оси, строишь квадрат по диагонали и переносишь геометрические идеи в задачи всей главы.',note:'Дальше — обязательная практика из 20 задач с Пифагором и озвучкой Sulafat. После неё § 15 завершён.',diagram:{type:'panel',kind:'final'}}
];

function DissectionDiagram({variant}:{variant:Extract<Diagram,{type:'dissection'}>['variant']}){
  if(variant==='source-375')return <div className="dissection-review-diagram"><svg viewBox="0 0 720 290" role="img" aria-label="Задание 375: треугольник разделён средними линиями на четыре равные части и собран в квадрат" data-source-exercise="№375" data-piece-count="4" data-equal-piece-kind="right-isosceles-triangle" data-result-shape="square"><g className="dr-source-shape"><polygon points="50,40 50,230 240,230"/><path d="M50 135H145M50 135L145 230M145 135V230"/></g><text x="145" y="268" textAnchor="middle">соединяем середины сторон</text><path className="dr-arrow" d="M285 140H390"/><g className="dr-result-shape"><polygon points="540,45 635,140 540,235 445,140"/><path d="M540 140L540 45M540 140L635 140M540 140L540 235M540 140L445 140"/><path className="dr-right-angle" d="M540 126h14v14"/></g><text x="540" y="268" textAnchor="middle">4 прямых угла в центре</text></svg></div>;
  if(variant==='figure-221')return <div className="dissection-review-diagram"><svg viewBox="0 0 720 300" role="img" aria-label="Рисунок 221: разрезание прямоугольника 8 на 4 на четыре равных треугольника" data-source-figure="221" data-original-width="8" data-original-height="4" data-piece-count="4" data-result-shape="square"><g className="dr-source-shape"><rect x="45" y="60" width="360" height="180"/><path d="M225 60V240M45 60L225 240L405 60"/></g><text x="225" y="43" textAnchor="middle">8 см</text><text x="27" y="155" transform="rotate(-90 27 155)" textAnchor="middle">4 см</text><path className="dr-arrow" d="M440 150H500"/><g className="dr-result-shape"><polygon points="600,55 690,145 600,235 510,145"/><path d="M600 145V55M600 145H690M600 145V235M600 145H510"/></g><text x="600" y="274" textAnchor="middle">квадрат</text></svg></div>;
  if(variant==='figure-222')return <div className="dissection-review-diagram"><svg viewBox="0 0 720 285" role="img" aria-label="Рисунок 222: квадрат разрезан от нижней левой вершины до середины верхней стороны и собран в треугольник" data-source-figure="222" data-piece-count="2" data-piece-types="triangle|quadrilateral" data-result-shape="triangle"><g className="dr-source-shape"><rect x="50" y="35" width="200" height="200"/><path d="M50 235L150 35"/><path className="dr-tick" d="M95 25V47M195 25V47"/></g><text x="150" y="268" textAnchor="middle">точка делит сторону пополам</text><path className="dr-arrow" d="M285 140H375"/><g className="dr-result-shape"><polygon points="645,35 455,235 645,235"/><path d="M550 135H645"/></g><text x="550" y="268" textAnchor="middle">треугольник из двух частей</text></svg></div>;
  return <div className="dissection-review-diagram"><svg viewBox="0 0 720 285" role="img" aria-label="Рисунок 223: квадрат со стороной 6 сантиметров разрезан ступенчатой ломаной и собран в прямоугольник 9 на 4" data-source-figure="223" data-original-side="6" data-cut-segments="3|2|3" data-result-width="9" data-result-height="4"><g className="dr-source-shape"><rect x="40" y="30" width="210" height="210"/><path d="M40 100H145V170H250"/></g><text x="145" y="20" textAnchor="middle">6 см</text><text x="83" y="91" textAnchor="middle">3 см</text><text x="132" y="140" transform="rotate(-90 132 140)" textAnchor="middle">2 см</text><text x="198" y="192" textAnchor="middle">3 см</text><text x="22" y="69" transform="rotate(-90 22 69)" textAnchor="middle">2 см</text><text x="268" y="211" transform="rotate(-90 268 211)" textAnchor="middle">2 см</text><path className="dr-arrow" d="M290 140H350"/><g className="dr-result-shape"><rect x="375" y="75" width="270" height="120"/><path d="M465 75V135H555V195"/></g><text x="510" y="62" textAnchor="middle">9 см</text><text x="665" y="140" transform="rotate(-90 665 140)" textAnchor="middle">4 см</text><text x="510" y="235" textAnchor="middle">одна часть повёрнута на 180°</text></svg></div>;
}

const mirrorItems=[
  {axis:'v',path:'M0 -48H-55V-28H-20V18H-55V38H0Z'},
  {axis:'v',path:'M0 -45H52V45H0V24H30V-22H0Z'},
  {axis:'h',path:'M-55 0V-20H-20V-54H-55V-72H0V0Z'},
  {axis:'v',path:'M0 -50H-18V-30H-50V-10H-30V18H-50V40H0Z'},
  {axis:'h',path:'M-48 0V-20H-24V-50H-48V-68H-12V-86H8V0Z'},
  {axis:'v',path:'M0 -30H38V-50H56V48H0V8H-20V-14H0Z'},
  {axis:'v',path:'M0 -50H-42L-62 -30V48H0Z'},
  {axis:'v',path:'M0 -50L46 -24H0ZM0 -15L46 11H0ZM0 20L46 46H0Z'},
] as const;
function MirrorDiagram(){return <div className="dissection-review-diagram"><svg viewBox="0 0 720 335" role="img" aria-label="Рабочая тетрадь 161: все восемь фигур достроены зеркально относительно прямой a" data-source-exercise="РТ №161" data-source-item-count="8" data-completed-item-count="8"><defs><pattern id="l51-grid" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M18 0H0V18"/></pattern></defs><rect className="dr-grid" x="10" y="10" width="700" height="290" fill="url(#l51-grid)"/>{mirrorItems.map((item,index)=>{const vertical=item.axis==='v';return <g className="dr-mirror-item" key={index} transform={`translate(${90+(index%4)*180} ${78+Math.floor(index/4)*145})`}><line className="dr-axis" x1={vertical?0:-68} y1={vertical?-60:0} x2={vertical?0:68} y2={vertical?60:0}/><text className="dr-axis-label" x={vertical?8:72} y={vertical?-48:-7}>a</text><path className="dr-half" d={item.path}/><path className="dr-mirror" d={item.path} transform={vertical?'scale(-1 1)':'scale(1 -1)'}/><text x="0" y="76" textAnchor="middle">{index+1}</text></g>})}<text x="360" y="325" textAnchor="middle">сплошная половина + пунктирное зеркальное достроение</text></svg></div>}

function ParkDiagram(){return <div className="dissection-review-diagram"><svg viewBox="0 0 720 310" role="img" aria-label="Рабочая тетрадь 162: квадратный парк с садом, озером, кафе и площадкой" data-source-exercise="РТ №162" data-lake-perimeter="120" data-garden-perimeter="200" data-playground-perimeter="160"><g className="dr-park" transform="translate(220 25)"><rect width="240" height="240"/><path d="M150 0V240M0 90H240"/><rect className="dr-lake" x="150" width="90" height="90"/><rect className="dr-garden" y="90" width="150" height="150"/><text x="75" y="55" textAnchor="middle">К</text><text x="195" y="55" textAnchor="middle">О</text><text x="75" y="175" textAnchor="middle">С</text><text x="195" y="175" textAnchor="middle">П</text></g><g className="dr-legend"><text x="80" y="75">Озеро: P=120 м → 30 м</text><text x="80" y="115">Сад: P=200 м → 50 м</text><text x="470" y="165">Площадка</text><text x="470" y="195">30 м × 50 м</text><text x="470" y="225">P=160 м</text></g></svg></div>}

const gridLines=Array.from({length:5},(_,index)=>index*34);
const dotSets=[[[0,0],[3,0],[0,3],[3,3]],[[0,0],[1,1],[1,2],[2,3]],[[1,1],[1,2],[2,2],[3,2]]];
const tileSets=[[[0,0,1,1],[0,0,1,1],[2,2,3,3],[2,2,3,3]],[[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[0,0,0,1],[2,0,1,1],[2,2,3,1],[2,3,3,3]]];
function DotGridDiagram(){return <div className="dissection-review-diagram"><svg viewBox="0 0 720 255" role="img" aria-label="Рабочая тетрадь 165: решения трёх сеток четыре на четыре, разделённых на четыре равные части с одним кружком в каждой" data-source-exercise="РТ №165" data-grid-count="3" data-dots-per-grid="4" data-required-parts="4" data-solution-types="square|strip|T-tetromino">{dotSets.map((dots,gridIndex)=><g className="dr-dot-grid" key={gridIndex} transform={`translate(${55+gridIndex*225} 40)`}>{tileSets[gridIndex].map((row,y)=>row.map((piece,x)=><rect className={`dr-piece dr-piece-${piece}`} key={`${x}-${y}`} x={x*34+1} y={y*34+1} width="32" height="32"/>))}{gridLines.map(value=><path key={`v${value}`} d={`M${value} 0V136`}/>)}{gridLines.map(value=><path key={`h${value}`} d={`M0 ${value}H136`}/>)}{dots.map(([x,y])=><circle key={`${x}-${y}`} cx={x*34+17} cy={y*34+17} r="10"/>)}<text x="68" y="170" textAnchor="middle">схема {gridIndex+1}</text></g>)}</svg></div>}

function DiagonalSquareDiagram(){return <div className="dissection-review-diagram"><svg viewBox="0 0 720 300" role="img" aria-label="Рабочая тетрадь 166: построение квадрата по диагонали AC на клетчатой сетке" data-source-exercise="РТ №166" data-diagonal-vector="4|2" data-midpoint="4|3" data-missing-vertices="3|5;5|1"><defs><pattern id="l51-square-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32"/></pattern></defs><rect className="dr-grid" x="208" y="25" width="256" height="224" fill="url(#l51-square-grid)"/><g className="dr-square-build" transform="translate(208 25)"><polygon points="64,64 160,32 192,128 96,160"/><path className="dr-diagonal" d="M64 64L192 128"/><circle cx="64" cy="64" r="6"/><circle cx="192" cy="128" r="6"/><circle className="dr-new-point" cx="96" cy="160" r="6"/><circle className="dr-new-point" cx="160" cy="32" r="6"/><text x="49" y="58">A</text><text x="198" y="145">C</text><text x="81" y="182">B</text><text x="166" y="25">D</text></g><text x="336" y="282" textAnchor="middle">A(2;2), C(6;4) → B(3;5), D(5;1)</text></svg></div>}

function IntersectionDiagram(){return <div className="dissection-review-diagram"><svg viewBox="0 0 720 285" role="img" aria-label="Задание 379: луч PS пересекает отрезок AB и прямую MK, а MK не пересекает AB" data-source-exercise="№379" data-ray-intersects-segment="true" data-ray-intersects-line="true" data-line-intersects-segment="false"><defs><marker id="l51-arrowhead" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto"><path d="M0 0L9 4.5L0 9Z"/></marker></defs><line className="dr-line" x1="70" y1="190" x2="650" y2="190"/><text x="55" y="197">M</text><text x="662" y="197">K</text><line className="dr-segment" x1="270" y1="65" x2="270" y2="150"/><text x="255" y="55">A</text><text x="255" y="165">B</text><line className="dr-ray" x1="85" y1="55" x2="625" y2="235" markerEnd="url(#l51-arrowhead)"/><circle cx="85" cy="55" r="6"/><circle cx="175" cy="85" r="6"/><text x="65" y="48">P</text><text x="165" y="72">S</text><circle className="dr-cross" cx="270" cy="117" r="7"/><circle className="dr-cross" cx="490" cy="190" r="7"/></svg></div>}

function TransportDiagram(){return <div className="dissection-review-panel" data-source-exercise="№381"><div className="dr-transport"><span><b>Автобус</b><small>10+75+5</small><strong>90 мин</strong></span><span className="is-best"><b>Электропоезд</b><small>8+56+10</small><strong>74 мин</strong></span><span><b>Маршрутное такси</b><small>7+65+8</small><strong>80 мин</strong></span></div></div>}

function JugsDiagram(){return <div className="dissection-review-panel" data-source-exercise="№383"><div className="dr-jugs"><span><b>1</b>5 л → 3 л<small>в бидоне 2 л</small></span><i>→</i><span><b>2</b>2 л → банку<small>свободен 1 л</small></span><i>→</i><span><b>3</b>снова 5 л<small>доливаем 1 л</small></span><i>→</i><span className="is-result"><b>4</b>в бидоне<small>4 литра</small></span></div></div>}

function PanelDiagram({kind}:{kind:Extract<Diagram,{type:'panel'}>['kind']}){
  if(kind==='invariants')return <div className="dissection-review-panel"><div className="dr-invariants"><span><b>1</b><strong>равные части</strong><small>проверяем стороны и углы</small></span><span><b>2</b><strong>без потерь</strong><small>нет щелей и наложений</small></span><span><b>3</b><strong>новая граница</strong><small>замыкается точно</small></span></div></div>;
  if(kind==='straight-cut')return <div className="dissection-review-panel" data-source-exercise="РТ №163"><div className="dr-straight-cut"><span>△<small>3 стороны</small></span><span>□<small>4 стороны</small></span><span>⬠<small>5 сторон</small></span><span className="is-impossible">6?<small>невозможно</small></span></div></div>;
  if(kind==='fruit')return <div className="dissection-review-panel" data-source-exercise="№380"><div className="dr-fruit"><span><b>лимоны</b><strong>205+55=260</strong></span><span><b>апельсины</b><strong>205+36=241</strong></span><span><b>мандарины</b><strong>205+34=239</strong></span></div></div>;
  if(kind==='equations')return <div className="dissection-review-panel" data-source-exercise="№382"><div className="dr-equations"><span><b>x=130</b><b>y=109</b><strong>сумма 239</strong></span><span><b>x=28</b><b>y=231</b><strong>сумма 259</strong></span></div></div>;
  return <div className="dissection-review-panel"><div className="dr-final"><b>№375–378<br/>разрезания ✓</b><b>РТ №161–166<br/>построения ✓</b><b>№379–383<br/>повторение ✓</b><b>§ 15<br/>завершён ✓</b></div></div>;
}

function DiagramView({diagram}:{diagram:Diagram}){
  if(diagram.type==='dissection')return <DissectionDiagram variant={diagram.variant}/>;
  if(diagram.type==='mirror')return <MirrorDiagram/>;
  if(diagram.type==='park')return <ParkDiagram/>;
  if(diagram.type==='dot-grid')return <DotGridDiagram/>;
  if(diagram.type==='diagonal-square')return <DiagonalSquareDiagram/>;
  if(diagram.type==='intersection')return <IntersectionDiagram/>;
  if(diagram.type==='transport')return <TransportDiagram/>;
  if(diagram.type==='jugs')return <JugsDiagram/>;
  return <PanelDiagram kind={diagram.kind}/>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyOneStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function DissectionReviewPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyOneStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyOneStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==51||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyOneStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyOneStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player dissection-review-player" data-lesson-number="51" data-source-reference="Мерзляк §15 · №375–383 · рабочая тетрадь №161–163, 165–166"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<DiagramView diagram={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} Можно перейти дальше и вернуться к заданию позже.`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span className="stage-counter">Этап {saved.stageIndex+1} из {lessonFiftyOneStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyOneStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyOneStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
