import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'components'|'zeros'|'order'|'check'|'estimate'|'word'|'river'|'motion'|'unknown'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-62-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyTwoStages:Stage[]=[
  {id:'l62-mission',kind:'story',eyebrow:'Урок 62 · § 18 · закрепление',title:'Теперь деление должно стать рабочим инструментом',body:'На прошлом уроке мы разобрали смысл деления. Теперь тренируем вычислительную надёжность: быстрые частные случаи, порядок действий, проверку и задачи, где деление спрятано внутри модели.',note:'Технологическая карта: вопросы 1–6, затем № 452, 455, 465, 466, 468, 470; особое внимание — порядку действий.',visual:'mission'},
  {id:'l62-components-review',kind:'model',eyebrow:'Быстрый старт',title:'Компоненты помогают выбрать обратное действие',body:'В записи a:b=c число a — делимое, b — делитель, c — частное. Проверка всегда возвращает делимое: c·b=a.',note:'Если неизвестно делимое — умножай. Если неизвестен делитель — дели делимое на частное.',visual:'components'},
  {id:'l62-component-check',kind:'quiz',eyebrow:'Компоненты',title:'Читаем запись без путаницы',body:'Рассмотри равенство 936:18=52.',activity:{id:'l62-p1',type:'choice',prompt:'Какое число является делителем?',options:['936','18','52','936 и 52'],answer:'18',hint:'Делитель стоит после знака деления.',explanation:'В равенстве 936:18=52 делимое — 936, делитель — 18, частное — 52.'},visual:'components'},
  {id:'l62-powers-rule',kind:'model',eyebrow:'№ 452 · быстрые случаи',title:'Деление на 10, 100, 1000 — это работа с разрядами',body:'Если число оканчивается нужным количеством нулей, деление на 10, 100, 1000 уменьшает разряд каждой цифры. Но правило работает потому, что произведение частного и делителя возвращает исходное число.',note:'Не просто «зачёркивай нули»: всегда мысленно проверяй умножением.',visual:'zeros',sourceExercise:'№ 452'},
  {id:'l62-452-1',kind:'practice',eyebrow:'№ 452(1)',title:'Делим на 10',body:'Выполни деление 34 250 000:10.',activity:{id:'l62-p2',type:'input',prompt:'Чему равно частное?',answer:['3425000','3 425 000'],placeholder:'Частное',hint:'Каждый разряд становится в 10 раз меньше.',explanation:'34 250 000:10=3 425 000; проверка 3 425 000·10=34 250 000.'},visual:'zeros',sourceExercise:'№ 452(1)'},
  {id:'l62-452-2',kind:'practice',eyebrow:'№ 452(2)',title:'Делим на 1000',body:'Вычисли 34 250 000:1000.',activity:{id:'l62-p3',type:'input',prompt:'Запиши частное.',answer:['34250','34 250'],placeholder:'Частное',hint:'Разряды сдвигаются на три позиции.',explanation:'34 250 000:1000=34 250.'},visual:'zeros',sourceExercise:'№ 452(2)'},
  {id:'l62-452-3',kind:'practice',eyebrow:'№ 452(3)',title:'Делим на 10 000',body:'Теперь тот же делимый и делитель 10 000.',activity:{id:'l62-p4',type:'input',prompt:'34 250 000:10 000 = ?',answer:['3425','3 425'],placeholder:'Частное',hint:'Четыре нуля в делителе — четыре разрядных шага.',explanation:'34 250 000:10 000=3 425.'},visual:'zeros',sourceExercise:'№ 452(3)'},
  {id:'l62-452-4',kind:'practice',eyebrow:'№ 452(4)',title:'Круглый делитель 80',body:'Вычисли 25 600:80.',activity:{id:'l62-p5',type:'input',prompt:'Чему равно частное?',answer:['320'],placeholder:'Частное',hint:'Сократи общий множитель 10: 25 600:80 = 2 560:8.',explanation:'25 600:80=320; проверка 320·80=25 600.'},visual:'zeros',sourceExercise:'№ 452(4)'},
  {id:'l62-round-divisor',kind:'model',eyebrow:'Стратегия',title:'У круглого делителя можно убрать общий степенной множитель 10',body:'Если и делимое, и делитель делятся на 10, 100 и т. д., можно одновременно уменьшить оба числа в одинаковое число раз. Частное не изменится.',note:'25 600:800 = 256:8. Здесь оба числа уменьшили в 100 раз.',visual:'zeros'},
  {id:'l62-452-5',kind:'practice',eyebrow:'№ 452(5)',title:'Сокращаем два нуля',body:'Вычисли 25 600:800.',activity:{id:'l62-p6',type:'input',prompt:'Частное равно…',answer:['32'],placeholder:'Частное',hint:'Раздели оба числа на 100: 256:8.',explanation:'25 600:800=256:8=32.'},visual:'zeros',sourceExercise:'№ 452(5)'},
  {id:'l62-452-6',kind:'practice',eyebrow:'№ 452(6)',title:'Деление на 180',body:'Вычисли 2 430 000:180.',activity:{id:'l62-p7',type:'input',prompt:'Найди частное.',answer:['13500','13 500'],placeholder:'Частное',hint:'Сначала сократи общий ноль: 243 000:18.',explanation:'2 430 000:180=13 500; 13 500·180=2 430 000.'},visual:'zeros',sourceExercise:'№ 452(6)'},
  {id:'l62-order-rule',kind:'model',eyebrow:'№ 455–456',title:'Порядок действий — часть ответа, а не оформление',body:'Сначала выполняем действия в скобках, затем умножение и деление слева направо, после этого сложение и вычитание слева направо.',note:'Методическое пособие отдельно предупреждает об этом именно для № 455–456.',visual:'order'},
  {id:'l62-455-1',kind:'practice',eyebrow:'№ 455(1)',title:'Скобки → деление → вычитание',body:'Вычисли 4704 − 4704:(46+38).',activity:{id:'l62-p8',type:'input',prompt:'Каково значение выражения?',answer:['4648','4 648'],placeholder:'Результат',hint:'46+38=84, затем 4704:84=56.',explanation:'4704−4704:(46+38)=4704−56=4648.'},visual:'order',sourceExercise:'№ 455(1)'},
  {id:'l62-455-2',kind:'practice',eyebrow:'№ 455(2)',title:'Два частных перед сложением',body:'Вычисли 2808:72 + 15808:52.',activity:{id:'l62-p9',type:'input',prompt:'Найди итог.',answer:['343'],placeholder:'Результат',hint:'Вычисли два частных отдельно: 39 и 304.',explanation:'2808:72=39, 15808:52=304, поэтому сумма равна 343.'},visual:'order',sourceExercise:'№ 455(2)'},
  {id:'l62-parentheses-trap',kind:'model',eyebrow:'Антиошибка',title:'Нельзя читать выражение «по порядку записи»',body:'В 3264−3264:(92−44) первое действие находится в скобках. Если начать с вычитания 3264−3264, структура выражения разрушится.',note:'Перед вычислением назови порядок действий словами.',visual:'order'},
  {id:'l62-456-1',kind:'practice',eyebrow:'№ 456(1)',title:'Проверяем порядок действий',body:'Вычисли 3264 − 3264:(92−44).',activity:{id:'l62-p10',type:'input',prompt:'Значение выражения?',answer:['3196','3 196'],placeholder:'Результат',hint:'92−44=48; 3264:48=68.',explanation:'3264−68=3196.'},visual:'order',sourceExercise:'№ 456(1)'},
  {id:'l62-456-2',kind:'practice',eyebrow:'№ 456(2)',title:'Два деления и разность',body:'Вычисли 18144:84 − 2924:68.',activity:{id:'l62-p11',type:'input',prompt:'Найди результат.',answer:['173'],placeholder:'Результат',hint:'18144:84=216, 2924:68=43.',explanation:'216−43=173.'},visual:'order',sourceExercise:'№ 456(2)'},
  {id:'l62-check-rule',kind:'model',eyebrow:'Самопроверка',title:'Частное подтверждаем умножением',body:'Если вычислено a:b=c, то проверяем c·b=a. Для сложного выражения дополнительно проверяем промежуточные частные отдельно.',note:'Это быстрее, чем заново повторять весь вычислительный маршрут.',visual:'check'},
  {id:'l62-check-343',kind:'quiz',eyebrow:'Проверка № 455',title:'Как проверить второе частное?',body:'В № 455(2) получилось 15808:52=304.',activity:{id:'l62-p12',type:'choice',prompt:'Какое равенство является правильной проверкой?',options:['304·52=15808','304+52=15808','15808·52=304','304:52=15808'],answer:'304·52=15808',hint:'Частное умножаем на делитель.',explanation:'304·52=15 808, значит частное вычислено верно.'},visual:'check'},
  {id:'l62-estimate',kind:'model',eyebrow:'Прикидка',title:'Проверка масштаба ловит лишний ноль',body:'Перед точным делением оцени порядок результата. Например, 25 600:800 должно быть около 32, а не 320 или 3 200.',note:'Прикидка не заменяет точный ответ, но быстро отбрасывает невозможные.',visual:'estimate'},
  {id:'l62-estimate-choice',kind:'quiz',eyebrow:'Прикидка',title:'Выбери реалистичное частное',body:'Нужно оценить 2 430 000:18 000.',activity:{id:'l62-p13',type:'choice',prompt:'Какой результат подходит по масштабу?',options:['135','1 350','13 500','135 000'],answer:'135',hint:'Сократи три нуля: 2430:18.',explanation:'2 430 000:18 000=135.'},visual:'estimate'},
  {id:'l62-word-model',kind:'model',eyebrow:'Текстовые задачи',title:'Сначала отношения, потом вычисления',body:'В задачах § 18 деление часто отвечает на вопрос «сколько раз по столько?», а умножение переносит найденную норму на новое количество.',note:'Полезная схема: найти количество одинаковых групп → найти результат для одной/нескольких групп → проверить единицы.',visual:'word'},
  {id:'l62-465',kind:'practice',eyebrow:'№ 465',title:'Из сливок получаем масло',body:'Из 9 кг сливок получают 2 кг масла. Сколько масла можно изготовить из 261 кг сливок?',activity:{id:'l62-p14',type:'input',prompt:'Сколько килограммов масла получится?',answer:['58','58 кг'],placeholder:'кг',hint:'261:9=29 одинаковых порций сливок, затем 29·2.',explanation:'261:9=29, 29·2=58 кг масла.'},visual:'word',sourceExercise:'№ 465'},
  {id:'l62-466',kind:'quiz',eyebrow:'№ 466',title:'Хватит ли бензина?',body:'Автомобиль расходует 8 л на 100 км. Между Рязанью и Владимиром по трассе 248 км. В баке 20 л.',activity:{id:'l62-p15',type:'choice',prompt:'Хватит ли 20 л бензина?',options:['Да','Нет','Хватит ровно на 200 км','Нельзя определить'],answer:'Да',hint:'20 л при расходе 8 л на 100 км хватит на 250 км.',explanation:'20:8·100=250 км, а 250>248, значит бензина хватит.'},visual:'word',sourceExercise:'№ 466'},
  {id:'l62-river-model',kind:'model',eyebrow:'№ 468',title:'Течение меняет скорость дважды',body:'По течению скорость катера равна собственной скорости плюс скорость течения. Против течения — собственная скорость минус скорость течения.',note:'Если известны путь и время по течению, сначала найди скорость по течению: v=s:t.',visual:'river',sourceExercise:'№ 468'},
  {id:'l62-468',kind:'practice',eyebrow:'№ 468',title:'Катер между пристанями',body:'Расстояние 476 км. По течению катер проходит его за 14 ч. Скорость течения 3 км/ч.',activity:{id:'l62-p16',type:'input',prompt:'За сколько часов катер пройдёт путь против течения?',answer:['17','17 ч','17 часов'],placeholder:'ч',hint:'476:14=34; собственная 31; против течения 28; затем 476:28.',explanation:'34−3=31 км/ч — собственная скорость; 31−3=28 км/ч против течения; 476:28=17 ч.'},visual:'river',sourceExercise:'№ 468'},
  {id:'l62-motion-model',kind:'model',eyebrow:'№ 470',title:'При встречном движении складываем скорости',body:'Если два объекта движутся навстречу, за каждый час расстояние между ними уменьшается на сумму их скоростей.',note:'Скорость сближения = весь путь : время до встречи.',visual:'motion',sourceExercise:'№ 470'},
  {id:'l62-470',kind:'practice',eyebrow:'№ 470',title:'Винтик и Шпунтик',body:'Между Цветочным и Солнечным 136 км. Винтик едет 16 км/ч. Они встретились через 4 ч.',activity:{id:'l62-p17',type:'input',prompt:'С какой скоростью ехал Шпунтик?',answer:['18','18 км/ч'],placeholder:'км/ч',hint:'136:4=34 км/ч — общая скорость сближения. Вычти 16.',explanation:'136:4=34; 34−16=18 км/ч.'},visual:'motion',sourceExercise:'№ 470'},
  {id:'l62-unknown-components',kind:'model',eyebrow:'Обратные задачи',title:'Неизвестный компонент определяет действие',body:'Если a:b=c, то a=c·b, а b=a:c. Эти две формулы защищают от угадывания действия.',note:'Проверяй найденный компонент исходным равенством.',visual:'unknown'},
  {id:'l62-unknown-dividend',kind:'practice',eyebrow:'Обратное действие',title:'Восстанавливаем делимое',body:'Частное равно 48, делитель 25.',activity:{id:'l62-p18',type:'input',prompt:'Найди делимое.',answer:['1200','1 200'],placeholder:'Делимое',hint:'Делимое = частное · делитель.',explanation:'48·25=1200.'},visual:'unknown'},
  {id:'l62-unknown-divisor',kind:'practice',eyebrow:'Обратное действие',title:'Восстанавливаем делитель',body:'Делимое 1512, частное 216.',activity:{id:'l62-p19',type:'input',prompt:'Найди делитель.',answer:['7'],placeholder:'Делитель',hint:'Делитель = делимое : частное.',explanation:'1512:216=7; проверка 216·7=1512.'},visual:'unknown'},
  {id:'l62-error-hunt',kind:'model',eyebrow:'Диагностика ошибок',title:'Три типичные ловушки урока',body:'Лишний ноль в частном, нарушенный порядок действий и неверный выбор скорости в задаче — разные ошибки. Для каждой нужен свой контроль: прикидка, план действий или схема движения.',note:'Сильная проверка выбирается под тип риска.',visual:'error'},
  {id:'l62-zero-rule',kind:'quiz',eyebrow:'Граница правила',title:'Делитель не может быть нулём',body:'В вычислениях с компонентами это ограничение остаётся обязательным.',activity:{id:'l62-p20',type:'choice',prompt:'Какое утверждение верно?',options:['84:0 не определено','84:0=84','84:0=0','0:0=1'],answer:'84:0 не определено',hint:'Нельзя найти число q, для которого q·0=84.',explanation:'Делить на ноль нельзя.'},visual:'error'},
  {id:'l62-transfer',kind:'model',eyebrow:'Перенос',title:'Один и тот же алгоритм работает в новой ситуации',body:'Для сложной задачи сначала выпиши величины и единицы, затем обозначь неизвестное, выбери действие по смыслу и только после этого считай.',note:'Так деление перестаёт быть набором приёмов и становится частью математической модели.',visual:'challenge'},
  {id:'l62-challenge',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Обратная задача на встречное движение',body:'Два велосипедиста стартовали навстречу и встретились через 6 ч. Расстояние между пунктами 372 км, скорость первого 27 км/ч.',activity:{id:'l62-p21',type:'input',prompt:'Найди скорость второго велосипедиста.',answer:['35','35 км/ч'],placeholder:'км/ч',hint:'372:6=62 км/ч — скорость сближения.',explanation:'62−27=35 км/ч.'},visual:'challenge'},
  {id:'l62-reflection',kind:'guided',eyebrow:'Перед финишем',title:'Сформулируй алгоритм надёжного деления',body:'Назови четыре шага: понять роль деления, выбрать удобный способ, выполнить действия в правильном порядке, проверить частное умножением или моделью задачи.',note:'На финише обязательная практика проверит эти шаги в разных форматах.',visual:'check'},
  {id:'l62-summary',kind:'summary',eyebrow:'Урок 62 · итог',title:'Деление закреплено не только как вычисление, но и как способ моделирования',body:'Ты потренировал № 452, 455, 465, 466, 468 и 470: круглые делители, порядок действий, проверку, пропорциональные зависимости, течение и встречное движение.',note:'Дальше — обязательная практика: 20 заданий и ровно 50 ответов. После неё сформулируй главный вывод своими словами.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){
  if(kind==='mission')return <div className="division-visual"><div className="division-final"><b>§18</b><b>вычисления</b><b>порядок</b><b>задачи</b><b>проверка</b></div></div>;
  if(kind==='components')return <div className="division-visual"><div className="division-check"><span>a:b</span><i>=</i><b>c</b><i>→</i><strong>c·b=a ✓</strong></div></div>;
  if(kind==='zeros')return <div className="division-visual"><div className="division-zeros"><span>25 600:800</span><i>÷100</i><span>256:8</span><i>=</i><strong>32</strong></div></div>;
  if(kind==='order')return <div className="division-visual"><div className="division-written"><span><small>1</small><b>( )</b></span><i>→</i><span><small>2</small><b>× и :</b></span><i>→</i><span><small>3</small><b>+ и −</b></span></div></div>;
  if(kind==='check')return <div className="division-visual"><div className="division-check"><span>15 808:52</span><i>→</i><b>304</b><i>→</i><strong>304·52=15 808 ✓</strong></div></div>;
  if(kind==='estimate')return <div className="division-visual"><div className="division-estimate"><span><small>прикидка</small><b>2 430 000:18 000</b></span><strong>≈135</strong><del>13 500</del></div></div>;
  if(kind==='word')return <div className="division-visual"><div className="division-check"><span>261 кг</span><i>÷9</i><b>29 групп</b><i>×2</i><strong>58 кг</strong></div></div>;
  if(kind==='river')return <div className="division-visual"><div className="division-written"><span><small>по течению</small><b>v+3</b></span><i>↔</i><span><small>собственная</small><b>v</b></span><i>↔</i><span><small>против</small><b>v−3</b></span></div></div>;
  if(kind==='motion')return <div className="division-visual"><div className="division-check"><span>136 км</span><i>÷4 ч</i><b>34 км/ч</b><i>−16</i><strong>18 км/ч</strong></div></div>;
  if(kind==='unknown')return <div className="division-visual"><div className="division-specials"><b>a:b=c</b><b>a=c·b</b><b>b=a:c</b></div></div>;
  if(kind==='error')return <div className="division-visual"><div className="division-errors"><b>прикидка ✓</b><b>порядок ✓</b><b>схема ✓</b><del>деление на 0</del></div></div>;
  if(kind==='challenge')return <div className="division-visual"><div className="division-check"><span>372:6</span><i>=</i><b>62</b><i>−27</i><strong>?</strong></div></div>;
  return <div className="division-visual"><div className="division-final"><b>№452 ✓</b><b>№455 ✓</b><b>№465–466 ✓</b><b>№468 ✓</b><b>№470 ✓</b><b>50 ответов →</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyTwoStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function DivisionReinforcementPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyTwoStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyTwoStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==62||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyTwoStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonSixtyTwoStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player division-meaning-player division-reinforcement-player" data-lesson-number="62" data-source-reference="Мерзляк § 18 · технологическая карта урока 62 · № 452, 455, 465, 466, 468, 470" data-source-exercise-range="452-470"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyTwoStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyTwoStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyTwoStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
