import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'rule'|'factor'|'dividend'|'divisor'|'combine'|'verify'|'transfer'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-64-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyFourStages:Stage[]=[
{id:'l64-mission',kind:'story',eyebrow:'Урок 64 · § 18 · уравнения',title:'Не угадываем действие — определяем роль неизвестного',body:'Сегодня уравнение решается не по внешнему виду, а по смыслу действия. Сначала определяем, чем является неизвестное: множителем, делимым или делителем. Затем применяем обратную связь и обязательно проверяем корень.',note:'Технологическая карта урока 64: решать уравнения, используя связи между компонентами действия деления.',visual:'mission'},
{id:'l64-rule-map',kind:'model',eyebrow:'Карта правил',title:'Три роли неизвестного — три разных хода',body:'Если x·a=b, то x=b:a. Если x:a=b, то x=a·b. Если a:x=b, то x=a:b. Ключевой вопрос: какую роль играет x именно сейчас?',note:'Неизвестное делимое находят умножением, неизвестный делитель — делением, неизвестный множитель — делением.',visual:'rule'},
{id:'l64-rule-check',kind:'quiz',eyebrow:'Выбор правила',title:'x : 21 = 16',body:'Здесь x стоит на месте делимого.',activity:{id:'l64-p1',type:'choice',prompt:'Какое действие найдёт x?',options:['21·16','21:16','16:21','21+16'],answer:'21·16',hint:'Чтобы найти неизвестное делимое, делитель умножают на частное.',explanation:'x=21·16. Неизвестное делимое восстанавливаем умножением.'},visual:'dividend'},
{id:'l64-example-factor',kind:'guided',eyebrow:'Пример 1 из § 18',title:'12x = 84: неизвестный множитель',body:'Произведение равно 84, один множитель равен 12. Поэтому неизвестный множитель равен произведению, делённому на известный множитель.',note:'x=84:12.',visual:'factor'},
{id:'l64-example-factor-root',kind:'practice',eyebrow:'Пример 1',title:'Находим корень',body:'12x=84.',activity:{id:'l64-p2',type:'input',prompt:'Чему равен x?',answer:['7','x=7'],placeholder:'x',hint:'84 раздели на 12.',explanation:'x=84:12=7.'},visual:'factor'},
{id:'l64-example-factor-check',kind:'quiz',eyebrow:'Проверка корня',title:'Возвращаем найденное число в исходное уравнение',body:'Для x=7 исходная левая часть становится 12·7.',activity:{id:'l64-p3',type:'input',prompt:'Чему равно 12·7?',answer:'84',placeholder:'результат',hint:'Проверка должна вернуть правую часть исходного уравнения.',explanation:'12·7=84, значит x=7 — корень.'},visual:'verify'},
{id:'l64-example-dividend',kind:'guided',eyebrow:'Пример 2 из § 18',title:'x : 21 = 16: неизвестное делимое',body:'Чтобы найти неизвестное делимое, нужно делитель умножить на частное.',note:'x=21·16.',visual:'dividend'},
{id:'l64-example-dividend-root',kind:'practice',eyebrow:'Пример 2',title:'Восстанавливаем делимое',body:'x:21=16.',activity:{id:'l64-p4',type:'input',prompt:'Чему равен x?',answer:['336','x=336'],placeholder:'x',hint:'21·16.',explanation:'x=21·16=336.'},visual:'dividend'},
{id:'l64-example-dividend-check',kind:'quiz',eyebrow:'Проверка корня',title:'Проверяем делением',body:'Подставим x=336.',activity:{id:'l64-p5',type:'input',prompt:'Чему равно 336:21?',answer:'16',placeholder:'частное',hint:'Проверка должна дать 16.',explanation:'336:21=16, поэтому x=336 подходит.'},visual:'verify'},
{id:'l64-example-divisor',kind:'guided',eyebrow:'Пример 3 из § 18',title:'576 : x = 18: неизвестный делитель',body:'Чтобы найти неизвестный делитель, нужно делимое разделить на частное.',note:'x=576:18.',visual:'divisor'},
{id:'l64-example-divisor-root',kind:'practice',eyebrow:'Пример 3',title:'Находим делитель',body:'576:x=18.',activity:{id:'l64-p6',type:'input',prompt:'Чему равен x?',answer:['32','x=32'],placeholder:'x',hint:'576 раздели на 18.',explanation:'x=576:18=32.'},visual:'divisor'},
{id:'l64-example-divisor-check',kind:'quiz',eyebrow:'Проверка корня',title:'Проверяем исходное деление',body:'Подставляем x=32.',activity:{id:'l64-p7',type:'input',prompt:'Чему равно 576:32?',answer:'18',placeholder:'частное',hint:'Если получилось 18, корень верен.',explanation:'576:32=18. Корень x=32 проверен.'},visual:'verify'},
{id:'l64-457-map',kind:'model',eyebrow:'№ 457',title:'Шесть уравнений — три базовых правила плюс упрощение',body:'В №457 встречаются неизвестный множитель, неизвестное делимое и неизвестный делитель. В двух уравнениях сначала нужно привести подобные слагаемые с x или m.',note:'Сначала упростить левую часть, затем определить роль неизвестного.',visual:'combine',sourceExercise:'№ 457'},
{id:'l64-457-1',kind:'practice',eyebrow:'№ 457 (1)',title:'13x = 195',body:'x — неизвестный множитель.',activity:{id:'l64-p8',type:'input',prompt:'Найди x.',answer:['15','x=15'],placeholder:'x',hint:'195:13.',explanation:'x=195:13=15. Проверка: 13·15=195.'},visual:'factor',sourceExercise:'№ 457 (1)'},
{id:'l64-457-2',kind:'practice',eyebrow:'№ 457 (2)',title:'x · 18 = 468',body:'Снова неизвестный множитель.',activity:{id:'l64-p9',type:'input',prompt:'Найди x.',answer:['26','x=26'],placeholder:'x',hint:'468:18.',explanation:'x=468:18=26.'},visual:'factor',sourceExercise:'№ 457 (2)'},
{id:'l64-457-3',kind:'practice',eyebrow:'№ 457 (3)',title:'11x + 6x = 408',body:'Перед обратным действием объедини одинаковые буквенные части: 11x+6x=17x.',activity:{id:'l64-p10',type:'input',prompt:'Найди x.',answer:['24','x=24'],placeholder:'x',hint:'Сначала 17x=408, затем 408:17.',explanation:'17x=408, поэтому x=24.'},visual:'combine',sourceExercise:'№ 457 (3)'},
{id:'l64-457-4',kind:'practice',eyebrow:'№ 457 (4)',title:'33m − m = 1 024',body:'33m−m=32m.',activity:{id:'l64-p11',type:'input',prompt:'Найди m.',answer:['32','m=32'],placeholder:'m',hint:'1024:32.',explanation:'32m=1024, значит m=32.'},visual:'combine',sourceExercise:'№ 457 (4)'},
{id:'l64-457-5',kind:'practice',eyebrow:'№ 457 (5)',title:'x : 19 = 26',body:'x — неизвестное делимое.',activity:{id:'l64-p12',type:'input',prompt:'Найди x.',answer:['494','x=494'],placeholder:'x',hint:'19·26.',explanation:'x=19·26=494.'},visual:'dividend',sourceExercise:'№ 457 (5)'},
{id:'l64-457-6',kind:'practice',eyebrow:'№ 457 (6)',title:'476 : x = 14',body:'x — неизвестный делитель.',activity:{id:'l64-p13',type:'input',prompt:'Найди x.',answer:['34','x=34'],placeholder:'x',hint:'476:14.',explanation:'x=476:14=34.'},visual:'divisor',sourceExercise:'№ 457 (6)'},
{id:'l64-458-map',kind:'model',eyebrow:'№ 458',title:'Меняем числа — правило остаётся',body:'Второй набор нужен не для запоминания ответов, а для автоматизации выбора правила. Каждый корень затем проверяется в исходном уравнении.',visual:'rule',sourceExercise:'№ 458'},
{id:'l64-458-1',kind:'practice',eyebrow:'№ 458 (1)',title:'19x = 95',body:'Неизвестный множитель.',activity:{id:'l64-p14',type:'input',prompt:'Найди x.',answer:['5','x=5'],placeholder:'x',hint:'95:19.',explanation:'x=5.'},visual:'factor',sourceExercise:'№ 458 (1)'},
{id:'l64-458-2',kind:'practice',eyebrow:'№ 458 (2)',title:'x · 22 = 132',body:'Неизвестный множитель.',activity:{id:'l64-p15',type:'input',prompt:'Найди x.',answer:['6','x=6'],placeholder:'x',hint:'132:22.',explanation:'x=6.'},visual:'factor',sourceExercise:'№ 458 (2)'},
{id:'l64-458-3',kind:'practice',eyebrow:'№ 458 (3)',title:'38x − 16x = 1 474',body:'Сначала 38x−16x=22x.',activity:{id:'l64-p16',type:'input',prompt:'Найди x.',answer:['67','x=67'],placeholder:'x',hint:'1474:22.',explanation:'22x=1474, поэтому x=67.'},visual:'combine',sourceExercise:'№ 458 (3)'},
{id:'l64-458-4',kind:'practice',eyebrow:'№ 458 (4)',title:'y + 27y = 952',body:'y+27y=28y.',activity:{id:'l64-p17',type:'input',prompt:'Найди y.',answer:['34','y=34'],placeholder:'y',hint:'952:28.',explanation:'28y=952, значит y=34.'},visual:'combine',sourceExercise:'№ 458 (4)'},
{id:'l64-458-5',kind:'practice',eyebrow:'№ 458 (5)',title:'x : 25 = 16',body:'x — делимое.',activity:{id:'l64-p18',type:'input',prompt:'Найди x.',answer:['400','x=400'],placeholder:'x',hint:'25·16.',explanation:'x=25·16=400.'},visual:'dividend',sourceExercise:'№ 458 (5)'},
{id:'l64-458-6',kind:'practice',eyebrow:'№ 458 (6)',title:'324 : x = 27',body:'x — делитель.',activity:{id:'l64-p19',type:'input',prompt:'Найди x.',answer:['12','x=12'],placeholder:'x',hint:'324:27.',explanation:'x=324:27=12.'},visual:'divisor',sourceExercise:'№ 458 (6)'},
{id:'l64-verification',kind:'model',eyebrow:'Самопроверка',title:'Проверка — часть решения, а не украшение',body:'После нахождения корня подставь его именно в исходное уравнение. Если обе части равны, корень подтверждён. Это ловит ошибку в выборе правила и арифметике.',note:'Особенно важно не проверять уже преобразованное уравнение вместо исходного.',visual:'verify'},
{id:'l64-error-lab',kind:'model',eyebrow:'Ловушка',title:'Неизвестное делимое и делитель нельзя менять местами',body:'В x:8=6 получаем x=8·6. Но в 48:x=6 получаем x=48:6. Одинаковое слово «деление» не означает одинаковое обратное действие.',visual:'error'},
{id:'l64-459',kind:'practice',eyebrow:'№ 459 · перенос навыка',title:'Сначала восстанови расстояние, затем новую скорость',body:'Всадник проходит путь за 5 ч со скоростью 12 км/ч. Тот же путь нужно пройти за 4 ч.',activity:{id:'l64-p20',type:'input',prompt:'С какой скоростью нужно двигаться?',answer:['15','15 км/ч'],placeholder:'км/ч',hint:'Сначала 12·5=60 км, затем 60:4.',explanation:'Путь 60 км. Чтобы пройти его за 4 ч, нужна скорость 15 км/ч.'},visual:'transfer',sourceExercise:'№ 459'},
{id:'l64-460',kind:'practice',eyebrow:'№ 460 · перенос навыка',title:'Одна и та же сумма денег',body:'Вика купила 8 кг конфет по 630 рублей за килограмм. За ту же сумму покупает конфеты по 420 рублей за килограмм.',activity:{id:'l64-p21',type:'input',prompt:'Сколько килограммов она сможет купить?',answer:['12','12 кг'],placeholder:'кг',hint:'Сначала найди общую стоимость: 8·630.',explanation:'8·630=5040 рублей; 5040:420=12 кг.'},visual:'transfer',sourceExercise:'№ 460'},
{id:'l64-error-check',kind:'model',eyebrow:'Диагностика ошибки',title:'Почему x=3 для 72:x=8 неверно?',body:'Если подставить 3, получаем 72:3=24, а не 8. Правило для неизвестного делителя: x=72:8=9.',note:'Подстановка мгновенно обнаруживает ошибку «перевернул действие».',visual:'error'},
{id:'l64-challenge',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Сначала сверни одинаковые части',body:'Рассмотри уравнение 9x+7x=512. Сильный ход — сначала получить 16x=512, а уже потом применить правило неизвестного множителя.',note:'Корень x=32; проверка: 9·32+7·32=512.',visual:'challenge'},
{id:'l64-strategy',kind:'model',eyebrow:'Стратегия',title:'Алгоритм решения уравнения с делением',body:'1) Упрости числовые и одинаковые буквенные части. 2) Назови последнее действие и роль неизвестного. 3) Примени соответствующее обратное действие. 4) Вычисли. 5) Подставь корень в исходное уравнение.',visual:'rule'},
{id:'l64-checkpoint',kind:'quiz',eyebrow:'Контроль понимания',title:'Три формулы в одной карте',body:'x·a=b → x=b:a; x:a=b → x=a·b; a:x=b → x=a:b.',note:'Если можешь объяснить не только формулу, но и почему она является обратным действием, тема усвоена.',visual:'verify'},
{id:'l64-summary',kind:'summary',eyebrow:'Итог урока',title:'Теперь ты решаешь уравнения по структуре действия',body:'Ты научился различать неизвестный множитель, делимое и делитель, упрощать выражение перед решением, находить корень и доказывать его подстановкой. Дальше — обязательная практика: 20 заданий и 50 ответов.',note:'После практики урок считается завершённым.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){
 const map:Record<VisualKind,[string,string,string]>={
  mission:['роль x','обратное действие','проверка'],rule:['x·a=b','x:a=b','a:x=b'],factor:['произведение','÷ известный множитель','x'],dividend:['делитель','× частное','делимое'],divisor:['делимое','÷ частное','делитель'],combine:['11x+6x','17x','408'],verify:['корень','→ подстановка','равенство ✓'],transfer:['модель','вычисление','смысл'],error:['роль x?','не угадывай','проверь'],challenge:['структура','короткий ход','доказательство'],final:['21 проверка','20 задач','50 ответов']
 };
 const [a,b,c]=map[kind];return <div className="division-visual" data-division-equation-visual={kind}><div className="division-check"><span>{a}</span><i>→</i><strong>{b}</strong><i>→</i><span>{c}</span></div></div>;
}
function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyFourStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function DivisionEquationsPlayer(){
 const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyFourStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyFourStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==64||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyFourStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
 function next(){if(!canContinue||saved.stageIndex>=lessonSixtyFourStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player division-equations-player" data-lesson-number="64" data-source-reference="Мерзляк § 18 · технологическая карта урока 64 · примеры 1-3 · № 457-460" data-source-exercise-range="457-460"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyFourStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyFourStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyFourStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
