import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'division'|'equation'|'work'|'expression'|'mass'|'verify'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-65-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyFiveStages:Stage[]=[
{id:'l65-mission',kind:'story',eyebrow:'Урок 65 · § 18 · закрепление',title:'Теперь действие выбирает смысл задачи',body:'Сегодня деление соединяется со сложением, вычитанием и умножением. Сильное решение — это не цепочка случайных вычислений, а план: что означает каждый промежуточный результат, в каких он единицах и зачем нужен следующему шагу.',note:'Технологическая карта урока 65 требует закрепить деление, уравнения и текстовые задачи с применением всех четырёх арифметических действий.',visual:'mission'},
{id:'l65-four-actions',kind:'model',eyebrow:'Карта действий',title:'Четыре действия — четыре вопроса',body:'Сложение объединяет, вычитание находит остаток или разность, умножение собирает одинаковые группы, деление распределяет поровну или находит число групп. В многошаговой задаче эти смыслы могут сменять друг друга.',visual:'map'},
{id:'l65-plan-choice',kind:'quiz',eyebrow:'Выбор стратегии',title:'Сначала назови величину',body:'Если 288 страниц набраны за 4 дня тремя одинаково работающими операторами, первый промежуточный результат удобно понимать как общую производительность за один день.',activity:{id:'l65-p1',type:'choice',prompt:'Какое действие сначала выполняем?',options:['288:4','288·4','288−4','288+4'],answer:'288:4',hint:'Нужно перейти от четырёх дней к одному дню.',explanation:'288:4=72 страницы — столько три оператора вместе набирают за один день.'},visual:'work',sourceExercise:'№ 483'},
{id:'l65-division-check',kind:'practice',eyebrow:'Разминка',title:'Деление должно выдерживать обратную проверку',body:'Частное считается надёжным, если умножение частного на делитель возвращает делимое.',activity:{id:'l65-p2',type:'input',prompt:'Вычисли 936:18.',answer:'52',placeholder:'частное',hint:'Проверь 52·18.',explanation:'936:18=52; 52·18=936.'},visual:'division'},
{id:'l65-equation-map',kind:'model',eyebrow:'Уравнения',title:'Роль неизвестного определяет обратное действие',body:'x·a=b → x=b:a; x:a=b → x=a·b; a:x=b → x=a:b. Перед вычислением полезно вслух назвать: множитель, делимое или делитель.',visual:'equation'},
{id:'l65-factor',kind:'practice',eyebrow:'Уравнение',title:'Неизвестный множитель',body:'17x=697.',activity:{id:'l65-p3',type:'input',prompt:'Найди x.',answer:['41','x=41'],placeholder:'x',hint:'697:17.',explanation:'x=697:17=41. Проверка: 17·41=697.'},visual:'equation'},
{id:'l65-dividend',kind:'practice',eyebrow:'Уравнение',title:'Неизвестное делимое',body:'x:24=37.',activity:{id:'l65-p4',type:'input',prompt:'Найди x.',answer:['888','x=888'],placeholder:'x',hint:'Делимое = делитель · частное.',explanation:'x=24·37=888.'},visual:'equation'},
{id:'l65-divisor',kind:'practice',eyebrow:'Уравнение',title:'Неизвестный делитель',body:'888:x=37.',activity:{id:'l65-p5',type:'input',prompt:'Найди x.',answer:['24','x=24'],placeholder:'x',hint:'Делитель = делимое : частное.',explanation:'x=888:37=24.'},visual:'equation'},
{id:'l65-461-map',kind:'guided',eyebrow:'№ 461 (2)',title:'Контроль вычислительной точности',body:'В технологической карте первым письменным заданием стоит № 461 (2). В ответах учебника для этого пункта указан результат 888. Здесь важно не только получить число, но и проверить порядок действий и масштаб результата.',note:'Контрольный результат № 461 (2): 888.',visual:'expression',sourceExercise:'№ 461 (2)'},
{id:'l65-461-answer',kind:'practice',eyebrow:'№ 461 (2)',title:'Фиксируем контрольный результат',body:'После выполнения исходного выражения сравни результат с контрольным ответом.',activity:{id:'l65-p6',type:'input',prompt:'Какой результат должен получиться в № 461 (2)?',answer:'888',placeholder:'результат',hint:'Сверь вычисления и порядок действий.',explanation:'Контрольный ответ учебника: 888.'},visual:'verify',sourceExercise:'№ 461 (2)'},
{id:'l65-estimate',kind:'quiz',eyebrow:'Самопроверка',title:'Прикидка ловит грубую ошибку',body:'Если точный ответ должен быть 888, результат 8 880 отличается на порядок и требует немедленной перепроверки записи или действия.',activity:{id:'l65-p7',type:'choice',prompt:'Какой ответ согласуется с контрольным результатом № 461 (2)?',options:['888','8 880','88','88 800'],answer:'888',hint:'Проверь разрядность.',explanation:'Правильная контрольная точка — 888.'},visual:'verify'},
{id:'l65-483-model',kind:'model',eyebrow:'№ 483',title:'Производительность: от общего к одному',body:'Три оператора за 4 дня набрали 288 страниц. Их производительность одинакова. Нужно узнать, сколько страниц наберёт один оператор за 7 дней. План: общая работа за день → работа одного оператора за день → работа одного за 7 дней.',visual:'work',sourceExercise:'№ 483'},
{id:'l65-483-day',kind:'practice',eyebrow:'№ 483 · шаг 1',title:'Три оператора за один день',body:'За 4 дня набрано 288 страниц.',activity:{id:'l65-p8',type:'input',prompt:'Сколько страниц три оператора набирают за 1 день?',answer:['72','72 страницы','72 страниц'],placeholder:'страниц',hint:'288:4.',explanation:'288:4=72 страницы в день — совместная производительность трёх операторов.'},visual:'work',sourceExercise:'№ 483'},
{id:'l65-483-one',kind:'practice',eyebrow:'№ 483 · шаг 2',title:'Один оператор за один день',body:'Три оператора вместе набирают 72 страницы в день и работают одинаково.',activity:{id:'l65-p9',type:'input',prompt:'Сколько страниц набирает один оператор за день?',answer:['24','24 страницы','24 страниц'],placeholder:'страниц',hint:'72:3.',explanation:'72:3=24 страницы в день.'},visual:'work',sourceExercise:'№ 483'},
{id:'l65-483-seven',kind:'practice',eyebrow:'№ 483 · шаг 3',title:'Один оператор за семь дней',body:'Производительность одного оператора — 24 страницы в день.',activity:{id:'l65-p10',type:'input',prompt:'Сколько страниц он наберёт за 7 дней?',answer:['168','168 страниц','168 страницы'],placeholder:'страниц',hint:'24·7.',explanation:'24·7=168 страниц. Это совпадает с ответом учебника.'},visual:'work',sourceExercise:'№ 483'},
{id:'l65-483-check',kind:'quiz',eyebrow:'№ 483 · проверка',title:'Возвращаемся к исходным данным',body:'Если один оператор делает 24 страницы в день, три оператора за 4 дня должны дать исходные 288 страниц.',activity:{id:'l65-p11',type:'input',prompt:'Вычисли 24·3·4.',answer:'288',placeholder:'страниц',hint:'Это обратная проверка модели.',explanation:'24·3·4=288 — исходное условие восстановлено.'},visual:'verify',sourceExercise:'№ 483'},
{id:'l65-model-switch',kind:'model',eyebrow:'Многошаговые задачи',title:'Не выбирай действие по одному слову',body:'Слова «всего», «на», «в раз», «поровну» полезны, но не заменяют модель. Сначала определи, какая величина известна и какую нужно получить. Затем проверь единицы каждого шага.',visual:'map'},
{id:'l65-units-choice',kind:'quiz',eyebrow:'Смысл промежуточного ответа',title:'Что означает 72 в № 483?',body:'Число без смысла легко использовать не в том месте.',activity:{id:'l65-p12',type:'choice',prompt:'72 — это...',options:['страниц у трёх операторов за день','страниц у одного оператора за 7 дней','дней работы','операторов'],answer:'страниц у трёх операторов за день',hint:'288 страниц поделили на 4 дня.',explanation:'72 — совместная дневная производительность трёх операторов.'},visual:'work'},
{id:'l65-491-map',kind:'model',eyebrow:'№ 491 (3–4)',title:'Вычислительная практика: держим структуру выражения',body:'Технологическая карта отдельно выделяет пункты 3–4 упражнения № 491. Здесь ключевой навык — не терять порядок действий и проверять деление обратным умножением. Полный текст исходного упражнения остаётся в учебнике; в тренажёре закрепляем тот же приём.',visual:'expression',sourceExercise:'№ 491 (3–4)'},
{id:'l65-expression-a',kind:'practice',eyebrow:'Тренировка к № 491',title:'Скобки сначала',body:'Вычисли (840−336):24.',activity:{id:'l65-p13',type:'input',prompt:'Чему равно выражение?',answer:'21',placeholder:'результат',hint:'Сначала 840−336=504.',explanation:'504:24=21. Проверка: 21·24=504.'},visual:'expression'},
{id:'l65-expression-b',kind:'practice',eyebrow:'Тренировка к № 491',title:'Умножение и деление до сложения',body:'Вычисли 864:27+14·6.',activity:{id:'l65-p14',type:'input',prompt:'Чему равно выражение?',answer:'116',placeholder:'результат',hint:'864:27=32, 14·6=84.',explanation:'32+84=116.'},visual:'expression'},
{id:'l65-499-map',kind:'model',eyebrow:'№ 499',title:'Перед вычислением составь план',body:'№ 499 включён в основной маршрут урока 65 как отдельная контрольная точка. Универсальный алгоритм: выписать данные → назвать искомое → построить цепочку промежуточных величин → выполнить действия → проверить ответ по смыслу.',visual:'map',sourceExercise:'№ 499'},
{id:'l65-equation-mixed',kind:'practice',eyebrow:'Смешанное закрепление',title:'Сначала упростить, потом решить',body:'8x+4x=1 008.',activity:{id:'l65-p15',type:'input',prompt:'Найди x.',answer:['84','x=84'],placeholder:'x',hint:'12x=1008.',explanation:'x=1008:12=84.'},visual:'equation'},
{id:'l65-501-map',kind:'model',eyebrow:'№ 501',title:'Три результата должны согласовываться между собой',body:'Для № 501 ответный раздел учебника даёт три массы: 132 кг, 88 кг и 44 кг. Такая задача удобна для проверки отношений между величинами и общей суммы, а не только отдельных чисел.',note:'Контрольные ответы № 501: 132 кг, 88 кг, 44 кг.',visual:'mass',sourceExercise:'№ 501'},
{id:'l65-501-sum',kind:'practice',eyebrow:'№ 501 · контроль',title:'Проверяем общую массу',body:'Сложим три контрольных результата.',activity:{id:'l65-p16',type:'input',prompt:'Чему равно 132+88+44?',answer:['264','264 кг'],placeholder:'кг',hint:'Сначала 132+88=220.',explanation:'Общая масса трёх частей — 264 кг.'},visual:'mass',sourceExercise:'№ 501'},
{id:'l65-501-ratio',kind:'practice',eyebrow:'№ 501 · связи',title:'Сравни крайние значения',body:'132 кг и 44 кг связаны простым отношением.',activity:{id:'l65-p17',type:'input',prompt:'Во сколько раз 132 больше 44?',answer:['3','в 3 раза'],placeholder:'раз',hint:'132:44.',explanation:'132:44=3.'},visual:'mass',sourceExercise:'№ 501'},
{id:'l65-512-map',kind:'model',eyebrow:'№ 512',title:'Сложная задача — тот же цикл проверки',body:'№ 512 завершает основной набор технологической карты. Независимо от сюжета, используем цикл: модель → вычисление → единицы → обратная или смысловая проверка. Это защищает от правильной арифметики в неправильной модели.',visual:'verify',sourceExercise:'№ 512'},
{id:'l65-equation-transfer',kind:'practice',eyebrow:'Перенос',title:'Неизвестный делитель внутри модели',body:'1 512:x=27.',activity:{id:'l65-p18',type:'input',prompt:'Найди x.',answer:['56','x=56'],placeholder:'x',hint:'1512:27.',explanation:'x=56. Проверка: 1512:56=27.'},visual:'equation'},
{id:'l65-error-lab',kind:'model',eyebrow:'Ловушка',title:'Правильное число может быть неправильным ответом',body:'Если в задаче спрашивают производительность одного человека за день, нельзя оставить совместную производительность всей группы. Каждое число должно иметь подпись: страницы/день, кг, км/ч и т. п.',visual:'error'},
{id:'l65-error-choice',kind:'quiz',eyebrow:'Диагностика',title:'Проверяем размерность',body:'В № 483 после 288:4 получаем 72.',activity:{id:'l65-p19',type:'choice',prompt:'Какая подпись корректна?',options:['72 страницы/день для трёх операторов','72 оператора','72 дня','72 страницы за 7 дней одного оператора'],answer:'72 страницы/день для трёх операторов',hint:'Мы делили объём работы на число дней.',explanation:'Получили совместную дневную производительность.'},visual:'error'},
{id:'l65-519-model',kind:'model',eyebrow:'Повторение · № 519',title:'Конверты: логика множеств плюс арифметика',body:'Купили розовые и зелёные конверты. Розовых 18. С марками 12, из них 8 розовых. Все зелёные конверты были с марками. Сначала найдём число зелёных конвертов.',visual:'map',sourceExercise:'№ 519'},
{id:'l65-519-green',kind:'practice',eyebrow:'№ 519 · шаг 1',title:'Сколько зелёных конвертов?',body:'Из 12 конвертов с марками 8 розовых; все зелёные входят в эти 12.',activity:{id:'l65-p20',type:'input',prompt:'Сколько зелёных конвертов?',answer:['4','4 конверта','4 конвертов'],placeholder:'конвертов',hint:'12−8.',explanation:'12−8=4 зелёных конверта.'},visual:'map',sourceExercise:'№ 519'},
{id:'l65-519-total',kind:'practice',eyebrow:'№ 519 · шаг 2',title:'Собираем весь набор',body:'Розовых 18, зелёных 4.',activity:{id:'l65-p21',type:'input',prompt:'Сколько всего конвертов купили?',answer:['22','22 конверта','22 конвертов'],placeholder:'конвертов',hint:'18+4.',explanation:'18+4=22 конверта — совпадает с ответом учебника.'},visual:'verify',sourceExercise:'№ 519'},
{id:'l65-transfer',kind:'model',eyebrow:'Перенос навыка',title:'Пять вопросов перед последней строкой',body:'Что ищу? Что означает каждый промежуточный результат? В каких единицах он записан? Почему выбрано именно это действие? Каким независимым способом можно проверить ответ?',visual:'map'},
{id:'l65-challenge',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Сожми решение без потери смысла',body:'Четыре одинаково работающих наборщика за 6 дней набрали 720 страниц. Сколько страниц наберут три таких наборщика за 5 дней? Попробуй решить как цепочкой действий, так и через производительность одного наборщика.',note:'Один наборщик за день: 720:6:4=30 страниц; трое за 5 дней: 30·3·5=450 страниц.',visual:'challenge'},
{id:'l65-checkpoint',kind:'model',eyebrow:'Контроль понимания',title:'Сильный алгоритм смешанной задачи',body:'1) Прочитать вопрос. 2) Построить величины и связи. 3) Выполнять действия по смыслу, а не по словам. 4) Подписывать промежуточные результаты. 5) Проверить деление умножением, уравнение подстановкой, текстовую задачу — возвратом к условию.',visual:'verify'},
{id:'l65-summary',kind:'summary',eyebrow:'Итог урока',title:'Деление встроено в общую систему действий',body:'Ты закрепил деление, обратные связи компонентов, уравнения, порядок действий и многошаговые текстовые модели. Отдельно разобраны производительность № 483, контрольные результаты № 461 (2) и № 501, а также повторение № 519. Дальше — обязательная практика: 20 заданий и 50 ответов.',note:'После практики и рефлексии урок считается завершённым.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){
 const map:Record<VisualKind,[string,string,string]>={mission:['данные','→ план','→ проверка'],map:['что известно?','какая связь?','что ищем?'],division:['делимое','÷ делитель','частное'],equation:['роль x','обратное действие','подстановка'],work:['общая работа','за 1 день','на 1 человека'],expression:['структура','порядок','прикидка'],mass:['части','отношения','общая сумма'],verify:['ответ','обратная проверка','✓'],error:['число','единицы?','смысл?'],challenge:['2 способа','один результат','450'],final:['36 этапов','21 проверка','20×50']};
 const [a,b,c]=map[kind];return <div className="division-visual" data-division-mixed-visual={kind}><div className="division-check"><span>{a}</span><i>→</i><strong>{b}</strong><i>→</i><span>{c}</span></div></div>;
}
function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyFiveStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function DivisionMixedPracticePlayer(){
 const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyFiveStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyFiveStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==65||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyFiveStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
 function next(){if(!canContinue||saved.stageIndex>=lessonSixtyFiveStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player division-mixed-practice-player" data-lesson-number="65" data-source-reference="Мерзляк § 18 · технологическая карта урока 65 · № 461 (2), 483, 491 (3-4), 499, 501, 512 · повторение № 519" data-source-exercise-range="461,483,491,499,501,512,519"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyFiveStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyFiveStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyFiveStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
