import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'plan'|'meeting'|'timeline'|'catchup'|'units'|'rate'|'schedule'|'check'|'error'|'challenge'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-63-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyThreeStages:Stage[]=[
{id:'l63-mission',kind:'story',eyebrow:'Урок 63 · § 18 · задачи',title:'Текстовая задача — это модель, а не угадывание действия',body:'Сегодня деление работает внутри задач. Сначала переводим текст в величины и связи, затем строим короткий арифметический план и только после этого считаем.',note:'Технологическая карта урока 63: № 454, 472, 474, 476, 478, 480. Цель — решать текстовые задачи арифметическим способом.',visual:'mission'},
{id:'l63-plan',kind:'model',eyebrow:'Главный алгоритм',title:'Четыре шага сильного решения',body:'1) Что известно? 2) Что нужно найти? 3) Какой промежуточный вопрос открывает путь к ответу? 4) Каким обратным действием проверить результат?',note:'Единицы измерения записываем рядом с каждым промежуточным результатом.',visual:'plan'},
{id:'l63-plan-check',kind:'quiz',eyebrow:'Модель',title:'Сначала промежуточный вопрос',body:'Два объекта идут навстречу. Известны расстояние и время до встречи, скорость одного объекта.',activity:{id:'l63-p1',type:'choice',prompt:'Что разумнее всего найти первым?',options:['Скорость сближения','Путь первого за один час','Разность расстояний','Количество остановок'],answer:'Скорость сближения',hint:'При встречном движении расстояние закрывается общей скоростью.',explanation:'Расстояние : время = скорость сближения. После этого можно вычесть известную скорость.'},visual:'meeting'},
{id:'l63-454-total',kind:'practice',eyebrow:'№ 454',title:'Находим общую скорость',body:'Два автомобиля выехали навстречу из городов на расстоянии 588 км и встретились через 6 ч.',activity:{id:'l63-p2',type:'input',prompt:'Какова скорость сближения?',answer:['98','98 км/ч'],placeholder:'км/ч',hint:'588 раздели на 6.',explanation:'588:6=98 км/ч — вместе автомобили сокращали расстояние на 98 км каждый час.'},visual:'meeting',sourceExercise:'№ 454'},
{id:'l63-454-second',kind:'practice',eyebrow:'№ 454',title:'От общей скорости — к скорости второго',body:'Скорость одного автомобиля 46 км/ч, скорость сближения 98 км/ч.',activity:{id:'l63-p3',type:'input',prompt:'Найди скорость второго автомобиля.',answer:['52','52 км/ч'],placeholder:'км/ч',hint:'При встречном движении скорости складываются.',explanation:'98−46=52 км/ч. Проверка: (46+52)·6=588.'},visual:'check',sourceExercise:'№ 454'},
{id:'l63-delay-model',kind:'model',eyebrow:'Поздний старт',title:'Если стартовали в разное время — у каждого своё время движения',body:'Нельзя подставлять одно и то же время обоим участникам. Удобно сначала перевести время суток в длительность каждого пути.',note:'Именно это является ключом к № 472.',visual:'timeline'},
{id:'l63-472-ilya-time',kind:'practice',eyebrow:'№ 472',title:'Сколько ехал первый?',body:'Илья выехал в 6:00 и был догнан в 14:00.',activity:{id:'l63-p4',type:'input',prompt:'Сколько часов ехал Илья?',answer:['8','8 ч','8 часов'],placeholder:'ч',hint:'14−6.',explanation:'От 6:00 до 14:00 прошло 8 часов.'},visual:'timeline',sourceExercise:'№ 472'},
{id:'l63-472-distance',kind:'practice',eyebrow:'№ 472',title:'Общий путь к моменту встречи',body:'Илья ехал 8 ч со скоростью 9 км/ч.',activity:{id:'l63-p5',type:'input',prompt:'Какое расстояние он прошёл?',answer:['72','72 км'],placeholder:'км',hint:'Путь = скорость · время.',explanation:'9·8=72 км.'},visual:'rate',sourceExercise:'№ 472'},
{id:'l63-472-alesha-time',kind:'practice',eyebrow:'№ 472',title:'Время второго участника',body:'Алёша выехал в 8:00 и догнал Илью в 14:00.',activity:{id:'l63-p6',type:'input',prompt:'Сколько часов был в пути Алёша?',answer:['6','6 ч','6 часов'],placeholder:'ч',hint:'14−8.',explanation:'Алёша ехал 6 часов.'},visual:'timeline',sourceExercise:'№ 472'},
{id:'l63-472-speed',kind:'practice',eyebrow:'№ 472',title:'Деление завершает модель',body:'К моменту встречи Алёша прошёл те же 72 км за 6 ч.',activity:{id:'l63-p7',type:'input',prompt:'Найди скорость Алёши.',answer:['12','12 км/ч'],placeholder:'км/ч',hint:'Скорость = путь : время.',explanation:'72:6=12 км/ч.'},visual:'check',sourceExercise:'№ 472'},
{id:'l63-catchup-model',kind:'model',eyebrow:'Движение вдогонку',title:'Разность скоростей закрывает начальный отрыв',body:'Если оба движутся в одном направлении, более быстрый объект сокращает отрыв со скоростью vбыстр−vмедл.',note:'Можно решать либо через разность скоростей, либо через пути к моменту встречи. Полезно уметь оба способа.',visual:'catchup'},
{id:'l63-474-first-path',kind:'practice',eyebrow:'№ 474',title:'Путь впереди идущего поезда',body:'Первый поезд идёт 4 ч со скоростью 58 км/ч.',activity:{id:'l63-p8',type:'input',prompt:'Какой путь прошёл первый поезд?',answer:['232','232 км'],placeholder:'км',hint:'58·4.',explanation:'58·4=232 км.'},visual:'catchup',sourceExercise:'№ 474'},
{id:'l63-474-second-path',kind:'practice',eyebrow:'№ 474',title:'Быстрый поезд должен пройти ещё начальный отрыв',body:'Станции находятся на расстоянии 24 км. За 4 ч быстрый поезд догнал первый.',activity:{id:'l63-p9',type:'input',prompt:'Сколько километров прошёл быстрый поезд?',answer:['256','256 км'],placeholder:'км',hint:'К 232 км добавь начальный отрыв 24 км.',explanation:'232+24=256 км.'},visual:'catchup',sourceExercise:'№ 474'},
{id:'l63-474-speed',kind:'practice',eyebrow:'№ 474',title:'Скорость второго поезда',body:'Быстрый поезд прошёл 256 км за 4 ч.',activity:{id:'l63-p10',type:'input',prompt:'Найди его скорость.',answer:['64','64 км/ч'],placeholder:'км/ч',hint:'256:4.',explanation:'256:4=64 км/ч.'},visual:'check',sourceExercise:'№ 474'},
{id:'l63-474-alt',kind:'quiz',eyebrow:'№ 474 · второй способ',title:'Проверяем через скорость сближения',body:'Скорости поездов 64 и 58 км/ч, начальный отрыв 24 км.',activity:{id:'l63-p11',type:'input',prompt:'На сколько километров в час сокращался отрыв?',answer:['6','6 км/ч'],placeholder:'км/ч',hint:'64−58.',explanation:'64−58=6 км/ч; 24:6=4 ч, что совпадает с условием.'},visual:'check',sourceExercise:'№ 474'},
{id:'l63-units',kind:'model',eyebrow:'Единицы',title:'Одинаковые величины должны быть в совместимых единицах',body:'Перед делением проверь размерность: км:ч даёт км/ч, м:(м/мин) даёт минуты, см/мин нужно перевести в м/мин, если путь задан в метрах.',note:'Ошибки в единицах часто дают красивое, но бессмысленное число.',visual:'units'},
{id:'l63-476-relative',kind:'practice',eyebrow:'№ 476',title:'Скорость сближения вдогонку',body:'Портос движется со скоростью 1 лье/ч, д’Артаньян — 3 лье/ч.',activity:{id:'l63-p12',type:'input',prompt:'Какова скорость сближения?',answer:['2','2 лье/ч'],placeholder:'лье/ч',hint:'Более быстрая скорость минус более медленная.',explanation:'3−1=2 лье/ч.'},visual:'catchup',sourceExercise:'№ 476'},
{id:'l63-476-time',kind:'practice',eyebrow:'№ 476',title:'Время догоняния',body:'Начальный отрыв равен 12 лье, он сокращается на 2 лье каждый час.',activity:{id:'l63-p13',type:'input',prompt:'Через сколько часов произойдёт встреча?',answer:['6','6 ч','6 часов'],placeholder:'ч',hint:'Время = отрыв : скорость сближения.',explanation:'12:2=6 ч.'},visual:'check',sourceExercise:'№ 476'},
{id:'l63-rate-model',kind:'model',eyebrow:'Постоянная скорость',title:'Один и тот же темп переносим на другое время',body:'Если скорость не меняется, сначала можно найти скорость по известному пути и времени, затем умножить её на новое время.',note:'Схема № 478: S1:t1=v, затем v·t2=S2.',visual:'rate'},
{id:'l63-478-speed',kind:'practice',eyebrow:'№ 478',title:'Скорость поезда',body:'Поезд прошёл 336 км за 4 ч.',activity:{id:'l63-p14',type:'input',prompt:'Какова его скорость?',answer:['84','84 км/ч'],placeholder:'км/ч',hint:'336:4.',explanation:'336:4=84 км/ч.'},visual:'rate',sourceExercise:'№ 478'},
{id:'l63-478-distance',kind:'practice',eyebrow:'№ 478',title:'Новый путь при той же скорости',body:'Поезд продолжает двигаться со скоростью 84 км/ч.',activity:{id:'l63-p15',type:'input',prompt:'Сколько километров он пройдёт за 7 ч?',answer:['588','588 км'],placeholder:'км',hint:'84·7.',explanation:'84·7=588 км.'},visual:'check',sourceExercise:'№ 478'},
{id:'l63-schedule',kind:'model',eyebrow:'Расписание',title:'В задачах на время счёт идёт назад от момента прибытия',body:'Сначала вычисли длительность пути, затем определи требуемое время прибытия и только потом вычти длительность пути.',note:'Если нужно прийти за 10 минут до 8:30, целевое прибытие — 8:20.',visual:'schedule'},
{id:'l63-480-speed',kind:'practice',eyebrow:'№ 480',title:'Переводим шаги в метры за минуту',body:'Буратино делает 120 шагов в минуту, средняя длина шага 40 см.',activity:{id:'l63-p16',type:'input',prompt:'Сколько метров он проходит за минуту?',answer:['48','48 м','48 м/мин'],placeholder:'м/мин',hint:'120·40=4800 см, затем переведи сантиметры в метры.',explanation:'4800 см=48 м, значит скорость 48 м/мин.'},visual:'units',sourceExercise:'№ 480'},
{id:'l63-480-time',kind:'practice',eyebrow:'№ 480',title:'Длительность дороги',body:'До школы 1 км 200 м, то есть 1200 м. Скорость 48 м/мин.',activity:{id:'l63-p17',type:'input',prompt:'Сколько минут занимает дорога?',answer:['25','25 мин','25 минут'],placeholder:'мин',hint:'1200:48.',explanation:'1200:48=25 минут.'},visual:'schedule',sourceExercise:'№ 480'},
{id:'l63-480-leave',kind:'practice',eyebrow:'№ 480',title:'Считаем время выхода',body:'Уроки начинаются в 8:30. Нужно быть в школе за 10 мин до начала, дорога занимает 25 мин.',activity:{id:'l63-p18',type:'input',prompt:'Во сколько надо выйти?',answer:['7:55','7 55','7ч55мин','7 ч 55 мин'],placeholder:'чч:мм',hint:'Цель — 8:20. Вычти 25 минут.',explanation:'8:20−25 мин=7:55.'},visual:'schedule',sourceExercise:'№ 480'},
{id:'l63-check-model',kind:'model',eyebrow:'Обратная проверка',title:'Проверяем не только арифметику, но и смысл',body:'Для скорости проверяем v·t=S. Для времени проверяем S:v=t. Для догоняния проверяем, что разность пройденных путей равна начальному отрыву.',note:'Хорошая проверка использует исходные данные задачи, а не повторяет тот же расчёт.',visual:'check'},
{id:'l63-check-choice',kind:'quiz',eyebrow:'Проверка',title:'Как проверить № 478?',body:'Получено 588 км за 7 ч при скорости 84 км/ч.',activity:{id:'l63-p19',type:'choice',prompt:'Какая проверка правильная?',options:['588:7=84','588+7=84','84:7=588','588−84=7'],answer:'588:7=84',hint:'Путь делим на время и должны вернуть скорость.',explanation:'588:7=84 км/ч — исходная скорость восстановлена.'},visual:'check'},
{id:'l63-error-model',kind:'model',eyebrow:'Антиошибка',title:'Самая опасная ошибка — правильное действие с неправильной величиной',body:'Например, в № 472 нельзя делить 72 км на 8 ч для скорости Алёши: 8 ч — время Ильи. Для Алёши нужно использовать его 6 часов.',note:'Подписывай, кому принадлежит каждое время и каждый путь.',visual:'error'},
{id:'l63-error-choice',kind:'quiz',eyebrow:'Диагностика ошибки',title:'Найди неверный шаг',body:'Ученик решает № 480: 120·40=4800 см; 4800 см=48 м; 1200:48=25 мин; 8:30−25 мин=8:05.',activity:{id:'l63-p20',type:'choice',prompt:'Что он забыл учесть?',options:['Нужно прийти на 10 минут раньше','Нужно умножить 1200 на 48','40 см равны 4 м','Скорость равна 120 м/мин'],answer:'Нужно прийти на 10 минут раньше',hint:'Целевое время прибытия не 8:30.',explanation:'Нужно прийти в 8:20, поэтому выйти следует в 7:55.'},visual:'error'},
{id:'l63-challenge',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Два способа должны дать один ответ',body:'Велосипедист стартовал на 30 км впереди со скоростью 12 км/ч. Второй едет следом со скоростью 18 км/ч.',activity:{id:'l63-p21',type:'input',prompt:'Через сколько часов второй догонит первого?',answer:['5','5 ч','5 часов'],placeholder:'ч',hint:'Отрыв сокращается на 18−12=6 км каждый час.',explanation:'30:(18−12)=30:6=5 ч. Проверка путями: 18·5−12·5=30.'},visual:'challenge'},
{id:'l63-transfer',kind:'model',eyebrow:'Перенос',title:'Сильная запись — это цепочка вопросов',body:'Вместо списка действий запиши смысл каждого шага: «сколько времени?», «какой путь?», «какова общая скорость?». Тогда даже длинная задача остаётся прозрачной.',note:'Если промежуточное число нельзя назвать словами и единицами, скорее всего модель построена плохо.',visual:'plan'},
{id:'l63-review',kind:'guided',eyebrow:'Систематизация',title:'Три базовые модели движения',body:'Навстречу: скорости складываются. Вдогонку: скорости вычитаются. Постоянная скорость: S=v·t, v=S:t, t=S:v.',note:'Определяй модель по направлению движения и роли неизвестного, а не по отдельным словам в условии.',visual:'rate'},
{id:'l63-independent',kind:'guided',eyebrow:'Самостоятельный план',title:'Не считай — сначала составь маршрут',body:'Автомобиль прошёл 420 км за 6 ч. Сколько он пройдёт за 9 ч при той же скорости? Сильный план: 420:6 — скорость; найденная скорость ·9 — новый путь.',note:'Перед вычислением проверь единицы каждого шага.',visual:'plan'},
{id:'l63-olympiad',kind:'challenge',eyebrow:'Повышенный уровень',title:'Когда два маршрута эквивалентны?',body:'Для догоняния можно либо найти разность скоростей и разделить начальный отрыв на неё, либо выразить оба пути за одно и то же время и сравнить их. Объясни, почему это одна и та же модель.',note:'Ключ: (v₂−v₁)t = v₂t−v₁t.',visual:'challenge'},
{id:'l63-reflection',kind:'story',eyebrow:'Перед практикой',title:'Проверь, что умеешь объяснить каждое действие',body:'Для любой задачи назови величину, которую находишь, её единицу и связь с предыдущим шагом. Это важнее механического набора вычислений.',note:'После этого — обязательная практика 20 заданий / 50 ответов.',visual:'check'},
{id:'l63-summary',kind:'summary',eyebrow:'Урок 63 · итог',title:'Деление стало частью арифметической модели текстовой задачи',body:'Ты прошёл задачи № 454, 472, 474, 476, 478 и 480: встречное движение, поздний старт, догоняние, постоянную скорость, единицы и расчёт времени выхода.',note:'Дальше обязательная практика: 20 задач и ровно 50 ответов. После неё сформулируй главный принцип решения текстовых задач своими словами.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){
 if(kind==='mission')return <div className="division-visual"><div className="division-final"><b>условие</b><b>модель</b><b>действия</b><b>ответ</b><b>проверка</b></div></div>;
 if(kind==='plan')return <div className="division-visual"><div className="division-written"><span><small>1</small><b>дано?</b></span><i>→</i><span><small>2</small><b>что найти?</b></span><i>→</i><span><small>3</small><b>план</b></span></div></div>;
 if(kind==='meeting')return <div className="division-visual"><div className="division-check"><span>588 км</span><i>÷ 6 ч</i><b>98 км/ч</b><i>−46</i><strong>52 км/ч</strong></div></div>;
 if(kind==='timeline')return <div className="division-visual"><div className="division-zeros"><span>6:00</span><i>→ 8 ч →</i><strong>14:00</strong><span>8:00</span><i>→ 6 ч →</i><strong>14:00</strong></div></div>;
 if(kind==='catchup')return <div className="division-visual"><div className="division-check"><span>отрыв S</span><i>÷</i><b>v₂−v₁</b><i>=</i><strong>время</strong></div></div>;
 if(kind==='units')return <div className="division-visual"><div className="division-zeros"><span>4800 см</span><i>=</i><strong>48 м</strong><span>1200 м</span><i>÷48 м/мин</i><strong>25 мин</strong></div></div>;
 if(kind==='rate')return <div className="division-visual"><div className="division-check"><span>S</span><i>=</i><b>v·t</b><i>↔</i><strong>v=S:t · t=S:v</strong></div></div>;
 if(kind==='schedule')return <div className="division-visual"><div className="division-written"><span><small>цель</small><b>8:20</b></span><i>−</i><span><small>дорога</small><b>25 мин</b></span><i>=</i><span><small>выход</small><b>7:55</b></span></div></div>;
 if(kind==='error')return <div className="division-visual"><div className="division-check"><span>число</span><i>+</i><b>единица</b><i>+</i><strong>смысл ✓</strong></div></div>;
 if(kind==='challenge')return <div className="division-visual"><div className="division-check"><span>30 км</span><i>÷</i><b>18−12</b><i>=</i><strong>5 ч</strong></div></div>;
 if(kind==='final')return <div className="division-visual"><div className="division-final"><b>№454</b><b>№472</b><b>№474</b><b>№476</b><b>№478</b><b>№480</b></div></div>;
 return <div className="division-visual"><div className="division-check"><span>ответ</span><i>→</i><strong>обратная проверка ✓</strong></div></div>;
}
function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyThreeStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function DivisionTextProblemsPlayer(){
 const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyThreeStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyThreeStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==63||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyThreeStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
 function next(){if(!canContinue||saved.stageIndex>=lessonSixtyThreeStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player division-text-problems-player" data-lesson-number="63" data-source-reference="Мерзляк § 18 · технологическая карта урока 63 · № 454, 472, 474, 476, 478, 480" data-source-exercise-range="454,472-480"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyThreeStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyThreeStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyThreeStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
