import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-36-progress-v1';
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g,'').replace(/−/g,'-').replace(/×|·/g,'*').replace(',', '.');

export const lessonThirtySixStages:Stage[]=[
  {id:'l36-mission',kind:'story',eyebrow:'Урок 36 · § 10 · итог',title:'Финал темы: решение должно быть объяснимым',body:'В сильном решении уравнения важны не только цифры. Мы умеем назвать роль неизвестного, обосновать выбранное действие, проверить корень и связать равенство с условием задачи.',note:'Маршрут: упрости → определи роль x → реши → проверь → объясни смысл.'},
  {id:'l36-map',kind:'model',eyebrow:'Карта темы',title:'Три базовые роли неизвестного остаются фундаментом',body:'x + a = b: неизвестное слагаемое. x − a = b: неизвестное уменьшаемое. a − x = b: неизвестное вычитаемое. Даже в длинной записи после упрощения мы возвращаемся к одной из этих моделей.'},
  {id:'l36-mixed-model',kind:'model',eyebrow:'Смешанные записи',title:'Числовое выражение сначала превращаем в одно число',body:'Например, x + 37 = 100 − 28. Сначала 100 − 28 = 72. Получаем x + 37 = 72, значит x = 35. После этого проверяем исходную запись: 35 + 37 = 100 − 28.'},
  {id:'l36-practice1',kind:'practice',eyebrow:'Практика · 1/10',title:'Неизвестное слагаемое',body:'Сначала упрости известную часть.',activity:{id:'l36-p1',type:'input',prompt:'Реши уравнение x + 37 = 100 − 28.',answer:'35',placeholder:'x =',hint:'100 − 28 = 72, затем найди неизвестное слагаемое.',explanation:'100 − 28 = 72; x = 72 − 37 = 35. Проверка: 35 + 37 = 72.'}},
  {id:'l36-practice2',kind:'practice',eyebrow:'Практика · 2/10',title:'Неизвестное уменьшаемое',body:'Определи роль x до выбора действия.',activity:{id:'l36-p2',type:'input',prompt:'Реши уравнение x − 24 = 48 + 12.',answer:'84',placeholder:'x =',hint:'48 + 12 = 60; x — неизвестное уменьшаемое.',explanation:'x − 24 = 60; x = 60 + 24 = 84. Проверка: 84 − 24 = 60.'}},
  {id:'l36-practice3',kind:'practice',eyebrow:'Практика · 3/10',title:'Неизвестное вычитаемое',body:'Здесь правило другое.',activity:{id:'l36-p3',type:'input',prompt:'Реши уравнение 140 − x = 90 − 18.',answer:'68',placeholder:'x =',hint:'90 − 18 = 72; неизвестное вычитаемое равно уменьшаемое минус разность.',explanation:'140 − x = 72; x = 140 − 72 = 68. Проверка: 140 − 68 = 72.'}},
  {id:'l36-verify-model',kind:'model',eyebrow:'Доказательство',title:'Проверка должна возвращаться к исходной записи',body:'Если мы упрощали части уравнения, в финале полезно подставить корень именно в исходное равенство. Так одновременно проверяются и промежуточные вычисления, и правило поиска неизвестного.'},
  {id:'l36-practice4',kind:'guided',eyebrow:'Практика · 4/10',title:'Проверка готового корня',body:'Сравни значения обеих частей.',activity:{id:'l36-p4',type:'choice',prompt:'Является ли x = 56 корнем уравнения x + 24 = 100 − 20?',options:['Да','Нет'],answer:'Да',hint:'56 + 24 = ? и 100 − 20 = ?',explanation:'Обе части равны 80, поэтому 56 — корень уравнения.'}},
  {id:'l36-error-model',kind:'model',eyebrow:'Диагностика',title:'Ошибка часто начинается с неверно названной роли x',body:'В x − 18 = 42 x — уменьшаемое. Поэтому x = 42 + 18, а не 42 − 18. Простая привычка вслух назвать компонент резко уменьшает количество случайных ошибок.'},
  {id:'l36-practice5',kind:'guided',eyebrow:'Практика · 5/10',title:'Исправь чужое решение',body:'Найди причину, а не только новый ответ.',activity:{id:'l36-p5',type:'choice',prompt:'Ученик решил x − 18 = 42 так: x = 42 − 18 = 24. Что нужно исправить?',options:['Нужно сложить 42 и 18','Нужно разделить 42 на 18','Нужно вычесть 42 из 18','Решение верное'],answer:'Нужно сложить 42 и 18',hint:'x — неизвестное уменьшаемое.',explanation:'Неизвестное уменьшаемое равно разность плюс вычитаемое: x = 42 + 18 = 60.'}},
  {id:'l36-text-model',kind:'model',eyebrow:'Задача → уравнение',title:'Уравнение фиксирует историю изменения величины',body:'«Было неизвестно сколько. Добавили 17, стало 65» превращается в x + 17 = 65. «Было неизвестно сколько. Убрали 29, осталось 46» превращается в x − 29 = 46.'},
  {id:'l36-practice6',kind:'practice',eyebrow:'Практика · 6/10',title:'Выбери модель задачи',body:'Сохрани порядок событий.',activity:{id:'l36-p6',type:'choice',prompt:'Было несколько карточек. Добавили 17 карточек, и стало 65. Какое уравнение описывает задачу?',options:['x + 17 = 65','x − 17 = 65','17 − x = 65','65 + 17 = x'],answer:'x + 17 = 65',hint:'Количество увеличилось на 17.',explanation:'Было x, прибавили 17, получили 65: x + 17 = 65.'}},
  {id:'l36-practice7',kind:'practice',eyebrow:'Практика · 7/10',title:'Реши текстовую задачу через уравнение',body:'Сначала составь модель мысленно.',activity:{id:'l36-p7',type:'input',prompt:'В ящике было несколько деталей. 29 деталей использовали, после чего осталось 46. Сколько деталей было сначала?',answer:'75',placeholder:'Ответ',hint:'x − 29 = 46.',explanation:'x = 46 + 29 = 75. Проверка: 75 − 29 = 46.'}},
  {id:'l36-reverse-model',kind:'model',eyebrow:'Уравнение → задача',title:'Можно двигаться и в обратную сторону',body:'Запись 80 − x = 35 можно прочитать так: «Из 80 вычли неизвестное число и получили 35». Умение переводить уравнение обратно в слова показывает, что смысл компонентов действительно понят.'},
  {id:'l36-practice8',kind:'practice',eyebrow:'Практика · 8/10',title:'Восстанови условие',body:'Выбери историю, которая точно соответствует записи.',activity:{id:'l36-p8',type:'choice',prompt:'Какое условие соответствует уравнению 80 − x = 35?',options:['Из 80 вычли неизвестное число и получили 35','К неизвестному числу прибавили 80 и получили 35','Из неизвестного числа вычли 80 и получили 35','К 35 прибавили неизвестное число и получили 80'],answer:'Из 80 вычли неизвестное число и получили 35',hint:'Сохрани порядок чисел и знак действия.',explanation:'80 — уменьшаемое, x — вычитаемое, 35 — разность.'}},
  {id:'l36-same-root-model',kind:'model',eyebrow:'Связи',title:'Один корень может удовлетворять разным уравнениям',body:'Если x + 14 = 50, то x = 36. Проверяем x − 9 = 27: 36 − 9 = 27. Значит эти два уравнения имеют один и тот же корень.'},
  {id:'l36-practice9',kind:'practice',eyebrow:'Практика · 9/10',title:'Найди пару с одним корнем',body:'Реши одно уравнение каждой пары и быстро проверь второе.',activity:{id:'l36-p9',type:'choice',prompt:'Какая пара имеет один и тот же корень?',options:['x + 14 = 50 и x − 9 = 27','x + 14 = 50 и 70 − x = 20','x − 10 = 30 и x + 5 = 50','90 − x = 40 и x − 8 = 35'],answer:'x + 14 = 50 и x − 9 = 27',hint:'Первое уравнение первой пары даёт x = 36.',explanation:'36 + 14 = 50 и 36 − 9 = 27.'}},
  {id:'l36-estimate-model',kind:'model',eyebrow:'Оценка',title:'Размер корня можно предсказать ещё до вычисления',body:'Если x − 45 = 100, x должен быть больше 100. Если x + 45 = 100, x меньше 100. Если 145 − x = 100, x меньше 145. Такая оценка ловит ответы с неверным знаком действия.'},
  {id:'l36-practice10',kind:'practice',eyebrow:'Практика · 10/10',title:'Оцени корень',body:'Точный ответ пока не нужен.',activity:{id:'l36-p10',type:'choice',prompt:'В каком уравнении корень обязательно больше 100?',options:['x − 45 = 100','x + 45 = 100','145 − x = 100','x + 100 = 145'],answer:'x − 45 = 100',hint:'Из x вычли 45, и всё равно осталось 100.',explanation:'x = 145, поэтому корень больше 100.'}},
  {id:'l36-control-intro',kind:'model',eyebrow:'Итоговый мини-контроль',title:'Теперь работаем без опоры на предыдущий пример',body:'Пять заданий проверят всю тему: смешанную запись, три роли неизвестного, текстовую модель и проверку корня.'},
  {id:'l36-quiz1',kind:'quiz',eyebrow:'Контроль · 1/6',title:'Смешанное уравнение',body:'Сначала упрости известную часть.',activity:{id:'l36-q1',type:'input',prompt:'x + 28 = 96 − 18. Найди x.',answer:'50',placeholder:'x =',hint:'96 − 18 = 78.',explanation:'x + 28 = 78; x = 50. Проверка: 50 + 28 = 78.'}},
  {id:'l36-quiz2',kind:'quiz',eyebrow:'Контроль · 2/6',title:'Неизвестное уменьшаемое',body:'Назови компонент до действия.',activity:{id:'l36-q2',type:'input',prompt:'x − 39 = 25 + 16. Найди x.',answer:'80',placeholder:'x =',hint:'25 + 16 = 41.',explanation:'x − 39 = 41; x = 80. Проверка: 80 − 39 = 41.'}},
  {id:'l36-quiz3',kind:'quiz',eyebrow:'Контроль · 3/6',title:'Неизвестное вычитаемое',body:'Сначала вычисли правую часть.',activity:{id:'l36-q3',type:'input',prompt:'180 − x = 75 + 35. Найди x.',answer:'70',placeholder:'x =',hint:'75 + 35 = 110.',explanation:'180 − x = 110; x = 70. Проверка: 180 − 70 = 110.'}},
  {id:'l36-quiz4',kind:'quiz',eyebrow:'Контроль · 4/6',title:'Текстовая модель',body:'Определи, что было неизвестно.',activity:{id:'l36-q4',type:'choice',prompt:'После того как к неизвестному числу прибавили 26, получили 90. Какое уравнение соответствует условию?',options:['x + 26 = 90','x − 26 = 90','26 − x = 90','90 + 26 = x'],answer:'x + 26 = 90',hint:'К x прибавляют 26.',explanation:'Условие прямо задаёт x + 26 = 90.'}},
  {id:'l36-quiz5',kind:'quiz',eyebrow:'Контроль · 5/6',title:'Проверка корня',body:'Подставь число в исходное уравнение.',activity:{id:'l36-q5',type:'choice',prompt:'Является ли x = 72 корнем уравнения 130 − x = 80 − 22?',options:['Да','Нет'],answer:'Да',hint:'130 − 72 = ? и 80 − 22 = ?',explanation:'Обе части равны 58, значит 72 — корень.'}},
  {id:'l36-quiz6',kind:'quiz',eyebrow:'Контроль · 6/6',title:'Диагностика ошибки',body:'Проверь роль неизвестного.',activity:{id:'l36-q6',type:'choice',prompt:'Ученик решает 120 − x = 47 так: x = 120 + 47 = 167. В чём ошибка?',options:['Неизвестное вычитаемое нужно найти как 120 − 47','Нужно сложить 120 и 47 ещё раз','Нужно из 47 вычесть 120','Ошибки нет'],answer:'Неизвестное вычитаемое нужно найти как 120 − 47',hint:'x — вычитаемое.',explanation:'x = 120 − 47 = 73. Проверка: 120 − 73 = 47.'}},
  {id:'l36-challenge1',kind:'challenge',eyebrow:'Challenge · 1/2',title:'Одно число — два условия',body:'Найди число по одному равенству и обязательно проверь второе.',activity:{id:'l36-c1',type:'input',prompt:'Найди x, если одновременно x + 18 = 70 и 100 − x = 48.',answer:'52',placeholder:'x =',hint:'Первое уравнение быстро даёт x.',explanation:'x = 70 − 18 = 52; проверка второго: 100 − 52 = 48.'}},
  {id:'l36-challenge2',kind:'challenge',eyebrow:'Challenge · 2/2',title:'Один корень в двух разных моделях',body:'Работай через проверку, а не через два длинных решения.',activity:{id:'l36-c2',type:'choice',prompt:'Какое число одновременно является корнем x − 12 = 45 и 80 − x = 23?',options:['55','57','58','68'],answer:'57',hint:'Из первого уравнения x = 45 + 12.',explanation:'x = 57; 57 − 12 = 45 и 80 − 57 = 23.'}},
  {id:'l36-mastery',kind:'model',eyebrow:'Мастерство § 10',title:'Ты умеешь не только решать, но и объяснять',body:'Полное понимание уравнений — это пять навыков вместе: увидеть структуру, назвать роль неизвестного, выбрать действие, проверить корень и перевести между текстом и математической записью.'},
  {id:'l36-summary',kind:'summary',eyebrow:'§ 10 завершён',title:'Уравнение стало инструментом, а не загадкой',body:'Ты прошёл весь цикл темы: от понятия корня до смешанных уравнений, текстовых моделей, диагностики ошибок и задач с двумя условиями.',note:'Следующая тема — § 11 «Угол. Обозначение углов».'},
];

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirtySixStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function EquationMasteryPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonThirtySixStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==36||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonThirtySixStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonThirtySixStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player equation-mastery-player" aria-label="Урок 36. Итог темы Уравнение"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric"/></div>}<button type="button" className="check-button" disabled={!response.trim()} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><b>§ 10 завершён</b><span>Корень · компоненты действий · текстовые модели · проверка · диагностика ошибок</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonThirtySixStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonThirtySixStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonThirtySixStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}
