import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './controlWork.css';
import {loadLessonTiming} from './lessonTiming';
import {exactDecimalEquals} from './exactDecimal';
import {lessonOneHundredSeventyFiveProgressKey,lessonOneHundredSeventyFiveResponseCount,lessonOneHundredSeventyFiveTasks,type LessonOneHundredSeventyFiveDomain,type LessonOneHundredSeventyFiveField,type LessonOneHundredSeventyFiveTask} from './data/lessonOneHundredSeventyFiveControl';

type Stage={id:string;kind:'intro'|'task'|'submit'|'summary';eyebrow:string;title:string;body:string;task?:LessonOneHundredSeventyFiveTask};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;submitted:boolean;submittedResponses?:Record<string,string>;completedAt?:string};
type Jump={lessonNumber?:number;stageIndex?:number};
const COMPLETION_KEY='mathnikita:lesson-complete:175';
const domains:LessonOneHundredSeventyFiveDomain[]=['Натуральные числа','Обыкновенные дроби','Десятичные дроби','Проценты и среднее','Выражения и уравнения','Геометрия','Комбинаторика','Текстовые задачи'];
const responseKey=(task:LessonOneHundredSeventyFiveTask,field:LessonOneHundredSeventyFiveField)=>`${task.id}:${field.id}`;
const correct=(value:string,field:LessonOneHundredSeventyFiveField)=>exactDecimalEquals(value,field.answer);
const stages:Stage[]=[
  {id:'l175-intro',kind:'intro',eyebrow:'Урок 175 · итоговая контрольная',title:'Финальная работа по курсу математики 5 класса',body:'20 заданий, 50 проверяемых ответов, 50 минут. Во время первичной попытки ответы, темы и решения скрыты. Заполни все поля, затем сдай работу один раз.'},
  ...lessonOneHundredSeventyFiveTasks.map((task,i)=>({id:`l175-task-${String(i+1).padStart(2,'0')}`,kind:'task' as const,eyebrow:`Итоговая работа · ${i+1} из 20`,title:task.title,body:task.prompt,task})),
  {id:'l175-submit',kind:'submit',eyebrow:'Сдача работы',title:'Проверь, что заполнены все ответы',body:'После нажатия «Сдать итоговую работу» первичный результат фиксируется. Изменить его можно только новым полным прохождением.'},
  {id:'l175-summary',kind:'summary',eyebrow:'Курс завершён',title:'Результат итоговой контрольной',body:'Первичный результат сохранён. Можно просмотреть задания и разбор ошибок; исходный балл при этом не изменяется.'}
];
export const lessonOneHundredSeventyFiveStageCount=stages.length;
function load():Saved{try{const raw=localStorage.getItem(lessonOneHundredSeventyFiveProgressKey);if(!raw)return{version:1,stageIndex:0,responses:{},submitted:false};const p=JSON.parse(raw) as Saved;return p?.version===1?{version:1,stageIndex:Math.max(0,Math.min(p.stageIndex,stages.length-1)),responses:p.responses??{},submitted:Boolean(p.submitted),submittedResponses:p.submittedResponses,completedAt:p.completedAt}:{version:1,stageIndex:0,responses:{},submitted:false}}catch{return{version:1,stageIndex:0,responses:{},submitted:false}}}

export function FinalCourseControlPlayer(){
  const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState(initial.responses);const[submitted,setSubmitted]=useState(initial.submitted);const[submittedResponses,setSubmittedResponses]=useState<Record<string,string>|undefined>(initial.submittedResponses);const[completedAt,setCompletedAt]=useState<string|undefined>(initial.completedAt);const stage=stages[stageIndex];const task=stage.task;const baseline=submittedResponses??{};
  const answeredCount=lessonOneHundredSeventyFiveTasks.reduce((sum,item)=>sum+item.fields.filter(field=>Boolean(responses[responseKey(item,field)]?.trim())).length,0);
  const scoreByDomain=domains.map(domain=>{let total=0,score=0;for(const item of lessonOneHundredSeventyFiveTasks.filter(t=>t.domain===domain))for(const field of item.fields){total++;if(correct(baseline[responseKey(item,field)]??'',field))score++;}return{domain,total,score};});
  const score=scoreByDomain.reduce((sum,item)=>sum+item.score,0);const percent=Math.round(score/lessonOneHundredSeventyFiveResponseCount*100);const grade=score>=45?'5':score>=38?'4':score>=30?'3':'нужно повторить';
  useEffect(()=>{localStorage.setItem(lessonOneHundredSeventyFiveProgressKey,JSON.stringify({version:1,stageIndex,responses,submitted,submittedResponses,completedAt} satisfies Saved))},[stageIndex,responses,submitted,submittedResponses,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const d=(event as CustomEvent<Jump>).detail;if(d?.lessonNumber!==175||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const move=(index:number)=>{setStageIndex(Math.max(0,Math.min(index,stages.length-1)));window.scrollTo({top:0,behavior:'smooth'})};
  const stageComplete=!task||task.fields.every(field=>Boolean(responses[responseKey(task,field)]?.trim()));
  const submit=()=>{if(submitted||answeredCount!==lessonOneHundredSeventyFiveResponseCount)return;const now=new Date().toISOString();const snapshot={...responses};const activeSeconds=Math.round(loadLessonTiming(175).activeSeconds);setSubmittedResponses(snapshot);setSubmitted(true);setCompletedAt(now);localStorage.setItem(COMPLETION_KEY,JSON.stringify({completedAt:now,activeSeconds,finalControl:true}));window.dispatchEvent(new CustomEvent('mathnikita-lesson-completed',{detail:{lessonNumber:175,completedAt:now,activeSeconds}}));move(stages.length-1)};
  const reset=()=>{localStorage.removeItem(lessonOneHundredSeventyFiveProgressKey);localStorage.removeItem(COMPLETION_KEY);setResponses({});setSubmittedResponses(undefined);setSubmitted(false);setCompletedAt(undefined);setStageIndex(0)};
  return <main className="control-work-page final-course-control" data-control-work="final" data-lesson-number="175" data-control-field-count={lessonOneHundredSeventyFiveResponseCount}><section className="lesson-player-shell"><div className="control-work-status"><div><span>Итоговая контрольная работа</span><b>{submitted?`Первичный балл ${score}/50`:`Заполнено ${answeredCount}/50`}</b></div><div className="control-progress"><i style={{width:`${((stageIndex+1)/stages.length)*100}%`}}/></div></div><article className={`interactive-stage control-stage ${stage.kind==='summary'?'control-result-stage':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p></div>{stage.kind==='intro'?<div className="control-rules"><b>Правила первичной попытки</b><ul><li>калькулятор и подсказки не используются;</li><li>можно возвращаться назад и менять ответы до сдачи;</li><li>проверка правильности появляется только после сдачи;</li><li>первичный результат фиксируется и завершает курс.</li></ul></div>:null}{task?<div className="activity-area"><div className="answer-grid">{task.fields.map(field=>{const key=responseKey(task,field);const isCorrect=submitted&&correct(baseline[key]??'',field);return <label className="inline-answer" key={field.id}><span>{field.label}</span><input value={responses[key]??''} disabled={submitted} placeholder={field.placeholder} inputMode="decimal" onChange={event=>!submitted&&setResponses(p=>({...p,[key]:event.target.value}))}/>{submitted?<small className={isCorrect?'control-correct':'control-wrong'}>{isCorrect?'Верно':`Ответ: ${field.answer}`}</small>:null}</label>})}</div>{submitted?<p className="control-explanation">{task.explanation}</p>:null}</div>:null}{stage.kind==='submit'?<div className="control-submit-card"><b>Заполнено {answeredCount} из 50</b><button type="button" disabled={answeredCount!==50||submitted} onClick={submit}>Сдать итоговую работу</button></div>:null}{stage.kind==='summary'&&submitted?<div className="control-submit-card control-result-card"><b>Первичный результат: {score}/50 · {percent}% · оценка {grade}</b><span>Курс из 175 уроков завершён.</span>{scoreByDomain.map(item=><span key={item.domain} data-domain={item.domain}>{item.domain}: {item.score} из {item.total}</span>)}<button type="button" onClick={reset}>Пройти итоговую заново</button></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по итоговой контрольной"><button type="button" onClick={()=>move(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(stageIndex+1)} disabled={stageIndex===stages.length-1||stage.kind==='task'&&!stageComplete||stage.kind==='submit'}>Дальше →</button></nav></section></main>;
}
