import type {ReactNode} from 'react';
import type {LessonOpeningData} from './LessonOpening';
import {lateOpeningForLesson as baseOpeningForLesson,lateRuntimeForLesson as baseRuntimeForLesson} from './LateLessonRegistryBase';
import {lessonOneHundredFiftyThreeOpening} from './LessonOneHundredFiftyThreeOpening';
import {InversePercentFinalePlayer} from './InversePercentFinalePlayer';
import {lessonOneHundredFiftyFourOpening} from './LessonOneHundredFiftyFourOpening';
import {MeanPercentReviewPlayer} from './MeanPercentReviewPlayer';
import {lessonOneHundredFiftyFiveOpening} from './LessonOneHundredFiftyFiveOpening';
import {ControlNineRehearsalPlayer} from './ControlNineRehearsalPlayer';
import {lessonOneHundredFiftySixOpening} from './LessonOneHundredFiftySixOpening';
import {ControlWorkNineGuard} from './ControlWorkNineGuard';
import {lessonOneHundredFiftySevenOpening} from './LessonOneHundredFiftySevenOpening';
import {NaturalNumberCourseReviewPlayer} from './NaturalNumberCourseReviewPlayer';
import {lessonOneHundredFiftyEightOpening} from './LessonOneHundredFiftyEightOpening';
import {NaturalMultiplicationDivisionReviewPlayer} from './NaturalMultiplicationDivisionReviewPlayer';
import {lessonOneHundredFiftyNineOpening} from './LessonOneHundredFiftyNineOpening';
import {CommonFractionsReviewPlayer} from './CommonFractionsReviewPlayer';
import {lessonOneHundredSixtyOpening} from './LessonOneHundredSixtyOpening';
import {DecimalAdditionSubtractionReviewPlayer} from './DecimalAdditionSubtractionReviewPlayer';
import {lessonOneHundredSixtyOneOpening} from './LessonOneHundredSixtyOneOpening';
import {DecimalMultiplicationDivisionReviewPlayer} from './DecimalMultiplicationDivisionReviewPlayer';
import {lessonOneHundredSixtyTwoOpening} from './LessonOneHundredSixtyTwoOpening';
import {PercentCourseReviewPlayer} from './PercentCourseReviewPlayer';
import {lessonOneHundredSixtyThreeOpening} from './LessonOneHundredSixtyThreeOpening';
import {AdvancedPercentReviewPlayer} from './AdvancedPercentReviewPlayer';
import {lessonOneHundredSixtyFourOpening} from './LessonOneHundredSixtyFourOpening';
import {PolygonPerimeterReviewPlayer} from './PolygonPerimeterReviewPlayer';
import {lessonOneHundredSixtyFiveOpening} from './LessonOneHundredSixtyFiveOpening';
import {AreaVolumeReviewPlayer} from './AreaVolumeReviewPlayer';
import {lessonOneHundredSixtySixOpening} from './LessonOneHundredSixtySixOpening';
import {AngleMeasurementReviewPlayer} from './AngleMeasurementReviewPlayer';
import {lessonOneHundredSixtySevenOpening} from './LessonOneHundredSixtySevenOpening';
import {CombinatorialReviewPlayer} from './CombinatorialReviewPlayer';
import {lessonOneHundredSixtyEightOpening} from './LessonOneHundredSixtyEightOpening';
import {AdvancedCombinatorialReviewPlayer} from './AdvancedCombinatorialReviewPlayer';
import {lessonOneHundredSixtyNineOpening} from './LessonOneHundredSixtyNineOpening';
import {TextProblemModelingReviewPlayer} from './TextProblemModelingReviewPlayer';
import {lessonOneHundredSeventyOpening} from './LessonOneHundredSeventyOpening';
import {MultiStepTextProblemReviewPlayer} from './MultiStepTextProblemReviewPlayer';

export const LATEST_READY_LESSON=170;

export function lateOpeningForLesson(lessonNumber:number):LessonOpeningData|null{
  if(lessonNumber===153)return lessonOneHundredFiftyThreeOpening;
  if(lessonNumber===154)return lessonOneHundredFiftyFourOpening;
  if(lessonNumber===155)return lessonOneHundredFiftyFiveOpening;
  if(lessonNumber===156)return lessonOneHundredFiftySixOpening;
  if(lessonNumber===157)return lessonOneHundredFiftySevenOpening;
  if(lessonNumber===158)return lessonOneHundredFiftyEightOpening;
  if(lessonNumber===159)return lessonOneHundredFiftyNineOpening;
  if(lessonNumber===160)return lessonOneHundredSixtyOpening;
  if(lessonNumber===161)return lessonOneHundredSixtyOneOpening;
  if(lessonNumber===162)return lessonOneHundredSixtyTwoOpening;
  if(lessonNumber===163)return lessonOneHundredSixtyThreeOpening;
  if(lessonNumber===164)return lessonOneHundredSixtyFourOpening;
  if(lessonNumber===165)return lessonOneHundredSixtyFiveOpening;
  if(lessonNumber===166)return lessonOneHundredSixtySixOpening;
  if(lessonNumber===167)return lessonOneHundredSixtySevenOpening;
  if(lessonNumber===168)return lessonOneHundredSixtyEightOpening;
  if(lessonNumber===169)return lessonOneHundredSixtyNineOpening;
  if(lessonNumber===170)return lessonOneHundredSeventyOpening;
  return baseOpeningForLesson(lessonNumber);
}

export function lateRuntimeForLesson(lessonNumber:number):ReactNode|null{
  if(lessonNumber===153)return <InversePercentFinalePlayer key="lesson-153"/>;
  if(lessonNumber===154)return <MeanPercentReviewPlayer key="lesson-154"/>;
  if(lessonNumber===155)return <ControlNineRehearsalPlayer key="lesson-155"/>;
  if(lessonNumber===156)return <ControlWorkNineGuard key="lesson-156"/>;
  if(lessonNumber===157)return <NaturalNumberCourseReviewPlayer key="lesson-157"/>;
  if(lessonNumber===158)return <NaturalMultiplicationDivisionReviewPlayer key="lesson-158"/>;
  if(lessonNumber===159)return <CommonFractionsReviewPlayer key="lesson-159"/>;
  if(lessonNumber===160)return <DecimalAdditionSubtractionReviewPlayer key="lesson-160"/>;
  if(lessonNumber===161)return <DecimalMultiplicationDivisionReviewPlayer key="lesson-161"/>;
  if(lessonNumber===162)return <PercentCourseReviewPlayer key="lesson-162"/>;
  if(lessonNumber===163)return <AdvancedPercentReviewPlayer key="lesson-163"/>;
  if(lessonNumber===164)return <PolygonPerimeterReviewPlayer key="lesson-164"/>;
  if(lessonNumber===165)return <AreaVolumeReviewPlayer key="lesson-165"/>;
  if(lessonNumber===166)return <AngleMeasurementReviewPlayer key="lesson-166"/>;
  if(lessonNumber===167)return <CombinatorialReviewPlayer key="lesson-167"/>;
  if(lessonNumber===168)return <AdvancedCombinatorialReviewPlayer key="lesson-168"/>;
  if(lessonNumber===169)return <TextProblemModelingReviewPlayer key="lesson-169"/>;
  if(lessonNumber===170)return <MultiStepTextProblemReviewPlayer key="lesson-170"/>;
  return baseRuntimeForLesson(lessonNumber);
}
