import { useEffect,useMemo,useState } from 'react';
import { lessonOneStages } from './LessonPlayer';
import { lessonTwoStages } from './NaturalRowPracticePlayer';
import { lessonThreeStages } from './DecimalNotationPlayer';
import { lessonFourStages } from './PlaceValueMasteryPlayer';
import './lessonPageNavigator.css';
type PageItem={id:string;title:string};type PageGroup={label:string;indexes:number[]};
const groups1:PageGroup[]=[{label:'Объяснение',indexes:[0,1,2,3,4,5,6,7]},{label:'Практика',indexes:[8,9,10,11,12,13]},{label:'Мини-проверка',indexes:[14,15,16,17,18]},{label:'Завершение',indexes:[19,20]}];
const groups2:PageGroup[]=[{label:'Натуральный ряд и промежутки',indexes:[0,1,2,3,4,5,6,7]},{label:'Закономерности и практика',indexes:[8,9,10,11,12,13,14,15]},{label:'Мини-проверка',indexes:[16,17,18,19,20]},{label:'Завершение',indexes:[21,22]}];
const groups3:PageGroup[]=[{label:'Цифры, записи и разряды',indexes:[0,1,2,3,4,5]},{label:'Классы и чтение чисел',indexes:[6,7,8,9,10]},{label:'Разрядные слагаемые',indexes:[11,12,13,14,15]},{label:'Мини-проверка',indexes:[16,17,18,19,20]},{label:'Завершение',indexes:[21,22]}];
const groups4:PageGroup[]=[{label:'Разрядная система',indexes:[0,1,2,3,4,5]},{label:'Чтение, запись и разложение',indexes:[6,7,8,9,10,11,12]},{label:'Точный разряд и алгоритм',indexes:[13,14]},{label:'Мини-проверка',indexes:[15,16,17,18,19]},{label:'Завершение',indexes:[20,21]}];
function activeLessonNumber(){const text=document.querySelector<HTMLElement>('.lesson-mode-toolbar')?.textContent??'';if(/Урок\s+4\s+из/.test(text))return 4;if(/Урок\s+3\s+из/.test(text))return 3;if(/Урок\s+2\s+из/.test(text))return 2;const n=Number(localStorage.getItem('mathnikita-selected-lesson'));return [2,3,4].includes(n)?n:1}
function pagesForLesson(n:number):PageItem[]{return n===4?lessonFourStages:n===3?lessonThreeStages:n===2?lessonTwoStages:lessonOneStages}
function groupsForLesson(n:number){return n===4?groups4:n===3?groups3:n===2?groups2:groups1}
function activeStageIndex(pages:PageItem[]){const stage=document.querySelector<HTMLElement>('.lesson-runtime:not([hidden]) .interactive-stage');const id=stage?.dataset.stageId;if(id){const i=pages.findIndex(p=>p.id===id);if(i>=0)return i}const title=stage?.querySelector<HTMLElement>('.stage-copy h2')?.textContent?.trim();const i=pages.findIndex(p=>p.title===title);return i>=0?i:0}
export function LessonPageNavigator(){const[visible,setVisible]=useState(false);const[open,setOpen]=useState(false);const[lessonNumber,setLessonNumber]=useState(1);const[currentPage,setCurrentPage]=useState(0);const pages=useMemo(()=>pagesForLesson(lessonNumber),[lessonNumber]);const groups=groupsForLesson(lessonNumber);useEffect(()=>{const refresh=()=>{const active=Boolean(document.querySelector('.lesson-runtime:not([hidden]) .lesson-player-page'));const next=activeLessonNumber();const nextPages=pagesForLesson(next);setVisible(active);setLessonNumber(next);if(active)setCurrentPage(activeStageIndex(nextPages));else setOpen(false)};refresh();const observer=new MutationObserver(refresh);observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['hidden','class','data-stage-id']});return()=>observer.disconnect()},[]);
function jumpTo(targetIndex:number){setOpen(false);if([2,3,4].includes(lessonNumber)){window.dispatchEvent(new CustomEvent('mathnikita-go-to-stage',{detail:{lessonNumber,stageIndex:targetIndex}}));setCurrentPage(targetIndex);return}const move=()=>{const current=activeStageIndex(pages);if(current===targetIndex){setCurrentPage(targetIndex);return}const buttons=document.querySelector<HTMLElement>('.lesson-runtime:not([hidden]) .lesson-controls')?.querySelectorAll<HTMLButtonElement>('button');const button=targetIndex<current?buttons?.[0]:buttons?.[1];if(!button)return;const disabled=button.disabled;if(disabled)button.disabled=false;button.click();if(disabled)button.disabled=true;window.setTimeout(move,45)};move()}
if(!visible)return null;return <aside className={`lesson-page-navigator ${open?'is-open':''}`} aria-label="Навигация по страницам урока"><button className="lesson-page-navigator-toggle" type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span aria-hidden="true">☰</span><b>Страница {currentPage+1}/{pages.length}</b></button>{open?<div className="lesson-page-navigator-panel"><header><div><span>Быстрый просмотр · урок {lessonNumber}</span><b>Перейти к странице урока</b></div><button type="button" onClick={()=>setOpen(false)} aria-label="Закрыть навигацию">×</button></header><p>Режим для взрослого: можно открыть любую страницу без прохождения предыдущих заданий. Сохранённые результаты не удаляются.</p><div className="lesson-page-navigator-groups">{groups.map(group=><section key={group.label}><h3>{group.label}</h3><div>{group.indexes.map(index=>{const stage=pages[index];return <button key={stage.id} type="button" className={index===currentPage?'active':''} onClick={()=>jumpTo(index)}><span>{index+1}</span><b>{stage.title}</b></button>})}</div></section>)}</div></div>:null}</aside>}
