import { useEffect, useMemo, useState, type CSSProperties, type RefObject, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import './mentorMarkerOverlay.css';
import './catMentorVoice.css';

type Props={rootRef:RefObject<HTMLElement|null>;lessonNumber:number;mode:'opening'|'lesson';sceneKey:string;stageId?:string;title:string;body:string;prompt:string;action:'welcome'|'different'|'example'|'hint'|'why'};
function Header({close}:{close:()=>void}){return <header><div><span>Электронный маркер</span><b>Пифагор показывает ход мысли</b></div><button type="button" onClick={close} aria-label="Скрыть разбор">×</button></header>}
function Board({close,children,className=''}:{close:()=>void;children:ReactNode;className?:string}){return <section className={`mentor-marker-overlay ${className}`}><Header close={close}/>{children}</section>}
function extractBounds(text:string){const values=(text.match(/\d[\d\s\u00a0]*/g)??[]).map(v=>Number(v.replace(/[\s\u00a0]/g,''))).filter(Number.isFinite);const unique=values.filter((v,i)=>values.indexOf(v)===i);if(unique.length<2)return null;return unique[0]<=unique[1]?[unique[0],unique[1]] as const:[unique[1],unique[0]] as const}

function LessonOneBoard({id,close}:{id:string;close:()=>void}){
  if(['story','count-rule','measure'].includes(id))return <Board close={close} className="lesson-one-marker"><div className="marker-two-paths"><div><b>📚 📚 📚 📚 📚</b><span>счёт предметов</span><strong>5 книг</strong></div><i>и</i><div><b>▮ ▮ ▮ ▮ ▮</b><span>одинаковые мерки</span><strong>5 мерок</strong></div></div><p>Натуральное число отвечает на вопрос «сколько?», но способ получения числа может быть разным.</p></Board>;
  if(['row','model','choice','quiz2','quiz4'].includes(id))return <Board close={close} className="lesson-one-marker"><div className="marker-infinite-row">{[1,2,3,4,5,6].map(n=><span key={n}>{n}</span>)}<b>…</b></div><div className="marker-formula-single"><span>для любого n</span><b>n → n + 1</b><strong>последнего числа нет</strong></div><p>К любому натуральному числу можно прибавить единицу и получить следующее.</p></Board>;
  if(['previous-one','input','quiz3'].includes(id))return <Board close={close} className="lesson-one-marker"><div className="marker-previous-row"><i>нет натурального</i><b>1</b><span>2</span><span>3</span><span>4</span></div><div className="marker-formula-single"><span>для n &gt; 1</span><b>n → n − 1</b><strong>у 1 предыдущего нет</strong></div><p>Единица — первое натуральное число в этом курсе.</p></Board>;
  if(id==='counterexample')return <Board close={close} className="lesson-one-marker"><div className="marker-counterexample"><div><b>99</b><span>первая цифра 9</span></div><strong>&lt;</strong><div><b>100</b><span>первая цифра 1</span></div></div><div className="marker-strike">«Больше первая цифра → больше число»</div><p>Один контрпример опровергает общее неверное утверждение.</p></Board>;
  if(['compare','order','quiz5','numberline','bounds'].includes(id))return <Board close={close} className="lesson-one-marker"><div className="marker-order-row"><span>5</span><span>6</span><span>7</span><span>8</span><b>→ больше</b></div><p>На числовом луче значения увеличиваются вправо; границы включаются только по знаку условия.</p></Board>;
  if(id==='challenge')return <Board close={close} className="lesson-one-marker"><div className="marker-pigeonhole"><div><b>370</b><span>учеников</span></div><strong>&gt;</strong><div><b>366</b><span>дат</span></div></div><p>Объектов больше, чем возможных дат, поэтому совпадение обязательно.</p></Board>;
  return null;
}

function LessonTwoBoard({id,title,body,prompt,close}:{id:string;title:string;body:string;prompt:string;close:()=>void}){
  if(/sequence|missing|order|counterexample|natural-vs/.test(id))return <Board close={close}><div className="marker-order-row"><span>5</span><span>8</span><span>11</span><span>14</span><b>+3</b></div><div className="marker-formula-single"><span>постоянный шаг</span><b>8−5 = 11−8 = 14−11</b><strong>сначала найди разность</strong></div><p>Натуральный ряд имеет шаг 1, а отдельная последовательность может иметь другой постоянный шаг.</p></Board>;
  const text=`${prompt} ${title} ${body}`;const bounds=extractBounds(text);if(!bounds)return null;const[left,right]=bounds;const difference=right-left;if(difference<=0)return null;const inclusive=/включительно/i.test(text);const result=inclusive?difference+1:Math.max(0,difference-1);const numbers=difference<=12?Array.from({length:difference+1},(_,i)=>left+i):[left,right];
  return <Board close={close}><div className="mentor-number-track" style={{'--marker-count':numbers.length} as CSSProperties}>{numbers.map((n,i)=><div key={`${n}-${i}`} className={i===0||i===numbers.length-1?'is-boundary':'is-between'}><span>{difference>12&&i===1?'…':n.toLocaleString('ru-RU')}</span></div>)}<svg className="mentor-marker-arc" viewBox="0 0 600 90" preserveAspectRatio="none"><path d="M18 72 C140 4 460 4 582 72"/></svg></div><div className="mentor-marker-formula"><div><span>разность</span><b>{right.toLocaleString('ru-RU')} − {left.toLocaleString('ru-RU')} = {difference}</b></div><i>↓</i><div className="is-result"><span>{inclusive?'границы считаются':'границы не считаются'}</span><b>{difference} {inclusive?'+ 1':'− 1'} = <strong>{result}</strong></b></div></div><p>{inclusive?'При подсчёте включительно используем разность плюс один.':'Чисел строго между границами на одно меньше, чем шагов.'}</p></Board>;
}

function ClassBlocks({highlight}:{highlight?:number}){const blocks=[['миллиарды','17'],['миллионы','025'],['тысячи','543'],['единицы','607']];return <div className="l3-marker-classes">{blocks.map(([name,value],i)=><div key={name} className={highlight===i?'is-highlighted':''}><small>{name}</small><b>{value}</b></div>)}</div>}
function PlaceGrid({value='507 042'}:{value?:string}){const digits=value.replace(/\s/g,'').split('');const names=['сотни тысяч','десятки тысяч','тысячи','сотни','десятки','единицы'];return <div className="l3-marker-place-grid">{digits.map((digit,i)=><div key={`${digit}-${i}`}><b>{digit}</b><small>{names[i]}</small></div>)}</div>}
function LessonThreeBoard({id,close}:{id:string;close:()=>void}){
  if(id==='l3-story')return <Board close={close} className="lesson-three-marker"><ClassBlocks/><div className="marker-rule-card"><b>17 | 025 | 543 | 607</b><span>разбиваем справа по три цифры</span><strong>читаем слева направо</strong></div><p>Длинная запись превращается в четыре понятных класса.</p></Board>;
  if(['l3-digits','l3-length','l3-leading-zero'].includes(id))return <Board close={close} className="lesson-three-marker"><div className="digit-strip">{[0,1,2,3,4,5,6,7,8,9].map(n=><b key={n}>{n}</b>)}</div><div className="l3-leading-zero"><span className="is-crossed">0 0</span><b>7</b><strong>обычная запись: 7</strong></div><p>Цифр десять. Ведущие нули не меняют число и в стандартной записи не используются.</p></Board>;
  if(['l3-place','l3-zero-role','l3-place-name'].includes(id))return <Board close={close} className="lesson-three-marker"><PlaceGrid/><div className="marker-formula-single"><span>позиционная система</span><b>507 042 = 500 000 + 7 000 + 40 + 2</b><strong>нуль удерживает пустой разряд</strong></div><p>Одинаковая цифра имеет разное значение на разных местах.</p></Board>;
  if(['l3-classes','l3-split','l3-class-names'].includes(id))return <Board close={close} className="lesson-three-marker"><ClassBlocks highlight={id==='l3-class-names'?1:undefined}/><div className="marker-rule-card"><b>справа налево</b><span>единицы → тысячи → миллионы → миллиарды</span><strong>в каждом классе три разряда</strong></div><p>Левый класс может содержать одну, две или три цифры.</p></Board>;
  if(['l3-read','l3-write'].includes(id))return <Board close={close} className="lesson-three-marker"><div className="l3-read-write"><div><b>8 | 000 | 045</b><span>восемь миллионов сорок пять</span></div><i>↔</i><div><b>12 | 005 | 007</b><span>двенадцать миллионов пять тысяч семь</span></div></div><p>Нулевые классы не произносят, но при записи сохраняют все три позиции.</p></Board>;
  if(['l3-expanded','l3-expand-practice','l3-compose'].includes(id))return <Board close={close} className="lesson-three-marker"><div className="l3-expanded-flow"><b>507 042</b><i>→</i><span>500 000</span><span>7 000</span><span>40</span><span>2</span></div><div className="marker-rule-card"><b>обратная сборка</b><span>400 000 + 20 000 + 300 + 8</span><strong>420 308</strong></div><p>Разложение и сборка — взаимно обратные действия.</p></Board>;
  if(id==='l3-order'||/^l3-quiz/.test(id))return <Board close={close} className="lesson-three-marker"><div className="l3-reading-algorithm"><span>1</span><b>Разбить справа по три цифры</b><span>2</span><b>Читать слева направо</b><span>3</span><b>Назвать ненулевые классы</b><span>4</span><b>Класс единиц — без названия</b></div><p>Этот порядок защищает от пропущенных нулей и сдвига разрядов.</p></Board>;
  if(id==='l3-challenge')return <Board close={close} className="lesson-three-marker"><div className="l3-permutation"><div><b>2</b><span>205</span><span>250</span></div><div><b>5</b><span>502</span><span>520</span></div><div className="is-forbidden"><b>0</b><span>025</span><span>052</span></div></div><p>Ноль не может стоять первым, поэтому допустимы четыре трёхзначных числа.</p></Board>;
  if(id==='l3-summary')return <Board close={close} className="lesson-three-marker"><ClassBlocks/><div className="marker-rule-card"><b>цифра + место = разрядное значение</b><span>классы помогают читать большие числа</span><strong>тема собрана в единую систему</strong></div><p>Теперь можно читать, записывать, раскладывать и собирать многозначные числа.</p></Board>;
  return null;
}

export function MentorMarkerOverlay({rootRef,lessonNumber,mode,sceneKey,stageId='',title,body,prompt,action}:Props){const[mount,setMount]=useState<HTMLElement|null>(null);const[dismissed,setDismissed]=useState(false);useEffect(()=>{const root=rootRef.current;if(!root)return;const refresh=()=>setMount(root.querySelector<HTMLElement>('.lesson-runtime:not([hidden]) .interactive-stage'));refresh();const observer=new MutationObserver(refresh);observer.observe(root,{subtree:true,childList:true,attributes:true,attributeFilter:['class','hidden','data-stage-id']});return()=>observer.disconnect()},[rootRef,lessonNumber,mode]);useEffect(()=>setDismissed(false),[sceneKey,action]);const show=mode==='lesson'&&action!=='welcome'&&mount&&!dismissed;const board=useMemo(()=>{if(!show)return null;const close=()=>setDismissed(true);if(lessonNumber===1)return <LessonOneBoard id={stageId} close={close}/>;if(lessonNumber===2)return <LessonTwoBoard id={stageId} title={title} body={body} prompt={prompt} close={close}/>;if(lessonNumber===3)return <LessonThreeBoard id={stageId} close={close}/>;return null},[show,lessonNumber,stageId,title,body,prompt]);return mount&&board?createPortal(board,mount):null}
