import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredThreePractice,lessonOneHundredThreeResponseCount,type Lesson103Practice} from './data/lessonOneHundredThreePractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson103Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-103-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l103-split',eyebrow:'Урок 103 · § 29 · 2 из 5',title:'Считаем по частям',body:'При действиях со смешанными числами отдельно работаем с целыми и дробными частями. Знаменатель дробной части сохраняется.',note:'Это сводит вычисление к знакомым действиям.'},
{id:'l103-add',eyebrow:'Сложение',title:'Сложи целые части и числители',body:'При одинаковых знаменателях сложи целые части и дробные части отдельно. Затем проверь дробную сумму.',note:'Если она правильная, ответ готов.'},
{id:'l103-carry',eyebrow:'Переход через единицу',title:'Выдели целую из неправильной дробной суммы',body:'Если дробная сумма не меньше единицы, выдели из неё целую часть и добавь её к целой части результата.',note:'Пятнадцать одиннадцатых — одна целая и четыре одиннадцатых.'},
{id:'l103-subtract',eyebrow:'Вычитание',title:'Если дробной части хватает — вычитай по частям',body:'Вычти целые части и числители дробных частей. Знаменатель оставь прежним.',note:'Заём не нужен, если дробная часть уменьшаемого не меньше.'},
{id:'l103-borrow',eyebrow:'Заём единицы',title:'Если дробной части не хватает — займи одну целую',body:'Уменьши целую часть на один и преврати занятую единицу в дробь нужного знаменателя.',note:'Десять и три восьмых = девять и одиннадцать восьмых.'},
{id:'l103-natural',eyebrow:'Натуральное минус смешанное',title:'Добавь полную дробную единицу',body:'Натуральное число можно представить с дробной частью после займа: девять = восемь и семь седьмых.',note:'После этого вычитай по частям.'},
{id:'l103-check',eyebrow:'Самопроверка',title:'Проверь знаменатель, перенос и заём',body:'Знаменатель не меняется; неправильную дробную часть нужно преобразовать; после займа целая часть уменьшается ровно на один.',note:'Обратное действие помогает проверить ответ.'},
{id:'l103-ready',eyebrow:'Перед практикой',title:'Маршрут второго урока § 29',body:'Сначала реши точные № 776, № 778(1–5) и № 783. Затем закрепи перенос, заём, цепочки, уравнения и задачи.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredThreePractice.map((practice,i)=>({id:`l103-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точная задача ${practice.source}`:`Практика § 29 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l103-summary',eyebrow:'Итог урока 103',title:'Сложение и вычитание смешанных чисел освоено',body:'Ты складываешь и вычитаешь смешанные числа с одинаковыми знаменателями, переносишь и занимаешь целую единицу и решаешь задачи на остаток.',note:'Урок 104 продолжит § 29 более сложными упражнениями.',summary:true}];
export const lessonOneHundredThreeStageCount=stages.length;
export const lessonOneHundredThreePracticeTaskCount=lessonOneHundredThreePractice.length;
export const lessonOneHundredThreePracticeResponseCount=lessonOneHundredThreeResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function MixedNumberOperationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==103||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 103: сложение и вычитание смешанных чисел"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь целую и дробную части; при необходимости перенеси или займи единицу.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 103 завершён</b><span>20 задач · 50 ответов · § 29 продолжается</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 103"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
