import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredFivePractice,lessonOneHundredFiveResponseCount,type Lesson105Practice} from './data/lessonOneHundredFivePractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson105Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-105-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l105-expression',eyebrow:'Урок 105 · § 29 · 4 из 5',title:'Сложное выражение разбирай на блоки',body:'Если выражение содержит несколько скобок, сначала вычисли каждую скобку отдельно. Только после этого выполняй действие между полученными смешанными числами.',note:'Промежуточные результаты уменьшают риск потерять перенос или заём.'},
{id:'l105-brackets',eyebrow:'Скобки',title:'Ищи удобные полные единицы',body:'Суммы дробных частей иногда дают ровно одну целую. Замечай такие случаи сразу: это может превратить длинное выражение в действие с натуральными числами.',note:'Перед вычислением полезно оценить дробные части каждой скобки.'},
{id:'l105-equation',eyebrow:'Уравнения',title:'Снимай уравнение слой за слоем',body:'Сначала найди значение всего выражения с неизвестным, затем восстанови саму переменную. Каждый шаг проверяй правилом нахождения неизвестного компонента действия.',note:'Подстановка найденного значения должна вернуть правую часть.'},
{id:'l105-double',eyebrow:'Двойное неравенство',title:'Приведи обе границы к одному языку',body:'Если между двумя смешанными числами стоит дробь с переменным числителем, представь границы дробями с тем же знаменателем. Тогда условие превращается в обычный целочисленный диапазон.',note:'Строгие знаки означают, что сами границы в ответ не входят.'},
{id:'l105-numerator',eyebrow:'Переменный числитель',title:'После общего знаменателя сравнивай числители',body:'Когда знаменатели одинаковы и положительны, порядок дробей определяется числителями. Поэтому двойное дробное неравенство становится цепочкой неравенств для натурального числа.',note:'Так в первом пункте задания семьсот восемьдесят девять получается короткий диапазон соседних чисел.'},
{id:'l105-denominator',eyebrow:'Переменный знаменатель',title:'Помни: при фиксированном положительном числителе дробь уменьшается',body:'Чем больше положительный знаменатель, тем меньше значение дроби. Поэтому условия на дробь с постоянным числителем превращаются в обратные ограничения на знаменатель.',note:'Работай только с положительными натуральными значениями и проверяй крайние кандидаты.'},
{id:'l105-strict',eyebrow:'Строгость границ',title:'Знаки меньше и больше исключают равенство',body:'Если дробь или выражение точно равно натуральной границе, эта граница не входит в решение строгого неравенства. Это особенно важно при делении без остатка.',note:'После нахождения диапазона обязательно проверь два края.'},
{id:'l105-ready',eyebrow:'Перед практикой',title:'Маршрут четвёртого урока § 29',body:'Сначала реши точные номера семьсот семьдесят восемь, семьсот восемьдесят один и семьсот восемьдесят девять. Затем закрепи выражения, уравнения, переменный числитель и переменный знаменатель.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredFivePractice.map((practice,i)=>({id:`l105-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точная задача ${practice.source}`:`Практика § 29 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l105-summary',eyebrow:'Итог урока 105',title:'Сложные выражения и двойные неравенства освоены',body:'Ты вычисляешь многошаговые выражения со смешанными числами, решаешь уравнения и находишь все натуральные значения переменной в двойных дробных неравенствах.',note:'Урок 106 завершит § 29 итоговыми задачами и систематизацией смешанных чисел.',summary:true}];
export const lessonOneHundredFiveStageCount=stages.length;
export const lessonOneHundredFivePracticeTaskCount=lessonOneHundredFivePractice.length;
export const lessonOneHundredFivePracticeResponseCount=lessonOneHundredFiveResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function MixedNumberAdvancedPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==105||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 105: сложные выражения и двойные неравенства"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Проверь скобки, строгие границы и направление изменения дроби при изменении знаменателя.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 105 завершён</b><span>20 задач · 50 ответов · § 29 продолжается</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 105"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
