import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredSixPractice,lessonOneHundredSixResponseCount,type Lesson106Practice} from './data/lessonOneHundredSixPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson106Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-106-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const match=(v:string,a:string[])=>a.some(x=>norm(v)===norm(x));
const concepts:Stage[]=[
{id:'l106-map',eyebrow:'Урок 106 · § 29 · 5 из 5',title:'Собери весь параграф в одну карту',body:'Смешанные числа связывают деление с остатком, неправильные дроби, сложение, вычитание и сравнение. Перед решением сначала определи тип задачи и только потом выбирай алгоритм.',note:'Итоговая цель — не отдельный приём, а уверенный выбор правильного приёма.'},
{id:'l106-convert',eyebrow:'Преобразования',title:'Два направления должны работать одинаково уверенно',body:'Неправильную дробь превращай в смешанное число делением с остатком. Смешанное число возвращай в неправильную дробь умножением целой части на знаменатель и прибавлением числителя.',note:'Обратное преобразование — быстрый способ проверить себя.'},
{id:'l106-operations',eyebrow:'Сложение и вычитание',title:'Перенос и заём — части одного принципа',body:'При сложении выделяй целую единицу из неправильной дробной суммы. При вычитании, если дробной части не хватает, занимай одну целую и превращай её в полный знаменатель.',note:'Знаменатель в обоих случаях остаётся прежним.'},
{id:'l106-equation',eyebrow:'Уравнения и выражения',title:'Сложное решение разбивай на независимые шаги',body:'В выражениях вычисляй скобки отдельно. В уравнениях рассматривай скобку как неизвестный компонент действия, затем восстанавливай переменную следующим шагом.',note:'После решения выполняй подстановку.'},
{id:'l106-numerator',eyebrow:'Переменный числитель',title:'Одинаковые знаменатели превращают дробное сравнение в целочисленное',body:'Если знаменатель фиксирован и положителен, приведи смешанные границы к дробям с этим знаменателем. После этого сравнивай только числители.',note:'Строгие границы в множество решений не входят.'},
{id:'l106-denominator',eyebrow:'Переменный знаменатель',title:'При фиксированном числителе больше знаменатель — меньше дробь',body:'Условия на знаменатель читай с учётом обратной зависимости. Если дополнительно требуется неправильная дробь, одновременно соблюдай условие, что знаменатель не превосходит числитель.',note:'Пересечение двух условий часто сразу даёт конечный диапазон.'},
{id:'l106-check',eyebrow:'Контроль результата',title:'Проверяй смысл, а не только вычисления',body:'Сумма долей целого не должна случайно превышать целое, если ситуация этого не допускает. Для неравенств проверяй крайние значения, для преобразований — обратный переход, для уравнений — подстановку.',note:'Задача семьсот восемьдесят четыре специально проверяет смысл результата.'},
{id:'l106-ready',eyebrow:'Перед практикой',title:'Финальный маршрут § 29',body:'Сначала реши точные номера семьсот восемьдесят четыре, семьсот восемьдесят восемь и семьсот девяносто. Затем пройди итоговую практику по всем типам задач параграфа.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredSixPractice.map((practice,i)=>({id:`l106-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точная задача ${practice.source}`:`Итоговая практика § 29 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l106-summary',eyebrow:'Итог урока 106',title:'§ 29 «Смешанные числа» завершён',body:'Ты преобразуешь смешанные и неправильные дроби, складываешь и вычитаешь смешанные числа, решаешь выражения, уравнения и дробные неравенства и проверяешь ответы по смыслу.',note:'Урок 107 — повторение и систематизация главы 4 перед контрольной работой № 6.',summary:true}];
export const lessonOneHundredSixStageCount=stages.length;
export const lessonOneHundredSixPracticeTaskCount=lessonOneHundredSixPractice.length;
export const lessonOneHundredSixPracticeResponseCount=lessonOneHundredSixResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function MixedNumberSynthesisPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>match(responses[`${key}:${f.id}`]??'',f.answers)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==106||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 106: итоговая систематизация смешанных чисел"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Определи тип задачи, проверь перенос или заём и внимательно проверь строгие границы.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 106 завершён</b><span>20 задач · 50 ответов · § 29 завершён</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 106"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
