import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './multiplicationMeaning.css';

type Activity={
  id:string;
  type:'choice'|'input';
  prompt:string;
  options?:string[];
  answer:string|string[];
  explanation:string;
  hint:string;
  placeholder?:string;
};
type VisualKind='groups'|'translation'|'order'|'vocabulary'|'one'|'zero'|'zero-product'|'array'|'explorer'|'commutative'|'tens'|'operations'|'notebooks'|'final';
type Stage={
  id:string;
  title:string;
  eyebrow:string;
  kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';
  body:string;
  note?:string;
  activity?:Activity;
  visual?:VisualKind;
  sourceExercise?:string;
};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-54-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/[\s.,;:!?()[\]{}'"«»]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonFiftyFourStages:Stage[]=[
  {id:'l54-mission',kind:'story',eyebrow:'Урок 54 · § 16 · новая глава',title:'Короткая запись для одинаковых групп',body:'Сложение остаётся верным, но становится неудобным, когда одинаковое число надо повторить много раз. Умножение сжимает такую сумму в два множителя и сохраняет её смысл.',note:'Маршрут: равные слагаемые → язык произведения → 1 и 0 → прямоугольная таблица → ab=ba → задачи № 384 и 393.',visual:'groups'},
  {id:'l54-equal-groups',kind:'model',eyebrow:'Смысл действия',title:'Первый множитель — что повторяем, второй — сколько раз',body:'Если b — натуральное число, большее 1, то произведение a·b означает сумму b слагаемых, каждое из которых равно a. Например, 6·4=6+6+6+6.',note:'Читаем: «число 6 взяли слагаемым 4 раза».',visual:'translation'},
  {id:'l54-sum-product',kind:'practice',eyebrow:'Перевод · сумма → произведение',title:'Четыре одинаковых слагаемых',body:'В сумме 7+7+7+7 повторяется число 7, а одинаковых слагаемых четыре.',activity:{id:'l54-p1',type:'input',prompt:'Запиши сумму произведением.',answer:['7·4','7×4','7*4'],placeholder:'a·b',hint:'Сначала запиши повторяющееся слагаемое, затем число повторений.','explanation':'7+7+7+7=7·4.'},visual:'translation'},
  {id:'l54-product-sum',kind:'practice',eyebrow:'Перевод · произведение → сумма',title:'Раскрываем короткую запись',body:'В произведении 5·3 число 5 должно стать одинаковым слагаемым три раза.',activity:{id:'l54-p2',type:'choice',prompt:'Какая сумма точно выражает 5·3?',options:['5+5+5','3+3+3+3+3','5+3','5+5+3'],answer:'5+5+5',hint:'Первый множитель повторяется столько раз, сколько показывает второй.','explanation':'5·3=5+5+5=15.'},visual:'translation'},
  {id:'l54-factor-order',kind:'model',eyebrow:'Смысл порядка',title:'7·4 и 4·7 — разные рассказы',body:'Запись 7·4 моделирует четыре группы по 7, а 4·7 — семь групп по 4. Значения равны, но описание конкретной ситуации зависит от порядка множителей.',note:'Сначала сохраняем смысл модели, а равенство результатов докажем прямоугольной таблицей.',visual:'order'},
  {id:'l54-order-trap',kind:'quiz',eyebrow:'Ловушка смысла',title:'Не переставляй множители раньше времени',body:'Нужно заменить произведением именно сумму 7+7+7+7.',activity:{id:'l54-p3',type:'choice',prompt:'Какая запись передаёт структуру суммы по определению?',options:['7·4','4·7','7+4','4+4+4+4'],answer:'7·4',hint:'Какое число является слагаемым и сколько раз оно записано?','explanation':'Слагаемое 7 повторено 4 раза, поэтому модель — 7·4. Число 4·7 равно ему по значению, но кодирует другую группировку.'},visual:'order'},
  {id:'l54-vocabulary',kind:'model',eyebrow:'Язык математики',title:'Два множителя и произведение',body:'В равенстве 8·5=40 числа 8 и 5 называют множителями, а число 40 — значением произведения. Саму запись 8·5 тоже называют произведением.',visual:'vocabulary'},
  {id:'l54-factors-check',kind:'practice',eyebrow:'Термины',title:'Называем компоненты без перестановки',body:'Рассмотри равенство 3·8=24.',activity:{id:'l54-p4',type:'choice',prompt:'Какие числа являются множителями?',options:['3 и 8','8 и 24','3 и 24','Только 24'],answer:'3 и 8',hint:'Множители соединены знаком умножения.','explanation':'В записи 3·8 множители — 3 и 8; значение произведения — 24.'},visual:'vocabulary'},
  {id:'l54-product-name',kind:'quiz',eyebrow:'Термины',title:'Одно слово — две связанные записи',body:'Выражение 12·6 называют произведением, а 72 — значением этого произведения.',activity:{id:'l54-p5',type:'choice',prompt:'Как называется результат 72 в равенстве 12·6=72?',options:['Значение произведения','Первый множитель','Второй множитель','Сумма'],answer:'Значение произведения',hint:'Результат находится справа от знака равенства.','explanation':'72 — значение произведения множителей 12 и 6.'},visual:'vocabulary'},
  {id:'l54-one-model',kind:'model',eyebrow:'Особый случай',title:'Умножение на 1 сохраняет число',body:'Для второго множителя 1 вводят правило a·1=a: число берётся слагаемым один раз. По переместительному свойству также 1·a=a.',visual:'one'},
  {id:'l54-one-check',kind:'practice',eyebrow:'Формула a·1=a',title:'Буква остаётся собой',body:'Значение a не задано, но специальное правило уже определяет результат.',activity:{id:'l54-p6',type:'input',prompt:'Чему равно a·1?',answer:'a',placeholder:'Ответ',hint:'Один экземпляр числа a — это само число a.','explanation':'a·1=a.'},visual:'one'},
  {id:'l54-zero-model',kind:'model',eyebrow:'Особый случай',title:'Умножение на 0 даёт 0',body:'Если взять число ноль раз, не останется ни одной группы: a·0=0. По переместительному свойству 0·a=0.',note:'Нуль не делает число «тем же самым» — это роль единицы.',visual:'zero'},
  {id:'l54-zero-check',kind:'practice',eyebrow:'Формула a·0=0',title:'Какое бы число ни стояло рядом',body:'Даже очень большое число при умножении на ноль даёт ноль.',activity:{id:'l54-p7',type:'input',prompt:'Вычисли 987654·0.',answer:'0',placeholder:'Ответ',hint:'В произведении есть нулевой множитель.','explanation':'987654·0=0.'},visual:'zero'},
  {id:'l54-zero-product',kind:'guided',eyebrow:'Свойство нулевого произведения',title:'Нуль в ответе раскрывает один из множителей',body:'Если произведение равно нулю, то хотя бы один множитель равен нулю. И наоборот: наличие нулевого множителя гарантирует нулевое произведение.',note:'Коротко: ab=0 тогда и только тогда, когда a=0 или b=0.',visual:'zero-product'},
  {id:'l54-zero-factor',kind:'practice',eyebrow:'Обратное рассуждение',title:'Находим неизвестный множитель',body:'В равенстве 73·x=0 первый множитель точно не равен нулю.',activity:{id:'l54-p8',type:'input',prompt:'Чему равен x?',answer:'0',placeholder:'x',hint:'Какой множитель обязан дать нулевой результат?','explanation':'Так как 73≠0, нулём должен быть второй множитель: x=0.'},visual:'zero-product'},
  {id:'l54-array-model',kind:'model',eyebrow:'Наглядное доказательство',title:'Одну таблицу можно посчитать в двух направлениях',body:'В таблице 3 строки по 4 точки: по строкам получаем 4·3. Те же точки образуют 4 столбца по 3: по столбцам получаем 3·4. Общее число точек не изменилось.',visual:'array'},
  {id:'l54-array-explorer',kind:'guided',eyebrow:'Интерактивная лаборатория',title:'Переставь строки и столбцы',body:'Измени размеры таблицы и нажми «Поменять множители местами». Количество точек сохранится, а роли строк и столбцов поменяются.',note:'Именно прямоугольная таблица показывает, почему ab=ba для любых выбранных размеров.',visual:'explorer'},
  {id:'l54-commutative-model',kind:'model',eyebrow:'Переместительное свойство',title:'От перестановки множителей произведение не меняется',body:'Для любых натуральных чисел a и b выполняется равенство ab=ba. Свойство разрешает выбрать более удобный порядок вычисления, но в текстовой модели сначала полезно записать смысл условия.',visual:'commutative'},
  {id:'l54-commutative-check',kind:'practice',eyebrow:'Применяем ab=ba',title:'Переставляем, не меняя числа',body:'Нужно получить равное произведение для 9·6.',activity:{id:'l54-p9',type:'choice',prompt:'Какое выражение гарантированно равно 9·6 по переместительному свойству?',options:['6·9','9+6','9·5','6+9'],answer:'6·9',hint:'Поменяй местами только множители.','explanation':'9·6=6·9.'},visual:'commutative'},
  {id:'l54-same-value',kind:'challenge',eyebrow:'Точность языка',title:'Равные значения не стирают смысл задачи',body:'Четыре коробки по 7 карандашей естественно записать как 7·4. Семь коробок по 4 карандаша — как 4·7. В обоих случаях 28 предметов, потому что 7·4=4·7.',note:'Различай два вопроса: «как устроены группы?» и «сколько всего?».',visual:'order'},
  {id:'l54-ex384-1',kind:'practice',eyebrow:'Учебник · № 384(1)',title:'Восемь шестёрок',body:'Сумма содержит восемь одинаковых слагаемых, каждое равно 6.',sourceExercise:'384.1',activity:{id:'l54-p10',type:'input',prompt:'Запиши сумму 6+6+6+6+6+6+6+6 произведением.',answer:['6·8','6×8','6*8'],placeholder:'a·b',hint:'Слагаемое 6 повторяется 8 раз.','explanation':'6+6+6+6+6+6+6+6=6·8.'},visual:'translation'},
  {id:'l54-ex384-2',kind:'practice',eyebrow:'Учебник · № 384(2)',title:'Пять девяток',body:'Сначала выдели повторяющееся число, затем пересчитай слагаемые.',sourceExercise:'384.2',activity:{id:'l54-p11',type:'input',prompt:'Запиши 9+9+9+9+9 произведением.',answer:['9·5','9×5','9*5'],placeholder:'a·b',hint:'Первый множитель — 9, второй — 5.','explanation':'9+9+9+9+9=9·5.'},visual:'translation'},
  {id:'l54-ex384-variables',kind:'challenge',eyebrow:'Учебник · № 384(3)',title:'Та же идея работает с буквой',body:'Слагаемое n повторяется семь раз. Его значение неизвестно, но структура суммы известна полностью.',sourceExercise:'384.3',activity:{id:'l54-p12',type:'input',prompt:'Запиши n+n+n+n+n+n+n произведением.',answer:['n·7','n×7','n*7','7n'],placeholder:'Произведение',hint:'Буква n — повторяющееся слагаемое.','explanation':'Сумма семи одинаковых слагаемых n равна n·7.'},visual:'translation'},
  {id:'l54-oral-product',kind:'practice',eyebrow:'Устный счёт',title:'Сначала смысл, затем значение',body:'Произведение 14·6 можно представить как шесть слагаемых 14 или разбить каждое 14 на 10 и 4.',activity:{id:'l54-p13',type:'input',prompt:'Вычисли 14·6.',answer:'84',placeholder:'Ответ',hint:'10·6+4·6=60+24.','explanation':'14·6=84.'},visual:'groups'},
  {id:'l54-tens-model',kind:'model',eyebrow:'Разрядные единицы',title:'Умножение на 10, 100 и 1000',body:'При умножении натурального числа на 10, 100 или 1000 справа приписывают соответственно один, два или три нуля. Так 37·100=3700.',note:'Это не механический фокус: каждая цифра сдвигается в разряд, который в 10, 100 или 1000 раз крупнее.',visual:'tens'},
  {id:'l54-tens-check',kind:'practice',eyebrow:'Разрядный сдвиг',title:'Два нуля второго множителя',body:'Во втором множителе 100 два нуля.',activity:{id:'l54-p14',type:'input',prompt:'Вычисли 34·100.',answer:['3400','3 400'],placeholder:'Ответ',hint:'Припиши к 34 два нуля.','explanation':'34·100=3400.'},visual:'tens'},
  {id:'l54-operation-order',kind:'model',eyebrow:'Выражения',title:'Умножение выполняем раньше сложения и вычитания',body:'Если скобок нет, сначала находят произведения, а затем выполняют сложение или вычитание. Например, 90−8·7=90−56=34.',visual:'operations'},
  {id:'l54-operation-check',kind:'practice',eyebrow:'Порядок действий',title:'Не вычитай раньше умножения',body:'В выражении 80−6·4 сначала вычисляется произведение 6·4.',activity:{id:'l54-p15',type:'input',prompt:'Вычисли 80−6·4.',answer:'56',placeholder:'Ответ',hint:'Сначала 6·4=24.','explanation':'80−6·4=80−24=56.'},visual:'operations'},
  {id:'l54-word-model',kind:'model',eyebrow:'Текстовая задача',title:'Равные группы дают произведение',body:'Если купили 8 упаковок по 15 карандашей, число 15 повторяется 8 раз. Поэтому всего 15·8=120 карандашей.',note:'Слова «по столько в каждой» часто сигнализируют о равных группах.',visual:'groups'},
  {id:'l54-notebook-plan',kind:'guided',eyebrow:'Учебник · № 393 · план',title:'Две покупки — два произведения',body:'Купили 34 тетради по 12 сальдо и 18 тетрадей по 16 сальдо. Сначала найдём стоимость каждой партии, затем сложим.',sourceExercise:'393',activity:{id:'l54-p16',type:'choice',prompt:'Какое выражение моделирует всю покупку?',options:['34·12+18·16','(34+18)·12','34+12+18+16','34·18+12·16'],answer:'34·12+18·16',hint:'Цена в каждой партии своя, поэтому произведений два.','explanation':'Первая партия стоит 34·12, вторая — 18·16; общая стоимость равна их сумме.'},visual:'notebooks'},
  {id:'l54-notebook-answer',kind:'practice',eyebrow:'Учебник · № 393 · решение',title:'Складываем стоимости партий',body:'34·12=408 сальдо, а 18·16=288 сальдо.',sourceExercise:'393',activity:{id:'l54-p17',type:'input',prompt:'Сколько сальдо заплатили всего?',answer:'696',placeholder:'Стоимость',hint:'Сложи 408 и 288.','explanation':'408+288=696 сальдо.'},visual:'notebooks'},
  {id:'l54-error-analysis',kind:'challenge',eyebrow:'Диагностика ошибки',title:'«Четыре семёрки — это 4·7»',body:'Ученик сразу переставил множители и потерял точную связь с исходной суммой. Значение он получил то же, но перевод суммы выполнил неточно.',activity:{id:'l54-p18',type:'choice',prompt:'Какая запись непосредственно соответствует 7+7+7+7?',options:['7·4','4·7','7·7','4·4'],answer:'7·4',hint:'Сначала передай структуру суммы, затем при желании используй ab=ba.','explanation':'По определению 7+7+7+7=7·4, а уже по свойству 7·4=4·7.'},visual:'order'},
  {id:'l54-mixed-gate',kind:'quiz',eyebrow:'Mastery gate',title:'Четыре правила в одном выражении',body:'Вычисли 8·6+125·0+37·1−37. Здесь понадобятся обычное произведение, нулевой множитель и умножение на единицу.',activity:{id:'l54-p19',type:'input',prompt:'Чему равно выражение?',answer:'48',placeholder:'Ответ',hint:'8·6=48, 125·0=0, 37·1=37.','explanation':'48+0+37−37=48.'},visual:'operations'},
  {id:'l54-array-proof',kind:'challenge',eyebrow:'Доказательство моделью',title:'Три строки по восемь точек',body:'Одну таблицу можно прочитать как 8·3 по строкам и как 3·8 по столбцам.',activity:{id:'l54-p20',type:'input',prompt:'Сколько точек доказывают равенство 8·3=3·8?',answer:'24',placeholder:'Точек',hint:'Посчитай 8·3.','explanation':'Обе записи считают одни и те же 24 точки.'},visual:'array'},
  {id:'l54-zero-quiz',kind:'quiz',eyebrow:'Последняя проверка',title:'Когда произведение равно нулю',body:'Нужно выбрать утверждение, верное для любых двух множителей.',activity:{id:'l54-p21',type:'choice',prompt:'Что следует из равенства a·b=0?',options:['Хотя бы один множитель равен нулю','Оба множителя равны нулю','Оба множителя равны единице','Множители обязательно равны'],answer:'Хотя бы один множитель равен нулю',hint:'Достаточно одного нулевого множителя; второй может быть любым.','explanation':'Из a·b=0 следует: a=0 или b=0.'},visual:'zero-product'},
  {id:'l54-summary',kind:'summary',eyebrow:'Итог урока 54',title:'За знаком умножения теперь видна структура',body:'Ты переводишь одинаковые слагаемые в произведение и обратно, называешь множители, применяешь a·1=a и a·0=0, распознаёшь нулевое произведение и объясняешь ab=ba одной прямоугольной таблицей.',note:'Дальше — обязательная мастерская: 20 заданий и 50 ответов по всему маршруту § 16.',visual:'final'}
];

function DotArray({rows,columns,label}:{rows:number;columns:number;label:string}){
  return <div className="multiplication-dot-field" role="img" aria-label={label} style={{gridTemplateColumns:'repeat('+columns+', minmax(0, 1fr))'}}>{Array.from({length:rows*columns},(_,index)=><i key={index}/>)}</div>;
}

function ArrayExplorer(){
  const[rows,setRows]=useState(3);const[columns,setColumns]=useState(4);const[swapped,setSwapped]=useState(false);
  function swap(){setRows(columns);setColumns(rows);setSwapped(value=>!value)}
  return <div className="multiplication-explorer" data-array-model="interactive" data-rows={rows} data-columns={columns} data-total={rows*columns} data-swapped={String(swapped)}>
    <div className="multiplication-explorer-controls">
      <label><span>Строки: <b>{rows}</b></span><input aria-label="Количество строк" type="range" min="2" max="6" value={rows} onChange={event=>{setRows(Number(event.target.value));setSwapped(false)}}/></label>
      <label><span>Точек в строке: <b>{columns}</b></span><input aria-label="Количество точек в строке" type="range" min="2" max="8" value={columns} onChange={event=>{setColumns(Number(event.target.value));setSwapped(false)}}/></label>
      <button type="button" onClick={swap}>Поменять множители местами</button>
    </div>
    <DotArray rows={rows} columns={columns} label={rows+' строк по '+columns+' точек'}/>
    <div className="multiplication-equation"><b>{columns}·{rows}</b><span>=</span><b>{rows}·{columns}</b><span>=</span><strong>{rows*columns}</strong></div>
  </div>;
}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='explorer')return <ArrayExplorer/>;
  if(kind==='array')return <div className="multiplication-visual" data-array-model="static" data-rows="3" data-columns="4" data-total="12"><DotArray rows={3} columns={4} label="3 строки по 4 точки"/><div className="multiplication-equation"><b>4·3</b><span>=</span><strong>12</strong><span>=</span><b>3·4</b></div></div>;
  if(kind==='groups')return <div className="multiplication-visual" data-visual="equal-groups"><div className="multiplication-groups"><span>● ● ● ●</span><span>● ● ● ●</span><span>● ● ● ●</span></div><div className="multiplication-equation"><b>4+4+4</b><span>=</span><strong>4·3</strong><span>= 12</span></div></div>;
  if(kind==='translation')return <div className="multiplication-visual" data-visual="translation"><div className="multiplication-translation"><span><small>одинаковая сумма</small><b>6+6+6+6</b></span><i>⇄</i><span><small>короткая запись</small><b>6·4</b></span></div></div>;
  if(kind==='order')return <div className="multiplication-visual" data-visual="factor-order"><div className="multiplication-order"><span><b>7·4</b><small>4 группы по 7</small></span><span><b>4·7</b><small>7 групп по 4</small></span></div><strong className="multiplication-same-total">разные модели · одинаковое значение 28</strong></div>;
  if(kind==='vocabulary')return <div className="multiplication-visual" data-visual="vocabulary"><div className="multiplication-vocabulary"><span><b>8</b><small>первый множитель</small></span><i>·</i><span><b>5</b><small>второй множитель</small></span><i>=</i><span><b>40</b><small>значение произведения</small></span></div></div>;
  if(kind==='one')return <div className="multiplication-visual multiplication-rules" data-visual="multiply-by-one"><b>a·1=a</b><b>1·a=a</b><span>один экземпляр числа</span></div>;
  if(kind==='zero')return <div className="multiplication-visual multiplication-rules is-zero" data-visual="multiply-by-zero"><b>a·0=0</b><b>0·a=0</b><span>ноль одинаковых групп</span></div>;
  if(kind==='zero-product')return <div className="multiplication-visual" data-visual="zero-product"><div className="multiplication-zero-product"><b>a·b=0</b><span>⇔</span><strong>a=0 или b=0</strong></div></div>;
  if(kind==='commutative')return <div className="multiplication-visual" data-visual="commutative"><div className="multiplication-property"><b>ab</b><span>=</span><b>ba</b></div><small className="multiplication-caption">множители поменялись местами · произведение сохранилось</small></div>;
  if(kind==='tens')return <div className="multiplication-visual" data-visual="place-values"><div className="multiplication-place-values"><span><b>46·10</b><strong>460</strong></span><span><b>37·100</b><strong>3700</strong></span><span><b>205·1000</b><strong>205000</strong></span></div></div>;
  if(kind==='operations')return <div className="multiplication-visual" data-visual="operation-order"><div className="multiplication-operation"><b>80 − <mark>6·4</mark></b><span>→</span><b>80 − 24</b><span>→</span><strong>56</strong></div></div>;
  if(kind==='notebooks')return <div className="multiplication-visual" data-visual="notebooks"><div className="multiplication-notebooks"><span><b>34 × 12</b><small>первая партия</small><strong>408</strong></span><i>+</i><span><b>18 × 16</b><small>вторая партия</small><strong>288</strong></span></div><div className="multiplication-equation"><b>408+288</b><span>=</span><strong>696 сальдо</strong></div></div>;
  return <div className="multiplication-visual" data-visual="final"><div className="multiplication-final"><b>равные слагаемые ✓</b><b>множители ✓</b><b>1 и 0 ✓</b><b>ab=ba ✓</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFiftyFourStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function MultiplicationMeaningPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFiftyFourStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFiftyFourStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==54||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFiftyFourStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFiftyFourStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player multiplication-meaning-player" data-lesson-number="54" data-source-reference="Мерзляк § 16 · с. 106–113 · № 384–419" data-source-exercise-range="384-419"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFiftyFourStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFiftyFourStages.length-1||!canContinue}>{saved.stageIndex===lessonFiftyFourStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
