import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './multiplicationStrategies.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'substitute'|'simplify'|'lab'|'pairs'|'chain'|'units'|'zeros'|'angle'|'heads'|'travel'|'logic'|'error'|'final';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-60-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyStages:Stage[]=[
  {id:'l60-mission',kind:'story',eyebrow:'Урок 60 · § 17 · итог темы',title:'Не считай длиннее, чем нужно',body:'Свойства умножения становятся настоящим инструментом, когда ты сам выбираешь маршрут. Сегодня завершим § 17: сначала упростим структуру, затем подставим числа, соберём круглые произведения и применим те же идеи к величинам, геометрии и логике.',note:'Маршрут по учебнику Мерзляка: § 17, № 430–446 · буквенные выражения → удобные группы → составные величины → нули → модели задач.',visual:'mission'},
  {id:'l60-strategy-map',kind:'model',eyebrow:'Карта решения',title:'Четыре вопроса до первого вычисления',body:'Есть ли общий множитель? Можно ли получить 10, 100 или 1000? Нужно ли сначала привести единицы? Какая модель связывает данные? Ответы на эти вопросы почти всегда сокращают решение.',note:'Стратегия не меняет значение выражения — она меняет сложность промежуточных шагов.',visual:'map'},
  {id:'l60-430-model',kind:'guided',eyebrow:'№ 430 · структура',title:'Сначала постоянные множители, потом буквы',body:'В произведении 25x·4y переставим и сгруппируем множители: (25·4)·x·y=100xy. Подстановка x=12 и y=11 теперь требует умножить только 100·12·11.',note:'Упрощение до подстановки уменьшает риск и сразу показывает порядок величины.',visual:'substitute',sourceExercise:'№ 430'},
  {id:'l60-430-value',kind:'practice',eyebrow:'№ 430(1)',title:'Круглая сотня перед подстановкой',body:'После упрощения выражение равно 100xy.',activity:{id:'l60-p1',type:'input',prompt:'Вычисли 25x·4y при x=12, y=11.',answer:['13200','13 200'],placeholder:'Значение',hint:'100·12·11.',explanation:'25x·4y=100xy=100·12·11=13200.'},visual:'substitute',sourceExercise:'№ 430(1)'},
  {id:'l60-431-value',kind:'practice',eyebrow:'№ 431(2)',title:'Двести умножается на mn',body:'В выражении 4m·50n постоянные множители дают 4·50=200.',activity:{id:'l60-p2',type:'input',prompt:'Вычисли 4m·50n при m=22, n=34.',answer:['149600','149 600'],placeholder:'Значение',hint:'200·22·34.',explanation:'4m·50n=200mn=200·22·34=149600.'},visual:'substitute',sourceExercise:'№ 431(2)'},
  {id:'l60-substitution-choice',kind:'quiz',eyebrow:'Стратегия подстановки',title:'Не прячем удобную структуру',body:'Если подставить все числа немедленно, равенство останется верным, но вычисление станет длиннее.',activity:{id:'l60-p3',type:'choice',prompt:'Какой первый шаг выгоднее для 8k·125c?',options:['Собрать 8·125=1000','Сначала умножить k на c','Сложить 8 и 125','Заменить kc на k+c'],answer:'Собрать 8·125=1000',hint:'Ищи пару, которая образует степень десяти.',explanation:'8k·125c=(8·125)kc=1000kc.'},visual:'map'},
  {id:'l60-432-a',kind:'practice',eyebrow:'№ 432(1)',title:'Подстановка создаёт общий множитель',body:'При b=602 оба слагаемых содержат множитель 36: 398·36+36·602.',activity:{id:'l60-p4',type:'input',prompt:'Вычисли 398·36+36b при b=602.',answer:['36000','36 000'],placeholder:'Значение',hint:'36·(398+602).',explanation:'36·1000=36000.'},visual:'simplify',sourceExercise:'№ 432(1)'},
  {id:'l60-432-b',kind:'practice',eyebrow:'№ 432(2)',title:'Общий множитель стоит с разных сторон',body:'При b=83 выражение становится 986·83−86·83.',activity:{id:'l60-p5',type:'input',prompt:'Вычисли 986b−86·83 при b=83.',answer:['74700','74 700'],placeholder:'Значение',hint:'83·(986−86).',explanation:'83·900=74700.'},visual:'simplify',sourceExercise:'№ 432(2)'},
  {id:'l60-433-a',kind:'practice',eyebrow:'№ 433(1)',title:'Сумма коэффициентов равна тысяче',body:'При x=18 получаем 631·18+18·369.',activity:{id:'l60-p6',type:'input',prompt:'Вычисли 631·18+x·369 при x=18.',answer:['18000','18 000'],placeholder:'Значение',hint:'18·(631+369).',explanation:'18·1000=18000.'},visual:'simplify',sourceExercise:'№ 433(1)'},
  {id:'l60-433-b',kind:'practice',eyebrow:'№ 433(2)',title:'Разность внутри скобок равна двумстам',body:'При a=1024 вынесем 58: 58·(1024−824).',activity:{id:'l60-p7',type:'input',prompt:'Вычисли 58a−58·824 при a=1024.',answer:['11600','11 600'],placeholder:'Значение',hint:'1024−824=200.',explanation:'58·200=11600.'},visual:'simplify',sourceExercise:'№ 433(2)'},
  {id:'l60-434-like',kind:'practice',eyebrow:'№ 434(3)',title:'Скрытая единица меняет итоговый коэффициент',body:'В записи 38x+17x−54x+x последний x означает 1x.',activity:{id:'l60-p8',type:'input',prompt:'Вычисли 38x+17x−54x+x при x=678.',answer:['1356','1 356'],placeholder:'Значение',hint:'38+17−54+1=2.',explanation:'Выражение равно 2x, поэтому 2·678=1356.'},visual:'simplify',sourceExercise:'№ 434(3)'},
  {id:'l60-435-like',kind:'practice',eyebrow:'№ 435(4)',title:'Свободное число остаётся отдельно',body:'Буквенная часть упрощается: 19z−12z+33z=40z. Число 192 не содержит z.',activity:{id:'l60-p9',type:'input',prompt:'Вычисли 19z−12z+33z−192 при z=82.',answer:['3088','3 088'],placeholder:'Значение',hint:'40·82−192.',explanation:'3280−192=3088.'},visual:'simplify',sourceExercise:'№ 435(4)'},
  {id:'l60-strategy-lab',kind:'model',eyebrow:'Интерактивная лаборатория',title:'Переключай выражения и сравни два маршрута',body:'Для каждого выражения лаборатория показывает обычную запись и стратегический маршрут. Итоги обязаны совпасть, а число неудобных произведений должно уменьшиться.',note:'Выбери другой сценарий и проследи, где появились 100 или 1000.',visual:'lab'},
  {id:'l60-lab-conclusion',kind:'quiz',eyebrow:'Вывод из лаборатории',title:'Хорошая стратегия сохраняет значение',body:'Свойства позволяют переставлять, группировать и распределять множители по правилам, но не разрешают произвольно менять действия.',activity:{id:'l60-p10',type:'choice',prompt:'Какой признак подтверждает корректность стратегического маршрута?',options:['Оба маршрута дают одно значение','В новом маршруте обязательно меньше знаков','Все числа стали меньше 10','Можно удалить любой неудобный множитель'],answer:'Оба маршрута дают одно значение',hint:'Сравни не внешний вид записей, а их значения.',explanation:'Равенство значений — обязательная проверка любого тождественного преобразования.'},visual:'lab'},
  {id:'l60-436',kind:'practice',eyebrow:'№ 436(4)',title:'Разложи 24 ради пары 375·8',body:'Представим 24 как 8·3 и используем сочетательное свойство.',activity:{id:'l60-p11',type:'input',prompt:'Вычисли 375·24 удобным способом.',answer:['9000','9 000'],placeholder:'Значение',hint:'375·8·3=3000·3.',explanation:'375·24=375·8·3=3000·3=9000.'},visual:'pairs',sourceExercise:'№ 436(4)'},
  {id:'l60-437',kind:'practice',eyebrow:'№ 437(3)',title:'Пара 75·4 образует три сотни',body:'Разложим 36 как 4·9 и сначала вычислим 75·4.',activity:{id:'l60-p12',type:'input',prompt:'Вычисли 75·36 удобным способом.',answer:['2700','2 700'],placeholder:'Значение',hint:'300·9.',explanation:'75·36=75·4·9=300·9=2700.'},visual:'pairs',sourceExercise:'№ 437(3)'},
  {id:'l60-438-a',kind:'practice',eyebrow:'№ 438(1)',title:'Две сборки общего множителя подряд',body:'Сначала 43·64+43·23=43·87. Затем 43·87−87·33=87·(43−33).',activity:{id:'l60-p13',type:'input',prompt:'Вычисли 43·64+43·23−87·33.',answer:['870'],placeholder:'Значение',hint:'87·(43−33).',explanation:'87·10=870.'},visual:'chain',sourceExercise:'№ 438(1)'},
  {id:'l60-438-b',kind:'guided',eyebrow:'№ 438(2)',title:'Две разности дают один множитель 25',body:'84·(53−28)+16·(61−36)=84·25+16·25=25·(84+16)=2500.',note:'Прежде чем умножать, сравни выражения внутри скобок: оба равны 25.',visual:'chain',sourceExercise:'№ 438(2)'},
  {id:'l60-439-a',kind:'practice',eyebrow:'№ 439(1)',title:'Разность 93−27 превращается в 66',body:'Первые два произведения дают 24·66; третье уже содержит 66.',activity:{id:'l60-p14',type:'input',prompt:'Вычисли 93·24−27·24+66·76.',answer:['6600','6 600'],placeholder:'Значение',hint:'66·(24+76).',explanation:'66·100=6600.'},visual:'chain',sourceExercise:'№ 439(1)'},
  {id:'l60-439-b',kind:'challenge',eyebrow:'№ 439(2)',title:'Две сотни складываются в третью',body:'82·(46+54)+18·(135−35)=82·100+18·100.',activity:{id:'l60-p15',type:'input',prompt:'Вычисли 82·46+82·54+135·18−18·35.',answer:['10000','10 000'],placeholder:'Значение',hint:'100·(82+18).',explanation:'100·100=10000.'},visual:'chain',sourceExercise:'№ 439(2)'},
  {id:'l60-units-model',kind:'model',eyebrow:'№ 440–441 · составные величины',title:'Умножай в одной системе, затем нормализуй',body:'Составную величину можно перевести в младшие единицы до умножения. После вычисления возвращай крупные единицы: 100 см=1 м, 60 с=1 мин, 60 мин=1 ч.',note:'Ответ с 170 минутами верен, но запись 2 ч 50 мин лучше показывает нормализацию.',visual:'units'},
  {id:'l60-440',kind:'practice',eyebrow:'№ 440(1)',title:'Метры переносятся в километры',body:'2 км 56 м=2056 м. После умножения получим 139808 м.',activity:{id:'l60-p16',type:'input',prompt:'Вычисли 2 км 56 м · 68.',answer:['139 км 808 м','139км808м'],placeholder:'км и м',hint:'2056·68=139808 м.',explanation:'139808 м=139 км 808 м.'},visual:'units',sourceExercise:'№ 440(1)'},
  {id:'l60-441',kind:'practice',eyebrow:'№ 441(5)',title:'Секунды превращаются в минуты и часы',body:'7 мин 5 с=425 с. Умножаем на 24 и переводим 10200 секунд обратно.',activity:{id:'l60-p17',type:'input',prompt:'Вычисли 7 мин 5 с · 24.',answer:['2 ч 50 мин','2ч50мин','170 мин','170мин'],placeholder:'ч и мин',hint:'10200 с=170 мин.',explanation:'170 мин=2 ч 50 мин.'},visual:'units',sourceExercise:'№ 441(5)'},
  {id:'l60-zero-model',kind:'model',eyebrow:'№ 442 · нули произведения',title:'Каждый конечный нуль требует пару 2·5',body:'В длинном произведении двоек намного больше, поэтому считаем множители 5. В произведении 1·2·…·100 есть 20 чисел, кратных 5, и ещё четыре дополнительные пятёрки от чисел 25, 50, 75 и 100.',note:'Итого 20+4=24 пары 2·5 и 24 конечных нуля.',visual:'zeros',sourceExercise:'№ 442'},
  {id:'l60-442',kind:'practice',eyebrow:'№ 442(4)',title:'Не забудь дополнительные пятёрки',body:'Числа, кратные 25, содержат не одну, а минимум две пятёрки.',activity:{id:'l60-p18',type:'input',prompt:'Сколькими нулями оканчивается 1·2·3·…·100?',answer:['24'],placeholder:'Число нулей',hint:'⌊100/5⌋+⌊100/25⌋.',explanation:'20+4=24 конечных нуля.'},visual:'zeros',sourceExercise:'№ 442(4)'},
  {id:'l60-angle-model',kind:'model',eyebrow:'№ 443 · геометрическая модель',title:'Две половины складываются в половину прямого угла',body:'Пусть ∠ABK=x°, тогда ∠KBC=90°−x°. Биссектрисы дают половины этих углов, а между ними получается x/2+(90−x)/2.',note:'Не нужно знать положение луча BK: переменная x сокращается.',visual:'angle',sourceExercise:'№ 443'},
  {id:'l60-443',kind:'practice',eyebrow:'№ 443 · вывод',title:'Половина суммы равна сорока пяти',body:'Сумма двух исходных частей — прямой угол 90°.',activity:{id:'l60-p19',type:'input',prompt:'Найди градусную меру угла между биссектрисами BP и BM.',answer:['45','45°'],placeholder:'Градусы',hint:'(x+90−x):2.',explanation:'90°:2=45°.'},visual:'angle',sourceExercise:'№ 443'},
  {id:'l60-heads-model',kind:'model',eyebrow:'№ 444 · головы и ноги',title:'Сначала представь, что все — цыплята',body:'У 14 животных тогда было бы 14·2=28 ног. Фактически ног 38, то есть на 10 больше. Каждый котёнок добавляет ещё 2 ноги, поэтому котят 10:2=5.',note:'Оставшиеся 14−5=9 животных — цыплята.',visual:'heads',sourceExercise:'№ 444'},
  {id:'l60-444',kind:'practice',eyebrow:'№ 444 · проверка модели',title:'Головы и ноги должны совпасть одновременно',body:'Проверка: 5+9=14 голов; 5·4+9·2=38 ног.',activity:{id:'l60-p20',type:'input',prompt:'Запиши количество котят и цыплят через «и».',answer:['5 и 9','5и9'],placeholder:'котята и цыплята',hint:'Лишние 10 ног раздели на 2.',explanation:'5 котят и 9 цыплят.'},visual:'heads',sourceExercise:'№ 444'},
  {id:'l60-travel-model',kind:'model',eyebrow:'№ 445 · сравнение стоимости',title:'Два транспорта — две независимые сметы',body:'Поезд: 1440·2+720=3600 руб. Автомобиль: на 600 км нужно 12·6=72 л, стоимость бензина 72·40=2880 руб.',note:'Сравнивать можно только полные стоимости одного и того же маршрута для всей семьи.',visual:'travel',sourceExercise:'№ 445'},
  {id:'l60-445',kind:'practice',eyebrow:'№ 445 · решение',title:'Автомобиль дешевле на семьсот двадцать рублей',body:'Разность полных стоимостей равна 3600−2880.',activity:{id:'l60-p21',type:'choice',prompt:'Какой итог верен?',options:['Автомобиль дешевле на 720 руб.','Поезд дешевле на 720 руб.','Стоимость одинакова','Автомобиль дешевле на 2880 руб.'],answer:'Автомобиль дешевле на 720 руб.',hint:'Сравни 3600 и 2880.',explanation:'2880<3600, экономия равна 720 руб.'},visual:'travel',sourceExercise:'№ 445'},
  {id:'l60-446-logic',kind:'guided',eyebrow:'№ 446 · логическая таблица',title:'Исключай невозможное, а не угадывай',body:'Футболист самый младший и без сестры: это не Миша и не Дима, значит Саша. Миша старше боксёра, поэтому Миша не боксёр; боксёр — Дима. Мише остаётся плавание.',note:'Ответ: Саша — футбол, Дима — бокс, Миша — плавание.',visual:'logic',sourceExercise:'№ 446'},
  {id:'l60-cross-check',kind:'guided',eyebrow:'Независимая проверка',title:'Каждой модели — свой контроль',body:'Буквенное выражение проверяй обратным раскрытием скобок, величину — переводом в младшие единицы, задачу про животных — одновременно по головам и ногам, а логику — подстановкой всех условий.',note:'Проверка должна использовать исходные данные, а не повторять тот же ошибочный шаг.',visual:'map'},
  {id:'l60-error-diagnosis',kind:'model',eyebrow:'Диагностика',title:'Три ошибки, которые маскируются под короткий путь',body:'Нельзя объединять свободное число с буквенным слагаемым, складывать километры с метрами без перевода и считать только числа, кратные 10, при поиске конечных нулей.',note:'Короткое решение обязано сохранять структуру выражения, единицы и все множители 5.',visual:'error'},
  {id:'l60-final-challenge',kind:'challenge',eyebrow:'Финальный вызов',title:'Одна привычка связывает все задачи',body:'Перед вычислением назови модель, затем выбери свойство и в конце проверь ответ независимо: подстановкой, обратным преобразованием, переводом единиц или проверкой всех условий.',note:'Пример: 93·24−27·24+66·76=66·100=6600, а раскрытие обратно подтверждает исходное выражение.',visual:'map'},
  {id:'l60-summary',kind:'summary',eyebrow:'Урок 60 · итог',title:'§ 17 завершён: ты управляешь стратегией',body:'Ты упростил и вычислил № 430–435, собрал удобные произведения № 436–439, нормализовал величины № 440–441 и построил модели для № 442–446.',note:'Теперь пройди обязательную мастерскую: 20 задач и ровно 50 оцениваемых ответов.',visual:'final'}
];

const plans=[
  {id:'round-hundred',label:'75·36',direct:'75·36=2700',strategy:'75·4·9=300·9=2700',value:2700,before:1,after:0},
  {id:'round-thousand',label:'375·24',direct:'375·24=9000',strategy:'375·8·3=3000·3=9000',value:9000,before:1,after:0},
  {id:'double-factor',label:'Цепочка к 100',direct:'93·24−27·24+66·76=6600',strategy:'66·24+66·76=66·100=6600',value:6600,before:3,after:0}
];
function StrategyLab(){const[index,setIndex]=useState(0);const plan=plans[index];return <div className="strategy-lab" data-strategy-lab="interactive" data-plan-id={plan.id} data-direct-value={plan.value} data-strategy-value={plan.value} data-equal="true" data-awkward-before={plan.before} data-awkward-after={plan.after}><div className="strategy-lab-tabs">{plans.map((item,itemIndex)=><button key={item.id} type="button" className={index===itemIndex?'active':''} onClick={()=>setIndex(itemIndex)}>{item.label}</button>)}</div><div className="strategy-lab-routes"><span><small>обычный маршрут</small><b>{plan.direct}</b><em>неудобных произведений: {plan.before}</em></span><strong>=</strong><span><small>стратегический маршрут</small><b>{plan.strategy}</b><em>неудобных произведений: {plan.after}</em></span></div><p>Значение сохранено: <b>{plan.value.toLocaleString('ru-RU')}</b></p></div>}

function Visual({kind}:{kind:VisualKind}){
  if(kind==='lab')return <StrategyLab/>;
  if(kind==='mission')return <div className="strategy-visual"><div className="strategy-route"><b>увидеть структуру</b><i>→</i><b>выбрать свойство</b><i>→</i><strong>проверить</strong></div></div>;
  if(kind==='map')return <div className="strategy-visual"><div className="strategy-map"><span><b>1</b>общий множитель?</span><span><b>2</b>пара до 100?</span><span><b>3</b>единые величины?</span><span><b>4</b>какая модель?</span></div></div>;
  if(kind==='substitute')return <div className="strategy-visual"><div className="strategy-equation"><span>25x·4y</span><i>→</i><b>100xy</b><i>→</i><strong>13 200</strong></div></div>;
  if(kind==='simplify')return <div className="strategy-visual"><div className="strategy-pairs"><span><small>сначала упростить</small><b>38+17−54+1=2</b><strong>2x</strong></span><span><small>потом подставить</small><b>x=678</b><strong>1 356</strong></span></div></div>;
  if(kind==='pairs')return <div className="strategy-visual"><div className="strategy-pairs"><span><small>к сотне</small><b>75·4</b><strong>300</strong></span><span><small>к тысяче</small><b>375·8</b><strong>3000</strong></span></div></div>;
  if(kind==='chain')return <div className="strategy-visual"><div className="strategy-chain"><span>93·24−27·24</span><i>→</i><b>66·24</b><i>→</i><strong>66·(24+76)</strong><i>→</i><em>6600</em></div></div>;
  if(kind==='units')return <div className="strategy-visual"><div className="strategy-units"><span><b>7 мин 5 с</b><small>425 с</small></span><i>× 24</i><span><b>10 200 с</b><small>170 мин</small></span><i>→</i><strong>2 ч 50 мин</strong></div></div>;
  if(kind==='zeros')return <div className="strategy-visual"><div className="strategy-zeros"><span><small>кратные 5</small><b>⌊100/5⌋=20</b></span><span><small>дополнительные 5</small><b>⌊100/25⌋=4</b></span><strong>24 нуля</strong></div></div>;
  if(kind==='angle')return <div className="strategy-visual"><div className="strategy-angle" aria-label="Прямой угол и две биссектрисы"><svg viewBox="0 0 420 220" role="img"><path d="M70 180 L70 30 M70 180 L360 180 M70 180 L255 68 M70 180 L205 105 M70 180 L300 125"/><text x="50" y="22">A</text><text x="45" y="205">B</text><text x="368" y="202">C</text><text x="260" y="62">P</text><text x="307" y="124">M</text><text x="210" y="102">K</text><text x="210" y="170">45°</text></svg></div></div>;
  if(kind==='heads')return <div className="strategy-visual"><div className="strategy-heads"><span><small>14 цыплят-модель</small><b>28 ног</b></span><i>+10 ног</i><span><small>по +2 на котёнка</small><b>5 котят</b></span><strong>9 цыплят</strong></div></div>;
  if(kind==='travel')return <div className="strategy-visual"><div className="strategy-travel"><span><small>поезд</small><b>3600 ₽</b></span><span><small>автомобиль</small><b>2880 ₽</b></span><strong>экономия 720 ₽</strong></div></div>;
  if(kind==='logic')return <div className="strategy-visual"><div className="strategy-logic"><span><b>Саша</b><strong>футбол</strong></span><span><b>Дима</b><strong>бокс</strong></span><span><b>Миша</b><strong>плавание</strong></span></div></div>;
  if(kind==='error')return <div className="strategy-visual"><div className="strategy-errors"><del>50c+296=346c</del><strong>разные части</strong><del>139 808 м=139 км 8 м</del><strong>верно 139 км 808 м</strong><del>100! оканчивается 20 нулями</del><strong>учти кратные 25 → 24</strong></div></div>;
  return <div className="strategy-visual"><div className="strategy-final"><b>№ 430–435 ✓</b><b>№ 436–439 ✓</b><b>№ 440–441 ✓</b><b>№ 442 ✓</b><b>№ 443–446 ✓</b><b>50 ответов →</b></div></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixtyStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function MultiplicationStrategiesPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonSixtyStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==60||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonSixtyStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonSixtyStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player multiplication-strategies-player" data-lesson-number="60" data-source-reference="Мерзляк § 17 · № 430–446" data-source-exercise-range="430-446"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
