import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';
import './naturalComparison.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='mission'|'digits'|'lexicographic'|'signs'|'double'|'zero'|'error'|'algorithm'|'challenge';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};

const KEY='mathnikita-lesson-16-progress-v1';

export const lessonSixteenStages:Stage[]=[
{id:'l16-mission',kind:'story',eyebrow:'Новая тема · § 6',title:'Кто больше — и как это доказать?',body:'Сравнение чисел нужно не только для ответа «больше» или «меньше». Важно быстро найти решающий разряд, поставить правильный знак и объяснить ход рассуждения.',note:'Сначала сравни количество цифр. Если оно одинаково — ищи первую различающуюся цифру слева.',sourceTag:'Мерзляк § 6, технологическая карта урока 16',visual:'mission'},
{id:'l16-diagnostic',kind:'guided',eyebrow:'Диагностика',title:'Выбери верное объяснение',body:'Числа 9 876 и 10 032 выглядят близкими, но сравнивать все цифры не требуется.',activity:{id:'l16-a1',type:'choice',prompt:'Почему 10 032 больше 9 876?',options:['У числа 10 032 больше цифр','В числе 10 032 есть ноль','9 меньше 10','Нужно сложить цифры обоих чисел'],answer:'У числа 10 032 больше цифр',explanation:'Пятизначное натуральное число больше любого четырёхзначного.'}},
{id:'l16-digits-model',kind:'model',eyebrow:'Правило 1',title:'Разное количество цифр',body:'Из двух натуральных чисел с разным количеством цифр больше то, в записи которого цифр больше. Поэтому 84 215 > 9 999.',note:'Это правило работает для натуральных чисел без ведущих нулей.',visual:'digits'},
{id:'l16-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Сравнение по длине записи',body:'Не выполняй вычислений — достаточно посчитать цифры.',activity:{id:'l16-p1',type:'choice',prompt:'Какой знак нужно поставить: 78 405 □ 9 999?',options:['>','<','='],answer:'>',explanation:'78 405 — пятизначное число, а 9 999 — четырёхзначное.'}},
{id:'l16-same-length',kind:'model',eyebrow:'Правило 2',title:'Одинаковое количество цифр',body:'Если цифр поровну, сравнивай разряды слева направо. Как только встретилась первая неодинаковая пара цифр, дальнейшие разряды уже не влияют на результат.',note:'В сравнении 564 321 и 564 370 решающими являются десятки: 2 < 7.',visual:'lexicographic'},
{id:'l16-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Первая различающаяся цифра',body:'Найди разряд, который решает сравнение.',activity:{id:'l16-p2',type:'choice',prompt:'Какой знак верен: 302 701 □ 302 170?',options:['>','<','='],answer:'>',explanation:'Первые три цифры равны. В разряде сотен 7 > 1, значит первое число больше.'}},
{id:'l16-signs',kind:'model',eyebrow:'Математическая запись',title:'Знаки >, < и = читаются направленно',body:'Острый конец знака показывает на меньшее число, раскрытая сторона — на большее. Записи 17 < 25 и 25 > 17 выражают один и тот же факт.',note:'Всегда читай неравенство слева направо.',visual:'signs'},
{id:'l16-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Запись результата',body:'В ответе нужен только знак.',activity:{id:'l16-p3',type:'input',prompt:'Поставь знак: 640 089 □ 640 098',answer:'<',placeholder:'>, < или =',explanation:'Первые четыре цифры совпадают, затем 8 < 9, поэтому 640 089 < 640 098.'}},
{id:'l16-zero-model',kind:'model',eyebrow:'Важный случай',title:'Ноль меньше любого натурального числа',body:'Ноль не является натуральным числом в принятой в учебнике нумерации, но его можно сравнивать с натуральными: 0 < 1, 0 < 58, 0 < 1 000 000.',note:'Запись 0 057 — это число 57, а не четырёхзначное натуральное число.',visual:'zero'},
{id:'l16-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Ведущие нули не увеличивают число',body:'Сравни значения, а не визуальную длину записи.',activity:{id:'l16-p4',type:'choice',prompt:'Какой знак верен: 004 208 □ 4 208?',options:['>','<','='],answer:'=',explanation:'Ведущие нули не меняют значение числа: обе записи обозначают 4 208.'}},
{id:'l16-double-model',kind:'model',eyebrow:'Двойное неравенство',title:'Число между двумя границами',body:'Запись 120 < x < 125 означает сразу два условия: x больше 120 и одновременно меньше 125. Натуральные решения: 121, 122, 123, 124.',note:'В строгом двойном неравенстве границы не входят в ответ.',visual:'double'},
{id:'l16-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Все числа внутри границ',body:'Запиши решения по возрастанию через запятую.',activity:{id:'l16-p5',type:'input',prompt:'Запиши все натуральные x, для которых 734 < x < 739.',answer:'735,736,737,738',placeholder:'Например: 4,5,6',explanation:'Подходят четыре числа: 735, 736, 737 и 738.'}},
{id:'l16-algorithm',kind:'model',eyebrow:'Алгоритм',title:'Сравнение без лишних действий',body:'Правильный алгоритм сокращает работу: сначала длина записи, затем разряды слева направо, после первой разницы — знак и проверка чтением.',note:'Сумма цифр, последняя цифра и величина отдельных «красивых» разрядов сами по себе ничего не доказывают.',visual:'algorithm'},
{id:'l16-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Собери алгоритм',body:'Расположи действия в рабочем порядке.',activity:{id:'l16-p6',type:'order',prompt:'Как сравнить два натуральных числа?',items:['Сравнить количество цифр','Если цифр поровну, сравнивать разряды слева направо','Остановиться на первой различающейся цифре','Поставить знак >, < или =','Прочитать запись и проверить смысл'],answer:['Сравнить количество цифр','Если цифр поровну, сравнивать разряды слева направо','Остановиться на первой различающейся цифре','Поставить знак >, < или =','Прочитать запись и проверить смысл'],explanation:'Алгоритм идёт от самого сильного признака к решающему разряду и смысловой проверке.'}},
{id:'l16-error-check',kind:'guided',eyebrow:'Разбор ошибки',title:'Почему сравнение неверно?',body:'Ученик записал: 52 999 > 103 001, потому что 5 > 1.',activity:{id:'l16-a2',type:'choice',prompt:'Как исправить рассуждение?',options:['52 999 < 103 001, потому что второе число шестизначное','52 999 > 103 001, потому что 9 > 0','Числа равны после округления','Нужно сравнить суммы цифр'],answer:'52 999 < 103 001, потому что второе число шестизначное',explanation:'Количество цифр сравнивается раньше разрядов: любое шестизначное натуральное число больше любого пятизначного.'},visual:'error'},
{id:'l16-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Разное количество цифр',body:'Работай самостоятельно.',activity:{id:'l16-q1',type:'choice',prompt:'Выбери верную запись.',options:['99 999 > 100 000','99 999 < 100 000','99 999 = 100 000'],answer:'99 999 < 100 000',explanation:'100 000 — шестизначное число, 99 999 — пятизначное.'}},
{id:'l16-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Поразрядное сравнение',body:'Работай самостоятельно.',activity:{id:'l16-q2',type:'input',prompt:'Поставь знак: 7 308 019 □ 7 309 019',answer:'<',placeholder:'Знак',explanation:'Первые четыре цифры совпадают, затем 8 < 9.'}},
{id:'l16-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Наименьшее подходящее число',body:'Работай самостоятельно.',activity:{id:'l16-q3',type:'input',prompt:'Какое наименьшее натуральное m делает неравенство m > 4 608 верным?',answer:'4609',placeholder:'Число',explanation:'Следующее натуральное число после 4 608 — это 4 609.'}},
{id:'l16-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Наибольшее число перед границей',body:'Работай самостоятельно.',activity:{id:'l16-q4',type:'input',prompt:'Какое наибольшее натуральное n делает неравенство n < 31 080 верным?',answer:'31079',placeholder:'Число',explanation:'Предыдущее натуральное число перед 31 080 — это 31 079.'}},
{id:'l16-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Двойное неравенство',body:'Работай самостоятельно.',activity:{id:'l16-q5',type:'input',prompt:'Сколько натуральных решений имеет неравенство 2 015 < x < 2 021?',answer:'5',placeholder:'Количество',explanation:'Решения: 2 016, 2 017, 2 018, 2 019, 2 020 — всего 5.'}},
{id:'l16-challenge',kind:'challenge',eyebrow:'Олимпиадная задача',title:'Максимальное число из заданных цифр',body:'Используй каждую цифру 0, 2, 4, 7, 9 ровно один раз. Получившееся число должно быть меньше 90 000.',activity:{id:'l16-c1',type:'input',prompt:'Какое наибольшее число можно составить?',answer:'79420',placeholder:'Число',explanation:'Первая цифра не может быть 9, иначе число будет не меньше 90 000. Берём 7, а остальные цифры ставим по убыванию: 79 420.'},visual:'challenge'},
{id:'l16-transfer',kind:'guided',eyebrow:'Перенос знания',title:'Сравнение в реальной ситуации',body:'В двух школьных библиотеках 98 750 и 101 200 книг.',activity:{id:'l16-a3',type:'choice',prompt:'Какое объяснение корректно?',options:['101 200 больше, потому что это шестизначное число','98 750 больше, потому что первая цифра 9','Нужно сначала сложить цифры','Сравнить нельзя без калькулятора'],answer:'101 200 больше, потому что это шестизначное число',explanation:'Шестизначное число 101 200 больше пятизначного 98 750.'}},
{id:'l16-reflection',kind:'model',eyebrow:'Рефлексия',title:'Теперь сравнение — это алгоритм, а не догадка',body:'Ты умеешь сравнивать числа по количеству цифр и поразрядно, читать знаки, работать с нулём, находить числа между границами и исправлять неверные рассуждения.',visual:'algorithm'},
{id:'l16-summary',kind:'summary',eyebrow:'Итог урока 16',title:'Первый урок § 6 завершён',body:'Следующий урок свяжет сравнение с расположением точек на координатном луче и даст больше составных задач.',visual:'mission'},
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е').replace(/[;]+/g,',')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function ComparisonVisual({kind}:{kind:Visual}){
  if(kind==='digits')return <div className="comparison-visual"><div className="comparison-caption"><b>84 215</b><span>5 цифр</span><strong>&gt;</strong><b>9 999</b><span>4 цифры</span></div></div>;
  if(kind==='lexicographic')return <div className="comparison-visual"><div className="digit-rows"><div><span>5</span><span>6</span><span>4</span><mark>3</mark><span>2</span><span>1</span></div><div><span>5</span><span>6</span><span>4</span><mark>3</mark><span>7</span><span>0</span></div></div><p>Первая разница слева: 2 &lt; 7</p></div>;
  if(kind==='signs')return <div className="comparison-visual sign-visual"><div><b>17</b><strong>&lt;</strong><b>25</b></div><span>острый конец смотрит на меньшее число</span></div>;
  if(kind==='double')return <div className="comparison-visual"><div className="double-strip"><b>120</b><span>121</span><span>122</span><span>123</span><span>124</span><b>125</b></div><p>120 &lt; x &lt; 125</p></div>;
  if(kind==='zero')return <div className="comparison-visual"><div className="comparison-caption"><b>0</b><strong>&lt;</strong><b>1</b><strong>&lt;</strong><b>58</b><strong>&lt;</strong><b>1 000 000</b></div></div>;
  if(kind==='error')return <div className="comparison-visual error-visual"><s>52 999 &gt; 103 001</s><b>52 999 &lt; 103 001</b><span>5 цифр &lt; 6 цифр</span></div>;
  if(kind==='algorithm')return <div className="comparison-visual"><div className="comparison-steps"><div><b>1</b>Количество цифр</div><div><b>2</b>Разряды слева</div><div><b>3</b>Первая разница</div><div><b>4</b>Знак и чтение</div></div></div>;
  if(kind==='challenge')return <div className="comparison-visual"><div className="digit-cards">{['0','2','4','7','9'].map(digit=><span key={digit}>{digit}</span>)}</div><p>Составь максимум, но меньше 90 000</p></div>;
  return <div className="comparison-visual mission-visual"><div><b>?</b><span>Какое число больше?</span></div><div><b>✓</b><span>Как это доказать?</span></div></div>;
}

export function NaturalNumberComparisonPlayer(){
  const saved=useMemo(load,[]);
  const[stageIndex,setStageIndex]=useState(saved.stageIndex);
  const[responses,setResponses]=useState(saved.responses);
  const[orders,setOrders]=useState(saved.orders);
  const[checked,setChecked]=useState(saved.checked);
  const[results,setResults]=useState(saved.results);
  const[completedAt,setCompletedAt]=useState(saved.completedAt);
  const stage=lessonSixteenStages[stageIndex];
  const activity=stage.activity;
  const answer=activity?responses[activity.id]??'':'';
  const ordered=activity?orders[activity.id]??[]:[];
  const isChecked=activity?Boolean(checked[activity.id]):false;
  const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l16-q1','l16-q2','l16-q3','l16-q4','l16-q5'];
  const practice=['l16-p1','l16-p2','l16-p3','l16-p4','l16-p5','l16-p6'];
  const quizScore=quiz.filter(id=>results[id]).length;
  const practiceScore=practice.filter(id=>results[id]).length;
  const progress=Math.round(((stageIndex+1)/lessonSixteenStages.length)*100);

  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
  useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===16&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);

  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonSixteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];
    return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }

  return <main className="lesson-player-page natural-comparison-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 16 из 175 · § 6</span><h1>Сравнение натуральных чисел</h1><p>Количество цифр, поразрядное сравнение, знаки неравенств и числа между границами.</p></div><div className="lesson-duration">43 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonSixteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<ComparisonVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Вернись к алгоритму и найди первый решающий признак. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Контроль</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус урока</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonSixteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
