import { useEffect, useMemo, useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './placeValueMastery.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type PlaceValueStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};
const KEY='mathnikita-lesson-4-progress-v1';

export const lessonFourStages:PlaceValueStage[]=[
{id:'l4-story',kind:'story',eyebrow:'Разрядный детектив',title:'Почему три одинаковые цифры означают разное?',body:'На панели записано число 7 070 007. Цифра 7 встречается три раза, но обозначает семь миллионов, семьдесят тысяч и семь единиц.',note:'Значение цифры определяется не её видом, а местом в записи числа.',sourceTag:'Мерзляк § 2 · урок закрепления'},
{id:'l4-ladder',kind:'model',eyebrow:'Десятичная лестница',title:'Каждый шаг влево увеличивает значение в 10 раз',body:'Единицы, десятки, сотни, тысячи и следующие разряды образуют позиционную систему. Одна единица соседнего разряда слева равна десяти единицам разряда справа.',activity:{id:'l4-a1',type:'choice',prompt:'Во сколько раз 1 тысяча больше 1 сотни?',options:['в 2 раза','в 5 раз','в 10 раз','в 100 раз'],answer:'в 10 раз',explanation:'1 000 = 10 · 100, поэтому соседние разряды отличаются в 10 раз.'}},
{id:'l4-same-digit',kind:'guided',eyebrow:'Одна цифра — три значения',title:'Читаем разрядное значение цифры',body:'В числе 7 070 007 крайняя слева цифра 7 означает 7 000 000, средняя — 70 000, крайняя справа — 7.',activity:{id:'l4-a2',type:'choice',prompt:'Что означает средняя цифра 7 в числе 7 070 007?',options:['7 000','70 000','700 000','7 000 000'],answer:'70 000',explanation:'Она стоит в разряде десятков тысяч, поэтому обозначает 70 000.'}},
{id:'l4-zero',kind:'guided',eyebrow:'Нуль работает',title:'Нули удерживают пустые разряды',body:'В записи 7 070 007 нули показывают, что некоторые разряды не содержат единиц. Если удалить нули, остальные цифры сдвинутся и получится другое число.',activity:{id:'l4-a3',type:'choice',prompt:'Как изменится число 405, если удалить нуль?',options:['не изменится','получится 45','получится 4050','получится 4005'],answer:'получится 45',explanation:'Нуль удерживал разряд десятков. После удаления цифра 4 перемещается из сотен в десятки.'}},
{id:'l4-classes',kind:'model',eyebrow:'Классы и разряды',title:'В каждом классе по три разряда',body:'Классы идут справа налево: единиц, тысяч, миллионов, миллиардов. Внутри каждого класса находятся сотни, десятки и единицы этого класса.',note:'Например: сотни миллионов, десятки миллионов, единицы миллионов.'},
{id:'l4-double-name',kind:'guided',eyebrow:'Точный адрес цифры',title:'Двойное название разряда задаёт одно место',body:'Фраза «десятки миллионов» одновременно называет положение внутри класса и сам класс. Такой адрес невозможно перепутать с десятками тысяч или обычными десятками.',activity:{id:'l4-a4',type:'choice',prompt:'Где стоит цифра 8 в числе 481 207 036?',options:['в единицах миллионов','в десятках миллионов','в сотнях миллионов','в десятках тысяч'],answer:'в десятках миллионов',explanation:'Класс миллионов равен 481: 4 сотни миллионов, 8 десятков миллионов, 1 единица миллионов.'}},
{id:'l4-split',kind:'practice',eyebrow:'Практика · 1/6',title:'Раздели число на классы',body:'Начинай справа и отделяй группы по три цифры. Левый класс может содержать одну, две или три цифры.',activity:{id:'l4-p1',type:'input',prompt:'Раздели число 50803100407 на классы пробелами',answer:'50 803 100 407',placeholder:'Например: 12 345 678',explanation:'Справа получаются классы 407, 100, 803 и 50: 50 803 100 407.'}},
{id:'l4-read',kind:'practice',eyebrow:'Практика · 2/6',title:'Прочитай число с нулевыми разрядами',body:'Внутри ненулевого класса нули сохраняют позиции. Полностью нулевой класс при чтении пропускают.',activity:{id:'l4-p2',type:'choice',prompt:'Как правильно прочитать 4 006 020?',options:['четыре миллиона шесть тысяч двадцать','четыре миллиона шестьсот двадцать','четыре тысячи шестьсот двадцать','четыре миллиона ноль тысяч двадцать'],answer:'четыре миллиона шесть тысяч двадцать',explanation:'Классы: 4 миллиона, 006 тысяч, 020 единиц.'}},
{id:'l4-write',kind:'practice',eyebrow:'Практика · 3/6',title:'Запиши число по названию',body:'Для каждого класса оставляй три места. Отсутствующий класс заполняй тремя нулями.',activity:{id:'l4-p3',type:'input',prompt:'Запиши цифрами: триста два миллиона семьдесят тысяч пять',answer:'302070005',placeholder:'Только цифры',explanation:'Классы: 302 | 070 | 005, поэтому число равно 302 070 005.'}},
{id:'l4-expanded',kind:'model',eyebrow:'Разрядная сумма',title:'Разложение показывает вклад каждой цифры',body:'Число 905 040 300 состоит из 900 000 000, 5 000 000, 40 000 и 300. Слагаемые нулевых разрядов не записывают.',note:'Разрядное слагаемое равно цифре, умноженной на единицу её разряда.'},
{id:'l4-expand-practice',kind:'practice',eyebrow:'Практика · 4/6',title:'Выбери верное разложение',body:'Проверяй каждую ненулевую цифру и её место.',activity:{id:'l4-p4',type:'choice',prompt:'Как разложить 905 040 300?',options:['900 000 000 + 5 000 000 + 40 000 + 300','900 000 000 + 5 000 000 + 4 000 + 300','90 000 000 + 5 000 000 + 40 000 + 300','900 000 000 + 500 000 + 40 000 + 300'],answer:'900 000 000 + 5 000 000 + 40 000 + 300',explanation:'Цифра 5 стоит в единицах миллионов, а 4 — в десятках тысяч.'}},
{id:'l4-compose',kind:'practice',eyebrow:'Практика · 5/6',title:'Собери число из разрядных слагаемых',body:'Поставь каждую цифру в её разряд и заполни пустые позиции нулями.',activity:{id:'l4-p5',type:'input',prompt:'Собери число: 600 000 000 + 20 000 + 9',answer:'600020009',placeholder:'Только цифры',explanation:'Получаем классы 600 | 020 | 009, то есть 600 020 009.'}},
{id:'l4-place-name',kind:'practice',eyebrow:'Практика · 6/6',title:'Найди разряд по адресу',body:'Сначала выдели нужный класс, затем определи место цифры внутри него.',activity:{id:'l4-p6',type:'choice',prompt:'Какой разряд занимает цифра 8 в числе 481 207 036?',options:['единицы миллионов','десятки миллионов','сотни миллионов','единицы тысяч'],answer:'десятки миллионов',explanation:'В классе миллионов 481 цифра 8 стоит посередине — в десятках миллионов.'}},
{id:'l4-total-ranks',kind:'guided',eyebrow:'Тонкое различие',title:'Цифра разряда и количество полных разрядных единиц — не одно и то же',body:'В числе 47 305 цифра сотен равна 3, но всего в числе содержится 473 полные сотни. Первое — цифра на месте, второе — результат деления на 100 без остатка.',activity:{id:'l4-a5',type:'input',prompt:'Сколько полных сотен содержится в числе 82 649?',answer:'826',explanation:'82 649 = 826 · 100 + 49, поэтому в числе 826 полных сотен.'}},
{id:'l4-order',kind:'guided',eyebrow:'Универсальный алгоритм',title:'Как разбирать любое многозначное число',body:'Работай в одном порядке: раздели на классы, подпиши классы, найди нужный разряд, определи значение цифры и проверь разложением.',activity:{id:'l4-a6',type:'order',prompt:'Расставь шаги разбора числа',items:['Разделить запись справа по три цифры','Подписать классы','Найти разряд внутри класса','Определить значение цифры'],answer:['Разделить запись справа по три цифры','Подписать классы','Найти разряд внутри класса','Определить значение цифры'],explanation:'Классы создают карту числа, после чего легко найти точный разряд и значение цифры.'}},
{id:'l4-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Разрядное значение',body:'Ответь без подсказки.',activity:{id:'l4-q1',type:'choice',prompt:'Что означает цифра 6 в числе 2 064 105?',options:['6 000','60 000','600 000','6 000 000'],answer:'60 000',explanation:'Цифра 6 стоит в разряде десятков тысяч.'}},
{id:'l4-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Количество классов',body:'Ответь без подсказки.',activity:{id:'l4-q2',type:'input',prompt:'Сколько классов в числе 90 004 000 021?',answer:'4',explanation:'Классы: миллиарды, миллионы, тысячи и единицы.'}},
{id:'l4-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Сборка числа',body:'Ответь без подсказки.',activity:{id:'l4-q3',type:'input',prompt:'Собери: 700 000 000 + 300 000 + 40 + 2',answer:'700300042',explanation:'Получаем 700 300 042.'}},
{id:'l4-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Адрес цифры',body:'Ответь без подсказки.',activity:{id:'l4-q4',type:'choice',prompt:'В каком числе цифра 5 стоит в разряде десятков тысяч?',options:['205 013','250 013','502 013','520 013'],answer:'250 013',explanation:'В числе 250 013 класс тысяч равен 250, и цифра 5 занимает разряд десятков тысяч.'}},
{id:'l4-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Полные сотни',body:'Ответь без подсказки.',activity:{id:'l4-q5',type:'input',prompt:'Сколько полных сотен в числе 47 305?',answer:'473',explanation:'47 305 = 473 · 100 + 5.'}},
{id:'l4-challenge',kind:'challenge',eyebrow:'Исследовательская задача',title:'Числа из цифр 0, 0, 2 и 5',body:'Используй все четыре цифры ровно по одному разу. Запись четырёхзначного числа не может начинаться с нуля.',activity:{id:'l4-c1',type:'input',prompt:'Сколько различных четырёхзначных чисел можно составить?',answer:'6',explanation:'Получаются 2005, 2050, 2500, 5002, 5020 и 5200 — всего 6 чисел.'}},
{id:'l4-summary',kind:'summary',eyebrow:'Итог основной части',title:'Разрядная карта числа освоена',body:'Ты прошёл объяснение, практику и мини-проверку основной части. Дальше обязательна расширенная практика: только после неё и собственного объяснения урок получит статус «завершён».'}
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFourStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

export function PlaceValueMasteryPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);
  const stage=lessonFourStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l4-q1','l4-q2','l4-q3','l4-q4','l4-q5'];const practice=['l4-p1','l4-p2','l4-p3','l4-p4','l4-p5','l4-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonFourStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
  useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===4&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonFourStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);localStorage.removeItem('mathnikita:lesson-complete:4');localStorage.removeItem('mathnikita:reflection:4');localStorage.removeItem('mathnikita:extended-practice:4:v1');setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
  const model=useMemo(()=>{
    if(['l4-story','l4-same-digit','l4-zero'].includes(stage.id))return <div className="l4-value-map"><b>7 070 007</b><div><span><i>7</i><small>7 000 000</small></span><span><i>7</i><small>70 000</small></span><span><i>7</i><small>7</small></span></div></div>;
    if(stage.id==='l4-ladder')return <div className="l4-place-ladder">{[['млн','1 000 000'],['сот. тыс.','100 000'],['дес. тыс.','10 000'],['тыс.','1 000'],['сот.','100'],['дес.','10'],['ед.','1']].map(([name,value])=><div key={name}><small>{name}</small><b>{value}</b></div>)}</div>;
    if(['l4-classes','l4-double-name','l4-split','l4-read','l4-write'].includes(stage.id))return <div className="l4-class-map">{[['миллиарды','50'],['миллионы','803'],['тысячи','100'],['единицы','407']].map(([name,value])=><div key={name}><small>{name}</small><b>{value}</b><span>сотни · десятки · единицы</span></div>)}</div>;
    if(['l4-expanded','l4-expand-practice','l4-compose'].includes(stage.id))return <div className="l4-expanded-model"><b>905 040 300</b><i>→</i><span>900 000 000</span><span>5 000 000</span><span>40 000</span><span>300</span></div>;
    if(stage.id==='l4-total-ranks'||stage.id==='l4-quiz5')return <div className="l4-full-hundreds"><b>47 305</b><div><span>цифра сотен</span><strong>3</strong></div><div><span>полных сотен</span><strong>473</strong></div></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page place-value-mastery-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 4 из 175 · § 2</span><h1>Разряды числа: закрепление</h1><p>Урок закрепляет чтение и запись больших натуральных чисел, классы, разряды, роль нулей и разрядные слагаемые.</p></div><div className="lesson-duration">Основная часть</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonFourStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь классы, разряды и положение каждой цифры. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Основная часть ✓':'Повторить'}</b><small>{quizScore>=4&&practiceScore>=5?'впереди обязательная практика':completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% основной части</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonFourStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
