import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './planeLineRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type PlaneLineRayStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-10-progress-v2';
const LEGACY_KEY='mathnikita-lesson-10-progress-v1';

export const lessonTenStages:PlaneLineRayStage[]=[
  {id:'l10-story',kind:'story',eyebrow:'Новая тема § 4',title:'Плоскость нельзя дорисовать до края',body:'Лист тетради, стол или футбольное поле дают представление только о части плоскости. Сама плоскость бесконечна, поэтому целиком изобразить её невозможно.',note:'Сегодня познакомимся с плоскостью, прямой и лучом и научимся различать их по главным свойствам.',sourceTag:'Мерзляк § 4 · урок 10 · изучение нового материала'},
  {id:'l10-plane',kind:'model',eyebrow:'Плоскость',title:'Рисунок показывает только часть бесконечной плоскости',body:'Плоскость можно вообразить как бесконечное продолжение ровной поверхности во все стороны. Любой рисунок плоскости показывает лишь её фрагмент.',note:'Плоскость бесконечна.',sourceTag:'Мерзляк § 4 · теоретический материал'},
  {id:'l10-plane-check',kind:'guided',eyebrow:'Узнаём модель',title:'Предмет показывает лишь часть плоскости',body:'В учебнике примерами моделей части плоскости служат лист, стол, теннисный корт и футбольное поле.',activity:{id:'l10-a1',type:'choice',prompt:'Что лучше всего служит моделью части плоскости?',options:['поверхность стола','одна точка','верёвка с узлом','край линейки'],answer:'поверхность стола',explanation:'Ровная поверхность стола может служить моделью части плоскости, но сама плоскость бесконечна.'},sourceTag:'Мерзляк § 4 · вводный пример'},
  {id:'l10-line',kind:'model',eyebrow:'Прямая',title:'Продлим отрезок в обе стороны без конца',body:'Если отрезок мысленно неограниченно продолжать в обе стороны, получим прямую. На рисунке всегда видна только часть прямой.',note:'Прямая не имеет концов и бесконечна.',sourceTag:'Мерзляк § 4 · прямая'},
  {id:'l10-one-line',kind:'model',eyebrow:'Свойство прямой',title:'Две точки определяют одну прямую',body:'Отметим две различные точки A и B. Через них можно провести прямую, а провести через те же две точки другую прямую уже не получится.',note:'Через две различные точки проходит только одна прямая.',sourceTag:'Мерзляк § 4 · свойство прямой'},
  {id:'l10-one-line-check',kind:'guided',eyebrow:'Проверяем свойство',title:'Не путай прямую с множеством кривых путей',body:'Между двумя точками можно нарисовать много кривых, но прямую через них — только одну.',activity:{id:'l10-a2',type:'input',prompt:'Сколько прямых проходит через две различные точки?',answer:'1',placeholder:'Количество прямых',explanation:'Через две различные точки проходит ровно одна прямая.'}},
  {id:'l10-line-names',kind:'model',eyebrow:'Обозначение',title:'Прямую можно назвать по двум точкам или одной строчной буквой',body:'Прямую через точки A и B обозначают AB или BA. Также прямые обозначают одной строчной латинской буквой, например m.',note:'Для прямой порядок A и B не меняет саму прямую: AB и BA — одна и та же прямая.',sourceTag:'Мерзляк § 4 · обозначение прямой'},
  {id:'l10-name-check',kind:'guided',eyebrow:'Читаем обозначения',title:'У прямой несколько корректных имён',body:'Пусть точки A и B лежат на прямой m.',activity:{id:'l10-a3',type:'choice',prompt:'Как можно обозначить эту прямую?',options:['AB, BA или m','только AB','только BA','OA или AO'],answer:'AB, BA или m',explanation:'Прямую можно назвать по двум любым её точкам в любом порядке либо одной строчной латинской буквой.'}},
  {id:'l10-ray',kind:'model',eyebrow:'Луч',title:'Одна точка делит прямую на два луча',body:'Если на прямой отметить точку O, она разделит прямую на две части. Каждую часть вместе с точкой O называют лучом с началом в O.',note:'У луча есть начало, но нет конца.',sourceTag:'Мерзляк § 4 · луч'},
  {id:'l10-ray-check',kind:'guided',eyebrow:'Обозначение луча',title:'Первая буква — начало луча',body:'Луч обозначают двумя прописными буквами: сначала начало, затем любую другую точку этого луча.',activity:{id:'l10-a4',type:'choice',prompt:'Как обозначить луч с началом O, проходящий через A?',options:['OA','AO','AB','m'],answer:'OA',explanation:'В обозначении луча первой записывают букву его начала: OA.'}},
  {id:'l10-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Узнай прямую по свойству',body:'Сравни признаки отрезка, луча и прямой.',activity:{id:'l10-p1',type:'choice',prompt:'Какая фигура не имеет концов и продолжается в обе стороны?',options:['прямая','луч','отрезок','точка'],answer:'прямая',explanation:'Прямая бесконечна в обе стороны и не имеет концов.'}},
  {id:'l10-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Точка на прямой рождает два направления',body:'Отметим на прямой точку M.',activity:{id:'l10-p2',type:'input',prompt:'На сколько лучей точка M делит прямую?',answer:'2',placeholder:'Количество лучей',explanation:'Любая точка прямой делит её на два луча с общим началом M.'},sourceTag:'Мерзляк § 4 · определение луча'},
  {id:'l10-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Начало луча определяет порядок букв',body:'Точки K и P лежат на одном луче, причём начало луча — K.',activity:{id:'l10-p3',type:'choice',prompt:'Как обозначить этот луч по точкам K и P?',options:['KP','PK','только p','PP'],answer:'KP',explanation:'В обозначении луча первая буква всегда обозначает его начало, поэтому это луч KP.'}},
  {id:'l10-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Два луча с общим началом',body:'Точки A, O и B лежат на одной прямой, O находится между A и B.',activity:{id:'l10-p4',type:'choice',prompt:'Какие два луча задаёт точка O?',options:['OA и OB','AO и BO','AB и BA','OA и BA'],answer:'OA и OB',explanation:'Точка O является общим началом двух частей прямой — лучей OA и OB.'}},
  {id:'l10-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Построй прямую через две точки',body:'Порядок построения следует свойству прямой.',activity:{id:'l10-p5',type:'order',prompt:'Расставь шаги построения прямой AB',items:['Продолжить изображение в обе стороны','Провести линию через обе точки','Отметить две различные точки A и B','Приложить линейку к точкам A и B'],answer:['Отметить две различные точки A и B','Приложить линейку к точкам A и B','Провести линию через обе точки','Продолжить изображение в обе стороны'],explanation:'Две точки однозначно задают прямую; на чертеже показываем лишь её часть и продолжаем в обе стороны.'}},
  {id:'l10-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Модель из окружающего мира',body:'Модель должна передавать главное свойство: один фиксированный старт и продолжение в одном направлении.',activity:{id:'l10-p6',type:'choice',prompt:'Что ближе всего к модели луча?',options:['тонкий луч света, идущий от источника в одном направлении','ровная поверхность стола','линия, мысленно продолженная в обе стороны','отрезок между двумя метками'],answer:'тонкий луч света, идущий от источника в одном направлении',explanation:'У модели луча есть начало и одно направление продолжения.'},sourceTag:'Методическое пособие · урок 10 · модели в окружающем мире'},
  {id:'l10-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Плоскость',body:'Без подсказки.',activity:{id:'l10-q1',type:'choice',prompt:'Какое утверждение о плоскости верно?',options:['плоскость бесконечна','плоскость имеет два конца','плоскость — это отрезок','плоскость всегда ограничена листом'],answer:'плоскость бесконечна',explanation:'Лист или экран показывают только часть бесконечной плоскости.'}},
  {id:'l10-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Свойство прямой',body:'Без подсказки.',activity:{id:'l10-q2',type:'input',prompt:'Сколько прямых проходит через две различные точки?',answer:'1',placeholder:'Количество',explanation:'Через две различные точки проходит только одна прямая.'}},
  {id:'l10-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Концы прямой',body:'Без подсказки.',activity:{id:'l10-q3',type:'input',prompt:'Сколько концов у прямой?',answer:'0',placeholder:'Количество концов',explanation:'У прямой нет концов; она бесконечна в обе стороны.'}},
  {id:'l10-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Начало луча',body:'Без подсказки.',activity:{id:'l10-q4',type:'choice',prompt:'В обозначении луча OA какая точка является началом?',options:['O','A','обе','ни одна'],answer:'O',explanation:'Первая буква обозначения луча указывает его начало.'}},
  {id:'l10-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Деление прямой точкой',body:'Без подсказки.',activity:{id:'l10-q5',type:'input',prompt:'Сколько лучей с общим началом образуются, если отметить одну точку на прямой?',answer:'2',placeholder:'Количество',explanation:'Точка делит прямую на две части, каждая из которых вместе с точкой является лучом.'}},
  {id:'l10-challenge',kind:'challenge',eyebrow:'Исследование',title:'Три точки — сколько прямых?',body:'Точки A, B и C не лежат на одной прямой. Для каждой пары точек можно применить свойство: через две различные точки проходит только одна прямая.',activity:{id:'l10-c1',type:'input',prompt:'Сколько разных прямых задают пары AB, AC и BC?',answer:'3',placeholder:'Количество прямых',explanation:'Есть три пары точек: AB, AC и BC. Так как точки не лежат на одной прямой, получаются три разные прямые.'}},
  {id:'l10-summary',kind:'summary',eyebrow:'Итог основной части',title:'Плоскость, прямая и луч больше не смешиваются',body:'Ты прошёл основную часть: отличил плоскость, прямую и луч, применил главное свойство прямой, разобрал обозначения и модели. Полный урок завершится только после обязательной практики и собственного объяснения.',note:'Плоскость бесконечна. Прямая не имеет концов. Через две различные точки проходит одна прямая. Луч имеет начало и не имеет конца.'}
];

const empty:Saved={version:2,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonTenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

export function PlaneLineRayPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
  const stage=lessonTenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l10-q1','l10-q2','l10-q3','l10-q4','l10-q5'];const practice=['l10-p1','l10-p2','l10-p3','l10-p4','l10-p5','l10-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonTenStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===10&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonTenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:10}}))}
  const model=useMemo(()=>{
    if(['l10-story','l10-plane','l10-plane-check'].includes(stage.id))return <div className="plane-model"><div className="plane-grid"/><span>часть плоскости</span><strong>продолжается во все стороны</strong></div>;
    if(['l10-line'].includes(stage.id))return <div className="infinite-line-model"><span className="point a">A</span><span className="point b">B</span><i/><b>прямая AB</b></div>;
    if(['l10-one-line','l10-one-line-check'].includes(stage.id))return <div className="two-point-line-model"><span>A</span><i/><span>B</span><strong>через A и B — одна прямая</strong></div>;
    if(['l10-line-names','l10-name-check'].includes(stage.id))return <div className="line-name-model"><i/><span>A</span><span>B</span><b>AB = BA = m</b></div>;
    if(stage.id==='l10-practice2')return <div className="ray-model ray-model-m"><span className="origin"/><i className="line"/><b>← луч · M · луч →</b></div>;
    if(stage.id==='l10-practice3')return <div className="ray-model ray-model-kp"><span className="origin"/><span className="right"/><i className="line"/><b>K → P → …</b></div>;
    if(['l10-ray','l10-ray-check','l10-practice4','l10-quiz4','l10-quiz5'].includes(stage.id))return <div className="ray-model"><span className="left">A</span><span className="origin">O</span><span className="right">B</span><i className="line"/><b>OA ← O → OB</b></div>;
    if(['l10-practice5'].includes(stage.id))return <div className="construction-model"><span>A</span><span>B</span><i/><strong>две точки → одна прямая</strong></div>;
    if(['l10-practice6'].includes(stage.id))return <div className="world-ray-model"><span className="lamp">●</span><i/><strong>начало + одно направление</strong></div>;
    if(['l10-challenge'].includes(stage.id))return <div className="triangle-lines-model"><span className="a">A</span><span className="b">B</span><span className="c">C</span><i className="ab"/><i className="ac"/><i className="bc"/><strong>AB · AC · BC</strong></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page plane-line-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 10 из 175 · § 4</span><h1>Плоскость. Прямая. Луч</h1><p>Первое знакомство с бесконечной плоскостью, свойством прямой, обозначениями и лучом.</p></div><div className="lesson-duration">план · 40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonTenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Сначала определи фигуру по её свойству: есть ли начало, есть ли конец и в какие стороны она продолжается. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Основная проверка пройдена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>в основной части</small></div><div><span>Основная часть</span><b>Основная часть ✓</b><small>дальше — обязательная практика</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonTenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
