import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './planeLineRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type PlaneLineRayPracticeStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-11-progress-v2';
const LEGACY_KEY='mathnikita-lesson-11-progress-v1';

export const lessonElevenStages:PlaneLineRayPracticeStage[]=[
  {id:'l11-story',kind:'story',eyebrow:'Закрепление § 4',title:'Теперь геометрию нужно не узнавать, а строить',body:'На прошлом уроке мы познакомились с плоскостью, прямой и лучом. Сегодня главная цель — уверенно читать чертёж, выполнять построения и учитывать взаимное расположение фигур.',note:'Сначала определи фигуру и её направление, затем проверь пересечение и только после этого делай вывод.',sourceTag:'Методическое пособие Мерзляка · технологическая карта урока № 11'},
  {id:'l11-recap',kind:'model',eyebrow:'Быстрое повторение',title:'Три фигуры — три разных набора свойств',body:'Прямая бесконечна в обе стороны. Луч имеет начало и бесконечно продолжается в одну сторону. Отрезок ограничен двумя концами.',note:'Через две различные точки проходит ровно одна прямая.',sourceTag:'Мерзляк § 4 · основные понятия'},
  {id:'l11-diagnostic',kind:'guided',eyebrow:'Актуализация',title:'Проверь направление до построения',body:'Для луча порядок букв важен: первая буква обозначает его начало.',activity:{id:'l11-a1',type:'choice',prompt:'Какой луч имеет начало в точке M и проходит через K?',options:['MK','KM','только m','KM и MK одновременно'],answer:'MK',explanation:'В обозначении луча первая буква — его начало, поэтому нужен луч MK.'}},
  {id:'l11-intersections',kind:'model',eyebrow:'Взаимное расположение',title:'Пересечение зависит не только от линии, но и от направления луча',body:'Прямая продолжается в обе стороны, а луч — только от начала в выбранном направлении. Поэтому прямая может пересекать продолжение линии луча, но сам луч до точки пересечения не дойдёт.',note:'Всегда проверяй: лежит ли точка пересечения именно на луче, а не на противоположном направлении.'},
  {id:'l11-task94-model',kind:'model',eyebrow:'№ 94',title:'Общая часть двух лучей может быть разной',body:'Два луча можно расположить так, что их общая часть будет только одной точкой, целым отрезком или снова лучом.',note:'Важны начала лучей и направления их продолжения.',sourceTag:'Мерзляк § 4 · № 94'},
  {id:'l11-rays-model',kind:'model',eyebrow:'№ 98',title:'Каждая отмеченная точка задаёт два луча',body:'Одна точка на прямой делит её на два луча с общим началом. Если отмечены разные точки, для каждой точки получаем свою пару лучей.',note:'n отмеченных точек задают 2n лучей.',sourceTag:'Мерзляк § 4 · № 98; методический комментарий к № 98'},
  {id:'l11-three-points',kind:'model',eyebrow:'№ 99',title:'Три точки на одной прямой могут стоять в разном порядке',body:'При известных AB и AC нельзя автоматически считать, что B и C лежат по одну сторону от A. Возможны разные взаимные расположения точек.',note:'Если B и C по одну сторону от A, BC — разность. Если по разные стороны — сумма.',sourceTag:'Мерзляк § 4 · № 99; методический комментарий к № 99'},
  {id:'l11-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'№ 94: общая часть — только точка',body:'Выбираем взаимное расположение двух лучей.',activity:{id:'l11-p1',type:'choice',prompt:'Как расположить два луча, чтобы их общая часть была только одной точкой?',options:['дать им общее начало и направить в разные стороны','полностью совместить лучи','поместить начало одного луча внутри другого и направить одинаково','взять два совпадающих луча'],answer:'дать им общее начало и направить в разные стороны',explanation:'Два противоположно направленных луча с общим началом имеют общей только точку начала.'},sourceTag:'Мерзляк § 4 · № 94'},
  {id:'l11-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'№ 95: направление решает всё',body:'Нужно различать прямую TF и луч TF: прямая идёт в обе стороны, а луч начинается в T и идёт через F только в одном направлении.',activity:{id:'l11-p2',type:'choice',prompt:'Почему возможно, что луч MK пересекает прямую TF, но луч TF не пересекает прямую MK?',options:['точка пересечения может лежать на прямой TF по другую сторону от T, чем F','луч всегда длиннее прямой','прямая имеет начало, а луч нет','любые два луча никогда не пересекаются'],answer:'точка пересечения может лежать на прямой TF по другую сторону от T, чем F',explanation:'Прямая TF содержит оба направления от T, а луч TF — только направление от T через F. Поэтому точка пересечения может принадлежать прямой TF, но не лучу TF.'},sourceTag:'Мерзляк § 4 · № 95'},
  {id:'l11-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'№ 98: сто точек',body:'Используй правило 2n.',activity:{id:'l11-p3',type:'input',prompt:'Сколько лучей образуется, если на прямой отметить 100 точек?',answer:'200',placeholder:'Количество лучей',explanation:'Каждая точка задаёт два луча: 100 · 2 = 200.'},sourceTag:'Мерзляк § 4 · № 98'},
  {id:'l11-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'№ 99: два возможных ответа',body:'Точки A, B и C лежат на одной прямой. AB = 24 см, AC = 32 см.',activity:{id:'l11-p4',type:'choice',prompt:'Какие значения может иметь BC и сколько решений у задачи?',options:['8 см или 56 см; два решения','8 см; одно решение','56 см; одно решение','24 см или 32 см; два решения'],answer:'8 см или 56 см; два решения',explanation:'Если B и C по одну сторону от A: BC = 32 − 24 = 8 см. Если по разные стороны: BC = 32 + 24 = 56 см. Значит, два решения.'},sourceTag:'Мерзляк § 4 · № 99'},
  {id:'l11-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Диктант 3: все имена одной прямой',body:'На прямой a отмечены точки C, E и D, причём E лежит между C и D.',activity:{id:'l11-p5',type:'choice',prompt:'Какой набор содержит только корректные обозначения этой прямой по отмеченным точкам?',options:['CE, EC, CD, DC, ED, DE','только CD','CE и ED, но не DC','EC, DE и луч ED'],answer:'CE, EC, CD, DC, ED, DE',explanation:'Прямую можно обозначить любой парой её точек в любом порядке.'},sourceTag:'Методическое пособие · математический диктант 3 · задание 4'},
  {id:'l11-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Алгоритм геометрического построения',body:'Закрепляем навык построения, который является главным планируемым результатом урока № 11.',activity:{id:'l11-p6',type:'order',prompt:'Расставь шаги решения задачи на построение',items:['Проверить все требуемые пересечения и непересечения','Прочитать условие и назвать требуемые фигуры','Сверить готовый чертёж со всеми условиями','Провести базовые прямые и отметить точки','Определить начала и направления лучей'],answer:['Прочитать условие и назвать требуемые фигуры','Определить начала и направления лучей','Провести базовые прямые и отметить точки','Проверить все требуемые пересечения и непересечения','Сверить готовый чертёж со всеми условиями'],explanation:'Построение надёжнее выполнять от структуры условия к проверке каждого ограничения.'},sourceTag:'Методическое пособие · урок № 11 · планируемый результат: выполнять геометрические построения'},
  {id:'l11-control',kind:'model',eyebrow:'Контроль',title:'Три проверки перед ответом',body:'В задачах § 4 ошибки чаще всего связаны с направлением луча, неверным порядком точек или тем, что продолжение фигуры принимают за саму фигуру.',note:'Проверка: начало → направление → принадлежность/пересечение.'},
  {id:'l11-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Луч',body:'Без подсказки.',activity:{id:'l11-q1',type:'choice',prompt:'У какой фигуры есть начало, но нет конца?',options:['луч','отрезок','прямая','точка'],answer:'луч',explanation:'Луч начинается в одной точке и неограниченно продолжается в одном направлении.'}},
  {id:'l11-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Две точки',body:'Без подсказки.',activity:{id:'l11-q2',type:'input',prompt:'Сколько различных прямых можно провести через две различные точки?',answer:'1',placeholder:'Количество',explanation:'Через две различные точки проходит ровно одна прямая.'}},
  {id:'l11-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Четыре точки на прямой',body:'Без подсказки.',activity:{id:'l11-q3',type:'input',prompt:'Сколько лучей задают четыре отмеченные на прямой точки?',answer:'8',placeholder:'Количество лучей',explanation:'Каждая точка задаёт два луча: 4 · 2 = 8.'}},
  {id:'l11-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Два луча из точки E',body:'Точки C, E и D лежат на одной прямой, E между C и D.',activity:{id:'l11-q4',type:'choice',prompt:'Какие два противоположных луча имеют начало E?',options:['EC и ED','CE и DE','CD и DC','EC и DE'],answer:'EC и ED',explanation:'Оба луча должны начинаться буквой E и идти в противоположных направлениях.'}},
  {id:'l11-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Общая часть лучей',body:'Без подсказки.',activity:{id:'l11-q5',type:'choice',prompt:'Что может быть общей частью двух лучей по задаче № 94?',options:['точка, отрезок или луч','только точка','только луч','только отрезок'],answer:'точка, отрезок или луч',explanation:'В № 94 требуется построить все три варианта: общая часть — точка, отрезок или луч.'}},
  {id:'l11-challenge',kind:'challenge',eyebrow:'Задача повышенного уровня · № 102',title:'Три прямые делят плоскость',body:'Изменяя взаимное расположение трёх различных прямых, можно менять количество частей плоскости.',activity:{id:'l11-c1',type:'choice',prompt:'Каковы наибольшее и наименьшее количества частей плоскости для трёх прямых?',options:['7 и 4','6 и 3','8 и 4','7 и 3'],answer:'7 и 4',explanation:'Максимум 7 получается, когда прямые попарно пересекаются в трёх разных точках. Минимум 4 — когда три прямые параллельны.'},sourceTag:'Мерзляк § 4 · № 102'},
  {id:'l11-reflection',kind:'model',eyebrow:'Рефлексия',title:'Проверь не память, а навык построения',body:'Ответь себе: какое задание понравилось больше всего и какое вызвало затруднения. Это именно вопросы рефлексии из технологической карты урока № 11.',note:'Отдельно отметь, где была трудность: направление луча, взаимное расположение фигур или чтение условия.',sourceTag:'Методическое пособие · урок № 11 · рефлексия'},
  {id:'l11-summary',kind:'summary',eyebrow:'Итог основной части',title:'Построения стали инструментом',body:'Основная часть пройдена: ты не только различаешь прямую и луч, но и умеешь анализировать взаимное расположение фигур, считать лучи и учитывать несколько вариантов расположения точек.',note:'Дальше — обязательная практика и финальная рефлексия. Только после них урок считается завершённым.'},
];

const empty:Saved={version:2,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonElevenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

export function PlaneLineRayPracticePlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
  const stage=lessonElevenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l11-q1','l11-q2','l11-q3','l11-q4','l11-q5'];const practice=['l11-p1','l11-p2','l11-p3','l11-p4','l11-p5','l11-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonElevenStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===11&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonElevenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:11}}))}
  const model=useMemo(()=>{
    if(['l11-story','l11-recap'].includes(stage.id))return <div className="plane-model"><div className="plane-grid"/><span>плоскость</span><strong>прямая ↔ · луч → · отрезок —</strong></div>;
    if(stage.id==='l11-diagnostic')return <div className="l11-ray-name-model"><i/><span className="origin">M</span><span className="through">K</span><strong>луч MK: M → K → …</strong></div>;
    if(['l11-intersections','l11-practice2'].includes(stage.id))return <div className="l11-intersection-model"><i className="mk-ray"/><i className="tf-line"/><i className="tf-ray"/><span className="m">M</span><span className="k">K</span><span className="x">X</span><span className="t">T</span><span className="f">F</span><strong>X принадлежит лучу MK и прямой TF, но не лучу TF</strong></div>;
    if(['l11-task94-model','l11-practice1','l11-quiz5'].includes(stage.id))return <div className="l11-common-parts-model"><div><span>← ● →</span><b>общая часть: точка</b></div><div><span>← ●━━━━● →</span><b>общая часть: отрезок</b></div><div><span>●━━━━━━→</span><b>общая часть: луч</b></div><strong>№ 94 · три возможных типа общей части</strong></div>;
    if(['l11-rays-model','l11-practice3','l11-quiz3'].includes(stage.id)){const caption=stage.id==='l11-practice3'?'100 точек → 200 лучей':stage.id==='l11-quiz3'?'4 точки → 8 лучей':'каждая точка → 2 луча';return <div className="l11-many-rays-model"><i/><span className="p1">●</span><span className="p2">●</span><span className="p3">●</span><span className="p4">●</span><strong>{caption}</strong></div>}
    if(['l11-three-points','l11-practice4'].includes(stage.id))return <div className="l11-distance-cases"><div><i/><span className="a">A</span><span className="b">B</span><span className="c">C</span><b>одна сторона: 32 − 24 = 8 см</b></div><div><i/><span className="b">B</span><span className="a">A</span><span className="c">C</span><b>разные стороны: 24 + 32 = 56 см</b></div></div>;
    if(['l11-practice5','l11-quiz4'].includes(stage.id))return <div className="l11-ced-model"><i/><span className="c">C</span><span className="e">E</span><span className="d">D</span><strong>{stage.id==='l11-practice5'?'CE, EC, CD, DC, ED, DE — одна прямая':'EC и ED — противоположные лучи с началом E'}</strong></div>;
    if(stage.id==='l11-challenge')return <div className="l11-three-lines-model"><div className="maximum"><i className="one"/><i className="two"/><i className="three"/><b>максимум: 7 частей</b></div><div className="minimum"><i className="one"/><i className="two"/><i className="three"/><b>минимум: 4 части</b></div><strong>Три прямые: пересечения меняют число частей плоскости</strong></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page plane-line-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 11 из 175 · § 4</span><h1>Плоскость. Прямая. Луч — закрепление</h1><p>Чертежи, построения, направления лучей и задачи на взаимное расположение фигур.</p></div><div className="lesson-duration">план · 40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonElevenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь начало и направление луча, порядок точек и принадлежность точки фигуре. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Основная проверка пройдена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>основной части выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Основная часть ✓':'Повторить'}</b><small>дальше — обязательная практика</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% основной части</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonElevenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
