import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './polygonLesson.css';
import './polygonConstruction.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='construction'|'side-diagonal'|'from-one'|'all-diagonals'|'perimeter'|'equal'|'crossing'|'formula';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram;builder?:boolean};
type Point={id:string;x:number;y:number};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;builderOrder:string[]};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

type Segment={a:Point;b:Point};
const KEY='mathnikita-lesson-45-progress-v1';
const points:Point[]=[{id:'A',x:105,y:225},{id:'B',x:85,y:75},{id:'C',x:320,y:42},{id:'D',x:570,y:110},{id:'E',x:505,y:240}];
const pointById=new Map(points.map(point=>[point.id,point]));
const normalize=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/\s+/g,'').replace(/Ё/g,'Е');
const orientation=(a:Point,b:Point,c:Point)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
function segmentsCross(first:Segment,second:Segment){const o1=orientation(first.a,first.b,second.a);const o2=orientation(first.a,first.b,second.b);const o3=orientation(second.a,second.b,first.a);const o4=orientation(second.a,second.b,first.b);return o1*o2<0&&o3*o4<0}
function buildSegments(order:string[]){if(order.length<2)return[];const segments:Segment[]=[];for(let index=0;index<order.length-1;index+=1){const a=pointById.get(order[index]);const b=pointById.get(order[index+1]);if(a&&b)segments.push({a,b})}if(order.length===points.length){const a=pointById.get(order.at(-1)!);const b=pointById.get(order[0]);if(a&&b)segments.push({a,b})}return segments}
function hasSelfIntersection(order:string[]){const segments=buildSegments(order);for(let i=0;i<segments.length;i+=1){for(let j=i+1;j<segments.length;j+=1){const adjacent=j===i+1||(i===0&&j===segments.length-1);if(adjacent)continue;if(segmentsCross(segments[i],segments[j]))return true}}return false}

export const lessonFortyFiveStages:Stage[]=[
  {id:'l45-mission',kind:'story',eyebrow:'Урок 45 · § 13 · закрепление',title:'Из наблюдателя — в конструктора',body:'Теперь мало узнать многоугольник. Нужно уметь его построить, проверить границу, провести диагонали, посчитать элементы и доказать, что построение действительно отвечает условию.',note:'Маршрут: построение → диагональ → n − 3 → все диагонали → обратные задачи → равные фигуры.',diagram:'construction'},
  {id:'l45-bridge',kind:'model',eyebrow:'Опора на урок 44',title:'Сначала граница, потом свойства',body:'У корректного многоугольника граница замкнута и не самопересекается. Поэтому любое построение заканчивается проверкой: последняя вершина соединена с первой, а несоседние стороны не пересеклись.',diagram:'crossing'},
  {id:'l45-construction-plan',kind:'guided',eyebrow:'Алгоритм построения',title:'Четыре действия конструктора',body:'1) отметь вершины; 2) выбери последовательный обход; 3) соедини соседние вершины; 4) замкни последнюю сторону и проверь самопересечение. Перепрыгивание через вершину может превратить контур в «звезду».',diagram:'construction'},
  {id:'l45-builder',kind:'practice',eyebrow:'Интерактивное построение',title:'Построй пятиугольник ABCDE',body:'Начни с A. Нажимай остальные вершины в последовательном обходе границы. После пятой вершины контур замкнётся автоматически. Если рёбра пересеклись — сбрось построение и попробуй другой порядок.',builder:true},
  {id:'l45-practice1',kind:'practice',eyebrow:'Контроль построения',title:'Что доказывает корректность?',body:'После соединения всех пяти точек нужен не взгляд «похоже на пятиугольник», а точная проверка.',activity:{id:'l45-p1',type:'choice',prompt:'Какой итог проверки достаточен?',options:['Контур замкнут и несоседние стороны не пересекаются','Все стороны выглядят одинаковыми','Есть ровно пять букв','Фигура помещается в прямоугольник'],answer:'Контур замкнут и несоседние стороны не пересекаются',hint:'Вспомни точный признак границы многоугольника.',explanation:'Простая замкнутая ломаная задаёт границу многоугольника.'},diagram:'crossing'},
  {id:'l45-side-diagonal-model',kind:'model',eyebrow:'Новый инструмент внутри знакомой фигуры',title:'Сторона или диагональ?',body:'Сторона соединяет соседние вершины. Диагональ соединяет две несоседние вершины многоугольника. Например, в пятиугольнике ABCDE отрезок AB — сторона, а AC — диагональ.',diagram:'side-diagonal'},
  {id:'l45-practice2',kind:'practice',eyebrow:'Сторона и диагональ',title:'Пятиугольник ABCDE',body:'Вершины идут по границе A → B → C → D → E → A.',activity:{id:'l45-p2',type:'choice',prompt:'Какой отрезок является диагональю?',options:['AB','BC','DE','AC'],answer:'AC',hint:'Диагональ соединяет несоседние вершины.',explanation:'A и C не соседние, поэтому AC — диагональ.'},diagram:'side-diagonal'},
  {id:'l45-from-one-model',kind:'model',eyebrow:'Диагонали из одной вершины',title:'Почему n − 3?',body:'Из выбранной вершины нельзя провести диагональ в саму эту вершину и в две соседние вершины: эти два соединения уже являются сторонами. Поэтому из одной вершины n-угольника выходит n − 3 диагонали.',note:'Именно это наблюдение методическое пособие использует в комментарии к № 329.',diagram:'from-one'},
  {id:'l45-practice3',kind:'practice',eyebrow:'n − 3 · пятиугольник',title:'Из вершины A',body:'У пятиугольника n = 5.',activity:{id:'l45-p3',type:'input',prompt:'Сколько диагоналей можно провести из одной вершины?',answer:'2',placeholder:'Число диагоналей',hint:'Вычисли 5 − 3.',explanation:'5 − 3 = 2.'},diagram:'from-one'},
  {id:'l45-practice4',kind:'practice',eyebrow:'n − 3 · шестиугольник',title:'Шесть вершин',body:'Из одной вершины нельзя соединяться диагональю с тремя вершинами: с собой и двумя соседними.',activity:{id:'l45-p4',type:'input',prompt:'Сколько диагоналей выходит из одной вершины шестиугольника?',answer:'3',placeholder:'Число диагоналей',hint:'6 − 3.',explanation:'6 − 3 = 3.'},diagram:'from-one'},
  {id:'l45-practice5',kind:'practice',eyebrow:'n − 3 · восьмиугольник',title:'Правило без рисунка',body:'Теперь рисунок уже не нужен: работаем по структуре.',activity:{id:'l45-p5',type:'input',prompt:'Сколько диагоналей выходит из одной вершины восьмиугольника?',answer:'5',placeholder:'Число диагоналей',hint:'8 − 3.',explanation:'8 − 3 = 5.'},diagram:'formula'},
  {id:'l45-double-count-model',kind:'model',eyebrow:'Все диагонали',title:'Почему нельзя просто умножить n на n − 3?',body:'Если для каждой вершины посчитать её n − 3 диагонали, одна и та же диагональ попадёт в список дважды: один раз от первого конца и второй раз от второго. Поэтому результат нужно разделить на 2.',diagram:'all-diagonals'},
  {id:'l45-practice6',kind:'practice',eyebrow:'Двойной счёт',title:'Ключ к формуле',body:'Сначала n(n − 3), затем устраняем двойной подсчёт.',activity:{id:'l45-p6',type:'choice',prompt:'Почему делим на 2?',options:['Каждую диагональ посчитали от двух её концов','У многоугольника две стороны','Диагональ всегда делит фигуру пополам','Так удобнее вычислять'],answer:'Каждую диагональ посчитали от двух её концов',hint:'У каждой диагонали две вершины-конца.',explanation:'При подсчёте из каждой вершины любая диагональ учитывается дважды.'},diagram:'all-diagonals'},
  {id:'l45-formula-model',kind:'model',eyebrow:'Формула № 329',title:'D = n(n − 3) : 2',body:'Общее число диагоналей n-угольника равно n(n − 3) : 2. Формула не заменяет смысл: n − 3 — диагонали из одной вершины, умножение на n проходит по всем вершинам, деление на 2 убирает повторный счёт.',diagram:'formula'},
  {id:'l45-practice7',kind:'practice',eyebrow:'Формула · пятиугольник',title:'n = 5',body:'Подставь число сторон в формулу.',activity:{id:'l45-p7',type:'input',prompt:'Сколько всего диагоналей у пятиугольника?',answer:'5',placeholder:'D',hint:'5 · (5 − 3) : 2.',explanation:'5 · 2 : 2 = 5.'},diagram:'all-diagonals'},
  {id:'l45-practice8',kind:'practice',eyebrow:'Формула · шестиугольник',title:'n = 6',body:'Сначала найди диагонали из одной вершины.',activity:{id:'l45-p8',type:'input',prompt:'Сколько всего диагоналей у шестиугольника?',answer:'9',placeholder:'D',hint:'6 · 3 : 2.',explanation:'6 · 3 : 2 = 9.'},diagram:'all-diagonals'},
  {id:'l45-practice9',kind:'practice',eyebrow:'Формула · семиугольник',title:'n = 7',body:'Проверяем, что алгоритм масштабируется.',activity:{id:'l45-p9',type:'input',prompt:'Сколько всего диагоналей у семиугольника?',answer:'14',placeholder:'D',hint:'7 · 4 : 2.',explanation:'7 · 4 : 2 = 14.'},diagram:'formula'},
  {id:'l45-practice10',kind:'practice',eyebrow:'Формула · восьмиугольник',title:'n = 8',body:'Ещё один шаг без рисунка.',activity:{id:'l45-p10',type:'input',prompt:'Сколько всего диагоналей у восьмиугольника?',answer:'20',placeholder:'D',hint:'8 · 5 : 2.',explanation:'8 · 5 : 2 = 20.'},diagram:'formula'},
  {id:'l45-reverse-model',kind:'model',eyebrow:'Обратная задача',title:'Из числа диагоналей — к числу сторон',body:'Иногда известно D, а n нужно восстановить. Для пятого класса удобнее не решать квадратное уравнение, а разумно перебирать n: 5 → 5 диагоналей, 6 → 9, 7 → 14, 8 → 20, 9 → 27.',diagram:'formula'},
  {id:'l45-practice11',kind:'practice',eyebrow:'Обратная задача',title:'D = 27',body:'Найди число сторон проверкой формулы.',activity:{id:'l45-p11',type:'input',prompt:'Сколько сторон у многоугольника с 27 диагоналями?',answer:'9',placeholder:'n',hint:'Проверь n = 9: 9 · 6 : 2.',explanation:'9 · 6 : 2 = 27, значит это девятиугольник.'},diagram:'formula'},
  {id:'l45-practice12',kind:'practice',eyebrow:'Обратная задача · быстрее',title:'Из одной вершины выходит 9 диагоналей',body:'Здесь не нужна формула общего числа диагоналей.',activity:{id:'l45-p12',type:'input',prompt:'Сколько сторон у этого многоугольника?',answer:'12',placeholder:'n',hint:'n − 3 = 9.',explanation:'n = 9 + 3 = 12.'},diagram:'from-one'},
  {id:'l45-perimeter-bridge',kind:'model',eyebrow:'Элементы + вычисления',title:'Периметр остаётся длиной границы',body:'Диагонали лежат внутри многоугольника и в периметр не входят. При вычислении периметра складываем только стороны границы.',note:'Это важная ловушка: диагональ — элемент задачи, но не часть периметра.',diagram:'perimeter'},
  {id:'l45-practice13',kind:'practice',eyebrow:'Периметр',title:'Шестиугольник 8-8-8-10-10-10',body:'Три стороны по 8 см и три стороны по 10 см.',activity:{id:'l45-p13',type:'input',prompt:'Найди периметр.',answer:'54',placeholder:'См',hint:'3 · 8 + 3 · 10.',explanation:'24 + 30 = 54 см.'},diagram:'perimeter'},
  {id:'l45-practice14',kind:'practice',eyebrow:'Обратный периметр',title:'Неизвестная сторона',body:'P = 42 см; четыре стороны пятиугольника: 6, 7, 8 и 9 см.',activity:{id:'l45-p14',type:'input',prompt:'Найди пятую сторону.',answer:'12',placeholder:'См',hint:'42 − (6 + 7 + 8 + 9).',explanation:'42 − 30 = 12 см.'},diagram:'perimeter'},
  {id:'l45-equal-model',kind:'model',eyebrow:'Построение равной фигуры',title:'Копия может быть перенесена и повернута',body:'Чтобы построить фигуру, равную данной, нужно сохранить её форму и размеры. Положение на листе и поворот значения не имеют: окончательная проверка — совпадение при наложении.',diagram:'equal'},
  {id:'l45-practice15',kind:'practice',eyebrow:'Равенство фигур',title:'Поворот не мешает',body:'Вторую фигуру получили переносом и поворотом первой без изменения размеров.',activity:{id:'l45-p15',type:'choice',prompt:'Какой вывод верен?',options:['Фигуры равны','Равны только периметры','Фигуры не равны из-за поворота','Равенство зависит от положения на листе'],answer:'Фигуры равны',hint:'Используй определение через наложение.',explanation:'После обратного переноса и поворота фигуры полностью совпадут.'},diagram:'equal'},
  {id:'l45-practice16',kind:'practice',eyebrow:'Контрпример',title:'Одинаковый периметр — не доказательство',body:'Два четырёхугольника имеют одинаковый периметр, но при наложении не совпадают.',activity:{id:'l45-p16',type:'choice',prompt:'Равны ли эти фигуры?',options:['Нет','Да','Да, потому что периметры равны','Да, потому что у каждой четыре стороны'],answer:'Нет',hint:'Равенство требует полного совпадения.',explanation:'Одинаковый периметр не гарантирует одинаковую форму и размеры.'},diagram:'equal'},
  {id:'l45-error-analysis',kind:'practice',eyebrow:'Контроль и коррекция',title:'Ошибка конструктора',body:'Ученик соединил вершины A → C → B → D → E → A и получил пересекающиеся рёбра.',activity:{id:'l45-p17',type:'choice',prompt:'Как исправить построение?',options:['Соединять вершины последовательно по границе','Добавить ещё одну вершину','Сделать все стороны равными','Стереть только буквы'],answer:'Соединять вершины последовательно по границе',hint:'Проблема не в длинах, а в порядке обхода.',explanation:'Последовательный обход устраняет искусственное самопересечение границы.'},diagram:'crossing'},
  {id:'l45-practice17',kind:'practice',eyebrow:'Связь сторон и диагоналей',title:'Все пары вершин восьмиугольника',body:'Любые две вершины соединяются либо стороной, либо диагональю. У восьмиугольника 8 сторон и 20 диагоналей.',activity:{id:'l45-p18',type:'input',prompt:'Сколько всего отрезков соединяет пары вершин восьмиугольника?',answer:'28',placeholder:'Отрезков',hint:'Сложи стороны и диагонали.',explanation:'8 + 20 = 28.'},diagram:'all-diagonals'},
  {id:'l45-challenge1',kind:'challenge',eyebrow:'Уровень выше',title:'Двенадцатиугольник',body:'Сначала n − 3, затем общий подсчёт.',activity:{id:'l45-p19',type:'input',prompt:'Сколько всего диагоналей у двенадцатиугольника?',answer:'54',placeholder:'D',hint:'12 · 9 : 2.',explanation:'12 · 9 : 2 = 54.'},diagram:'formula'},
  {id:'l45-quiz1',kind:'quiz',eyebrow:'Мини-контроль · 1/3',title:'Десятиугольник',body:'Работай без рисунка.',activity:{id:'l45-q1',type:'input',prompt:'Сколько всего диагоналей у десятиугольника?',answer:'35',placeholder:'D',hint:'10 · 7 : 2.',explanation:'10 · 7 : 2 = 35.'},diagram:'formula'},
  {id:'l45-quiz2',kind:'quiz',eyebrow:'Мини-контроль · 2/3',title:'44 диагонали',body:'Используй обратную проверку нескольких значений n.',activity:{id:'l45-q2',type:'input',prompt:'Сколько сторон у многоугольника, имеющего 44 диагонали?',answer:'11',placeholder:'n',hint:'Проверь 11 · 8 : 2.',explanation:'11 · 8 : 2 = 44, значит n = 11.'},diagram:'formula'},
  {id:'l45-quiz3',kind:'quiz',eyebrow:'Мини-контроль · 3/3',title:'Что входит в периметр?',body:'У пятиугольника проведены все пять диагоналей.',activity:{id:'l45-q3',type:'choice',prompt:'Нужно ли прибавлять длины диагоналей при вычислении периметра?',options:['Нет, только длины сторон границы','Да, все отрезки рисунка','Только две диагонали','Да, если они пересекаются'],answer:'Нет, только длины сторон границы',hint:'Периметр — длина границы.',explanation:'Диагонали лежат внутри и не входят в периметр.'},diagram:'perimeter'},
  {id:'l45-synthesis',kind:'model',eyebrow:'Система § 13',title:'Пять проверок хорошего решения',body:'1) построение даёт простую замкнутую границу; 2) сторона соединяет соседние вершины, диагональ — несоседние; 3) из вершины n − 3 диагонали; 4) всего n(n − 3) : 2; 5) равенство фигур проверяется совпадением при наложении.',diagram:'formula'},
  {id:'l45-final-challenge',kind:'challenge',eyebrow:'Финальная связка',title:'Восьмиугольник: граница + внутренние связи',body:'У восьмиугольника 8 сторон и 20 диагоналей. Представь, что соединены все пары его вершин.',activity:{id:'l45-p20',type:'input',prompt:'Сколько всего получено отрезков между парами вершин?',answer:'28',placeholder:'Отрезков',hint:'Каждое соединение — либо сторона, либо диагональ.',explanation:'8 сторон + 20 диагоналей = 28 отрезков.'},diagram:'all-diagonals'},
  {id:'l45-summary',kind:'summary',eyebrow:'§ 13 завершён',title:'Ты умеешь не только видеть многоугольник, но и работать с ним',body:'Ты построил многоугольник с проверкой самопересечения, отличал стороны от диагоналей, вывел n − 3 и n(n − 3) : 2, решал прямые и обратные задачи, вычислял периметр и проверял равенство фигур.',note:'Следующий урок 46 открывает § 14: треугольник и его виды.',diagram:'equal'},
];

function DiagramView({kind}:{kind:Diagram}){
  if(kind==='construction')return <div className="polygon-diagram construction-diagram" aria-label="Последовательное построение пятиугольника"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill" points="105,225 85,75 320,42 570,110 505,240"/>{points.map(point=><g key={point.id}><circle className="polygon-vertex" cx={point.x} cy={point.y} r="9"/><text className="polygon-label" x={point.x+12} y={point.y-10}>{point.id}</text></g>)}</svg><span className="polygon-caption">A → B → C → D → E → A</span></div>;
  if(kind==='side-diagonal')return <div className="polygon-diagram" aria-label="Сторона AB и диагональ AC"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill" points="105,225 85,75 320,42 570,110 505,240"/><line className="construction-diagonal" x1="105" y1="225" x2="320" y2="42" data-diagonal="AC"/><text className="polygon-note" x="120" y="140">AC — диагональ</text><text className="polygon-note" x="18" y="150">AB — сторона</text></svg></div>;
  if(kind==='from-one')return <div className="polygon-diagram" aria-label="Диагонали из одной вершины"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill" points="105,225 85,75 320,42 570,110 505,240"/><line className="construction-diagonal" data-origin-diagonal="A-C" x1="105" y1="225" x2="320" y2="42"/><line className="construction-diagonal" data-origin-diagonal="A-D" x1="105" y1="225" x2="570" y2="110"/><circle className="construction-origin" cx="105" cy="225" r="13"/><text className="polygon-label" x="122" y="252">A</text></svg><span className="polygon-caption">В пятиугольнике из A выходят 5 − 3 = 2 диагонали</span></div>;
  if(kind==='all-diagonals')return <div className="polygon-diagram" aria-label="Все диагонали пятиугольника"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill" points="105,225 85,75 320,42 570,110 505,240"/>{[['A','C'],['A','D'],['B','D'],['B','E'],['C','E']].map(([a,b])=>{const p=pointById.get(a)!;const q=pointById.get(b)!;return <line key={`${a}-${b}`} className="construction-diagonal" data-all-diagonal={`${a}-${b}`} x1={p.x} y1={p.y} x2={q.x} y2={q.y}/>})}</svg><span className="polygon-caption">Каждая диагональ имеет два конца — поэтому двойной счёт делим на 2</span></div>;
  if(kind==='perimeter')return <div className="polygon-diagram" aria-label="Периметр — только стороны границы"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill second" points="115,225 90,75 325,45 565,110 500,240"/><line className="construction-diagonal muted-diagonal" x1="115" y1="225" x2="325" y2="45"/><text className="polygon-note" x="210" y="278">P = сумма сторон; диагональ не входит</text></svg></div>;
  if(kind==='equal')return <div className="polygon-diagram equal-construction" aria-label="Равные фигуры при переносе и повороте"><svg viewBox="0 0 680 280" role="img"><polygon className="polygon-fill" points="70,210 85,85 235,55 270,175 180,230"/><g transform="translate(385 25) rotate(18 105 105)"><polygon className="polygon-fill second" points="0,185 15,60 165,30 200,150 110,205"/></g><text className="polygon-note" x="245" y="268">перенос + поворот → совпадение</text></svg></div>;
  if(kind==='crossing')return <div className="polygon-diagram" aria-label="Правильный и самопересекающийся порядок соединения"><svg viewBox="0 0 680 300" role="img"><polygon className="polygon-fill" data-simple-polygon="true" points="45,220 55,80 260,45 290,200 170,245"/><g transform="translate(350 0)"><line className="polygon-invalid" data-crossing-edge="a" x1="35" y1="220" x2="245" y2="55"/><line className="polygon-invalid" x1="245" y1="55" x2="55" y2="75"/><line className="polygon-invalid" data-crossing-edge="b" x1="55" y1="75" x2="270" y2="220"/><line className="polygon-invalid" x1="270" y1="220" x2="155" y2="245"/><line className="polygon-invalid" x1="155" y1="245" x2="35" y2="220"/></g></svg><span className="polygon-caption">Слева — последовательный обход; справа — перепрыгивание создаёт пересечение</span></div>;
  return <div className="polygon-diagram formula-diagram" aria-label="Формула числа диагоналей"><div className="formula-board"><span>из одной вершины</span><strong>n − 3</strong><i>→</i><span>все вершины, двойной счёт</span><strong>D = n(n − 3) : 2</strong></div></div>;
}

function PolygonBuilder({order,onOrderChange,onPass}:{order:string[];onOrderChange:(next:string[])=>void;onPass:(passed:boolean)=>void}){
  const selected=new Set(order);const segments=buildSegments(order);const complete=order.length===points.length;const crossing=complete&&hasSelfIntersection(order);const passed=complete&&!crossing;
  useEffect(()=>onPass(passed),[passed,onPass]);
  function choose(id:string){if(selected.has(id))return;onOrderChange([...order,id])}
  function reset(){onOrderChange(['A']);onPass(false)}
  return <div className="polygon-builder" data-builder-valid={passed?'true':'false'} data-builder-crossing={crossing?'true':'false'}><div className="builder-instructions"><b>Старт: A</b><span>Выбирай следующую вершину. После пятой точки контур замкнётся.</span></div><svg viewBox="0 0 680 300" role="img" aria-label="Конструктор пятиугольника">{segments.map((segment,index)=><line key={index} className={`builder-edge ${index===segments.length-1&&complete?'closing':''}`} data-construction-edge={index} x1={segment.a.x} y1={segment.a.y} x2={segment.b.x} y2={segment.b.y}/>)}{points.map(point=><g key={point.id} className="builder-point" data-builder-point={point.id} onClick={()=>choose(point.id)}><circle className={selected.has(point.id)?'is-selected':''} cx={point.x} cy={point.y} r="18"/><text x={point.x} y={point.y+7} textAnchor="middle">{point.id}</text></g>)}</svg><div className="builder-order"><span>Порядок:</span><strong>{order.join(' → ')}{complete?` → ${order[0]}`:''}</strong></div>{complete?<div className={`builder-result ${passed?'good':'bad'}`}>{passed?'Граница замкнута, самопересечений нет — построение верно.':'Несоседние стороны пересеклись. Измени порядок обхода.'}</div>:null}<div className="builder-actions">{points.filter(point=>!selected.has(point.id)).map(point=><button type="button" key={point.id} onClick={()=>choose(point.id)}>Вершина {point.id}</button>)}<button type="button" className="builder-reset" onClick={reset}>Сбросить</button></div></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{},builderOrder:['A']};const parsed=JSON.parse(raw) as Partial<Saved>;const builderOrder=Array.isArray(parsed.builderOrder)&&parsed.builderOrder[0]==='A'?parsed.builderOrder.filter(id=>pointById.has(id)):['A'];return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyFiveStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},builderOrder:builderOrder.length?builderOrder:['A']}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{},builderOrder:['A']}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function PolygonConstructionPlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const[builderOrder,setBuilderOrder]=useState(initial.builderOrder);const stage=lessonFortyFiveStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results,builderOrder} satisfies Saved))},[stageIndex,responses,checked,results,builderOrder]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==45||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonFortyFiveStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const response=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;const builderPassed=Boolean(results['l45-builder']);
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonFortyFiveStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  function setBuilderPassed(passed:boolean){setResults(previous=>previous['l45-builder']===passed?previous:{...previous,'l45-builder':passed})}
  const blockedByBuilder=Boolean(stage.builder)&&!builderPassed;
  return <section className="lesson-player polygon-lesson-player polygon-construction-player" aria-label="Урок 45. Построение многоугольников и диагонали"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<DiagramView kind={stage.diagram}/>:null}{stage.builder?<PolygonBuilder order={builderOrder} onOrderChange={next=>{setBuilderOrder(next);setBuilderPassed(false)}} onPass={setBuilderPassed}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>setResponse(option)} disabled={isCorrect}>{option}</button>)}</div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric" disabled={isCorrect}/></div>}<button type="button" className="check-button" disabled={!response.trim()||isCorrect} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 13 полностью освоен</strong><span>построение · стороны и диагонали · n − 3 · n(n − 3) : 2 · периметр · равные фигуры</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonFortyFiveStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonFortyFiveStages.length-1||blockedByBuilder||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonFortyFiveStages.length-1?'Готово':'Дальше →'}</button></div></article></section>;
}
