import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'power'|'product'|'order'|'verify'|'challenge'|'final';
export type LessonSeventyOneStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-71-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyOneStages:LessonSeventyOneStage[]=[
{id:'l71-mission',kind:'story',eyebrow:'Урок 71 · § 20 · новая тема',title:'Степень — короткая запись длинного произведения',body:'Сегодня появляется новое арифметическое действие: возведение в степень. Научимся читать запись aⁿ, различать основание и показатель, превращать одинаковые множители в степень и обратно, понимать квадрат и куб и правильно ставить степень первой в порядке действий.',note:'Технологическая карта урока 71: устно № 1–2, с. 136; теория § 20; № 548, 549, 550, 552; повторение № 560 (1–2); домашний перенос § 20, вопросы 1–6, № 551, 553, 561.',visual:'mission'},
{id:'l71-oral-map',kind:'model',eyebrow:'Актуализация · № 1, с. 136',title:'Перед новой операцией — быстрый контроль обратных действий',body:'Устное № 1 содержит четыре уравнения. Их смысл знаком: сначала освобождаем выражение от внешнего действия, потом находим x.',visual:'map',sourceExercise:'Устно № 1, с. 136'},
{id:'l71-oral-1a',kind:'quiz',eyebrow:'Устно · № 1(1–2)',title:'Два уравнения со скобками',body:'Реши: (x−10):2=20 и (x+10)·2=20.',activity:{id:'l71-p1',type:'input',prompt:'Запиши два корня через запятую в порядке заданий.',answer:['50,0','50;0'],placeholder:'x₁, x₂',hint:'В первом умножь 20 на 2 и прибавь 10. Во втором раздели 20 на 2 и вычти 10.',explanation:'x=50 и x=0.'},visual:'verify',sourceExercise:'Устно № 1(1–2), с. 136'},
{id:'l71-oral-1b',kind:'quiz',eyebrow:'Устно · № 1(3–4)',title:'Два уравнения без скобок',body:'Реши: x·10−2=8 и x:10+2=8.',activity:{id:'l71-p2',type:'input',prompt:'Запиши два корня через запятую.',answer:['1,60','1;60'],placeholder:'x₃, x₄',hint:'Сначала убери ±2, затем используй обратное действие к умножению или делению на 10.',explanation:'x=1 и x=60.'},visual:'verify',sourceExercise:'Устно № 1(3–4), с. 136'},
{id:'l71-oral-2',kind:'quiz',eyebrow:'Устно · № 2, с. 136',title:'Равенство верно, а деление с остатком — нет',body:'90=14·5+20 — численно верное равенство. Но остаток 20 не меньше делителя 14.',activity:{id:'l71-p3',type:'choice',prompt:'Какой вывод правильный?',options:['равенство верно, но это не корректная запись деления с остатком','неверно само равенство','неполное частное 5 и остаток 20 корректны','остаток может быть больше делителя'],answer:'равенство верно, но это не корректная запись деления с остатком',hint:'Для деления с остатком обязательно r<b.',explanation:'70+20=90, но 20≥14, поэтому запись деления некорректна.'},visual:'verify',sourceExercise:'Устно № 2, с. 136'},
{id:'l71-theory-bridge',kind:'guided',eyebrow:'§ 20 · теория',title:'Сумму одинаковых слагаемых мы уже сокращали. Теперь — произведение',body:'Например, 7·7·7·7 можно записать намного короче. Для произведения одинаковых множителей вводят степень.',visual:'product'},
{id:'l71-theory-product',kind:'model',eyebrow:'§ 20 · определение',title:'7·7·7·7 = 7⁴',body:'Выражение 7⁴ называют степенью. Оно читается «семь в четвёртой степени» или «четвёртая степень числа семь». Основание показывает, какой множитель повторяется, показатель — сколько раз.',visual:'power'},
{id:'l71-base',kind:'quiz',eyebrow:'§ 20 · термин',title:'Основание — повторяющийся множитель',body:'В записи 7⁴ основание равно 7.',activity:{id:'l71-p4',type:'input',prompt:'Каково основание степени 7⁴?',answer:'7',placeholder:'основание',hint:'Посмотри на число, которое нужно умножать само на себя.',explanation:'Основание равно 7.'},visual:'power'},
{id:'l71-exponent',kind:'quiz',eyebrow:'§ 20 · термин',title:'Показатель — число одинаковых множителей',body:'В произведении 7·7·7·7 четыре одинаковых множителя.',activity:{id:'l71-p5',type:'input',prompt:'Каков показатель степени 7⁴?',answer:'4',placeholder:'показатель',hint:'Сосчитай одинаковые множители.',explanation:'Показатель равен 4.'},visual:'power'},
{id:'l71-reading',kind:'quiz',eyebrow:'§ 20 · чтение',title:'Степень читаем целиком',body:'Запись 3⁵ означает пять множителей, каждый из которых равен 3.',activity:{id:'l71-p6',type:'choice',prompt:'Как правильно прочитать 3⁵?',options:['три в пятой степени','пять в третьей степени','три умножить на пять','три плюс пять'],answer:'три в пятой степени',hint:'Сначала называют основание, затем показатель.',explanation:'3⁵ читают «три в пятой степени».'},visual:'power'},
{id:'l71-expand',kind:'practice',eyebrow:'§ 20 · степень → произведение',title:'Разверни степень',body:'Показатель 5 требует ровно пяти одинаковых множителей.',activity:{id:'l71-p7',type:'input',prompt:'Запиши 3⁵ как произведение.',answer:['3·3·3·3·3','3*3*3*3*3','3×3×3×3×3'],placeholder:'произведение',hint:'Повтори основание 3 пять раз.',explanation:'3⁵=3·3·3·3·3.'},visual:'product'},
{id:'l71-square',kind:'practice',eyebrow:'§ 20 · квадрат',title:'Вторая степень имеет специальное имя',body:'a² называют квадратом числа a. Это произведение a·a.',activity:{id:'l71-p8',type:'input',prompt:'Вычисли 3².',answer:'9',placeholder:'3²',hint:'3²=3·3.',explanation:'3²=9.'},visual:'power'},
{id:'l71-cube',kind:'practice',eyebrow:'§ 20 · куб',title:'Третья степень — куб',body:'a³ называют кубом числа a. Это произведение трёх одинаковых множителей.',activity:{id:'l71-p9',type:'input',prompt:'Вычисли 5³.',answer:'125',placeholder:'5³',hint:'5·5·5.',explanation:'5³=125.'},visual:'power'},
{id:'l71-first',kind:'practice',eyebrow:'§ 20 · первая степень',title:'Один множитель не превращают в произведение',body:'По договорённости a¹=a.',activity:{id:'l71-p10',type:'input',prompt:'Чему равно 17¹?',answer:'17',placeholder:'17¹',hint:'Первая степень числа равна самому числу.',explanation:'17¹=17.'},visual:'verify'},
{id:'l71-first-rule',kind:'model',eyebrow:'§ 20 · правило',title:'a¹=a — полноценное правило темы',body:'Показатель 1 допустим. Он означает, что значение первой степени совпадает с основанием.',visual:'map'},
{id:'l71-order-model',kind:'guided',eyebrow:'§ 20 · порядок действий',title:'Степень выполняется раньше остальных арифметических действий',body:'Если числовое выражение содержит степень, сначала вычисляют степень, а затем выполняют остальные действия в обычном порядке. В учебнике это новое действие выделено отдельно.',visual:'order'},
{id:'l71-order-multiply',kind:'practice',eyebrow:'§ 20 · пример',title:'5·2² — сначала квадрат',body:'Сначала 2²=4, только потом умножаем на 5.',activity:{id:'l71-p11',type:'input',prompt:'Вычисли 5·2².',answer:'20',placeholder:'значение',hint:'Не умножай 5·2 первым: начни с 2².',explanation:'5·2²=5·4=20.'},visual:'order'},
{id:'l71-order-add',kind:'practice',eyebrow:'§ 20 · пример',title:'5+2² — степень снова первая',body:'Сначала 2²=4, затем прибавляем 5.',activity:{id:'l71-p12',type:'input',prompt:'Вычисли 5+2².',answer:'9',placeholder:'значение',hint:'2²=4.',explanation:'5+2²=5+4=9.'},visual:'order'},
{id:'l71-terms-map',kind:'model',eyebrow:'§ 20 · карта понятий',title:'Основание, показатель, квадрат, куб, первая степень',body:'В aⁿ: a — основание, n — показатель. a² — квадрат, a³ — куб, a¹=a. А вычисление степени означает умножение основания само на себя нужное число раз.',visual:'map'},
{id:'l71-548-model',kind:'guided',eyebrow:'№ 548',title:'Назови основание и показатель',body:'В № 548 нужно читать готовую запись степени и точно разделять две роли: что повторяется и сколько раз.',visual:'power',sourceExercise:'№ 548'},
{id:'l71-548-numeric',kind:'practice',eyebrow:'№ 548(1–2)',title:'Числовые степени',body:'В учебнике даны 4⁸ и 13¹⁰.',activity:{id:'l71-p13',type:'input',prompt:'Для 4⁸ запиши через запятую основание и показатель.',answer:['4,8','4;8'],placeholder:'основание, показатель',hint:'Большое число в строке — основание, верхний показатель — число множителей.',explanation:'Основание 4, показатель 8.'},visual:'power',sourceExercise:'№ 548(1)'},
{id:'l71-548-symbolic',kind:'practice',eyebrow:'№ 548(3–4)',title:'Буква тоже может быть основанием или показателем',body:'В № 548 встречаются a⁹ и 6ᵐ.',activity:{id:'l71-p14',type:'input',prompt:'Для a⁹ запиши через запятую основание и показатель.',answer:['a,9','а,9','a;9','а;9'],placeholder:'основание, показатель',hint:'Основание — a, показатель — 9.',explanation:'У a⁹ основание a, показатель 9.'},visual:'power',sourceExercise:'№ 548(3)'},
{id:'l71-549-model',kind:'guided',eyebrow:'№ 549',title:'Теперь идём в обратную сторону: произведение → степень',body:'№ 549 просит заменить произведение одинаковых множителей степенью. Сначала найди сам повторяющийся множитель, затем сосчитай количество повторов.',visual:'product',sourceExercise:'№ 549'},
{id:'l71-549-simple',kind:'practice',eyebrow:'№ 549(1)',title:'Пять девяток',body:'9·9·9·9·9 содержит пять одинаковых множителей 9.',activity:{id:'l71-p15',type:'input',prompt:'Запиши произведение степенью.',answer:['9^5','9⁵'],placeholder:'степень',hint:'Основание 9, показатель 5.',explanation:'9·9·9·9·9=9⁵.'},visual:'power',sourceExercise:'№ 549(1)'},
{id:'l71-549-ellipsis',kind:'model',eyebrow:'№ 549(6–8) · новая запись',title:'Многоточие экономит место, но не отменяет счёт множителей',body:'Методическое пособие отдельно предупреждает: запись с многоточием для ученика новая. Под скобкой или подписью указано, сколько одинаковых множителей имеется. Например, десять множителей 6 дают 6¹⁰; восемь множителей y дают y⁸; n множителей c дают cⁿ.',note:'Не считай только видимые символы вокруг многоточия — используй указанное общее количество множителей.',visual:'product',sourceExercise:'№ 549(6–8)'},
{id:'l71-549-ten',kind:'practice',eyebrow:'№ 549(6)',title:'Десять одинаковых шестёрок',body:'В записи № 549(6) указано ровно 10 множителей 6.',activity:{id:'l71-p16',type:'input',prompt:'Запиши произведение как степень.',answer:['6^10','6¹⁰'],placeholder:'степень',hint:'Основание 6, показатель 10.',explanation:'Получаем 6¹⁰.'},visual:'power',sourceExercise:'№ 549(6)'},
{id:'l71-550-model',kind:'guided',eyebrow:'№ 550',title:'Вычисли значение степени',body:'№ 550 проверяет, что короткая запись не стала магическим значком: степень нужно уметь развернуть в умножение и вычислить.',visual:'power',sourceExercise:'№ 550'},
{id:'l71-550-values',kind:'practice',eyebrow:'№ 550(1–3)',title:'Куб, квадрат и четвёртая степень',body:'Вычисли 3³, 7² и 5⁴.',activity:{id:'l71-p17',type:'input',prompt:'Запиши три значения через запятую.',answer:['27,49,625','27;49;625'],placeholder:'3³, 7², 5⁴',hint:'3·3·3; 7·7; 5·5·5·5.',explanation:'3³=27, 7²=49, 5⁴=625.'},visual:'verify',sourceExercise:'№ 550(1–3)'},
{id:'l71-550-special',kind:'practice',eyebrow:'№ 550(5–6)',title:'Ноль и квадрат 11',body:'№ 550 содержит 0⁶ и 11².',activity:{id:'l71-p18',type:'input',prompt:'Запиши значения 0⁶ и 11² через запятую.',answer:['0,121','0;121'],placeholder:'0⁶, 11²',hint:'Любая положительная степень нуля равна 0; 11·11=121.',explanation:'0⁶=0, 11²=121.'},visual:'verify',sourceExercise:'№ 550(5–6)'},
{id:'l71-552-model',kind:'guided',eyebrow:'№ 552',title:'Степень внутри обычного числового выражения',body:'№ 552 тренирует главный новый порядок: сначала все степени, затем умножение и деление, затем сложение и вычитание с учётом скобок.',visual:'order',sourceExercise:'№ 552'},
{id:'l71-552-easy',kind:'practice',eyebrow:'№ 552(1–2)',title:'Сначала степени, потом разность',body:'Вычисли 10²−7² и 5³−5².',activity:{id:'l71-p19',type:'input',prompt:'Запиши два результата через запятую.',answer:['51,100','51;100'],placeholder:'результаты',hint:'100−49; 125−25.',explanation:'10²−7²=51, 5³−5²=100.'},visual:'order',sourceExercise:'№ 552(1–2)'},
{id:'l71-552-order',kind:'practice',eyebrow:'№ 552(3)',title:'Степени → деление и умножение → вычитание',body:'42²:14−4²·6. Сначала 42²=1764 и 4²=16, затем 1764:14=126 и 16·6=96.',activity:{id:'l71-p20',type:'input',prompt:'Чему равно всё выражение?',answer:'30',placeholder:'значение',hint:'126−96.',explanation:'42²:14−4²·6=30.'},visual:'order',sourceExercise:'№ 552(3)'},
{id:'l71-552-transfer',kind:'model',eyebrow:'№ 552(4–6)',title:'Проверка порядка на более плотных выражениях',body:'Оставшиеся пункты № 552 используют ту же схему. Например, в 8³:4²−2³ сначала вычисляются 8³, 4² и 2³. В выражении со скобками сначала степени внутри скобок, затем действие в скобках, после чего деление.',note:'Цель не в угадывании ответа, а в строгом порядке действий.',visual:'challenge',sourceExercise:'№ 552(4–6)'},
{id:'l71-560-repeat',kind:'practice',eyebrow:'Повторение · № 560(1–2)',title:'Новая тема не отменяет старые уравнения',body:'Реши 7(x−19)=133 и 9(213−2x)=927.',activity:{id:'l71-p21',type:'input',prompt:'Запиши два корня через запятую.',answer:['38,55','38;55'],placeholder:'x₁, x₂',hint:'133:7=19, затем x−19=19. Во втором 927:9=103, затем 213−2x=103.',explanation:'Корни: 38 и 55.'},visual:'verify',sourceExercise:'№ 560(1–2)'},
{id:'l71-questions',kind:'model',eyebrow:'Вопросы 1–6 · с. 136',title:'Шесть вопросов, которые должны отвечаться без подсказки',body:'Что называют степенью? Что такое основание и показатель? Как читается aⁿ? Как называются a² и a³? Чему равно a¹? В каком порядке выполняют вычисления, если есть степень? Если на любой из этих вопросов ответ не приходит сразу — вернись к соответствующему этапу.',visual:'map',sourceExercise:'Вопросы 1–6, с. 136'},
{id:'l71-summary',kind:'summary',eyebrow:'Итог урока 71',title:'Ты читаешь, раскрываешь и вычисляешь степени',body:'Новая запись теперь имеет точный смысл: aⁿ — произведение n одинаковых множителей a; a — основание, n — показатель; a² — квадрат, a³ — куб, a¹=a. В числовых выражениях степень вычисляется раньше остальных обычных действий.',note:'Обязательная практика: 20 задач / 50 ответов. Домашний перенос по карте: § 20, вопросы 1–6, № 551, 553, 561. Урок 72 продолжит § 20 закреплением.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'aⁿ',map:'§20',power:'aⁿ',product:'a·a·…',order:'1 → n',verify:'✓',challenge:'★',final:'71'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='power'?'основание + показатель':kind==='product'?'одинаковые множители':kind==='order'?'сначала степень':kind==='verify'?'проверь вычисление':kind==='challenge'?'объясни правило':'степень числа · § 20'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyOneStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function PowerFoundationsPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyOneStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyOneStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==71||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyOneStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyOneStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player power-foundations-player" data-lesson-number="71" data-source-reference="Мерзляк § 20 · технологическая карта урока 71 · № 548, 549, 550, 552; повторение № 560 (1–2)" data-source-exercise-range="548,549,550,552,560"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyOneStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSeventyOneStages.length-1||!canContinue}>{saved.stageIndex===lessonSeventyOneStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
