import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './angleLesson.css';
import './angleMeasurement.css';

type Activity={id:string;type:'choice'|'input'|'angle';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string;min?:number;max?:number};
type Diagram='setup'|'centerError'|'baseline'|'scale'|'read35'|'read145'|'rotated'|'estimate'|'construct'|'verify'|'mistakes'|'types';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-40-progress-v1';
const normalize=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/\s+/g,'').replace(/[°º]/g,'').replace(/Ё/g,'Е');

export const lessonFortyStages:Stage[]=[
  {id:'l40-mission',kind:'story',eyebrow:'Урок 40 · § 12 · практика',title:'Сегодня транспортир становится инструментом, а не картинкой',body:'На уроке 39 мы узнали, что такое градус и как устроен транспортир. Теперь тренируем точность. В конце урока ты должен уметь измерить незнакомый угол, построить угол по числу градусов и сразу заметить неверный результат.',note:'Правило урока: сначала геометрия — центр и сторона, затем числа — ноль и шкала.',diagram:'setup'},
  {id:'l40-algorithm',kind:'model',eyebrow:'Алгоритм',title:'Четыре шага измерения',body:'1) Центр транспортира — точно в вершину. 2) Одну сторону угла совмести с основанием. 3) Найди на этой стороне 0° и выбери шкалу, которая начинается здесь. 4) Считай число там, где вторая сторона пересекает шкалу.',note:'Если ответ выглядит странно, не пересчитывай штрихи наугад — заново проверь четыре шага.',diagram:'setup'},
  {id:'l40-practice1',kind:'practice',eyebrow:'Практика · 1/13',title:'Что проверяется первым?',body:'Начинаем не со шкалы.',activity:{id:'l40-p1',type:'choice',prompt:'Что нужно сделать первым при измерении угла?',options:['Совместить центр транспортира с вершиной угла','Найти отметку 90°','Выбрать большее число на шкале','Посчитать все штрихи от края'],answer:'Совместить центр транспортира с вершиной угла',hint:'Обе стороны угла выходят из одной точки.',explanation:'Сначала центр транспортира совмещают с вершиной угла.'}},
  {id:'l40-center-error',kind:'model',eyebrow:'Ошибка № 1',title:'Сдвинутый центр ломает всё измерение',body:'Если центр транспортира находится рядом с вершиной, а не на ней, лучи пересекают шкалу не в тех местах. Даже правильно выбранная шкала после этого даст неверный ответ.',diagram:'centerError'},
  {id:'l40-practice2',kind:'practice',eyebrow:'Практика · 2/13',title:'Диагностика установки',body:'Смотри на вершину, а не на красивые совпадения по краям.',diagram:'centerError',activity:{id:'l40-p2',type:'choice',prompt:'На рисунке центр транспортира сдвинут вправо от вершины. Можно ли считывать угол?',options:['Нет, сначала нужно совместить центр с вершиной','Да, если одна сторона проходит через 0°','Да, если угол острый','Да, если шкала хорошо видна'],answer:'Нет, сначала нужно совместить центр с вершиной',hint:'Нулевая линия не исправляет ошибку положения центра.',explanation:'Измерение начинается только после точного совмещения центра и вершины.'}},
  {id:'l40-baseline-model',kind:'model',eyebrow:'Шаг 2',title:'Исходный луч лежит на нулевой линии',body:'После центра поверни транспортир вокруг вершины. Исходная сторона угла должна лечь вдоль основания. Важно не просто сделать её параллельной основанию, а провести через центр и нулевую отметку.',diagram:'baseline'},
  {id:'l40-practice3',kind:'practice',eyebrow:'Практика · 3/13',title:'Параллельно — недостаточно',body:'Проверяем точность установки.',activity:{id:'l40-p3',type:'choice',prompt:'Луч идёт параллельно основанию транспортира, но проходит выше центра. Установка верна?',options:['Нет','Да','Только для прямого угла','Только для тупого угла'],answer:'Нет',hint:'Сторона угла начинается в вершине, а вершина должна быть в центре.',explanation:'Луч должен проходить через центр и совпадать с основанием, а не просто быть ему параллелен.'}},
  {id:'l40-scale-model',kind:'model',eyebrow:'Шаг 3',title:'Две шкалы — один правильный ноль',body:'У полукруглого транспортира часто две шкалы: одна растёт слева направо, другая — справа налево. Не запоминай «внутренняя» или «внешняя». Смотри только на исходный луч: правильная шкала на нём показывает 0°.',note:'Это универсальное правило работает при любом повороте рисунка.',diagram:'scale'},
  {id:'l40-practice4',kind:'practice',eyebrow:'Практика · 4/13',title:'Выбери шкалу',body:'Один штрих подписан двумя числами.',diagram:'scale',activity:{id:'l40-p4',type:'choice',prompt:'На нужном штрихе стоят 42° и 138°. Исходный луч лежит на правом 0°, и от правого нуля шкала возрастает к 42. Каков угол?',options:['42°','138°','90°','180°'],answer:'42°',hint:'Иди от своего нуля по возрастающим значениям.',explanation:'От правого 0° правильная шкала приходит к 42°, поэтому угол равен 42°.'}},
  {id:'l40-read35-model',kind:'guided',eyebrow:'Измеряем вместе',title:'Острый угол 35°',body:'Центр совпал с вершиной O. Луч OA лежит на правом 0°. Вторая сторона OB проходит через штрих 35°/145°. Так как отсчёт начался справа, читаем 35°.',diagram:'read35'},
  {id:'l40-practice5',kind:'practice',eyebrow:'Практика · 5/13',title:'Считай острый угол',body:'Не выбирай число только потому, что оно меньше.',diagram:'read35',activity:{id:'l40-p5',type:'input',prompt:'Введи градусную меру показанного угла.',answer:'35',placeholder:'Градусы',hint:'Исходный луч стоит на правом 0°.',explanation:'Правильный отсчёт даёт 35°.'}},
  {id:'l40-read145-model',kind:'guided',eyebrow:'Измеряем вместе',title:'Тупой угол 145°',body:'Теперь исходный луч снова начинается на 0°, но вторая сторона пересекает правильную шкалу уже после отметки 90°. Получаем 145°. На том же штрихе противоположная шкала покажет 35°, но она начинается не с нашего нуля.',diagram:'read145'},
  {id:'l40-practice6',kind:'practice',eyebrow:'Практика · 6/13',title:'Не преврати тупой угол в острый',body:'Сначала оцени форму, потом читай шкалу.',diagram:'read145',activity:{id:'l40-p6',type:'input',prompt:'Какова градусная мера показанного тупого угла?',answer:'145',placeholder:'Градусы',hint:'Угол явно больше 90°, поэтому 35° не может быть разумным ответом.',explanation:'По правильной шкале угол равен 145°.'}},
  {id:'l40-rotation-model',kind:'model',eyebrow:'Поворот рисунка',title:'Положение на листе не меняет угол',body:'Если весь рисунок повернуть, величина угла не изменится. Поворачивается и транспортир: центр остаётся в вершине, основание совмещается с выбранным лучом, а отсчёт снова начинается с 0°.',diagram:'rotated'},
  {id:'l40-practice7',kind:'practice',eyebrow:'Практика · 7/13',title:'Угол повернули',body:'Проверяем понимание, а не ориентацию страницы.',activity:{id:'l40-p7',type:'choice',prompt:'Угол 68° повернули на листе на четверть оборота. Какой стала его градусная мера?',options:['68°','158°','90°','22°'],answer:'68°',hint:'Поворот всей фигуры сохраняет величину угла.',explanation:'Положение угла на листе не влияет на его градусную меру.'}},
  {id:'l40-estimate-model',kind:'model',eyebrow:'Проверка здравого смысла',title:'До измерения оцени: меньше или больше 90°',body:'Не нужно угадывать точное число. Достаточно заранее увидеть: угол острый, прямой или тупой. Тогда ошибка шкалы часто обнаруживается мгновенно: рисунок тупой, а ты получил 28° — значит, нужно проверить шкалу.',diagram:'estimate'},
  {id:'l40-practice8',kind:'practice',eyebrow:'Практика · 8/13',title:'Поймай невозможный ответ',body:'Форма — контроль результата.',activity:{id:'l40-p8',type:'choice',prompt:'На рисунке явно тупой угол. После измерения ученик записал 52°. Что вероятнее всего произошло?',options:['Он прочитал противоположную шкалу вместо 128°','Тупой угол действительно может быть 52°','Транспортир всегда занижает тупые углы','Нужно прибавить 90° к любому ответу'],answer:'Он прочитал противоположную шкалу вместо 128°',hint:'На одном штрихе часто стоят дополнительные до 180° числа.',explanation:'52° — острый угол, поэтому для показанного тупого угла разумнее проверить парное показание 128°.'}},
  {id:'l40-construct-model',kind:'model',eyebrow:'Теперь строим',title:'Как построить угол по числу градусов',body:'Нарисуй первый луч и отметь вершину O. Поставь центр транспортира в O, совмести луч с 0° нужной шкалы, найди заданную отметку и поставь точку. Убери транспортир и проведи второй луч из O через эту точку.',note:'Не соединяй отметку на шкале с произвольной точкой — второй луч обязательно начинается в той же вершине.',diagram:'construct'},
  {id:'l40-practice9',kind:'practice',eyebrow:'Практика · 9/13',title:'Построй 40° на экране',body:'Передвигай второй луч. Цель — точно 40°.',activity:{id:'l40-p9',type:'angle',prompt:'Установи градусную меру 40°.',answer:'40',min:0,max:180,hint:'Начни от 0° и остановись на отметке 40°.',explanation:'Луч установлен на 40°. Так же выбирается отметка на реальном транспортире.'}},
  {id:'l40-construct-obtuse',kind:'guided',eyebrow:'Построение тупого угла',title:'Для 118° нужно пройти за 90°',body:'Если строим 118°, сначала убеждаемся, что идём по шкале от своего 0°. Отметка должна оказаться после прямого угла 90°, потому что 118° — тупой угол.',diagram:'construct'},
  {id:'l40-practice10',kind:'practice',eyebrow:'Практика · 10/13',title:'Построй 118° на экране',body:'Не остановись на парном показании 62°.',activity:{id:'l40-p10',type:'angle',prompt:'Установи градусную меру 118°.',answer:'118',min:0,max:180,hint:'118° больше 90°, значит луч должен образовать тупой угол.',explanation:'Получен угол 118°. Парное число на другой шкале — 62° — здесь не подходит.'}},
  {id:'l40-verify-model',kind:'model',eyebrow:'Проверка построения',title:'Построил — измерь ещё раз',body:'Хорошая геометрическая работа заканчивается проверкой. После проведения второго луча снова приложи транспортир по четырём шагам и считай фактическую величину. Если требовалось 75°, а получилось 74° или 76°, перестрой точнее.',diagram:'verify'},
  {id:'l40-practice11',kind:'practice',eyebrow:'Практика · 11/13',title:'Как проверить построение?',body:'Выбираем настоящий контроль, а не взгляд «примерно похоже».',activity:{id:'l40-p11',type:'choice',prompt:'Как лучше проверить построенный угол 75°?',options:['Повторно измерить его транспортиром','Сравнить длины лучей','Посмотреть, симметричен ли рисунок','Проверить линейкой расстояние между концами лучей'],answer:'Повторно измерить его транспортиром',hint:'Проверяем ту же величину независимым повторным измерением.',explanation:'Градусную меру построенного угла проверяют повторным измерением.'}},
  {id:'l40-mistakes-model',kind:'model',eyebrow:'Три главные ошибки',title:'Центр, ноль, шкала',body:'Ошибка A: центр рядом с вершиной. Ошибка B: исходный луч не лежит на нулевой линии. Ошибка C: считана встречная шкала. Их удобно проверять именно в таком порядке: геометрическая установка → ноль → число.',diagram:'mistakes'},
  {id:'l40-practice12',kind:'practice',eyebrow:'Практика · 12/13',title:'Найди ошибку в решении',body:'Ученик получил красивое число, но установка неверна.',activity:{id:'l40-p12',type:'choice',prompt:'Вершина совпадает с центром, исходный луч лежит на основании, но на выбранной шкале в этой точке стоит 180°, а не 0°. Что исправить?',options:['Перейти на другую шкалу, где исходный луч стоит на 0°','Сдвинуть центр','Повернуть сам угол','Вычесть 90° из результата'],answer:'Перейти на другую шкалу, где исходный луч стоит на 0°',hint:'Центр и основание уже установлены правильно.',explanation:'Если исходный луч показывает 180°, выбрана встречная шкала; нужна шкала с 0° на этом луче.'}},
  {id:'l40-classify-model',kind:'model',eyebrow:'Измерил — назови вид',title:'Число сразу классифицирует угол',body:'После измерения сравни результат с 90° и 180°. Меньше 90° — острый; ровно 90° — прямой; между 90° и 180° — тупой; 180° — развёрнутый.',diagram:'types'},
  {id:'l40-practice13',kind:'practice',eyebrow:'Практика · 13/13',title:'Измерение + классификация',body:'Последний раз проверяем границу 90°.',activity:{id:'l40-p13',type:'choice',prompt:'Транспортир показал 92°. Какой это угол?',options:['Тупой','Прямой','Острый','Развёрнутый'],answer:'Тупой',hint:'92° на два градуса больше прямого угла.',explanation:'90° < 92° < 180°, поэтому угол тупой.'}},
  {id:'l40-quiz-intro',kind:'quiz',eyebrow:'Мини-контроль',title:'Пять вопросов без подсказок из модели',body:'Теперь решаем короткий блок подряд. Подсказка появляется только после неверной попытки.'},
  {id:'l40-quiz1',kind:'quiz',eyebrow:'Контроль · 1/5',title:'Положение центра',body:'Точность начинается с вершины.',activity:{id:'l40-q1',type:'choice',prompt:'Центр транспортира должен находиться…',options:['в вершине угла','на середине одной стороны','на отметке 90°','в любой точке основания'],answer:'в вершине угла',hint:'Из вершины выходят оба луча.',explanation:'Центр и вершина должны совпасть.'}},
  {id:'l40-quiz2',kind:'quiz',eyebrow:'Контроль · 2/5',title:'Шкала 27/153',body:'Отсчёт начинается слева.',activity:{id:'l40-q2',type:'input',prompt:'Исходный луч стоит на левом 0°. Правильная шкала возрастает к 153 на нужном штрихе. Каков угол?',answer:'153',placeholder:'Градусы',hint:'Не выбирай автоматически 27.',explanation:'От левого 0° правильная шкала даёт 153°.'}},
  {id:'l40-quiz3',kind:'quiz',eyebrow:'Контроль · 3/5',title:'Построение',body:'Восстанови правильный порядок.',activity:{id:'l40-q3',type:'choice',prompt:'После того как первый луч нарисован и центр транспортира поставлен в вершину, что делать дальше?',options:['Совместить первый луч с 0° нужной шкалы','Сразу провести второй луч на глаз','Отметить 180°','Измерить длину первого луча'],answer:'Совместить первый луч с 0° нужной шкалы',hint:'Построение тоже начинается с нулевого направления.',explanation:'Первый луч задаёт направление 0°, от которого откладывают нужное число градусов.'}},
  {id:'l40-quiz4',kind:'quiz',eyebrow:'Контроль · 4/5',title:'Проверка формы',body:'Результат должен соответствовать рисунку.',activity:{id:'l40-q4',type:'choice',prompt:'Угол выглядит острым, а по выбранной шкале получилось 136°. Что сделать первым?',options:['Проверить, не нужна ли встречная шкала 44°','Записать 136° — шкала всегда важнее рисунка','Вычесть 90°','Разделить 136° пополам'],answer:'Проверить, не нужна ли встречная шкала 44°',hint:'Оценка вида угла — полезная проверка выбора шкалы.',explanation:'Острый угол должен быть меньше 90°, поэтому нужно проверить парное показание 44°.'}},
  {id:'l40-quiz5',kind:'quiz',eyebrow:'Контроль · 5/5',title:'Вид угла',body:'Граница уже знакома.',activity:{id:'l40-q5',type:'choice',prompt:'Какой вид имеет угол 137°?',options:['Тупой','Острый','Прямой','Развёрнутый'],answer:'Тупой',hint:'Сравни 137 с 90 и 180.',explanation:'137° больше 90°, но меньше 180°, значит угол тупой.'}},
  {id:'l40-challenge1',kind:'challenge',eyebrow:'Задача со звёздочкой · 1/2',title:'Почему два числа на штрихе складываются до 180°?',body:'На одном штрихе транспортира стоят 64° и 116°. Обе шкалы измеряют путь от противоположных концов развёрнутого угла.',activity:{id:'l40-c1',type:'input',prompt:'Чему равна сумма двух подписей 64° и 116°?',answer:'180',placeholder:'Градусы',hint:'Две шкалы начинают отсчёт с противоположных лучей одной прямой.',explanation:'64° + 116° = 180°. Парные показания одного штриха дополняют друг друга до развёрнутого угла.'}},
  {id:'l40-challenge2',kind:'challenge',eyebrow:'Задача со звёздочкой · 2/2',title:'Построй 45° без отметки 45°',body:'Представь, что отметка 45° стёрлась, но прямой угол 90° можно построить. Как получить 45°?',activity:{id:'l40-c2',type:'choice',prompt:'Как получить угол 45° из прямого угла?',options:['Разделить прямой угол на две равные части','Прибавить к 90° ещё 45°','Разделить развёрнутый угол на две части','Вычесть 90° из 180°'],answer:'Разделить прямой угол на две равные части',hint:'45 — половина 90.',explanation:'Биссектриса прямого угла делит 90° на два угла по 45°.'}},
  {id:'l40-summary',kind:'summary',eyebrow:'Итог',title:'Транспортир под контролем',body:'Ты умеешь измерять и строить углы по одному алгоритму: центр → нулевая линия → правильная шкала → считывание или отметка. Ты проверяешь ответ по виду угла, не путаешь встречные шкалы и умеешь повторным измерением контролировать построение.',note:'Дальше — 20 обязательных заданий. Они смешивают измерение, построение, поиск ошибок и классификацию, чтобы навык работал не только на одном рисунке.'},
];

function DiagramView({kind}:{kind:Diagram}){
  const base=<><line className="measure-base" x1="70" y1="270" x2="550" y2="270"/><path className="measure-protractor" d="M70 270 A240 240 0 0 1 550 270"/><circle className="measure-center" cx="310" cy="270" r="7"/><text className="angle-label" x="296" y="306">O</text></>;
  if(kind==='centerError')return <div className="angle-diagram" aria-label="Неверно установленный центр транспортира"><svg viewBox="0 0 620 330" role="img"><line className="angle-ray" x1="255" y1="270" x2="545" y2="270"/><line className="angle-ray" x1="255" y1="270" x2="430" y2="80"/><circle className="angle-point" cx="255" cy="270" r="7"/>{base}<text className="measure-label" x="195" y="305">вершина</text><text className="measure-small" x="326" y="250">центр ≠ вершина</text></svg><span className="angle-caption">Так измерять нельзя: центр сдвинут от вершины</span></div>;
  if(kind==='baseline')return <div className="angle-diagram" aria-label="Сторона угла совмещена с нулевой линией"><svg viewBox="0 0 620 330" role="img">{base}<line className="angle-ray" x1="310" y1="270" x2="548" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="465" y2="90"/><text className="measure-small" x="520" y="302">0°</text></svg><span className="angle-caption">Вершина в центре, исходный луч проходит через 0°</span></div>;
  if(kind==='scale'||kind==='read35')return <div className="angle-diagram" aria-label="Две шкалы транспортира и угол 35 градусов"><svg viewBox="0 0 620 330" role="img">{base}<line className="angle-ray" x1="310" y1="270" x2="548" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="505" y2="134"/><path className="angle-arc" d="M390 270 A80 80 0 0 0 376 224"/><text className="measure-label" x="472" y="126">35° / 145°</text><text className="measure-small" x="520" y="302">0°</text></svg><span className="angle-caption">От правого нуля правильное показание — 35°</span></div>;
  if(kind==='read145')return <div className="angle-diagram" aria-label="Тупой угол 145 градусов"><svg viewBox="0 0 620 330" role="img">{base}<line className="angle-ray" x1="310" y1="270" x2="548" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="115" y2="134"/><path className="angle-arc" d="M390 270 A80 80 0 0 0 244 224"/><text className="measure-label" x="78" y="126">145° / 35°</text><text className="measure-small" x="520" y="302">0°</text></svg><span className="angle-caption">От правого нуля до второй стороны — 145°</span></div>;
  if(kind==='rotated')return <div className="angle-diagram" aria-label="Одинаковый угол в двух поворотах"><svg viewBox="0 0 620 310" role="img"><g transform="translate(150 220)"><line className="angle-ray" x1="0" y1="0" x2="150" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="56" y2="-139"/><text className="measure-label" x="52" y="-60">68°</text></g><g transform="translate(450 160) rotate(90)"><line className="angle-ray" x1="0" y1="0" x2="150" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="56" y2="-139"/></g></svg><span className="angle-caption">Поворот меняет положение, но не градусную меру</span></div>;
  if(kind==='estimate')return <div className="angle-diagram" aria-label="Оценка острого и тупого угла"><svg viewBox="0 0 620 300" role="img"><g transform="translate(120 220)"><line className="angle-ray" x1="0" y1="0" x2="160" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="105" y2="-120"/><text className="measure-small" x="30" y="35">меньше 90°</text></g><g transform="translate(470 220)"><line className="angle-ray" x1="0" y1="0" x2="130" y2="0"/><line className="angle-ray" x1="0" y1="0" x2="-95" y2="-100"/><text className="measure-small" x="-82" y="35">больше 90°</text></g></svg><span className="angle-caption">Сначала оценка вида, затем точное измерение</span></div>;
  if(kind==='construct'||kind==='verify')return <div className="angle-diagram" aria-label="Построение угла транспортиром"><svg viewBox="0 0 620 330" role="img">{base}<line className="angle-ray" x1="310" y1="270" x2="548" y2="270"/><circle className="angle-point" cx="425" cy="95" r="7"/><line className="measure-mark" x1="310" y1="270" x2="425" y2="95"/><text className="measure-label" x="435" y="92">отметка</text><text className="measure-small" x="520" y="302">0°</text></svg><span className="angle-caption">Отметка на шкале задаёт направление второго луча</span></div>;
  if(kind==='mistakes')return <div className="angle-diagram" aria-label="Три проверки установки транспортира"><svg viewBox="0 0 620 280" role="img"><text className="measure-label" x="55" y="70">1. центр = вершина</text><text className="measure-label" x="55" y="135">2. луч = нулевая линия</text><text className="measure-label" x="55" y="200">3. шкала начинается с 0°</text><path className="measure-protractor" d="M390 210 A90 90 0 0 1 570 210"/><circle className="measure-center" cx="480" cy="210" r="6"/></svg><span className="angle-caption">Проверяй ошибки в этом порядке</span></div>;
  if(kind==='types')return <div className="angle-diagram" aria-label="Виды углов по градусной мере"><svg viewBox="0 0 620 280" role="img"><text className="measure-label" x="70" y="70">0° &lt; острый &lt; 90°</text><text className="measure-label" x="70" y="125">прямой = 90°</text><text className="measure-label" x="70" y="180">90° &lt; тупой &lt; 180°</text><text className="measure-label" x="70" y="235">развёрнутый = 180°</text></svg></div>;
  return <div className="angle-diagram" aria-label="Правильная установка транспортира"><svg viewBox="0 0 620 330" role="img">{base}<line className="angle-ray" x1="310" y1="270" x2="548" y2="270"/><line className="angle-ray" x1="310" y1="270" x2="440" y2="70"/><text className="measure-small" x="520" y="302">0°</text><text className="measure-label" x="335" y="245">центр → ноль → шкала</text></svg><span className="angle-caption">Точная установка важнее быстрого считывания</span></div>;
}

function AngleBuilder({value}:{value:number}){
  const radians=(180-value)*Math.PI/180;const x=310+190*Math.cos(radians);const y=250-190*Math.sin(radians);
  return <div className="angle-diagram angle-builder" aria-label={`Интерактивное построение угла ${value} градусов`}><svg viewBox="0 0 620 310" role="img"><line className="angle-ray" x1="310" y1="250" x2="530" y2="250"/><line className="angle-ray" x1="310" y1="250" x2={x} y2={y}/><circle className="angle-point" cx="310" cy="250" r="6"/><text className="measure-label" x="292" y="290">{value}°</text></svg></div>;
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function ProtractorPracticePlayer(){
  const initial=useMemo(loadSaved,[]);const[stageIndex,setStageIndex]=useState(initial.stageIndex);const[responses,setResponses]=useState<Record<string,string>>(initial.responses);const[checked,setChecked]=useState<Record<string,boolean>>(initial.checked);const[results,setResults]=useState<Record<string,boolean>>(initial.results);const stage=lessonFortyStages[stageIndex];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,results} satisfies Saved))},[stageIndex,responses,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==40||typeof detail.stageIndex!=='number')return;stopNarration();setStageIndex(Math.min(Math.max(Math.trunc(detail.stageIndex),0),lessonFortyStages.length-1))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  const activity=stage.activity;const defaultAngle=activity?.type==='angle'?String(Math.round(((activity.min??0)+(activity.max??180))/2)):'';const response=activity?responses[activity.id]??defaultAngle:'';const isChecked=activity?Boolean(checked[activity.id]):false;const isCorrect=activity?Boolean(results[activity.id]):false;
  function changeStage(next:number){stopNarration();setStageIndex(Math.min(Math.max(next,0),lessonFortyStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function checkAnswer(){if(!activity||!response.trim())return;const correct=normalize(response)===normalize(activity.answer);setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:correct}))}
  function setResponse(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}));setResults(previous=>({...previous,[activity.id]:false}))}
  return <section className="lesson-player angle-lesson-player measurement-player" aria-label="Урок 40. Транспортир без ошибок"><article className={`interactive-stage stage-${stage.kind} ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<aside className="theory-note">{stage.note}</aside>:null}</div>{stage.diagram?<DiagramView kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button type="button" key={option} className={response===option?'selected':''} aria-pressed={response===option} onClick={()=>setResponse(option)} disabled={isCorrect}>{option}</button>)}</div>:activity.type==='angle'?<div className="angle-control"><AngleBuilder value={Number(response)||0}/><label>Градусная мера: <output>{response}°</output><input aria-label="Градусная мера угла" type="range" min={activity.min??0} max={activity.max??180} step="1" value={response} onChange={event=>setResponse(event.target.value)} disabled={isCorrect}/></label></div>:<div className="inline-answer"><input value={response} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')checkAnswer()}} placeholder={activity.placeholder??'Ответ'} inputMode="numeric" disabled={isCorrect}/></div>}<button type="button" className="check-button" disabled={!response.trim()||isCorrect} onClick={checkAnswer}>Проверить</button>{isChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><b>{isCorrect?'Верно!':'Проверь ещё раз'}</b><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}{stage.kind==='summary'?<div className="summary-card"><strong>§ 12 · урок 2 из 5 завершён</strong><span>Центр · нулевая линия · правильная шкала · измерение · построение · проверка</span></div>:null}<div className="lesson-controls"><button type="button" onClick={()=>changeStage(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {lessonFortyStages.length}</span><button type="button" className="primary" onClick={()=>changeStage(stageIndex+1)} disabled={stageIndex===lessonFortyStages.length-1||(Boolean(activity)&&(!isChecked||!isCorrect))}>{stageIndex===lessonFortyStages.length-1?'Готово':'Дальше →'}</button></div></article></section>
}