import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'solid'|'wire'|'faces'|'measure'|'surface'|'cube'|'source'|'verify'|'final';
export type LessonSeventyEightStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-78-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSeventyEightStages:LessonSeventyEightStage[]=[
{id:'l78-mission',kind:'story',eyebrow:'Урок 78 · § 22 · новая тема',title:'Из плоскости — в пространство',body:'Прямоугольник имеет два измерения. У прямоугольного параллелепипеда появляется третье измерение, а вместе с ним — грани, рёбра, вершины и площадь всей поверхности.',note:'Технологическая карта урока 78: устно № 1–2, с. 150; теория § 22, с. 145–146; № 598, 599, 602; повторение № 612; вопросы 1–12; домашнее № 600, 601, 603.',visual:'mission'},
{id:'l78-oral1-model',kind:'guided',eyebrow:'Актуализация · устно № 1, с. 150',title:'Удобный порядок множителей',body:'Перед геометрией методичка предлагает три устных произведения. Их удобно переставлять и группировать, используя свойства умножения.',visual:'verify',sourceExercise:'Устно № 1, с. 150'},
{id:'l78-oral1-a',kind:'practice',eyebrow:'Устно № 1(1)',title:'Собери 4·25',body:'13·4·25 = 13·(4·25).',activity:{id:'l78-p1',type:'input',prompt:'13·4·25 = ?',answer:'1300',hint:'4·25=100.',explanation:'13·100=1300.'},visual:'verify',sourceExercise:'Устно № 1(1), с. 150'},
{id:'l78-oral1-b',kind:'practice',eyebrow:'Устно № 1(2)',title:'Две удобные пары',body:'4·5·78·5 можно сгруппировать как (4·5)·(78·5).',activity:{id:'l78-p2',type:'input',prompt:'4·5·78·5 = ?',answer:'7800',hint:'4·5=20, 78·5=390.',explanation:'20·390=7800.'},visual:'verify',sourceExercise:'Устно № 1(2), с. 150'},
{id:'l78-oral1-c',kind:'practice',eyebrow:'Устно № 1(3)',title:'125 и 8 дают тысячу',body:'125·943·8 = (125·8)·943.',activity:{id:'l78-p3',type:'input',prompt:'125·943·8 = ?',answer:'943000',hint:'125·8=1000.',explanation:'1000·943=943000.'},visual:'verify',sourceExercise:'Устно № 1(3), с. 150'},
{id:'l78-oral2-model',kind:'guided',eyebrow:'Актуализация · устно № 2, с. 150',title:'Упрощаем буквенные произведения',body:'Числовые множители перемножаем, а буквенные множители записываем рядом. Это пригодится, когда площадь поверхности будем выражать через a, b и c.',visual:'verify',sourceExercise:'Устно № 2, с. 150'},
{id:'l78-oral2-a',kind:'practice',eyebrow:'Устно № 2(1)',title:'3a·16b',body:'Числовой коэффициент равен 3·16.',activity:{id:'l78-p4',type:'input',prompt:'3a·16b = ?',answer:['48ab','48·a·b'],hint:'3·16=48.',explanation:'Получаем 48ab.'},visual:'verify',sourceExercise:'Устно № 2(1), с. 150'},
{id:'l78-oral2-b',kind:'practice',eyebrow:'Устно № 2(2)',title:'4m·9n·5k',body:'Сначала удобно перемножить 4·5, затем 20·9.',activity:{id:'l78-p5',type:'input',prompt:'4m·9n·5k = ?',answer:['180mnk','180·m·n·k'],hint:'4·9·5=180.',explanation:'Получаем 180mnk.'},visual:'verify',sourceExercise:'Устно № 2(2), с. 150'},
{id:'l78-oral2-c',kind:'practice',eyebrow:'Устно № 2(3)',title:'Четыре буквенных множителя',body:'7a·2b·50c·8d: сгруппируй числовые множители.',activity:{id:'l78-p6',type:'input',prompt:'7a·2b·50c·8d = ?',answer:['5600abcd','5600·a·b·c·d'],hint:'7·2·50·8=5600.',explanation:'Получаем 5600abcd.'},visual:'verify',sourceExercise:'Устно № 2(3), с. 150'},
{id:'l78-solid-model',kind:'model',eyebrow:'§ 22 · с. 145–146',title:'Что такое прямоугольный параллелепипед?',body:'Его поверхность состоит из шести прямоугольников — граней. Стороны граней называют рёбрами, а вершины граней — вершинами параллелепипеда.',visual:'solid',sourceExercise:'§ 22, с. 145–146'},
{id:'l78-faces-count',kind:'quiz',eyebrow:'§ 22 · строение',title:'Сколько граней?',body:'Поверхность тела ограничена прямоугольными гранями.',activity:{id:'l78-p7',type:'input',prompt:'Сколько граней у прямоугольного параллелепипеда?',answer:'6',hint:'Есть верх/низ, перед/зад, лево/право.',explanation:'У прямоугольного параллелепипеда 6 граней.'},visual:'faces',sourceExercise:'§ 22 · вопрос 3'},
{id:'l78-edges-count',kind:'quiz',eyebrow:'§ 22 · строение',title:'Сколько рёбер?',body:'Каждое ребро принадлежит двум граням.',activity:{id:'l78-p8',type:'input',prompt:'Сколько рёбер?',answer:'12',hint:'В учебнике прямо зафиксировано: 12 рёбер.',explanation:'У прямоугольного параллелепипеда 12 рёбер.'},visual:'wire',sourceExercise:'§ 22 · вопрос 9'},
{id:'l78-vertices-count',kind:'quiz',eyebrow:'§ 22 · строение',title:'Сколько вершин?',body:'В каждой вершине сходятся три ребра.',activity:{id:'l78-p9',type:'input',prompt:'Сколько вершин?',answer:'8',hint:'Четыре снизу и четыре сверху.',explanation:'У прямоугольного параллелепипеда 8 вершин.'},visual:'wire',sourceExercise:'§ 22 · вопрос 8'},
{id:'l78-opposite-model',kind:'model',eyebrow:'§ 22 · свойство',title:'Противолежащие грани',body:'Грани, не имеющие общих вершин, называют противолежащими. Противолежащие грани прямоугольного параллелепипеда равны.',visual:'faces',sourceExercise:'§ 22, с. 146'},
{id:'l78-opposite-pairs',kind:'practice',eyebrow:'§ 22 · свойство',title:'Три пары',body:'Шесть граней разбиваются на пары противоположных.',activity:{id:'l78-p10',type:'input',prompt:'Сколько пар противолежащих граней?',answer:'3',hint:'6:2.',explanation:'Получаются 3 пары равных противолежащих граней.'},visual:'faces',sourceExercise:'§ 22 · вопрос 4'},
{id:'l78-measure-model',kind:'model',eyebrow:'§ 22 · измерения',title:'Три ребра из одной вершины',body:'Чтобы описать размеры тела, достаточно трёх рёбер с общей вершиной. Их длины называют измерениями прямоугольного параллелепипеда.',visual:'measure',sourceExercise:'§ 22, с. 146'},
{id:'l78-measure-names',kind:'quiz',eyebrow:'§ 22 · измерения',title:'Названия измерений',body:'Для различения трёх измерений используют привычные названия.',activity:{id:'l78-p11',type:'choice',prompt:'Как называют три измерения?',options:['длина, ширина, высота','периметр, площадь, объём','грань, ребро, вершина'],answer:'длина, ширина, высота',hint:'Это три линейные величины.',explanation:'Измерения называют длиной, шириной и высотой.'},visual:'measure',sourceExercise:'§ 22 · вопросы 10–11'},
{id:'l78-surface-model',kind:'model',eyebrow:'§ 22 · площадь поверхности',title:'Складываем площади шести граней',body:'Если измерения равны a, b, c, то есть две грани площади ab, две — bc и две — ac. Поэтому Sпов=2(ab+bc+ac).',visual:'surface',sourceExercise:'§ 22, с. 146'},
{id:'l78-surface-check',kind:'practice',eyebrow:'§ 22 · модель',title:'Проверка формулы',body:'Возьмём размеры 2 см, 3 см и 4 см.',activity:{id:'l78-p12',type:'input',prompt:'2·(2·3+3·4+2·4) = ? см²',answer:'52',placeholder:'см²',hint:'6+12+8=26.',explanation:'2·26=52 см².'},visual:'surface'},
{id:'l78-cube-model',kind:'model',eyebrow:'§ 22 · куб',title:'Особый прямоугольный параллелепипед',body:'Если все три измерения равны, прямоугольный параллелепипед называют кубом. Его поверхность состоит из шести равных квадратов.',visual:'cube',sourceExercise:'§ 22, с. 146'},
{id:'l78-cube-faces',kind:'quiz',eyebrow:'§ 22 · куб',title:'Форма граней куба',body:'Все рёбра куба равны.',activity:{id:'l78-p13',type:'choice',prompt:'Какими фигурами являются грани куба?',options:['квадратами','прямоугольными треугольниками','кругами'],answer:'квадратами',hint:'У прямоугольника с равными соседними сторонами получается квадрат.',explanation:'Все 6 граней куба — равные квадраты.'},visual:'cube',sourceExercise:'§ 22 · вопросы 12–13'},
{id:'l78-598-source',kind:'model',eyebrow:'№ 598 · работа с рисунком 169',title:'Читаем пространственный чертёж по исходнику',body:'№ 598 просит по рисунку 169 назвать грани при вершине C, рёбра, равные BC, верхнюю грань, вершины нижней грани, грани с общим ребром AM и грань, равную DPKC.',note:'Исходный рисунок важен для буквенных обозначений, поэтому приложение не перерисовывает его приблизительно. Выполни № 598 по рисунку учебника; структурные свойства 6/12/8 и равенство противолежащих граней уже проверены интерактивно.',visual:'source',sourceExercise:'№ 598 · рис. 169'},
{id:'l78-599-model',kind:'guided',eyebrow:'№ 599',title:'Три измерения: 9 см, 5 см, 6 см',body:'Нужно вычислить сумму длин всех рёбер и площадь поверхности. Каждое из трёх измерений встречается среди рёбер четыре раза.',visual:'solid',sourceExercise:'№ 599'},
{id:'l78-599-edges',kind:'practice',eyebrow:'№ 599 · сумма рёбер',title:'Четыре одинаковых набора измерений',body:'4·(9+5+6).',activity:{id:'l78-p14',type:'input',prompt:'Сумма длин всех рёбер = ? см',answer:'80',placeholder:'см',hint:'9+5+6=20.',explanation:'4·20=80 см.'},visual:'wire',sourceExercise:'№ 599'},
{id:'l78-599-pairs',kind:'model',eyebrow:'№ 599 · грани',title:'Три площади пар граней',body:'Для измерений 9, 5 и 6 площади разных типов граней равны 9·5=45, 5·6=30 и 9·6=54 см². Каждая такая грань имеет равную противолежащую.',visual:'faces',sourceExercise:'№ 599'},
{id:'l78-599-surface',kind:'practice',eyebrow:'№ 599 · поверхность',title:'Удваиваем сумму трёх площадей',body:'Sпов=2·(45+30+54).',activity:{id:'l78-p15',type:'input',prompt:'Площадь поверхности = ? см²',answer:'258',placeholder:'см²',hint:'45+30+54=129.',explanation:'2·129=258 см².'},visual:'surface',sourceExercise:'№ 599'},
{id:'l78-602-model',kind:'guided',eyebrow:'№ 602',title:'Куб с ребром 5 см',body:'Для куба все 12 рёбер имеют длину 5 см, а каждая из 6 граней — квадрат 5×5.',visual:'cube',sourceExercise:'№ 602'},
{id:'l78-602-face',kind:'practice',eyebrow:'№ 602 · грань',title:'Площадь одной грани',body:'Грань — квадрат со стороной 5 см.',activity:{id:'l78-p16',type:'input',prompt:'5² = ? см²',answer:'25',placeholder:'см²',hint:'5·5.',explanation:'Площадь одной грани 25 см².'},visual:'cube',sourceExercise:'№ 602'},
{id:'l78-602-surface',kind:'practice',eyebrow:'№ 602 · поверхность',title:'Шесть одинаковых граней',body:'У куба шесть равных квадратных граней.',activity:{id:'l78-p17',type:'input',prompt:'6·25 = ? см²',answer:'150',placeholder:'см²',hint:'Площадь поверхности куба 6a².',explanation:'Sпов=150 см².'},visual:'surface',sourceExercise:'№ 602'},
{id:'l78-602-edges',kind:'practice',eyebrow:'№ 602 · рёбра',title:'Двенадцать равных рёбер',body:'У куба 12 рёбер по 5 см.',activity:{id:'l78-p18',type:'input',prompt:'12·5 = ? см',answer:'60',placeholder:'см',hint:'12 рёбер одинаковой длины.',explanation:'Сумма длин рёбер 60 см.'},visual:'wire',sourceExercise:'№ 602'},
{id:'l78-dictation-model',kind:'model',eyebrow:'Методическое пособие · диктант 19',title:'Проверяем пространственное представление',body:'Диктант 19 по § 22 независимо проверяет числа граней, рёбер и вершин, определение куба, а также расчёты каркаса и поверхности.',visual:'verify',sourceExercise:'Диктант 19'},
{id:'l78-dictation-cube64',kind:'practice',eyebrow:'Диктант 19 · № 11',title:'Куб из 64 единичных кубиков',body:'64=4³, значит вдоль каждого ребра большого куба располагаются 4 кубика с ребром 1 см.',activity:{id:'l78-p19',type:'input',prompt:'Чему равно ребро большого куба, см?',answer:'4',placeholder:'см',hint:'4·4·4=64.',explanation:'Ребро большого куба равно 4 см.'},visual:'cube',sourceExercise:'Диктант 19 · № 11'},
{id:'l78-dictation-wire',kind:'practice',eyebrow:'Диктант 19 · № 12',title:'Проволочный каркас',body:'Измерения каркаса 2 см, 4 см и 5 см. Каждое измерение повторяется четыре раза.',activity:{id:'l78-p20',type:'input',prompt:'Сколько проволоки нужно, см?',answer:'44',placeholder:'см',hint:'4·(2+4+5).',explanation:'4·11=44 см.'},visual:'wire',sourceExercise:'Диктант 19 · № 12'},
{id:'l78-dictation-paper',kind:'practice',eyebrow:'Диктант 19 · № 13',title:'Бумага на всю поверхность',body:'Измерения 10 см, 20 см и 30 см. Нужна сумма площадей всех шести граней.',activity:{id:'l78-p21',type:'input',prompt:'2·(10·20+20·30+10·30) = ? см²',answer:'2200',placeholder:'см²',hint:'200+600+300=1100.',explanation:'2·1100=2200 см² бумаги.'},visual:'surface',sourceExercise:'Диктант 19 · № 13'},
{id:'l78-transfer-source',kind:'model',eyebrow:'Повторение и домашний маршрут',title:'№ 612 и самостоятельное закрепление',body:'Технологическая карта урока 78 назначает № 612 для повторения и домашние № 600, 601, 603. № 600: размеры 13, 16, 21 см; № 601: 9, 24, 11 м; № 603: куб с ребром 7 см.',note:'Полное условие № 612 в доступном извлечении не восстановлено надёжно, поэтому оно остаётся source-checkpoint. Домашние № 600, 601, 603 даны по точным условиям учебника.',visual:'source',sourceExercise:'№ 612 · source checkpoint; ДЗ № 600, 601, 603'},
{id:'l78-summary',kind:'summary',eyebrow:'Итог урока 78',title:'Ты читаешь прямоугольный параллелепипед как систему',body:'Теперь 6 граней, 12 рёбер и 8 вершин — не отдельные факты: ты связываешь их с тремя измерениями, тремя парами равных противолежащих граней, суммой рёбер 4(a+b+c) и площадью поверхности 2(ab+bc+ac). Куб — частный случай с a=b=c.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Следующий урок 79 продолжит § 22 и останется заблокирован до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'3D',solid:'▣',wire:'12',faces:'6',measure:'a·b·c',surface:'S',cube:'□³',source:'§22',verify:'✓',final:'78'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='faces'?'6 граней · 3 пары противолежащих':kind==='wire'?'12 рёбер · 8 вершин':kind==='measure'?'длина · ширина · высота':kind==='surface'?'Sпов = 2(ab + bc + ac)':kind==='cube'?'куб: 6 равных квадратов':'пространственная геометрия · § 22'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSeventyEightStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function RectangularParallelepipedPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSeventyEightStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSeventyEightStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==78||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSeventyEightStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSeventyEightStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player rectangular-parallelepiped-player" data-lesson-number="78" data-source-reference="Мерзляк § 22 · технологическая карта урока 78 · устно 1–2 · № 598, 599, 602 · повторение № 612" data-source-exercise-range="598,599,602,612"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonSeventyEightStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonSeventyEightStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
