import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './rectangleSymmetry.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type AxisMode='none'|'vertical'|'horizontal'|'both'|'diagonals'|'four';
type RectangleDiagram={type:'rectangle';shape:'rectangle'|'square';widthLabel:string;heightLabel:string;axes?:AxisMode;showDimensions?:boolean;showSideMarks?:boolean};
type PanelKind='definition'|'sides'|'hierarchy'|'perimeter'|'fold'|'letters'|'polygons'|'errors'|'final';
type Diagram=RectangleDiagram|{type:'panel';kind:PanelKind};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-49-progress-v1';
const normalized=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[−–—]/g,'-').replace(/\s+/g,'').replace(/(?:СМ|ММ|ДМ|°|[.])$/,'');
const answerMatches=(response:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalized(response)===normalized(item))};

export const lessonFortyNineStages:Stage[]=[
  {id:'l49-mission',kind:'story',eyebrow:'Урок 49 · § 15 · новая фигура',title:'Прямые углы, равные стороны и зеркальный тест',body:'Мы научимся распознавать прямоугольник не по тому, как он повёрнут на листе, а по точным свойствам. Затем проверим, какие линии действительно являются осями симметрии.',note:'Источник маршрута: определения и рисунки § 15, задания № 359–365; урок 49 — первый из трёх уроков темы.',diagram:{type:'panel',kind:'definition'}},
  {id:'l49-quad-recall',kind:'practice',eyebrow:'Вспоминаем § 13',title:'Сначала род фигуры',body:'У прямоугольника четыре вершины, четыре стороны и четыре угла.',activity:{id:'l49-p1',type:'choice',prompt:'К какому виду многоугольников относится прямоугольник?',options:['Четырёхугольник','Треугольник','Пятиугольник','Ломаная без границы'],answer:'Четырёхугольник',hint:'Посчитай стороны фигуры.',explanation:'Прямоугольник — четырёхугольник, потому что у него четыре стороны.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'a',heightLabel:'b',showDimensions:false}},
  {id:'l49-definition',kind:'model',eyebrow:'Определение',title:'Прямоугольник — четырёхугольник с четырьмя прямыми углами',body:'Положение на листе не важно. Фигуру можно повернуть: если каждый внутренний угол остаётся равным 90°, перед нами прямоугольник.',diagram:{type:'panel',kind:'definition'}},
  {id:'l49-right-angle-gate',kind:'quiz',eyebrow:'Главный признак',title:'Не доверяй внешнему виду',body:'Похожая на рамку фигура может оказаться наклонным параллелограммом.',activity:{id:'l49-p2',type:'choice',prompt:'Что обязательно проверяют по определению прямоугольника?',options:['Все четыре угла прямые','Только две стороны равны','Диагональ вертикальна','Фигура стоит горизонтально'],answer:'Все четыре угла прямые',hint:'Название фигуры говорит об углах.',explanation:'Определяющее свойство — четыре прямых угла.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'7 см',heightLabel:'4 см'}},
  {id:'l49-right-markers',kind:'model',eyebrow:'Язык чертежа',title:'Маленький квадрат отмечает угол 90°',body:'На точном чертеже отметка прямого угла ставится у каждой вершины. Четыре маркера — визуальная запись определения.',diagram:{type:'rectangle',shape:'rectangle',widthLabel:'7 см',heightLabel:'4 см'}},
  {id:'l49-side-vocabulary',kind:'practice',eyebrow:'Стороны',title:'Соседние имеют общую вершину, противолежащие — нет',body:'В прямоугольнике ABCD стороны записаны по порядку обхода границы.',activity:{id:'l49-p3',type:'choice',prompt:'Как верно описаны пары?',options:['AB и BC — соседние; AB и CD — противолежащие','AB и CD — соседние; AB и BC — противолежащие','AC и BD — стороны','Все стороны соседние'],answer:'AB и BC — соседние; AB и CD — противолежащие',hint:'У AB и BC есть общая вершина B.',explanation:'AB и BC встречаются в B, а AB и CD лежат напротив друг друга.'},diagram:{type:'panel',kind:'sides'}},
  {id:'l49-opposite-properties',kind:'model',eyebrow:'Свойство прямоугольника',title:'Противолежащие стороны попарно равны',body:'Для ABCD выполняется AB=CD и BC=AD. На рисунке одинаковые штрихи показывают равные стороны.',diagram:{type:'rectangle',shape:'rectangle',widthLabel:'8 см',heightLabel:'5 см'}},
  {id:'l49-opposite-pair-gate',kind:'practice',eyebrow:'Читаем обозначения',title:'Найди сторону, равную AB',body:'Вершины идут вокруг границы в порядке A–B–C–D.',activity:{id:'l49-p4',type:'choice',prompt:'Какая сторона противолежит AB и равна ей?',options:['CD','BC','AD','AC'],answer:'CD',hint:'Она не имеет с AB общей вершины.',explanation:'Сторона CD противолежит AB, поэтому CD=AB.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'8 см',heightLabel:'5 см'}},
  {id:'l49-name-order',kind:'practice',eyebrow:'Название фигуры',title:'Буквы идут по границе, а не крест-накрест',body:'Запись ABCD описывает последовательный обход вершин.',activity:{id:'l49-p5',type:'choice',prompt:'Как правильно называть вершины прямоугольника?',options:['Обходить вершины по порядку вокруг границы','Сначала назвать диагонально противоположные','Порядок не имеет значения','Повторить первую букву дважды'],answer:'Обходить вершины по порядку вокруг границы',hint:'Между соседними буквами должна быть сторона.',explanation:'Последовательные буквы задают стороны AB, BC, CD и DA.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'a',heightLabel:'b',showDimensions:false}},
  {id:'l49-square-model',kind:'model',eyebrow:'Особый случай',title:'Квадрат — прямоугольник с четырьмя равными сторонами',body:'У квадрата сохраняются все четыре прямых угла, а соседние стороны дополнительно становятся равными.',diagram:{type:'rectangle',shape:'square',widthLabel:'a',heightLabel:'a'}},
  {id:'l49-square-gate',kind:'quiz',eyebrow:'Определение квадрата',title:'Добавь одно свойство',body:'Четыре прямых угла уже делают фигуру прямоугольником.',activity:{id:'l49-p6',type:'choice',prompt:'Как точнее всего определить квадрат?',options:['Прямоугольник, у которого все стороны равны','Любой четырёхугольник с равными сторонами','Прямоугольник с одной диагональю','Фигура с четырьмя осями без углов'],answer:'Прямоугольник, у которого все стороны равны',hint:'Сохрани свойство прямоугольника и добавь равенство сторон.',explanation:'Квадрат имеет четыре прямых угла и четыре равные стороны.'},diagram:{type:'rectangle',shape:'square',widthLabel:'a',heightLabel:'a'}},
  {id:'l49-shape-hierarchy',kind:'practice',eyebrow:'Связь понятий',title:'Квадрат не исключение из прямоугольников',body:'Он удовлетворяет определению прямоугольника и имеет дополнительное свойство.',activity:{id:'l49-p7',type:'choice',prompt:'Какое утверждение верно?',options:['Каждый квадрат — прямоугольник','Каждый прямоугольник — квадрат','Квадрат не является четырёхугольником','У квадрата нет прямых углов'],answer:'Каждый квадрат — прямоугольник',hint:'У квадрата четыре прямых угла.',explanation:'Каждый квадрат является прямоугольником, но не каждый прямоугольник является квадратом.'},diagram:{type:'panel',kind:'hierarchy'}},
  {id:'l49-source359-rectangle',kind:'guided',eyebrow:'Учебник № 359 · 1',title:'Построй прямоугольник 4 см × 2 см',body:'Строим сторону 4 см, в её концах — два перпендикулярных отрезка по 2 см, затем соединяем их концы и проверяем четвёртый прямой угол.',note:'После построения обязательно измерь обе пары противолежащих сторон.',diagram:{type:'rectangle',shape:'rectangle',widthLabel:'4 см',heightLabel:'2 см'}},
  {id:'l49-source359-sides',kind:'practice',eyebrow:'№ 359 · 1 · проверка',title:'Короткая сторона повторяется дважды',body:'У построенного прямоугольника соседние стороны равны 4 см и 2 см.',activity:{id:'l49-p8',type:'input',prompt:'Чему равна сторона, противолежащая стороне 2 см?',answer:'2',placeholder:'см',hint:'Противолежащие стороны прямоугольника равны.',explanation:'Противолежащая короткая сторона тоже равна 2 см.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'4 см',heightLabel:'2 см'}},
  {id:'l49-source359-perimeter',kind:'practice',eyebrow:'№ 359 · 1 · граница',title:'Периметр — сумма всех четырёх сторон',body:'Обходим фигуру: 4+2+4+2.',activity:{id:'l49-p9',type:'input',prompt:'Найди периметр построенного прямоугольника, см.',answer:'12',placeholder:'см',hint:'Сложи каждую сторону один раз.',explanation:'P=4+2+4+2=12 см.'},diagram:{type:'panel',kind:'perimeter'}},
  {id:'l49-source359-square',kind:'guided',eyebrow:'Учебник № 359 · 2',title:'Построй квадрат со стороной 3 см',body:'Сначала строим прямой угол и откладываем по 3 см на его сторонах. Затем через полученные точки достраиваем ещё два прямых угла.',diagram:{type:'rectangle',shape:'square',widthLabel:'3 см',heightLabel:'3 см'}},
  {id:'l49-source359-square-perimeter',kind:'practice',eyebrow:'№ 359 · 2 · проверка',title:'У квадрата одна длина повторяется четыре раза',body:'Каждая сторона построенного квадрата равна 3 см.',activity:{id:'l49-p10',type:'input',prompt:'Найди периметр квадрата, см.',answer:'12',placeholder:'см',hint:'Умножь длину стороны на 4.',explanation:'P=4·3=12 см.'},diagram:{type:'rectangle',shape:'square',widthLabel:'3 см',heightLabel:'3 см'}},
  {id:'l49-source360-units',kind:'practice',eyebrow:'Учебник № 360',title:'Прямоугольник 25 мм × 35 мм',body:'Перед построением можно перевести миллиметры в сантиметры и миллиметры, не меняя реальную длину.',activity:{id:'l49-p11',type:'choice',prompt:'Какие длины равны данным?',options:['2 см 5 мм и 3 см 5 мм','25 см и 35 см','2 см и 3 см','250 мм и 350 мм'],answer:'2 см 5 мм и 3 см 5 мм',hint:'10 мм=1 см.',explanation:'25 мм=2 см 5 мм, 35 мм=3 см 5 мм.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'35 мм',heightLabel:'25 мм'}},
  {id:'l49-source360-perimeter',kind:'practice',eyebrow:'№ 360 · вычисление',title:'Единицы у всех сторон одинаковые',body:'Складываем 25+35+25+35 миллиметров.',activity:{id:'l49-p12',type:'input',prompt:'Найди периметр прямоугольника, мм.',answer:'120',placeholder:'мм',hint:'Удвой сумму соседних сторон.',explanation:'P=2·(25+35)=120 мм, то есть 12 см.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'35 мм',heightLabel:'25 мм'}},
  {id:'l49-perimeter-model',kind:'model',eyebrow:'Формулы без заучивания',title:'P=2a+2b, а для квадрата P=4a',body:'У прямоугольника каждая из двух разных длин встречается дважды. У квадрата одна длина встречается четыре раза.',diagram:{type:'panel',kind:'perimeter'}},
  {id:'l49-source361-rectangle',kind:'practice',eyebrow:'Учебник № 361 · 1',title:'Соседние стороны 42 см и 23 см',body:'Обе длины входят в периметр дважды.',activity:{id:'l49-p13',type:'input',prompt:'Вычисли P, см.',answer:'130',placeholder:'см',hint:'2·42+2·23.',explanation:'84+46=130 см.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'42 см',heightLabel:'23 см'}},
  {id:'l49-source361-square',kind:'practice',eyebrow:'Учебник № 361 · 2',title:'Квадрат со стороной 8 дм',body:'Все четыре стороны равны.',activity:{id:'l49-p14',type:'input',prompt:'Вычисли P, дм.',answer:'32',placeholder:'дм',hint:'4·8.',explanation:'P=4·8=32 дм.'},diagram:{type:'rectangle',shape:'square',widthLabel:'8 дм',heightLabel:'8 дм'}},
  {id:'l49-source362',kind:'practice',eyebrow:'Учебник № 362',title:'Соседние стороны 13 мм и 17 мм',body:'Сначала вычислим в миллиметрах; затем при желании переведём в сантиметры.',activity:{id:'l49-p15',type:'input',prompt:'Найди периметр, мм.',answer:'60',placeholder:'мм',hint:'2·13+2·17.',explanation:'P=26+34=60 мм=6 см.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'17 мм',heightLabel:'13 мм'}},
  {id:'l49-symmetry-model',kind:'model',eyebrow:'Ось симметрии',title:'Мысленно сложи фигуру по прямой',body:'Если после складывания две части полностью совпадают, фигура симметрична относительно этой прямой, а прямая называется осью симметрии.',diagram:{type:'panel',kind:'fold'}},
  {id:'l49-fold-gate',kind:'quiz',eyebrow:'Проверка определения',title:'Одного прохождения через центр недостаточно',body:'Нужно проверить совпадение каждой точки одной половины с зеркальной точкой другой.',activity:{id:'l49-p16',type:'choice',prompt:'Когда прямая является осью симметрии фигуры?',options:['После складывания половины полностью совпадают','Она проходит через любую вершину','Она длиннее фигуры','Она делит периметр на два числа'],answer:'После складывания половины полностью совпадают',hint:'Представь реальное складывание бумаги.',explanation:'Ось симметрии совмещает фигуру саму с собой при отражении.'},diagram:{type:'panel',kind:'fold'}},
  {id:'l49-rectangle-axis-vertical',kind:'guided',eyebrow:'Прямоугольник · ось 1',title:'Вертикальная ось проходит через середины горизонтальных сторон',body:'Левая и правая половины прямоугольника совпадают после отражения.',diagram:{type:'rectangle',shape:'rectangle',widthLabel:'8 см',heightLabel:'5 см',axes:'vertical'}},
  {id:'l49-rectangle-axis-horizontal',kind:'guided',eyebrow:'Прямоугольник · ось 2',title:'Горизонтальная ось проходит через середины вертикальных сторон',body:'Верхняя и нижняя половины тоже зеркально совпадают.',diagram:{type:'rectangle',shape:'rectangle',widthLabel:'8 см',heightLabel:'5 см',axes:'horizontal'}},
  {id:'l49-diagonal-gate',kind:'practice',eyebrow:'Ловушка',title:'Диагональ обычного прямоугольника — не ось симметрии',body:'При отражении длинная сторона должна была бы перейти в короткую, поэтому половины не совпадут.',activity:{id:'l49-p17',type:'choice',prompt:'Являются ли диагонали осями прямоугольника 8 см × 5 см?',options:['Нет, диагонали не совмещают прямоугольник с самим собой','Да, обе диагонали — оси','Только одна диагональ — ось','Да, если повернуть лист'],answer:'Нет, диагонали не совмещают прямоугольник с самим собой',hint:'Сравни, куда перейдут длинная и короткая стороны.',explanation:'У прямоугольника, не являющегося квадратом, только две оси: горизонтальная и вертикальная.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'8 см',heightLabel:'5 см',axes:'diagonals'}},
  {id:'l49-square-axes',kind:'model',eyebrow:'Квадрат',title:'У квадрата добавляются две диагональные оси',body:'Все стороны равны, поэтому отражение относительно каждой диагонали тоже совмещает квадрат с самим собой. Всего осей четыре.',diagram:{type:'rectangle',shape:'square',widthLabel:'a',heightLabel:'a',axes:'four'}},
  {id:'l49-square-axis-gate',kind:'practice',eyebrow:'Считаем без повтора',title:'Две средние линии и две диагонали',body:'Каждую геометрическую прямую считаем один раз.',activity:{id:'l49-p18',type:'input',prompt:'Сколько осей симметрии у квадрата?',answer:'4',placeholder:'число осей',hint:'Горизонтальная, вертикальная и две диагонали.',explanation:'У квадрата четыре оси симметрии.'},diagram:{type:'rectangle',shape:'square',widthLabel:'a',heightLabel:'a',axes:'four'}},
  {id:'l49-source363-letters',kind:'practice',eyebrow:'Учебник № 363',title:'Ось симметрии зависит от начертания буквы',body:'В начертании рисунка 135 ось имеют четыре буквы.',activity:{id:'l49-p19',type:'choice',prompt:'Какая группа указана в задании № 363?',options:['А, В, Е, Т','А, Б, Г, Я','Ж, И, Л, Р','Все буквы алфавита'],answer:'А, В, Е, Т',hint:'Ищи полное зеркальное совпадение в данном шрифте.',explanation:'На рисунке 135 ось симметрии имеют буквы А, В, Е и Т.'},diagram:{type:'panel',kind:'letters'}},
  {id:'l49-source364-polygons',kind:'practice',eyebrow:'Учебник № 364',title:'Считай только линии полного совпадения',body:'Три многоугольника на рисунке 136 имеют соответственно 2, 1 и 6 осей.',activity:{id:'l49-p20',type:'input',prompt:'Запиши числа осей по порядку через запятую.',answer:['2,1,6','2;1;6','2 1 6'],placeholder:'например: 2, 1, 6',hint:'Первый складывается двумя способами, второй одним, правильный шестиугольник — шестью.',explanation:'Ответ по рисунку 136: 2, 1 и 6 осей симметрии.'},diagram:{type:'panel',kind:'polygons'}},
  {id:'l49-axis-count-gate',kind:'quiz',eyebrow:'Систематизация',title:'Форма определяет число осей',body:'У обычного прямоугольника соседние стороны различны; у квадрата все четыре стороны равны.',activity:{id:'l49-p21',type:'choice',prompt:'Какая пара верна?',options:['Прямоугольник — 2, квадрат — 4','Прямоугольник — 4, квадрат — 2','Обе фигуры — 2','Обе фигуры — бесконечно много'],answer:'Прямоугольник — 2, квадрат — 4',hint:'Диагонали становятся осями только у квадрата.',explanation:'Не-квадратный прямоугольник имеет 2 оси, квадрат — 4.'},diagram:{type:'panel',kind:'hierarchy'}},
  {id:'l49-error-check',kind:'practice',eyebrow:'Поиск ошибки',title:'Равные противоположные стороны ещё не доказывают прямоугольник',body:'У наклонного параллелограмма они тоже равны, но углы не прямые.',activity:{id:'l49-p22',type:'choice',prompt:'Что нужно проверить прежде всего?',options:['Сначала проверить четыре прямых угла','Только измерить одну диагональ','Проверить вертикальное положение','Сосчитать две длинные стороны'],answer:'Сначала проверить четыре прямых угла',hint:'Вернись к определению.',explanation:'Прямоугольник определяется четырьмя прямыми углами; равенство противоположных сторон — его свойство.'},diagram:{type:'panel',kind:'errors'}},
  {id:'l49-control-gate',kind:'challenge',eyebrow:'Учебник № 365 · 1',title:'Одна сторона 14 см, соседняя на 5 см короче',body:'Сначала найди неизвестную сторону, затем сложи четыре стороны.',activity:{id:'l49-p23',type:'input',prompt:'Найди периметр прямоугольника, см.',answer:'46',placeholder:'см',hint:'Соседняя сторона: 14−5=9 см.',explanation:'Вторая сторона 9 см; P=2·14+2·9=46 см.'},diagram:{type:'rectangle',shape:'rectangle',widthLabel:'14 см',heightLabel:'9 см'}},
  {id:'l49-summary',kind:'summary',eyebrow:'Итог урока 49',title:'Свойства превратились в надёжную проверку',body:'Ты узнаёшь прямоугольник по четырём прямым углам, различаешь соседние и противолежащие стороны, вычисляешь периметр, понимаешь квадрат как особый прямоугольник и проверяешь оси симметрии складыванием.',note:'Дальше — обязательная практика из 20 задач с Пифагором и озвучкой Sulafat.',diagram:{type:'panel',kind:'final'}}
];

function RectangleSvg({diagram}:{diagram:RectangleDiagram}){
  const square=diagram.shape==='square';const x=square?220:145;const y=square?40:65;const width=square?240:390;const height=square?240:190;const right=24;const axes=diagram.axes??'none';
  const shownAxisCount=axes==='vertical'||axes==='horizontal'?1:axes==='both'?2:axes==='four'?4:0;const theoreticalAxisCount=square?4:2;const showDimensions=diagram.showDimensions!==false;const showSideMarks=diagram.showSideMarks!==false;
  const vertical=axes==='vertical'||axes==='both'||axes==='four';const horizontal=axes==='horizontal'||axes==='both'||axes==='four';const validDiagonals=axes==='four';const invalidDiagonals=axes==='diagonals';
  return <div className="rectangle-symmetry-diagram" data-shape={diagram.shape} data-width-value={diagram.widthLabel} data-height-value={diagram.heightLabel} data-right-angle-count="4" data-opposite-side-pairs="AB=CD|BC=AD" data-axis-kind={axes} data-axis-count={shownAxisCount} data-theoretical-axis-count={theoreticalAxisCount}>
    <svg viewBox="0 0 680 320" role="img" aria-label={`${square?'Квадрат':'Прямоугольник'} ABCD с отмеченными прямыми углами и равными сторонами`}>
      <rect className={`rectangle-shape ${square?'rectangle-square':''}`} x={x} y={y} width={width} height={height}/>
      <path className="rectangle-right-marker" data-right-angle-marker="A" d={`M ${x+2} ${y+right} H ${x+right} V ${y+2}`}/><path className="rectangle-right-marker" data-right-angle-marker="B" d={`M ${x+width-right} ${y+2} V ${y+right} H ${x+width-2}`}/><path className="rectangle-right-marker" data-right-angle-marker="C" d={`M ${x+width-2} ${y+height-right} H ${x+width-right} V ${y+height-2}`}/><path className="rectangle-right-marker" data-right-angle-marker="D" d={`M ${x+right} ${y+height-2} V ${y+height-right} H ${x+2}`}/>
      {showSideMarks?<><path className="rectangle-side-mark" data-equal-side-mark="horizontal" d={`M ${x+width/2} ${y-9} v 18`}/><path className="rectangle-side-mark" data-equal-side-mark="horizontal" d={`M ${x+width/2} ${y+height-9} v 18`}/><path className="rectangle-side-mark" data-equal-side-mark="vertical" d={`M ${x-9} ${y+height/2-7} h 18 M ${x-9} ${y+height/2+7} h 18`}/><path className="rectangle-side-mark" data-equal-side-mark="vertical" d={`M ${x+width-9} ${y+height/2-7} h 18 M ${x+width-9} ${y+height/2+7} h 18`}/>{square?<><path className="rectangle-side-mark" data-square-extra-mark="top" d={`M ${x+width/2-14} ${y-9} v 18`}/><path className="rectangle-side-mark" data-square-extra-mark="bottom" d={`M ${x+width/2-14} ${y+height-9} v 18`}/></>:null}</>:null}
      {vertical?<line className="rectangle-axis" data-symmetry-axis="vertical" x1={x+width/2} y1={y-28} x2={x+width/2} y2={y+height+28}/>:null}{horizontal?<line className="rectangle-axis" data-symmetry-axis="horizontal" x1={x-28} y1={y+height/2} x2={x+width+28} y2={y+height/2}/>:null}
      {validDiagonals?<><line className="rectangle-axis" data-symmetry-axis="diagonal-ac" x1={x-18} y1={y-18} x2={x+width+18} y2={y+height+18}/><line className="rectangle-axis" data-symmetry-axis="diagonal-bd" x1={x+width+18} y1={y-18} x2={x-18} y2={y+height+18}/></>:null}
      {invalidDiagonals?<><line className="rectangle-invalid-axis" data-invalid-axis="AC" x1={x} y1={y} x2={x+width} y2={y+height}/><line className="rectangle-invalid-axis" data-invalid-axis="BD" x1={x+width} y1={y} x2={x} y2={y+height}/><path className="rectangle-cross" data-axis-rejected="true" d={`M ${x+width/2-17} ${y+height/2-17} l 34 34 M ${x+width/2+17} ${y+height/2-17} l -34 34`}/></>:null}
      <text className="rectangle-label" x={x-28} y={y-12}>A</text><text className="rectangle-label" x={x+width+12} y={y-12}>B</text><text className="rectangle-label" x={x+width+12} y={y+height+25}>C</text><text className="rectangle-label" x={x-28} y={y+height+25}>D</text>
      {showDimensions?<><text className="rectangle-dimension" x={x+width/2-28} y={y-18}>{diagram.widthLabel}</text><text className="rectangle-dimension" x={x+width+25} y={y+height/2+6}>{diagram.heightLabel}</text></>:null}
      {shownAxisCount?<text className="rectangle-axis-label" x={x+10} y={y+height+48}>показано осей: {shownAxisCount}</text>:null}
    </svg>
    <div className="rectangle-symmetry-readout"><span><b>Фигура</b>{square?'квадрат':'прямоугольник'}</span><span><b>Прямые углы</b>4</span><span><b>Оси фигуры</b>{theoreticalAxisCount}</span></div>
  </div>;
}

function PanelDiagram({kind}:{kind:PanelKind}){
  if(kind==='definition')return <div className="rectangle-symmetry-panel" data-panel="definition"><div className="rectangle-definition"><span><b>1</b>четырёхугольник</span><span><b>2</b>четыре угла по <strong>90°</strong></span><span><b>3</b>значит, прямоугольник</span></div></div>;
  if(kind==='sides')return <div className="rectangle-symmetry-panel" data-panel="sides"><div className="rectangle-side-pairs"><span><b>Соседние</b><strong>AB и BC</strong><small>общая вершина B</small></span><span><b>Противолежащие</b><strong>AB и CD</strong><small>общей вершины нет</small></span></div></div>;
  if(kind==='hierarchy')return <div className="rectangle-symmetry-panel" data-panel="hierarchy"><div className="rectangle-hierarchy"><span><b>Прямоугольник</b><small>4 прямых угла</small></span><i>→</i><span><b>Квадрат</b><small>4 прямых угла + 4 равные стороны</small></span></div></div>;
  if(kind==='perimeter')return <div className="rectangle-symmetry-panel" data-panel="perimeter"><div className="rectangle-perimeter"><span><b>P=2a+2b</b><small>прямоугольник</small></span><span><b>P=4a</b><small>квадрат</small></span></div></div>;
  if(kind==='fold')return <div className="rectangle-symmetry-panel" data-panel="fold"><div className="rectangle-fold"><span>левая половина</span><i>│ зеркало │</i><span>правая половина</span><strong>совпали после складывания → прямая является осью</strong></div></div>;
  if(kind==='letters')return <div className="rectangle-symmetry-panel" data-panel="letters"><div className="rectangle-letters"><span className="rectangle-letter" data-axis="vertical">А</span><span className="rectangle-letter" data-axis="horizontal">В</span><span className="rectangle-letter" data-axis="horizontal">Е</span><span className="rectangle-letter" data-axis="vertical">Т</span></div></div>;
  if(kind==='polygons')return <div className="rectangle-symmetry-panel" data-panel="polygons"><div className="rectangle-polygons"><span data-polygon-axis-count="2"><svg viewBox="0 0 100 70"><polygon points="15,15 85,15 85,55 15,55"/><line x1="50" y1="5" x2="50" y2="65"/><line x1="5" y1="35" x2="95" y2="35"/></svg><b>2 оси</b></span><span data-polygon-axis-count="1"><svg viewBox="0 0 100 70"><polygon points="50,7 92,60 8,60"/><line x1="50" y1="2" x2="50" y2="66"/></svg><b>1 ось</b></span><span data-polygon-axis-count="6"><svg viewBox="0 0 100 70"><polygon points="25,7 75,7 95,35 75,63 25,63 5,35"/><line x1="50" y1="1" x2="50" y2="69"/><line x1="1" y1="35" x2="99" y2="35"/></svg><b>6 осей</b></span></div></div>;
  if(kind==='errors')return <div className="rectangle-symmetry-panel" data-panel="errors"><div className="rectangle-errors"><span><b>✕</b>«похоже на рамку»</span><span><b>✕</b>«две стороны равны»</span><span><b>✕</b>«любая линия через центр»</span><strong>Проверка: 4 угла по 90° → пары сторон → зеркальное совпадение</strong></div></div>;
  return <div className="rectangle-symmetry-panel" data-panel="final"><div className="rectangle-final"><b>4 угла ✓</b><b>пары сторон ✓</b><b>периметр ✓</b><b>оси ✓</b></div></div>;
}

function DiagramView({diagram}:{diagram:Diagram}){return diagram.type==='rectangle'?<RectangleSvg diagram={diagram}/>:<PanelDiagram kind={diagram.kind}/>}
function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyNineStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function RectangleSymmetryPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFortyNineStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFortyNineStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==49||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFortyNineStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFortyNineStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player rectangle-symmetry-player" data-lesson-number="49" data-source-reference="Мерзляк §15 · №359–365"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<DiagramView diagram={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} Можно перейти дальше и вернуться к заданию позже.`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFortyNineStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFortyNineStages.length-1||!canContinue}>{saved.stageIndex===lessonFortyNineStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
