import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'map'|'division'|'equation'|'work'|'expression'|'verify'|'error'|'challenge'|'final';
export type LessonSixtyNineStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-69-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'');
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalize(value)===normalize(item))};

export const lessonSixtyNineStages:LessonSixtyNineStage[]=[
{id:'l69-mission',kind:'story',eyebrow:'Урок 69 · § 19 · закрепление',title:'Остаток найден. А что он означает?',body:'Сегодня превращаем новое правило в рабочий навык. Нужно не только вычислить неполное частное и остаток, но и решить, как они отвечают на вопрос задачи, восстановить неизвестный компонент и доказать, что запись корректна.',note:'Технологическая карта урока 69: устно № 2–3, с. 132; закрепление № 528, 530, 533, 535, 541, 542; повторение № 546; домашний перенос № 529, 534, 536.',visual:'mission'},
{id:'l69-map',kind:'model',eyebrow:'Карта навыка',title:'Четыре проверки одной записи',body:'Для a=b·q+r проверь: q — число полных групп; r=a−b·q; 0≤r<b; смысл ответа соответствует вопросу задачи. Иногда ответом будет q, иногда r, а иногда q+1.',visual:'map'},
{id:'l69-warmup',kind:'quiz',eyebrow:'Устная разминка',title:'Как узнать, что деление записано правильно?',body:'Равенство само по себе недостаточно: остаток обязан быть меньше делителя.',activity:{id:'l69-p1',type:'choice',prompt:'Какая запись является корректным делением 38 на 7 с остатком?',options:['38=7·5+3','38=7·4+10','38=7·3+17','38=7·2+24'],answer:'38=7·5+3',hint:'Проверь и равенство, и условие r<7.',explanation:'38=35+3 и 3<7.'},visual:'verify'},
{id:'l69-528-model',kind:'guided',eyebrow:'№ 528',title:'42 т песка и грузовики по 5 т',body:'Точное условие № 528: на один грузовик можно нагрузить 5 т песка. Нужно найти наименьшее количество грузовиков, чтобы перевезти 42 т. Здесь положительный остаток означает, что понадобится ещё один грузовик.',visual:'work',sourceExercise:'№ 528'},
{id:'l69-528-q',kind:'practice',eyebrow:'№ 528 · неполное частное',title:'Сколько грузовиков заполнятся полностью?',body:'42 : 5. Сначала находим число полных пятёрок.',activity:{id:'l69-p2',type:'input',prompt:'Найди неполное частное q.',answer:'8',placeholder:'q',hint:'5·8=40, а 5·9=45>42.',explanation:'q=8: полностью загрузятся 8 грузовиков.'},visual:'division',sourceExercise:'№ 528'},
{id:'l69-528-r',kind:'practice',eyebrow:'№ 528 · остаток',title:'Сколько тонн останется?',body:'В восемь полных грузовиков войдёт 40 т.',activity:{id:'l69-p3',type:'input',prompt:'Найди остаток r.',answer:'2',placeholder:'r',hint:'42−40.',explanation:'r=2, то есть после 8 полных загрузок остаются ещё 2 т.'},visual:'division',sourceExercise:'№ 528'},
{id:'l69-528-answer',kind:'practice',eyebrow:'№ 528 · смысл ответа',title:'Остаток меняет итог',body:'Оставшиеся 2 т нельзя бросить: для них нужен ещё один грузовик.',activity:{id:'l69-p4',type:'input',prompt:'Какое наименьшее количество грузовиков требуется?',answer:['9','9 грузовиков'],placeholder:'грузовиков',hint:'Если r>0 и нужно перевезти всё, добавь один транспорт к q.',explanation:'Нужно 9 грузовиков: 8 полных и один для оставшихся 2 т.'},visual:'work',sourceExercise:'№ 528'},
{id:'l69-528-rule',kind:'quiz',eyebrow:'№ 528 · обобщение',title:'Когда нужно q+1?',body:'В задачах на вместимость положительный остаток часто означает ещё одну ёмкость.',activity:{id:'l69-p5',type:'choice',prompt:'Когда для перевозки всего груза ответ равен q+1?',options:['когда r>0','всегда','только когда r=0','когда r=b'],answer:'когда r>0',hint:'Если что-то осталось, нужна ещё одна неполная ёмкость.',explanation:'При r>0 есть незагруженный остаток, поэтому полной величины q недостаточно.'},visual:'map',sourceExercise:'№ 528'},
{id:'l69-530-source',kind:'guided',eyebrow:'№ 530',title:'Таблица компонентов деления с остатком',body:'№ 530 просит заполнить таблицу «делимое — делитель — неполное частное — остаток». Исходные строки выполняй непосредственно по учебнику. Здесь мы тренируем точно тот же способ восстановления компонентов, не реконструируя не полностью извлечённую таблицу.',note:'Главный инструмент: a=b·q+r и обязательная проверка 0≤r<b.',visual:'map',sourceExercise:'№ 530'},
{id:'l69-530-rule',kind:'model',eyebrow:'№ 530 · стратегия',title:'Неизвестный компонент восстанавливаем из формулы',body:'Если неизвестно a, вычисли b·q+r. Если неизвестен r, вычисли a−b·q. Если неизвестны q или b, сначала отдели остаток: a−r=b·q.',visual:'equation',sourceExercise:'№ 530'},
{id:'l69-530-a',kind:'practice',eyebrow:'Структура № 530',title:'Восстанови делимое',body:'Дано b=7, q=6, r=3.',activity:{id:'l69-p6',type:'input',prompt:'Найди a.',answer:'45',placeholder:'a',hint:'a=7·6+3.',explanation:'a=42+3=45.'},visual:'equation',sourceExercise:'№ 530'},
{id:'l69-530-r',kind:'practice',eyebrow:'Структура № 530',title:'Восстанови остаток',body:'Дано a=53, b=8, q=6.',activity:{id:'l69-p7',type:'input',prompt:'Найди r.',answer:'5',placeholder:'r',hint:'r=53−8·6.',explanation:'r=5; проверка: 5<8.'},visual:'verify',sourceExercise:'№ 530'},
{id:'l69-530-q',kind:'practice',eyebrow:'Структура № 530',title:'Восстанови неполное частное',body:'Дано a=83, b=9, r=2.',activity:{id:'l69-p8',type:'input',prompt:'Найди q.',answer:'9',placeholder:'q',hint:'83−2=81; 81:9.',explanation:'q=9: 83=9·9+2.'},visual:'division',sourceExercise:'№ 530'},
{id:'l69-530-b',kind:'practice',eyebrow:'Структура № 530',title:'Восстанови делитель',body:'Дано a=47, q=5, r=2.',activity:{id:'l69-p9',type:'input',prompt:'Найди b.',answer:'9',placeholder:'b',hint:'47−2=45; 45:5.',explanation:'b=9: 47=9·5+2, и 2<9.'},visual:'division',sourceExercise:'№ 530'},
{id:'l69-533-model',kind:'guided',eyebrow:'№ 533',title:'Запиши 82 через делитель, q и r',body:'Точное условие № 533 задаёт a=82 и b=8 и просит представить делимое в форме a=bq+r. Нужно выполнить деление 82 на 8 и собрать равенство.',visual:'equation',sourceExercise:'№ 533'},
{id:'l69-533-q',kind:'practice',eyebrow:'№ 533',title:'Неполное частное',body:'8·10=80, а следующая восьмёрка уже больше 82.',activity:{id:'l69-p10',type:'input',prompt:'Найди q.',answer:'10',placeholder:'q',hint:'Ищи максимальное целое q с 8q≤82.',explanation:'q=10.'},visual:'division',sourceExercise:'№ 533'},
{id:'l69-533-r',kind:'practice',eyebrow:'№ 533',title:'Остаток',body:'После 80 остаётся небольшая часть делимого.',activity:{id:'l69-p11',type:'input',prompt:'Найди r.',answer:'2',placeholder:'r',hint:'82−80.',explanation:'r=2, и 2<8.'},visual:'division',sourceExercise:'№ 533'},
{id:'l69-533-equality',kind:'quiz',eyebrow:'№ 533',title:'Собери проверку',body:'Теперь запиши все четыре компонента одной строкой.',activity:{id:'l69-p12',type:'choice',prompt:'Какое равенство верно?',options:['82=8·10+2','82=8·2+10','82=10·2+8','82=8·11+2'],answer:'82=8·10+2',hint:'a=b·q+r.',explanation:'82=80+2; это точная запись деления с остатком.'},visual:'verify',sourceExercise:'№ 533'},
{id:'l69-535-model',kind:'guided',eyebrow:'№ 535',title:'Минимальное натуральное a и нужный остаток',body:'№ 535 учит работать обратно: подобрать наименьшее натуральное a, чтобы выражение делилось нацело или давало заданный остаток. Ищи не перебором вслепую, а через ближайшее подходящее кратное.',note:'Методический комментарий предлагает усилить эти задачи поиском нескольких значений a и закономерности.',visual:'challenge',sourceExercise:'№ 535'},
{id:'l69-535-1',kind:'practice',eyebrow:'№ 535(1)',title:'48+a делится на 6',body:'48 уже кратно 6, но a требуется натуральное, то есть положительное.',activity:{id:'l69-p13',type:'input',prompt:'Каково наименьшее натуральное a?',answer:'6',placeholder:'a',hint:'Нужно снова попасть в кратное 6; первое положительное смещение от 48 — 6.',explanation:'a=6: 48+6=54, 54 делится на 6.'},visual:'expression',sourceExercise:'№ 535(1)'},
{id:'l69-535-2',kind:'practice',eyebrow:'№ 535(2)',title:'65−a делится на 8',body:'Ближайшее меньшее кратное 8 к 65 — 64.',activity:{id:'l69-p14',type:'input',prompt:'Каково наименьшее натуральное a?',answer:'1',placeholder:'a',hint:'65−64.',explanation:'a=1: 65−1=64, 64:8=8.'},visual:'expression',sourceExercise:'№ 535(2)'},
{id:'l69-535-3',kind:'practice',eyebrow:'№ 535(3)',title:'96−a даёт остаток 4 при делении на 9',body:'96 при делении на 9 даёт остаток 6. Нужно уменьшить выражение так, чтобы остаток стал 4.',activity:{id:'l69-p15',type:'input',prompt:'Каково наименьшее натуральное a?',answer:'2',placeholder:'a',hint:'Уменьши остаток 6 до 4.',explanation:'a=2: 94=9·10+4.'},visual:'expression',sourceExercise:'№ 535(3)'},
{id:'l69-535-pattern',kind:'challenge',eyebrow:'№ 535 · закономерность',title:'Решений не одно',body:'Для пункта 3 после a=2 можно уменьшать выражение ещё на целые девятки и сохранять остаток 4, пока число остаётся допустимым.',activity:{id:'l69-p16',type:'input',prompt:'Какое следующее после 2 натуральное a тоже подходит?',answer:'11',placeholder:'a',hint:'Добавь к a один делитель — 9.',explanation:'a=11: 96−11=85=9·9+4.'},visual:'challenge',sourceExercise:'№ 535(3)'},
{id:'l69-541-model',kind:'guided',eyebrow:'№ 541',title:'Календарь как задача на остатки',body:'Точное условие № 541: в одном осеннем месяце суббот и понедельников оказалось больше, чем пятниц. Нужно определить, каким днём недели было 19-е число и какой это был месяц.',visual:'work',sourceExercise:'№ 541'},
{id:'l69-541-logic',kind:'model',eyebrow:'№ 541 · идея',title:'В 31-дневном месяце три дня недели встречаются по пять раз',body:'30 дней — это 4 полные недели и ещё 2 дня; 31 день — 4 недели и ещё 3 дня. Чтобы и суббот, и понедельник встречались чаще пятницы, нужны три добавочных дня подряд: суббота, воскресенье, понедельник. Значит месяц начинается в субботу и содержит 31 день.',visual:'map',sourceExercise:'№ 541'},
{id:'l69-541-month',kind:'practice',eyebrow:'№ 541',title:'Какой осенний месяц подходит?',body:'Из сентября, октября и ноября только один имеет 31 день.',activity:{id:'l69-p17',type:'input',prompt:'Назови месяц.',answer:['октябрь','октября'],placeholder:'месяц',hint:'Сентябрь и ноябрь имеют по 30 дней.',explanation:'Это октябрь.'},visual:'work',sourceExercise:'№ 541'},
{id:'l69-541-weekday',kind:'practice',eyebrow:'№ 541',title:'Какой день недели — 19 октября?',body:'Если 1 октября — суббота, то 8-е и 15-е тоже субботы. От 15-го отсчитай ещё четыре дня.',activity:{id:'l69-p18',type:'input',prompt:'Какой день недели был 19-го?',answer:['среда','в среду'],placeholder:'день недели',hint:'15 — суббота, 16 — воскресенье, 17 — понедельник, 18 — вторник.',explanation:'19-е было в среду.'},visual:'work',sourceExercise:'№ 541'},
{id:'l69-542-model',kind:'guided',eyebrow:'№ 542',title:'Если делимое меньше делителя',body:'Точное условие № 542: a — делимое, b — делитель и a<b. Нужно найти неполное частное и остаток. Ни одной полной группы размера b собрать нельзя.',visual:'division',sourceExercise:'№ 542'},
{id:'l69-542-answer',kind:'quiz',eyebrow:'№ 542',title:'Общий ответ без чисел',body:'Формула должна работать для любых натуральных a<b.',activity:{id:'l69-p19',type:'choice',prompt:'Какие q и r получаются?',options:['q=0, r=a','q=1, r=a','q=0, r=b','q=a, r=0'],answer:'q=0, r=a',hint:'a=b·0+a и a<b.',explanation:'Неполное частное равно 0, остаток равен всему делимому a.'},visual:'verify',sourceExercise:'№ 542'},
{id:'l69-edge',kind:'model',eyebrow:'Граница навыка',title:'Два крайних случая должны стать автоматическими',body:'Если a делится на b нацело, то r=0. Если 0<a<b, то q=0 и r=a. Оба случая подчиняются одной формуле и одному условию r<b.',visual:'map'},
{id:'l69-546-model',kind:'guided',eyebrow:'Повторение · № 546',title:'Прямоугольник: периметр 54 см',body:'Точное условие № 546: периметр прямоугольника 54 см, ширина на 3 см меньше длины. Найди стороны. Это повторение не про остатки, а про сохранение навыка составной арифметической модели.',visual:'work',sourceExercise:'№ 546'},
{id:'l69-546-length',kind:'practice',eyebrow:'№ 546',title:'Найди длину',body:'Полупериметр равен 27 см. Если длина L, то ширина L−3, поэтому L+(L−3)=27.',activity:{id:'l69-p20',type:'input',prompt:'Чему равна длина?',answer:['15','15 см'],placeholder:'см',hint:'2L−3=27.',explanation:'2L=30, L=15 см.'},visual:'equation',sourceExercise:'№ 546'},
{id:'l69-546-width',kind:'practice',eyebrow:'№ 546',title:'Найди ширину и проверь',body:'Ширина на 3 см меньше найденной длины.',activity:{id:'l69-p21',type:'input',prompt:'Чему равна ширина?',answer:['12','12 см'],placeholder:'см',hint:'15−3.',explanation:'Ширина 12 см; проверка: 2·(15+12)=54.'},visual:'verify',sourceExercise:'№ 546'},
{id:'l69-error-lab',kind:'model',eyebrow:'Лаборатория ошибок',title:'Три типичные ошибки после первого знакомства',body:'Ошибка 1: принять неполное частное за окончательный ответ в задаче на вместимость при r>0. Ошибка 2: забыть проверить r<b. Ошибка 3: подбирать a в №535 случайным перебором вместо работы с ближайшими кратными.',visual:'error'},
{id:'l69-transfer',kind:'model',eyebrow:'Домашний перенос',title:'Проверь, что навык переносится на новые данные',body:'Методичка задаёт §19, №529, 534, 536. В №529 положительный остаток снова потребует ещё один ящик; в №534 нужно записать 45 через делитель 7; в №536 — подобрать минимальное натуральное a по условию делимости или заданного остатка.',note:'Контрольные ориентиры для самопроверки: №529 — 9 ящиков; №534 — 45=7·6+3; №536 — a=3 в обоих пунктах.',visual:'map'},
{id:'l69-summary',kind:'summary',eyebrow:'Итог урока 69',title:'Теперь остаток — не хвост вычисления, а часть решения',body:'Ты закрепил деление с остатком на задачах №528, 530, 533, 535, 541, 542, повторил №546 и научился выбирать между q, r и q+1 по смыслу условия. Обязательная практика дальше проверит 20 задач и ровно 50 ответов.',note:'Следующий урок 70 завершит §19 обобщением и систематизацией.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'÷r',map:'q/r',division:'q,r',equation:'a=bq+r',work:'↗',expression:'a?',verify:'✓',error:'!',challenge:'★',final:'69'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='division'?'неполное частное + остаток':kind==='equation'?'восстановление компонентов':kind==='verify'?'равенство + r < b':kind==='work'?'смысл остатка в задаче':kind==='challenge'?'закономерность остатков':'закрепление § 19 · смысл · проверка'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonSixtyNineStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function RemainderDivisionReinforcementPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonSixtyNineStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonSixtyNineStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==69||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonSixtyNineStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonSixtyNineStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player remainder-reinforcement-player" data-lesson-number="69" data-source-reference="Мерзляк § 19 · технологическая карта урока 69 · № 528, 530, 533, 535, 541, 542; повторение № 546" data-source-exercise-range="528,530,533,535,541,542,546"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={['instant-feedback',isCorrect?'good':'bad'].join(' ')} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.hint+' Можно перейти дальше и вернуться к заданию позже.':activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonSixtyNineStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonSixtyNineStages.length-1||!canContinue}>{saved.stageIndex===lessonSixtyNineStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
