import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredSixteenPractice,lessonOneHundredSixteenResponseCount,type Lesson116Field,type Lesson116Practice} from './data/lessonOneHundredSixteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson116Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-116-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const matchField=(value:string,field:Lesson116Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l116-approximation',eyebrow:'Урок 116 · § 32 · 1 из 3',title:'Округление даёт близкое удобное число',body:'Точное значение иногда содержит больше цифр, чем нужно для задачи. Тогда число заменяют близким значением выбранной точности. Такая запись сообщает, что результат приближённый, а не точный.',note:'Сначала всегда назови разряд, до которого округляешь.'},
{id:'l116-decimal-rule',eyebrow:'Правило для десятичных дробей',title:'Сохрани нужный разряд и посмотри на следующий',body:'При округлении десятичной дроби оставляют цифры до нужного разряда включительно. Следующая справа цифра решает, изменится ли последний сохраняемый разряд. Остальные цифры после него отбрасывают.',note:'Для округления до десятых решают сотые, для сотых — тысячные.'},
{id:'l116-zero-four',eyebrow:'Решающая цифра от нуля до четырёх',title:'Последний сохраняемый разряд не меняется',body:'Если первая отбрасываемая цифра равна нулю, единице, двум, трём или четырём, последний сохраняемый разряд оставляют без изменения.',note:'Например, при округлении 7,84 до десятых решающая цифра 4, поэтому получается 7,8.'},
{id:'l116-five-nine',eyebrow:'Решающая цифра от пяти до девяти',title:'Последний сохраняемый разряд увеличивается на один',body:'Если первая отбрасываемая цифра равна пяти, шести, семи, восьми или девяти, последнюю сохраняемую цифру увеличивают на единицу.',note:'Поэтому 12,45 до десятых превращается в 12,5.'},
{id:'l116-carry',eyebrow:'Перенос через разряд',title:'Девятка может превратиться в ноль и увеличить разряд слева',body:'Если увеличивать нужно цифру 9, возникает перенос. При округлении это может изменить целую часть или сразу несколько старших разрядов.',note:'Например, 9,95 до десятых даёт 10,0, а 0,9996 до сотых — 1,00.'},
{id:'l116-natural-rule',eyebrow:'Правило для натуральных чисел',title:'Справа ставь нули',body:'У натурального числа сохраняют цифру выбранного разряда и все цифры слева. По следующей цифре решают, увеличивать ли сохраняемую. Все разряды справа после округления заменяют нулями.',note:'До десятков решают единицы, до сотен — десятки, до тысяч — сотни.'},
{id:'l116-precision',eyebrow:'Точность округления',title:'Одно число может иметь разные приближённые значения',body:'Результат зависит от выбранной точности. Чем более мелкий разряд сохраняем, тем ближе округлённое число к исходному, но тем длиннее его запись.',note:'4,651 до десятых — 4,7, а до сотых — 4,65.'},
{id:'l116-ready',eyebrow:'Перед практикой',title:'Сначала источник, затем закрепление и первая прикидка',body:'Реши точные задания 845(1–2), 847(1–3) и 860(1), затем отработай границу между 4 и 5, перенос через девятку, разные уровни точности и простую прикидку.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredSixteenPractice.map((practice,i)=>({id:`l116-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Округление · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l116-summary',eyebrow:'Итог урока 116',title:'Первое правило § 32 освоено',body:'Ты умеешь округлять десятичные дроби и натуральные числа до заданного разряда, находить решающую цифру, обрабатывать перенос и понимать, зачем округление используется для быстрых прикидок.',note:'Урок 117 продолжит § 32: более крупные разряды, наивысший разряд и новые задачи на округление.',summary:true}];
export const lessonOneHundredSixteenStageCount=stages.length;
export const lessonOneHundredSixteenPracticeTaskCount=lessonOneHundredSixteenPractice.length;
export const lessonOneHundredSixteenPracticeResponseCount=lessonOneHundredSixteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function RoundingFoundationsPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==116||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 116: округление чисел"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Найди сохраняемый разряд, затем проверь первую цифру справа от него.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 116 завершён</b><span>20 задач · 50 ответов · § 32 · 1 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 116"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
