import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredSeventeenPractice,lessonOneHundredSeventeenResponseCount,type Lesson117Field,type Lesson117Practice} from './data/lessonOneHundredSeventeenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson117Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-117-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.');
const matchField=(value:string,field:Lesson117Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l117-units-decimals',eyebrow:'Урок 117 · § 32 · 2 из 3',title:'До единиц решает цифра десятых',body:'Когда десятичную дробь округляют до целого числа, сохраняют целую часть и смотрят на первую цифру после запятой. Если это 0–4, целая часть не меняется; если 5–9, она увеличивается на единицу.',note:'25,54 округляется до 26, а 8,47 — до 8.'},
{id:'l117-thousandths',eyebrow:'Точная работа с дробной частью',title:'До тысячных сохраняем три цифры после запятой',body:'Чтобы округлить до тысячных, оставляют три цифры после запятой. Решение принимает четвёртая цифра. Если она 5–9, цифра тысячных увеличивается на один.',note:'8,55555 до тысячных даёт 8,556.'},
{id:'l117-millions',eyebrow:'Большие натуральные числа',title:'До миллионов решают сотни тысяч',body:'При округлении до миллионов сохраняют разряд миллионов и всё слева от него. Цифра сотен тысяч определяет, увеличивать ли миллионы. Все младшие разряды заменяются нулями.',note:'При округлении 9 821 893 до миллионов получается 10 000 000.'},
{id:'l117-highest-place',eyebrow:'Наивысший разряд',title:'Сначала найди самую левую значащую цифру',body:'Округление до наивысшего разряда означает, что в результате остаётся только одна значащая цифра. Следующая цифра справа решает, увеличить её или оставить.',note:'583 037 до наивысшего разряда превращается в 600 000.'},
{id:'l117-carry-chain',eyebrow:'Цепочка переносов',title:'Одна пятёрка может изменить несколько разрядов',body:'Если последняя сохраняемая цифра равна девяти и её нужно увеличить, возникает перенос. Иногда он проходит через несколько девяток и создаёт новый старший разряд.',note:'999 500 до тысяч округляется до 1 000 000.'},
{id:'l117-precision-control',eyebrow:'Контроль точности',title:'Один и тот же исходник даёт разные результаты',body:'До единиц, десятых, сотых и тысячных одно число округляется по-разному. Перед вычислением всегда проговори нужный разряд и только потом ищи решающую цифру.',note:'48,7564: до единиц 49, до десятых 48,8, до сотых 48,76.'},
{id:'l117-exact-vs-estimate',eyebrow:'Округление и точное решение',title:'Прикидка помогает проверить порядок результата, но не заменяет точный ответ',body:'Округлённые числа удобны для быстрой оценки суммы, разности или произведения. Но если задача требует точного значения, как № 861, сначала строят точное рассуждение, а прикидку используют как проверку здравого смысла.',note:'В № 861 точная масса торта равна 4 кг.'},
{id:'l117-ready',eyebrow:'Перед практикой',title:'Источник → крупные разряды → перенос → прикидка',body:'Сначала реши точные № 845(3–4), № 847(4–5) и № 861. Затем закрепи округление до единиц, тысячных, миллионов, наивысшего разряда, цепочки переносов и простую прикидку.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredSeventeenPractice.map((practice,i)=>({id:`l117-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Округление · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l117-summary',eyebrow:'Итог урока 117',title:'Крупные разряды § 32 освоены',body:'Ты умеешь округлять десятичные дроби до единиц и тысячных, большие натуральные числа до миллионов и наивысшего разряда, проводить перенос через девятки и применять округление для быстрой прикидки.',note:'Урок 118 завершит § 32: итоговые упражнения № 850, № 854, № 856 и № 858.',summary:true}];
export const lessonOneHundredSeventeenStageCount=stages.length;
export const lessonOneHundredSeventeenPracticeTaskCount=lessonOneHundredSeventeenPractice.length;
export const lessonOneHundredSeventeenPracticeResponseCount=lessonOneHundredSeventeenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function RoundingAdvancedPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==117||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 117: округление чисел"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Найди сохраняемый разряд и проверь первую цифру справа от него.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 117 завершён</b><span>20 задач · 50 ответов · § 32 · 2 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 117"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
