import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';import './theoryExperience.css';
import {lessonOneHundredEighteenPractice,lessonOneHundredEighteenResponseCount,type Lesson118Field,type Lesson118Practice} from './data/lessonOneHundredEighteenPractice';
type Stage={id:string;eyebrow:string;title:string;body:string;note?:string;practice?:Lesson118Practice;summary?:boolean};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;attempts:Record<string,number>};
type Jump={lessonNumber?:number;stageIndex?:number};
const KEY='mathnikita-lesson-118-progress-v1';
const norm=(v:string)=>v.normalize('NFKC').trim().toLocaleLowerCase('ru-RU').replace(/\s+/g,'').replace(/,/g,'.').replace(/[–—-]/g,'');
const matchField=(value:string,field:Lesson118Field)=>field.answers.some(answer=>norm(value)===norm(answer));
const concepts:Stage[]=[
{id:'l118-discarded-digits',eyebrow:'Урок 118 · § 32 · 3 из 3',title:'Отброшенные цифры показывают точность округления',body:'Если после округления последней сохранённой цифрой остаются десятые, значит число округляли до десятых. Если остаются сотые или тысячные, название разряда определяется точно так же. Первая отброшенная цифра решает, менять ли последнюю сохранённую.',note:'В числе 5,874 после сохранения десятых первая отброшенная цифра равна 7, поэтому результат 5,9.'},
{id:'l118-reverse-rounding',eyebrow:'Обратная задача',title:'По готовому результату можно восстановить возможные цифры',body:'Если округление не увеличило последнюю сохранённую цифру, решающая цифра могла быть от нуля до четырёх. Если последняя сохранённая цифра увеличилась, решающая цифра должна быть от пяти до девяти.',note:'Чтобы 5,47 звёздочка 4 округлялось до 5,47, вместо звёздочки подходят цифры от нуля до четырёх.'},
{id:'l118-unit-conversion',eyebrow:'Округление величин',title:'Сначала округли в исходных единицах, затем переведи',body:'Когда условие просит сначала округлить метры до тысяч, а потом записать километры, порядок действий важен. Сначала получаем целое количество тысяч метров, затем каждую тысячу заменяем одним километром.',note:'324 711 метров после округления до тысяч дают 325 000 метров, то есть 325 километров.'},
{id:'l118-safe-estimation',eyebrow:'Прикидка с гарантией',title:'Для доказательства выбирай оценку нужного направления',body:'Обычное округление к ближайшему удобно для приблизительного ответа. Но чтобы доказать, что груза слишком много, полезна нижняя оценка: заменить исходные величины меньшими, но уже получить предельную массу. Тогда настоящий груз точно тяжелее оценки.',note:'Сто ящиков тяжелее тридцати килограммов каждый уже дают массу более трёх тонн.'},
{id:'l118-capacity-proof',eyebrow:'Задача № 858',title:'Не обязательно считать точное произведение',body:'В задаче с 102 ящиками по 30,7 килограмма достаточно заметить две вещи: ящиков больше ста, а каждый тяжелее тридцати килограммов. Значит общая масса больше трёх тысяч килограммов, поэтому грузоподъёмности три тонны недостаточно.',note:'Это строгая нижняя оценка, а не просто приблизительное вычисление.'},
{id:'l118-error-direction',eyebrow:'Контроль ошибки',title:'Округление может увеличить или уменьшить число',body:'Если решающая цифра меньше пяти, округлённое число обычно становится не больше исходного. Если решающая цифра не меньше пяти, результат может стать больше. Понимание направления ошибки особенно важно в задачах на деньги, массу и вместимость.',note:'4,46 до десятых превращается в 4,5, поэтому результат немного больше исходного числа.'},
{id:'l118-exact-vs-estimate',eyebrow:'Точное значение и прикидка',title:'Прикидка отвечает на вопрос быстрее, но не всегда заменяет вычисление',body:'Для проверки порядка результата можно округлить числа и выполнить простое действие. Если требуется точный ответ, после прикидки всё равно нужно вычисление. Если же надо только доказать, хватит ли денег или вместимости, грамотной верхней или нижней оценки часто достаточно.',note:'Выбирай оценку так, чтобы она гарантировала именно тот вывод, который нужен в задаче.'},
{id:'l118-ready',eyebrow:'Перед практикой',title:'Источник → обратное округление → единицы → строгая прикидка',body:'Сначала реши точные № 850, № 854, № 856 и № 858. Затем закрепи восстановление цифр, перевод величин после округления, направление ошибки и безопасные оценки сверху и снизу.',note:'20 обязательных задач · 50 проверяемых ответов.'}
];
const practiceStages:Stage[]=lessonOneHundredEighteenPractice.map((practice,i)=>({id:`l118-practice-${String(i+1).padStart(2,'0')}`,eyebrow:practice.source?`Учебник · ${practice.source}`:`Обязательная практика · ${i+1} из 20`,title:practice.source?`Точное задание ${practice.source}`:`Итог § 32 · ${i+1}`,body:practice.prompt,practice}));
const stages:Stage[]=[...concepts,...practiceStages,{id:'l118-summary',eyebrow:'Итог урока 118',title:'§ 32 полностью завершён',body:'Ты умеешь округлять числа по заданному разряду, определять точность по отброшенным цифрам, восстанавливать возможные цифры по результату округления, переводить величины после округления и строить прикидки, которые гарантируют нужный вывод.',note:'Следующий урок 119 начинает § 33: сложение и вычитание десятичных дробей.',summary:true}];
export const lessonOneHundredEighteenStageCount=stages.length;
export const lessonOneHundredEighteenPracticeTaskCount=lessonOneHundredEighteenPractice.length;
export const lessonOneHundredEighteenPracticeResponseCount=lessonOneHundredEighteenResponseCount;
function load():Saved{try{const r=localStorage.getItem(KEY);if(!r)return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}};const p=JSON.parse(r) as Saved;return p?.version===1?p:{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},attempts:{}}}}
export function RoundingSynthesisPlayer(){
 const initial=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(()=>Math.max(0,Math.min(initial.stageIndex,stages.length-1)));const[responses,setResponses]=useState(initial.responses);const[checked,setChecked]=useState(initial.checked);const[attempts,setAttempts]=useState(initial.attempts);const stage=stages[stageIndex];const task=stage.practice;const key=stage.id;const complete=task?task.fields.every(f=>matchField(responses[`${key}:${f.id}`]??'',f)):true;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,checked,attempts} satisfies Saved))},[stageIndex,responses,checked,attempts]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent<Jump>).detail;if(d?.lessonNumber!==118||typeof d.stageIndex!=='number')return;setStageIndex(Math.max(0,Math.min(Math.trunc(d.stageIndex),stages.length-1)))};window.addEventListener('mathnikita-go-to-stage',h);return()=>window.removeEventListener('mathnikita-go-to-stage',h)},[]);
 const check=()=>{if(task){setChecked(p=>({...p,[key]:true}));setAttempts(p=>({...p,[key]:(p[key]??0)+1}))}};const move=(d:number)=>setStageIndex(i=>Math.max(0,Math.min(i+d,stages.length-1)));
 return <section className="lesson-player theory-experience" aria-label="Урок 118: итог округления и прикидок"><article className={`interactive-stage ${stage.summary?'stage-summary':''}`} data-stage-id={stage.id} data-stage-index={stageIndex}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{task?<div className="activity-area"><h3>{task.instruction}</h3><div className="answer-grid">{task.fields.map(f=>{const k=`${key}:${f.id}`;return <label className="inline-answer" key={f.id}><span>{f.label}</span><input value={responses[k]??''} placeholder="Введите ответ" onChange={e=>{setResponses(p=>({...p,[k]:e.target.value}));setChecked(p=>({...p,[key]:false}))}}/></label>})}</div><button className="check-button" type="button" onClick={check}>Проверить</button>{checked[key]?complete?<div className="instant-feedback good" data-explanation={task.explanation}><b>Верно.</b><span>{task.explanation}</span></div>:<div className="instant-feedback bad" data-explanation={task.explanation}><b>Пока есть ошибка.</b><span>{attempts[key]>1?task.hint:'Определи сохраняемый разряд, решающую цифру и проверь направление оценки.'}</span></div>:null}</div>:null}{stage.summary?<div className="summary-card"><b>Урок 118 завершён</b><span>20 задач · 50 ответов · § 32 · 3 из 3</span></div>:null}</article><nav className="lesson-controls" aria-label="Навигация по этапам урока 118"><button type="button" onClick={()=>move(-1)} disabled={stageIndex===0}>← Назад</button><span>Этап {stageIndex+1} из {stages.length}</span><button type="button" onClick={()=>move(1)} disabled={stageIndex===stages.length-1}>Дальше →</button></nav></section>
}
