import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='ruler'|'instrument'|'construction'|'ray'|'points';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};
const KEY='mathnikita-lesson-13-progress-v1';

export const lessonThirteenStages:Stage[]=[
{id:'l13-story',kind:'story',eyebrow:'Новая тема · § 5',title:'Почему штрихи превращают прибор в измерительный',body:'Ровная рейка помогает провести отрезок, но измерять начинает только после появления шкалы: штрихов, чисел и одинаковых промежутков.',note:'Шкала работает лишь тогда, когда одинаковым делениям соответствует одинаковое изменение величины.',sourceTag:'Мерзляк § 5, с. 34',visual:'ruler'},
{id:'l13-scale',kind:'model',eyebrow:'Главное понятие',title:'Цена деления — значение одного промежутка',body:'Чтобы найти цену деления, возьми разность двух подписанных значений и раздели её на число равных промежутков между ними.',note:'Считать нужно промежутки, а не штрихи.',visual:'instrument'},
{id:'l13-diagnostic',kind:'guided',eyebrow:'Разминка',title:'Не перепутай штрихи и промежутки',body:'Между отметками 20 и 50 расположено 6 одинаковых промежутков.',activity:{id:'l13-a1',type:'input',prompt:'Чему равна цена одного деления?',answer:'5',placeholder:'Цена деления',explanation:'50 − 20 = 30, затем 30 : 6 = 5.'}},
{id:'l13-instruments',kind:'model',eyebrow:'Шкалы вокруг нас',title:'Линейка, часы, термометр, весы и спидометр',body:'Форма шкалы может быть прямой или круглой, а единицы — миллиметры, минуты, градусы, граммы или километры в час. Алгоритм чтения остаётся одинаковым.',note:'Всегда называй не только число, но и единицу измерения.',visual:'instrument'},
{id:'l13-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Цена деления спидометра',body:'Между 40 км/ч и 100 км/ч находится 6 одинаковых промежутков.',activity:{id:'l13-p1',type:'input',prompt:'Чему равна цена деления?',answer:'10',placeholder:'км/ч',explanation:'100 − 40 = 60; 60 : 6 = 10 км/ч.'}},
{id:'l13-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Читаем показание',body:'На шкале цена деления равна 10 км/ч. Стрелка стоит на третьем делении после 60.',activity:{id:'l13-p2',type:'input',prompt:'Какое показание у прибора?',answer:'90',placeholder:'км/ч',explanation:'60 + 3 · 10 = 90 км/ч.'}},
{id:'l13-construction',kind:'model',eyebrow:'От прибора к математике',title:'Строим бесконечную шкалу',body:'На луче OX отмечаем начало O и подписываем 0. Затем выбираем точку E, подписываем 1 и многократно откладываем отрезок OE вправо.',note:'Точка O — начало отсчёта, а OE — единичный отрезок.',sourceTag:'Мерзляк § 5, с. 35',visual:'construction'},
{id:'l13-ray',kind:'model',eyebrow:'Координатный луч',title:'Каждой отмеченной точке соответствует число',body:'Если точка K изображает число 5, говорят, что 5 — координата точки K, и записывают K (5).',visual:'ray'},
{id:'l13-coordinate',kind:'guided',eyebrow:'Читаем запись',title:'Что означает A (7)',body:'Буква называет точку, а число в скобках показывает её координату.',activity:{id:'l13-a2',type:'choice',prompt:'Какая запись означает «точка M имеет координату 4»?',options:['M (4)','4 (M)','M = 4 см','луч M4'],answer:'M (4)',explanation:'Координату записывают в скобках после названия точки: M (4).'}},
{id:'l13-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Определяем координату',body:'От начала O до точки A отложено 7 единичных отрезков.',activity:{id:'l13-p3',type:'input',prompt:'Запиши координату точки A.',answer:'7',placeholder:'Координата',explanation:'Каждый единичный отрезок увеличивает координату на 1, поэтому A (7).'}},
{id:'l13-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Движение вправо',body:'Точка C имеет координату 7. От неё вправо отложили 4 единичных отрезка.',activity:{id:'l13-p4',type:'input',prompt:'Какова координата новой точки?',answer:'11',placeholder:'Координата',explanation:'При движении вправо координата увеличивается: 7 + 4 = 11.'}},
{id:'l13-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Движение влево',body:'Точка B имеет координату 12. От неё переместились на 5 единичных отрезков влево.',activity:{id:'l13-p5',type:'input',prompt:'В какой координате оказались?',answer:'7',placeholder:'Координата',explanation:'При движении влево координата уменьшается: 12 − 5 = 7.'}},
{id:'l13-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Алгоритм построения',body:'Собери порядок, который не позволит получить неверный координатный луч.',activity:{id:'l13-p6',type:'order',prompt:'Расставь шаги построения',items:['Провести луч и обозначить начало O','Подписать под O число 0','Выбрать единичный отрезок OE','Откладывать равные отрезки вправо','Подписать координаты точек'],answer:['Провести луч и обозначить начало O','Подписать под O число 0','Выбрать единичный отрезок OE','Откладывать равные отрезки вправо','Подписать координаты точек'],explanation:'Сначала задают луч и начало отсчёта, затем единичный отрезок и только после этого координаты.'}},
{id:'l13-control',kind:'model',eyebrow:'Перед проверкой',title:'Два алгоритма, которые нужно удержать',body:'Для шкалы: разность значений разделить на число промежутков. Для координатного луча: определить начало, единичный отрезок, направление и число шагов.',note:'Размер единичного отрезка на бумаге может быть разным, но координата точки от этого не меняется.',visual:'points'},
{id:'l13-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Цена деления',body:'Без подсказки.',activity:{id:'l13-q1',type:'input',prompt:'Между 0 и 80 восемь равных промежутков. Цена деления равна…',answer:'10',placeholder:'Ответ',explanation:'80 : 8 = 10.'}},
{id:'l13-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Начало отсчёта',body:'Без подсказки.',activity:{id:'l13-q2',type:'choice',prompt:'Какую координату имеет начало координатного луча?',options:['0','1','−1','зависит от длины луча'],answer:'0',explanation:'Начало отсчёта O изображает число 0.'}},
{id:'l13-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Единичный отрезок',body:'Без подсказки.',activity:{id:'l13-q3',type:'choice',prompt:'Что определяет расстояние между соседними целыми координатами на рисунке?',options:['единичный отрезок','длина всего луча','название точки','число штрихов слева'],answer:'единичный отрезок',explanation:'Именно выбранный единичный отрезок откладывают последовательно.'}},
{id:'l13-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Координата после перемещения',body:'Без подсказки.',activity:{id:'l13-q4',type:'input',prompt:'Из точки P (9) сделали 6 шагов вправо. Новая координата?',answer:'15',placeholder:'Ответ',explanation:'9 + 6 = 15.'}},
{id:'l13-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Числа между координатами',body:'Без подсказки.',activity:{id:'l13-q5',type:'input',prompt:'Сколько натуральных чисел расположено строго между 8 и 18?',answer:'9',placeholder:'Количество',explanation:'Это числа 9, 10, 11, 12, 13, 14, 15, 16 и 17 — всего 9.'}},
{id:'l13-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Робот на координатном луче',body:'Робот начинает в точке O (0). За ход он перемещается на 4 единицы вправо или на 3 единицы влево и не может уходить левее нуля.',activity:{id:'l13-c1',type:'input',prompt:'Какое наименьшее число ходов нужно, чтобы попасть в точку с координатой 10?',answer:'6',placeholder:'Количество ходов',explanation:'За 6 ходов: четыре раза вправо и два раза влево, 4 · 4 − 2 · 3 = 10. За меньшее число ходов получить 10 невозможно.'}},
{id:'l13-reflection',kind:'model',eyebrow:'Рефлексия',title:'Что теперь должно получаться автоматически',body:'Находить цену деления, читать показание с единицей, различать начало отсчёта и единичный отрезок, записывать A (a) и мысленно двигаться по координатному лучу.'},
{id:'l13-summary',kind:'summary',eyebrow:'Итог урока',title:'Шкала стала точной картой чисел',body:'Ты научился читать шкалы приборов и строить координатный луч, отмечать точки и определять их координаты.'}
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е').replace(/км\/ч/g,'').replace(/°c|°с/g,'')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonThirteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function ScaleVisual({kind}:{kind:Visual}){
  if(kind==='construction')return <div className="scale-visual"><div className="scale-caption"><b>Как появляется координатный луч</b><span>четыре обязательных шага</span></div><div className="construction-steps"><div><b>1</b>Луч OX</div><div><b>2</b>O соответствует 0</div><div><b>3</b>OE — единичный отрезок</div><div><b>4</b>Равные шаги вправо</div></div></div>;
  if(kind==='instrument')return <div className="scale-visual instrument-panel"><div className="instrument-scale">{[40,50,60,70,80,90,100].map((value,index)=><div className={`tick ${index%3===0?'major':''}`} key={value}><span>{value}</span></div>)}</div><div className="instrument-reading"><span>пример показания</span><b>70</b><small>км/ч</small></div></div>;
  const values=kind==='ruler'?[0,1,2,3,4,5,6,7,8]:[0,1,2,3,4,5,6,7,8];
  return <div className="scale-visual"><div className="scale-caption"><b>{kind==='ruler'?'Шкала линейки':'Координатный луч OX'}</b><span>{kind==='ruler'?'цена деления 1':'OE — единичный отрезок'}</span></div><div className={kind==='ruler'?'ruler-track':'ray-track'}>{values.map(value=><div className={`tick ${value===0||value===1?'major':''} ${kind==='points'&&[2,5,7].includes(value)?'point':''}`} key={value}><span>{value}</span>{kind!=='ruler'&&[0,1,5].includes(value)?<small>{value===0?'O':value===1?'E':'K'}</small>:null}</div>)}</div></div>;
}

export function ScaleCoordinateRayPlayer(){
const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);
const stage=lessonThirteenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;const quiz=['l13-q1','l13-q2','l13-q3','l13-q4','l13-q5'];const practice=['l13-p1','l13-p2','l13-p3','l13-p4','l13-p5','l13-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonThirteenStages.length)*100);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===13&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonThirteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
function setAnswer(value:string){if(!activity)return;setResponses(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function setOrder(value:string[]){if(!activity)return;setOrders(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(p=>({...p,[activity.id]:true}));setResults(p=>({...p,[activity.id]:ok}))}
function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
function render(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>}
return <main className="lesson-player-page coordinate-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 13 из 175 · § 5</span><h1>Шкала. Координатный луч</h1><p>Цена деления, показания приборов, начало отсчёта, единичный отрезок и координаты точек.</p></div><div className="lesson-duration">40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonThirteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<ScaleVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь число промежутков, единичный отрезок и направление движения. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonThirteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
