import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='system'|'intervals'|'bounds'|'errors'|'route'|'proof';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};
const KEY='mathnikita-lesson-15-progress-v1';

export const lessonFifteenStages:Stage[]=[
{id:'l15-mission',kind:'story',eyebrow:'Обобщение · § 5',title:'Финальная проверка координатной карты',body:'На этом уроке недостаточно получить число. Нужно уметь восстановить шкалу, доказать правильность построения и заметить, где нарушено постоянство шага.',note:'У координатного луча один масштаб: равным промежуткам соответствуют равные изменения координаты.',sourceTag:'Мерзляк § 5, технологическая карта урока 15',visual:'system'},
{id:'l15-diagnostic',kind:'guided',eyebrow:'Актуализация знаний',title:'Четыре опоры координатного луча',body:'Выбери утверждение, которое одновременно проверяет начало, направление, масштаб и координаты.',activity:{id:'l15-a1',type:'choice',prompt:'Как лучше всего проверить координатный луч?',options:['Найти начало и 0, проверить равные промежутки, постоянный шаг и координаты точек','Посчитать только подписанные буквы','Измерить общую длину линии в сантиметрах','Убедиться, что стрелка нарисована красиво'],answer:'Найти начало и 0, проверить равные промежутки, постоянный шаг и координаты точек',explanation:'Полная проверка включает начало отсчёта, направление, равные промежутки, постоянный координатный шаг и положение точек.'}},
{id:'l15-system',kind:'model',eyebrow:'Система знаний',title:'Любую задачу раскладываем на четыре вопроса',body:'Где ноль? Каков шаг? Сколько промежутков? Какой координате соответствует нужная отметка?',note:'Сначала установи масштаб, только затем считай координаты.',visual:'system'},
{id:'l15-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Цена деления по двум подписям',body:'Между отметками 24 и 72 расположено восемь равных промежутков.',activity:{id:'l15-p1',type:'input',prompt:'Какому числу соответствует один промежуток?',answer:'6',placeholder:'Шаг',explanation:'72 − 24 = 48; 48 : 8 = 6.'}},
{id:'l15-interval-model',kind:'model',eyebrow:'Числа между границами',title:'Промежутки и внутренние точки — не одно и то же',body:'Между координатами 12 и 18 шесть единичных промежутков, но натуральных чисел строго между ними только пять: 13, 14, 15, 16, 17.',note:'Количество натуральных чисел строго между a и b равно b − a − 1.',visual:'intervals'},
{id:'l15-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Сколько чисел внутри',body:'Границы не включаем.',activity:{id:'l15-p2',type:'input',prompt:'Сколько натуральных чисел расположено строго между 132 и 140?',answer:'7',placeholder:'Количество',explanation:'140 − 132 − 1 = 7. Это числа 133–139.'}},
{id:'l15-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Перечисляем координаты',body:'Нужно назвать все натуральные точки внутри заданного участка.',activity:{id:'l15-p3',type:'input',prompt:'Запиши через запятую натуральные числа строго между 234 и 239.',answer:'235,236,237,238',placeholder:'Например: 2,3,4',explanation:'После 234 и до 239 идут 235, 236, 237 и 238.'}},
{id:'l15-bounds-model',kind:'model',eyebrow:'Двойное условие',title:'Левее, правее и строго между',body:'Фразы «правее 8, но левее 14» означают, что обе границы исключаются. На луче останутся координаты 9, 10, 11, 12, 13.',note:'Слово «строго» и формулировка «между» обычно исключают границы.',visual:'bounds'},
{id:'l15-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Точки по двойному условию',body:'Отметить на луче нужно только натуральные координаты, удовлетворяющие обоим ограничениям.',activity:{id:'l15-p4',type:'input',prompt:'Сколько натуральных чисел больше 5, но меньше 10?',answer:'4',placeholder:'Количество',explanation:'Это числа 6, 7, 8 и 9 — всего 4.'}},
{id:'l15-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Обратное восстановление точки',body:'Шаг шкалы равен 9. Точка B находится на шестой отметке после нуля.',activity:{id:'l15-p5',type:'choice',prompt:'Как записать координату точки B?',options:['B (15)','B (54)','B (63)','B (9)'],answer:'B (54)',explanation:'Шесть равных шагов по 9 единиц дают 6 · 9 = 54.'}},
{id:'l15-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Алгоритм доказательной проверки',body:'После построения нельзя сразу переходить к ответу — рисунок нужно проверить.',activity:{id:'l15-p6',type:'order',prompt:'Расположи действия в правильном порядке',items:['Найти начало отсчёта и число 0','Определить координатный шаг','Посчитать равные промежутки до каждой точки','Сопоставить число шагов с координатой','Исправить найденные несоответствия','Записать окончательный ответ'],answer:['Найти начало отсчёта и число 0','Определить координатный шаг','Посчитать равные промежутки до каждой точки','Сопоставить число шагов с координатой','Исправить найденные несоответствия','Записать окончательный ответ'],explanation:'Проверка идёт от основы шкалы к каждой точке, затем к исправлению и окончательному ответу.'}},
{id:'l15-error-model',kind:'model',eyebrow:'Коррекция знаний',title:'Ошибка может быть спрятана в одной подписи',body:'Если под равными промежутками стоят 0, 12, 24, 36, 50, то первые три шага подтверждают масштаб 12, а последняя подпись его нарушает.',note:'Продолжай закономерность: после 36 должна стоять координата 48.',visual:'errors'},
{id:'l15-error-check',kind:'guided',eyebrow:'Контроль и коррекция',title:'Исправь координатный луч',body:'На равномерной шкале подписаны 0, 7, 14, 22, 28.',activity:{id:'l15-a2',type:'choice',prompt:'Какую подпись нужно заменить?',options:['0 на 1','7 на 8','22 на 21','28 на 35'],answer:'22 на 21',explanation:'Постоянный шаг равен 7, поэтому последовательность должна быть 0, 7, 14, 21, 28.'}},
{id:'l15-control-model',kind:'model',eyebrow:'Перед итоговым контролем',title:'Проверяем ответ обратным действием',body:'Если найден шаг 8 и между точками пять промежутков, разность координат должна быть 8 · 5 = 40. Такая обратная проверка быстро обнаруживает ошибку деления.',note:'Шаг · число промежутков = разность координат.',visual:'proof'},
{id:'l15-quiz1',kind:'quiz',eyebrow:'Итоговый контроль · 1/5',title:'Восстановление масштаба',body:'Работай самостоятельно.',activity:{id:'l15-q1',type:'input',prompt:'Точки A (18) и B (66) разделены шестью равными промежутками. Найди шаг.',answer:'8',placeholder:'Ответ',explanation:'66 − 18 = 48; 48 : 6 = 8.'}},
{id:'l15-quiz2',kind:'quiz',eyebrow:'Итоговый контроль · 2/5',title:'Координата точки',body:'Работай самостоятельно.',activity:{id:'l15-q2',type:'input',prompt:'Шаг равен 12. Точка K стоит на седьмой отметке после нуля. Координата K?',answer:'84',placeholder:'Ответ',explanation:'7 · 12 = 84.'}},
{id:'l15-quiz3',kind:'quiz',eyebrow:'Итоговый контроль · 3/5',title:'Выбор верного построения',body:'Работай самостоятельно.',activity:{id:'l15-q3',type:'choice',prompt:'Под равными промежутками стоят четыре последовательности. Какая может быть шкалой?',options:['0, 5, 10, 15, 20','0, 5, 11, 15, 20','0, 4, 8, 13, 16','0, 6, 12, 18, 25'],answer:'0, 5, 10, 15, 20',explanation:'Только в первой последовательности изменение координаты на каждом шаге постоянно и равно 5.'}},
{id:'l15-quiz4',kind:'quiz',eyebrow:'Итоговый контроль · 4/5',title:'Натуральные числа между точками',body:'Работай самостоятельно.',activity:{id:'l15-q4',type:'input',prompt:'Сколько натуральных чисел расположено строго между 487 и 492?',answer:'4',placeholder:'Ответ',explanation:'492 − 487 − 1 = 4: это 488, 489, 490, 491.'}},
{id:'l15-quiz5',kind:'quiz',eyebrow:'Итоговый контроль · 5/5',title:'Составное перемещение',body:'Работай самостоятельно.',activity:{id:'l15-q5',type:'input',prompt:'Робот стартовал в точке C (36), сделал 4 шага по 5 вправо и 3 шага по 4 влево. Где он оказался?',answer:'44',placeholder:'Ответ',explanation:'36 + 4 · 5 − 3 · 4 = 36 + 20 − 12 = 44.'}},
{id:'l15-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Неизвестная стартовая координата',body:'Робот сделал три шага по 8 единиц вправо, затем два шага по 5 единиц влево и оказался в точке 51.',activity:{id:'l15-c1',type:'input',prompt:'Из какой координаты робот начал движение?',answer:'37',placeholder:'Стартовая координата',explanation:'Общее изменение равно 3 · 8 − 2 · 5 = 14. Значит старт: 51 − 14 = 37.'}},
{id:'l15-transfer',kind:'guided',eyebrow:'Перенос знания',title:'Доказываем невозможность',body:'Иногда задача проверяет не вычисление, а понимание свойства шкалы.',activity:{id:'l15-a3',type:'choice',prompt:'Могут ли точки A (20), B (35), C (50) стоять на трёх соседних отметках равномерной шкалы?',options:['Да, шаг равен 15','Нет, координаты должны начинаться с 0','Нет, между соседними отметками обязана быть разность 1','Да, но только при единичном отрезке 1 см'],answer:'Да, шаг равен 15',explanation:'Разности 35 − 20 и 50 − 35 одинаковы и равны 15, поэтому точки могут стоять на соседних отметках.'}},
{id:'l15-reflection',kind:'model',eyebrow:'Рефлексия',title:'Теперь § 5 собран в единую систему',body:'Ты умеешь читать шкалы, находить цену деления, выбирать масштаб, строить точки, считать координаты между границами и проверять построение обратным действием.',visual:'route'},
{id:'l15-summary',kind:'summary',eyebrow:'Итог § 5',title:'Шкала и координатный луч освоены',body:'Результат показывает, готов ли ты переходить к сравнению натуральных чисел. При необходимости вернись к ошибочным этапам и пройди их ещё раз.',visual:'proof'},
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е').replace(/[;]+/g,',')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFifteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function SummaryVisual({kind}:{kind:Visual}){
  if(kind==='system')return <div className="scale-visual"><div className="scale-caption"><b>Четыре вопроса</b><span>ноль · шаг · промежутки · координата</span></div><div className="construction-steps"><div><b>0</b>Начало</div><div><b>↔</b>Шаг</div><div><b>▥</b>Промежутки</div><div><b>A</b>Координата</div></div></div>;
  if(kind==='intervals')return <div className="scale-visual"><div className="scale-caption"><b>Строго между 12 и 18</b><span>границы не считаем</span></div><div className="ray-track">{[12,13,14,15,16,17,18].map(value=><div className={`tick ${value===12||value===18?'major':'point'}`} key={value}><span>{value}</span></div>)}</div></div>;
  if(kind==='bounds')return <div className="scale-visual"><div className="scale-caption"><b>8 &lt; x &lt; 14</b><span>подходят 9, 10, 11, 12, 13</span></div><div className="ray-track">{[8,9,10,11,12,13,14].map(value=><div className={`tick ${value>8&&value<14?'point':'major'}`} key={value}><span>{value}</span></div>)}</div></div>;
  if(kind==='errors')return <div className="scale-visual"><div className="scale-caption"><b>Найди нарушение</b><span>шаг должен быть постоянным</span></div><div className="ray-track">{[0,12,24,36,50].map((value,index)=><div className={`tick ${index===4?'point':'major'}`} key={value}><span>{value}</span></div>)}</div></div>;
  if(kind==='proof')return <div className="scale-visual"><div className="scale-caption"><b>Обратная проверка</b><span>шаг · промежутки = разность координат</span></div><div className="construction-steps"><div><b>8</b>шаг</div><div><b>×</b></div><div><b>5</b>промежутков</div><div><b>= 40</b>разность</div></div></div>;
  return <div className="scale-visual"><div className="scale-caption"><b>Маршрут решения</b><span>условие → модель → вычисление → проверка</span></div><div className="construction-steps"><div><b>1</b>Прочитать</div><div><b>2</b>Построить</div><div><b>3</b>Вычислить</div><div><b>4</b>Проверить</div></div></div>;
}

export function ScaleCoordinateRaySummaryPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);
  const stage=lessonFifteenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;const quiz=['l15-q1','l15-q2','l15-q3','l15-q4','l15-q5'];const practice=['l15-p1','l15-p2','l15-p3','l15-p4','l15-p5','l15-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonFifteenStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
  useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===15&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonFifteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
  function render(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>}
  return <main className="lesson-player-page coordinate-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 15 из 175 · § 5</span><h1>Шкала. Координатный луч — обобщение</h1><p>Восстановление масштаба, точки между границами, доказательная проверка и итоговый контроль темы.</p></div><div className="lesson-duration">42 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonFifteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<SummaryVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь масштаб, число промежутков и включены ли границы. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Итоговый контроль</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус § 5</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonFifteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
