import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='route'|'bounds'|'source-scale'|'unit-choice'|'errors'|'incomplete';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};
const KEY='mathnikita-lesson-14-progress-v2';
const LEGACY_KEY='mathnikita-lesson-14-progress-v1';

export const lessonFourteenStages:Stage[]=[
{id:'l14-mission',kind:'story',eyebrow:'Закрепление · § 5',title:'Координатный луч: строим и проверяем точно',body:'Сегодня закрепляем задачи § 5: читаем положение натуральных чисел, выбираем физическую длину единичного отрезка, строим точки и проверяем равномерность шкалы.',note:'Единичный отрезок всегда соответствует изменению координаты на 1. Его физическая длина на бумаге может быть выбрана удобной.',sourceTag:'Мерзляк § 5 · урок закрепления',visual:'route'},
{id:'l14-recall',kind:'guided',eyebrow:'Быстрая диагностика',title:'Что обязательно есть у координатного луча',body:'Одной стрелки или нескольких подписанных чисел недостаточно.',activity:{id:'l14-a1',type:'choice',prompt:'Какой набор описывает координатный луч полностью?',options:['Начало O с числом 0, направление и единичный отрезок','Только стрелка и несколько чисел','Две любые точки и прямая','Линейка любой длины'],answer:'Начало O с числом 0, направление и единичный отрезок',explanation:'Координатный луч задают началом отсчёта O(0), направлением и выбранным единичным отрезком.'}},
{id:'l14-bounds',kind:'model',eyebrow:'Мерзляк · №120–124',title:'Левее, правее и между — это язык порядка чисел',body:'На координатном луче точка с меньшей натуральной координатой расположена левее. В строгом промежутке сами границы не учитываются.',note:'Между 8 и 18 находятся натуральные координаты 9–17.',sourceTag:'Мерзляк § 5, №120–124',visual:'bounds'},
{id:'l14-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'№120 · числа левее границы',body:'Рассматриваем натуральные числа на координатном луче.',sourceTag:'Мерзляк § 5, №120',activity:{id:'l14-p1',type:'input',prompt:'Сколько натуральных чисел расположено левее числа 12?',answer:'11',placeholder:'Количество',explanation:'Это числа 1, 2, …, 11 — всего 11. Число 0 не является натуральным в используемой здесь нумерации учебника.'}},
{id:'l14-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'№121 · строгие границы',body:'Нужно отметить все натуральные координаты, которые больше 3 и меньше 7.',sourceTag:'Мерзляк § 5, №121',activity:{id:'l14-p2',type:'input',prompt:'Запиши эти числа по возрастанию.',answer:'4,5,6',placeholder:'Например: 4, 5, 6',explanation:'Строгие границы исключают 3 и 7, поэтому остаются 4, 5 и 6.'}},
{id:'l14-source-scale',kind:'model',eyebrow:'Мерзляк · №125',title:'Крупное деление не равно единичному отрезку',body:'Отрезок длиной 8 см соответствует шкале от 0 до 16 и разделён на четыре равные большие части. Каждая большая часть соответствует 4 координатным единицам, но один единичный отрезок имеет длину только 8 см : 16 = 0,5 см.',note:'80 мм : 16 = 5 мм — физическая длина одного единичного отрезка.',sourceTag:'Мерзляк § 5, №125',visual:'source-scale'},
{id:'l14-guided',kind:'guided',eyebrow:'Решаем №125',title:'Подпиши крупные штрихи',body:'Шкала от 0 до 16 разбита на четыре одинаковые большие части.',activity:{id:'l14-a2',type:'input',prompt:'Сколько координатных единиц приходится на одну большую часть?',answer:'4',placeholder:'Координатных единиц',explanation:'16 : 4 = 4. Это крупный интервал шкалы из четырёх единичных отрезков, а не один единичный отрезок.'}},
{id:'l14-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'№123 · сколько чисел между границами',body:'Нужно посчитать натуральные координаты строго между 132 и 140.',sourceTag:'Мерзляк § 5, №123',activity:{id:'l14-p3',type:'input',prompt:'Сколько натуральных чисел находится между 132 и 140?',answer:'7',placeholder:'Количество',explanation:'133, 134, 135, 136, 137, 138, 139 — всего 7. То же даёт 140 − 132 − 1 = 7.'}},
{id:'l14-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'№124 · перечисли координаты',body:'Запиши натуральные числа строго между 234 и 239.',sourceTag:'Мерзляк § 5, №124',activity:{id:'l14-p4',type:'input',prompt:'Какие числа нужно отметить?',answer:'235,236,237,238',placeholder:'Числа по возрастанию',explanation:'После 234 идут 235, 236, 237, 238, а 239 — правая граница и не включается.'}},
{id:'l14-unit-choice',kind:'model',eyebrow:'Построение · №118–119',title:'Выбираем длину единичного отрезка, а не значение координатного шага',body:'Чтобы построить точки 5, 6, 7 и 10, можно выбрать единичный отрезок длиной 5 мм, 1 см или другой удобной длины. Во всех случаях координата 10 остаётся числом 10.',note:'Меняется физический размер рисунка; математическая единица по-прежнему переводит координату на 1.',sourceTag:'Мерзляк § 5, №118–119',visual:'unit-choice'},
{id:'l14-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Удобный физический масштаб',body:'Нужно уместить координаты от 0 до 10 ровно в полосу длиной 5 см.',visual:'unit-choice',activity:{id:'l14-p5',type:'choice',prompt:'Какую физическую длину единичного отрезка нужно выбрать?',options:['5 мм','1 см','2 см','5 см'],answer:'5 мм',explanation:'5 см = 50 мм; 50 : 10 = 5 мм на один единичный отрезок.'}},
{id:'l14-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'План точного построения',body:'Нужно построить координатный луч и отметить точки 5, 6, 7 и 10.',activity:{id:'l14-p6',type:'order',prompt:'Расставь действия в правильном порядке',items:['Отметить точки 5, 6, 7 и 10','Отложить от O выбранный отрезок и обозначить E(1)','Провести луч и обозначить O(0)','Повторять равные единичные отрезки вправо','Выбрать удобную физическую длину единичного отрезка','Проверить число единичных отрезков до каждой точки'],answer:['Провести луч и обозначить O(0)','Выбрать удобную физическую длину единичного отрезка','Отложить от O выбранный отрезок и обозначить E(1)','Повторять равные единичные отрезки вправо','Отметить точки 5, 6, 7 и 10','Проверить число единичных отрезков до каждой точки'],explanation:'Сначала задают луч и O(0), затем выбирают физическую длину единичного отрезка, откладывают её до E(1), продолжают равные единичные отрезки и только потом отмечают нужные координаты.'}},
{id:'l14-error-lab',kind:'model',eyebrow:'Лаборатория ошибок',title:'Равные крупные интервалы требуют постоянного координатного прироста',body:'Если одинаковые большие интервалы подписаны 0, 8, 16, 25, последний прирост стал +9 вместо +8.',note:'При равномерной шкале одинаковым графическим интервалам соответствуют одинаковые изменения координаты.',visual:'errors'},
{id:'l14-error-check',kind:'guided',eyebrow:'Найди нарушение',title:'Проверяем готовую шкалу',body:'Под равными крупными интервалами стоят числа 0, 8, 16, 25.',activity:{id:'l14-a3',type:'choice',prompt:'В чём ошибка?',options:['Последняя подпись должна быть 24, а не 25','Нельзя подписывать число 0','Координаты должны уменьшаться вправо','Любой крупный интервал обязан означать ровно 1'],answer:'Последняя подпись должна быть 24, а не 25',explanation:'Изменения 0→8 и 8→16 равны 8, поэтому следующий равный крупный интервал должен привести к 24.'}},
{id:'l14-control',kind:'model',eyebrow:'Перед самостоятельной работой',title:'Три проверки, которые нельзя смешивать',body:'1) координата считает единичные отрезки; 2) физическая длина единичного отрезка задаёт размер рисунка; 3) крупные подписанные интервалы могут объединять несколько единичных отрезков.',note:'Если A находится через n единичных отрезков от O, то координата A равна n.',visual:'route'},
{id:'l14-quiz1',kind:'quiz',eyebrow:'Самостоятельная проверка · 1/5',title:'Единичный отрезок — это +1',body:'Не возвращайся к старой ошибке «шаг 7».',activity:{id:'l14-q1',type:'input',prompt:'Точка A находится через 9 единичных отрезков от O. Какова координата A?',answer:'9',placeholder:'Координата',explanation:'Один единичный отрезок изменяет координату на 1, поэтому девять единичных отрезков дают A(9).'}},
{id:'l14-quiz2',kind:'quiz',eyebrow:'Самостоятельная проверка · 2/5',title:'№125 · крупные штрихи',body:'Шкала 0…16 разделена на четыре равные большие части.',activity:{id:'l14-q2',type:'input',prompt:'Какая подпись стоит на третьем внутреннем крупном штрихе?',answer:'12',placeholder:'Ответ',explanation:'Крупные подписи идут 0, 4, 8, 12, 16. Третий внутренний штрих — 12.'}},
{id:'l14-quiz3',kind:'quiz',eyebrow:'Самостоятельная проверка · 3/5',title:'Координата и размер рисунка',body:'Единичные отрезки на двух рисунках имеют разную физическую длину.',activity:{id:'l14-q3',type:'choice',prompt:'На обоих рисунках от O до M отложено ровно 5 выбранных единичных отрезков. Что верно?',options:['Обе записи M (5) верны','Верна только шкала с отрезком 1 см','Больший отрезок даёт большую координату','Координата зависит от ширины экрана'],answer:'Обе записи M (5) верны',explanation:'Координата равна числу единичных отрезков. Их физическая длина влияет только на размер рисунка.'}},
{id:'l14-quiz4',kind:'quiz',eyebrow:'Самостоятельная проверка · 4/5',title:'Перемещение по единичным отрезкам',body:'Без скрытого масштаба.',activity:{id:'l14-q4',type:'input',prompt:'Из P (32) прошли 3 единичных отрезка влево, затем 5 вправо. Где оказались?',answer:'34',placeholder:'Координата',explanation:'32 − 3 + 5 = 34.'}},
{id:'l14-quiz5',kind:'quiz',eyebrow:'Самостоятельная проверка · 5/5',title:'Строго между границами',body:'Без подсказки.',activity:{id:'l14-q5',type:'input',prompt:'Сколько натуральных координат расположено строго между 18 и 31?',answer:'12',placeholder:'Количество',explanation:'31 − 18 − 1 = 12.'}},
{id:'l14-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Третья точка на неполной шкале',body:'A (18) и B (54) разделены шестью одинаковыми крупными интервалами. Точка C находится на четыре таких интервала правее A.',visual:'incomplete',activity:{id:'l14-c1',type:'input',prompt:'Какова координата точки C?',answer:'42',placeholder:'Координата',explanation:'Изменение за крупный интервал: (54 − 18) : 6 = 6. Тогда C: 18 + 4 · 6 = 42.'}},
{id:'l14-reflection',kind:'model',eyebrow:'Рефлексия',title:'Что теперь должно быть разделено в голове',body:'Единичный отрезок означает +1 координату. Его физическую длину можно выбирать. Крупный подписанный интервал может содержать несколько единичных отрезков.',visual:'unit-choice'},
{id:'l14-summary',kind:'summary',eyebrow:'Итог основной части',title:'Основная часть § 5 закреплена',body:'Ты разобрал исходные задачи на положение натуральных чисел, построение координатного луча, физический масштаб и проверку равномерной шкалы.'}
];

const empty:Saved={version:2,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0,.;:]+/g,'').replace(/ё/g,'е').replace(/мм|см/g,'')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFourteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function PracticeVisual({kind}:{kind:Visual}){
  if(kind==='bounds')return <div className="scale-visual l14-bounds-model"><div className="scale-caption"><b>Строго между 8 и 18</b><span>границы не входят</span></div><div className="l14-number-row">{Array.from({length:11},(_,index)=>8+index).map(value=><span className={value===8||value===18?'boundary':'inside'} key={value}>{value}</span>)}</div><small>Внутри: 9, 10, 11, 12, 13, 14, 15, 16, 17</small></div>;
  if(kind==='source-scale')return <div className="scale-visual l14-source-scale"><div className="scale-caption"><b>№125 · 8 см ↔ координаты 0…16</b><span>4 большие части, но 16 единичных отрезков</span></div><div className="l14-major-scale">{[0,4,8,12,16].map(value=><span key={value}>{value}</span>)}</div><div className="l14-scale-facts"><b>Одна большая часть = 4 координатные единицы</b><b>Один единичный отрезок = 5 мм</b></div></div>;
  if(kind==='unit-choice')return <div className="scale-visual l14-unit-model"><div className="scale-caption"><b>Одна координата — разные размеры рисунка</b><span>A(5) остаётся A(5)</span></div><div className="l14-unit-cards"><div><b>OE = 5 мм</b><span>до A(5): 25 мм</span></div><div><b>OE = 2 см</b><span>до A(5): 10 см</span></div><div><b>Координата</b><span>в обоих случаях 5</span></div></div></div>;
  if(kind==='errors')return <div className="scale-visual l14-error-model"><div className="scale-caption"><b>Проверка постоянного прироста</b><span>равные крупные интервалы</span></div><div className="construction-steps"><div><b>0 → 8</b>+8</div><div><b>8 → 16</b>+8</div><div><b>16 → 25</b>+9 ✕</div><div><b>Верно</b>16 → 24</div></div></div>;
  if(kind==='incomplete')return <div className="scale-visual l14-incomplete-model"><div className="scale-caption"><b>A(18) → B(54)</b><span>6 одинаковых крупных интервалов</span></div><div className="l14-number-row">{[18,24,30,36,42,48,54].map(value=><span className={value===42?'target':''} key={value}>{value}{value===18?' A':value===42?' C':value===54?' B':''}</span>)}</div><small>Изменение координаты за крупный интервал = 6; C — четвёртый интервал после A.</small></div>;
  return <div className="scale-visual l14-route-model"><div className="scale-caption"><b>Маршрут проверки</b><span>термины не смешиваем</span></div><div className="construction-steps"><div><b>1</b>O и 0</div><div><b>2</b>Единичный OE = +1</div><div><b>3</b>Физическая длина OE</div><div><b>4</b>Координата = число единичных отрезков</div></div></div>;
}

export function ScaleCoordinateRayPracticePlayer(){
const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
const stage=lessonFourteenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;const quiz=['l14-q1','l14-q2','l14-q3','l14-q4','l14-q5'];const practice=['l14-p1','l14-p2','l14-p3','l14-p4','l14-p5','l14-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const coreComplete=quizScore===5&&practiceScore===6;const progress=Math.round(((stageIndex+1)/lessonFourteenStages.length)*100);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===14&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonFourteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
function setAnswer(value:string){if(!activity)return;setResponses(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function setOrder(value:string[]){if(!activity)return;setOrders(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(p=>({...p,[activity.id]:true}));setResults(p=>({...p,[activity.id]:ok}))}
function reset(){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:14}}))}
function render(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>}
return <main className="lesson-player-page coordinate-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 14 из 175 · § 5</span><h1>Шкала. Координатный луч</h1><p>Закрепление по Мерзляку: положение натуральных чисел, единичный отрезок, физический масштаб и проверка шкал.</p></div><div className="lesson-duration">план · 40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonFourteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<PracticeVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь границы, единичный отрезок и смысл крупного интервала. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Самостоятельная проверка</span><b>{quizScore}/5</b><small>{quizScore===5?'всё верно':'нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{coreComplete?'Основная часть ✓':'Повторить'}</b><small>{coreComplete?'дальше — обязательная практика':'исправь ошибки основной части'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonFourteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
