import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;placeholder?:string};
type Visual='route'|'scale126'|'read127'|'read128'|'plot'|'distance'|'arrows'|'proof';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:2;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
const KEY='mathnikita-lesson-15-progress-v2';
const LEGACY_KEY='mathnikita-lesson-15-progress-v1';

export const lessonFifteenStages:Stage[]=[
{id:'l15-mission',kind:'story',eyebrow:'Обобщение · § 5',title:'Финальный маршрут по шкале и координатному лучу',body:'Теперь § 5 нужно собрать целиком: построить шкалу по физическим размерам, прочитать координаты, поставить точки, найти точки на заданном расстоянии и восстановить начало или конец движения по стрелке.',note:'Не смешивай три вещи: единичный отрезок всегда даёт +1 координату; крупное деление может содержать несколько единиц; физическая длина задаёт только размер рисунка.',sourceTag:'Мерзляк § 5 · итог по №126–134',visual:'route'},
{id:'l15-diagnostic',kind:'guided',eyebrow:'Диагностика',title:'Что такое единичный отрезок',body:'Это главный термин, который должен остаться после § 5 без двусмысленности.',activity:{id:'l15-a1',type:'choice',prompt:'Какое утверждение верно для координатного луча?',options:['Единичный отрезок соответствует изменению координаты на 1','Единичный отрезок всегда равен 1 см','Единичный отрезок равен разности любых соседних подписей','Единичный отрезок зависит от ширины экрана'],answer:'Единичный отрезок соответствует изменению координаты на 1',explanation:'На координатном луче один единичный отрезок изменяет координату на 1. Его физическая длина на бумаге может быть любой удобной.'}},
{id:'l15-task126',kind:'model',eyebrow:'Мерзляк · №126',title:'Из 9 см строим шкалу 0…18',body:'Отрезок длиной 9 см подписан 0 и 18 и разделён на 6 равных больших частей. Поэтому один большой интервал означает 3 координатные единицы, а один настоящий единичный отрезок имеет длину 9 см : 18 = 0,5 см.',note:'Большие штрихи: 0, 3, 6, 9, 12, 15, 18. Между ними можно отмечать и координаты 4, 7, 8, 10, 11, 16, 17.',sourceTag:'Мерзляк § 5, №126',visual:'scale126'},
{id:'l15-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'№126 · подпиши большие штрихи',body:'Крайние подписи 0 и 18, больших равных частей шесть.',sourceTag:'Мерзляк § 5, №126',activity:{id:'l15-p1',type:'input',prompt:'Запиши внутренние большие подписи по возрастанию.',answer:'3,6,9,12,15',placeholder:'Например: 3, 6, ...',explanation:'18 : 6 = 3, поэтому подписи идут 0, 3, 6, 9, 12, 15, 18.'}},
{id:'l15-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'№126 · физическая длина единицы',body:'Вся шкала 0…18 имеет длину 9 см.',activity:{id:'l15-p2',type:'input',prompt:'Какова физическая длина одного единичного отрезка в миллиметрах?',answer:'5 мм',placeholder:'Например: 5 мм',explanation:'9 см = 90 мм; 90 : 18 = 5 мм на один единичный отрезок.'}},
{id:'l15-task127',kind:'model',eyebrow:'Мерзляк · №127',title:'Читаем координаты на готовом рисунке',body:'На рисунке 57 нужно определить координаты шести точек. Итоговая проверка должна читать и крупные, и промежуточные отметки.',note:'Для рисунка 57: A(10), C(50), B(90), F(125), D(140), E(190).',sourceTag:'Мерзляк § 5, №127',visual:'read127'},
{id:'l15-guided',kind:'guided',eyebrow:'Разбор №127',title:'Не меняй порядок букв на порядок координат',body:'Записываем ответы именно в порядке A, B, C, D, E, F.',activity:{id:'l15-a2',type:'input',prompt:'Запиши координаты A, B, C, D, E, F в этом порядке.',answer:'10,90,50,140,190,125',placeholder:'A,B,C,D,E,F',explanation:'A(10), B(90), C(50), D(140), E(190), F(125).'}},
{id:'l15-task128',kind:'model',eyebrow:'Мерзляк · №128',title:'Цена малого деления важнее крупных подписей',body:'На рисунке 58 встречается промежуточная координата S(155), поэтому нельзя округлять точки до ближайшего десятка или считать только крупные подписи.',note:'M(10), P(70), N(80), T(130), S(155), K(180).',sourceTag:'Мерзляк § 5, №128',visual:'read128'},
{id:'l15-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'№128 · полный набор координат',body:'Сохрани порядок букв из вопроса.',activity:{id:'l15-p3',type:'input',prompt:'Запиши M, N, P, T, K, S в этом порядке.',answer:'10,80,70,130,180,155',placeholder:'M,N,P,T,K,S',explanation:'M(10), N(80), P(70), T(130), K(180), S(155).'}},
{id:'l15-plot',kind:'model',eyebrow:'Мерзляк · №129–130',title:'Теперь не читаем — ставим точки сами',body:'В №129 нужно отметить B(12), C(2), D(8). В №130 — E(27), F(6), K(15), P(21); на рисунке 60 одна клетка соответствует 3 координатным единицам.',note:'Координата — это число у точки. Число клеток или физическая длина — только способ найти место на рисунке.',sourceTag:'Мерзляк § 5, №129–130',visual:'plot'},
{id:'l15-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'№130 · поставь четыре точки',body:'Запиши координаты в порядке E, F, K, P.',activity:{id:'l15-p4',type:'input',prompt:'Какие координаты нужно поставить?',answer:'27,6,15,21',placeholder:'E,F,K,P',explanation:'По условию: E(27), F(6), K(15), P(21). На рисунке это 9, 2, 5 и 7 клеток от начала.'}},
{id:'l15-distance',kind:'model',eyebrow:'Мерзляк · №131–132',title:'Расстояние от точки может дать одно или два решения',body:'Для точки x и расстояния d проверяем x − d и x + d. Если x − d отрицательно, левая точка на координатном луче не существует.',note:'B(5), расстояние 6 → только 11. B(5), расстояние 3 → 2 и 8. A(7), расстояние 7 → 0 и 14.',sourceTag:'Мерзляк § 5, №131–132',visual:'distance'},
{id:'l15-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'№132 · две стороны от A(7)',body:'Ищем точки на расстоянии четырёх единичных отрезков.',activity:{id:'l15-p5',type:'input',prompt:'Запиши обе координаты по возрастанию.',answer:'3,11',placeholder:'Например: 3, 11',explanation:'7 − 4 = 3 и 7 + 4 = 11.'}},
{id:'l15-arrows',kind:'model',eyebrow:'Мерзляк · №133–134',title:'Стрелка: прямое и обратное восстановление',body:'№133 просит найти точку, в которую указывает стрелка: 46 + 9 = 55 и 293 − 25 = 268. №134 просит найти точку, где стрелка начинается: 82 − 8 = 74 и второй старт равен 424.',note:'Сначала прочитай направление. Если ищешь начало движения, выполняй действие, обратное показанному перемещению.',sourceTag:'Мерзляк § 5, №133–134',visual:'arrows'},
{id:'l15-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'№133 · куда указывает стрелка',body:'В первом случае движение начинается с 46 и идёт на 9 вправо. Во втором — от 293 на 25 влево.',activity:{id:'l15-p6',type:'input',prompt:'Запиши две конечные координаты в порядке рисунка.',answer:'55,268',placeholder:'Два числа',explanation:'46 + 9 = 55; 293 − 25 = 268.'}},
{id:'l15-control',kind:'model',eyebrow:'Перед итоговым контролем',title:'Пять разных типов задач § 5',body:'1) построить шкалу; 2) прочитать координаты; 3) поставить точки; 4) найти точки на расстоянии; 5) восстановить координату по стрелке.',note:'Если в решении появляется «шаг 6» или «шаг 12», спроси себя: это координатное изменение крупного деления, число клеток или настоящий единичный отрезок?',visual:'route'},
{id:'l15-quiz1',kind:'quiz',eyebrow:'Итоговый контроль · 1/5',title:'№126 · крупное деление',body:'Шкала 0…18 разбита на 6 равных больших частей.',activity:{id:'l15-q1',type:'input',prompt:'На сколько координатных единиц меняется подпись от одного большого штриха к следующему?',answer:'3',placeholder:'Ответ',explanation:'18 : 6 = 3. Но это большой интервал из трёх единичных отрезков.'}},
{id:'l15-quiz2',kind:'quiz',eyebrow:'Итоговый контроль · 2/5',title:'№127 · промежуточная точка',body:'Работай без подсказки.',activity:{id:'l15-q2',type:'input',prompt:'Какова координата точки F на рисунке 57?',answer:'125',placeholder:'Ответ',explanation:'По рисунку 57 точка F имеет координату 125.'}},
{id:'l15-quiz3',kind:'quiz',eyebrow:'Итоговый контроль · 3/5',title:'№131 · когда слева места уже нет',body:'Точка B имеет координату 5.',activity:{id:'l15-q3',type:'input',prompt:'Какая точка удалена от B(5) на 6 единичных отрезков?',answer:'11',placeholder:'Координата',explanation:'5 + 6 = 11, а 5 − 6 = −1 недопустимо на данном координатном луче.'}},
{id:'l15-quiz4',kind:'quiz',eyebrow:'Итоговый контроль · 4/5',title:'№132 · расстояние до нуля',body:'Точка A имеет координату 7.',activity:{id:'l15-q4',type:'input',prompt:'Какие две точки удалены от A(7) на 7 единичных отрезков?',answer:'0,14',placeholder:'Две координаты',explanation:'7 − 7 = 0 и 7 + 7 = 14.'}},
{id:'l15-quiz5',kind:'quiz',eyebrow:'Итоговый контроль · 5/5',title:'№134 · восстанови начало стрелки',body:'Стрелка закончилась в координате 82 после движения на 8 вправо.',activity:{id:'l15-q5',type:'input',prompt:'Где стрелка начиналась?',answer:'74',placeholder:'Стартовая координата',explanation:'Начало = 82 − 8 = 74.'}},
{id:'l15-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'№126 · координата превращается в физическое расстояние',body:'На шкале длиной 9 см от 0 до 18 нужно отметить точку с координатой 17.',visual:'scale126',activity:{id:'l15-c1',type:'input',prompt:'На каком физическом расстоянии от нуля находится координата 17?',answer:'8,5 см',placeholder:'Расстояние',explanation:'Один единичный отрезок равен 0,5 см. Поэтому 17 · 0,5 = 8,5 см.'}},
{id:'l15-transfer',kind:'guided',eyebrow:'Перенос знания',title:'Финальная защита от терминологической ошибки',body:'На шкале №126 соседние большие подписи — 0 и 3.',activity:{id:'l15-a3',type:'choice',prompt:'Что верно?',options:['Крупное деление 0→3 содержит три единичных отрезка','Единичный отрезок равен 3 координатам','Координатный луч не имеет единичного отрезка','Физическая длина единицы обязана быть 3 см'],answer:'Крупное деление 0→3 содержит три единичных отрезка',explanation:'Между координатами 0 и 3 три математические единицы. На рисунке они вместе образуют один крупный подписанный интервал.'}},
{id:'l15-reflection',kind:'model',eyebrow:'Рефлексия',title:'§ 5 теперь собран в одну систему',body:'Ты различаешь единичный отрезок и крупное деление, читаешь и строишь координатные лучи, находишь точки по расстоянию и решаешь задачи со стрелками в обе стороны.',visual:'proof'},
{id:'l15-summary',kind:'summary',eyebrow:'Итог основной части',title:'Основная часть § 5 завершена',body:'Дальше обязательная практика и финальное объяснение своими словами. Только после них урок считается полностью завершённым.'}
];

const empty:Saved={version:2,stageIndex:0,responses:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0,.;:]+/g,'').replace(/ё/g,'е').replace(/мм|см/g,'')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===2?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFifteenStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function PracticeVisual({kind}:{kind:Visual}){
  if(kind==='scale126')return <div className="scale-visual l15-scale126-model"><div className="scale-caption"><b>№126 · 9 см ↔ координаты 0…18</b><span>6 больших частей · 18 единичных отрезков</span></div><div className="l15-major-scale">{[0,3,6,9,12,15,18].map(value=><span key={value}>{value}</span>)}</div><div className="l15-scale-facts"><b>Большой интервал = +3 координаты</b><b>Единичный отрезок = 5 мм</b><b>Координата 17 = 8,5 см от 0</b></div></div>;
  if(kind==='read127')return <div className="scale-visual l15-read-model"><div className="scale-caption"><b>№127 · рисунок 57</b><span>читаем промежуточные отметки</span></div><div className="l15-point-grid">{[['A',10],['C',50],['B',90],['F',125],['D',140],['E',190]].map(([name,value])=><div key={String(name)}><b>{String(name)}</b><span>{String(value)}</span></div>)}</div></div>;
  if(kind==='read128')return <div className="scale-visual l15-read-model"><div className="scale-caption"><b>№128 · рисунок 58</b><span>S(155) проверяет цену малого деления</span></div><div className="l15-point-grid">{[['M',10],['P',70],['N',80],['T',130],['S',155],['K',180]].map(([name,value])=><div className={name==='S'?'focus':''} key={String(name)}><b>{String(name)}</b><span>{String(value)}</span></div>)}</div></div>;
  if(kind==='plot')return <div className="scale-visual l15-plot-model"><div className="scale-caption"><b>№129–130 · ставим точки</b><span>координата ≠ число клеток</span></div><div className="l15-plot-rows"><div><b>№129</b><span>C(2) · D(8) · B(12)</span></div><div><b>№130</b><span>F(6) · K(15) · P(21) · E(27)</span></div><div><b>Рис. 60</b><span>1 клетка = 3 координатные единицы</span></div></div></div>;
  if(kind==='distance')return <div className="scale-visual l15-distance-model"><div className="scale-caption"><b>№131–132 · x ± d</b><span>отрицательную левую координату отбрасываем</span></div><div className="construction-steps"><div><b>B(5), d=6</b>только 11</div><div><b>B(5), d=3</b>2 и 8</div><div><b>A(7), d=7</b>0 и 14</div><div><b>A(7), d=4</b>3 и 11</div></div></div>;
  if(kind==='arrows')return <div className="scale-visual l15-arrow-model"><div className="scale-caption"><b>№133–134 · направление имеет значение</b><span>конец и начало стрелки — разные задачи</span></div><div className="l15-arrow-rows"><div><b>№133</b><span>46 → +9 → 55</span><span>293 → −25 → 268</span></div><div><b>№134</b><span>74 → +8 → 82</span><span>424 → −16 → 408</span></div></div></div>;
  if(kind==='proof')return <div className="scale-visual l15-proof-model"><div className="scale-caption"><b>Три масштаба не смешиваем</b><span>математика → рисунок → подписи</span></div><div className="construction-steps"><div><b>Единичный отрезок</b>всегда +1</div><div><b>Большое деление</b>может быть +3, +10…</div><div><b>Физическая длина</b>5 мм, 1 см…</div><div><b>Координата</b>не зависит от размера рисунка</div></div></div>;
  return <div className="scale-visual l15-route-model"><div className="scale-caption"><b>Маршрут § 5</b><span>№126–134</span></div><div className="construction-steps"><div><b>1</b>Построй шкалу</div><div><b>2</b>Прочитай / поставь точки</div><div><b>3</b>Проверь расстояние</div><div><b>4</b>Разбери стрелку</div></div></div>;
}

export function ScaleCoordinateRaySummaryPlayer(){
const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
const stage=lessonFifteenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;const quiz=['l15-q1','l15-q2','l15-q3','l15-q4','l15-q5'];const practice=['l15-p1','l15-p2','l15-p3','l15-p4','l15-p5','l15-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const coreComplete=quizScore===5&&practiceScore===6;const progress=Math.round(((stageIndex+1)/lessonFifteenStages.length)*100);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:2,stageIndex,responses,checked,results})),[stageIndex,responses,checked,results]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===15&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonFifteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
function setAnswer(value:string){if(!activity)return;setResponses(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function submit(){if(!activity)return;const ok=norm(answer)===norm(activity.answer);setChecked(p=>({...p,[activity.id]:true}));setResults(p=>({...p,[activity.id]:ok}))}
function reset(){localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);setStageIndex(0);setResponses({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:15}}))}
function render(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>}
return <main className="lesson-player-page coordinate-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 15 из 175 · § 5</span><h1>Шкала. Координатный луч — обобщение</h1><p>Финал по Мерзляку: №126–134, от построения шкалы до расстояний и стрелок.</p></div><div className="lesson-duration">план · 42 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonFifteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<PracticeVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь, что именно считается: единичные отрезки, крупные деления, координаты или физическая длина. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Итоговый контроль</span><b>{quizScore}/5</b><small>{quizScore===5?'всё верно':'нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{coreComplete?'Основная часть ✓':'Повторить'}</b><small>{coreComplete?'дальше — обязательная практика и финальное объяснение':'исправь ошибки основной части'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonFifteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
