import { useEffect,useMemo,useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './coordinateRay.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
type Visual='scale'|'reconstruct'|'compare'|'errors'|'route';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;visual?:Visual;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};
const KEY='mathnikita-lesson-14-progress-v1';

export const lessonFourteenStages:Stage[]=[
{id:'l14-mission',kind:'story',eyebrow:'Закрепление · § 5',title:'Сегодня координатный луч нужно не узнать, а восстановить',body:'Иногда на рисунке подписаны только две точки, иногда нужно самому выбрать масштаб, а иногда в готовом построении спрятана ошибка. На этом уроке ты будешь работать как математический картограф.',note:'Любое построение проверяется четырьмя вещами: начало, ноль, единичный отрезок и равные промежутки.',sourceTag:'Мерзляк § 5, урок закрепления',visual:'route'},
{id:'l14-recall',kind:'guided',eyebrow:'Быстрая диагностика',title:'Что обязательно есть у координатного луча',body:'Выбери полный набор признаков. Одной стрелки или нескольких подписанных чисел недостаточно.',activity:{id:'l14-a1',type:'choice',prompt:'Какой набор описывает координатный луч полностью?',options:['Начало, число 0, единичный отрезок и направление','Только стрелка и несколько чисел','Две любые точки и прямая','Линейка любой длины'],answer:'Начало, число 0, единичный отрезок и направление',explanation:'Координатный луч задают началом отсчёта, нулём, направлением и выбранным единичным отрезком.'}},
{id:'l14-scale-choice',kind:'model',eyebrow:'Масштаб',title:'Один штрих может означать не одну единицу',body:'Если соседние отметки соответствуют числам 0, 6, 12, 18, то один графический промежуток равен шести координатным единицам.',note:'Не путай длину штриха на экране со значением шага в координатах.',visual:'scale'},
{id:'l14-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Восстанавливаем цену шага',body:'От отметки 0 до отметки 60 расположено 10 равных промежутков.',activity:{id:'l14-p1',type:'input',prompt:'Сколько координатных единиц приходится на один промежуток?',answer:'6',placeholder:'Цена шага',explanation:'60 : 10 = 6 координатных единиц.'}},
{id:'l14-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Находим координату по числу шагов',body:'Единичный шаг шкалы равен 6. Точка A стоит на седьмой отметке справа от нуля.',activity:{id:'l14-p2',type:'input',prompt:'Какова координата точки A?',answer:'42',placeholder:'Координата',explanation:'7 · 6 = 42, поэтому A (42).'}},
{id:'l14-reconstruct',kind:'model',eyebrow:'Обратная задача',title:'Две известные точки раскрывают всю шкалу',body:'Если A (18) и B (42) разделены четырьмя равными промежутками, то разность координат 24 нужно разделить на 4.',note:'Сначала находят разность координат, затем делят её на число промежутков.',visual:'reconstruct'},
{id:'l14-guided',kind:'guided',eyebrow:'Решаем вместе',title:'Восстанови пропущенные подписи',body:'Точки A (18) и B (42) стоят через четыре равных промежутка.',activity:{id:'l14-a2',type:'input',prompt:'Какое число прибавляется при переходе к соседней отметке?',answer:'6',placeholder:'Шаг',explanation:'42 − 18 = 24; 24 : 4 = 6.'}},
{id:'l14-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Шаг между двумя точками',body:'Точки C (12) и D (48) разделены шестью равными промежутками.',activity:{id:'l14-p3',type:'input',prompt:'Найди координатный шаг одного промежутка.',answer:'6',placeholder:'Шаг',explanation:'48 − 12 = 36; 36 : 6 = 6.'}},
{id:'l14-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Координата далёкой точки',body:'От нуля до точки K пять равных промежутков. Каждый промежуток соответствует 8 единицам.',activity:{id:'l14-p4',type:'input',prompt:'Запиши координату точки K.',answer:'40',placeholder:'Координата',explanation:'5 · 8 = 40, значит K (40).'}},
{id:'l14-convenient',kind:'model',eyebrow:'Выбор масштаба',title:'Удобный единичный отрезок экономит место и ошибки',body:'Для точек с координатами 24, 48 и 72 можно выбрать шаг 12: тогда они окажутся на второй, четвёртой и шестой отметках.',note:'Хороший масштаб позволяет разместить все нужные точки и получить целое число шагов.',visual:'compare'},
{id:'l14-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Выбираем удобный шаг',body:'Нужно построить луч до числа 72 ровно за шесть одинаковых промежутков.',activity:{id:'l14-p5',type:'choice',prompt:'Какой координатный шаг следует выбрать?',options:['6','9','12','18'],answer:'12',explanation:'72 : 6 = 12, поэтому каждый промежуток должен соответствовать 12 единицам.'}},
{id:'l14-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'План точного построения',body:'Нужно отметить точки B (18), C (30) и D (42), выбрав шаг 6.',activity:{id:'l14-p6',type:'order',prompt:'Расставь действия в правильном порядке',items:['Провести луч и обозначить начало O','Подписать под началом число 0','Выбрать координатный шаг 6','Отложить равные промежутки вправо','Отметить B (18), C (30) и D (42)','Проверить число шагов до каждой точки'],answer:['Провести луч и обозначить начало O','Подписать под началом число 0','Выбрать координатный шаг 6','Отложить равные промежутки вправо','Отметить B (18), C (30) и D (42)','Проверить число шагов до каждой точки'],explanation:'Сначала задают луч и масштаб, затем строят точки и обязательно проверяют число равных шагов.'}},
{id:'l14-error-lab',kind:'model',eyebrow:'Лаборатория ошибок',title:'Красивый рисунок может быть математически неверным',body:'Нельзя подписывать числа 0, 10, 20, 35 под равными промежутками: изменение координаты должно быть одинаковым на каждом шаге.',note:'Равным графическим промежуткам соответствуют равные изменения координаты.',sourceTag:'Мерзляк § 5, упражнения на построение и чтение координат',visual:'errors'},
{id:'l14-error-check',kind:'guided',eyebrow:'Найди нарушение',title:'Проверяем готовый луч',body:'На луче под равными промежутками подписаны числа 0, 8, 16, 25.',activity:{id:'l14-a3',type:'choice',prompt:'В чём ошибка?',options:['Последний шаг должен привести к 24, а не к 25','Нельзя подписывать число 0','Координаты должны уменьшаться вправо','Все точки обязаны иметь буквенные названия'],answer:'Последний шаг должен привести к 24, а не к 25',explanation:'Шаг равен 8, поэтому последовательность должна быть 0, 8, 16, 24.'}},
{id:'l14-control',kind:'model',eyebrow:'Перед самостоятельной работой',title:'Три способа проверить себя',body:'Проверь равенство промежутков, постоянство координатного шага и соответствие координаты числу шагов от нуля.',note:'Для двух известных точек используй формулу: шаг = разность координат : число промежутков.',visual:'route'},
{id:'l14-quiz1',kind:'quiz',eyebrow:'Самостоятельная проверка · 1/5',title:'Координата по масштабу',body:'Без подсказки.',activity:{id:'l14-q1',type:'input',prompt:'Шаг равен 7. Точка A находится на девятой отметке после нуля. Координата A?',answer:'63',placeholder:'Ответ',explanation:'9 · 7 = 63.'}},
{id:'l14-quiz2',kind:'quiz',eyebrow:'Самостоятельная проверка · 2/5',title:'Масштаб по двум точкам',body:'Без подсказки.',activity:{id:'l14-q2',type:'input',prompt:'A (15) и B (45) разделены пятью равными промежутками. Чему равен шаг?',answer:'6',placeholder:'Ответ',explanation:'45 − 15 = 30; 30 : 5 = 6.'}},
{id:'l14-quiz3',kind:'quiz',eyebrow:'Самостоятельная проверка · 3/5',title:'Координата и размер рисунка',body:'Без подсказки.',activity:{id:'l14-q3',type:'choice',prompt:'На двух рисунках точка M имеет координату 5, но единичные отрезки разной длины. Что верно?',options:['Обе записи M (5) могут быть верными','Верна только шкала с отрезком 1 см','Больший отрезок даёт большую координату','Координата зависит от ширины экрана'],answer:'Обе записи M (5) могут быть верными',explanation:'Координата определяется числом единичных шагов, а не физической длиной рисунка.'}},
{id:'l14-quiz4',kind:'quiz',eyebrow:'Самостоятельная проверка · 4/5',title:'Составное перемещение',body:'Без подсказки.',activity:{id:'l14-q4',type:'input',prompt:'Из точки P (32) сделали 3 шага по 4 единицы влево, затем 5 шагов по 2 единицы вправо. Где оказались?',answer:'30',placeholder:'Ответ',explanation:'32 − 3 · 4 + 5 · 2 = 32 − 12 + 10 = 30.'}},
{id:'l14-quiz5',kind:'quiz',eyebrow:'Самостоятельная проверка · 5/5',title:'Точки между границами',body:'Без подсказки.',activity:{id:'l14-q5',type:'input',prompt:'Сколько натуральных координат расположено строго между 18 и 31?',answer:'12',placeholder:'Ответ',explanation:'31 − 18 − 1 = 12.'}},
{id:'l14-challenge',kind:'challenge',eyebrow:'Задача повышенной сложности',title:'Третья точка на восстановленной шкале',body:'Точки A (18) и B (54) разделены шестью равными промежутками. Точка C находится на четыре промежутка правее A.',activity:{id:'l14-c1',type:'input',prompt:'Какова координата точки C?',answer:'42',placeholder:'Координата',explanation:'Шаг равен (54 − 18) : 6 = 6. Тогда C: 18 + 4 · 6 = 42.'}},
{id:'l14-reflection',kind:'model',eyebrow:'Рефлексия',title:'Теперь ты умеешь читать даже неполную шкалу',body:'Ты можешь выбрать масштаб, восстановить пропущенные координаты, построить несколько точек и доказать, почему готовый рисунок верен или ошибочен.',visual:'compare'},
{id:'l14-summary',kind:'summary',eyebrow:'Итог урока',title:'Координатный луч стал рабочим инструментом',body:'Закреплены построение точек, выбор единичного отрезка, восстановление шага и проверка координатных схем.'}
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е').replace(/единиц(а|ы)?/g,'')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFourteenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

function PracticeVisual({kind}:{kind:Visual}){
  if(kind==='errors')return <div className="scale-visual"><div className="scale-caption"><b>Проверка постоянного шага</b><span>равные промежутки — равные изменения</span></div><div className="construction-steps"><div><b>0 → 8</b>+8</div><div><b>8 → 16</b>+8</div><div><b>16 → 25</b>+9 ✕</div><div><b>Верно</b>16 → 24</div></div></div>;
  if(kind==='compare')return <div className="scale-visual"><div className="scale-caption"><b>Одинаковые координаты — разный размер рисунка</b><span>число шагов важнее сантиметров</span></div><div className="construction-steps"><div><b>Шаг 1 см</b>M после 5 шагов</div><div><b>Шаг 2 см</b>M после 5 шагов</div><div><b>В обоих случаях</b>M (5)</div></div></div>;
  if(kind==='route')return <div className="scale-visual"><div className="scale-caption"><b>Маршрут проверки</b><span>от начала до координаты</span></div><div className="construction-steps"><div><b>1</b>Найди O и 0</div><div><b>2</b>Определи шаг</div><div><b>3</b>Посчитай промежутки</div><div><b>4</b>Проверь координату</div></div></div>;
  const values=kind==='reconstruct'?[18,24,30,36,42]:[0,6,12,18,24,30,36,42,48];
  return <div className="scale-visual"><div className="scale-caption"><b>{kind==='reconstruct'?'Шкала между A и B':'Координатный шаг 6'}</b><span>{kind==='reconstruct'?'четыре равных промежутка':'каждый промежуток добавляет 6'}</span></div><div className="ray-track">{values.map((value,index)=><div className={`tick ${index===0||index===values.length-1?'major':''}`} key={value}><span>{value}</span>{kind==='reconstruct'&&(index===0||index===values.length-1)?<small>{index===0?'A':'B'}</small>:null}</div>)}</div></div>;
}

export function ScaleCoordinateRayPracticePlayer(){
const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);
const stage=lessonFourteenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;const quiz=['l14-q1','l14-q2','l14-q3','l14-q4','l14-q5'];const practice=['l14-p1','l14-p2','l14-p3','l14-p4','l14-p5','l14-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonFourteenStages.length)*100);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===14&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonFourteenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
function setAnswer(value:string){if(!activity)return;setResponses(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function setOrder(value:string[]){if(!activity)return;setOrders(p=>({...p,[activity.id]:value}));setChecked(p=>({...p,[activity.id]:false}))}
function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(p=>({...p,[activity.id]:true}));setResults(p=>({...p,[activity.id]:ok}))}
function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
function render(current:Activity){if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>}
return <main className="lesson-player-page coordinate-ray-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 14 из 175 · § 5</span><h1>Шкала. Координатный луч</h1><p>Закрепление: выбор масштаба, восстановление шага, построение точек и проверка координатных схем.</p></div><div className="lesson-duration">40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonFourteenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{stage.visual?<PracticeVisual kind={stage.visual}/>:null}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь разность координат, число промежутков и выбранный шаг. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Самостоятельная проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема закреплена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonFourteenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
