import { useEffect, useMemo, useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './segmentLength.css';
import './segmentPractice.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type SegmentPracticeStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>};

const KEY='mathnikita-lesson-7-progress-v1';

export const lessonSevenStages:SegmentPracticeStage[]=[
  {id:'l7-story',kind:'story',eyebrow:'Геометрическая мастерская',title:'Теперь отрезки нужно не узнавать, а уверенно использовать',body:'На прошлом уроке мы познакомились с отрезком и длиной. Сегодня закрепляем навык: читаем чертёж, переводим единицы, находим целое и части и строим отрезок заданной длины.',note:'Главный рабочий инструмент: если C лежит на AB, то AB = AC + CB.',sourceTag:'Мерзляк § 3 · урок 7 · закрепление знаний'},
  {id:'l7-rule-model',kind:'model',eyebrow:'Опорное правило',title:'Сначала восстанови порядок точек',body:'Перед вычислением посмотри, какая точка лежит между какими. Только после этого записывай сумму или разность длин.',note:'Для порядка A—C—B: AB = AC + CB.'},
  {id:'l7-unit-equal',kind:'guided',eyebrow:'Разминка · единицы',title:'Равные длины могут выглядеть по-разному',body:'Сравнивать длины удобно после перевода в одну единицу.',activity:{id:'l7-a1',type:'choice',prompt:'AB = 4 см 8 мм, NP = 48 мм, ST = 504 мм. Какие два отрезка равны?',options:['AB и NP','AB и ST','NP и ST','все три'],answer:'AB и NP',explanation:'4 см 8 мм = 48 мм, поэтому AB = NP. ST = 504 мм значительно длиннее.'},sourceTag:'Математический диктант 2 · «Отрезок. Длина отрезка»'},
  {id:'l7-task59',kind:'guided',eyebrow:'Учебник · № 59',title:'Когда одна часть в несколько раз длиннее другой',body:'Точки расположены R—S—K. Отрезок SK в 3 раза длиннее RS, а RS = 34 см. Сначала найдём SK, затем весь RK.',activity:{id:'l7-a2',type:'input',prompt:'Чему равен RK в сантиметрах?',answer:'136',placeholder:'Ответ в см',explanation:'SK = 34 · 3 = 102 см, поэтому RK = RS + SK = 34 + 102 = 136 см.'},sourceTag:'Мерзляк § 3 · № 59'},
  {id:'l7-chain-model',kind:'model',eyebrow:'Читаем чертёж',title:'Одна и та же точка может входить в несколько отрезков',body:'Для порядка A—C—B—D отрезок AB состоит из AC и CB, а CD — из CB и BD. Один рисунок даёт сразу два равенства.',note:'AB = AC + CB; CD = CB + BD.'},
  {id:'l7-task61',kind:'guided',eyebrow:'Учебник · № 61',title:'Найди неизвестную часть цепочки',body:'На рисунке A—C—B—D даны AC = 32 см, BC = 9 см и CD = 12 см. Здесь AB = 41 см, а для BD нужно использовать CD = CB + BD.',activity:{id:'l7-a3',type:'input',prompt:'Чему равен BD в сантиметрах?',answer:'3',placeholder:'Ответ в см',explanation:'BD = CD − CB = 12 − 9 = 3 см. Одновременно AB = 32 + 9 = 41 см.'},sourceTag:'Мерзляк § 3 · № 61'},
  {id:'l7-subsegments-model',kind:'model',eyebrow:'Все пары точек',title:'Четыре точки дают несколько разных отрезков',body:'На одном отрезке отметим точки в порядке M—A—C—K. Можно назвать не только соседние MA, AC, CK, но и более длинные MC, AK, MK.',note:'Для этих четырёх точек получаются 6 разных отрезков.'},
  {id:'l7-practice1',kind:'practice',eyebrow:'Практика · 1/6',title:'Две точки — один отрезок',body:'Закрепляем базовое свойство без лишних вычислений.',activity:{id:'l7-p1',type:'choice',prompt:'Даны две точки A и B. Сколько отрезков с концами A и B существует?',options:['0','1','2','бесконечно много'],answer:'1',explanation:'Две заданные точки определяют единственный отрезок AB.'},sourceTag:'Мерзляк § 3 · № 63'},
  {id:'l7-practice2',kind:'practice',eyebrow:'Практика · 2/6',title:'Перечисли все отрезки на одной линии',body:'На отрезке MK отмечены точки A и C в порядке M—A—C—K.',activity:{id:'l7-p2',type:'input',prompt:'Сколько разных отрезков можно назвать, используя пары точек M, A, C, K?',answer:'6',placeholder:'Количество',explanation:'MA, MC, MK, AC, AK и CK — всего 6 отрезков.'},sourceTag:'По задаче Мерзляка § 3 · № 64'},
  {id:'l7-practice3',kind:'practice',eyebrow:'Практика · 3/6',title:'Вычти две известные части',body:'Точки расположены A—M—K—B. Известно AB = 28 см, AM = 12 см, BK = 9 см.',activity:{id:'l7-p3',type:'input',prompt:'Найди MK в сантиметрах.',answer:'7',placeholder:'Ответ в см',explanation:'MK = AB − AM − BK = 28 − 12 − 9 = 7 см.'},sourceTag:'Мерзляк § 3 · № 65'},
  {id:'l7-practice4',kind:'practice',eyebrow:'Практика · 4/6',title:'Разница длин сразу даёт недостающую часть',body:'C принадлежит AB. AC = 15 см, а AB на 5 см больше AC.',activity:{id:'l7-p4',type:'input',prompt:'Чему равен BC в сантиметрах?',answer:'5',placeholder:'Ответ в см',explanation:'BC = AB − AC. По условию эта разность уже равна 5 см.'},sourceTag:'Мерзляк § 3 · № 66'},
  {id:'l7-practice5',kind:'practice',eyebrow:'Практика · 5/6',title:'Приведи длины к одной единице',body:'Смешанные единицы часто маскируют равные отрезки.',activity:{id:'l7-p5',type:'choice',prompt:'Какой отрезок равен 5 дм 4 мм?',options:['54 мм','504 мм','540 мм','5004 мм'],answer:'504 мм',explanation:'5 дм = 500 мм, ещё 4 мм дают 504 мм.'},sourceTag:'Математический диктант 2 · «Отрезок. Длина отрезка»'},
  {id:'l7-practice6',kind:'practice',eyebrow:'Практика · 6/6',title:'Построй отрезок без ошибки масштаба',body:'Экран не является физической линейкой: здесь тренируем математический порядок действий, а реальное построение выполняют линейкой.',activity:{id:'l7-p6',type:'order',prompt:'Расставь шаги построения отрезка PK длиной 7 см',items:['Отметить точку P','Совместить нулевую отметку линейки с P','На отметке 7 см поставить точку K','Провести отрезок PK по линейке'],answer:['Отметить точку P','Совместить нулевую отметку линейки с P','На отметке 7 см поставить точку K','Провести отрезок PK по линейке'],explanation:'Начало измерения совмещаем с нулём, затем отмечаем второй конец на нужной отметке и соединяем точки.'}},
  {id:'l7-extra-data',kind:'guided',eyebrow:'Математическая внимательность',title:'Не все числа в условии обязательно нужны',body:'В задаче № 66 сказано: AB на 5 см больше AC. Этой разности уже достаточно, чтобы получить BC = 5 см.',activity:{id:'l7-a4',type:'choice',prompt:'Какое числовое данное можно не использовать для нахождения BC?',options:['AC = 15 см','AB на 5 см больше AC','C принадлежит AB','никакое'],answer:'AC = 15 см',explanation:'Конкретная длина AC = 15 см не нужна: из отношения AB = AC + 5 сразу следует BC = 5 см.'},sourceTag:'Мерзляк § 3 · № 66'},
  {id:'l7-half-model',kind:'model',eyebrow:'Задача со структурой',title:'Равные половины помогают собирать длинную цепочку',body:'В задаче № 75 отрезок AE равен 12 см, а пары AQ = QB, BM = MC, CK = KD и DR = RE. Поэтому QB + BM + KD + DR составляет половину AE, то есть 6 см.',note:'Поскольку MK = MC + CK = 4 см, то QR = (QB + BM + KD + DR) + MK = 6 + 4 = 10 см.',sourceTag:'Мерзляк § 3 · № 75 · методический комментарий'},
  {id:'l7-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Целое из двух частей',body:'Без подсказки.',activity:{id:'l7-q1',type:'input',prompt:'C лежит на AB. AC = 23 см, CB = 17 см. Найди AB.',answer:'40',placeholder:'Ответ в см',explanation:'AB = AC + CB = 23 + 17 = 40 см.'}},
  {id:'l7-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Часть цепочки',body:'Без подсказки.',activity:{id:'l7-q2',type:'input',prompt:'Точки идут C—B—D. CB = 8 см, CD = 13 см. Найди BD.',answer:'5',placeholder:'Ответ в см',explanation:'CD = CB + BD, значит BD = 13 − 8 = 5 см.'}},
  {id:'l7-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Одинаковые единицы',body:'Без подсказки.',activity:{id:'l7-q3',type:'choice',prompt:'5 см 4 мм — это…',options:['45 мм','50 мм','54 мм','504 мм'],answer:'54 мм',explanation:'5 см = 50 мм, поэтому 5 см 4 мм = 54 мм.'}},
  {id:'l7-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Сколько отрезков видно через три точки',body:'Точки A, C, B лежат на одном отрезке в этом порядке.',activity:{id:'l7-q4',type:'choice',prompt:'Сколько разных отрезков можно назвать по парам точек A, C, B?',options:['2','3','4','6'],answer:'3',explanation:'Это AC, CB и AB — три разных отрезка.'}},
  {id:'l7-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Линейка со сдвигом',body:'Начальная отметка не обязана быть нулевой.',activity:{id:'l7-q5',type:'input',prompt:'Концы отрезка совпали с отметками 4 см и 11 см. Какова длина отрезка?',answer:'7',placeholder:'Ответ в см',explanation:'Длина равна разности отметок: 11 − 4 = 7 см.'}},
  {id:'l7-challenge',kind:'challenge',eyebrow:'Задача повышенного уровня',title:'Собери QR из скрытой половины и известной части',body:'AE = 12 см; AQ = QB, BM = MC, CK = KD, DR = RE; MK = 4 см. Из равных пар следует: QB + BM + KD + DR = AE ÷ 2 = 6 см.',activity:{id:'l7-c1',type:'input',prompt:'Чему равен QR в сантиметрах?',answer:'10',placeholder:'Ответ в см',explanation:'QR = QB + BM + MK + KD + DR = (QB + BM + KD + DR) + MK = 6 + 4 = 10 см.'},sourceTag:'Мерзляк § 3 · № 75'},
  {id:'l7-reflection',kind:'guided',eyebrow:'Рефлексия',title:'Проверь не только ответ, но и способ',body:'Вспомни урок: какое задание понравилось больше всего? Какие задания вызвали затруднения? Это ровно те вопросы, которыми методическое пособие завершает урок № 7.',note:'Сильный навык — уметь назвать место, где рассуждение стало сложным, и вернуться к нему.'},
  {id:'l7-summary',kind:'summary',eyebrow:'Итог основной части',title:'Отрезки теперь работают как система',body:'Ты закрепил измерение и построение, чтение цепочек точек, перевод единиц и вычисление неизвестных частей. Теперь впереди обязательная практика и итоговое объяснение своими словами.',note:'Урок получит статус «завершён» только после обязательной практики и итоговой рефлексии.'}
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{
  try{
    const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;
    if(parsed?.version!==1)return empty;
    return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSevenStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}};
  }catch{return empty}
}

function chainModel(points:string[],caption:string){return <div className="l7-chain-model">{points.flatMap((point,index)=>index===points.length-1?[<span key={`${point}-${index}`}>{point}</span>]:[<span key={`${point}-${index}`}>{point}</span>,<i key={`line-${index}`}/ >])}<strong>{caption}</strong></div>}
function rulerModel(max:number){return <div className="l6-ruler"><div>{Array.from({length:max+1},(_,index)=><span key={index}><i/><b>{index}</b></span>)}</div><em>длина = конечная отметка − начальная отметка</em></div>}

export function SegmentLengthPracticePlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);
  const stage=lessonSevenStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l7-q1','l7-q2','l7-q3','l7-q4','l7-q5'];const practice=['l7-p1','l7-p2','l7-p3','l7-p4','l7-p5','l7-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonSevenStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results})),[stageIndex,responses,orders,checked,results]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===7&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonSevenStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});window.dispatchEvent(new CustomEvent('mathnikita-lesson-reset',{detail:{lessonNumber:7}}))}
  const model=useMemo(()=>{
    if(['l7-story','l7-rule-model','l7-quiz1'].includes(stage.id))return <div className="l6-addition-model"><div><span>A</span><i/><span>C</span><i/><span>B</span></div><strong>AB = AC + CB</strong></div>;
    if(['l7-unit-equal','l7-practice5','l7-quiz3'].includes(stage.id))return <div className="l6-equal-model"><div><span>4 см 8 мм</span><i/><span>48 мм</span></div><div><span>5 дм 4 мм</span><i/><span>504 мм</span></div><strong>Сначала — одна единица</strong></div>;
    if(stage.id==='l7-task59')return <div className="l7-chain-model three"><span>R</span><i/><span>S</span><i className="long"/><span>K</span><strong>RS = 34 см · SK = 3 · RS</strong></div>;
    if(['l7-chain-model','l7-task61'].includes(stage.id))return chainModel(['A','C','B','D'],'Сначала прочитай порядок точек');
    if(stage.id==='l7-practice3')return chainModel(['A','M','K','B'],'AB = AM + MK + KB');
    if(stage.id==='l7-practice4')return chainModel(['A','C','B'],'AB = AC + CB');
    if(stage.id==='l7-quiz2')return chainModel(['C','B','D'],'CD = CB + BD');
    if(['l7-subsegments-model','l7-practice1','l7-practice2','l7-quiz4'].includes(stage.id))return <div className="l7-points-model"><span>M</span><span>A</span><span>C</span><span>K</span><i/><strong>MA · MC · MK · AC · AK · CK</strong></div>;
    if(stage.id==='l7-practice6')return rulerModel(8);
    if(stage.id==='l7-quiz5')return rulerModel(12);
    if(['l7-half-model','l7-challenge'].includes(stage.id))return <div className="l7-half-model"><div><span>A</span><i/><span>Q</span><i/><span>B</span><i/><span>M</span><i/><span>C</span><i/><span>K</span><i/><span>D</span><i/><span>R</span><i/><span>E</span></div><strong>AE = 12 см · MK = 4 см</strong></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page segment-length-page segment-practice-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 7 из 175 · § 3</span><h1>Отрезок. Длина отрезка — закрепление</h1><p>Геометрическая практика по Мерзляку: измерение и построение, цепочки точек, равные длины и задачи на части отрезка.</p></div><div className="lesson-duration">план · 40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonSevenStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Сначала восстанови порядок точек и приведи длины к одной единице. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>основная часть</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>основная часть</small></div><div><span>Статус</span><b>Основная часть ✓</b><small>дальше — обязательная практика</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonSevenStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
