import { useEffect, useMemo, useState } from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './segmentLength.css';

type Activity={id:string;type:'choice'|'input'|'order';prompt:string;options?:string[];items?:string[];answer:string|string[];explanation:string;placeholder?:string};
export type SegmentLengthStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;sourceTag?:string;activity?:Activity};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;orders:Record<string,string[]>;checked:Record<string,boolean>;results:Record<string,boolean>;completedAt?:string};

const KEY='mathnikita-lesson-6-progress-v1';

export const lessonSixStages:SegmentLengthStage[]=[
  {id:'l6-story',kind:'story',eyebrow:'Новая глава геометрии',title:'Как соединить две точки самым коротким путём?',body:'Отметим точки A и B. Между ними можно провести много кривых линий, но линейка показывает единственный прямой короткий путь — отрезок AB.',note:'Точка и отрезок — геометрические фигуры. Точки A и B называют концами отрезка.',sourceTag:'Мерзляк § 3 · урок 6'},
  {id:'l6-segment-definition',kind:'model',eyebrow:'Главный объект',title:'Отрезок задаётся двумя концами',body:'Если концами являются точки A и B, существует ровно один отрезок с этими концами. В записи используют названия концов: AB или BA.',note:'AB и BA — два обозначения одного и того же отрезка.'},
  {id:'l6-unique',kind:'guided',eyebrow:'Проверяем определение',title:'Между двумя концами — один отрезок',body:'Кривых линий между двумя точками можно придумать сколько угодно. Но отрезок с заданными концами определяется однозначно.',activity:{id:'l6-a1',type:'choice',prompt:'Сколько существует отрезков, концами которых являются точки A и B?',options:['ни одного','ровно один','ровно два','бесконечно много'],answer:'ровно один',explanation:'Для двух данных концов A и B существует единственный отрезок AB.'}},
  {id:'l6-name',kind:'guided',eyebrow:'Математический язык',title:'Название можно читать в обе стороны',body:'Порядок букв в названии отрезка не меняет саму фигуру: сначала можно назвать любой из его концов.',activity:{id:'l6-a2',type:'choice',prompt:'Какие обозначения подходят для одного отрезка с концами A и B?',options:['только AB','только BA','AB и BA','AA и BB'],answer:'AB и BA',explanation:'Отрезок обозначают по двум концам, поэтому записи AB и BA равноправны.'}},
  {id:'l6-measure-model',kind:'model',eyebrow:'Из фигуры — в число',title:'Длину сравнивают с единичным отрезком',body:'Чтобы измерить отрезок, выбирают единицу длины и определяют, сколько таких единичных отрезков в нём помещается. Линейка делает это сравнение удобным.',note:'В учебнике используются миллиметры, сантиметры, дециметры и километры.'},
  {id:'l6-unit',kind:'guided',eyebrow:'Смысл измерения',title:'Измерить — значит сравнить с единицей',body:'Число возле обозначения длины показывает, сколько выбранных единиц укладывается в отрезке.',activity:{id:'l6-a3',type:'choice',prompt:'Что означает «измерить длину отрезка»?',options:['посчитать его точки','узнать его цвет','подсчитать, сколько единичных отрезков в нём помещается','назвать его концы'],answer:'подсчитать, сколько единичных отрезков в нём помещается',explanation:'Именно так учебник определяет смысл измерения длины отрезка.'}},
  {id:'l6-units',kind:'guided',eyebrow:'Единицы длины',title:'Единица должна быть указана',body:'Одна и та же фигура получит разные числовые значения в миллиметрах и сантиметрах. Поэтому ответ о длине всегда включает единицу измерения.',activity:{id:'l6-a4',type:'choice',prompt:'Отрезок PK на линейке имеет длину 17 миллиметров. Какая запись верна?',options:['PK = 17','PK = 17 мм','PK = 17 см','PK = 1 мм'],answer:'PK = 17 мм',explanation:'Число без единицы не передаёт полную информацию о длине; здесь единица — миллиметр.'}},
  {id:'l6-additivity-model',kind:'model',eyebrow:'Главное свойство длины',title:'Точка внутри делит отрезок на части',body:'Если точка C лежит на отрезке AB, то весь отрезок складывается из двух частей: AC и CB.',note:'Свойство длины отрезка: AB = AC + CB.',sourceTag:'Мерзляк § 3 · свойство длины отрезка'},
  {id:'l6-equal-model',kind:'model',eyebrow:'Равные отрезки',title:'Равенство можно проверить наложением',body:'Два отрезка называют равными, если они совпадают при наложении. У равных отрезков равны и их длины.',note:'Одинаковая длина позволяет переносить и сравнивать отрезки независимо от их положения на рисунке.'},
  {id:'l6-endpoints',kind:'practice',eyebrow:'Практика · 1/6',title:'Найди концы отрезка',body:'Название отрезка сразу сообщает две его граничные точки.',activity:{id:'l6-p1',type:'choice',prompt:'Какие точки являются концами отрезка MN?',options:['M и N','M и K','только M','любые две точки'],answer:'M и N',explanation:'Буквы M и N в названии отрезка — его концы.'}},
  {id:'l6-whole',kind:'practice',eyebrow:'Практика · 2/6',title:'Собери длину целого',body:'Когда внутренняя точка известна, длину целого находят сложением длин частей.',activity:{id:'l6-p2',type:'input',prompt:'Точка C лежит на AB. AC = 6 см, CB = 9 см. Чему равна длина AB в сантиметрах?',answer:'15',placeholder:'Ответ в см',explanation:'AB = AC + CB = 6 + 9 = 15 см.'}},
  {id:'l6-part',kind:'practice',eyebrow:'Практика · 3/6',title:'Найди недостающую часть',body:'Из равенства AB = AC + CB можно найти любую неизвестную часть, если известны длина целого и другая часть.',activity:{id:'l6-p3',type:'input',prompt:'AB = 18 см, AC = 7 см, точка C лежит на AB. Чему равна CB в сантиметрах?',answer:'11',placeholder:'Ответ в см',explanation:'CB = AB − AC = 18 − 7 = 11 см.'}},
  {id:'l6-convert',kind:'practice',eyebrow:'Практика · 4/6',title:'Сравни длины в одной единице',body:'Перед сравнением удобно перевести обе длины в одинаковые единицы.',activity:{id:'l6-p4',type:'choice',prompt:'Какова длина 4 см 8 мм в миллиметрах?',options:['12 мм','40 мм','48 мм','408 мм'],answer:'48 мм',explanation:'4 см = 40 мм, ещё 8 мм дают 48 мм.'}},
  {id:'l6-equal',kind:'practice',eyebrow:'Практика · 5/6',title:'Узнай равные отрезки',body:'Равные отрезки совпадают при наложении; следовательно, их длины одинаковы.',activity:{id:'l6-p5',type:'choice',prompt:'Какое утверждение верно для равных отрезков?',options:['они обязательно лежат горизонтально','они совпадают при наложении','у них разные длины','у них должны совпадать названия'],answer:'они совпадают при наложении',explanation:'Именно совпадение при наложении является определением равных отрезков.'}},
  {id:'l6-build-order',kind:'practice',eyebrow:'Практика · 6/6',title:'Построй отрезок заданной длины',body:'На экране мы тренируем порядок действий схематически: физические сантиметры зависят от масштаба устройства, а математический алгоритм остаётся тем же.',activity:{id:'l6-p6',type:'order',prompt:'Расставь шаги построения отрезка AB длиной 6 см с помощью линейки',items:['Отметить точку A','Совместить нулевую отметку линейки с A','На отметке 6 см поставить точку B','Соединить A и B по линейке'],answer:['Отметить точку A','Совместить нулевую отметку линейки с A','На отметке 6 см поставить точку B','Соединить A и B по линейке'],explanation:'Нулевая отметка фиксирует начало измерения, а отметка 6 см задаёт второй конец.'}},
  {id:'l6-ruler-shift',kind:'guided',eyebrow:'Ловушка линейки',title:'Не всегда начало лежит на нуле',body:'Если один конец отрезка совпал с отметкой 2 см, а другой — с отметкой 7 см, длина равна разности показаний.',activity:{id:'l6-a5',type:'input',prompt:'Концы отрезка стоят на отметках 2 см и 7 см. Какова его длина в сантиметрах?',answer:'5',explanation:'7 − 2 = 5 см. Нельзя просто назвать конечную отметку 7 см длиной отрезка.'}},
  {id:'l6-quiz1',kind:'quiz',eyebrow:'Мини-проверка · 1/5',title:'Единственность отрезка',body:'Ответь без подсказки.',activity:{id:'l6-q1',type:'choice',prompt:'Сколько отрезков можно провести с концами P и K?',options:['1','2','3','бесконечно много'],answer:'1',explanation:'Две заданные точки определяют единственный отрезок.'}},
  {id:'l6-quiz2',kind:'quiz',eyebrow:'Мини-проверка · 2/5',title:'Свойство длины',body:'Ответь без подсказки.',activity:{id:'l6-q2',type:'input',prompt:'C лежит на AB, AC = 8 см, CB = 5 см. Найди AB в сантиметрах.',answer:'13',explanation:'AB = AC + CB = 8 + 5 = 13 см.'}},
  {id:'l6-quiz3',kind:'quiz',eyebrow:'Мини-проверка · 3/5',title:'Неизвестная часть',body:'Ответь без подсказки.',activity:{id:'l6-q3',type:'input',prompt:'C лежит на AB, AB = 20 см, AC = 12 см. Найди CB в сантиметрах.',answer:'8',explanation:'CB = AB − AC = 20 − 12 = 8 см.'}},
  {id:'l6-quiz4',kind:'quiz',eyebrow:'Мини-проверка · 4/5',title:'Единицы длины',body:'Ответь без подсказки.',activity:{id:'l6-q4',type:'choice',prompt:'Какая длина равна 5 см 4 мм?',options:['45 мм','50 мм','54 мм','504 мм'],answer:'54 мм',explanation:'5 см = 50 мм; 50 + 4 = 54 мм.'}},
  {id:'l6-quiz5',kind:'quiz',eyebrow:'Мини-проверка · 5/5',title:'Два имени одной фигуры',body:'Ответь без подсказки.',activity:{id:'l6-q5',type:'choice',prompt:'Верно ли, что обозначения AB и BA называют один и тот же отрезок?',options:['да','нет'],answer:'да',explanation:'Оба обозначения состоят из тех же двух концов, поэтому называют один отрезок.'}},
  {id:'l6-challenge',kind:'challenge',eyebrow:'Задача со звёздочкой',title:'Две внутренние точки',body:'На отрезке AB длиной 28 см отмечены точки M и K. Точка K лежит между M и B. Известно AM = 12 см и BK = 9 см. Найди MK.',activity:{id:'l6-star',type:'input',prompt:'Чему равна длина MK в сантиметрах?',answer:'7',explanation:'AB = AM + MK + KB, поэтому MK = 28 − 12 − 9 = 7 см.'},sourceTag:'Мерзляк § 3 · упражнение 65'},
  {id:'l6-summary',kind:'summary',eyebrow:'Финиш урока',title:'Теперь отрезок — точный математический объект',body:'Ты умеешь узнавать и обозначать отрезок, понимать смысл измерения, работать с единицами длины, строить отрезок по линейке и применять свойство AB = AC + CB.',note:'Следующие уроки § 3 закрепят измерение и построение отрезков и затем добавят ломаные.'},
];

const empty:Saved={version:1,stageIndex:0,responses:{},orders:{},checked:{},results:{}};
function norm(value:string){return value.trim().toLowerCase().replace(/[\s\u00a0]+/g,'').replace(/ё/g,'е')}
function load():Saved{try{const parsed=JSON.parse(localStorage.getItem(KEY)??'null') as Partial<Saved>|null;return parsed?.version===1?{...empty,...parsed,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonSixStages.length-1),responses:parsed.responses??{},orders:parsed.orders??{},checked:parsed.checked??{},results:parsed.results??{}}:empty}catch{return empty}}

export function SegmentLengthPlayer(){
  const saved=useMemo(load,[]);const[stageIndex,setStageIndex]=useState(saved.stageIndex);const[responses,setResponses]=useState(saved.responses);const[orders,setOrders]=useState(saved.orders);const[checked,setChecked]=useState(saved.checked);const[results,setResults]=useState(saved.results);const[completedAt,setCompletedAt]=useState(saved.completedAt);
  const stage=lessonSixStages[stageIndex];const activity=stage.activity;const answer=activity?responses[activity.id]??'':'';const ordered=activity?orders[activity.id]??[]:[];const isChecked=activity?Boolean(checked[activity.id]):false;const correct=activity?Boolean(results[activity.id]):false;
  const quiz=['l6-q1','l6-q2','l6-q3','l6-q4','l6-q5'];const practice=['l6-p1','l6-p2','l6-p3','l6-p4','l6-p5','l6-p6'];const quizScore=quiz.filter(id=>results[id]).length;const practiceScore=practice.filter(id=>results[id]).length;const progress=Math.round(((stageIndex+1)/lessonSixStages.length)*100);
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify({version:1,stageIndex,responses,orders,checked,results,completedAt})),[stageIndex,responses,orders,checked,results,completedAt]);
  useEffect(()=>{if(stage.kind==='summary'&&!completedAt)setCompletedAt(new Date().toISOString())},[stage.kind,completedAt]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.lessonNumber===6&&Number.isInteger(detail.stageIndex))goTo(detail.stageIndex)};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function goTo(index:number){setStageIndex(Math.min(Math.max(index,0),lessonSixStages.length-1));window.scrollTo({top:0,behavior:'smooth'})}
  function setAnswer(value:string){if(!activity)return;setResponses(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function setOrder(value:string[]){if(!activity)return;setOrders(previous=>({...previous,[activity.id]:value}));setChecked(previous=>({...previous,[activity.id]:false}))}
  function submit(){if(!activity)return;const ok=activity.type==='order'?JSON.stringify(ordered)===JSON.stringify(activity.answer):norm(answer)===norm(String(activity.answer));setChecked(previous=>({...previous,[activity.id]:true}));setResults(previous=>({...previous,[activity.id]:ok}))}
  function reset(){localStorage.removeItem(KEY);setStageIndex(0);setResponses({});setOrders({});setChecked({});setResults({});setCompletedAt(undefined)}
  const model=useMemo(()=>{
    if(['l6-story','l6-segment-definition','l6-unique','l6-name'].includes(stage.id))return <div className="l6-segment-board"><span className="l6-point l6-point-a">A</span><i/><span className="l6-point l6-point-b">B</span><small>единственный отрезок AB</small></div>;
    if(['l6-measure-model','l6-unit','l6-units','l6-ruler-shift'].includes(stage.id))return <div className="l6-ruler"><div>{Array.from({length:9},(_,index)=><span key={index}><i/><b>{index}</b></span>)}</div><em>единичный отрезок</em></div>;
    if(['l6-additivity-model','l6-whole','l6-part','l6-challenge'].includes(stage.id))return <div className="l6-addition-model"><div><span>A</span><i/><span>C</span><i/><span>B</span></div><strong>AB = AC + CB</strong></div>;
    if(['l6-equal-model','l6-equal'].includes(stage.id))return <div className="l6-equal-model"><div><span>A</span><i/><span>B</span></div><div><span>M</span><i/><span>N</span></div><strong>AB = MN</strong></div>;
    return null;
  },[stage.id]);
  function render(current:Activity){
    if(current.type==='choice')return <div className="activity-area"><h3>{current.prompt}</h3><div className="choice-grid">{current.options!.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div><button className="check-button" disabled={!answer} onClick={submit}>Проверить</button></div>;
    if(current.type==='input')return <div className="activity-area"><h3>{current.prompt}</h3><div className="inline-answer"><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&submit()} placeholder={current.placeholder??'Ответ'}/><button className="check-button" disabled={!answer.trim()} onClick={submit}>Проверить</button></div></div>;
    const items=current.items??[];return <div className="activity-area"><h3>{current.prompt}</h3><div className="order-bank">{items.map(item=><button key={item} disabled={ordered.includes(item)} onClick={()=>setOrder([...ordered,item])}>{item}</button>)}</div><div className="order-result">{ordered.map((item,index)=><button key={`${item}-${index}`} onClick={()=>setOrder(ordered.filter((_,position)=>position!==index))}>{index+1}. {item}</button>)}</div><button className="check-button" disabled={ordered.length!==items.length} onClick={submit}>Проверить</button></div>;
  }
  return <main className="lesson-player-page segment-length-page"><section className="lesson-workspace interactive-workspace"><header className="lesson-header"><div><span>Урок 6 из 175 · § 3</span><h1>Отрезок. Длина отрезка</h1><p>Первая геометрическая тема курса: точки и отрезки, измерение и построение длины, равные отрезки и свойство AB = AC + CB.</p></div><div className="lesson-duration">35–40 мин</div></header><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="stage-counter"><span>Этап {stageIndex+1} из {lessonSixStages.length}</span><button type="button" onClick={reset}>Начать заново</button></div><article className={`interactive-stage stage-${stage.kind}`} data-stage-id={stage.id}><div className="stage-copy"><span>{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.sourceTag?<small className="source-tag">Источник: {stage.sourceTag}</small>:null}{stage.note?<div className="theory-note"><b>Запомни</b><span>{stage.note}</span></div>:null}</div>{model}{activity?render(activity):null}{isChecked&&activity?<div className={`instant-feedback ${correct?'good':'bad'}`} data-explanation={activity.explanation}><b>{correct?'Верно!':'Пока не получилось'}</b><span>{correct?activity.explanation:`Проверь концы, единицы длины и расположение точек. ${activity.explanation}`}</span></div>:null}{stage.kind==='quiz'&&isChecked?<div className="quiz-meter"><span>Текущий результат</span><b>{quizScore} из 5</b></div>:null}{stage.kind==='summary'?<div className="summary-card"><div><span>Мини-проверка</span><b>{quizScore}/5</b><small>{quizScore>=4?'Тема усвоена':'Нужно повторение'}</small></div><div><span>Практика</span><b>{practiceScore}/6</b><small>выполнено верно</small></div><div><span>Статус</span><b>{quizScore>=4&&practiceScore>=5?'Завершён':'Повторить'}</b><small>{completedAt?new Date(completedAt).toLocaleDateString('ru-RU'):'сегодня'}</small></div></div>:null}</article><footer className="lesson-controls"><button onClick={()=>goTo(stageIndex-1)} disabled={stageIndex===0}>← Назад</button><span>{progress}% урока</span><button className="primary" onClick={()=>goTo(stageIndex+1)} disabled={stageIndex===lessonSixStages.length-1||Boolean(activity&&!correct)}>Продолжить →</button></footer></section></main>;
}
