import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './trianglePractice.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type Diagram='algorithm'|'obtuse'|'units'|'matrix'|'right'|'scalene'|'perimeter344'|'isosceles'|'equilateral'|'unknown'|'inequality'|'equations';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-47-progress-v1';
const normalized=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[−–—]/g,'-').replace(/\s+/g,'').replace(/(?:СМ|ММ|ДМ)$/,'').replace(/[°.]$/,'');
const answerMatches=(response:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalized(response)===normalized(item))};

export const lessonFortySevenStages:Stage[]=[
  {id:'l47-mission',kind:'story',eyebrow:'Урок 47 · § 14 · закрепление',title:'Из названия — к решению задачи',body:'В прошлом уроке мы составили два паспорта треугольника. Теперь используем их в вычислениях: классифицируем, находим стороны, периметр и проверяем, может ли фигура существовать.',note:'Источник маршрута: учебник Мерзляка, § 14, № 344, 346, 348, 356; методическое пособие, урок 47.',diagram:'algorithm'},
  {id:'l47-algorithm',kind:'model',eyebrow:'Рабочий алгоритм',title:'Три вопроса вместо догадки',body:'Сначала изучи данные об углах, затем сравни стороны в одинаковых единицах, и только после этого выбирай формулу. Такой порядок не даёт смешать два независимых признака.',diagram:'algorithm'},
  {id:'l47-recall-gate',kind:'quiz',eyebrow:'Устный старт',title:'Какой признак отвечает за слово «равнобедренный»?',body:'Определи, к какому из двух паспортов относится термин.',activity:{id:'l47-p1',type:'choice',prompt:'Что нужно сравнить?',options:['Длины сторон','Величины углов','Площадь','Положение на листе'],answer:'Длины сторон',hint:'Вспомни: боковые стороны и основание — элементы какой классификации?',explanation:'Равнобедренный — вид по сторонам: у треугольника есть две равные стороны.'},diagram:'algorithm'},
  {id:'l47-angle-dictation',kind:'practice',eyebrow:'Математический диктант',title:'Углы 40°, 95° и 45°',body:'Сумма углов равна 180°, а один из них больше прямого.',activity:{id:'l47-p2',type:'choice',prompt:'Каков вид треугольника по углам?',options:['Остроугольный','Прямоугольный','Тупоугольный','Равнобедренный'],answer:'Тупоугольный',hint:'Сравни самый большой угол с 90°.',explanation:'95° больше 90°, поэтому треугольник тупоугольный.'},diagram:'obtuse'},
  {id:'l47-unit-conversion',kind:'guided',eyebrow:'До сравнения сторон',title:'Сначала приведи длины к одной единице',body:'Числа 32, 32 и 32 ещё не доказывают равенство: единицы могут различаться. Переводи все длины, например, в сантиметры, и только затем классифицируй.',note:'32 мм = 3,2 см; 3 дм 2 см = 32 см.',diagram:'units'},
  {id:'l47-unit-gate',kind:'practice',eyebrow:'Диктант 12 · единицы',title:'32 мм, 32 см и 3 дм 2 см',body:'После перевода получаются стороны 3,2 см, 32 см и 32 см.',activity:{id:'l47-p3',type:'choice',prompt:'Каков вид треугольника по сторонам?',options:['Разносторонний','Равнобедренный','Равносторонний','Прямоугольный'],answer:'Равнобедренный',hint:'После перевода сравни 3,2; 32; 32.',explanation:'Две стороны по 32 см равны, третья равна 3,2 см: треугольник равнобедренный.'},diagram:'units'},
  {id:'l47-matrix',kind:'model',eyebrow:'Карта классификации',title:'Два ответа образуют один полный паспорт',body:'Строка отвечает за углы, столбец — за стороны. Большинство сочетаний возможно. Равносторонний треугольник всегда остроугольный, поэтому с прямым или тупым углом он несовместим.',diagram:'matrix'},
  {id:'l47-passport-gate',kind:'practice',eyebrow:'Два паспорта',title:'Прямой угол и две равные стороны',body:'Данные отвечают сразу на два независимых вопроса.',activity:{id:'l47-p4',type:'choice',prompt:'Выбери полное описание.',options:['Прямоугольный равнобедренный','Прямоугольный разносторонний','Остроугольный равнобедренный','Тупоугольный равносторонний'],answer:'Прямоугольный равнобедренный',hint:'90° определяет вид по углам; две равные стороны — вид по сторонам.',explanation:'По углам треугольник прямоугольный, по сторонам — равнобедренный.'},diagram:'right'},
  {id:'l47-independence',kind:'challenge',eyebrow:'Причина и следствие',title:'Один признак не заменяет другой',body:'Равенство двух сторон не сообщает, острый, прямой или тупой угол у вершины. Для вида по углам нужны отдельные данные. Хорошее рассуждение не добавляет того, чего нет в условии.',diagram:'matrix'},
  {id:'l47-independence-gate',kind:'quiz',eyebrow:'Логическая проверка',title:'Известно только AB = AC',body:'Отдели гарантированный вывод от догадки.',activity:{id:'l47-p5',type:'choice',prompt:'Что следует обязательно?',options:['Треугольник равнобедренный','Треугольник остроугольный','Треугольник прямоугольный','Треугольник тупоугольный'],answer:'Треугольник равнобедренный',hint:'Равенство AB и AC относится только к длинам сторон.',explanation:'Можно гарантировать лишь равнобедренность. Вид по углам без дополнительных данных неизвестен.'},diagram:'isosceles'},
  {id:'l47-perimeter-plan',kind:'model',eyebrow:'Задачи на периметр',title:'Подпиши три стороны до вычисления',body:'Периметр треугольника — сумма трёх сторон: P=a+b+c. Если сторона описана словами «на 18 см больше» или «в 2 раза меньше», сначала найди её, затем сложи все три длины.',diagram:'perimeter344'},
  {id:'l47-textbook344-step1',kind:'practice',eyebrow:'Учебник № 344 · шаг 1',title:'Первая сторона 24 см, вторая на 18 см больше',body:'Слово «на» указывает на сложение.',activity:{id:'l47-p6',type:'input',prompt:'Найди вторую сторону, см.',answer:'42',placeholder:'24 + 18',hint:'24+18.',explanation:'Вторая сторона: 24+18=42 см.'},diagram:'perimeter344'},
  {id:'l47-textbook344-step2',kind:'practice',eyebrow:'Учебник № 344 · шаг 2',title:'Третья сторона в 2 раза меньше второй',body:'Вторая сторона уже найдена: 42 см.',activity:{id:'l47-p7',type:'input',prompt:'Найди третью сторону, см.',answer:'21',placeholder:'42 : 2',hint:'Раздели 42 на 2.',explanation:'Третья сторона: 42:2=21 см.'},diagram:'perimeter344'},
  {id:'l47-textbook344-answer',kind:'practice',eyebrow:'Учебник № 344 · ответ',title:'Стороны 24 см, 42 см и 21 см',body:'Теперь все три длины известны.',activity:{id:'l47-p8',type:'input',prompt:'Найди периметр, см.',answer:'87',placeholder:'P',hint:'24+42+21.',explanation:'P=24+42+21=87 см. Обратная проверка: 87−24−42=21.'},diagram:'perimeter344'},
  {id:'l47-isosceles-model',kind:'guided',eyebrow:'Равнобедренный треугольник',title:'Две боковые стороны входят в сумму дважды',body:'Если боковая сторона равна a, а основание b, то P=2a+b. В обратной задаче a=(P−b):2, а основание b=P−2a.',diagram:'isosceles'},
  {id:'l47-textbook346a',kind:'practice',eyebrow:'Учебник № 346 · 1',title:'Основание 13 см, боковая сторона 8 см',body:'Вторая боковая сторона тоже равна 8 см.',activity:{id:'l47-p9',type:'input',prompt:'Найди периметр, см.',answer:'29',placeholder:'P',hint:'8+8+13.',explanation:'P=2·8+13=29 см.'},diagram:'isosceles'},
  {id:'l47-textbook346b-plan',kind:'guided',eyebrow:'Обратная задача',title:'Из периметра — к каждой боковой стороне',body:'Вычти основание из периметра. Полученный остаток — сумма двух одинаковых боковых сторон, поэтому раздели его на 2.',note:'Проверка: найденная сторона должна дважды войти в исходный периметр.',diagram:'isosceles'},
  {id:'l47-textbook346b',kind:'practice',eyebrow:'Учебник № 346 · 2',title:'Периметр 39 см, основание 15 см',body:'Две боковые стороны равны.',activity:{id:'l47-p10',type:'input',prompt:'Найди боковую сторону, см.',answer:'12',placeholder:'(39 − 15) : 2',hint:'39−15=24; теперь раздели 24 пополам.',explanation:'(39−15):2=12 см. Проверка: 12+12+15=39.'},diagram:'isosceles'},
  {id:'l47-equilateral-model',kind:'model',eyebrow:'Равносторонний треугольник',title:'Одна сторона определяет весь периметр',body:'Все три стороны равны, поэтому P=3a. Обратно: a=P:3. Если в условии сравнивают периметр со стороной, помни, что разность P−a равна двум сторонам.',diagram:'equilateral'},
  {id:'l47-equilateral-difference-side',kind:'practice',eyebrow:'Диктант 12 · равносторонний',title:'Периметр на 26 см больше стороны',body:'Для равностороннего треугольника 3a=a+26, значит 2a=26.',activity:{id:'l47-p11',type:'input',prompt:'Найди сторону, см.',answer:'13',placeholder:'a',hint:'Разность между тремя сторонами и одной стороной — это 2a.',explanation:'2a=26, поэтому a=13 см.'},diagram:'equilateral'},
  {id:'l47-equilateral-difference-perimeter',kind:'practice',eyebrow:'Диктант 12 · проверка',title:'Сторона уже найдена: 13 см',body:'У равностороннего треугольника три такие стороны.',activity:{id:'l47-p12',type:'input',prompt:'Найди периметр, см.',answer:'39',placeholder:'P',hint:'13·3.',explanation:'P=3·13=39 см; 39 действительно на 26 см больше 13.'},diagram:'equilateral'},
  {id:'l47-third-side-model',kind:'model',eyebrow:'Неизвестная третья сторона',title:'Из суммы вычти две известные части',body:'Если периметр p, а две стороны равны a и b, то третья сторона c=p−a−b. После вычисления сложи три стороны и восстанови исходный периметр.',diagram:'unknown'},
  {id:'l47-textbook348-expression',kind:'practice',eyebrow:'Учебник № 348 · выражение',title:'Периметр p, стороны 22 см и b см',body:'Нужно записать длину третьей стороны.',activity:{id:'l47-p13',type:'choice',prompt:'Какое выражение верно?',options:['p−22−b','p+22+b','22+b−p','(p−22)·b'],answer:'p−22−b',hint:'Из целого периметра убери обе известные стороны.',explanation:'Третья сторона равна p−22−b.'},diagram:'unknown'},
  {id:'l47-textbook348-value',kind:'practice',eyebrow:'Учебник № 348 · значение',title:'p=72, b=26',body:'Подставь значения в выражение p−22−b.',activity:{id:'l47-p14',type:'input',prompt:'Найди третью сторону, см.',answer:'24',placeholder:'72 − 22 − 26',hint:'72−22=50; 50−26.',explanation:'72−22−26=24 см. Проверка: 22+26+24=72.'},diagram:'unknown'},
  {id:'l47-inequality-model',kind:'guided',eyebrow:'Проверка существования',title:'Две стороны вместе длиннее третьей',body:'После вычисления проверь здравый смысл: сумма любых двух сторон треугольника должна быть больше третьей. Равенства недостаточно — фигура «сложится» в отрезок.',diagram:'inequality'},
  {id:'l47-inequality-gate',kind:'quiz',eyebrow:'Логический контроль',title:'Стороны 2 см, 3 см и 6 см',body:'Сравни сумму двух меньших сторон с наибольшей.',activity:{id:'l47-p15',type:'choice',prompt:'Можно ли построить такой треугольник?',options:['Нет, потому что 2+3<6','Да, любой набор подходит','Да, потому что 6 — наибольшая','Нет, потому что стороны разные'],answer:'Нет, потому что 2+3<6',hint:'Проверь неравенство для двух меньших сторон.',explanation:'2+3=5<6, поэтому стороны не замыкаются в треугольник.'},diagram:'inequality'},
  {id:'l47-equations-model',kind:'model',eyebrow:'Повторение · № 356',title:'Уравнение — тоже задача на неизвестную часть',body:'Определи неизвестный компонент, выполни обратное действие и обязательно подставь найденное число в исходное равенство.',diagram:'equations'},
  {id:'l47-textbook356a',kind:'practice',eyebrow:'Учебник № 356 · 1',title:'429 + m = 2106',body:'Неизвестное слагаемое находят вычитанием.',activity:{id:'l47-p16',type:'input',prompt:'Найди m.',answer:'1677',placeholder:'m',hint:'2106−429.',explanation:'m=1677. Проверка: 429+1677=2106.'},diagram:'equations'},
  {id:'l47-textbook356b',kind:'practice',eyebrow:'Учебник № 356 · 2',title:'348 − k = 154',body:'Неизвестное вычитаемое равно уменьшаемому минус разность.',activity:{id:'l47-p17',type:'input',prompt:'Найди k.',answer:'194',placeholder:'k',hint:'348−154.',explanation:'k=194. Проверка: 348−194=154.'},diagram:'equations'},
  {id:'l47-textbook356c',kind:'practice',eyebrow:'Учебник № 356 · 3',title:'(m + 326) − 569 = 674',body:'Сначала восстанови выражение в скобках, затем найди m.',activity:{id:'l47-p18',type:'input',prompt:'Найди m.',answer:'917',placeholder:'m',hint:'m+326=674+569; затем вычти 326.',explanation:'m+326=1243, поэтому m=917. Проверка: 1243−569=674.'},diagram:'equations'},
  {id:'l47-textbook356d',kind:'practice',eyebrow:'Учебник № 356 · 4',title:'5084 − (k − 299) = 568',body:'Сначала найди значение скобок как неизвестное вычитаемое.',activity:{id:'l47-p19',type:'input',prompt:'Найди k.',answer:'4815',placeholder:'k',hint:'k−299=5084−568; затем прибавь 299.',explanation:'k−299=4516, поэтому k=4815. Проверка: 5084−4516=568.'},diagram:'equations'},
  {id:'l47-control-passport',kind:'quiz',eyebrow:'Мини-контроль · 1/4',title:'Все углы острые; стороны 5 см, 6 см и 7 см',body:'Дай полный паспорт, используя обе классификации.',activity:{id:'l47-p20',type:'choice',prompt:'Какое описание верно?',options:['Остроугольный разносторонний','Остроугольный равнобедренный','Тупоугольный разносторонний','Прямоугольный разносторонний'],answer:'Остроугольный разносторонний',hint:'Все углы меньше 90°; все стороны различны.',explanation:'Треугольник остроугольный по углам и разносторонний по сторонам.'},diagram:'scalene'},
  {id:'l47-control-third-side',kind:'quiz',eyebrow:'Мини-контроль · 2/4',title:'Две стороны 9 см и 12 см, периметр 30 см',body:'Найди недостающую сторону вычитанием двух известных.',activity:{id:'l47-p21',type:'input',prompt:'Чему равна третья сторона, см?',answer:'9',placeholder:'30 − 9 − 12',hint:'30−9−12.',explanation:'Третья сторона равна 9 см; проверка: 9+12+9=30.'},diagram:'unknown'},
  {id:'l47-control-type',kind:'quiz',eyebrow:'Мини-контроль · 3/4',title:'Стороны 9 см, 12 см и 9 см',body:'Используй найденный результат предыдущего шага.',activity:{id:'l47-p22',type:'choice',prompt:'Каков вид по сторонам?',options:['Равнобедренный','Равносторонний','Разносторонний','Прямоугольный'],answer:'Равнобедренный',hint:'Сравни первую и третью стороны.',explanation:'Две стороны по 9 см равны, значит треугольник равнобедренный.'},diagram:'isosceles'},
  {id:'l47-final-gate',kind:'challenge',eyebrow:'Мини-контроль · 4/4',title:'Периметр 44 см, боковые стороны по 15 см',body:'Для основания используй b=P−2a.',activity:{id:'l47-p23',type:'input',prompt:'Найди основание, см.',answer:'14',placeholder:'b',hint:'44−15−15.',explanation:'Основание равно 14 см. Проверка: 15+15+14=44; 15+14>15, треугольник существует.'},diagram:'isosceles'},
  {id:'l47-summary',kind:'summary',eyebrow:'Итог урока 47',title:'Данные → два паспорта → формула → проверка',body:'Ты закрепил классификацию по углам и сторонам, научился приводить единицы, решать прямые и обратные задачи для равнобедренного и равностороннего треугольников, составлять выражение для третьей стороны и проверять ответ.',note:'Домашняя работа по маршруту методического пособия: § 14, № 345, 347, 349. Дальше — обязательная мастерская из 20 задач.',diagram:'algorithm'}
];

function TrianglePracticeDiagram({kind}:{kind:Diagram}){
  if(kind==='algorithm')return <div className="triangle-practice-diagram" data-diagram="algorithm"><div className="triangle-practice-steps"><span><b>1</b>Углы</span><span><b>2</b>Стороны и единицы</span><span><b>3</b>Формула и проверка</span></div></div>;
  if(kind==='matrix')return <div className="triangle-practice-diagram" data-diagram="matrix"><div className="triangle-practice-matrix"><span>остроугольный<br/>разносторонний</span><span>остроугольный<br/>равнобедренный</span><span>остроугольный<br/>равносторонний</span><span>прямоугольный<br/>разносторонний</span><span>прямоугольный<br/>равнобедренный</span><span data-possible="false">прямоугольный<br/>равносторонний</span><span>тупоугольный<br/>разносторонний</span><span>тупоугольный<br/>равнобедренный</span><span data-possible="false">тупоугольный<br/>равносторонний</span></div></div>;
  if(kind==='units')return <div className="triangle-practice-diagram" data-diagram="unit-conversion"><div className="triangle-practice-measures"><div><span>32 мм</span><strong>= 3,2 см</strong></div><div><span>32 см</span><strong>= 32 см</strong></div><div><span>3 дм 2 см</span><strong>= 32 см</strong></div></div></div>;
  if(kind==='unknown')return <div className="triangle-practice-diagram" data-diagram="unknown-side"><div className="triangle-practice-formulas"><span><b>c = p − a − b</b></span><span>Проверка: <b>a + b + c = p</b></span></div></div>;
  if(kind==='inequality')return <div className="triangle-practice-diagram" data-diagram="triangle-inequality"><div className="triangle-practice-verdict"><span>2 + 3 = 5</span><b>&lt;</b><span>6</span><strong>треугольник не замкнётся</strong></div></div>;
  if(kind==='equations')return <div className="triangle-practice-diagram" data-diagram="equations"><div className="triangle-practice-formulas triangle-practice-equation"><span><b>неизвестный компонент</b> → обратное действие</span><span><b>корень</b> → подстановка → верное равенство</span></div></div>;
  const config=kind==='obtuse'?{points:'60,240 180,60 520,240',angle:'obtuse',side:'scalene',values:['40°','95°','45°']}:kind==='right'?{points:'140,240 140,70 310,240',angle:'right',side:'isosceles',values:['90°','','']}:kind==='perimeter344'?{points:'80,230 283,157 458,230',angle:'obtuse',side:'scalene',values:['24 см','21 см','42 см']}:kind==='isosceles'?{points:'105,235 300,95 495,235',angle:'acute',side:'isosceles',values:['8 см','8 см','13 см']}:kind==='equilateral'?{points:'165,245 300,11 435,245',angle:'acute',side:'equilateral',values:['a','a','a']}:{points:'80,240 300,30 500,240',angle:'acute',side:'scalene',values:['5 см','7 см','6 см']};
  return <div className="triangle-practice-diagram" data-diagram={kind} data-angle-type={config.angle} data-side-type={config.side} data-side-values={config.values.join('|')}><svg viewBox="0 0 600 285" role="img" aria-label={`Треугольник: ${config.angle}, ${config.side}`}><polygon className="triangle-practice-shape" points={config.points}/><text className="triangle-practice-label" x="52" y="267">A</text><text className="triangle-practice-label" x="292" y="25">B</text><text className="triangle-practice-label" x="510" y="267">C</text><text className="triangle-practice-value" x="150" y="133">{config.values[0]}</text><text className="triangle-practice-value" x="390" y="133">{config.values[1]}</text><text className="triangle-practice-value" x="270" y="267">{config.values[2]}</text>{kind==='right'?<path className="triangle-practice-mark" data-right-angle-marker="true" d="M140 215 L165 215 L165 240"/>:null}{kind==='isosceles'||kind==='right'?<><path className="triangle-practice-mark" data-equal-side-mark="1" d={kind==='right'?'M129 150 L151 150':'M190 146 L204 162'}/><path className="triangle-practice-mark" data-equal-side-mark="2" d={kind==='right'?'M225 229 L225 251':'M396 162 L410 146'}/></>:null}{kind==='equilateral'?<><path className="triangle-practice-mark" data-equal-side-mark="1" d="M220 139 L238 149"/><path className="triangle-practice-mark" data-equal-side-mark="2" d="M362 149 L380 139"/><path className="triangle-practice-mark" data-equal-side-mark="3" d="M300 234 L300 256"/></>:null}</svg></div>;
}

function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortySevenStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function TrianglePracticePlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFortySevenStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFortySevenStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==47||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFortySevenStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFortySevenStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player triangle-practice-player" data-lesson-number="47" data-source-reference="Мерзляк §14 · урок 47"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<TrianglePracticeDiagram kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} Можно перейти дальше и вернуться к заданию позже.`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFortySevenStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFortySevenStages.length-1||!canContinue}>{saved.stageIndex===lessonFortySevenStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
