import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './triangleTypes.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string;explanation:string;hint:string;placeholder?:string};
type Diagram='anatomy'|'acute'|'right'|'obtuse'|'scalene'|'isosceles'|'equilateral'|'matrix'|'perimeter';
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-46-progress-v1';
const normalize=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/\s+/g,'').replace(/Ё/g,'Е');

export const lessonFortySixStages:Stage[]=[
{id:'l46-mission',kind:'story',eyebrow:'Урок 46 · § 14 · новая тема',title:'У треугольника два паспорта',body:'Треугольник можно классифицировать независимо по углам и по сторонам. Поэтому одного названия часто недостаточно: например, фигура может быть одновременно прямоугольной и равнобедренной.',note:'Маршрут: углы → стороны → два признака вместе → периметр → проверка.',diagram:'anatomy'},
{id:'l46-anatomy',kind:'model',eyebrow:'Что уже знакомо',title:'Три вершины, три стороны, три угла',body:'Треугольник ABC имеет вершины A, B, C; стороны AB, BC, CA и три угла при этих вершинах. Вид треугольника определяют свойства именно этих элементов.',diagram:'anatomy'},
{id:'l46-angle-axis',kind:'model',eyebrow:'Классификация № 1',title:'Сначала смотрим на углы',body:'По углам треугольники делятся на остроугольные, прямоугольные и тупоугольные. Здесь длины сторон не определяют название: нужно проверить углы.',diagram:'acute'},
{id:'l46-acute-model',kind:'model',eyebrow:'По углам · остроугольный',title:'Все три угла острые',body:'Если каждый из трёх углов меньше 90°, треугольник называется остроугольным. Недостаточно проверить только один или два угла.',diagram:'acute'},
{id:'l46-practice1',kind:'practice',eyebrow:'Проверка · углы',title:'Три острых угла',body:'У фигуры углы 55°, 60° и 65°.',activity:{id:'l46-p1',type:'choice',prompt:'Каков вид треугольника по углам?',options:['Остроугольный','Прямоугольный','Тупоугольный','Равнобедренный'],answer:'Остроугольный',hint:'Сравни каждый угол с 90°.',explanation:'Все три угла меньше 90°, поэтому треугольник остроугольный.'},diagram:'acute'},
{id:'l46-right-model',kind:'model',eyebrow:'По углам · прямоугольный',title:'Есть угол 90°',body:'Если в треугольнике есть прямой угол, то он прямоугольный. На чертеже прямой угол часто отмечают маленьким квадратом.',diagram:'right'},
{id:'l46-practice2',kind:'practice',eyebrow:'Проверка · прямой угол',title:'Маркер 90°',body:'На рисунке при вершине A стоит квадратный маркер.',activity:{id:'l46-p2',type:'choice',prompt:'Каков вид по углам?',options:['Остроугольный','Прямоугольный','Тупоугольный','Равносторонний'],answer:'Прямоугольный',hint:'Квадратный маркер обозначает 90°.',explanation:'Наличие угла 90° означает, что треугольник прямоугольный.'},diagram:'right'},
{id:'l46-obtuse-model',kind:'model',eyebrow:'По углам · тупоугольный',title:'Есть угол больше 90°',body:'Если один угол треугольника тупой, то есть больше 90°, треугольник называется тупоугольным.',diagram:'obtuse'},
{id:'l46-practice3',kind:'practice',eyebrow:'Проверка · тупой угол',title:'Один угол раскрыт шире прямого',body:'Угол B равен 112°.',activity:{id:'l46-p3',type:'choice',prompt:'Каков вид по углам?',options:['Остроугольный','Прямоугольный','Тупоугольный','Разносторонний'],answer:'Тупоугольный',hint:'112° больше 90°.',explanation:'Треугольник с тупым углом является тупоугольным.'},diagram:'obtuse'},
{id:'l46-boundaries',kind:'quiz',eyebrow:'Граница категорий',title:'89°, 90°, 91° — три разных сигнала',body:'89° — острый угол, 90° — прямой, 91° — уже тупой. В классификации важна точная граница, а не впечатление от рисунка.',activity:{id:'l46-p-boundary',type:'choice',prompt:'Если один угол равен ровно 90°, какой термин обязателен?',options:['Остроугольный','Прямоугольный','Тупоугольный','Разносторонний'],answer:'Прямоугольный',hint:'90° — точное определение прямого угла.',explanation:'Ровно 90° означает прямоугольный треугольник.'},diagram:'right'},
{id:'l46-side-axis',kind:'model',eyebrow:'Классификация № 2',title:'Теперь забываем углы и сравниваем стороны',body:'По сторонам различают разносторонние, равнобедренные и равносторонние треугольники. Эта классификация независима от первой.',diagram:'scalene'},
{id:'l46-scalene-model',kind:'model',eyebrow:'По сторонам · разносторонний',title:'Все три стороны различны',body:'Если длины всех трёх сторон разные, треугольник разносторонний. На рисунке это подтверждают измерением или заданными длинами.',diagram:'scalene'},
{id:'l46-practice4',kind:'practice',eyebrow:'Сравнение сторон',title:'5 см, 7 см, 8 см',body:'Все три длины различаются.',activity:{id:'l46-p4',type:'choice',prompt:'Каков вид по сторонам?',options:['Разносторонний','Равнобедренный','Равносторонний','Прямоугольный'],answer:'Разносторонний',hint:'Посчитай, сколько пар равных сторон.',explanation:'Равных сторон нет, значит треугольник разносторонний.'},diagram:'scalene'},
{id:'l46-isosceles-model',kind:'model',eyebrow:'По сторонам · равнобедренный',title:'Две стороны равны',body:'Треугольник с двумя равными сторонами называется равнобедренным. На схеме одинаковые штрихи на сторонах показывают их равенство.',diagram:'isosceles'},
{id:'l46-base-model',kind:'guided',eyebrow:'Элементы равнобедренного',title:'Боковые стороны и основание',body:'Две равные стороны называют боковыми. Третью сторону называют основанием. Если AB=AC, то AB и AC — боковые стороны, BC — основание.',diagram:'isosceles'},
{id:'l46-practice5',kind:'practice',eyebrow:'Основание',title:'AB = AC',body:'Равные стороны сходятся в вершине A.',activity:{id:'l46-p5',type:'choice',prompt:'Какая сторона является основанием?',options:['AB','AC','BC','Нельзя определить'],answer:'BC',hint:'Основание — третья, неравная сторона.',explanation:'При AB=AC основанием является BC.'},diagram:'isosceles'},
{id:'l46-equilateral-model',kind:'model',eyebrow:'По сторонам · равносторонний',title:'Все три стороны равны',body:'Если равны все три стороны, треугольник равносторонний. В учебнике также используется название «правильный треугольник».',diagram:'equilateral'},
{id:'l46-practice6',kind:'practice',eyebrow:'Три равные стороны',title:'6 см, 6 см, 6 см',body:'Равенство видно сразу из данных.',activity:{id:'l46-p6',type:'choice',prompt:'Каков наиболее точный вид по сторонам?',options:['Разносторонний','Равнобедренный','Равносторонний','Остроугольный'],answer:'Равносторонний',hint:'Сравни все три длины.',explanation:'Все три стороны равны — треугольник равносторонний.'},diagram:'equilateral'},
{id:'l46-inclusion',kind:'guided',eyebrow:'Логика определения',title:'Равносторонний — частный случай равнобедренного',body:'Определение равнобедренного требует наличия двух равных сторон. У равностороннего равны все три, значит условие «две равны» тоже выполнено.',note:'Но когда просят наиболее точный вид по сторонам, говорим «равносторонний».',diagram:'equilateral'},
{id:'l46-practice7',kind:'quiz',eyebrow:'Логическое утверждение',title:'Проверяем включение',body:'Смотрим не на картинку, а на определения.',activity:{id:'l46-p7',type:'choice',prompt:'Верно ли: каждый равносторонний треугольник равнобедренный?',options:['Да','Нет'],answer:'Да',hint:'У равностороннего точно есть хотя бы две равные стороны.',explanation:'Да. Равносторонний удовлетворяет определению равнобедренного.'},diagram:'equilateral'},
{id:'l46-matrix',kind:'model',eyebrow:'Главная идея урока',title:'Две оси классификации работают одновременно',body:'Первое слово отвечает на вопрос об углах, второе — о сторонах. Например: «прямоугольный равнобедренный» или «тупоугольный разносторонний».',diagram:'matrix'},
{id:'l46-practice8',kind:'practice',eyebrow:'Два паспорта',title:'Прямой угол + две равные стороны',body:'У треугольника есть угол 90°, а две его стороны равны.',activity:{id:'l46-p8',type:'choice',prompt:'Какое полное описание верно?',options:['Прямоугольный равнобедренный','Прямоугольный разносторонний','Остроугольный равнобедренный','Тупоугольный равносторонний'],answer:'Прямоугольный равнобедренный',hint:'Назови отдельно тип по углам и по сторонам.',explanation:'По углам — прямоугольный, по сторонам — равнобедренный.'},diagram:'right'},
{id:'l46-practice9',kind:'practice',eyebrow:'Два паспорта',title:'Тупой угол + три разные стороны',body:'Один угол равен 105°, стороны имеют три разные длины.',activity:{id:'l46-p9',type:'choice',prompt:'Полное описание?',options:['Тупоугольный разносторонний','Тупоугольный равнобедренный','Прямоугольный разносторонний','Остроугольный разносторонний'],answer:'Тупоугольный разносторонний',hint:'105° задаёт тип по углам; разные длины — тип по сторонам.',explanation:'Треугольник тупоугольный и разносторонний.'},diagram:'obtuse'},
{id:'l46-practice10',kind:'practice',eyebrow:'Два паспорта',title:'Все углы острые + две стороны равны',body:'У треугольника нет прямого или тупого угла, а две стороны отмечены одинаковыми штрихами.',activity:{id:'l46-p10',type:'choice',prompt:'Какое описание подходит?',options:['Остроугольный равнобедренный','Прямоугольный равнобедренный','Остроугольный разносторонний','Тупоугольный равносторонний'],answer:'Остроугольный равнобедренный',hint:'Сначала углы, потом стороны.',explanation:'Все углы острые; две стороны равны.'},diagram:'isosceles'},
{id:'l46-impossible',kind:'challenge',eyebrow:'Проверка здравого смысла',title:'Не смешивай признаки',body:'Фраза «две стороны равны, значит треугольник остроугольный» неверна. Равенство сторон говорит только о классификации по сторонам; вид по углам надо определять отдельно.',diagram:'matrix'},
{id:'l46-practice11',kind:'practice',eyebrow:'Диагностика ошибки',title:'Какой вывод лишний?',body:'Известно только, что AB=AC.',activity:{id:'l46-p11',type:'choice',prompt:'Что можно утверждать наверняка?',options:['Треугольник равнобедренный','Треугольник обязательно остроугольный','Треугольник обязательно прямоугольный','Треугольник обязательно тупоугольный'],answer:'Треугольник равнобедренный',hint:'Данные касаются только сторон.',explanation:'Равенство двух сторон гарантирует равнобедренность, но не определяет тип углов.'},diagram:'isosceles'},
{id:'l46-textbook338',kind:'guided',eyebrow:'По мотивам № 338',title:'Рисунок нужно проверять измерением',body:'В задании учебника предлагается определить виды треугольников по рисунку, измеряя стороны и углы. Вывод: внешний вид — гипотеза, а измерение — доказательство классификации.',note:'Порядок: измерь углы → классифицируй; измерь стороны → классифицируй второй раз.',diagram:'matrix'},
{id:'l46-textbook339',kind:'practice',eyebrow:'По мотивам № 339',title:'Выбери достаточные данные',body:'Нужно уверенно определить оба вида.',activity:{id:'l46-p339',type:'choice',prompt:'Какие данные достаточны для двух классификаций?',options:['Все нужные углы и длины сторон','Только цвет фигуры','Только положение на странице','Только название одной вершины'],answer:'Все нужные углы и длины сторон',hint:'Одна классификация опирается на углы, другая на стороны.',explanation:'Для полной классификации проверяют и угловые, и линейные данные.'},diagram:'matrix'},
{id:'l46-perimeter-model',kind:'model',eyebrow:'Задачи § 14',title:'Периметр треугольника',body:'Периметр — сумма трёх сторон: P=a+b+c. Для равнобедренного удобно использовать P=2a+b, где a — боковая сторона, b — основание.',diagram:'perimeter'},
{id:'l46-practice12',kind:'practice',eyebrow:'По мотивам № 341',title:'Две равные стороны по 9 см, основание 6 см',body:'Используй структуру равнобедренного треугольника.',activity:{id:'l46-p12',type:'input',prompt:'Найди периметр, см.',answer:'24',placeholder:'P',hint:'9+9+6.',explanation:'P=9+9+6=24 см.'},diagram:'perimeter'},
{id:'l46-unknown-side',kind:'guided',eyebrow:'Обратная задача',title:'Из периметра к стороне',body:'Если известен периметр равнобедренного треугольника и основание, сначала вычитаем основание. Остаток — сумма двух равных боковых сторон, поэтому делим его на 2.',diagram:'perimeter'},
{id:'l46-practice13',kind:'practice',eyebrow:'По мотивам № 343',title:'P=34 см, основание 12 см',body:'Две боковые стороны равны.',activity:{id:'l46-p13',type:'input',prompt:'Найди длину боковой стороны, см.',answer:'11',placeholder:'Сторона',hint:'(34−12):2.',explanation:'34−12=22; 22:2=11 см.'},diagram:'perimeter'},
{id:'l46-error-analysis',kind:'challenge',eyebrow:'Контроль рассуждения',title:'Название должно отвечать на свой вопрос',body:'«Равнобедренный» ничего само по себе не говорит о наличии прямого или тупого угла. «Прямоугольный» ничего само по себе не говорит о равенстве сторон. Всегда спрашивай: какой признак сейчас классифицирую?',diagram:'matrix'},
{id:'l46-mixed-gate',kind:'challenge',eyebrow:'Смешанная задача',title:'Один угол 90°, стороны 10, 10 и 14 см',body:'Нужно одновременно увидеть две классификации и вычислительный факт.',activity:{id:'l46-p14',type:'input',prompt:'Найди периметр этого прямоугольного равнобедренного треугольника, см.',answer:'34',placeholder:'P',hint:'Сложи 10+10+14.',explanation:'По углам треугольник прямоугольный, по сторонам равнобедренный; P=34 см.'},diagram:'right'},
{id:'l46-passport',kind:'quiz',eyebrow:'Mastery gate',title:'Полный паспорт за один шаг',body:'У треугольника один угол тупой; стороны равны 5 см, 6 см и 8 см.',activity:{id:'l46-p15',type:'choice',prompt:'Какое полное описание верно?',options:['Тупоугольный разносторонний','Тупоугольный равнобедренный','Остроугольный разносторонний','Прямоугольный разносторонний'],answer:'Тупоугольный разносторонний',hint:'Раздели задачу на два независимых вопроса.',explanation:'Тупой угол даёт первое название, три разные стороны — второе.'},diagram:'obtuse'},
{id:'l46-summary',kind:'summary',eyebrow:'Итог урока 46',title:'Треугольник читается по двум независимым признакам',body:'По углам: остроугольный, прямоугольный, тупоугольный. По сторонам: разносторонний, равнобедренный, равносторонний. Сильное решение не угадывает по виду, а проверяет данные, даёт два названия и затем использует свойства в задачах.',note:'Дальше — обязательная практика: 20 задач на классификацию, логику и периметр.',diagram:'matrix'}
];

function TriangleDiagram({kind}:{kind:Diagram}){
  const config=kind==='right'?{points:'120,240 120,70 290,240',angle:'right',side:'isosceles'}:kind==='obtuse'?{points:'55,235 230,70 525,235',angle:'obtuse',side:'scalene'}:kind==='isosceles'?{points:'80,235 300,55 520,235',angle:'acute',side:'isosceles'}:kind==='equilateral'?{points:'170,245 300,20 430,245',angle:'acute',side:'equilateral'}:kind==='scalene'?{points:'100,240 280,30 500,240',angle:'acute',side:'scalene'}:{points:'100,240 280,30 500,240',angle:'acute',side:'scalene'};
  if(kind==='matrix')return <div className="triangle-lesson-diagram" data-diagram="triangle-matrix"><div className="triangle-matrix"><span>по углам: остроугольный</span><span>по углам: прямоугольный</span><span>по углам: тупоугольный</span><span>по сторонам: разносторонний</span><span>по сторонам: равнобедренный</span><span>по сторонам: равносторонний</span></div></div>;
  if(kind==='perimeter')return <div className="triangle-lesson-diagram" data-diagram="perimeter"><div className="triangle-passport"><span>P=a+b+c</span><span>равнобедренный: P=2a+b</span></div></div>;
  const labels=kind==='right'?{a:[92,265],b:[92,62],c:[300,265]}:kind==='equilateral'?{a:[145,270],b:[292,18],c:[440,270]}:kind==='obtuse'?{a:[30,265],b:[220,60],c:[535,265]}:{a:[55,265],b:[275,45],c:[525,265]};
  return <div className="triangle-lesson-diagram" data-diagram={kind} data-angle-type={config.angle} data-side-type={config.side}><svg viewBox="0 0 600 290" role="img" aria-label={`Треугольник: ${config.angle}, ${config.side}`}><polygon className="triangle-shape" points={config.points}/><text className="triangle-label" x={labels.a[0]} y={labels.a[1]}>A</text><text className="triangle-label" x={labels.b[0]} y={labels.b[1]}>B</text><text className="triangle-label" x={labels.c[0]} y={labels.c[1]}>C</text>{kind==='right'?<path className="right-angle-marker" data-right-angle-marker="true" d="M120 215 L145 215 L145 240"/>:null}{kind==='isosceles'||kind==='right'?<><path className="triangle-side-mark" data-equal-side-mark="1" d={kind==='right'?'M109 150 L131 150':'M180 135 L193 151'}/><path className="triangle-side-mark" data-equal-side-mark="2" d={kind==='right'?'M205 229 L205 251':'M407 151 L420 135'}/></>:null}{kind==='equilateral'?<><path className="triangle-side-mark" data-equal-side-mark="1" d="M220 137 L238 147"/><path className="triangle-side-mark" data-equal-side-mark="2" d="M362 147 L380 137"/><path className="triangle-side-mark" data-equal-side-mark="3" d="M300 234 L300 256"/></>:null}</svg></div>
}

function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return{version:1,stageIndex:0,responses:{},checked:{},results:{}};const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortySixStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{}}}catch{return{version:1,stageIndex:0,responses:{},checked:{},results:{}}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function TriangleTypesPlayer(){
 const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFortySixStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;
 const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFortySixStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==46||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFortySixStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=normalize(response)===normalize(activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct}}))}
 function next(){if(activity&&!isCorrect)return;if(saved.stageIndex>=lessonFortySixStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player triangle-types-player" data-lesson-number="46"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<TriangleDiagram kind={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFortySixStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFortySixStages.length-1||(Boolean(activity)&&!isCorrect)}>{saved.stageIndex===lessonFortySixStages.length-1?'Итог':'Дальше'}</button></div></article></section>
}
