import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './additionProperties.css';
import './triangleConstruction.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type ConstructionDiagram=
  |{type:'construction';method:'sas';step:1|2|3;sides:[number,number];angleA:number;sideLabels?:[string,string];vertexLabels?:[string,string,string];displayAngles?:number[];classification?:string;protractor?:'A';reflection?:boolean}
  |{type:'construction';method:'asa';step:1|2|3|4;base:number;angleA:number;angleB:number;baseLabel?:string;vertexLabels?:[string,string,string];classification?:string;protractor?:'A'|'B'};
type PanelKind='toolkit'|'sas-sequence'|'asa-sequence'|'uniqueness'|'feasibility'|'methods'|'points'|'checklist'|'errors'|'digits'|'final';
type Diagram=ConstructionDiagram|{type:'panel';kind:PanelKind};
type Stage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;diagram?:Diagram};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};
type Point={x:number;y:number};

const KEY='mathnikita-lesson-48-progress-v1';
const normalized=(value:string)=>value.trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[−–—]/g,'-').replace(/\s+/g,'').replace(/(?:СМ|ММ|°|[.])$/,'');
const answerMatches=(response:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>normalized(response)===normalized(item))};

export const lessonFortyEightStages:Stage[]=[
  {id:'l48-mission',kind:'story',eyebrow:'Урок 48 · § 14 · новая конструкция',title:'Из чисел — в точный треугольник',body:'Сегодня условие станет чертежом. Мы освоим два маршрута: по двум сторонам и углу между ними, а затем по одной стороне и двум прилежащим к ней углам.',note:'Источник маршрута: примеры 1–2 § 14, № 350, 352 и 357; методическое пособие, урок 48.',diagram:{type:'panel',kind:'toolkit'}},
  {id:'l48-toolkit',kind:'model',eyebrow:'Инструменты',title:'Линейка отвечает за длину, транспортир — за угол',body:'Центр транспортира совмещаем с вершиной, нулевую линию — с исходным лучом. Линейку тоже начинаем с нулевой отметки, а не с края пластика.',diagram:{type:'panel',kind:'toolkit'}},
  {id:'l48-sas-order-gate',kind:'quiz',eyebrow:'Способ 1 · план',title:'Две стороны и угол между ними',body:'В примере 1 заданы 3 см, 2 см и включённый угол 50°.',activity:{id:'l48-p1',type:'choice',prompt:'Какой порядок действий точный?',options:['Угол → две длины → соединить концы','Три длины → сложить','Два произвольных луча → измерить','Сторона → перпендикуляр → окружность'],answer:'Угол → две длины → соединить концы',hint:'Сначала нужна общая вершина двух заданных сторон.',explanation:'Строим угол, откладываем на его лучах две длины и соединяем полученные точки.'},diagram:{type:'panel',kind:'sas-sequence'}},
  {id:'l48-tool-gate',kind:'practice',eyebrow:'Подготовка',title:'Выбери минимальный набор инструментов',body:'Нам нужно воспроизвести и сантиметры, и градусы.',activity:{id:'l48-p2',type:'choice',prompt:'Что понадобится?',options:['Линейка и транспортир','Только циркуль','Только линейка','Калькулятор и угольник'],answer:'Линейка и транспортир',hint:'Один инструмент измеряет отрезки, другой — углы.',explanation:'Линейка задаёт длины, а транспортир — градусную меру.'},diagram:{type:'panel',kind:'toolkit'}},
  {id:'l48-sas-angle-step',kind:'guided',eyebrow:'Пример 1 · шаг 1',title:'Построй ∠A=50°',body:'Проведи исходный луч, совмести с ним нулевую линию транспортира, отметь 50° и проведи второй луч из той же вершины A.',note:'На экране лучи длинные, но заданные стороны появятся только после измерения линейкой.',diagram:{type:'construction',method:'sas',step:1,sides:[3,2],angleA:50,protractor:'A'}},
  {id:'l48-protractor-scale-gate',kind:'practice',eyebrow:'Транспортир без ловушки',title:'Ноль шкалы должен лежать на исходном луче',body:'На транспортире две шкалы. Правильная начинается с 0° там, откуда поворачивается луч.',activity:{id:'l48-p3',type:'choice',prompt:'Как прочитать отметку 50°?',options:['По шкале с нулём на исходном луче','Всегда по внешней шкале','Выбрать большее число','Сложить обе шкалы'],answer:'По шкале с нулём на исходном луче',hint:'Отсчёт начинается с нуля на исходном луче.',explanation:'Нужная шкала стартует с 0° на исходном луче и доходит до отметки 50°.'},diagram:{type:'construction',method:'sas',step:1,sides:[3,2],angleA:50,protractor:'A'}},
  {id:'l48-sas-length-step',kind:'practice',eyebrow:'Пример 1 · шаг 2',title:'Отложи AB=3 см и AC=2 см',body:'На каждом луче измерение начинается от одной и той же вершины A.',activity:{id:'l48-p4',type:'input',prompt:'На какой сантиметровой отметке ставим B?',answer:'3',placeholder:'см',hint:'A совмещена с нулём линейки.',explanation:'Точку B ставим на отметке 3 см; точку C — на отметке 2 см другого луча.'},diagram:{type:'construction',method:'sas',step:2,sides:[3,2],angleA:50}},
  {id:'l48-sas-connect-step',kind:'practice',eyebrow:'Пример 1 · шаг 3',title:'Замкни треугольник',body:'Точки B и C уже находятся на нужных расстояниях от A.',activity:{id:'l48-p5',type:'choice',prompt:'Какое последнее действие?',options:['Соединить B и C','Продолжить только AB','Стереть вершину A','Сложить 3+2+50'],answer:'Соединить B и C',hint:'Не хватает третьей стороны.',explanation:'Отрезок BC замыкает фигуру. Получен треугольник ABC с заданными данными.'},diagram:{type:'construction',method:'sas',step:3,sides:[3,2],angleA:50,classification:'остроугольный разносторонний'}},
  {id:'l48-sas-uniqueness',kind:'model',eyebrow:'Точность конструкции',title:'Форма задана однозначно — с точностью до отражения',body:'Если длины и включённый угол те же, вершины окажутся в тех же взаимных положениях. Построение под лучом даёт зеркальную, но равную фигуру.',diagram:{type:'construction',method:'sas',step:3,sides:[3,2],angleA:50,reflection:true}},
  {id:'l48-sas-data-gate',kind:'quiz',eyebrow:'Проверка способа',title:'Не перепутай включённый угол с любым углом',body:'Две заданные стороны должны быть сторонами именно данного угла.',activity:{id:'l48-p6',type:'choice',prompt:'Какой набор подходит способу 1?',options:['Две стороны и угол между ними','Одна сторона и один угол','Три угла','Только периметр'],answer:'Две стороны и угол между ними',hint:'Угол имеет общую вершину с двумя заданными сторонами.',explanation:'Способ SAS использует две стороны и включённый между ними угол.'},diagram:{type:'panel',kind:'sas-sequence'}},
  {id:'l48-source350-1-build',kind:'guided',eyebrow:'Учебник № 350 · 1',title:'Стороны 3 см и 6 см, угол между ними 40°',body:'Строим угол 40°, на его сторонах откладываем 3 см и 6 см, затем соединяем концы. После построения измеряем остальные элементы.',note:'Острый заданный угол ещё не гарантирует, что весь треугольник остроугольный.',diagram:{type:'construction',method:'sas',step:3,sides:[3,6],angleA:40,displayAngles:[40,28,112],classification:'тупоугольный разносторонний'}},
  {id:'l48-source350-1-classify',kind:'practice',eyebrow:'№ 350 · 1 · измерение',title:'Измеренные углы примерно 40°, 28° и 112°',body:'Стороны после построения имеют разные длины.',activity:{id:'l48-p7',type:'choice',prompt:'Дай полный вид треугольника.',options:['Тупоугольный разносторонний','Остроугольный разносторонний','Тупоугольный равнобедренный','Прямоугольный разносторонний'],answer:'Тупоугольный разносторонний',hint:'112° больше 90°; равных сторон нет.',explanation:'Треугольник тупоугольный по углам и разносторонний по сторонам.'},diagram:{type:'construction',method:'sas',step:3,sides:[3,6],angleA:40,displayAngles:[40,28,112],classification:'тупоугольный разносторонний'}},
  {id:'l48-source350-2',kind:'practice',eyebrow:'Учебник № 350 · 2',title:'2 см 5 мм, 5 см и включённый угол 130°',body:'Строим по двум сторонам и углу между ними. Уже заданный угол больше 90°.',activity:{id:'l48-p8',type:'choice',prompt:'Каков вид после построения?',options:['Тупоугольный разносторонний','Остроугольный равнобедренный','Прямоугольный разносторонний','Тупоугольный равнобедренный'],answer:'Тупоугольный разносторонний',hint:'130° — тупой угол; заданные стороны не равны.',explanation:'Получается тупоугольный разносторонний треугольник.'},diagram:{type:'construction',method:'sas',step:3,sides:[2.5,5],sideLabels:['2 см 5 мм','5 см'],angleA:130,classification:'тупоугольный разносторонний'}},
  {id:'l48-source350-3',kind:'practice',eyebrow:'Учебник № 350 · 3',title:'Две стороны по 3 см 5 мм, угол между ними 54°',body:'Равные заданные стороны отмечаем одинаковыми штрихами. Остальные углы после построения — по 63°.',activity:{id:'l48-p9',type:'choice',prompt:'Каков полный вид?',options:['Остроугольный равнобедренный','Тупоугольный равнобедренный','Остроугольный разносторонний','Прямоугольный равносторонний'],answer:'Остроугольный равнобедренный',hint:'Все углы меньше 90°, две стороны равны.',explanation:'Треугольник остроугольный и равнобедренный.'},diagram:{type:'construction',method:'sas',step:3,sides:[3.5,3.5],sideLabels:['3 см 5 мм','3 см 5 мм'],angleA:54,displayAngles:[54,63,63],classification:'остроугольный равнобедренный'}},
  {id:'l48-asa-switch',kind:'model',eyebrow:'Способ 2',title:'Сторона и два прилежащих угла',body:'Теперь сначала строим известную сторону. Из её концов откладываем два угла в одну сторону от прямой; пересечение новых лучей становится третьей вершиной.',diagram:{type:'panel',kind:'asa-sequence'}},
  {id:'l48-asa-base-gate',kind:'practice',eyebrow:'Пример 2 · шаг 1',title:'Построй AB=2 см',body:'Это общая сторона двух заданных углов.',activity:{id:'l48-p10',type:'input',prompt:'Какова длина AB в сантиметрах?',answer:'2',placeholder:'см',hint:'Значение дано прямо в условии примера 2.',explanation:'Линейкой строим отрезок AB длиной 2 см.'},diagram:{type:'construction',method:'asa',step:1,base:2,angleA:40,angleB:110}},
  {id:'l48-asa-angle-a',kind:'practice',eyebrow:'Пример 2 · шаг 2',title:'Из A построй луч под углом к AB',body:'Исходным лучом служит AB, вершиной — A.',activity:{id:'l48-p11',type:'input',prompt:'Какой угол откладываем при A, °?',answer:'40',placeholder:'градусы',hint:'В условии ∠CAB=40°.',explanation:'От луча AB откладываем угол 40° и проводим первый угловой луч.'},diagram:{type:'construction',method:'asa',step:2,base:2,angleA:40,angleB:110,protractor:'A'}},
  {id:'l48-asa-angle-b',kind:'practice',eyebrow:'Пример 2 · шаг 3',title:'Из B отсчёт начинается от луча BA',body:'Нулевая линия теперь направлена от B к A. Угол строим в ту же полуплоскость.',activity:{id:'l48-p12',type:'input',prompt:'Какой угол откладываем при B, °?',answer:'110',placeholder:'градусы',hint:'В условии ∠CBA=110°.',explanation:'От луча BA откладываем 110° и проводим второй угловой луч.'},diagram:{type:'construction',method:'asa',step:3,base:2,angleA:40,angleB:110,protractor:'B'}},
  {id:'l48-example2-complete',kind:'guided',eyebrow:'Пример 2 · шаг 4',title:'Пересечение лучей — точка C',body:'Оба луча построены в одной полуплоскости. Их точка пересечения вместе с AB образует искомый треугольник ABC.',diagram:{type:'construction',method:'asa',step:4,base:2,angleA:40,angleB:110,classification:'тупоугольный разносторонний'}},
  {id:'l48-third-angle-gate',kind:'practice',eyebrow:'Контроль результата',title:'Третий угол подтверждает построение',body:'Сумма углов треугольника равна 180°.',activity:{id:'l48-p13',type:'input',prompt:'Найди ∠C: 180°−40°−110°.',answer:'30',placeholder:'градусы',hint:'Сначала 40+110=150.',explanation:'∠C=30°. Измерение на готовом чертеже должно дать близкое значение.'},diagram:{type:'construction',method:'asa',step:4,base:2,angleA:40,angleB:110,classification:'тупоугольный разносторонний'}},
  {id:'l48-same-side-gate',kind:'quiz',eyebrow:'Критическая деталь',title:'Два луча должны встретиться',body:'Если отложить углы по разные стороны от прямой AB, получится не тот треугольник.',activity:{id:'l48-p14',type:'choice',prompt:'Где строить оба угловых луча?',options:['По одну сторону от прямой AB','По разные стороны от AB','Оба вдоль AB','Направление не важно'],answer:'По одну сторону от прямой AB',hint:'Оба луча должны пересечься над одной базовой стороной.',explanation:'Углы откладывают в одну полуплоскость относительно прямой AB.'},diagram:{type:'panel',kind:'errors'}},
  {id:'l48-asa-feasibility',kind:'model',eyebrow:'Проверка до чертежа',title:'Сумма двух прилежащих углов должна быть меньше 180°',body:'Третий угол равен 180°−α−β и обязан быть больше нуля. При сумме 180° лучи параллельны, при большей сумме нужного треугольника нет.',diagram:{type:'panel',kind:'feasibility'}},
  {id:'l48-feasibility-gate',kind:'practice',eyebrow:'Быстрая проверка',title:'Углы при концах стороны: 100° и 70°',body:'Их сумма равна 170°, поэтому построение возможно.',activity:{id:'l48-p15',type:'input',prompt:'Чему равен третий угол, °?',answer:'10',placeholder:'градусы',hint:'180−170.',explanation:'Третий угол равен 10°, то есть остаётся положительным.'},diagram:{type:'construction',method:'asa',step:4,base:4,angleA:100,angleB:70,classification:'тупоугольный разносторонний'}},
  {id:'l48-source350-4',kind:'practice',eyebrow:'Учебник № 350 · 4',title:'AB=4 см, углы при A и B: 30° и 70°',body:'Строим сторону AB, два луча и отмечаем их пересечение.',activity:{id:'l48-p16',type:'input',prompt:'Найди третий угол, °.',answer:'80',placeholder:'180 − 30 − 70',hint:'Сложи 30° и 70°.',explanation:'Третий угол равен 80°. Все углы острые и разные: треугольник остроугольный разносторонний.'},diagram:{type:'construction',method:'asa',step:4,base:4,angleA:30,angleB:70,classification:'остроугольный разносторонний'}},
  {id:'l48-source350-5',kind:'practice',eyebrow:'Учебник № 350 · 5',title:'AB=2 см 5 мм, углы 100° и 20°',body:'Третий угол равен 60°.',activity:{id:'l48-p17',type:'choice',prompt:'Каков полный вид?',options:['Тупоугольный разносторонний','Остроугольный равнобедренный','Прямоугольный разносторонний','Тупоугольный равнобедренный'],answer:'Тупоугольный разносторонний',hint:'Есть угол 100°; все три угла различны.',explanation:'Треугольник тупоугольный разносторонний.'},diagram:{type:'construction',method:'asa',step:4,base:2.5,baseLabel:'2 см 5 мм',angleA:100,angleB:20,classification:'тупоугольный разносторонний'}},
  {id:'l48-source350-6',kind:'practice',eyebrow:'Учебник № 350 · 6',title:'BC=5 см, углы B=30° и C=60°',body:'Третья вершина обозначена A; третий угол равен 90°.',activity:{id:'l48-p18',type:'choice',prompt:'Каков полный вид?',options:['Прямоугольный разносторонний','Остроугольный разносторонний','Прямоугольный равнобедренный','Тупоугольный разносторонний'],answer:'Прямоугольный разносторонний',hint:'Углы 30°, 60° и 90° все различны.',explanation:'Треугольник прямоугольный и разносторонний.'},diagram:{type:'construction',method:'asa',step:4,base:5,angleA:30,angleB:60,vertexLabels:['B','C','A'],classification:'прямоугольный разносторонний'}},
  {id:'l48-source350-7',kind:'practice',eyebrow:'Учебник № 350 · 7',title:'BC=5 см 5 мм, углы B и C по 45°',body:'На третий угол остаётся 90°, а равные углы дают равные противоположные стороны.',activity:{id:'l48-p19',type:'choice',prompt:'Каков полный вид?',options:['Прямоугольный равнобедренный','Прямоугольный разносторонний','Остроугольный равносторонний','Тупоугольный равнобедренный'],answer:'Прямоугольный равнобедренный',hint:'45°+45°=90°; два угла равны.',explanation:'Треугольник прямоугольный равнобедренный.'},diagram:{type:'construction',method:'asa',step:4,base:5.5,baseLabel:'5 см 5 мм',angleA:45,angleB:45,vertexLabels:['B','C','A'],classification:'прямоугольный равнобедренный'}},
  {id:'l48-source350-8',kind:'practice',eyebrow:'Учебник № 350 · 8',title:'AC=5 см 5 мм, углы A и C по 60°',body:'Третий угол тоже равен 60°.',activity:{id:'l48-p20',type:'choice',prompt:'Каков полный вид?',options:['Остроугольный равносторонний','Остроугольный равнобедренный','Прямоугольный равносторонний','Тупоугольный разносторонний'],answer:'Остроугольный равносторонний',hint:'Все три угла равны 60°.',explanation:'Все стороны получаются равными, а все углы острыми.'},diagram:{type:'construction',method:'asa',step:4,base:5.5,baseLabel:'5 см 5 мм',angleA:60,angleB:60,vertexLabels:['A','C','B'],classification:'остроугольный равносторонний'}},
  {id:'l48-method-compare',kind:'model',eyebrow:'Выбор маршрута',title:'Сначала распознай данные — затем бери инструменты',body:'SAS: угол, две стороны на его лучах, соединение концов. ASA: сторона, два угла у её концов, пересечение лучей. В обоих случаях проверяем данные и измеряем результат.',diagram:{type:'panel',kind:'methods'}},
  {id:'l48-method-choice',kind:'quiz',eyebrow:'Мини-контроль · 1/3',title:'Даны стороны 4 см и 7 см и угол 60° между ними',body:'Определи не название треугольника, а маршрут построения.',activity:{id:'l48-p21',type:'choice',prompt:'Какой способ нужен?',options:['По двум сторонам и углу между ними','По стороне и двум прилежащим углам','По трём углам','По одному периметру'],answer:'По двум сторонам и углу между ними',hint:'В наборе две длины и включённый угол.',explanation:'Это способ SAS: строим угол 60°, откладываем 4 см и 7 см, соединяем концы.'},diagram:{type:'panel',kind:'methods'}},
  {id:'l48-source352',kind:'challenge',eyebrow:'Учебник № 352 · идея',title:'Четыре точки могут лежать на трёх сторонах',body:'У треугольника три вершины, но сторона — весь отрезок. Поэтому дополнительная отмеченная точка может оказаться внутри одной из сторон.',activity:{id:'l48-p22',type:'choice',prompt:'Обязана ли каждая из четырёх точек стать вершиной?',options:['Нет, точка может лежать внутри стороны','Да, нужен треугольник с четырьмя вершинами','Да, иначе точка не принадлежит стороне','Нет, четвёртую точку можно удалить'],answer:'Нет, точка может лежать внутри стороны',hint:'Вспомни, что принадлежит отрезку кроме его концов.',explanation:'Три точки могут быть вершинами, а четвёртая — лежать внутри одной стороны.'},diagram:{type:'panel',kind:'points'}},
  {id:'l48-construction-checklist',kind:'guided',eyebrow:'Самопроверка',title:'Пять проверок готового чертежа',body:'Проверь ноль линейки, центр транспортира, исходный луч, нужную шкалу и совпадение всех заданных длин и углов. Только затем называй вид треугольника.',diagram:{type:'panel',kind:'checklist'}},
  {id:'l48-error-clinic',kind:'model',eyebrow:'Клиника ошибок',title:'Край линейки — не ноль, 130° — не 50°, разные полуплоскости — не один треугольник',body:'Большая часть неточностей появляется до соединения сторон. Остановись после каждого действия и сравни чертёж с условием.',diagram:{type:'panel',kind:'errors'}},
  {id:'l48-source357',kind:'model',eyebrow:'Повторение · № 357',title:'Цифровая проверка тоже идёт справа налево',body:'Восстанавливая цифры, учитывай перенос или занимание в каждом разряде. Получаются верные записи 74 768+25 232=100 000 и 101 230−45 675=55 555.',diagram:{type:'panel',kind:'digits'}},
  {id:'l48-final-gate',kind:'challenge',eyebrow:'Мини-контроль · 3/3',title:'№ 351(4): AB=4 см 5 мм, углы при A и B по 35°',body:'Строим сторону, два луча по 35° в одной полуплоскости и находим C.',activity:{id:'l48-p23',type:'input',prompt:'Чему равен третий угол C, °?',answer:'110',placeholder:'180 − 35 − 35',hint:'Сумма двух заданных углов равна 70°.',explanation:'∠C=110°. После построения получаем тупоугольный равнобедренный треугольник.'},diagram:{type:'construction',method:'asa',step:4,base:4.5,baseLabel:'4 см 5 мм',angleA:35,angleB:35,classification:'тупоугольный равнобедренный'}},
  {id:'l48-summary',kind:'summary',eyebrow:'Итог урока 48',title:'Данные → алгоритм → точный чертёж → проверка',body:'Ты строишь треугольники двумя способами, правильно читаешь транспортир, проверяешь возможность ASA-построения, находишь третий угол и классифицируешь только готовую фигуру.',note:'Домашняя работа по маршруту методического пособия: § 14, № 351, 353; дополнительное задание № 358. Дальше — обязательная мастерская из 20 задач.',diagram:{type:'panel',kind:'final'}}
];

function projectTriangle(points:Point[]){
  const minX=Math.min(...points.map(point=>point.x));const maxX=Math.max(...points.map(point=>point.x));const minY=Math.min(...points.map(point=>point.y));const maxY=Math.max(...points.map(point=>point.y));
  const width=Math.max(maxX-minX,.1);const height=Math.max(maxY-minY,.1);const scale=Math.min(500/width,195/height);const centerX=(minX+maxX)/2;const centerY=(minY+maxY)/2;
  return(pointsToProject:Point[])=>pointsToProject.map(point=>({x:325+(point.x-centerX)*scale,y:145+(point.y-centerY)*scale}));
}
function extendRay(start:Point,end:Point,extra=44){const dx=end.x-start.x;const dy=end.y-start.y;const length=Math.max(Math.hypot(dx,dy),1);return{x:end.x+dx/length*extra,y:end.y+dy/length*extra}}
function tickPath(start:Point,end:Point){const dx=end.x-start.x;const dy=end.y-start.y;const length=Math.max(Math.hypot(dx,dy),1);const middle={x:(start.x+end.x)/2,y:(start.y+end.y)/2};const nx=-dy/length*10;const ny=dx/length*10;return`M ${middle.x-nx} ${middle.y-ny} L ${middle.x+nx} ${middle.y+ny}`}
function angleArc(vertex:Point,from:Point,to:Point,radius=38){const unit=(point:Point)=>{const dx=point.x-vertex.x;const dy=point.y-vertex.y;const length=Math.max(Math.hypot(dx,dy),1);return{x:dx/length,y:dy/length}};const first=unit(from);const second=unit(to);const start={x:vertex.x+first.x*radius,y:vertex.y+first.y*radius};const end={x:vertex.x+second.x*radius,y:vertex.y+second.y*radius};const dot=Math.max(-1,Math.min(1,first.x*second.x+first.y*second.y));const large=Math.acos(dot)>Math.PI?'1':'0';return`M ${start.x} ${start.y} A ${radius} ${radius} 0 ${large} 0 ${end.x} ${end.y}`}

function ConstructionSvg({diagram}:{diagram:ConstructionDiagram}){
  const labels=diagram.vertexLabels??['A','B','C'];let raw:Point[];let angleValues:number[];let sideValues:string[];let equalPairs:[number,number][]=[];
  if(diagram.method==='sas'){
    const radians=diagram.angleA*Math.PI/180;raw=[{x:0,y:0},{x:diagram.sides[0],y:0},{x:diagram.sides[1]*Math.cos(radians),y:-diagram.sides[1]*Math.sin(radians)}];angleValues=diagram.displayAngles??[diagram.angleA];sideValues=diagram.sideLabels??diagram.sides.map(value=>`${value} см`) as [string,string];if(Math.abs(diagram.sides[0]-diagram.sides[1])<.001)equalPairs=[[0,1],[0,2]];
  }else{
    const sum=(diagram.angleA+diagram.angleB)*Math.PI/180;const alpha=diagram.angleA*Math.PI/180;const beta=diagram.angleB*Math.PI/180;const heightDenominator=Math.max(Math.sin(sum),.02);const cx=diagram.base*Math.sin(beta)*Math.cos(alpha)/heightDenominator;const cy=-diagram.base*Math.sin(alpha)*Math.sin(beta)/heightDenominator;raw=[{x:0,y:0},{x:diagram.base,y:0},{x:cx,y:cy}];const third=180-diagram.angleA-diagram.angleB;angleValues=[diagram.angleA,diagram.angleB,third];sideValues=[diagram.baseLabel??`${diagram.base} см`];if(Math.abs(diagram.angleA-diagram.angleB)<.001)equalPairs=[[0,2],[1,2]];
  }
  const project=projectTriangle(raw);const[A,B,C]=project(raw);const rayAB=extendRay(A,B);const rayAC=extendRay(A,C);const rayBA=extendRay(B,A);const rayBC=extendRay(B,C);const complete=diagram.method==='sas'?diagram.step>=3:diagram.step>=4;const sasLengths=diagram.method==='sas'&&diagram.step>=2;const asaBase=diagram.method==='asa'&&diagram.step>=1;const thirdAngle=diagram.method==='asa'?180-diagram.angleA-diagram.angleB:null;const rightAngle=diagram.method==='sas'?angleValues.includes(90):[diagram.angleA,diagram.angleB,thirdAngle].includes(90);const equilateral=diagram.method==='asa'&&diagram.angleA===60&&diagram.angleB===60;
  const protractorPoint=diagram.protractor==='B'?B:A;
  return <div className="triangle-construction-diagram" data-construction-method={diagram.method} data-step={diagram.step} data-side-values={sideValues.join('|')} data-angle-values={angleValues.join('|')} data-classification={diagram.classification??'not-set'} data-protractor-scale={diagram.protractor?`${diagram.protractor==='A'?'from-right':'from-left'}-${diagram.protractor==='A'?diagram.angleA:diagram.method==='asa'?diagram.angleB:''}`:'none'}>
    <svg viewBox="0 0 650 290" role="img" aria-label={`Построение треугольника способом ${diagram.method==='sas'?'по двум сторонам и углу между ними':'по стороне и двум прилежащим углам'}`}>
      {diagram.protractor?<g className="construction-protractor" data-protractor-at={diagram.protractor}><path d={`M ${protractorPoint.x-78} ${protractorPoint.y} A 78 78 0 0 1 ${protractorPoint.x+78} ${protractorPoint.y}`}/><line x1={protractorPoint.x-83} y1={protractorPoint.y} x2={protractorPoint.x+83} y2={protractorPoint.y}/><circle cx={protractorPoint.x} cy={protractorPoint.y} r="4"/><text x={protractorPoint.x-89} y={protractorPoint.y+18}>180</text><text x={protractorPoint.x+70} y={protractorPoint.y+18}>0</text></g>:null}
      {diagram.method==='sas'?<>
        <line className="construction-ray" data-construction-ray="AB" x1={A.x} y1={A.y} x2={rayAB.x} y2={rayAB.y}/><line className="construction-ray" data-construction-ray="AC" x1={A.x} y1={A.y} x2={rayAC.x} y2={rayAC.y}/>
        <path className="construction-angle" data-angle-marker={diagram.angleA} d={angleArc(A,B,C)}/><text className="construction-angle-label" x={A.x+46} y={A.y-22}>{diagram.angleA}°</text>
        {sasLengths?<><line className="construction-segment" data-construction-segment="AB" x1={A.x} y1={A.y} x2={B.x} y2={B.y}/><line className="construction-segment" data-construction-segment="AC" x1={A.x} y1={A.y} x2={C.x} y2={C.y}/><circle className="construction-point" cx={B.x} cy={B.y} r="6"/><circle className="construction-point" cx={C.x} cy={C.y} r="6"/><text className="construction-value" x={(A.x+B.x)/2-12} y={(A.y+B.y)/2+24}>{sideValues[0]}</text><text className="construction-value" x={(A.x+C.x)/2-54} y={(A.y+C.y)/2-8}>{sideValues[1]}</text></>:null}
        {complete?<><polygon className="construction-fill" points={`${A.x},${A.y} ${B.x},${B.y} ${C.x},${C.y}`}/><line className="construction-segment construction-final" data-construction-segment="BC" x1={B.x} y1={B.y} x2={C.x} y2={C.y}/></>:null}
        {diagram.reflection?<polygon className="construction-reflection" data-reflection="true" points={`${A.x},${A.y} ${B.x},${B.y} ${C.x},${2*A.y-C.y}`}/>:null}
      </>:<>
        {asaBase?<line className="construction-segment" data-construction-segment="AB" x1={A.x} y1={A.y} x2={B.x} y2={B.y}/>:null}
        {diagram.step>=2?<><line className="construction-ray" data-construction-ray="AC" x1={A.x} y1={A.y} x2={rayAC.x} y2={rayAC.y}/><path className="construction-angle" data-angle-marker={diagram.angleA} d={angleArc(A,B,C)}/><text className="construction-angle-label" x={A.x+42} y={A.y-20}>{diagram.angleA}°</text></>:null}
        {diagram.step>=3?<><line className="construction-ray" data-construction-ray="BC" x1={B.x} y1={B.y} x2={rayBC.x} y2={rayBC.y}/><path className="construction-angle" data-angle-marker={diagram.angleB} d={angleArc(B,A,C)}/><text className="construction-angle-label" x={B.x-70} y={B.y-20}>{diagram.angleB}°</text></>:null}
        {complete?<><polygon className="construction-fill" points={`${A.x},${A.y} ${B.x},${B.y} ${C.x},${C.y}`}/><circle className="construction-point construction-intersection" data-intersection-marker="true" cx={C.x} cy={C.y} r="7"/><text className="construction-angle-label" x={C.x+12} y={C.y+22}>{thirdAngle}°</text></>:null}
      </>}
      <circle className="construction-point" cx={A.x} cy={A.y} r="6"/><text className="construction-label" x={A.x-24} y={A.y+25}>{labels[0]}</text>{(sasLengths||asaBase)?<><circle className="construction-point" cx={B.x} cy={B.y} r="6"/><text className="construction-label" x={B.x+12} y={B.y+24}>{labels[1]}</text></>:null}{complete?<text className="construction-label" x={C.x+12} y={C.y-10}>{labels[2]}</text>:null}
      {equalPairs.map(([first,second],index)=><path key={`${first}-${second}`} className="construction-equal-mark" data-equal-side-mark={index+1} d={tickPath([A,B,C][first],[A,B,C][second])}/>) }
      {equilateral?<path className="construction-equal-mark" data-equal-side-mark="3" d={tickPath(A,B)}/>:null}
      {rightAngle&&complete?<path className="construction-right-mark" data-right-angle-marker="true" d={`M ${C.x-12} ${C.y+18} l 15 3 l 3 -15`}/>:null}
      {diagram.method==='asa'&&asaBase?<text className="construction-value" x={(A.x+B.x)/2-24} y={(A.y+B.y)/2+26}>{sideValues[0]}</text>:null}
    </svg>
    <div className="construction-readout"><span><b>Способ</b>{diagram.method==='sas'?'2 стороны + угол между ними':'сторона + 2 прилежащих угла'}</span><span><b>Шаг</b>{diagram.step}</span>{diagram.classification?<span><b>Результат</b>{diagram.classification}</span>:null}</div>
  </div>;
}

function PanelDiagram({kind}:{kind:PanelKind}){
  if(kind==='toolkit')return <div className="triangle-construction-panel" data-panel="toolkit"><div className="construction-tools"><span><i>📏</i><b>Линейка</b><small>отрезки от 0</small></span><span><i>◡</i><b>Транспортир</b><small>центр · луч · шкала</small></span><span><i>✏️</i><b>Карандаш</b><small>тонкая точная линия</small></span></div></div>;
  if(kind==='sas-sequence'||kind==='asa-sequence'){const steps=kind==='sas-sequence'?['Построй угол','Отложи 2 длины','Соедини концы']:['Построй сторону','Отложи угол A','Отложи угол B','Отметь пересечение'];return <div className="triangle-construction-panel" data-panel={kind}><div className="construction-sequence">{steps.map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</div></div>}
  if(kind==='uniqueness')return <div className="triangle-construction-panel" data-panel="uniqueness"><div className="construction-equivalence"><span>△ABC</span><b>↔ зеркало ↔</b><span>△ABС′</span><strong>длины и углы совпадают</strong></div></div>;
  if(kind==='feasibility')return <div className="triangle-construction-panel" data-panel="feasibility"><div className="construction-feasibility"><span data-valid="true">40°+110°=150°<b>третий угол 30°</b></span><span data-valid="false">100°+80°=180°<b>треугольника нет</b></span></div></div>;
  if(kind==='methods')return <div className="triangle-construction-panel" data-panel="methods"><div className="construction-methods"><span><b>SAS</b><small>сторона · угол · сторона</small><strong>угол → длины → замкнуть</strong></span><span><b>ASA</b><small>угол · сторона · угол</small><strong>сторона → лучи → пересечение</strong></span></div></div>;
  if(kind==='points')return <div className="triangle-construction-panel" data-panel="points"><svg className="construction-points-model" viewBox="0 0 600 220" role="img" aria-label="Треугольник, на сторонах которого лежат четыре отмеченные точки"><polygon points="90,185 300,35 525,185"/><circle cx="90" cy="185" r="8"/><circle cx="300" cy="35" r="8"/><circle cx="525" cy="185" r="8"/><circle data-point-on-side="true" cx="390" cy="185" r="8"/><text x="70" y="212">1</text><text x="292" y="25">2</text><text x="533" y="212">3</text><text x="382" y="212">4</text></svg><p>Точка 4 лежит внутри стороны — это допустимо.</p></div>;
  if(kind==='checklist')return <div className="triangle-construction-panel" data-panel="checklist"><ol className="construction-checklist"><li>ноль линейки</li><li>центр транспортира</li><li>нулевая линия на луче</li><li>верная шкала</li><li>повторное измерение</li></ol></div>;
  if(kind==='errors')return <div className="triangle-construction-panel" data-panel="errors"><div className="construction-errors"><span><b>✕</b>от края линейки</span><span><b>✕</b>не та шкала</span><span><b>✕</b>лучи по разные стороны</span><strong>Исправление: ноль → центр → исходный луч → одна полуплоскость</strong></div></div>;
  if(kind==='digits')return <div className="triangle-construction-panel" data-panel="digits"><div className="construction-digits"><span>74 768 + 25 232 = <b>100 000</b></span><span>101 230 − 45 675 = <b>55 555</b></span></div></div>;
  return <div className="triangle-construction-panel" data-panel="final"><div className="construction-final-card"><b>SAS ✓</b><b>ASA ✓</b><b>шкала ✓</b><b>проверка ✓</b></div></div>;
}

function DiagramView({diagram}:{diagram:Diagram}){return diagram.type==='construction'?<ConstructionSvg diagram={diagram}/>:<PanelDiagram kind={diagram.kind}/>}
function emptySaved():Saved{return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function loadSaved():Saved{try{const raw=localStorage.getItem(KEY);if(!raw)return emptySaved();const parsed=JSON.parse(raw) as Partial<Saved>;return{version:1,stageIndex:Math.min(Math.max(Number(parsed.stageIndex)||0,0),lessonFortyEightStages.length-1),responses:parsed.responses??{},checked:parsed.checked??{},results:parsed.results??{},attempts:parsed.attempts??{}}}catch{return emptySaved()}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}

export function TriangleConstructionPlayer(){
  const[saved,setSaved]=useState<Saved>(()=>loadSaved());const stage=lessonFortyEightStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):true;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;
  const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonFortyEightStages.length)*100),[saved.stageIndex]);
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==48||typeof detail.stageIndex!=='number')return;const index=Math.min(Math.max(detail.stageIndex,0),lessonFortyEightStages.length-1);stopNarration();setSaved(previous=>({...previous,stageIndex:index}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
  function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
  function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+(correct?0:1)}}))}
  function next(){if(!canContinue||saved.stageIndex>=lessonFortyEightStages.length-1)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
  function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
  return <section className="lesson-player triangle-construction-player" data-lesson-number="48" data-source-reference="Мерзляк §14 · примеры 1–2 · №350, 352, 357"><article className={`interactive-stage ${stage.kind==='summary'?'stage-summary':''}`} data-stage-id={stage.id}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.diagram?<DiagramView diagram={stage.diagram}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Пока нет'}</strong><span>{isCorrect?activity.explanation:attempts>=2?`${activity.hint} Можно перейти дальше и вернуться к заданию позже.`:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>Назад</button><span>Этап {saved.stageIndex+1} из {lessonFortyEightStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex===lessonFortyEightStages.length-1||!canContinue}>{saved.stageIndex===lessonFortyEightStages.length-1?'Итог':'Дальше'}</button></div></article></section>;
}
