import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'formula'|'inverse'|'box'|'cube'|'source'|'units'|'mass'|'rate'|'verify'|'final';
export type LessonEightyThreeStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-83-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[³^]/g,'3').replace(/[²]/g,'2').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightyThreeStages:LessonEightyThreeStage[]=[
{id:'l83-mission',kind:'story',eyebrow:'Урок 83 · § 23 · закрепление',title:'Объём в обратных и прикладных задачах',body:'Формулы V=abc, V=a³ и V=Sh уже известны. Сегодня учимся распознавать, какое измерение спрятано, приводить единицы, работать с составным объёмом и переводить геометрический результат в производительность или массу.',note:'Технологическая карта урока 83: устно №4, с.156; №626, 630, 633, 634; повторение №644; домашнее — §23, №627, 631, 643(3,4).',visual:'mission'},
{id:'l83-oral4-model',kind:'guided',eyebrow:'Актуализация · устно №4, с.156',title:'Знаки превращают запись в верное равенство',body:'Нужно расставить «+» и «−» в записи 20 * 30 * 10 * 80 * 70 = 50. Проверяем значение слева после каждого выбранного знака.',visual:'verify',sourceExercise:'Устно №4, с.156'},
{id:'l83-oral4-signs',kind:'practice',eyebrow:'Устно №4 · точное решение',title:'Выбери верную расстановку',body:'Только один вариант даёт 50.',activity:{id:'l83-p1',type:'choice',prompt:'Какая запись верна?',options:['20+30−10+80−70=50','20−30+10+80−70=10','20+30+10−80+70=50'],answer:'20+30−10+80−70=50',hint:'Считай слева направо: 20+30=50; 50−10=40; 40+80=120; 120−70=50.',explanation:'20+30−10+80−70=50.'},visual:'verify',sourceExercise:'Устно №4, с.156'},
{id:'l83-formula-map',kind:'model',eyebrow:'§23 · карта формул',title:'Прямая задача и обратная — одна формула',body:'V=abc. Если известны V,a,b, то c=V:(ab). Если известны V и площадь основания S, то h=V:S. Для куба V=a³.',visual:'formula',sourceExercise:'§23'},
{id:'l83-inverse-formula',kind:'quiz',eyebrow:'§23 · обратная задача',title:'Как найти высоту?',body:'Объём равен площади основания, умноженной на высоту.',activity:{id:'l83-p2',type:'choice',prompt:'Если известны V и S, какая формула даёт h?',options:['h=V:S','h=V·S','h=S:V'],answer:'h=V:S',hint:'Из V=Sh делим обе стороны на S.',explanation:'h=V:S.'},visual:'inverse',sourceExercise:'§23'},
{id:'l83-626-model',kind:'guided',eyebrow:'№626',title:'V=560 см³, a=14 см, b=8 см',body:'Точное условие №626 задаёт объём, длину и ширину. Сначала найдём площадь основания 14·8, затем высоту.',visual:'box',sourceExercise:'№626'},
{id:'l83-626-base',kind:'practice',eyebrow:'№626 · шаг 1',title:'Площадь основания',body:'Основание — прямоугольник 14 см × 8 см.',activity:{id:'l83-p3',type:'input',prompt:'14·8 = ? см²',answer:'112',placeholder:'см²',hint:'10·8+4·8.',explanation:'S=112 см².'},visual:'box',sourceExercise:'№626'},
{id:'l83-626-height',kind:'practice',eyebrow:'№626 · ответ',title:'Высота через объём и основание',body:'h=V:S=560:112.',activity:{id:'l83-p4',type:'input',prompt:'560:112 = ? см',answer:'5',placeholder:'см',hint:'112·5=560.',explanation:'Высота равна 5 см.'},visual:'inverse',sourceExercise:'№626'},
{id:'l83-630-source',kind:'model',eyebrow:'№630 · source checkpoint',title:'Составная фигура на рисунке 180',body:'№630 требует найти объём фигуры на авторском рисунке 180. Ответ учебника — 13 500 см³.',note:'Геометрия рисунка 180 не восстановлена из доступной текстовой выгрузки с достаточной точностью. Поэтому приложение сохраняет номер и авторский ответ, но не придумывает форму фигуры.',visual:'source',sourceExercise:'№630 · рис.180'},
{id:'l83-composite-model',kind:'model',eyebrow:'№630 · стратегия',title:'Составной объём раскладываем на простые тела',body:'Если фигура состоит из неперекрывающихся прямоугольных параллелепипедов, её объём равен сумме их объёмов. Если из большого тела вырезан блок — объём вырезанного блока вычитают.',visual:'box',sourceExercise:'§23 · свойство объёма'},
{id:'l83-dict-seven-cubes',kind:'practice',eyebrow:'Математический диктант 20',title:'Семь кубов с ребром 3 см',body:'Объём одного куба 3³=27 см³. Тело состоит из семи одинаковых кубов.',activity:{id:'l83-p5',type:'input',prompt:'7·27 = ? см³',answer:'189',placeholder:'см³',hint:'27·7.',explanation:'Общий объём 189 см³.'},visual:'cube',sourceExercise:'Математический диктант 20'},
{id:'l83-dict-liters',kind:'quiz',eyebrow:'Математический диктант 20',title:'6 дм³ и 7 литров',body:'1 л=1 дм³. Сосуд объёмом 6 дм³ не вместит 7 л жидкости.',activity:{id:'l83-p6',type:'choice',prompt:'Поместятся ли 7 л в сосуд объёмом 6 дм³?',options:['да','нет'],answer:'нет',hint:'7 л=7 дм³.',explanation:'Нет: 7 дм³ больше 6 дм³.'},visual:'units',sourceExercise:'Математический диктант 20'},
{id:'l83-units-map',kind:'model',eyebrow:'§23 · единицы',title:'Перед V=abc приводим длины к одной единице',body:'Например, 1 дм=10 см. После преобразования линейных размеров результат записывается в соответствующей кубической единице.',visual:'units',sourceExercise:'§23'},
{id:'l83-dict-box',kind:'practice',eyebrow:'Математический диктант 20',title:'2 см × 5 см × 12 см',body:'Все размеры уже выражены в сантиметрах.',activity:{id:'l83-p7',type:'input',prompt:'2·5·12 = ? см³',answer:'120',placeholder:'см³',hint:'10·12.',explanation:'V=120 см³.'},visual:'box',sourceExercise:'Математический диктант 20'},
{id:'l83-dict-mixed',kind:'practice',eyebrow:'Математический диктант 20',title:'2 дм³ 4 см³ в кубических сантиметрах',body:'1 дм³=1000 см³.',activity:{id:'l83-p8',type:'input',prompt:'2 дм³ 4 см³ = ? см³',answer:'2004',placeholder:'см³',hint:'2·1000+4.',explanation:'2 дм³ 4 см³=2004 см³.'},visual:'units',sourceExercise:'Математический диктант 20'},
{id:'l83-dict-cm-dm',kind:'practice',eyebrow:'Математический диктант 20',title:'15 см × 1 дм × 4 см',body:'Сначала 1 дм превращаем в 10 см.',activity:{id:'l83-p9',type:'input',prompt:'15·10·4 = ? см³',answer:'600',placeholder:'см³',hint:'150·4.',explanation:'V=600 см³.'},visual:'units',sourceExercise:'Математический диктант 20'},
{id:'l83-cube-formula',kind:'model',eyebrow:'§23 · куб',title:'V=a³ связывает объём и физическую величину',body:'Если известна масса одного кубического сантиметра вещества, сначала по ребру куба находим V=a³, затем умножаем объём на массу 1 см³.',visual:'cube',sourceExercise:'§23'},
{id:'l83-dict-al-volume',kind:'practice',eyebrow:'Математический диктант 20',title:'Куб с ребром 5 см',body:'5³=5·5·5.',activity:{id:'l83-p10',type:'input',prompt:'5³ = ? см³',answer:'125',placeholder:'см³',hint:'25·5.',explanation:'Объём 125 см³.'},visual:'cube',sourceExercise:'Математический диктант 20'},
{id:'l83-dict-al-mass',kind:'practice',eyebrow:'Математический диктант 20',title:'Масса при 3 г на 1 см³',body:'Каждый из 125 кубических сантиметров имеет массу 3 г.',activity:{id:'l83-p11',type:'input',prompt:'125·3 = ? г',answer:'375',placeholder:'г',hint:'100·3+25·3.',explanation:'Масса 375 г.'},visual:'mass',sourceExercise:'Математический диктант 20'},
{id:'l83-scale-model',kind:'model',eyebrow:'Математический диктант 20',title:'Как меняется объём куба',body:'Если ребро увеличивается в k раз, объём увеличивается в k³ раз. Для рёбер 4 и 2 отношение длин равно 2.',visual:'cube',sourceExercise:'Математический диктант 20'},
{id:'l83-scale-ratio',kind:'practice',eyebrow:'Математический диктант 20',title:'Куб 4 см против куба 2 см',body:'(4:2)³=2³.',activity:{id:'l83-p12',type:'input',prompt:'Во сколько раз объём куба 4 см больше объёма куба 2 см?',answer:'8',hint:'2³.',explanation:'В 8 раз.'},visual:'cube',sourceExercise:'Математический диктант 20'},
{id:'l83-633-model',kind:'guided',eyebrow:'№633',title:'Траншея и производительность',body:'Точное условие: длина 150 м, глубина 80 см, ширина 60 см. Машина вырыла траншею за 8 ч. Один рабочий за 8 ч вынимает 240 дм³ грунта.',note:'Прежде чем считать объём, 80 см=0,8 м и 60 см=0,6 м.',visual:'rate',sourceExercise:'№633'},
{id:'l83-633-volume',kind:'practice',eyebrow:'№633 · объём',title:'Объём траншеи',body:'V=150·0,8·0,6.',activity:{id:'l83-p13',type:'input',prompt:'Объём траншеи = ? м³',answer:'72',placeholder:'м³',hint:'0,8·0,6=0,48; 150·0,48.',explanation:'V=72 м³.'},visual:'box',sourceExercise:'№633'},
{id:'l83-633-rate',kind:'practice',eyebrow:'№633 · машина',title:'Производительность машины',body:'72 м³ выполнены за 8 часов.',activity:{id:'l83-p14',type:'input',prompt:'72:8 = ? м³/ч',answer:'9',placeholder:'м³/ч',hint:'Раздели общий объём на время.',explanation:'9 м³/ч.'},visual:'rate',sourceExercise:'№633'},
{id:'l83-633-worker-volume',kind:'practice',eyebrow:'№633 · один рабочий',title:'Перевод 240 дм³',body:'1000 дм³=1 м³, значит 240 дм³=0,24 м³.',activity:{id:'l83-p15',type:'input',prompt:'240 дм³ = ? м³',answer:['0.24','0,24'],placeholder:'м³',hint:'240:1000.',explanation:'0,24 м³.'},visual:'units',sourceExercise:'№633'},
{id:'l83-633-workers',kind:'practice',eyebrow:'№633 · сравнение',title:'Сколько рабочих заменяет машина?',body:'За те же 8 часов машина выполняет 72 м³, а один рабочий — 0,24 м³.',activity:{id:'l83-p16',type:'input',prompt:'72:0,24 = ? рабочих',answer:'300',placeholder:'рабочих',hint:'72·100:24.',explanation:'Машина заменяет 300 рабочих.'},visual:'rate',sourceExercise:'№633'},
{id:'l83-634-model',kind:'guided',eyebrow:'№634',title:'Равные объёмы куба и параллелепипеда',body:'У параллелепипеда длина 12 см; она в 2 раза больше ширины и в 4 раза больше высоты. Куб имеет тот же объём. Нужно найти площадь поверхности куба.',visual:'box',sourceExercise:'№634'},
{id:'l83-634-width',kind:'practice',eyebrow:'№634 · ширина',title:'12 см в 2 раза больше ширины',body:'Ширина равна 12:2.',activity:{id:'l83-p17',type:'input',prompt:'Ширина = ? см',answer:'6',placeholder:'см',hint:'12:2.',explanation:'Ширина 6 см.'},visual:'box',sourceExercise:'№634'},
{id:'l83-634-height',kind:'practice',eyebrow:'№634 · высота',title:'12 см в 4 раза больше высоты',body:'Высота равна 12:4.',activity:{id:'l83-p18',type:'input',prompt:'Высота = ? см',answer:'3',placeholder:'см',hint:'12:4.',explanation:'Высота 3 см.'},visual:'box',sourceExercise:'№634'},
{id:'l83-634-volume',kind:'practice',eyebrow:'№634 · объём',title:'Объём параллелепипеда',body:'V=12·6·3.',activity:{id:'l83-p19',type:'input',prompt:'12·6·3 = ? см³',answer:'216',placeholder:'см³',hint:'72·3.',explanation:'V=216 см³.'},visual:'box',sourceExercise:'№634'},
{id:'l83-634-cube-edge',kind:'practice',eyebrow:'№634 · равный объём',title:'Ребро куба',body:'Нужно число a, для которого a³=216.',activity:{id:'l83-p20',type:'input',prompt:'a³=216. a = ? см',answer:'6',placeholder:'см',hint:'6·6·6=216.',explanation:'Ребро куба 6 см.'},visual:'cube',sourceExercise:'№634'},
{id:'l83-634-surface',kind:'practice',eyebrow:'№634 · ответ',title:'Площадь поверхности куба',body:'У куба 6 квадратных граней, площадь каждой 6²=36 см².',activity:{id:'l83-p21',type:'input',prompt:'6·36 = ? см²',answer:'216',placeholder:'см²',hint:'Площадь поверхности куба 6a².',explanation:'Площадь поверхности куба 216 см².'},visual:'cube',sourceExercise:'№634'},
{id:'l83-644-source',kind:'model',eyebrow:'Повторение · №644 · source checkpoint',title:'Повторение сохраняем без выдуманного условия',body:'Технологическая карта урока 83 задаёт повторение №644.',note:'Полное условие №644 именно этой редакции не удалось надёжно восстановить из доступной выгрузки. Номер остаётся в маршруте как авторский checkpoint.',visual:'source',sourceExercise:'№644'},
{id:'l83-homework-route',kind:'model',eyebrow:'Домашний маршрут',title:'№627, 631 и 643(3,4)',body:'№627 подтверждён как обратная задача: длина 18 см, высота 15 см, объём 3240 см³; ширина равна 12 см.',note:'№631 зависит от рисунка 181; авторский ответ — 7456 см³, форму рисунка не реконструируем. Полные условия №643(3,4) надёжно не восстановлены и остаются source-checkpoints.',visual:'source',sourceExercise:'№627, 631, 643(3,4)'},
{id:'l83-reflection',kind:'story',eyebrow:'Самопроверка',title:'Выбери формулу по неизвестному',body:'Если ищешь объём — умножай согласованные измерения. Если ищешь высоту или площадь основания — перестрой V=Sh. Если тело составное — сначала определи его простые части. Если задача физическая — после геометрии переведи объём в требуемую величину.',visual:'verify'},
{id:'l83-summary',kind:'summary',eyebrow:'Итог урока 83',title:'Формула объёма стала инструментом решения задач',body:'Ты умеешь восстанавливать неизвестное измерение, приводить единицы, считать составной объём и связывать его с производительностью и массой. Точные №626, 633 и 634 доводят формулу до прикладного использования.',note:'Обязательная практика: 20 задач / ровно 50 ответов. Урок 84 — итоговое закрепление §23 — остаётся закрытым до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'V',formula:'V=abc',inverse:'V:S',box:'a·b·c',cube:'a³',source:'§23',units:'↔',mass:'см³→г',rate:'V:t',verify:'✓',final:'83'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='inverse'?'находим неизвестный размер':kind==='rate'?'объём и производительность':kind==='units'?'согласуем единицы':kind==='mass'?'объём превращается в массу':kind==='source'?'авторский источник без реконструкции':'закрепление формул объёма'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyThreeStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function VolumeReinforcementPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyThreeStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyThreeStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==83||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyThreeStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyThreeStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player volume-reinforcement-player" data-lesson-number="83" data-source-reference="Мерзляк § 23 · технологическая карта урока 83 · устно №4 · №626, 630, 633, 634 · повторение №644" data-source-exercise-range="626,630,633,634,644"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyThreeStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyThreeStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
