import {useEffect,useMemo,useState} from 'react';
import './lessonPlayer.css';
import './theoryExperience.css';
import './divisionMeaning.css';

type Activity={id:string;type:'choice'|'input';prompt:string;options?:string[];answer:string|string[];explanation:string;hint:string;placeholder?:string};
type VisualKind='mission'|'formula'|'inverse'|'box'|'cube'|'source'|'units'|'mass'|'rate'|'verify'|'final';
export type LessonEightyFourStage={id:string;title:string;eyebrow:string;kind:'story'|'model'|'guided'|'practice'|'quiz'|'challenge'|'summary';body:string;note?:string;activity?:Activity;visual?:VisualKind;sourceExercise?:string};
type Saved={version:1;stageIndex:number;responses:Record<string,string>;checked:Record<string,boolean>;results:Record<string,boolean>;attempts:Record<string,number>};
type StageJumpDetail={lessonNumber?:number;stageIndex?:number};

const KEY='mathnikita-lesson-84-progress-v1';
const normalize=(value:string)=>value.normalize('NFKC').trim().toLocaleUpperCase('ru-RU').replace(/Ё/g,'Е').replace(/[×*]/g,'·').replace(/−/g,'-').replace(/[³^]/g,'3').replace(/[²]/g,'2').replace(/[\s.,;:!?()[\]{}'"«»°]/g,'').replace(/·/g,'');
const numericValue=(value:string)=>{const compact=value.normalize('NFKC').trim().replace(/\s/g,'').replace(',','.');return/^[+-]?\d+(?:\.\d+)?$/.test(compact)?Number(compact):null};
const answerMatches=(value:string,answer:string|string[])=>{const variants=Array.isArray(answer)?answer:[answer];return variants.some(item=>{const actual=numericValue(value);const expected=numericValue(item);if(actual!==null&&expected!==null)return actual===expected;return normalize(value)===normalize(item)})};

export const lessonEightyFourStages:LessonEightyFourStage[]=[
{id:'l84-mission',kind:'story',eyebrow:'Урок 84 · § 23 · итоговое обобщение',title:'Объём: масштаб, модели и реальные задачи',body:'Финальный урок §23 собирает всё вместе: каркас параллелепипеда, масштабирование площади и объёма, согласование единиц, объём с пересекающимися отверстиями и практическую задачу про расход материала.',note:'Технологическая карта урока 84: устно №3, с.156; контроль и коррекция — рабочая тетрадь №154, 157; обобщение — №635, 636, 638, 639, 640; рабочая тетрадь №293–295; повторение №643(5,6); домашнее — §23, №637 и дидактические №153, 155.',visual:'mission'},
{id:'l84-oral3-model',kind:'guided',eyebrow:'Актуализация · устно №3, с.156',title:'Каркас состоит из 12 рёбер',body:'У прямоугольного параллелепипеда по четыре ребра каждой длины. При размерах 3 см, 5 см и 6 см длина проволоки равна 4·(3+5+6).',visual:'box',sourceExercise:'Устно №3, с.156'},
{id:'l84-oral3-sum',kind:'practice',eyebrow:'Устно №3 · шаг 1',title:'Сложи три разных измерения',body:'Одно ребро каждого направления даёт сумму 3+5+6.',activity:{id:'l84-p1',type:'input',prompt:'3+5+6 = ?',answer:'14',placeholder:'см',hint:'3+5=8; 8+6=14.',explanation:'Сумма трёх измерений равна 14 см.'},visual:'verify',sourceExercise:'Устно №3, с.156'},
{id:'l84-oral3-wire',kind:'practice',eyebrow:'Устно №3 · ответ',title:'Учти четыре набора рёбер',body:'Каждое из трёх измерений встречается в каркасе четыре раза.',activity:{id:'l84-p2',type:'input',prompt:'4·14 = ? см проволоки',answer:'56',placeholder:'см',hint:'14+14+14+14.',explanation:'Для каркаса нужно 56 см проволоки.'},visual:'box',sourceExercise:'Устно №3, с.156'},
{id:'l84-formula-map',kind:'model',eyebrow:'§23 · карта знаний',title:'Четыре формулы, которые надо видеть сразу',body:'V=abc, V=Sh, для куба V=a³. Площадь поверхности куба Sпов=6a². При изменении размеров особенно важно различать линейный масштаб, масштаб площади и масштаб объёма.',visual:'formula',sourceExercise:'§23'},
{id:'l84-scale-rule',kind:'model',eyebrow:'Обобщение · масштаб',title:'Коэффициенты размеров перемножаются',body:'Если длину изменить в k₁ раз, ширину в k₂ раз, высоту в k₃ раз, то объём изменится в k₁·k₂·k₃ раз. Для куба при изменении ребра в k раз поверхность меняется в k², а объём — в k³.',visual:'formula',sourceExercise:'§23'},
{id:'l84-635-area',kind:'practice',eyebrow:'№635 · площадь поверхности',title:'Ребро куба увеличили в 4 раза',body:'Площадь одной грани пропорциональна квадрату ребра; число граней остаётся тем же.',activity:{id:'l84-p3',type:'input',prompt:'4² = ? Во сколько раз возрастёт площадь поверхности?',answer:'16',hint:'4·4.',explanation:'Площадь поверхности первого куба больше в 16 раз.'},visual:'cube',sourceExercise:'№635(1)'},
{id:'l84-635-volume',kind:'practice',eyebrow:'№635 · объём',title:'Теперь сравни объёмы',body:'Объём куба V=a³, поэтому коэффициент изменения ребра нужно возвести в третью степень.',activity:{id:'l84-p4',type:'input',prompt:'4³ = ? Во сколько раз возрастёт объём?',answer:'64',hint:'4·4·4.',explanation:'Объём первого куба больше в 64 раза.'},visual:'cube',sourceExercise:'№635(2)'},
{id:'l84-636-first-model',kind:'guided',eyebrow:'№636(1)',title:'Три измерения меняются по-разному',body:'Длину увеличили в 4 раза, ширину — в 2 раза, высоту — в 5 раз. Для объёма не нужно знать исходные размеры: достаточно перемножить коэффициенты.',visual:'formula',sourceExercise:'№636(1)'},
{id:'l84-636-first',kind:'practice',eyebrow:'№636(1) · ответ',title:'Произведение коэффициентов',body:'Коэффициент объёма равен 4·2·5.',activity:{id:'l84-p5',type:'input',prompt:'4·2·5 = ?',answer:'40',hint:'8·5.',explanation:'Объём увеличится в 40 раз.'},visual:'verify',sourceExercise:'№636(1)'},
{id:'l84-636-second-model',kind:'guided',eyebrow:'№636(2)',title:'Увеличение может компенсировать уменьшения',body:'Ширину уменьшили в 4 раза, высоту — в 2 раза, а длину увеличили в 16 раз. Общий коэффициент: 16:4:2.',visual:'formula',sourceExercise:'№636(2)'},
{id:'l84-636-second',kind:'practice',eyebrow:'№636(2) · ответ',title:'Сократи коэффициенты',body:'16:(4·2)=16:8.',activity:{id:'l84-p6',type:'input',prompt:'16:4:2 = ?',answer:'2',hint:'Сначала 16:4=4, затем 4:2=2.',explanation:'Объём увеличится в 2 раза.'},visual:'verify',sourceExercise:'№636(2)'},
{id:'l84-workbook-control',kind:'model',eyebrow:'Контроль и коррекция · source checkpoint',title:'Рабочая тетрадь №154 и 157',body:'Технологическая карта требует индивидуальную проверку по заданиям №154 и 157 рабочей тетради №1.',note:'Точные условия этой рабочей тетради не восстановлены в доступном источнике с достаточной надёжностью. Номера сохраняются как авторские checkpoints — приложение не подменяет их похожими задачами.',visual:'source',sourceExercise:'Рабочая тетрадь №154, 157'},
{id:'l84-units-model',kind:'model',eyebrow:'№638 · единицы',title:'Литры, гектары и глубина требуют общего языка',body:'Для формулы V=Sh объём и площадь должны быть выражены в согласованных единицах. Здесь удобно перейти к сантиметрам: 1 л=1000 см³, 1 га=10 000 м²=100 000 000 см².',visual:'units',sourceExercise:'№638'},
{id:'l84-638-volume',kind:'practice',eyebrow:'№638 · объём воды',title:'Переведи миллион литров',body:'Каждый литр занимает 1000 см³.',activity:{id:'l84-p7',type:'input',prompt:'1 000 000 л = ? см³',answer:'1000000000',placeholder:'см³',hint:'1 000 000·1000.',explanation:'Объём воды равен 1 000 000 000 см³.'},visual:'units',sourceExercise:'№638'},
{id:'l84-638-area',kind:'practice',eyebrow:'№638 · площадь дна',title:'Переведи гектар в квадратные сантиметры',body:'1 га=10 000 м², а 1 м²=10 000 см².',activity:{id:'l84-p8',type:'input',prompt:'1 га = ? см²',answer:'100000000',placeholder:'см²',hint:'10 000·10 000.',explanation:'Площадь дна равна 100 000 000 см².'},visual:'units',sourceExercise:'№638'},
{id:'l84-638-depth',kind:'practice',eyebrow:'№638 · глубина',title:'h=V:S',body:'Делим объём воды на площадь дна.',activity:{id:'l84-p9',type:'input',prompt:'1 000 000 000 : 100 000 000 = ? см',answer:'10',placeholder:'см',hint:'Сократи одинаковые нули.',explanation:'Глубина воды всего 10 см.'},visual:'inverse',sourceExercise:'№638'},
{id:'l84-638-decision',kind:'quiz',eyebrow:'№638 · вывод',title:'Можно ли проводить соревнования?',body:'Полученная глубина — 10 см. Это не бассейн с глубиной, пригодной для соревнований по плаванию.',activity:{id:'l84-p10',type:'choice',prompt:'Можно ли провести соревнования по плаванию?',options:['да','нет'],answer:'нет',hint:'Сравни 10 см с реальной глубиной для плавания.',explanation:'Нет. По методическому решению глубина воды 10 см, соревнования провести нельзя.'},visual:'verify',sourceExercise:'№638'},
{id:'l84-639-model',kind:'guided',eyebrow:'№639 · рис.182',title:'Куб с тремя пересекающимися отверстиями',body:'У куба ребро 3 см. В нём проделаны три сквозных квадратных отверстия со стороной 1 см — по трём взаимно перпендикулярным направлениям. Пересечение всех трёх отверстий — центральный куб 1×1×1.',visual:'cube',sourceExercise:'№639 · рис.182'},
{id:'l84-639-cube-volume',kind:'practice',eyebrow:'№639 · исходный куб',title:'Сначала объём целого',body:'V=3³.',activity:{id:'l84-p11',type:'input',prompt:'3³ = ? см³',answer:'27',placeholder:'см³',hint:'3·3·3.',explanation:'Исходный куб имеет объём 27 см³.'},visual:'cube',sourceExercise:'№639'},
{id:'l84-639-hole-volume',kind:'practice',eyebrow:'№639 · одно отверстие',title:'Каждый тоннель имеет объём 3 см³',body:'Сечение 1×1 см проходит через весь куб длиной 3 см.',activity:{id:'l84-p12',type:'input',prompt:'1·1·3 = ? см³',answer:'3',placeholder:'см³',hint:'Площадь сечения 1 см² умножь на длину 3 см.',explanation:'Объём одного отверстия равен 3 см³.'},visual:'box',sourceExercise:'№639'},
{id:'l84-639-overlap',kind:'model',eyebrow:'№639 · ключевая идея',title:'Нельзя просто вычесть 3+3+3',body:'Если сложить объёмы трёх отверстий, центральный куб 1 см³ будет учтён трижды, хотя удалить его нужно один раз. Поэтому из суммы 9 см³ надо вычесть два лишних учёта центрального куба.',note:'Методическое пособие даёт: 3+3+3−2=7 см³ удалённого объёма.',visual:'verify',sourceExercise:'№639'},
{id:'l84-639-removed',kind:'practice',eyebrow:'№639 · вырезанная часть',title:'Исправь тройной учёт пересечения',body:'Три отверстия дают 9 см³ до поправки; центральный 1 см³ посчитан на два раза больше нужного.',activity:{id:'l84-p13',type:'input',prompt:'3+3+3−2 = ? см³',answer:'7',placeholder:'см³',hint:'9−2.',explanation:'Вырезанная часть имеет объём 7 см³.'},visual:'verify',sourceExercise:'№639'},
{id:'l84-639-remaining',kind:'practice',eyebrow:'№639 · ответ',title:'Объём оставшейся части',body:'Из объёма целого куба вычитаем объединённый объём отверстий.',activity:{id:'l84-p14',type:'input',prompt:'27−7 = ? см³',answer:'20',placeholder:'см³',hint:'27−7.',explanation:'Осталось 20 см³.'},visual:'cube',sourceExercise:'№639'},
{id:'l84-640-model',kind:'guided',eyebrow:'№640',title:'Кусок мыла уменьшается по всем трём измерениям',body:'Исходные размеры 12×6×4 см. Через 14 дней каждый размер стал в 2 раза меньше: 6×3×2 см. Масса расходуется ежедневно одинаково, поэтому при одной плотности одинаков и расход объёма.',visual:'mass',sourceExercise:'№640'},
{id:'l84-640-initial',kind:'practice',eyebrow:'№640 · исходный объём',title:'12·6·4',body:'Вычислим, сколько объёма было сначала.',activity:{id:'l84-p15',type:'input',prompt:'12·6·4 = ? см³',answer:'288',placeholder:'см³',hint:'72·4.',explanation:'Исходный объём мыла 288 см³.'},visual:'box',sourceExercise:'№640'},
{id:'l84-640-remaining-model',kind:'model',eyebrow:'№640 · после 14 дней',title:'Половина каждого размера — не половина объёма',body:'После уменьшения размеров вдвое остаётся параллелепипед 6×3×2 см с объёмом 36 см³. Это 1/8 исходного объёма.',visual:'box',sourceExercise:'№640'},
{id:'l84-640-used',kind:'practice',eyebrow:'№640 · израсходовано',title:'Найди разность объёмов',body:'За 14 дней использовали 288−36 см³.',activity:{id:'l84-p16',type:'input',prompt:'288−36 = ? см³',answer:'252',placeholder:'см³',hint:'288−30−6.',explanation:'Израсходовано 252 см³.'},visual:'mass',sourceExercise:'№640'},
{id:'l84-640-daily',kind:'practice',eyebrow:'№640 · расход в день',title:'Одинаковый ежедневный расход',body:'252 см³ израсходовали за 14 дней.',activity:{id:'l84-p17',type:'input',prompt:'252:14 = ? см³ в день',answer:'18',placeholder:'см³/день',hint:'14·18=252.',explanation:'За день расходуется 18 см³ мыла.'},visual:'rate',sourceExercise:'№640'},
{id:'l84-640-days',kind:'practice',eyebrow:'№640 · ответ',title:'На сколько дней хватит остатка?',body:'Осталось 36 см³, расход — 18 см³ в день.',activity:{id:'l84-p18',type:'input',prompt:'36:18 = ? дня',answer:'2',placeholder:'дня',hint:'18·2=36.',explanation:'Оставшегося куска хватит на 2 дня.'},visual:'rate',sourceExercise:'№640'},
{id:'l84-640-scale',kind:'practice',eyebrow:'№640 · короткий путь',title:'Три уменьшения в 2 раза дают восьмикратное изменение объёма',body:'Коэффициент объёма равен 2·2·2.',activity:{id:'l84-p19',type:'input',prompt:'Во сколько раз исходный объём больше оставшегося?',answer:'8',hint:'Каждое из трёх измерений уменьшилось в 2 раза.',explanation:'Объём уменьшился в 8 раз; осталось 1/8 исходного.'},visual:'formula',sourceExercise:'№640'},
{id:'l84-workbook-generalization',kind:'model',eyebrow:'Обобщение · source checkpoint',title:'Рабочая тетрадь №293, 294, 295',body:'Технологическая карта включает индивидуальную практику №293–295 рабочей тетради №1.',note:'Полные условия не восстановлены надёжно, поэтому приложение фиксирует маршрут без реконструкции заданий.',visual:'source',sourceExercise:'Рабочая тетрадь №293, 294, 295'},
{id:'l84-643-source',kind:'model',eyebrow:'Повторение · №643(5,6) · source checkpoint',title:'Повторение остаётся привязанным к авторскому заданию',body:'По технологической карте в урок 84 входит №643(5,6).',note:'Точный текст подпунктов 5–6 используемой редакции не восстановлен из доступной выгрузки. Мы не придумываем замену и сохраняем номер как source checkpoint.',visual:'source',sourceExercise:'№643(5,6)'},
{id:'l84-homework-first',kind:'practice',eyebrow:'Домашнее · №637(1)',title:'Все три измерения увеличили в 2 раза',body:'Объём меняется по произведению трёх коэффициентов: 2·2·2.',activity:{id:'l84-p20',type:'input',prompt:'Во сколько раз увеличится объём?',answer:'8',hint:'2³=8.',explanation:'Объём увеличится в 8 раз.'},visual:'formula',sourceExercise:'№637(1)'},
{id:'l84-homework-second',kind:'practice',eyebrow:'Домашнее · №637(2)',title:'Компенсация изменений',body:'Длину уменьшают в 3 раза, высоту — в 5 раз, ширину увеличивают в 15 раз. Общий коэффициент 15:(3·5)=1.',activity:{id:'l84-p21',type:'choice',prompt:'Как изменится объём?',options:['увеличится в 15 раз','уменьшится в 15 раз','не изменится'],answer:'не изменится',hint:'15:(3·5)=15:15=1.',explanation:'Объём не изменится.'},visual:'verify',sourceExercise:'№637(2)'},
{id:'l84-summary',kind:'summary',eyebrow:'Итог урока 84 · §23 завершён',title:'Теперь объём — не формула, а система рассуждений',body:'Ты умеешь связывать V=abc и V=Sh с единицами, масштабом, поверхностью куба, пересекающимися частями и реальными условиями. №635–640 показывают, как одна тема работает в геометрии, физическом смысле и прикладных задачах.',note:'Обязательная практика: 20 задач / ровно 50 ответов. §23 полностью завершён. Урок 85 открывает §24 «Комбинаторные задачи» и остаётся закрытым до отдельного релиза.',visual:'final'}
];

function Visual({kind}:{kind:VisualKind}){const labels:Record<VisualKind,string>={mission:'V',formula:'k₁·k₂·k₃',inverse:'V:S',box:'a·b·c',cube:'a³',source:'§23',units:'↔',mass:'V→расход',rate:'V:t',verify:'✓',final:'84'};return <div className={`division-meaning-visual is-${kind}`} aria-hidden="true"><strong>{labels[kind]}</strong><span>{kind==='formula'?'следим за коэффициентами':kind==='inverse'?'находим неизвестный размер':kind==='units'?'согласуем единицы':kind==='mass'?'объём и расход материала':kind==='source'?'авторский источник без реконструкции':'итоговое обобщение объёма'}</span></div>}
function initialSaved():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw) as Saved;if(parsed?.version===1&&Number.isInteger(parsed.stageIndex))return{...parsed,stageIndex:Math.max(0,Math.min(parsed.stageIndex,lessonEightyFourStages.length-1))}}}catch{}return{version:1,stageIndex:0,responses:{},checked:{},results:{},attempts:{}}}
function stopNarration(){window.dispatchEvent(new CustomEvent('mathnikita-stop-narration'));if('speechSynthesis'in window)window.speechSynthesis.cancel()}
export function VolumeSynthesisPlayer(){const[saved,setSaved]=useState<Saved>(initialSaved);const stage=lessonEightyFourStages[saved.stageIndex];const activity=stage.activity;const response=activity?saved.responses[activity.id]??'':'';const wasChecked=activity?Boolean(saved.checked[activity.id]):false;const isCorrect=activity?Boolean(saved.results[activity.id]):false;const attempts=activity?saved.attempts[activity.id]??0:0;const canContinue=!activity||isCorrect||attempts>=2;const progress=useMemo(()=>Math.round(((saved.stageIndex+1)/lessonEightyFourStages.length)*100),[saved.stageIndex]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<StageJumpDetail>).detail;if(detail?.lessonNumber!==84||typeof detail.stageIndex!=='number')return;stopNarration();setSaved(previous=>({...previous,stageIndex:Math.max(0,Math.min(Math.trunc(detail.stageIndex!),lessonEightyFourStages.length-1))}))};window.addEventListener('mathnikita-go-to-stage',handler);return()=>window.removeEventListener('mathnikita-go-to-stage',handler)},[]);
 function setResponse(value:string){if(!activity)return;setSaved(previous=>({...previous,responses:{...previous.responses,[activity.id]:value},checked:{...previous.checked,[activity.id]:false},results:{...previous.results,[activity.id]:false}}))}
 function check(){if(!activity||!response)return;const correct=answerMatches(response,activity.answer);setSaved(previous=>({...previous,checked:{...previous.checked,[activity.id]:true},results:{...previous.results,[activity.id]:correct},attempts:{...previous.attempts,[activity.id]:(previous.attempts[activity.id]??0)+1}}))}
 function next(){if(saved.stageIndex>=lessonEightyFourStages.length-1||!canContinue)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex+1}))}
 function previous(){if(saved.stageIndex===0)return;stopNarration();setSaved(previous=>({...previous,stageIndex:previous.stageIndex-1}))}
 return <section className="lesson-player division-meaning-player volume-synthesis-player" data-lesson-number="84" data-source-reference="Мерзляк § 23 · технологическая карта урока 84 · устно №3 · №635, 636, 638, 639, 640 · повторение №643(5,6)" data-source-exercise-range="635,636,638,639,640,643(5,6)"><article className={['interactive-stage',stage.kind==='summary'?'stage-summary':''].filter(Boolean).join(' ')} data-stage-id={stage.id} data-source-exercise={stage.sourceExercise}><div className="stage-copy"><span className="stage-eyebrow">{stage.eyebrow}</span><h2>{stage.title}</h2><p>{stage.body}</p>{stage.note?<p className="theory-note">{stage.note}</p>:null}</div>{stage.visual?<Visual kind={stage.visual}/>:null}{activity?<div className="activity-area"><h3>{activity.prompt}</h3>{activity.type==='choice'?<div className="choice-grid">{activity.options?.map(option=><button key={option} type="button" className={response===option?'selected':''} onClick={()=>setResponse(option)}>{option}</button>)}</div>:<label className="inline-answer"><span>Ответ</span><input value={response} placeholder={activity.placeholder??'Введите ответ'} onChange={event=>setResponse(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')check()}}/></label>}<button type="button" className="check-button" disabled={!response} onClick={check}>Проверить</button>{wasChecked?<div className={`instant-feedback ${isCorrect?'good':'bad'}`} data-explanation={activity.explanation}><strong>{isCorrect?'Верно':'Проверь ещё раз'}</strong><span>{isCorrect?activity.explanation:attempts>=2?activity.explanation:activity.hint}</span></div>:null}</div>:null}<div className="lesson-controls"><button type="button" onClick={previous} disabled={saved.stageIndex===0}>← Назад</button><span>Этап {saved.stageIndex+1} из {lessonEightyFourStages.length} · {progress}%</span><button type="button" className="primary" onClick={next} disabled={saved.stageIndex>=lessonEightyFourStages.length-1||!canContinue}>Дальше →</button></div></article></section>}
